= Key-Value Containers

`KeyValueContainer` and `KeyValueCollectionContainer` are designed to work with xref:data-model:entities.adoc#key-value[key-value entities]. Such entities can contain an arbitrary number of attributes that are defined at runtime.

`KeyValueContainer` and `KeyValueCollectionContainer` can be defined in a screen XML descriptor using `keyValueInstance` and `keyValueCollection` elements.

XML definition of a key-value container must include the `properties` element that defines the `KeyValueEntity` attributes (actually, keys and their types). The order of nested property elements should conform to the order of result set columns returned by the query. For example, in the following definition the `customer` attribute will get its value from `o.customer` column and the `sum` attribute from `sum(o.amount)` column:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/data/order-browse-data.xml[tags=key-value-container]
----

Besides, you can configure key-value containers using their Java API which includes the following methods:

* `addProperty()` - allows you to define the entity attributes (keys). The method accepts a name of the attribute and its type in the form of a xref:data-model:data-types.adoc[Datatype] or a Java class. In the latter case, the class should be either an entity class or a class supported by one of the datatypes. This method is used by the framework under the hood when you define properties of the key-value container declartively in XML as explained above.

* `setIdName()` is an optional method that allows you to define one of the attributes as an identifier attribute of the entity. It means that `KeyValueEntity` instances stored in this container will have identifiers obtained from the given attribute. Otherwise, `KeyValueEntity` instances get randomly generated UUIDs.

* `getEntityMetaClass()` returns a dynamic implementation of the xref:data-model:metadata.adoc[MetaClass] interface that represents the current schema of `KeyValueEntity` instances. It is determined by previous calls to `addProperty()`.
