= Начало работы с тестированием

По умолчанию каждый проект Jmix уже содержит структуру каталогов для автоматизированных тестов и два класса тестов в каталоге `src/test/java/<base-package>/user`:

. `UserTest.java` - интеграционный тест для сущности `User`.
. `UserUiTest.java` - интеграционный тест UI для экранов управления пользователями.

`UserTest` сохраняет сущность `User` через API Jmix xref:data-access:data-manager.adoc[DataManager].
Затем тест проверяет, что при загрузке пользователя по его имени пользователь найден и соответствует изначально сохраненному пользователю.

[source, java]
.UserTest.java
----
include::example$testing-ex1/src/test/java/com/company/demo/user/UserTest.java[]
----

<1> Аннотация `@SpringBootTest` указывает, что во время выполнения теста запускается контекст Spring.
<2> `AuthenticatedAsAdmin` позволяет тесту взаимодействовать с системой и базой данных от имени пользователя `admin`.
<3> Зависимости инжектированы в тестовый код используя аннотацию Spring `@Autowired`.
<4> Каждый тест-кейс помечен аннотацией JUnit `@Test`.
<5> Для выполнения проверок используется библиотека https://assertj.github.io/doc/[AssertJ^], автоматически доступная в проектах Jmix.
<6> Такие операции как очистка базы данных, выполняются в методах завершения, помеченных аннотацией JUnit `@AfterEach`.

Сам тест является обычным интеграционным тестом Spring Boot. Он запускает полный контекст Spring и взаимодействует с реальной базой данных.

NOTE: По умолчанию тесты используют ту же базу данных, что и приложение при локальном выполнении.

Jmix Studio использует возможности IntelliJ IDEA для выполнения тестов. Когда вы открываете класс `UserTest.java` в Jmix Studio, вы можете запустить тест-кейсы, щелкнув на кнопку воспроизведения на строке класса теста. Среда разработки покажет результат выполнения теста и успешен он или нет.

Более подробную информацию о том, как выполнять тесты, см. в https://www.jetbrains.com/help/idea/performing-tests.html[документации IntelliJ^].

Следующие разделы подробно объясняют различные типы тестов.
