= UI 集成测试

Jmix 支持为 UI 层编写测试。在这些测试中，可以打开视图、加载数据、验证 UI 组件的内容、修改组件内容以及模拟用户操作（例如，点击按钮）。

TIP: 使用 Studio *Jmix* 工具窗口的 *New → Advanced → UI Integration Test* 操作可以快速创建一个 UI 集成测试。

Jmix UI 测试会启动完整的 Spring 上下文，并且可以像业务逻辑的 xref:integration-tests.adoc[集成测试] 一样与数据库进行交互。从某种意义上说，Jmix UI 的集成测试更接近基于浏览器的端到端测试，因为可以测试应用程序的各种功能，但更加易于设置，执行速度也比基于浏览器的测试快得多。

每个新建的 Jmix 项目都包含一个 UI 集成测试的示例：'UserUiTest' 类，用于测试用户管理视图。我们通过此示例了解一下 UI 测试的配置和逻辑。

如需执行 UI 测试，项目需要依赖 `jmix-flowui-test-assist` 模块：

.build.gradle
[source,java,indent=0]
----
include::example$/testing-ex1/build.gradle[tag=dependency]
----

测试类示例如下：

.UserUiTest.java
[source,java,indent=0]
----
include::example$/testing-ex1/src/test/java/com/company/demo/user/UserUiTest.java[]
----
<1> `@UiTest` 注解定义了一个 JUnit 扩展，用于启动 Vaadin、配置应用程序视图以及配置用户认证。
<2> `@SpringBootTest` 注解需要声明应用程序和 `jmix-flowui-test-assist` 模块的配置。
<3> 可以用 `@Autowired` 注解注入 Spring bean。
<4> 测试用例的方法。
<5> `UiTestUtils.getCurrentView()` 返回导航当前打开的视图。
<6> `findComponent()` 可以按 ID 查找 UI 组件。
<7> 每个测试用例后执行该方法清理测试数据。
