= Интеграционные тесты UI

Jmix позволяет писать тесты для слоя пользовательского интерфейса. В этих тестах вы можете открывать экраны, загружать данные, проверять содержимое компонентов UI, вносить изменения и моделировать действия пользователя, такие как нажатия кнопок.

TIP: Используйте действие *New → Advanced → UI Integration Test* в окне инструментов *Jmix*, чтобы быстро создать интеграционный тест UI с помощью Studio.

Тесты пользовательского интерфейса Jmix запускают полный контекст Spring и могут взаимодействовать с базой данных, подобно xref:integration-tests.adoc[интеграционным тестам] бизнес-логики. Они близки к end-to-end тестам, основанным на управлении браузером с помощью Selenium WebDriver, в том что они могут проверять широкий спектр функциональности приложения, но в то же время их легко настроить, и выполняются они намного быстрее.

В каждом новом проекте Jmix включен пример интеграционного теста UI: класс `UserUiTest`, который проверяет экраны управления пользователями. Давайте рассмотрим конфигурацию и логику тестов пользовательского интерфейса, используя этот пример.

Для выполнения тестов UI проект должен содержать зависимость от модуля `jmix-flowui-test-assist`:

.build.gradle
[source,java,indent=0]
----
include::example$/testing-ex1/build.gradle[tag=dependency]
----

Класс теста приведен ниже.

.UserUiTest.java
[source,java,indent=0]
----
include::example$/testing-ex1/src/test/java/com/company/demo/user/UserUiTest.java[]
----
<1> Аннотация `@UiTest` определяет расширение JUnit для запуска Vaadin, настройки экранов приложения и установки аутентификации.
<2> Аннотация `@SpringBootTest` должна объявить конфигурации приложения и модуля `jmix-flowui-test-assist`.
<3> Вы можете внедрять любые бины Spring, используя аннотацию `@Autowired`.
<4> Метод тест-кейса.
<5> Метод `UiTestUtils.getCurrentView()` возвращает экран, в настоящее время открытый через навигацию.
<6> Метод `findComponent()` возвращает компонент UI по его идентификатору.
<7> Метод, выполняемый после каждого тест-кейса, может использоваться для очистки тестовых данных.

[[opened-dialog-view]]
== Получение экрана, открытого в окне диалога

Метод `UiTestUtils.getCurrentView()` возвращает экран, открытый с помощью навигации. Если действие открывает экран в окне диалога, например, с помощью `OpenMode.DIALOG`, используйте `DialogWindows.getOpenedDialogWindows()`.

В следующем примере тест нажимает кнопку создания заказа и получает экран деталей, открытый в окне диалога:

[source,java,indent=0]
----
include::example$/testing-ex1/src/test/java/com/company/demo/customer/CustomerDialogUiTest.java[tags=viewNavigators;dialogWindows;test-1]
----

Метод `getDialogs()` возвращает экраны-диалоги текущего UI. Чтобы получить диалоги конкретного UI, используйте `getDialogs(UI)`. Экраны добавляются в список в порядке их открытия, поэтому последний открытый диалог является последним элементом в списке.

Для получения дополнительной информации об API окон диалогов см. xref:flow-ui:views/opening-views.adoc#opened-dialog-windows[Получение открытых диалоговых окон].