= Quartz

This add-on allows you to manage https://www.quartz-scheduler.org/[Quartz^] jobs via user interface:

* Create new Quartz jobs from the existing implementation of `org.quartz.Job` interface.
* Pause and resume jobs execution.
* Trigger immediate execution of inactive jobs.
* Edit job triggers and parameters.
* Delete jobs.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.quartz:jmix-quartz-starter'
----

[[usage]]
== Usage

To create and schedule a job for execution, do the following:

. Create a class implementing the `org.quartz.Job` interface. It's `execute()` method will be invoked by the scheduler.

. Run the application, open *Administration -> Quartz jobs* screen, click *Create* and find your job class in the *Class* field. After that, create triggers for the job.

