= Protecting Resources

The {oauth-specification-page}#section-1.1[resource server] security is defined in the auto-configuration of the Authorization Server add-on. This configuration provides extension points that can be used to define any URL pattern as protected.

[[defining-protected-resources]]
== Defining Protected Resources

Suppose that you have the following REST controller:

[source,java,indent=0]
----
include::example$/authserver-ex1/src/main/java/com/company/demo/controller/GreetingController.java[tags=whole-class]
----

To make `pass:[/greeting/**]` endpoints protected with the access token you should define a bean that implements the `io.jmix.core.security.AuthorizedUrlsProvider` interface and return a list of URL patterns from its `getAuthenticatedUrlPatterns()` method:

[source,java,indent=0]
----
include::example$/authserver-ex1/src/main/java/com/company/demo/security/api/GreetingAuthorizedUrlsProvider.java[tags=whole-class]
----

[[sendiong-access-token]]
== Sending Access Token

After the above configuration is defined, all requests to `pass:[/greeting/**]` endpoints will need an access token in the `Authorization` header. The header value must contain the word `Bearer` followed by the access token value. For example:

[source]
----
GET /greeting/hello HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----

[[protecting-rest-api-endpoints]]
== Protecting Generic REST Add-on Endpoints

When you add the xref:rest:index.adoc[Generic REST] add-on to the application, all REST endpoints become automatically protected by the Authorization Server add-on. This means that to access REST endpoints you need to obtain an access token and pass it in the `Authorization` header of the HTTP request. The header value must contain the word `Bearer` followed by the access token value. For example:

[source]
----
GET /rest/entities/User HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----