= Report Spreadsheet

The Report Spreadsheet add-on connects the xref:reports:index.adoc[] add-on with the xref:vaadin-spreadsheet:index.adoc[] component, so that the XLS and XLSX output of a report opens in an interactive spreadsheet in the browser instead of being downloaded as a file. Users review the generated document, edit it, and download the edited version in its original format.

The add-on provides the following features:

* The *Run and open in spreadsheet* action next to the usual run action in the reports views.
* A spreadsheet viewer shown as a dialog or as a full page.
* Editing of the generated document before it is downloaded.
* A choice of only those templates and output types that the viewer can render.
* A programmatic API for opening a report in the viewer from your own code.

[[installation]]
== Installation

[NOTE]
====
This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial] section for how to get a trial version.

It also builds on two other add-ons, and both must be present in the project:

* xref:reports:index.adoc[]
* xref:vaadin-spreadsheet:index.adoc[]
====

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies of both add-ons to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.vcc:vaadin-spreadsheet-starter'
implementation 'io.jmix.reportsspreadsheet:jmix-reports-spreadsheet-flowui-starter'
----

[[configuration]]
== Configuration

By default, generated XLS and XLSX reports are opened in the spreadsheet viewer as a modal dialog. To open the viewer as a full page, set the xref:reports:configuration.adoc#jmix.reports.spreadsheet.output-open-mode[jmix.reports.spreadsheet.output-open-mode] application property to `NAVIGATION`.