= Entity Information Action

The Data Tools add-on provides a UI xref:ui:actions.adoc[action] that displays a system information about a selected entity. It includes the entity name, Java class, database table, identifier, and values of system attributes that constitute the entity xref:data-model:entities.adoc#traits[traits].

To add the action to a table or data grid using Studio, open the xref:studio:screen-designer.adoc#component-palette[component palette], drag and drop *Facets* -> *Action* to the component, and select `showEntityInfo` in the *Add Action* dialog. The action will be added to the table, for example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/datatools/ex1/screen/order/order-browse.xml[tags=entity-info]
----

After adding the action to a table or data grid, you can find it in the component's context menu as *Entity information* item.

NOTE: To be able to use the action, a user must have the `datatools-entity-info` resource role provided by the add-on.