= Configuration

Before you start working with the xref:dashboards:user-interface.adoc#dashboard-editor[Dashboard editor] and create dashboards, you should extend an application theme and add widgets.

[[extending-theme]]
== Extending Theme

The Dashboards add-on uses additional styles for the components, so it is required to use a custom theme in the project instead of the compiled theme.

If a custom theme is not used in the project, follow the instructions in the xref:jmix-ui:themes/custom_theme.adoc[Themes] section to create a new one.

After the theme is added and configured, add the following dependency to the `build.gradle` file:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dboards-dep1;dboards-ui;dboards-dep2]
----

////
NOTE: When a custom theme is used, it is required to remove the following dependency:

[source,groovy,indent=0]
----
implementation 'io.jmix.ui:jmix-ui-themes-compiled'
----
////

[[adding-widgets]]
== Adding Widgets

By default, the add-on does not have preset widgets. To create a widget, do the following:

1. Create a new xref:jmix-ui:using-fragments.adoc[fragment] using Studio interface. In the xref:studio:tool-window.adoc#creating-new-elements[Jmix Tool Window], go to *New -> Screen* and select *Screen Fragment* template. Set the names of the descriptor and controller.
2. In the screen controller, add the `@DashboardWidget` annotation. 
+
* Fill in the `name` parameter. It will be displayed in the xref:dashboards:user-interface.adoc#dashboard-editor[Dashboard editor]. 
* In case you are going to use a xref:dashboards:user-interface.adoc#custom-widget-editor[custom widget editor], fill in `editFragmentId` - id of the fragment for editing a widget.

Here is an example of a simple widget that displays a company logo:

.LogoWidget.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/dashboards/ex1/screen/widgets/LogoWidget.java[tags=logo-widget]
----

.logo-widget.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/dashboards/ex1/screen/widgets/logo-widget.xml[tags=logo-widget]
----

[[updatable-widget]]
=== Updatable Widget

The `RefreshableWidget` interface allows refreshing a widget from time to time. If the widget implements the `RefreshableWidget` interface, the `refresh()` method  will be invoked automatically on every dashboard update event.

In the example below, the widget displays a random joke. The refresh period is set in the xref:dashboards:user-interface.adoc#info-panel[Dashboard editor] while creating a dashboard.

.RandomJokeWidget.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/dashboards/ex1/screen/widgets/RandomJokeWidget.java[tags=joke-widget]
----

=== Widget Parameters

You should add the `@WindowParam` and `@WidgetParam` annotations to the class field that you want to use as a widget parameter.

The add-on provides the xref:dashboards:user-interface.adoc#widget-parameter[Parameter editor] dialog that allows creating parameters and passing them to your widget. 

Let's look at the example of how to access parameters in code. The widget shows the picture that is kept in one of the fields:

.ArtWidget.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/dashboards/ex1/screen/widgets/ArtWidget.java[tags=widget]
----
<1> A constant containing a value of the `name` field of an entity. It will be used in case a parameter is not set in a widget.
<2> Injects an instance container that holds an entity with a picture.
<3> A class field of the `Pet` type. It should have the same name as the `alias` field in the parameter editor.
<4> Injects a widget itself to set a new caption for it.
<5> In case the parameter is not set, the entity with the name specified in the constant will be used.
<6> Puts the entity in the instance container.
<7> Sets the caption of the widget.

A screen controller of a widget can look like this:

.art-widget.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/dashboards/ex1/screen/widgets/art-widget.xml[tags=widget]
----

[[predefined-roles]]
== Predefined Roles

The add-on provides the following predefined roles:

* `dashboards-admin` - allows users to create and edit dashboards and widget templates.
* `dashboards-view` - allows users to view embedded dashboards.
* `dashboards-browse` - allows users to view a list of available dashboards.
