= 配置

在使用 xref:dashboards:user-interface.adoc#dashboard-editor[仪表盘编辑器] 创建仪表盘之前，需要扩展一个应用程序主题并添加小部件。

[[extending-theme]]
== 扩展主题

仪表盘扩展组件使用组件的附加样式，因此需要使用项目的自定义主题而非预定义主题。

如果项目未使用自定义主题，按照 xref:ui:themes/custom_theme.adoc[主题] 章节的说明新建一个。

在主题创建和配置好之后，在 `build.gradle` 文件添加下列依赖：

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dboards-dep1;dboards-ui;dboards-dep2]
----

////
NOTE: When a custom theme is used, it is required to remove the following dependency:

[source,groovy,indent=0]
----
implementation 'io.jmix.ui:jmix-ui-themes-compiled'
----
////

[[adding-widgets]]
== 添加小部件

默认情况下，该扩展组件没有预设的小部件。按照下列步骤创建小部件：

1. 使用 Studio 创建一个新 xref:ui:using-fragments.adoc[fragment]。在 xref:studio:tool-window.adoc#creating-new-elements[Jmix 工具窗口中]，点击 *New -> Screen*，然后选择 *Screen Fragment* 模板。设置界面描述和控制器的名称。
2. 在界面控制器中，添加 `@DashboardWidget` 注解。
+
* 填写 `name` 参数。名称将在 xref:dashboards:user-interface.adoc#dashboard-editor[仪表盘编辑器] 展示。
* 如需使用 xref:dashboards:user-interface.adoc#custom-widget-editor[自定义小部件编辑器]，填写 `editFragmentId`，编辑小部件时的 fragment id。

下面是一个展示公司 logo 的简单小部件：

.LogoWidget.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/dashboards/ex1/screen/widgets/LogoWidget.java[tags=logo-widget]
----

.logo-widget.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/dashboards/ex1/screen/widgets/logo-widget.xml[tags=logo-widget]
----

[[updatable-widget]]
=== 小部件更新

`RefreshableWidget` 接口支持对一个小部件进行不定时刷新。如果小部件实现了 `RefreshableWidget` 接口，在每次仪表盘更新事件触发时，都会调用其 `refresh()` 方法。

下面示例中，小部件展示一个随机的小笑话。刷新频率在创建仪表盘时，使用 xref:dashboards:user-interface.adoc#info-panel[仪表盘编辑器] 设置。

.RandomJokeWidget.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/dashboards/ex1/screen/widgets/RandomJokeWidget.java[tags=joke-widget]
----

=== 小部件参数

如果希望类成员变量作为小部件参数使用，需要为其添加 `@WindowParam` 和 `@WidgetParam` 注解。

扩展插件提供 xref:dashboards:user-interface.adoc#widget-parameter[参数编辑器] 对话框，支持创建参数并传递给小部件。

我们看看如何在代码中访问参数。下面的小部件展示一个图片，图片保存在一个类成员变量中：

.ArtWidget.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/dashboards/ex1/screen/widgets/ArtWidget.java[tags=widget]
----
<1> 包含实体 `name` 字段的常量。没有为小部件设置参数时，默认使用该值。
<2> 注入实体实例数据容器，容器中包含一个带有图片属性的实体。
<3> `Pet` 类型的类成员变量。其名称需要与参数编辑器中的 `alias` 字段相同。
<4> 注入小部件本身，为其设置新标题。
<5> 如果参数未设置，则使用 `name` 等于常量的实体。
<6> 将实体放入实例容器中。
<7> 设置小部件的标题。

小部件的界面描述可以是这样：

.art-widget.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/dashboards/ex1/screen/widgets/art-widget.xml[tags=widget]
----

[[predefined-roles]]
== 预定义角色

该扩展组件提供下列预定义角色：

* `dashboards-admin` - 允许用户创建和编辑仪表盘和小部件模板。
* `dashboards-view` - 允许用户查看嵌入的仪表盘。
* `dashboards-browse` - 允许用户查看可用的仪表盘列表。
