= 仪表盘

该扩展组件支持用户创建仪表盘并将仪表盘嵌入应用程序界面。可用于查看统计信息、数据集、图表的可视化展示。

仪表盘由小部件组成，小部件是基于界面 fragment 的独立元素。集成了一些布局，支持根据需要调整仪表盘上的小部件位置。

组件提供下列功能：

* 针对用户设置仪表盘的可见性
* 使用响应式布局使仪表盘的展示能适应不同设备
* 创建并分类管理小部件模板
* 用于配置和管理仪表盘及小部件的用户界面

//Also, you can add chart widgets based on data from reports using Dashboard Chart Add-on.

[[installation]]
== 安装

按照 xref:ROOT:add-ons.adoc[扩展组件] 章节的说明进行安装。

在项目中使用时，需要扩展已有主题并创建小部件。参阅 xref:dashboards:config.adoc[配置] 章节。

////
=== Manual Installation

. Add the following dependencies to your `build.gradle` file:
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dboards-dep1;dboards-impl;dboards-dep2]
----
+
Also, remove `implementation 'io.jmix.ui:jmix-ui-widgets-compiled'` dependency because it is not needed.

. Add the `compileWidgets` task to your `build.gradle` file and specify an arbitrary widgetset name matching the `<base-package>.widgets.<name>` pattern, 示例：
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dboards-compile-widgets]
----

. Add the `jmix.ui.widgetSet` property to your `application.properties` file and set the compiled widgetset name in it, 示例：
+
[source,properties]
----
include::example$/ex1/src/main/resources/application.properties[tags=dboards-widgetset]
----
////
