= Dashboards

The add-on enables users to create and embed dashboards into application screens. Dashboards allow visualizing summarized information, data sets, or charts.

A dashboard consists of widgets — individual elements based on a frame. An integrated set of layouts allows positioning widgets on a dashboard according to your needs. 

The add-on provides the following features:

* Setting dashboard visibility for different users.
* Responsive layouts that help to adapt dashboards to different displays. 
* Creating and storing widget templates.
* User interface for configuring and managing dashboards and widgets.

//Also, you can add chart widgets based on data from reports using Dashboard Chart Add-on.

[[installation]]
== Installation

Follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section to install the add-on into your application.

To start using the add-on in your project, you need to extend the existing theme and create widgets. See the xref:dashboards:config.adoc[Configuration] section.

////
=== Manual Installation

. Add the following dependencies to your `build.gradle` file:
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dboards-dep1;dboards-impl;dboards-dep2]
----
+
Also, remove `implementation 'io.jmix.ui:jmix-ui-widgets-compiled'` dependency because it is not needed.

. Add the `compileWidgets` task to your `build.gradle` file and specify an arbitrary widgetset name matching the `<base-package>.widgets.<name>` pattern, for example:
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dboards-compile-widgets]
----

. Add the `jmix.ui.widgetSet` property to your `application.properties` file and set the compiled widgetset name in it, for example:
+
[source,properties]
----
include::example$/ex1/src/main/resources/application.properties[tags=dboards-widgetset]
----
////
