= Bulk Editor

This add-on is designed to allow users to change attribute values for multiple entity instances at once.

It provides an xref:flow-ui:actions.adoc[action] that opens a dialog where the user can enter attribute values. After that, the action updates the selected entities in the data store and in the UI.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependency to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.bulkeditor:jmix-bulkeditor-starter'
----

[[usage]]
== Usage

The type of action provided by the add-on is `bulked_edit`. It is a xref:flow-ui:actions/list-actions.adoc[list component action], so it can be added to xref:flow-ui:vc/components/dataGrid.adoc[] and xref:flow-ui:vc/components/treeDataGrid.adoc[].

Usage example:

[source,xml]
----
<hbox id="buttonsPanel" classNames="buttons-panel">
    <!-- ... -->
    <button action="booksDataGrid.bulkEdit"/>
</hbox>
<dataGrid id="booksDataGrid" dataContainer="booksDc" columnReorderingAllowed="true"
            selectionMode="MULTI">
    <actions>
        <!-- ... -->
        <action id="bulkEdit" type="bulked_edit"/>
    </actions>
----

To be able to select mulitple entities, set `selectionMode="MULTI"` for `dataGrid`.
