= Bulk Editor

Дополнение Bulk Editor (массовый редактор) предоставляет пользователям приложений возможность изменять значения атрибутов для нескольких экземпляров сущности одновременно.

Дополнение содержит xref:flow-ui:actions.adoc[действие], которое открывает диалоговое окно, в котором пользователь может ввести значения атрибутов. После этого действие обновляет выбранные сущности в хранилище данных и в пользовательском интерфейсе.

[[installation]]
== Установка

Для автоматической установки через маркетплейс Jmix следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующую зависимость в `build.gradle` проекта:

[source,groovy,indent=0]
----
implementation('io.jmix.bulkeditor:jmix-bulkeditor-starter')
----

[[usage]]
== Использование

Тип действия, предоставляемого дополнением - `bulked_edit`. Это xref:flow-ui:actions/list-actions.adoc[действие компонентов списка], поэтому его можно добавить в xref:flow-ui:vc/components/dataGrid.adoc[] и xref:flow-ui:vc/components/treeDataGrid.adoc[].

Пример использования:

[source,xml]
----
<hbox id="buttonsPanel" classNames="buttons-panel">
    <!-- ... -->
    <button action="booksDataGrid.bulkEdit"/>
</hbox>
<dataGrid id="booksDataGrid" dataContainer="booksDc" columnReorderingAllowed="true"
            selectionMode="MULTI">
    <actions>
        <!-- ... -->
        <action id="bulkEdit" type="bulked_edit"/>
    </actions>
----

Чтобы иметь возможность выбирать несколько сущностей, установите `selectionMode="MULTI"` для `dataGrid`.