
[[security-properties]]
== Security

TIP: https://doc.cuba-platform.com/restapi-7.2/#rest_api_v2_settings
(only security-relevant parts)

[[jmix.rest.client.id]]
=== jmix.rest.client.id

Defines an identifier of the REST API client. In this case, the client is not a platform user, but an application (some web portal or mobile app) that uses REST API. Client credentials are used for basic authentication when accessing the REST API token endpoint.

Default value: `client`

CAUTION: This value should be changed to some application specific random, long and non-guessable string.


[[jmix.rest.client.secret]]
=== jmix.rest.client.secret

Defines the secret for the REST API client. In this case, the client is not a platform user, but an application (some web portal or mobile app) that uses REST API. Client credentials are used for basic authentication when accessing the REST API token endpoint.

The application property value in addition to the actual password value (e.g., `secret`), must contain an identifier of the Password Encoder (e.g., `\{noop\}`). More information about the Password Encoder Mechanism can be found in the https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/DelegatingPasswordEncoder.html[Spring Security documentation].

NOTE: When the Token retrieval request is send for authentication, the Password Encoder identifier must not be part of the request value. Only `secret` is part of the request.


Default value: `\{noop\}secret`


CAUTION: This value should be changed to some application specific random, long and non-guessable string.

[[jmix.rest.anonymousUrlPatterns]]
=== jmix.rest.anonymousUrlPatterns

Defines a list of https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[URL patterns], which should allow anonymous access.

Default value: `none`

[[jmix.rest.allowedOrigins]]
=== jmix.rest.allowedOrigins

Defines a comma-separated list of origins (like `https://www.example.com`) that can access the REST API.

Example: `https://www.allowed1.com, https://www.allowed2.com`

Default value: `*`
