
[[security-properties]]
== Security

[[jmix.security.oauth2.client-id]]
=== jmix.security.oauth2.client-id

Defines an identifier of the REST API client. In this case, the client is not a platform user, but an application (some web portal or mobile app) that uses REST API. Client credentials are used for basic authentication when accessing the REST API token endpoint.

Default value: `client`

CAUTION: This value should be changed to some application specific random, long and non-guessable string.


[[jmix.security.oauth2.client-secret]]
=== jmix.security.oauth2.client-secret

Defines the secret for the REST API client. In this case, the client is not a platform user, but an application (some web portal or mobile app) that uses REST API. Client credentials are used for basic authentication when accessing the REST API token endpoint.

The application property value in addition to the actual password value (e.g., `secret`), must contain an identifier of the Password Encoder (e.g., `\{noop\}`). More information about the Password Encoder Mechanism can be found in the https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/DelegatingPasswordEncoder.html[Spring Security documentation^].

NOTE: When the Token retrieval request is send for authentication, the Password Encoder identifier must not be part of the request value. Only `secret` is part of the request.


Default value: `\{noop\}secret`


CAUTION: This value should be changed to some application specific random, long and non-guessable string.

[[jmix.rest.anonymous-url-patterns]]
=== jmix.rest.anonymous-url-patterns

Defines a comma-separated list of URL https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[patterns^], which should allow xref:rest:security/authentication.adoc#anonymous-access[anonymous access].

Default value: `none`

[[jmix.rest.allowed-origins]]
=== jmix.rest.allowed-origins

Defines a comma-separated list of origins (like `++https://www.example.com++`) that can access the REST API.

Example: `https://www.allowed1.com, https://www.allowed2.com`

Default value: `*`

[[jmix.rest.authenticated-url-patterns]]
=== jmix.rest.authenticated-url-patterns

Defines a comma-separated list of URL https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[patterns^] of xref:rest:business-logic.adoc#custom-controller[custom controllers] that require the standard OAuth2 authentication.

Default value: `none`
