= Перечисления

Перечисление – это набор констант, которые можно использовать в качестве значений атрибута сущности.

В Jmix перечисление – это тип Java _enum_, который реализует интерфейс `EnumClass` и имеет поле `id` типа `Integer` или `String`. Это поле хранится в базе данных вместо `ordinal()` или `name()` константы перечисления, что имеет следующие преимущества:

* Вы можете переименовывать и переупорядочивать константы enum, и пока вы не измените идентификаторы, ваша модель данных будет совместима с содержимым базы данных.

* Даже если база данных содержит значение, которое не соответствует ни одной из констант enum (это может произойти, если старая и новая версии приложения работают с одной и той же базой данных), сущность все равно может быть загружена с атрибутом enum, содержащим null. При стандартном JPA подходе загрузка такого экземпляра невозможна вообще.

TIP: Используйте дизайнер перечислений Studio для создания перечислений Jmix.

Ниже приведен пример класса перечисления Jmix:

.CustomerGrade.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/entity/CustomerGrade.java[tags=enum]
----

<1> Интерфейс `EnumClass` параметризуется типом поля Id (в данном случае `String`).
<2> Каждая константа enum задается с соответствующим значением Id, передаваемым конструктору.
<3> Методы `getId()` и `fromId()` методы преобразуют константу enum в ее Id и обратно.

Enum должен использоваться в сущности следующим образом:

.Customer.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/entity/Customer.java[tags=enum]
----

<1> Персистентное поле имеет тип идентификатора enum (`Integer` или `String`).
<2> Геттер и сеттер преобразуют тип Id в тип enum и обратно.

TIP: При создании атрибута в дизайнере сущностей Studio, выберите *ENUM* в поле *Attribute type* и найдите ваш enum в поле *Type*.