= Data Model

Development of a business application usually starts from designing its data model.

In Jmix, the application data is represented by entities. There are the following types of entities:

* xref:jpa-entities.adoc[JPA entities] are Java objects stored in a database using https://en.wikibooks.org/wiki/Java_Persistence[Java Persistence API].

* xref:dto-entities.adoc[DTO entities] are simple Java objects that are not tied to any specific persistence technology.

* xref:key-value-entity.adoc[KeyValueEntity] is a dynamic entity with an arbitrary number of attributes.

An entity may be stored in an external storage or exist purely in memory. In both cases, an entity is associated with a xref:data-stores.adoc[data store], which is an abstraction over a data source in Jmix applications.

An entity can have references to other entities, even if they are from different data stores. It allows you to create an integral data model comprising data from multiple databases or even from sources of different nature, like no-SQL databases or REST APIs.
