= Мягкое удаление

В режиме _Soft Deletion_ операция удаления объектов JPA просто помечает записи базы данных как удаленные, не удаляя их на самом деле. Позже системный администратор может либо полностью стереть записи, либо восстановить их.

Мягкое удаление может помочь вам снизить риск потери данных, вызванной неверными действиями пользователя. Оно также позволяет пользователям мгновенно сделать определенные записи недоступными, даже если на них есть ссылки из других таблиц.

Механизм мягкого удаления в Jmix прозрачен для разработчиков приложений. Если вы определяете xref:entities.adoc#soft-delete-trait[черту Soft Delete] для сущности, фреймворк помечает записи базы данных удаленных экземпляров сущности и загружает удаленные экземпляры в соответствии со следующими правилами:

* Мягко удаленные экземпляры не возвращаются при загрузке по Id и отфильтровываются из результатов запросов JPQL.

* В загруженных графах сущностей экземпляры, удаленные мягко отфильтровываются из атрибутов-коллекций (ссылки "много-ко-многим"), но присутствуют в единичных атрибутах (ссылки "много-к-одному").
+
Например, представим модель данных Customer - Order - OrderLine. Первоначально Customer ссылался на Order и пять экземпляров OrderLine. Вы мягко удалили экземпляр Customer и один из экземпляров OrderLine. Затем, если вы загрузите Order вместе с Customer и коллекцией OrderLine, он будет содержать ссылку на удаленного Customer и четыре экземпляра OrderLine в коллекции.

== Обработка связей

Когда удаляется обычная (жестко удаляемая) сущность, внешние ключи в базе данных определяют обработку ссылок на эту сущность. По умолчанию вы не можете удалить сущность, если на нее есть ссылки от других сущностей. Чтобы удалить ссылающуюся сущность вместе с ней или установить для ссылки значение null, вы определяете правила `ON DELETE CASCADE` или `ON DELETE SET NULL` для внешнего ключа.

Для мягко удаленных сущностей также существуют внешние ключи, но они не могут повлиять на удаление, поскольку с точки зрения базы данных удаление не выполняется. Поэтому по умолчанию, когда экземпляр сущности мягко удаляется, это не влияет ни на какие связанные сущности.

Jmix предлагает аннотации `@OnDelete` и `@OnDeleteInverse` для обработки ссылок между мягко удаленными сущностей.

TIP: Дизайнер сущностей Studio содержит визуальные подсказки, которые помогут вам выбрать правильные аннотации и их значения.

* Аннотация `@OnDelete` указывает, что делать со ссылочной сущностью при удалении текущей сущности. В следующем примере все экземпляры `OrderLine` удаляются при удалении экземпляра-владельца `Order`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/entity/Order.java[tags=class-def;on-delete]
----

* `@OnDeleteInverse` аннотация указывает, что делать с текущей сущностью при удалении ссылаемой сущности. В следующем примере экземпляр `Customer` нельзя удалить, если на него есть ссылка из экземпляра `Order`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/entity/Order.java[tags=class-def;on-delete-inverse]
----

Эти аннотации могут иметь одно из следующих значений:

* `DeletePolicy.DENY` – чтобы выбросить исключение при попытке удалить сущность, если ссылка не является null.

* `DeletePolicy.CASCADE` – чтобы удалить связанные сущности вместе.

* `DeletePolicy.UNLINK` – чтобы разъединить связанные сущности, установив для ссылочного атрибута значение null. Используйте это значение только на стороне владельца ассоциации (той, что имеет аннотацию `@JoinColumn`).

== Ограничения уникальности

Мягкое удаление усложняет создание ограничений уникальности базы данных. Ограничение должно учитывать, что может быть несколько записей с одним и тем же значением уникального поля: одна не удаленная и любое количество мягко удаленных.

Эта проблема решается по-разному для разных баз данных.

TIP: Studio создает скрипты миграции базы данных для уникальных атрибутов мягко удаленных сущностей с учетом базы данных, используемой в вашем проекте.

Если вы определяете ограничения уникальности вручную без помощи Studio, следуйте приведенным ниже рекомендациям.

* Если база данных поддерживает частичные индексы (PostgreSQL), ограничение уникальности может быть определено следующим образом:
+
[source,sql]
----
create unique index IDX_CUSTOMER_UNIQ_EMAIL on CUSTOMER (EMAIL) where DELETED_DATE is null
----

* Если база данных допускает только одно значение NULL в составном индексе (Oracle, SQL Server), определите составной индекс, включающий столбец `DELETED_DATE`:
+
[source,sql]
----
create unique index IDX_CUSTOMER_UNIQ_EMAIL on CUSTOMER (EMAIL, DELETED_DATE)
----

* В противном случае следует использовать дополнительный столбец, триггер для его обновления и составной индекс для ограничения уникальности. Ниже приведен пример для MySQL:
+
[source,sql]
----
alter table CUSTOMER add DELETED_DATE_NN datetime not null default '1000-01-01 00:00:00.000';

create unique index IDX_CUSTOMER_UNIQ_EMAIL on CUSTOMER (EMAIL, DELETED_DATE_NN);

create trigger CUSTOMER_DELETED_DATE_NN_UPDATE_TRIGGER before update on CUSTOMER
for each row
begin
    if not(NEW.DELETED_DATE <=> OLD.DELETED_DATE) then
        set NEW.DELETED_DATE_NN = if (NEW.DELETED_DATE is null, '1000-01-01 00:00:00.000', NEW.DELETED_DATE);
    end if;
end;
----

== Отключение мягкого удаления

По умолчанию мягкое удаление включено для всех объектов, имеющих xref:entities.adoc#soft-delete-trait[черту Soft Delete]. Но вы можете отключить его для определенной операции, используя hint `PersistenceHints.SOFT_DELETION` со значением `false`.

* При загрузке сущностей с помощью `DataManager`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/bean/CustomerService.java[tags=data-manager;load-hard-deleted]
----
+
Результаты будут включать в себя удаленные мягко экземпляры.

* При удалении сущностей с помощью `DataManager`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/bean/CustomerService.java[tags=data-manager;hard-delete]
----

* При работе с  `EntityManager`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/datamodel/ex1/bean/CustomerService.java[tags=hard-delete-em]
----
