= Root Screens

A root screen is a Jmix UI screen that is displayed directly in the web browser tab. There are two types of such screens: login screen and main screen. Among other components, any root screen can contain the `WorkArea` component which enables opening other application screens in the inner tabs. If the root screen doesn’t contain `WorkArea`, application screens can be opened only in the `DIALOG` mode.

[[login-screen]]
== Login Screen

Login screen is displayed before a user logs in. You can customize the existing login screen by changing its descriptor and controller.

Also, you can use *Login screen with branding image* template in Studio wizard to create a new login screen. After creating, the identifier of the newly created screen will be set in the xref:jmix-ui:app-properties.adoc#jmix.ui.login-screen-id[jmix.ui.login-screen-id] property.

////
If you want to create a new login screen from scratch, use *Blank screen* template. The source code of a minimalistic login screen can look as follows:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/login/my-login-screen.xml[tags=my-login]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/login/MyLoginScreen.java[tags=my-login]
----

In order to use this login screen instead of the default one, set its id to the `jmix.ui.loginScreenId` property in the `application.properties` file:

[source,properties,indent=0]
----
jmix.ui.loginScreenId = myLogin
----
////

[[main-screen]]
== Main Screen

Main screen is a root application screen displayed when the user is logged in. By default, the framework provides the main screen with a collapsible side menu.

You can use the following types of main screens in your application:

* *Main screen with side menu*. It allows users to expand and collapse the side menu using the *Collapse* button located in the lower-left corner.
* *Main screen with top menu*. It contains a menu bar on the top of your application window. You can create this screen from a template using Studio wizard. After creating, the identifier of the newly created screen will be set in the xref:jmix-ui:app-properties.adoc#jmix.ui.main-screen-id[jmix.ui.main-screen-id] property.

The following special components may be used in the main screen in addition to the standard UI components:

* xref:vcl/components/side-menu.adoc[SideMenu] - application menu in the form of the vertical tree.
* xref:vcl/components/app-menu.adoc[AppMenu] - application menu bar.
* xref:vcl/containers/drawer.adoc[Drawer] - a panel that can be collapsed to the left side. This panel is used as a side menu container.
* `AppWorkArea` - work area, the required component for opening screens in the `THIS_TAB`, `NEW_TAB`, and `NEW_WINDOW` modes.
* `NewWindowButton` - the button which opens a new main screen in a separate browser tab.
* `TimeZoneIndicator` - the label displaying the current user’s time zone.
* `UserIndicator` - the field which displays the name of the current user.
+
The `setFormatter()` method allows you to represent the user’s name in a format different from the `User` instance name:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/main/MainScreenTopMenu.java[tags=user-indicator;formatter]
----
* `LogoutButton` - the application logout button.

The following application properties can affect the main screen:

* xref:jmix-ui:app-properties.adoc#jmix.ui.app-window-mode[jmix.ui.app-window-mode] - sets default mode for the main window: `TABBED` or `SINGLE`.
//Users can change the mode using Settings screen available via the UserActionsButton.
* xref:jmix-ui:app-properties.adoc#jmix.ui.max-tab-count[jmix.ui.max-tab-count] - when the main window is in the tabbed mode, this property sets the maximum number of tabs that a user can open.
* xref:jmix-ui:app-properties.adoc#jmix.ui.default-screen-id[jmix.ui.default-screen-id] - specifies the default screen to be opened in the main screen automatically.
* xref:jmix-ui:app-properties.adoc#jmix.ui.default-screen-can-be-closed[jmix.ui.default-screen-can-be-closed] - defines whether the user can close the default screen.
