= ScreenFragment Events

This section describes the lifecycle events that can be handled in fragment controllers.

[[init-event]]
== InitEvent
This event is sent when the fragment controller and all its declaratively defined components are created, and dependency injection is completed. Nested fragments are not initialized yet. Some visual components are not fully initialized, for example, buttons are not linked with actions. If the fragment is attached to the host screen declaratively in XML, this event is sent after `InitEvent` of the host controller. Otherwise, it is sent when the fragment is added to the host’s component tree.

[[after-init-event]]
== AfterInitEvent
This event is sent when the fragment controller and all its declaratively defined components are created, dependency injection is completed, and all components have completed their internal initialization procedures. Nested screen fragments (if any) have sent their `InitEvent` and `AfterInitEvent`. In this event listener, you can create visual and data components and perform additional initialization if it depends on initialized nested fragments.

[[attach-event]]
== AttachEvent
This event is sent when the fragment is added to the host’s component tree. At this moment, the fragment is fully initialized, InitEvent and `AfterInitEvent` have been sent. In this event listener, you can access the host screen using `getHostScreen()` and `getHostController()` methods.

An example of listening to `AttachEvent`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java1;logger;events]
----

[[detach-event]]
== DetachEvent
This event is sent when the fragment is programmatically removed from the host’s component tree. You cannot access the host screen in this event listener.

[[listening-to-host-screen-events]]
== Listening to Host Screen Events
In a fragment controller, you can also subscribe to events of the host screen by specifying the `PARENT_CONTROLLER` value in the target attribute of the annotation, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=target]
----

Any event can be handled this way including xref:jmix-ui:screens/screen-events.adoc#init-entity-event[InitEntityEvent] sent by entity editors.
