## Execute 'authenticate.http' first to get have a valid access token for the API

# Load Messages of the Order Entity

GET {{baseRestUrl}}
         /messages
         /entities
         /rstex11_Order
Authorization: Bearer {{access_token}}


###

# Load Messages of all Entities

GET {{baseRestUrl}}
         /messages
         /entities
Authorization: Bearer {{access_token}}
