= Authentication

Authentication is the process of verifying the identity of a user or process that interacts with the system. For example, the system can authenticate users by their username and password. For authenticated users, the system can perform xref:authorization.adoc[authorization], which is a check of permissions to a particular resource.

Jmix directly uses Spring Security https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-authentication[servlet authentication^], so if you are familiar with this framework, you can easily extend or override the standard authentication mechanism provided by Jmix out-of-the-box.

[[current]]
== Current User

To determine who is currently authenticated, use the `CurrentAuthentication` bean. It has the following methods:

* `getUser()` returns the currently authenticated user as https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/UserDetails.html[UserDetails^]. You can cast it to the class of xref:users.adoc#entity[users] defined in your project.

* `getAuthentication()` returns the https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/Authentication.html[Authentication^] object set in the current execution thread. You can use it to get the collection of current user https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/GrantedAuthority.html[authorities^]. In the standard Jmix security implementation, the collection contains authority objects for each xref:resource-roles.adoc[resource] and xref:row-level-roles.adoc[row-level] role assigned to the user.

* `getLocale()` and `getTimeZone()` return the locale and time zone of the current user.

* `isSet()` returns true if the current execution thread is authenticated, that is contains information about the user. If it's not, `getUser()`, `getLocale()` and `getTimeZone()` methods described above will throw the `IllegalStateException`.

Below is an example of getting the information about the current user:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/security/ex1/screen/auth/AuthTestScreen.java[tags=current-auth]
----

NOTE: `CurrentAuthentication` is just a wrapper around https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/context/SecurityContextHolder.html[SecurityContextHolder^], so it is fully compatible with all Spring Security mechanisms.

[[client]]
== Client Authentication

The backend of a Jmix application can have different clients, for example, Backoffice UI, GraphQL, or REST API. Each client has its own standard authentication mechanism, for example:

* UI xref:backoffice-ui:screens/root-screens.adoc#login-screen[login screen]
* REST xref:rest:security/authentication.adoc[authentication]

[[brute-force-protection]]
=== BruteForce Protection

The framework has a mechanism for the protection against password brute force cracking.

The <<jmix-security-bruteforceprotection-enabled,jmix.security.bruteforceprotection.enabled>> application property enables the protection. If the protection is enabled, the combination of user login and IP address is blocked for a time interval in case of multiple unsuccessful login attempts. A maximum number of login attempts for the combination of user login and IP address is defined by the <<jmix-security-bruteforceprotection-maxLoginAttemptsNumber,jmix.security.bruteforceprotection.maxLoginAttemptsNumber>> application property. Blocking interval in seconds is determined by the <<jmix-security-bruteforceprotection-blockInterval,jmix.security.bruteforceprotection.blockInterval>> application property.

[[jmix-security-bruteforceprotection-enabled]]
* `jmix.security.bruteforceprotection.enabled`
+
Enables a mechanism for the protection against password brute force cracking. The default value: `false`.

[[jmix-security-bruteforceprotection-blockInterval]]
* `jmix.security.bruteforceprotection.blockInterval`
+
Defines the blocking interval in seconds after exceeding a maximum number of failed login attempts if the <<jmix-security-bruteforceprotection-enabled,jmix.security.bruteforceprotection.enabled>> property is on. The default value: `60 seconds`.

[[jmix-security-bruteforceprotection-maxLoginAttemptsNumber]]
* `jmix.security.bruteforceprotection.maxLoginAttemptsNumber`
+
Defines a maximum number of failed login attempts for the combination of user login and IP address if the <<jmix-security-bruteforceprotection-enabled,jmix.security.bruteforceprotection.enabled>> property is on. The default value: `5`.

[[system]]
== System Authentication

The execution thread can be not authenticated if it was started by an internal scheduler or handles a request from the JMX interface. At the same time, your business logic or data access code usually requires information on who is currently working with the system for logging or authorization.

To temporarily associate the current execution thread with a user, use the `SystemAuthenticator` bean. It has the following methods:

* `withSystem()` - accepts a lambda and executes it as the xref:users.adoc#built-in[system] user.

* `withUser()` - accepts a username of a regular application user and a lambda and executes the lambda as the given user with their permissions.

Below is an example of authenticating an MBean operation:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/security/ex1/mbean/SettingsManagementFacade.java[tags=system-authenticator;current-authentication;system-auth-code]
----

You can also use the `@Authenticated` annotation to authenticate an entire bean method as executed by the `system` user. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/security/ex1/mbean/SettingsManagementFacade.java[tags=current-authentication;system-auth-ann]
----

[[authentication-events]]
== Authentication Events

Spring framework sends specific application events related to authentication.

TIP: Studio can help you generate listeners to authentication events. Click *New (+) -> Event Listener* in the *Jmix* tool window and select *Authentication Event* in the dialog.

Below is an example of handling authentication events.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/security/ex1/security/AuthenticationEventListener.java[tags=class]
----

<1> `InteractiveAuthenticationSuccessEvent` is sent when a user logs in to the system through UI or REST API.
<2> `InteractiveAuthenticationSuccessEvent` contains the user entity.
<3> `AuthenticationSuccessEvent` is sent on any successful authentication including <<system,system>>.
<4> `InteractiveAuthenticationSuccessEvent` contains the user entity.
<5> `AbstractAuthenticationFailureEvent` is sent when the authentication attempt has failed, for example because of invalid credentials.
<6> `AbstractAuthenticationFailureEvent` contains only the user name provided for authentication.
<7> `LogoutSuccessEvent` is sent when the user logs out.
<8> `LogoutSuccessEvent` contains the user entity.
