= Безопасность

Подсистема безопасности Jmix предоставляет легко настраиваемый механизм контроля доступа для приложений. Она основана на Spring Security и предлагает следующие функции:

* Интеграция с моделью данных.

** Разрешения для вызова операций CRUD над сущностями и для просмотра/изменения определенных атрибутов сущностей. Например, пользователь может просматривать документы, но не может создавать, изменять и удалять их, и может просматривать все атрибуты документа, кроме `amount`.

** Контроль доступа на уровне строк ограничивает доступ к определенным экземплярам сущности. Например, пользователь может просматривать только те документы, которые были созданы в его отделе.

* Интеграция с UI.

** Разрешения для открытия экранов UI и просмотра пунктов главного меню.

** Если визуальный компонент, такой как TextField, привязан к атрибуту сущности, он автоматически становится доступным только для чтения или скрытым в зависимости от текущих прав пользователя на атрибут. Действия с таблицей отключаются, если пользователю запрещены соответствующие операции CRUD.

* Декларативное определение ролей и разрешений с использованием аннотированных интерфейсов Java.

* Возможность определять роли и разрешения во время выполнения и сохранять их в базе данных.

* UI для просмотра ролей и разрешений, назначения ролей пользователям и создания ролей во время выполнения.

В этом руководстве в основном описывается стандартная реализация подсистемы безопасности. Чтобы использовать все ее функции, убедитесь, что файл `build.gradle` содержит следующие зависимости:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----