= Пользователи

[[entity]]
== Сущность User

Пользователи приложения Jmix определяются классом `User`, который xref:studio:project.adoc#creating-new-project[Studio] автоматически создает в новом проекте. Это xref:data-model:entities.adoc#jpa[сущность JPA], реализующая интерфейс `JmixUserDetails`, который имеет ряд методов, требуемых фреймворком:

* `getUsername()` возвращает уникальное имя пользователя.
* `getPassword()` возвращает хэшированный пароль.
* `isEnabled()`, `isAccountNonExpired()`, `isAccountNonLocked()`, `isCredentialsNonExpired()` указывают, может ли пользователь войти в систему.
* `getAuthorities()`, `setAuthorities()` используются фреймворком для привязки пользователя к набору разрешений при входе в систему.

Пользователи хранятся в основной базе данных приложения. По умолчанию сущность `User` и соответствующая таблица базы данных имеют следующие атрибуты:

* `id`, `version` являются стандартными атрибутами первичного ключа и оптимистической блокировки.
* `username`, `password`, `enabled` хранят значения, возвращаемые методами интерфейса `JmixUserDetails`.
* `email`, `firstName`, `lastName` хранят дополнительную информацию о пользователях.

Вы можете определить любое количество дополнительных атрибутов, необходимых для приложения, например, `department` или `position`.

[[management]]
== Управление пользователями

Новый проект содержит скрипт xref:data-model:db-migration.adoc#changelogs[миграции базы данных] `010-init-user.xml`, который создает пользователя с именем и паролем `admin`/`admin` и предоставляет ему полный доступ к приложению, связывая сущность с xref:resource-roles.adoc[ролью] `system-full-access`.

Новый проект также содержит экраны UI для управления пользователями, см. *Application* -> *Users*. Эти экраны позволяют создавать, редактировать и удалять пользователей, изменять и сбрасывать их пароли. Чтобы назначить роли пользователю, нажмите кнопку *Role assignments* в браузере пользователя.

TIP: Фреймворк содержит роль `ui-minimal`, которая дает разрешения на вход в UI и использование некоторых рядовых элементов UI. Назначьте эту роль новым пользователям, которые будут взаимодействовать с приложением через UI, так как в противном случае они не смогут войти в систему.

[[built-in]]
== Встроенные пользователи

Любое приложение Jmix со стандартной подсистемой безопасности имеет два встроенных пользователя:

* Пользователь _Anonymous_ соответствует не прошедшим аутентификацию пользователям. Это позволяет предоставлять пользователю некоторые разрешения до того, как он войдет в систему.

* Пользователь _System_ требуется для механизма xref:authentication.adoc#system[системной аутентификации]. Он используется, когда нет реального пользователя, взаимодействующего с приложением, например, при его запуске или при вызове бизнес-метода планировщиком.

Встроенные объекты пользователей не хранятся в базе данных, а создаются при запуске приложения классом проекта `DatabaseUserRepository`. Обоих пользователей можно настроить в методах `initAnonymousUser()` и `initSystemUser()` этого класса. По умолчанию системный пользователь связан с ролью `system-full-access` и, следовательно, имеет все разрешения. Анонимный пользователь по умолчанию не имеет никаких разрешений.

[[user-substitution]]
== User Substitution

The system administrator can give a user an ability to substitute another user. The substitution means the user has the security xref:security:resource-roles.adoc[permissions] and xref:security:row-level-roles.adoc[restrictions] of the substituted user. For example, if Alice substitutes Bob, she logs in to the application as Alice but has the Bob's roles.

To see the feature in action, do the following:

. Log in as `admin` and create at least one more user with the `UI: minimal access` role.
. Select `admin` in the *Users* table and click *Additional -> User substitution*. You will see a list of users that `admin` can substitute.
. Add your new user to the list of users substituted by `admin`.
. Now you will see that the current user name in the `userIndicator` component of the main screen has changed to a drop-down list that contains the substituted user. If you select this user, the workspace will change as if you re-login as this user. But all audit features will still register `admin` - the logged-in user.

The `CurrentUserSubstitution` bean can be used to obtain a currently substituted user, an authenticated user, or the effective user (which is substituted user in case of substitution, authenticated one otherwise).

For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/security/ex1/screen/main/MainScreen.java[tags=user-substitution]
----

* The `CurrentAuthentication.getUser()` method always returns the authenticated user.

* The `CurrentAuthentication.getAuthentication().getAuthorities()` returns authorities of the effective user. That is, in the case of substitution, these authorities differ from the authorities of the authenticated user.