= 1. Cоздание приложения

В этом разделе описано создание минимального приложения для бронирования переговорных комнат в котором будет перечисление, сущность и CRUD-экраны. Это приложение будет позже использовано в xref:message-templates.adoc[Определении шаблона].

TIP: Если вы только начинаете работать с Jmix, рекомендуем ознакомиться с разделом xref:tutorial:index.adoc[Руководство], в котором подробнее описаны основные операции.

[[create-room-enum]]
== Создание перечисления Room

Предположим, что в офисе есть три переговорные комнаты разного размера. Создайте перечисление `Room` со следующими значениями:

* `Small`
* `Medium`
* `Large`

[[create-booking-entity]]
== Создание сущности Booking

Создайте сущность `Booking`.

Сущность `Booking` имеет следующие атрибуты:

* `title` - название бронирования с типом `String`. Обязательный атрибут.
* `room` - связь с перечислением `Room`. Обязательный атрибут.
* `startDate` - время начала бронирования с типом `LocalDateTime`. Обязательный атрибут.
* `endDate` - время окончания бронирования с типом `LocalDateTime`. Обязательный атрибут.
* `creator` - ассоциация с сущностью `User`. Обязательный атрибут.

[[create-crud]]
== Создание CRUD-экранов

Создайте экраны списка и деталей для сущности `Booking`:

. Откройте мастер создания экранов для сущности `Booking`.
. Выберите шаблон *List and detail views*.
. На шаге *Entity list view fetch plan* выберите атрибут `creator`.
. Для остальных шагов оставьте значения по умолчанию.

[[run-app]]
== Запуск приложения

Запустите приложение из Studio.

Когда приложение запустится, откройте в браузере `++http://localhost:8080++`, войдите как `admin` / `admin` и выберите *Бронирования* в главном меню приложения.
