= 1. Room Booking Application Creation

In this chapter, you will learn how to create and configure the following components for your application:

* The `Room` enumeration. Define an enumeration to represent the available rooms in your system.
* The `Booking` entity. Create a `Booking` entity to manage reservations.
* CRUD views for bookings. Develop CRUD views to enable users to interact with the `Booking` entity.

[[create-room-enum]]
== Creating Room Enumeration

To start, you’ll need to create a `Room` enumeration with the following values:

* `Senior`
* `Junior`
* `Middle`

TIP: For details on creating enumerations, see xref:tutorial:enumerations.adoc[Using Enumerations].

[[create-booking-entity]]
== Creating Booking Entity

Next, create the `Booking` entity. You can find detailed instructions for creating entities in the xref:tutorial:simple-crud.adoc[Simple CRUD] section of the Tutorial.

The `Booking` entity has the following attributes:

* `title` with `String` type. A descriptive name for the booking. Select the *Mandatory* checkbox.
* `room` - the room selected for the booking (using the `Room` enumeration). Select the *Mandatory* checkbox.
* `startDate` and `endDate` with `DateTime` type: the date and time range for the booking. Select the *Mandatory* checkbox.
* `creator` - the user who created the booking (linked to the `User` entity many-to-one cardinality). Select the *Mandatory* checkbox.

[[create-crud]]
== Creating CRUD Views

Create list and detail views for the `Booking` entity. In the view creation wizard, on the Entity list view fetch plan step, select the creator attribute. For all other steps, accept the default settings.

For more details, see the xref:tutorial:simple-crud.adoc[Creating CRUD Views] section of the Tutorial.

[[run-app]]
== Running the Application

Run the application from Studio as described in the xref:tutorial:project-setup.adoc#run-app[Running Application from IDE] section of the Tutorial.

When the application starts, open `++http://localhost:8080++` in your web browser, log in with `admin` / `admin`, and choose *Bookings* from the *Application* menu.

[[summary]]
== Summary

In this section, you learned how to implement a Room Booking feature within your application. You gained practical experience in creating and configuring a `Room` enumeration, defining a `Booking` entity with key attributes, and generating CRUD views to enable users to manage room reservations effectively. You also learned how to run the application, apply database changes, and access the new booking feature through the application menu.