= 1. Setting Up the Booking Application

In this section, you create a minimal room booking application with an enumeration, an entity, and CRUD views. This application is used later in xref:message-templates.adoc[Template Definition].

TIP: If you are new to Jmix, see the xref:tutorial:index.adoc[Tutorial], which explains common operations in greater detail.

[[create-room-enum]]
== Creating Room Enumeration

Assume that the office has three rooms of different sizes. Create a `Room` enumeration with the following values:

* `Small`
* `Medium`
* `Large`

[[create-booking-entity]]
== Creating Booking Entity

Create the `Booking` entity.

The `Booking` entity has the following attributes:

* `title` - booking title. Mandatory.
* `room` with `Room` enum type - selected room. Mandatory.
* `startDate` with `LocalDateTime` type - booking start time. Mandatory.
* `endDate` with `LocalDateTime` type - booking end time. Mandatory.
* `creator` - association with the `User` entity. Mandatory.

[[create-crud]]
== Creating CRUD Views

Create list and detail views for the `Booking` entity:

. Open the view creation wizard for the `Booking` entity.
. Select the *List and detail views* template.
. At the *Entity list view fetch plan* step, select the `creator` attribute.
. Accept the default settings for all other steps.

[[run-app]]
== Running the Application

Run the application from Studio.

When the application starts, open `++http://localhost:8080++` in a web browser, log in with `admin` / `admin`, and select *Bookings* from the main application menu.
