= Начало работы с Message Templates

В этом руководстве вы узнаете, как интегрировать дополнение Message Templates в ваше приложение.

[[project-setup]]
== Настройка проекта

Мы создадим приложение для бронирования переговорных комнат, чтобы показать, как использовать дополнение Message Templates в Jmix. Вы увидите, как создавать, редактировать и использовать шаблоны для рассылки уведомлений о бронированиях.

Администраторы настраивают шаблоны сообщений для уведомления пользователей о новых бронированиях. После бронирования пользователи получают email и уведомление прямо в приложении.

. Создайте базовый проект Jmix. Вы можете обратиться к разделу xref:tutorial:project-setup.adoc[Руководство], где представлено подробное пошаговое руководство по разработке базового приложения.
. Добавьте дополнение Message Templates в соответствии с разделом об xref:index.adoc#installation[установке].
. Чтобы включить отправку электронных писем и уведомлений, вам также потребуется установить дополнения xref:email:index.adoc[Email Sending] и xref:notifications:index.adoc[Notifications].

[[about-app]]
== О приложении

Это демонстрационное приложение представляет собой простую систему бронирования комнат. Оно предоставляет практический пример обработки бронирований и отправки уведомлений либо непосредственно в приложении, либо по электронной почте, с использованием готовых шаблонов сообщений.

Основным элементом приложения является сущность `Booking`. Сущность `User` (представленная атрибутом `creator`) отражает информацию о пользователе, создавшем бронирование.