= Блоки шаблонов

The add-on provides the ability to create custom blocks, which can be used to design and structure message templates more efficiently. To create a custom block, navigate to *Message Templates → Template blocks* and click the *Create* button.

Дополнение предоставляет возможность создания пользовательских блоков, которые можно использовать для более эффективного проектирования и структурирования шаблонов сообщений. Чтобы создать пользовательский блок, перейдите в раздел *Шаблоны сообщений → Блоки шаблонов* и нажмите кнопку *Создать*.

[[block-designer]]
== Дизайнер блоков шаблонов

При создании нового блока отобразится экран деталей блока шаблона. Этот интуитивно понятный инструмент позволяет:

* Перетаскивать готовые HTML-элементы на рабочую область.
* Настраивать эти элементы, изменяя их свойства, такие как размер, цвет, выравнивание и многое другое.
* Располагать и организовывать элементы для создания многократно используемого блока, отвечающего вашим потребностям.

На вкладке *Атрибуты* можно настроить атрибуты блока. В GrapesJS атрибуты представляют собой пары "ключ-значение", связанные с блоком. По сути, это способ хранения и управления дополнительными данными, относящимися к определенному элементу или блоку в вашем дизайне. Они позволяют настраивать и конфигурировать поведение и внешний вид ваших компонентов, помимо основных свойств, таких как содержание, стиль или положение.

[[using-custom-blocks]]
== Применение пользовательских блоков

После создания ваши пользовательские блоки будут доступны на экране xref:message-templates.adoc[Шаблон сообщения]. Вы можете легко вставлять эти блоки в свои шаблоны, экономя время и обеспечивая единообразие в разных шаблонах.