= EditAction

`EditAction` is a xref:actions/standart-actions.adoc#list-actions[list action] designed to edit xref:data-model:entities.adoc[entity] instances. It opens the entity edit screen with the entity instance selected in the UI component. After the instance is saved to the database by the edit screen, the action updates it in the data container of the UI component.

The action is implemented by the `io.jmix.ui.action.list.EditAction` class and should be defined in XML using `type="edit"` action’s attribute. You can configure common action parameters using XML attributes of the `action` element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details. Below we describe parameters specific to the `EditAction` class.

== Specific Parameters

The following parameters can be set both in XML and in Java:

* `openMode` - the editor screen opening mode as a value of the `OpenMode` enum: `NEW_TAB`, `DIALOG`, etc. By default, `EditAction` opens the editor in `THIS_TAB` mode.
* `screenId` - string id of the editor screen to use. By default, `EditAction` uses either a screen, annotated with `@PrimaryEditorScreen`, or having identifier in the format of `<entity_name>.edit`, for example, `demo_Customer.edit`.
* `screenClass` - Java class of the editor screen controller to use. It has a higher priority than `screenId`.

For example, if you want to open a specific editor screen as a dialog, you can configure the action in XML:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=edit-action]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-edit-action;on-init-start;edit-action-set;on-init-end]
----

== Handlers and Events

Now let’s consider parameters that can be configured only in Java code. To generate correctly annotated method stubs for these parameters, use xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

It is a handler that returns `ScreenOptions` object to be passed to the opened editor screen. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-screen-options-supplier]
----

The returned `ScreenOptions` object will be available in `InitEvent` of the opened screen.

=== screenConfigurer

It is a handler that accepts the editor screen and can initialize it before opening. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-screen-configurer]
----

Note that screen configurer comes into play when the screen is already initialized but not yet shown, that is, after its `InitEvent` and `AfterInitEvent` and before `BeforeShowEvent` are sent.

=== transformation

It is a handler that is invoked after the entity is selected and validated in the editor screen. It accepts the selected entity. You can use this handler to transform the committed entity before setting it to the target data container. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-transformation]
----

=== afterCommitHandler

It is a handler that is invoked after the edited entity instance is committed in the editor screen. It accepts the updated entity. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-after-commit-handler]
----

=== afterCloseHandler

It is a handler that is invoked after the editor screen is closed. `AfterCloseEvent` is passed to the handler. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-after-close-handler]
----

=== ActionPerformedEvent

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent` and invoke the `execute()` method of the action when needed. The action will be invoked with all parameters that you defined for it. In the example below, we show a confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-edit-action;edit-action-performed-event]
----

You can also subscribe to `ActionPerformedEvent` and instead of invoking the action’s `execute()` method, use `ScreenBuilders` API directly to open the edit screen. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like caption, icon, etc. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-screen-builders;edit-action-performed-event-2]
----