= EntityClearAction

`EntityClearAction` is an entity picker action designed to clear the value of xref:vcl/components/entity-picker.adoc[EntityPicker]. If the field displays a one-to-one composition xref:data-model:entities.adoc[entity], the entity instance will also be removed on `DataContext` commit (if the screen is an entity editor, it happens when the user clicks *OK*).

The action is implemented by the `io.jmix.ui.action.entitypicker.EntityClearAction` class and should be defined in XML using `type="entity_clear"` action’s attribute. You can configure common action parameters using XML attributes of the action element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details.

== ActionPerformedEvent

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent` and invoke the `execute()` method of the action when needed. In the example below, we show a confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-customerFieldClear;entity-clear-action-performed-event]
----