= ExcludeAction

`ExcludeAction` is a xref:actions/standart-actions.adoc#list-actions[list action] designed to remove xref:data-model:entities.adoc[entity] instances from a data container in UI. Unlike `RemoveAction`, `ExcludeAction` does not remove the selected instance from the database. It is required, for example, when working with a many-to-many collection.

The action is implemented by the `io.jmix.ui.action.list.ExcludeAction` class and should be defined in XML using `type="exclude"` action’s attribute. You can configure common action parameters using XML attributes of the action element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details. Below we describe parameters specific to the `ExcludeAction` class.

== Specific Parameters

The following parameters can be set both in XML and in Java:

* `confirmation` - boolean value specifying whether to show confirmation dialog before excluding the selected entities. The default value is `true`.
* `confirmationMessage` - confirmation dialog message. By default, it is taken from the main message pack using the `dialogs.Confirmation.Remove` key.
* `confirmationTitle` - confirmation dialog title. By default, it is taken from the main message pack using the `dialogs.Confirmation` key.

For example, if you want to show a specific confirmation message, you can configure the action in XML:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/entity/customer/customer-edit.xml[tags=exclude-action]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action;on-init-start;exclude-action-set;on-init-end]
----

== Handlers and Events

Now let’s consider parameters that can be configured only in Java code. To generate correctly annotated method stubs for these parameters, use xref:studio:index.adoc[Studio].

=== afterActionPerformedHandler

It is a handler that is invoked after selected entities are removed. It accepts the event object that can be used to get the entities selected for removal. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-after-action-performed-handler]
----

=== actionCancelledHandler

It is a handler that is invoked when the remove operation is cancelled by user in the confirmation dialog. It accepts the event object that can be used to get the entities selected for removal. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action-cancelled-handler]
----

=== ActionPerformedEvent

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent` and invoke the `execute()` method of the action when needed. The action will be invoked with all parameters that you defined for it. In the example below, we show a custom confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action-performed-event]
----

You can also subscribe to `ActionPerformedEvent` and instead of invoking the action’s `execute()` method, use `RemoveOperation` API directly to remove the selected entities. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like caption, icon, etc. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=inject-remove-operation;exclude-action-performed-event-2]
----