= ViewAction

`ViewAction` is a xref:actions/standard-actions.adoc#list-actions[list action] designed to view and edit xref:data-model:entities.adoc[entity] instances. It opens the edit screen in the same way as xref:actions/standard-actions/edit-action.adoc[EditAction], but it makes all fields non-editable and disables actions implementing interface `ReadOnlyAwareScreen`. If you want to allow users to switch the screen to the editable mode, add a button and link it with the predefined `enableEditing` action:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/entity/customer/customer-edit.xml[tags=enable-editing]
----

<1> This button is shown only when the screen is in read-only mode.

You can redefine the `enableEditing` action caption in the main message pack using the `actions.EnableEditing` key, or right in the screen by specifying the `caption` attribute to the corresponding button.

`ViewAction` is implemented by the `io.jmix.ui.action.list.ViewAction` class and should be defined in XML using `type="view"` action’s attribute. You can configure common action parameters using XML attributes of the action element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details. Below we describe parameters specific to the `ViewAction` class.

== Properties

The following parameters can be set both in XML and in Java:

* `openMode` - the editor screen opening mode as a value of the `OpenMode` enum: `NEW_TAB`, `DIALOG`, etc. By default, `ViewAction` opens the editor in `THIS_TAB` mode.
* `screenId` - string id of the editor screen to use. By default, `ViewAction` uses either a screen, annotated with `@PrimaryEditorScreen`, or having identifier in the format of `<entity_name>.edit`, for example, `demo_Customer.edit`.
* `screenClass` - Java class of the editor screen controller to use. It has a higher priority than `screenId`.

For example, if you want to open a specific editor screen as a dialog, you can configure the action in XML:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=view-action]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-view-action;on-init-start;view-action-set;on-init-end]
----

== Handlers

Now let’s consider parameters that can be configured only in Java code. To generate correctly annotated method stubs for these parameters, use xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

It is a handler that returns the `ScreenOptions` object to be passed to the opened editor screen. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=view-screen-options-supplier]
----

The returned `ScreenOptions` object will be available in the `InitEvent` of the opened screen.

=== screenConfigurer

It is a handler that accepts the editor screen and can initialize it before opening. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=view-screen-configurer]
----

Note that screen configurer comes into play when the screen is already initialized but not yet shown, that is, after its `InitEvent` and `AfterInitEvent` and before `BeforeShowEvent` are sent.

=== transformation

It is a handler that is invoked after the entity is selected and validated in the editor screen. It accepts the selected entity. You can use this handler to transform the committed entity (if `enableEditing` action was executed) before setting it to the target data container. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=view-transformation]
----

=== afterCommitHandler

It is a handler that is invoked after the edited entity instance is committed in the editor screen if the user switched the screen to editable mode using `enableEditing` action mentioned above. The handler method accepts the updated entity. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=view-after-commit-handler]
----

=== afterCloseHandler

It is a handler that is invoked after the editor screen is closed. `AfterCloseEvent` is passed to the handler. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=view-after-close-handler]
----

== Using ActionPerformedEvent

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent`, and invoke the `execute()` method of the action when needed. The action will be invoked with all parameters that you defined for it. In the example below, we show a confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-screen-builders;view-action-performed-event]
----