= BPM API

Для взаимодействия с механизмом процессов может использоваться https://flowable.com/open-source/docs/bpmn/ch04-API/[Flowable API^]. Он позволяет запускать экземпляры процессов программно, выполнять задачи и производить различные запросы, например, получить список задач для пользователя или получать активные экземпляры определения процесса.

Сервисы Flowable можно получить двумя способами:

* Использовать `ProcessEngines` в качестве отправной точки:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=services]
----
+
* Инжектировать сервисы в бины, поскольку они зарегистрированы как бины Spring:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomBean.java[tags=bean;runtime-service]
----

Дополнение предоставляет `BpmTaskService`, расширяющую `TaskService` Flowable. См. пример использования <<using-bpm-task-service,ниже>>.

[[starting-process-programmatically]]
== Программный запуск процесса

В приведенном ниже примере процесс запускается программно из обычного редактора сущностей с помощью `RuntimeService`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=runtime-service;commit]
----
<1>	Размещение редактируемой сущности в переменной процесса с именем `customer`.
<2> Имя клиента помещается в переменную процесса типа String.
<3> `RuntimeService` используется для запуска процесса.
<4> `new-customer` является ключом определения процесса.
<5>	Размещение карты переменных процесса.

[[getting-list-of-user-tasks]]
== Получение списка пользовательских задач

Рассмотрим примеры получения списка активных задач, назначенных аутентифицированному пользователю:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomBean.java[tags=task-service;current-authentication;get-tasks]
----
<1> Использование `TaskService` для получения списка задач.
<2> Поиск задачи процесса `approval`.
<3> Поиск задач, назначенных текущему пользователю.

[[getting-list-of-process-instances]]
== Получение списка экземпляров процессов

В примере ниже показано получение списка экземпляров процесса определения `approval`, относящегося к указанной сущности `Order`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomBean.java[tags=runtime-service;get-instances]
----
<1> Использование `RuntimeService` для получения списка задач.
<2> Поиск экземпляров процесса `approval`.
<3> Поиск экземпляров процесса с указанной переменной процесса `orderId`.

[[using-bpm-task-service]]
== Использование BpmTaskService

`BpmTaskService` расширяет `TaskService` и добавляет метод для выполнения задач с выходом.

[source,java,indent=0]
----
void completeTaskWithOutcome(String taskId, String outcomeId, Map<String, Object> processVariables);
----

Вы можете внедрить службу в свой бин Spring:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=inject-service]
----

или использовать класс `ProcessEngines`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=get-service]
----