= BPM API

You can use https://flowable.com/open-source/docs/bpmn/ch04-API/[Flowable API^] to interact with the process engine. This API allows you to start process instances programmatically, complete tasks, and execute various queries, for example, get a list of tasks for a user or get active instances of a process definition.

Flowable services can be obtained in two ways:

* Using `ProcessEngines` as a starting point:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=services]
----
+
* Injecting services inside your beans as they are registered as Spring beans:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomBean.java[tags=bean;runtime-service]
----

The add-on provides `BpmTaskService` that extends `TaskService` of Flowable. See an example of usage <<using-bpm-task-service,below>>.

[[starting-process-programmatically]]
== Starting Process Programmatically

In the example below, the process is started programmatically from the regular entity editor using `RuntimeService`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=runtime-service;commit]
----
<1> Puts the edited entity to the process variable with the `customer` name.
<2> The customer's name is put to the process variable with a String type.
<3> `RuntimeService` is used to start the process.
<4> `new-customer` is the process definition key.
<5> Puts the process variables map.

[[getting-list-of-user-tasks]]
== Getting List of User Tasks

Let's look at the examples that show getting a list of active tasks assigned to the authenticated user:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomBean.java[tags=task-service;current-authentication;get-tasks]
----
<1> Uses `TaskService` to get a list of tasks.
<2> Searches for the tasks of the `approval` process.
<3> Searches for the tasks assigned to the current user.

[[getting-list-of-process-instances]]
== Getting List of Process Instances

The example below shows getting a list of process instances of the `approval` definition related to the specified `Order` entity:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomBean.java[tags=runtime-service;get-instances]
----
<1> Uses `RuntimeService` to get a list of tasks.
<2> Searches for the instances of the `approval` process.
<3> Searches for the process instances with the specified `orderId` process variable.

[[using-bpm-task-service]]
== Using BpmTaskService

`BpmTaskService` extends the `TaskService` and adds a method for completing tasks with an outcome:

[source,java,indent=0]
----
void completeTaskWithOutcome(String taskId, String outcomeId, Map<String, Object> processVariables);
----

You can inject the service into your Spring component:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=inject-service]
----

or use the `ProcessEngines` class:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/customer/CustomerEdit.java[tags=get-service]
----