= Events

BPMN events are specific points in a business process where something happens. These events can represent various occurrences such as the start or end of a process, a message received, or a timer expiring. They help to model the flow of activities within a business process and indicate when certain actions should take place.

Events are always visualized as a circle. In BPMN 2.0, there exist two main event categories: _catching_ and _throwing_ events.

//todo - непонятно, откуда появились некие триггукы, нужно переписать

* *Catching:* when process execution arrives at the event, it will wait for a trigger to happen. The type of trigger is defined by the inner icon or the type declaration in the XML. Catching events are visually differentiated from a throwing event by the inner icon that is not filled (it’s just white).

* *Throwing:* when process execution arrives at the event, a trigger is fired. The type of trigger is defined by the inner icon or the type declaration in the XML. Throwing events are visually differentiated from a catching event by the inner icon that is filled with black.