= 自定义表单

当需要以非标准方式展示表单时，可以使用自定义流程表单。在建模器中，可以为自定义表单提供一个表单 id，一组表单参数和一组输出。

如果你使用的是另一种 UI 技术（比如，React），那么你需要获取表单的信息，并根据信息渲染表单。可以使用 `FormService` 接口获取表单信息，接口有如下方法：

* `StartFormData getStartFormData​(String processDefinitionId)`
* `TaskFormData getTaskFormData​(String taskId)`

如需在 *Start process（开始流程）* 和 *My tasks（我的任务）* 界面中展示自定义表单，你需要为自定义表单类型定义 `ProcessFormScreenCreator`。为了覆盖默认的 `ProcessFormScreenCreator`，你需要添加 `@Order` 注解。

我们看看下面示例 `MyCustomProcessFormScreenCreator` 实现了 `ProcessFormScreenCreator`：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomProcessFormScreenCreator.java[tags=custom]
----

<1> `@Order` 注解表示 `ProcessForScreenCreator` 接口的当前实现会第一个使用。
<2> `ScreenCreator` 用在自定义表单。
<3> 重写该方法，创建启动流程表单。
<4> 检查界面是否实现了 `AcceptsProcessDefinition` 接口，如是，则需要设置 `ProcessDefiniton`。
<5> 重写该方法，创建任务流程表单。
<6> 检查界面是否实现了 `AcceptsTask` 接口，如是，则需要设置 `Task`。

`AcceptsProcessDefinition` 接口示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/AcceptsProcessDefinition.java[tags=custom]
----

`AcceptsTask` 接口示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/AcceptsTask.java[tags=custom]
----

自定义流程启动表单 XML，只有 *Start process* 按钮：

[source,java,indent=0]
----
include::example$/ex1/src/main/resources/bpm/ex1/screen/forms/custom-start-form.xml[tags=custom]
----

自定义启动表单界面控制器：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/forms/CustomStartForm.java[tags=custom]
----

自定义任务表单 XML，只有 *Task complete* 按钮：

[source,java,indent=0]
----
include::example$/ex1/src/main/resources/bpm/ex1/screen/forms/custom-task-form.xml[tags=custom]
----

自定义任务表单界面控制器：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/forms/CustomTaskForm.java[tags=custom]
----


