= Настраиваемая форма

Настраиваемые формы процессов могут быть полезны, если вам нужно отобразить форму нестандартным способом. В моделере можно указать id, список параметров и список выходов для пользовательской формы.

Если вы используете альтернативную технологию UI (например, React), вам необходимо получить информацию о форме и отобразить форму, используя эту информацию. Ее можно получить с помощью интерфейса `FormService`, который имеет следующие методы:

* `StartFormData getStartFormData(String processDefinitionId)`
* `TaskFormData getTaskFormData(String taskId)`

Для отображения настраиваемых форм на экранах *Start process* или *My tasks* необходимо определить `ProcessFormScreenCreator` для типа формы `custom`. Чтобы переопределить значение по умолчанию `ProcessFormScreenCreator`, добавьте аннотацию `@Order`.

Давайте посмотрим на пример `MyCustomProcessFormScreenCreator`, которая реализует `ProcessFormScreenCreator`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/MyCustomProcessFormScreenCreator.java[tags=custom]
----

<1> Аннотация `@Order` указывает, что эта реализация `ProcessForScreenCreator` будет использоваться первой.
<2> `ScreenCreator` будет применяться к настраиваемым формам процесса.
<3> Переопределение метода создания формы запуска процесса.
<4> Проверка того, реализует ли экран `AcceptsProcessDefinition`. В таком случае необходимо установить `ProcessDefiniton` в экран.
<5> Переопределение метода создания формы процесса задачи.
<6> Проверка того, реализует ли экран `AcceptsTask`. В таком случае необходимо установить `Task` в экран.

Пример интерфейса `AcceptsProcessDefinition`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/AcceptsProcessDefinition.java[tags=custom]
----

Пример интерфейса `AcceptsTask:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/service/AcceptsTask.java[tags=custom]
----

XML-дескриптор настраиваемой формы запуска, имеющей только кнопку *Start process*:

[source,java,indent=0]
----
include::example$/ex1/src/main/resources/bpm/ex1/screen/forms/custom-start-form.xml[tags=custom]
----

Контроллер экрана настраиваемой стартовой формы:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/forms/CustomStartForm.java[tags=custom]
----

XML-дескриптор настраиваемой формы задачи, имеющей только кнопку *Task complete*:

[source,java,indent=0]
----
include::example$/ex1/src/main/resources/bpm/ex1/screen/forms/custom-task-form.xml[tags=custom]
----

Контроллер экрана настраиваемой формы задачи:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/screen/forms/CustomTaskForm.java[tags=custom]
----


