= History

History is the component that captures what happened during process execution and stores it permanently.
In contrast to the runtime data,
the history data will remain present in the DB also after process instances have completed.

There are six history entities:

[[historic-process-instances]]
* *Historic Process Instances* -- containing information about current and past process instances.
* *Historic Variable Instances* -- containing the latest value of a process variable or task variable.
* *Historic Activity Instances* -- containing information about a single execution of an activity (node in the process).
* *Historic Task Instances* -- containing information about current and past (completed and deleted) task instances.
* *Historic Identity Links* -- containing information about current and past identity links on tasks and process instances.
* *Historic Details* -- containing various kinds of information related to either a historic process instances, an activity instance or a task instance.

Since the database contains historic entities for past as well as ongoing instances,
you might want to consider querying these tables
to minimize access to the runtime process instance data and that way keeping the runtime execution performant.


For details, see https://www.flowable.com/open-source/docs/bpmn/ch10-History[Flowable documentation^].