= BPM
//my branch

include::ROOT:partial$outdated-ui-warning.adoc[]

BPM add-on is used for modeling and running business processes. Processes are described using BPMN 2.0 notation. The add-on uses https://flowable.com/open-source/[Flowable^] as a business process engine and https://bpmn.io/[bpmn-js^] rendering toolkit for process modeling.

This manual mostly describes features added by the add-on, not features provided by underlying frameworks, so you should be familiar with the Flowable engine.

[[installation]]
== Installation

[NOTE]
====
This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial] section for how to get a trial version.
====

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----
