= BPM

include::ROOT:partial$outdated-ui-warning.adoc[]

Дополнение BPM используется для моделирования и запуска бизнес-процессов. Процессы описываются с использованием нотации BPMN 2.0. Это дополнение использует https://flowable.com/open-source/[Flowable^] в качестве механизма бизнес-процессов и набор инструментов рендеринга https://bpmn.io/[bpmn-js^] для моделирования процессов.

В этом руководстве описываются в основном функции дополнения, а не базовых технологий, поэтому мы рекомендуем вам также ознакомится непосредственно с движком Flowable.

[[installation]]
== Установка

NOTE: Для этого дополнения требуется https://www.jmix.io/subscription-plans-and-prices/[подписка^] Enterprise. Если у вас нет подписки, узнайте, как получить пробную версию в разделе xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial].

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие действия.

. Настройте доступ к премиум-репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в свой `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----
