= Миграция экземпляров процесса

При изменении модели процесса и развертывании новой версии определения процесса, все существующие экземпляры процесса продолжают использовать предыдущую версию определения. При необходимости возможна их миграция в новую версию.

Если вам нужно мигрировать все экземпляры процессов, откройте экран xref:bpm:proc-definitions.adoc[Process Definitions] и нажмите *View details*. В редакторе выберите нужную версию в выпадающем списке и нажмите кнопку *Migrate all instances*. Перед выполнением миграции все экземпляры проходят валидацию, и если какой-либо экземпляр не может быть мигрирован, отобразится окно с информацией.

Чтобы мигрировать один экземпляр, найдите его на экране xref:bpm:proc-instances.adoc[Process Instances] и нажмите *Edit*. В редакторе нажмите кнопку *Migrate*.

Для получения более подробной информации о миграции экземпляров процессов см. https://flowable.com/open-source/docs/bpmn/ch09-ProcessInstanceMigration/#process-instance-migration-experimental[документацию Flowable^].
