= Process Instances Migration

When you modify a process model and deploy a new process definition version, all existing process instances continue using the previous version of the process definition. If necessary, you can migrate them to the new process definition version.

If you need to migrate all process instances, open the xref:bpm:proc-definitions.adoc[Process Definitions] screen and click *View details*. In the editor, select a required version in the combo box field and click the *Migrate all instances* button. Before the migration is performed, all instances are validated, and if any instance cannot be migrated, an information window will be displayed.

To migrate a single instance, find it in the xref:bpm:proc-instances.adoc[Process Instances] screen and click *Edit*. In the editor, click the *Migrate* button.

For more details about the process instance migration, see https://flowable.com/open-source/docs/bpmn/ch09-ProcessInstanceMigration/#process-instance-migration-experimental[Flowable documentation^].
