= Слушатели событий

Существует несколько подходов к обработке событий механизма процессов, таких как создание задачи, завершение операции и т.д.

Во-первых, можно определить слушателя выполнения или слушателя задачи для определенного узла процесса. Подробнее см. в https://www.flowable.org/docs/userguide/index.html#executionListeners[документации Flowable^].

Моделер процессов предоставляет UI для настройки слушателей.

* В редакторе слушателя завершения выпадающий список содержит классы, реализующие интерфейс `org.flowable.engine.delegate.ExecutionListener`.
* В редакторе слушателя задачи выпадающий список содержит классы, реализующие интерфейс `org.flowable.engine.delegate.TaskListener`. Если класс содержит https://flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#field-injection-on-execution-listeners[инжектированные поля^], то они будут автоматически добавлены в раздел *Fields* редактора слушателя.

Второй подход — объявить глобальные слушатели событий, предоставляемые фреймворком Flowable, см. раздел https://flowable.com/open-source/docs/bpmn/ch03-Configuration/#event-handlers[Event handlers^]. Их можно определить в разделе *Event listeners* панели свойств проекта.

Дополнение BPM также представляет набор событий приложений Spring. Публикуются следующие события:

* `UserTaskAssignedEvent`
* `UserTaskCreatedEvent`
* `UserTaskCompletedEvent`
* `ActivityStartedEvent`
* `ActivityCompletedEvent`
* `ProcessStartedEvent`
* `ProcessCompletedEvent`

Ниже представлен пример слушателя, который отправляет уведомление по электронной почте каждый раз, когда пользовательская задача назначается пользователю:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=event-listener-1;event-listener-2]
----

<1> Объявляет, что метод является слушателем события.
<2> Слушатель срабатывает каждый раз, когда публикуется `UserTaskAssignedEvent`.
<3> Сущность `User` получает имя пользователя и адрес электронной почты. `UserTaskAssignedEvent` содержит `username` пользователя, которому назначена задача.
<4> Содержит `UserTaskAssignedEvent` объект `Task`, который содержит информацию о пользовательской задаче.
<5> Создает и отправляет письмо. Подробнее см. в xref:email:index.adoc[].

Если вам нужно получить в слушателе значение переменной процесса, то это можно сделать следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender2.java[tags=get-variable-1;get-variable-2]
----

По умолчанию слушатель срабатывает, когда в любом процессе назначается пользовательская задача. Если вы хотите отправлять уведомления только для конкретного определения процесса, вы можете проверить определение процесса в теле метода слушателя;

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=specific-process-1;specific-process-2]
----

либо определить соответствующее выражение SpEL (Spring Expression Language) для обработки события:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender3.java[tags=spel-example-1;spel-example-2]
----