= Tasks

In BPMN, a *task* is an atomic activity within a process flow that represents work performed by a person or an application.
Tasks are the fundamental elements that define the units of work in a business process.

_Atomic_ means that it cannot be broken down further in the process model.
If an activity can be decomposed into smaller units, a xref:bpmn-subprocesses.adoc[subprocess] should be used instead.

Tasks are connected by xref:bpmn-sequence-flow.adoc[sequence flows] to define the order of execution within the process.

[[task-type]]
== Task Types

BPMN defines several types of tasks to represent different behaviors and performers.
These task types are graphically annotated with symbols in the top left corner of the task shape.
The task types include:

[horizontal]
Abstract Task:: A task that does not have a specific type defined. It is used when the task's behavior is not specified in detail.
User Task:: Performed by a human user with the assistance of a software application.
Service Task:: Uses a web service, automated application, or other service to perform the task.
Manual Task:: Performed without the aid of any business process execution engine. *Not supported in Jmix BPM*.
Business Rule Task:: Provides input to a business rules engine and gets the output.
Script Task:: Executed by a business process engine by running a predefined script.

[[naming-tasks]]
== Naming Tasks
Tasks are typically named using a verb + object syntax, such as "Approve Order" or "Send Invoice".

Task name maximum length is 255 characters.

[[additional-markers]]
=== Additional Markers
Tasks can also be annotated with markers to indicate specific behaviors such as:

[horizontal]
Looping:: It indicates that a task will repeat until a certain condition is met. *Not supported in Jmix BPM*.
Multi-Instance:: It indicates that a task will be executed multiple times, either in parallel or sequentially. See the xref:multi-instance.adoc[multi-instance] section for details.