= Application Properties

== core

[[jmix.core.exclude-beans]]
=== jmix.core.exclude-beans

A comma-separated list of bean names to exclude from the Spring application context. It can be used to xref:modularity:extension.adoc#beans[override beans] already having `@Primary` annotations in some add-on.

For example:

[source,properties]
----
jmix.core.exclude-beans = abc_FooService,abc_BarService
----

[[cors]]
== CORS

See more information on CORS in the xref:rest:security.adoc#cors[REST Security] section.

[[jmix.cors.allow-credentials]]
=== jmix.cors.allow-credentials

Whether user credentials are supported.

Default value: `false`

[[jmix.cors.allowed-headers]]
=== jmix.cors.allowed-headers

The list of headers that a pre-flight request can list as allowed for use during an actual request. The special value "*" allows actual requests to send any header.

Default value: `*`

[[jmix.cors.allowed-methods]]
=== jmix.cors.allowed-methods

The HTTP methods to allow, e.g. "GET", "POST", "PUT", etc.
The special value "*" allows all methods.

Default value: `*`

[[jmix.cors.allowed-origins]]
=== jmix.cors.allowed-origins

Defines a comma-separated list of origins for which cross-origin requests are allowed. Use special value `*` for all origins.

For example: `++https://www.allowed1.com, https://www.allowed2.com++`

Default value: `*`
