= 应用程序属性

[[core]]
== Core

[[jmix.core.anonymous-authentication-token-key]]
=== jmix.core.anonymous-authentication-token-key

用在 Spring Security {spring-security-api}/org/springframework/security/authentication/AnonymousAuthenticationProvider.html[AnonymousAuthenticationProvider^] 和 {spring-security-api}/org/springframework/security/web/authentication/AnonymousAuthenticationFilter.html[AnonymousAuthenticationFilter^] 中的 key。

默认值：`de72c623-6d3d-458c-a187-c526de515ecd`

[[jmix.core.available-locales]]
=== jmix.core.available-locales

定义应用程序中使用的语言环境，用英文逗号分隔。参阅 xref:localization:message-bundles.adoc#setting-locales[配置语言环境] 章节。

示例：

[source,properties]
----
jmix.core.available-locales = en,zh_CN
----

[[jmix.core.conf-dir]]
=== jmix.core.conf-dir

设置配置文件的目录，可以在运行时修改。`Resources` 接口的默认实现会使用该参数，在对 classpath 进行搜索之前先加载该文件夹内的资源文件。

默认值：`${user.dir}/.jmix/conf`

TIP: `${user.dir}` 是用户的工作目录（即 JVM 的启动目录）。

[[jmix.core.cross-data-store-reference-loading-batch-size]]
=== jmix.core.cross-data-store-reference-loading-batch-size

定义为实体集合批量加载 xref:data-model:entities.adoc[跨数据存储引用] 实体的数量。

默认值：`50`


[[jmix.core.default-file-storage]]
=== jmix.core.default-file-storage

如果应用程序使用了 xref:files:file-storage.adoc#multiple-fs[多个文件存储]，用该参数指定默认的文件存储。

[[jmix.core.exclude-beans]]
=== jmix.core.exclude-beans

排除在 Spring 应用程序上下文之外的一组 bean 名称，用逗号分隔。可以用来 xref:modularity:extension.adoc#beans[覆盖] 已经在某些扩展组件中使用了 `@Primary` 注解的 bean。

示例：

[source,properties]
----
jmix.core.exclude-beans = abc_FooService,abc_BarService
----

[[cors]]
== CORS

关于 CORS 的更多信息，参阅 xref:rest:security.adoc#cors[REST 安全] 章节。

[[jmix.cors.allow-credentials]]
=== jmix.cors.allow-credentials

是否支持用户凭证。

默认值：`false`

[[jmix.cors.allowed-headers]]
=== jmix.cors.allowed-headers

预检（pre-flight）请求中给出在实际请求中可以使用的请求头列表。特殊值 “*” 表示允许实际请求发送任何请求头。

默认值：`*`

[[jmix.cors.allowed-methods]]
=== jmix.cors.allowed-methods

允许的 HTTP 方法，例如 "GET"、"POST"、"PUT" 等。特殊值 “*” 表示允许所有方法。

默认值：`*`

[[jmix.cors.allowed-origins]]
=== jmix.cors.allowed-origins

定义 origin 列表，列表中的 origin 可以使用跨域访问。特殊值 “*” 表示允许所有 origin。

例如，`++https://www.allowed1.com, https://www.allowed2.com++`

默认值：`*`
