= Application Properties

[[cors]]
== CORS

See more information on CORS in the xref:rest:security.adoc#cors[REST Security] section.

[[jmix.cors.allow-credentials]]
=== jmix.cors.allow-credentials

Whether user credentials are supported.

Default value: `false`

[[jmix.cors.allowed-headers]]
=== jmix.cors.allowed-headers

The list of headers that a pre-flight request can list as allowed for use during an actual request. The special value "*" allows actual requests to send any header.

Default value: `*`

[[jmix.cors.allowed-methods]]
=== jmix.cors.allowed-methods

The HTTP methods to allow, e.g. "GET", "POST", "PUT", etc.
The special value "*" allows all methods.

Default value: `*`

[[jmix.cors.allowed-origins]]
=== jmix.cors.allowed-origins

Defines a comma-separated list of origins for which cross-origin requests are allowed. Use special value `*` for all origins.

For example: `++https://www.allowed1.com, https://www.allowed2.com++`

Default value: `*`

[[jmix.cors.url-patterns]]
=== jmix.cors.url-patterns

A comma-separated list of URL https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[path patterns^] used for applying CORS settings provided by the properties of this section.

Default value: `/**`

