= Essentials

== Key Concepts

Jmix provides a convenient way of working with one or multiple relational databases. With some additional effort, you can connect to any data source like a no-SQL database or an external API.

Developing with Jmix usually starts from defining the xref:data-model:index.adoc[data model]. Studio creates the database schema from the data model automatically, and when your data model evolves, Studio helps you synchronize the database schema with the model by generating database migration scripts. If you have an existing database already, you can generate the data model from your database schema, also with the help of Studio.

Jmix is based on Spring Framework, so use Spring beans to create the business logic that works with your data model.

As soon as you have some entities in the data model, Studio can generate UI screens for CRUD operations on the entities. Then you can customize the UI in many ways: change the layout, add and remove visual components, adjust the data loading.

== Choosing UI

Jmix provides two options for creating the user interface:

. xref:backoffice-ui:index.adoc[Backoffice UI] allows you to develop the rich web UI using just Java/Kotlin and XML. In this case, you don't have to be familiar with the modern JavaScript/HTML/CSS stack. Also, your UI components work in the same JVM as your backend, which simplifies working with data and invoking business logic.
+
The downside of this technology is limited scalability: the backend side of the UI is stateful and consumes the amount of resources proportional to the number of concurrent user sessions. So Backoffice UI is suitable when you have a predictable and not very high (up to tens of thousands) number of users working with the system at the same time.

. xref:frontend-ui:index.adoc[Frontend UI] allows you to create a traditional frontend with React and TypeScript, working with the Java backend through the REST API. It is more flexible in terms of layout customization and enables easy integration of UI libraries and components from the vast JavaScript ecosystem. It's also infinitely scalable, as the UI state resides in the user's browser and the backend is stateless.
+
On the other hand, the entry barrier to the Frontend UI is higher if you don't have experience in the frontend technologies, and the speed of development is usually lower. This differentiation is amplified by the fact that currently Studio supports Backoffice UI much better than Frontend UI.

Choosing UI is not an "either-or" decision: you can use both technologies in your project. For example, you can quickly create a bunch of administrative screens for internal users of your application with Backoffice UI, and develop a more polished UI with specific functionality for external users using Frontend UI. Both UIs in this case will work with the same data model and business logic.