= Introduction

Welcome to the Jmix documentation!

[[whats-jmix]]
== What is Jmix?

Jmix is a high-level framework for creating enterprise applications. It comes with advanced tooling and a rich set of functional modules.

Jmix is a full-stack framework in the sense that it provides support for creating both backend and the user interface of your application. You develop the backend in Java or Kotlin, and you have different options for creating the UI:

* You can develop the rich web UI using just Java/Kotlin and XML, so you don't have to be familiar with the modern JavaScript/HTML/CSS stack. Also, your UI components work in the same JVM as your backend, which simplifies working with data and invoking business logic.

* You can create a traditional frontend with React and TypeScript, working with the Java backend through the REST API. It is more flexible in terms of layout customization and enables easy integration of UI libraries and components from the vast JavaScript ecosystem.

Jmix is based on https://spring.io/projects/spring-boot[Spring Boot^], which is a de-facto standard for creating enterprise Java web applications. It means that you are not constrained with the functionality provided by Jmix, but you can use a lot of third-party libraries and frameworks with minimal configuration.

Jmix itself consists of a number of fine-grained modules which you include in your project using starters, as you would do for any Spring Boot application. All modules except `jmix-core` are optional, so you can have only dependencies that you really need.

Jmix Studio is a plugin for IntelliJ IDEA that helps you at all stages of the application development: creating and configuring a project, defining data model, generating database migration scripts, developing UI screens in a visual editor. It provides advanced navigation, code completion and inspections specific to Jmix projects.

[[doc-overview]]
== Documentation Overview

If you are new to Jmix, go straight to the xref:getting-started:index.adoc[] section where you will learn how to set up the development environment and create a small fully functioning application.

Check out the xref:studio:index.adoc[] section to get more information about Jmix Studio features and installation options.

The rest of the documentation is organized by topics:

* The xref:ROOT:essentials.adoc[] section contains basic topics that help you develop any kind of application.

* The xref:ROOT:add-ons.adoc[] section describes functional modules that you can use in your project.
