= Введение
:page-aliases: quick-start:index.adoc

Добро пожаловать в документацию https://www.jmix.ru[Jmix^]!

[[whats-jmix]]
== Что такое Jmix?

*Jmix* – это высокоуровневый фреймворк для разработки корпоративных веб-приложений. Он предлагает передовой инструментарий и богатый набор функциональных модулей.

Jmix лучше всего подходит для создания ориентированных на данные приложений со сложной моделью данных и насыщенным пользовательским интерфейсом. Это full-stack фреймворк, что означает поддержку разработки и backend, и UI вашего приложения.

Jmix основан на https://spring.io/projects/spring-boot[Spring Boot^], что является фактически стандартом для разработки корпоративных веб-приложений на Java. Это означает, что вы можете использовать множество сторонних библиотек и фреймворков после минимальной конфигурации в дополнение к функционалу самого Jmix.

*Jmix Studio* – это плагин для IntelliJ IDEA, который помогает на всех этапах разработки приложений: создание и конфигурация проекта, определение модели данных, генерация скриптов для миграции базы данных, разработка UI экранов в визуальном редакторе. Он предоставляет продвинутую навигацию, автодополнение кода и инспекции, специфичные для Jmix-проектов.

[[getting-started]]
== Начало работы

Если вы новичок в Jmix, посмотрите 15-минутное ознакомительное видео: https://www.youtube.com/watch?v=7FGdB7qko3M[Quick Start^].

Пройдите xref:tutorial:index.adoc[] чтобы изучить базовые концепции и приемы программирования на Jmix.

Если вы хотите получить высокоуровневое представление о Jmix перед тем как погрузиться в разработку, взгляните на архитектурные диаграммы, приведенные ниже.

Используйте данную документацию при разработке на Jmix:

* В разделе xref:studio:index.adoc[Использование Studio] детально представлены особенности Jmix Studio и варианты установки.

* Корневые разделы от xref:data-model:index.adoc[Модели данных] до xref:deployment:index.adoc[Развертывания] объясняют основные функции, помогающие при разработке приложений любого типа.

* Раздел xref:ROOT:add-ons.adoc[Дополнения] описывает дополнительные модули, которые вы можете использовать в своем проекте.

[[architecture]]
== Обзор архитектуры

Здесь представлены несколько диаграмм в нотации C4, которые показывают  общую картину ландшафта Jmix.

[[architecture-containers]]
=== Контейнеры

Во-первых, давайте разделим типичную информационную систему, построенную с помощью Jmix, на контейнеры. Контейнер здесь – это отдельно запускаемый / развертываемый модуль, который выполняет код или хранит данные.

image::architecture-containers.drawio.svg[align="center"]

Как видите, основная часть системы включает в себя веб-приложение, работающее на JVM, и реляционную базу данных. Веб-приложение основано на Spring Boot и может быть написано на Java или Kotlin. Реляционная база данных используется для хранения данных подсистем Jmix (например, конфигурации безопасности) и в качестве основного хранилища данных приложений.

Приложение Jmix может подключаться к любому количеству дополнительных хранилищ данных и использовать отдельное файловое хранилище в файловой системе или в облаке. Кроме того, Jmix предлагает интеграцию с Elasticsearch для полнотекстового поиска по данным приложения и с сервером OIDC для внешней аутентификации и единого входа.

Приложение Jmix предоставляет пользователям веб-интерфейс. Он создан на Java/Kotlin и XML с использованием подсистемы пользовательского интерфейса Jmix.

Вы также можете создать отдельное интерфейсное приложение и подключить его к бэкенду Jmix через Jmix REST API или путем создания собственных конечных точек API. Обратите внимание, что интерфейсные приложения выходят за рамки Jmix, и вы можете создавать их с помощью любой технологии по вашему выбору.

[[architecture-components]]
=== Компоненты

Давайте подробнее рассмотрим контейнер Jmix Application и его компоненты.

image::architecture-jmix-application.drawio.svg[align="center"]

Приложение Jmix всегда содержит зависимости от Spring Boot и ряда подсистем Jmix. Существует две категории подсистем Jmix:

* _Основные подсистемы (Core subsystems)_ обеспечивают функциональность системного уровня и включены в большинство проектов.

* _Дополнения (Add-ons)_ – это дополнительные подсистемы, которые могут быть включены в проект по требованию. Они публикуются в https://www.jmix.io/marketplace/[Каталоге дополнений^] Jmix.

Технически, как основные подсистемы, так и дополнения организованы одинаково. Подсистема содержит один или несколько функциональных модулей и соответствующие средства запуска Spring Boot, каждый из которых упакован в JAR-файл. Подсистема может зависеть от других подсистем: например, многие дополнения содержат экраны, которые требуют зависимости от основной подсистемы пользовательского интерфейса.
