= 介绍
:page-aliases: quick-start:index.adoc

欢迎使用 https://www.jmix.cn[Jmix^] 文档！

[[whats-jmix]]
== 什么是 Jmix？

*Jmix* 是企业级 Web 应用程序开发的高级别框架。配备了先进的开发工具和丰富的功能模块。

Jmix 最适合用于构建以数据为中心，且具有复杂数据模型和丰富用户界面的应用程序。从某种意义上说，它是一个全栈框架，能为创建应用程序的后端和 UI 提供支持。

Jmix 基于 https://spring.io/projects/spring-boot[Spring Boot^]，这是创建企业级 Java web 应用程序的事实标准。也就是说，除了使用 Jmix 提供的功能之外，还能以最小的配置使用很多第三方库和框架。

*Jmix Studio* 是 IntelliJ IDEA 的一个插件，可以在整个应用程序开发周期为你提供帮助：创建和配置项目、定义数据模型、生成数据库脚本以及在可视化编辑器开发 UI 界面。更是为 Jmix 项目提供了代码的高级导航、自动完成和提示功能。

[[getting-started]]
== 开始使用

如果你之前没有接触过 Jmix，请先观看我们的 https://www.bilibili.com/video/BV1tm4y1R7wm[快速入门^] 视频，花 15 分钟了解下如何使用 Jmix 构建应用程序。

完成 xref:tutorial:index.adoc[]，学习使用 Jmix 编程的基础概念和技术要求。

如果在开始编写代码前需要了解 Jmix 高级别的概念，请参考下面的架构介绍。

本文档包含使用 Jmix 开发需要了解的所有内容：

* xref:studio:index.adoc[] 章节详细介绍了 Jmix Studio 的功能和安装选项。

* 从 xref:data-model:index.adoc[] 至 xref:deployment:index.adoc[] 的章节是主要内容，包含开发任何应用程序所需要了解的内容。

* xref:ROOT:add-ons.adoc[] 章节介绍了项目中能用到的附加模块功能。

[[architecture]]
== 架构概览

这里我们采用 C4 模型表示法，展示 Jmix 架构的鸟瞰图。

[[architecture-containers]]
=== 容器

首先，我们将一个用 Jmix 构建的典型信息系统划分成不同的容器。这里的容器是指可以单独运行/部署的单元，负责执行代码或者存储数据。

image::architecture-containers.drawio.svg[align="center"]

可以看到，系统的主要部分包括运行在 JVM 上的 Web 应用程序以及一个关系型数据库。Web 应用程序基于 Spring Boot，支持用 Java 或 Kotlin 编写。关系型数据库用于保存 Jmix 子系统的数据（例如，安全配置）以及作为应用程序数据的主要存储。

Jmix 应用程序可以与多个附加数据存储连接，并支持使用文件系统或云环境作为独立的文件存储。此外，Jmix 还支持集成 Elasticsearch 实现对应用程序数据的全文检索功能，支持通过 OIDC 服务进行外部认证和单点登录（SSO）。

Jmix 应用程序为用户提供 web 界面，界面使用 Jmix UI 子系统通过 Java/Kotlin 和 XML 创建。

你也可以创建独立的前端应用，通过 Jmix REST API 或创建自己的接口与 Jmix 后端连接。这里的前端应用并不在 Jmix 的范围内，你可以选择任何技术进行构建。

[[architecture-components]]
=== 组件

我们更进一步进入 Jmix 容器内了解其内部组件。

image::architecture-jmix-application.drawio.svg[align="center"]

Jmix 应用程序始终包含对 Spring Boot 和其他 Jmix 子系统的依赖关系。Jmix 有两类子系统：

* _核心子系统_ 提供系统级别的功能，包含在绝大多数项目中。

* _扩展组件_ 是可选的子系统，根据需要添加至项目中。扩展组件在 Jmix https://www.jmix.io/marketplace/[市场^] 发布。

技术上来说，核心子系统和扩展组件都是以相同的方式进行组织。子系统包含一个或多个功能模块以及对应的 Spring Boot starter，均以 JAR 文件格式打包。子系统可以依赖其他子系统，例如，很多包含界面的扩展组件依赖核心 UI 子系统。

