= Introduction
:page-aliases: quick-start:index.adoc

Welcome to the https://www.jmix.io[Jmix^] documentation!

[[whats-jmix]]
== What is Jmix?

*Jmix* is a high-level framework for enterprise web applications. It comes with advanced tooling and a rich set of functional modules.

Jmix is best suited for creating data-centric applications with a complex data model and rich user interface. It is a full-stack framework in the sense that it provides support for creating both the backend and UI of your application.

Jmix is based on https://spring.io/projects/spring-boot[Spring Boot^], which is a de-facto standard for creating enterprise Java web applications. It means that you can use a lot of third-party libraries and frameworks with minimal configuration, in addition to the functionality provided by Jmix.

//Jmix itself consists of a number of fine-grained modules that you include in your project using starters, as you would do for any Spring Boot application. All modules except the core one are optional, so you can have only dependencies that you really need.

*Jmix Studio* is a plugin for IntelliJ IDEA that helps you at all stages of the application development: creating and configuring a project, defining data model, generating database migration scripts, developing UI screens in a visual editor. It provides advanced navigation, code completion and inspections specific to Jmix projects.

//[[key-concepts]]
//== Key Concepts
//
//Jmix provides a convenient way of working with one or multiple relational databases. With some additional effort, you can connect to any data source like a no-SQL database or an external API.
//
//Developing with Jmix usually starts from defining the xref:data-model:index.adoc[data model]. Jmix Studio creates the database schema from the data model automatically, and when your data model evolves, Studio helps you synchronize the database schema with the model by generating database migration scripts. If you have an existing database already, you can generate the data model from your database schema, also with the help of Studio.
//
//Jmix is based on Spring Framework, so use Spring beans to create the business logic that works with your data model.
//
//As soon as you have some entities in the data model, Studio can generate xref:ui:index.adoc[UI] screens for CRUD operations on the entities. Then you can customize the UI in many ways: change the layout, add and remove visual components, adjust the data loading.

//[[choosing-ui]]
//=== Choosing UI
//
//You can use any frontend technology to work with Jmix backend through its xref:rest:index.adoc[] or custom endpoints of your application.
//
//Moreover, Jmix provides two specific options for rapid creation of the user interface:
//
//. xref:backoffice-ui:index.adoc[Backoffice UI] allows you to develop the rich web UI using just Java/Kotlin and XML. In this case, your UI components work in the same JVM as your backend, which simplifies working with data and invoking business logic. Also, you don't have to be familiar with the modern JavaScript/HTML/CSS stack.
//+
//The downside of this technology is limited scalability: the backend side of the UI is stateful and consumes the amount of resources proportional to the number of concurrent user sessions. So Backoffice UI is suitable when you have a predictable and not very high (up to tens of thousands) number of users working with the system at the same time.
//
//
//. xref:jmix-frontend-docs:overview:index.adoc[Frontend UI] allows you to create a traditional frontend with React and TypeScript, working with the Java backend through the REST API. It is more flexible in terms of layout customization and enables easy integration of UI libraries and components from the vast JavaScript ecosystem. It's also infinitely scalable, as the UI state resides in the user's browser and the backend is stateless.
//+
//On the other hand, the entry barrier to the Frontend UI is higher if you don't have experience in frontend technologies, and the speed of development is usually lower. This differentiation is amplified by the fact that currently Studio supports Backoffice UI much better than Frontend UI.
//
//Choosing UI is not an "either-or" decision: you can use both technologies in your project. For example, you can quickly create a bunch of administrative screens for internal users of your application with Backoffice UI, and develop a more polished UI with specific functionality for external users using Frontend UI. Both UIs in this case will work with the same data model and business logic.

[[getting-started]]
== Getting Started

If you are new to Jmix, xref:setup.adoc[set up] your development environment and check out the https://www.jmix.io/learn/quickstart/studio[Quick Start^] video for a 15-minute introduction to building applications.

After completing the quick start guide, explore the https://www.jmix.io/learn/live-demo/[demo applications^] and look at the https://www.jmix.io/marketplace/[add-ons^] to get a sense of what is available in Jmix out-of-the-box.

If you want to learn more about Jmix concepts before diving into code, see the architecture overview below.

The documentation contains everything you need to know for developing with Jmix:

* xref:studio:index.adoc[] section gives you detailed information about Jmix Studio features and installation options.

* The top-level sections from xref:data-model:index.adoc[] to xref:deployment:index.adoc[] explain basic topics that help you develop any kind of application.

* The xref:ROOT:add-ons.adoc[] section describes additional modules that can be used in your project.

== Architecture Overview

Here you can find a few diagrams in C4 Model notation that show a birds eye view of the Jmix landscape.

=== Containers

First, let's divide a typical information system built with Jmix into containers. A container here is a separately runnable/deployable unit that executes code or stores data.

image::architecture-containers.drawio.svg[align="center"]

As you can see, the main part of the system includes a web application running on JVM and a relational database. The web application is based on Spring Boot and can be written in Java or Kotlin. A relational database is used to store data of Jmix subsystems (for example, security configuration) and as a main storage of application data.

The Jmix application can connect to any number of additional data stores and use a separate file storage on a file system or in the cloud. Also, Jmix offers integrations with Elasticsearch for full-text search through the application data, and with an OIDC server for external authentication and SSO.

The Jmix application provides users with a web interface. It's created in Java/Kotlin and XML using the Jmix UI subsystem.

You can also create a separate frontend application and connect it with the Jmix backend through the Jmix REST API or by creating custom endpoints. Note that frontend applications are out of Jmix scope, you can create them with any technology of your choice.

=== Components

Let's zoom in to the Jmix Application container and explore its components.

image::architecture-jmix-application.drawio.svg[align="center"]

A Jmix application always contains dependencies to Spring Boot and to a number of Jmix subsystems. There are two categories of Jmix subsystems:

* _Core subsystems_ provide system-level functionality and are included in most projects.

* _Add-ons_ are optional subsystems that can be included in the project on demand. The add-ons are published at Jmix https://www.jmix.io/marketplace/[marketplace^].

Technically, both core subsystems and add-ons are organized in the same way. A subsystem contains one or more functional modules and corresponding Spring Boot starters, each packaged in a JAR file. A subsystem can depend on other subsystems: for example, many add-ons contain screens that require dependency on the core UI subsystem.
