## Execute 'authenticate.http' first to get have a valid access token for the API

# Create multiple Customers

POST {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

[
  {
    "name": "Klaudia Klüvert"
  },
  {
    "name": "Sarah Doogle"
  }
]


> {%

    client.test("Response Code is 201", function() {
      client.assert(
          response.status === 201,
          "Response status is not 201 - Created"
      );
    });

    client.test("new Entities are returned", function() {
      client.assert(
          response.body.length == 2,
          "there are two entities created"
      );


      client.global.set("firstCustomerId", response.body[0]["id"])
      client.global.set("secondCustomerId", response.body[1]["id"])
    });
  %}

###

DELETE {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

[
  {
    "id": "{{firstCustomerId}}"
  },
  {
    "id": "{{secondCustomerId}}"
  }
]

> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });

    client.test("updated Entities are returned", function() {
      client.assert(
          response.body.length == 2,
          "there are two entities created"
      );
    });
  %}


###

DELETE {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

[
  "6a669bb0-d954-cea3-55a5-ed02300bbbe6",
  "6a669bb0-d954-cea3-55a5-ed02300bbbe7"
]

> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });
  %}

