## Execute 'authenticate.http' first to get have a valid access token for the API

# Create a Customer

POST {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

{
  id: "13f01f59-8e5f-4fd9-802b-66501d49ac99",
  createdBy: "hans-wurst",
  name: "Randall Bishop Wurst"
}

> {%

    client.test("Response Code is 201", function() {
      client.assert(
          response.status === 201,
          "Response status is not 201 - Created"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body["id"],
          "ID Attribute of an Entity is not returned"
      );
    });

    client.global.set("customerId", response.body["id"])
  %}

###
DELETE {{baseRestUrl}}
         /entities
         /rstex11_Customer
         /{{customerId}}
Authorization: Bearer {{access_token}}


> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });
  %}
