= Entity Log

Entity Log is a mechanism for tracking changes in your JPA entities. It records changes in entity attributes and provides a user interface for searching and displaying information about the changes:

* What entity instance was changed.
* Old and new values of changed attributes.
* When the entity was changed.
* Which user changed the entity.

[[installation]]
== Installation

Follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section to install the add-on into your application.

[[usage]]
== Usage

Entity Log automatically tracks changes of JPA entities when they are saved using xref:data-access:data-manager.adoc[DataManager]. It doesn't work if you use `EntityManager` or native SQL.

You can also use the `EntityLog` bean to register changed entities from your application code. In this case, invoke `registerCreate()`, `registerModify()` and `registerDelete()` methods with `auto` parameter set to false. When the entity log is called automatically by the framework, this parameter is set to true.
