= FullCalendar component

`FullCalendar` is a UI component designed to display date ranges and calendar events.
It has a lot of features for managing calendar events and various views (day, week, etc).

[cols="1h,6",grid=none]
|===

|XML Element |`calendar`

|XML Schema | `http://jmix.io/schema/fullcalendar/ui`

|XML namespace | `calendar`

|Java Class |`FullCalendar`

|Attributes

|xref:flow-ui:vc/common-attributes.adoc#id[id] -
<<allDayMaintainDurationEnabled, allDayMaintainDurationEnabled>> -
xref:flow-ui:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:flow-ui:vc/common-attributes.adoc#classNames[classNames] -
xref:flow-ui:vc/common-attributes.adoc#colspan[colspan] -
xref:flow-ui:vc/common-attributes.adoc#css[css] -
<<dateAlignment, dateAlignment>> -
<<dayHeadersVisible, dayHeadersVisible>> -
<<dayMaxEventRows, dayMaxEventRows>> -
<<dayMaxEvents, dayMaxEvents>> -
<<defaultAllDay, defaultAllDay>> -
<<defaultAllDayEventDuration, defaultAllDayEventDuration>> -
<<defaultBusinessHoursEnabled, defaultBusinessHoursEnabled>> -
<<defaultDayHeaderFormat, defaultDayHeaderFormat>> -
<<defaultDayMaxEventRowsEnabled, defaultDayMaxEventRowsEnabled>> -
<<defaultDayMaxEventsEnabled, defaultDayMaxEventsEnabled>> -
<<defaultDayPopoverFormat, defaultDayPopoverFormat>> -
<<defaultEventTimeFormat, defaultEventTimeFormat>> -
<<defaultSlotLabelFormat, defaultSlotLabelFormat>> -
<<defaultTimedEventDuration, defaultTimedEventDuration>> -
<<defaultWeekNumberFormat, defaultWeekNumberFormat>> -
<<displayEventTime, displayEventTime>> -
<<dragRevertDuration, dragRevertDuration>> -
<<dragScroll, dragScroll>> -
<<eventBackgroundColor, eventBackgroundColor>> -
<<eventBorderColor, eventBorderColor>> -
<<eventConstraintBusinessHoursEnabled, eventConstraintBusinessHoursEnabled>> -
<<eventConstraintGroupId, eventConstraintGroupId>> -
<<eventDisplay, eventDisplay>> -
<<eventDragMinDistance, eventDragMinDistance>> -
<<eventDurationEditable, eventDurationEditable>> -
<<eventInteractive, eventInteractive>> -
<<eventLongPressDelay, eventLongPressDelay>> -
<<eventMaxStack, eventMaxStack>> -
<<eventOrder, eventOrder>> -
<<eventOrderStrict, eventOrderStrict>> -
<<eventOverlap, eventOverlap>> -
<<eventResizableFromStart, eventResizableFromStart>> -
<<eventStartEditable, eventStartEditable>> -
<<eventTextColor, eventTextColor>> -
<<expandRows, expandRows>> -
<<firstDayOfWeek, firstDayOfWeek>> -
<<forceEventDuration, forceEventDuration>> -
xref:flow-ui:vc/common-attributes.adoc#height[height] -
<<initialDate, initialDate>> -
<<initialDisplayMode, initialDisplayMode>> -
xref:flow-ui:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:flow-ui:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:flow-ui:vc/common-attributes.adoc#minHeight[minHeight] -
xref:flow-ui:vc/common-attributes.adoc#minWidth[minWidth] -
<<moreLinkClassNames, moreLinkClassNames>> -
<<moreLinkDisplayMode, moreLinkDisplayMode>> -
<<navigationLinksEnabled, navigationLinksEnabled>> -
<<nextDayThreshold, nextDayThreshold>> -
<<nowIndicatorVisible, nowIndicatorVisible>> -
<<progressiveEventRendering, progressiveEventRendering>> -
<<scrollTime, scrollTime>> -
<<scrollTimeReset, scrollTimeReset>> -
<<selectConstraintBusinessHoursEnabled, selectConstraintBusinessHoursEnabled>> -
<<selectConstraintGroupId, selectConstraintGroupId>> -
<<selectLongPressDelay, selectLongPressDelay>> -
<<selectMinDistance, selectMinDistance>> -
<<selectMirror, selectMirror>> -
<<selectOverlap, selectOverlap>> -
<<selectionEnabled, selectionEnabled>> -
<<slotDuration, slotDuration>> -
<<slotLabelInterval, slotLabelInterval>> -
<<slotMaxTime, slotMaxTime>> -
<<slotMinTime, slotMinTime>> -
<<snapDuration, snapDuration>> -
<<unselectAuto, unselectAuto>> -
<<unselectCancelSelector, unselectCancelSelector>> -
xref:flow-ui:vc/common-attributes.adoc#visible[visible] -
<<weekNumbersVisible, weekNumbersVisible>> -
<<weekendsVisible, weekendsVisible>> -
xref:flow-ui:vc/common-attributes.adoc#width[width] -
<<windowResizeDelay, windowResizeDelay>>

|Elements
|<<dataProviders, dataProviders>>

|===

== Basic

`FullCalendar` component is available in the *Add Component* palette of the Studio xref:studio:view-designer.adoc[View Designer] as soon as you install add-on in your project.

To create the component, use `calendar` XML element.
If you need to show events, bind `containerEventProvider` to xref:flow-ui:data/data-containers.adoc[data container].

The following example demonstrates how a basic `calendar` is created:

[source,xml,indent=0]
----
include::example$fullcalendar-ex2/src/main/resources/com/company/fullcalendarsample/view/demos/sample-basic.xml[tags=sample-basic1]
----

== Data Binding

=== CalendarEvent

==== EntityCalendarEvent

==== SimpleCalendarEvent

=== CalendarEventProvider

==== ContainerEventProvider

==== ListEventProvider

=== LazyCalendarEventProvider

==== Default

==== Abstract class

== Calendar Display Modes

=== Predefined Display Modes

=== Display Mode Properties

=== CustomCalendarDisplayMode

== Selection

== Event editing

== Styling

== ContextMenu

== Business Hours

== Attributes

In Jmix there are many xref:flow-ui:vc/common-attributes.adoc[common attributes] that serve the same purpose for all components.
The following are attributes specific to `calendar`:

[cols="1h,5,1",grid=rows,frame=none]
|===
|*Name*|*Description*|*Default*

|[[allDayMaintainDurationEnabled]]allDayMaintainDurationEnabled
| Determines how an event’s duration should be mutated when it is dragged from a timed section to an all-day section and vice versa.

- `true` - the duration will remain roughly the same before and after it is dragged to or from an all-day section. "Roughly" because if an event has a duration with hourly precision, it will be rounded down to the nearest whole-day.

- `false` - the event’s duration will be reset to getDefaultAllDayEventDuration() if it is being dropped in an all-day section or getDefaultTimedEventDuration() if it is being dropped in a timed section

| `false`

|[[dateAlignment]]dateAlignment
| Sets the first visible date of <<CustomCalendarDisplayMode>>.

 When a custom calendar display mode is being used, and you’d like to guarantee that the calendar begins at a certain interval, like the start-of-week or start-of-month, specify a value like `week` or `month`. If the property is not specified, a reasonable default will be generated based on the display mode’s duration.

If a display mode’s range is explicitly defined by visible date range, this property will be ignored.
|

|[[dayHeadersVisible]]dayHeadersVisible
| Sets whether the day headers should appear. It works for day-grid, time-grid and month display modes.
| `true`

|[[dayMaxEventRows]]dayMaxEventRows
| Sets rows count of events in day-grid display modes and in "all-day" section in time-grid display modes.

 Note that "+x more" row is included to count. For instance, if the value is `1`, only the "+x more" row will be shown. Takes precedence over the <<defaultDayMaxEventRowsEnabled, defaultDayMaxEventRowsEnabled>>.
|

|[[dayMaxEvents]]dayMaxEvents
| Sets rows count of events in day-grid display modes and in "all-day" section in time-grid display modes.

 Note that "+ more" row is not included to count. For instance, if the value is  `1`, one event and the "+x more" row will be shown. Takes precedence over the <<defaultDayMaxEventsEnabled, defaultDayMaxEventsEnabled>>.
|

|[[defaultAllDay]]defaultAllDay
| Sets the default value for each calendar event's `allDay` property when it is unspecified.

 If the property is set to `true`, all events without `allDay` property (e.g. is not specified mapping in a data provider or calendar event returns `null` for this property) will be considered as all-day events.

 Note, in this case, events without `allDay` property will be shown as all-day events. If such event will be changed by dragging or resizing, and you have listeners for these events, the component will apply changes to a calendar event, which can lead to modifying entity/ DTO instance.
| `false`

|[[defaultAllDayEventDuration]]defaultAllDayEventDuration
| Sets the default duration of all-day events if they don't specify `endDateTime` property.

For instance, the property is set to 2 days. The event that has `allDay` property equals to `true` and do not have `endDateTime` property, will be shown in all-day section and will occupy two days.

 Note, calendar event's `endDateTime` property will remain unset, unless <<forceEventDuration, forceEventDuration>> has been set to `true`. In this case, the calendar will explicitly assign end date-time to an event. If such event will be changed by dragging or resizing, and you have listeners for these events, the component will set to calendar event end date-time value, which can lead to modifying entity/ DTO instance.

 This property only affects events with `allDay` property equals to `true`.
| `P1d`

|[[defaultBusinessHoursEnabled]]defaultBusinessHoursEnabled
| Enables default business hours. The default business hour is: `monday - friday` from `9 AM` to `5 PM`.
| `false`

|[[defaultDayHeaderFormat]]defaultDayHeaderFormat
| Sets the format of the text that will be displayed on the calendar’s column headings.

 By default, component sets localized format from `messages` when is created.
This property act as default format for all display modes and for <<CustomCalendarDisplayMode>> until specific property won't be set for these display modes. However, all display-mode properties objects by default explicitly specify the format, thus they override this property.

As component uses https://fullcalendar.io/docs/moment-plugin[moment plugin] for `FullCalendar`, we should follow the `moment.js` formatting rules: https://momentjs.com/docs/#/displaying/format/[Moment. js Documentation]. For instance, the `dd` produces the `Mo` value.

The property change is not applied after component attached to the UI.
|

|[[defaultDayMaxEventRowsEnabled]]defaultDayMaxEventRowsEnabled
| Limits the maximum number of stacked events within a given day.

- `true` - limits the number of events by height of the day cell.

- `false` - component displays all events as is.

 This property is applied for day-grid display modes and in all-day cells.
| `false`

|[[defaultDayMaxEventsEnabled]]defaultDayMaxEventsEnabled
| Limits the maximum number of stacked events within a given day.

- `true` - limits the number of events by height of the day cell.

- `false` - component displays all events as is.

This property is applied for day-grid display modes and in all-day cells.
| `false`

|[[defaultDayPopoverFormat]]defaultDayPopoverFormat
| Sets the date format of title of the popover that is shown when "more" link is clicked. By default, component sets localized format from `messages` when is created.

This property act as default format for all display modes and for <<CustomCalendarDisplayMode>> until specific property won't be set for these display modes. However, all display-mode properties objects by default explicitly specify the format, thus they override this property.

As component uses href="https://fullcalendar.io/docs/moment-plugin[moment plugin] for `FullCalendar`, we should follow the `moment.js` formatting rules: https://momentjs.com/docs/#/displaying/format/[Moment.js Documentation]. For instance, the `MMM D, YY` produces the `Sep 9, 24` value.

The property change is not applied after component attached to the UI.
|

|[[defaultEventTimeFormat]]defaultEventTimeFormat
| Sets the format of the time-text that will be displayed on each event. By default, component sets localized format from `messages` when is created.

 This property act as default format for all display modes and for <<CustomCalendarDisplayMode>> until specific property won't be set for these display modes. However, all display-mode properties objects by default explicitly specify the format, thus they override this property.

 As component uses https://fullcalendar.io/docs/moment-plugin[moment plugin] for `FullCalendar`, we should follow the `moment.js` formatting rules: https://momentjs.com/docs/#/displaying/format/[Moment.js Documentation]. For instance, the `HH:mm` produces the `00:00` (01, 2, ... 23 : 01, 02 ... 59).

 The property change is not applied after component attached to the UI.
|

|[[defaultSlotLabelFormat]]defaultSlotLabelFormat
| Sets the format of the text that will be displayed within a time slot. By default, component sets localized format from `messages` when is created.

 This property act as default format for all display modes and for <<CustomCalendarDisplayMode>> until specific property won't be set for these display modes. However, all display-mode properties objects by default explicitly specify the format, thus they override this property.

 As component uses https://fullcalendar.io/docs/moment-plugin[moment plugin] for `FullCalendar`, we should follow the `moment.js` formatting rules: https://momentjs.com/docs/#/displaying/format/[Moment.js Documentation]. For instance, the `ha` produces `1 am` (1, 2, ... 12 am/ pm).

 The property change is not applied after component attached to the UI.
|

|[[defaultTimedEventDuration]]defaultTimedEventDuration
| Sets the default duration for timed events if they don't specify `endDateTime` property.

 For instance, the property is set to 2 hours. The event that has `allDay` propery equals to  `false` and do not have `endDateTime` property, will occupy two hours in time slots.

 Note, calendar event's `endDateTime` property will remain unset, unless <<forceEventDuration, forceEventDuration>> has been set to `true`. In this case, the calendar will explicitly assign end date to an event. If such event will be changed by dragging or resizing, and you have listeners for these events, the component will set new value to calendar event's `endDateTime` property, which can lead to modifying entity/ DTO instance.

This property only affects events with `allDay` property equals to `false`.
| `PT1h`

|[[defaultWeekNumberFormat]]defaultWeekNumberFormat
| Sets the format of the week number that will be displayed when <<weekNumbersVisible, weekNumbersVisible>> is `true`. By default, component sets localized format from `messages` when is created.

 This property act as default format for all display modes and for <<CustomCalendarDisplayMode>> until specific property won't be set for these display modes. However, all display-mode properties objects by default explicitly specify the format, thus they override this property.

 As component uses https://fullcalendar.io/docs/moment-plugin[moment plugin] for `FullCalendar`, we should follow the `moment.js` formatting rules: https://momentjs.com/docs/#/displaying/format/[Moment.js Documentation]. For instance, the `[Week] w` produces the `Week 1` (1, 2, ... 52, 53).

The property change is not applied after component attached to the UI.
|

|[[displayEventTime]]displayEventTime
| Determines visibility of time text of each event.

 The property applies to timed-events (not all-day). If set to `true`, time text will always be displayed on the event. If set to `false`, time text will never be displayed on the event. Events that are all-day will never display time text anyhow.
| `true`

|[[dragRevertDuration]]dragRevertDuration
| Sets the time it takes for an event to revert to its original position after an unsuccessful drag.
| `500`

|[[dragScroll]]dragScroll
| Enables to automatically scroll the scroll-containers during event drag-and-drop and date selecting.

 The property change is not applied after component attached to the UI.
| `true`

|[[eventBackgroundColor]]eventBackgroundColor
| Sets the background color for all events on the calendar.

 Note, calendar events can override this value if they specify `backgroundColor` property.

 Supported values are:

- `#f00`

- `#ff0000`

- `rgb(255,0,0)`

- Color name - `red`
|

|[[eventBorderColor]]eventBorderColor
| Sets the border color for all events on the calendar.

 Note, calendar events can override this value if they specify `borderColor` property.

 Supported values are:

- `#f00`

- `#ff0000`

- `rgb(255,0,0)`

- Color name - `red`
|

|[[eventConstraintBusinessHoursEnabled]]eventConstraintBusinessHoursEnabled
| Sets whether events being dragged or resized must be fully contained within the week’s business hours.

 It also respects custom business hours.
| `false`

|[[eventConstraintGroupId]]eventConstraintGroupId
| Sets a group ID to limit the dragging and resizing of events. Events that are being dragged or resized must be fully contained by at least one of the events linked to by the given group ID.

Takes precedence over <<eventConstraintBusinessHoursEnabled, eventConstraintBusinessHoursEnabled>>.

The group ID can be an entity instance, string, enum or other types.
|

|[[eventDisplay]]eventDisplay
| Sets the display mode that controls the appearance of all events that do not specify display mode.

 To control the display of specific events, use the `display` property of calendar event.
| `AUTO`

|[[eventDragMinDistance]]eventDragMinDistance
| Sets how many pixels the user’s mouse/touch must move before an event drag activates.
| `5`

|[[eventDurationEditable]]eventDurationEditable
| // todo
| `false`

|[[eventInteractive]]eventInteractive
| Enables to edit event duration using resizing

 Note, this property can be overridden on per-event by `durationEditable` property.
| `false`

|[[eventLongPressDelay]]eventLongPressDelay
| Sets amount of time in milliseconds the user must hold down before an event becomes draggable.

 For touch devices.
| `1000`

|[[eventMaxStack]]eventMaxStack
| Sets the maximum number of events that stack top-to-bottom for time-grid display modes.
|

|[[eventOrder]]eventOrder
| Sets the list of calendar event properties that should participate in sorting. It is also available to specify properties from event's `additionalProperties`.

For most calendar display modes, this property determines the vertical ordering of events within the same day. For time-grid display modes however, it determines the horizontal ordering of events within the same time slot.

The default value puts earlier events first. If tied, it puts longer events first. If still tied, it puts all-day events first. If still tied, orders events by title, alphabetically.

If putting a lower-precedent event before a higher-precedent improves compactness, the algorithm will do so. To disable this behavior, set <<eventOrderStrict, eventOrderStrict>> to `true`.

The provided properties are sorted in ascending order. If a property is prefixed with a minus sign like `-title`, sorting will be in descending order.
| `start,-duration,allDay,title`

|[[eventOrderStrict]]eventOrderStrict
| Enables the component to strictly follow the specified event order.

 The `false` value, meaning the event order is not strict and compactness will be prioritized over following event order exactly.
| `false`

|[[eventOverlap]]eventOverlap
| Allows events to overlap each other during dragging and resizing.
| `true`

|[[eventResizableFromStart]]eventResizableFromStart
| Enables to resize an event from its starting date.
| `false`

|[[eventStartEditable]]eventStartEditable
| Enables to edit event start time using dragging.

 Note, this property can be overridden on per-event by `startEditable` property.
| `false`

|[[eventTextColor]]eventTextColor
| Sets the text color for all events on the calendar.

 Note, calendar events can override this value if they specify `textColor` property.

 Supported values are:

 - `#f00`

 - `#ff0000`

 - `rgb(255,0,0)`

 - Color name - `red`

The color applies in time-grid display modes and for all-day events in day-grid display modes.
|

|[[expandRows]]expandRows
| Enables to expand rows of time-grid display modes if they don’t take up the entire height.
| `false`

|[[firstDayOfWeek]]firstDayOfWeek
| Sets the day that each week begins. The default value is taken from locale.
|

|[[forceEventDuration]]forceEventDuration
| Makes the component to assign `endDateTime` property value to events if they do not have it.

 Note, if event does not specify `endDateTime` property, the component will set it explicitly. If such event will be changed by dragging or resizing, and you have listeners for these events, the component will set new value to calendar event `endDateTime` property, which can lead to modifying entity/ DTO instance.
| `false`

|[[initialDate]]initialDate
| Sets the initial date that will be displayed when the component is attached to UI. If not specified, the current date will be used.

 The property change is not applied after component attached to the UI.
|

|[[initialDisplayMode]]initialDisplayMode
| Sets initial calendar display mode that will be shown after attaching component to th UI.

 The property change is not applied after component attached to the UI.
| `DAY_GRID_MONTH`

|[[moreLinkClassNames]]moreLinkClassNames
| Sets CSS class names that should be added to "more" link.
|

|[[moreLinkDisplayMode]]moreLinkDisplayMode
| Sets the calendar display mode that should be shown when "more" link is clicked.
|

|[[navigationLinksEnabled]]navigationLinksEnabled
| Enables navigation to date using day names and week names.
| `false`

|[[nextDayThreshold]]nextDayThreshold
| Sets the minimum time that event's `endDateTime` property should achieve to render event as it if were on that day.

 For instance, the property is set to `09:00:00`. And there is an event with dates:

 - start - `2024-09-01T20:00:00`;

 - end - `2024-09-02T02:00:00`;

So, the event spans to another day, but it will be rendered as a one-day event, because we specified the `nextDayThreshold` property. However, If the event has end date - `2024-09-02T10:00:00`, it will be rendered as two-day event.

Only affects timed events that appear on whole-days cells. Whole-day cells occur in day-grid display modes and the all-day slots in the time-grid display modes.

Note that this property is ignored when event's `allDay` property is set to `true`.
|

|[[nowIndicatorVisible]]nowIndicatorVisible
| Enables displaying a marker indicating the current time. The property applies in time-grid display modes.

 The property change is not applied after component attached to the UI.
| `false`

|[[progressiveEventRendering]]progressiveEventRendering
| // todo
| `false`

|[[scrollTime]]scrollTime
| // todo
| `PT6h`

|[[scrollTimeReset]]scrollTimeReset
| // todo
| `true`

|[[selectConstraintBusinessHoursEnabled]]selectConstraintBusinessHoursEnabled
| // todo
| `false`

|[[selectConstraintGroupId]]selectConstraintGroupId
| // todo
|

|[[selectLongPressDelay]]selectLongPressDelay
| // todo
| `1000`

|[[selectMinDistance]]selectMinDistance
| // todo
| `0`

|[[selectMirror]]selectMirror
| // todo
| `false`

|[[selectOverlap]]selectOverlap
| // todo
| `true`

|[[selectionEnabled]]selectionEnabled
| // todo
| `false`

|[[slotDuration]]slotDuration
| // todo
| `PT30m`

|[[slotLabelInterval]]slotLabelInterval
| // todo
|

|[[slotMaxTime]]slotMaxTime
| // todo
| `PT24h`

|[[slotMinTime]]slotMinTime
| // todo
| `PT0h`

|[[snapDuration]]snapDuration
| // todo
| `PT30m`

|[[unselectAuto]]unselectAuto
| // todo
| `true`

|[[unselectCancelSelector]]unselectCancelSelector
| // todo
|

|[[weekNumbersVisible]]weekNumbersVisible
| // todo
| `false`

|[[weekendsVisible]]weekendsVisible
| // todo
| `true`

|[[windowResizeDelay]]windowResizeDelay
| // todo
| `100`

|===

== Handlers

In Jmix there are many xref:flow-ui:vc/common-handlers.adoc[common handlers] that are configured in the same way for all components.
The following are handlers specific to `calendar`:

include::flow-ui:vc/handler-generation-tip.adoc[]

[cols="1h,6",grid=rows,frame=none]
|===
|*Name*|*Description*

|[[DateClickEvent]]DateClickEvent
| // todo

|[[DatesSetEvent]]DatesSetEvent
| // todo

|[[EventClickEvent]]EventClickEvent
| // todo

|[[EventDropEvent]]EventDropEvent
| // todo

|[[EventMouseEnterEvent]]EventMouseEnterEvent
| // todo

|[[EventMouseLeaveEvent]]EventMouseLeaveEvent
| // todo

|[[EventResizeEvent]]EventResizeEvent
| // todo

|[[MoreLinkClickEvent]]MoreLinkClickEvent
| // todo

|[[SelectEvent]]SelectEvent
| // todo

|[[UnselectEvent]]UnselectEvent
| // todo

|[[dayCellClassNamesGenerator]]dayCellClassNamesGenerator
| // todo

|[[dayHeaderClassNamesGenerator]]dayHeaderClassNamesGenerator
| // todo

|[[moreLinkClassNamesGenerator]]moreLinkClassNamesGenerator
| // todo

|[[nowIndicatorClassNamesGenerator]]nowIndicatorClassNamesGenerator
| // todo

|[[slotLabelClassNamesGenerator]]slotLabelClassNamesGenerator
| // todo

|===

== Elements

Elements of `calendar` provide a wide range of options to control the appearance, behavior, formatting, data binding and other functionality.

[TIP]
====
To add an element to a selected component click the xref:studio:screen-designer.adoc#component-inspector[Add] button in the *Jmix UI* inspector panel.
====

// todo elements

== See Also

See the https://fullcalendar.io/docs[FullCalendar Docs^] for more information.