= Удаление сущностей

Наконец, Entities API позволяет удалять сущности из приложения. Соответствующая операция – `/entities/:entityName/:entityId` с использованием HTTP метода `DELETE`.

[[delete-entity]]
== Удалить сущность

В следующем примере мы удалим ранее созданный Customer:

[source, http request]
.Request
----
DELETE http://localhost:8080/rest
            /entities
            /sample_Customer
            /13f01f59-8e5f-4fd9-802b-66501d49ac99
----

Если сущность существует, возвращается статус `200 - OK` без тела ответа, и сущность удаляется из приложения. В случае, если сущность не найдена, возвращается `404 - Not Found`.

TIP: Entities API принимает во внимание xref:data-model:soft-deletion.adoc[мягкое удаление]. В зависимости от настройки сущности ее экземпляр удаляется из базы данных либо мягко, либо полностью.

[[bulk-delete]]
== Массовое удаление

Delete Entity API также позволяет удалять несколько сущностей в одном запросе. Для этого тело запроса JSON должно содержать массив идентификаторов, представляющих каждую сущность.

[source, http request]
.Bulk Update Request
----
DELETE http://localhost:8080/rest
            /entities
            /sample_Customer

[
  "3b9a1d43-1397-d2ae-eedd-f79eec1b81e2",
  "20ba4218-6690-c14c-9453-9ccd4b0add37"
]
----

Если все сущности могут быть удалены, возвращается код ответа HTTP `200 - OK`.

////
NOTE: All entities of the Bulk API are processed as part of one database transaction. This means if there is a validation violation in at least one of the entities, none of the entities will be created at all.
////