
== Update Entities

The Entities API also allows you to update already existing entities through the endpoint: `/entities/:entityName/:entityId`. The URL is the same as for the <<Load Entity by ID,Load Entity by ID>> as they are both pointing to the same resource (the entity). But, the HTTP method for using the Update Entity endpoint is `PUT`.

When the entity is updated successfully, the HTTP response status code `200 - OK` is returned. By default, a JSON metadata representation of the entity is returned mainly containing the `id` attribute for further reference.

[source, http request]
.Request
----
PUT http://localhost:8080/rest
            /entities
            /rstex11_Customer
            /13f01f59-8e5f-4fd9-802b-66501d49ac99

{
  name: "Updated Name"
}
----


[source, json]
.Response: 200 - OK
----
{
  "_entityName": "rstex11_Customer",
  "_instanceName": "Updated Name",
  "id": "13f01f59-8e5f-4fd9-802b-66501d49ac99"
}
----

Generally the Update Entity API behalves similar to the <<Create Entities,Create Entity API>> regards validation and entity referencing. The differences when it comes to collection Associations will be described below.


=== Association Attributes

In case you want to update an association attribute, the references to the other entites can be updated.

IMPORTANT: the Update Entity endpoint will _replace_ the existing collection with what is part of the Request. For every entity reference that is not part of the request the association will be removed. But, the entity that has been referenced _will not be removed_ from the application.

In this example you will see how to update an `M:N` association between `Product` and `ProductTag`. Assuming that the stored Product before the update looks like this:

[source, json]
.Existing Product
----
{
  "_entityName": "rstex11_Product",
  "_instanceName": "123",
  "id": "e1d586b4-aefb-2ee7-3b91-b07357b178ea",
  "createdDate": "2021-03-05",
  "createdBy": "admin",
  "lastModifiedDate": "2021-03-05",
  "price": 99.95,
  "name": "Outback Power Remote Power System",
  "version": 1,
  "tags": [
    {
      "_entityName": "rstex11_ProductTag",
      "_instanceName": "shiny",
      "id": "333f3a20-c47b-4bc9-ba34-a72d2d815695",
      "name": "shiny"
    },
    {
      "_entityName": "rstex11_ProductTag",
      "_instanceName": "great",
      "id": "c4c028f0-fec1-7512-83cd-c17537d1f502",
      "name": "great"
    }
  ]
}
----

In this example you would like to change the tags of the Product in the following ways:

* `great` should be removed from the tags.
* `amazing` should be added to the tags.
* The tag `shiny` should be kept.

[source, http request]
.Update Tag Associations Request
----
PUT http://localhost:8080/rest
            /entities
            /rstex11_Product
            /e1d586b4-aefb-2ee7-3b91-b07357b178ea
            ?responseFetchPlan=product-with-tags

{
  "name": "123",
  "price": 99.95,
  "tags": [
    {
      "id": "333f3a20-c47b-4bc9-ba34-a72d2d815695" // <1>
    },
    {
      "id": "d6ab132e-a0bd-a624-c6ad-cc544e83c584" // <2>
    }
  ]
}
----
<1> The ID of the product tag `shiny` is part of the request in order to keep the association.
<2> The ID of the product tag `amazing` is newly added to the association.

NOTE: As the ID of the product tag `great (c4c028f0-fec1-7512-83cd-c17537d1f502)` is not part of the Request anymore, it will be removed from the association.

[source,json]
.Response: 200 - OK
----
{
  "_entityName": "rstex11_Product",
  "_instanceName": "Outback Power Remote Power System",
  "id": "e1d586b4-aefb-2ee7-3b91-b07357b178ea",
  "createdDate": "2021-03-05",
  "createdBy": "admin",
  "lastModifiedDate": "2021-03-05",
  "price": 99.95,
  "lastModifiedBy": "admin",
  "name": "Outback Power Remote Power System",
  "version": 2,
  "tags": [
    {
      "_entityName": "rstex11_ProductTag",
      "_instanceName": "shiny",
      "id": "333f3a20-c47b-4bc9-ba34-a72d2d815695",
      "name": "shiny" // <1>
    },
    {
      "_entityName": "rstex11_ProductTag",
      "_instanceName": "amazing",
      "id": "d6ab132e-a0bd-a624-c6ad-cc544e83c584",
      "name": "amazing" // <2>
    }
  ]
}
----
<1> The `shiny` reference is still there, as it was part of the Request
<2> The `amazing` reference has been added, whereas the tag `great` is not part of the association anymore.

==== Remove `*:1` Entity References

In order to remove a reference for `N:1` or `1:1` associations, you need to send in `null` as a value. The absence of the attribute in the Request will _not_ lead that the reference is removed, because of the <<Partial Updates>> feature. In this case the attribute would just be ignored and not changed as part of the request.

=== Composition Attributes

In case you want to update a Composition attribute, just as in the Create Entity API, it is possible to directly update the content of the child entity. This is true for `1:1` as well as `1:N` compositions.

IMPORTANT: the Update Entity endpoint will _replace_ the existing collection with what is part of the Request. For every entity reference that is not part of the request the association will be removed. Further: the entity that has been referenced before _will be removed_ from the application as well.

In this example you will see how to update an `1:N` composition between `Order` and `OrderLine`. Assuming that the stored Order before the update looks like this:

[source, json]
.Existing Order
----
{
  "_entityName": "rstex11_Order",
  "_instanceName": "rest.sample.entity.Order-288a5d75-f06f-d150-9b70-efee1272b96c [detached]",
  "id": "288a5d75-f06f-d150-9b70-efee1272b96c",
  "date": "2021-03-01",
  "amount": 130.08,
  "createdDate": "2021-03-05T10:35:13.427",
  "createdBy": "admin",
  "lastModifiedDate": "2021-03-05T10:35:13.427",
  "lines": [
    {
      "_entityName": "rstex11_OrderLine",
      "_instanceName": "rest.sample.entity.OrderLine-a1cd778b-fe49-4c74-05a0-6fb207dc11bd [detached]",
      "id": "a1cd778b-fe49-4c74-05a0-6fb207dc11bd",  // <1>
      "product": {
        "_entityName": "rstex11_Product",
        "_instanceName": "Solar-One HUP Flooded Battery 48V",
        "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19",
        "name": "Solar-One HUP Flooded Battery 48V"
      },
      "quantity": 2.0,
      "createdDate": "2021-03-05T10:35:13.427",
      "createdBy": "admin",
      "lastModifiedDate": "2021-03-05T10:35:13.427",
      "version": 1
    },
    {
      "_entityName": "rstex11_OrderLine",
      "_instanceName": "rest.sample.entity.OrderLine-55b925e5-9f3a-a725-9eb3-1240f9c1fe95 [detached]",
      "id": "55b925e5-9f3a-a725-9eb3-1240f9c1fe95",  // <2>
      "product": {
        "_entityName": "rstex11_Product",
        "_instanceName": "Cotek Battery Charger",
        "id": "1ed85c7a-89f1-c339-a738-16307ed6003a",
        "name": "Cotek Battery Charger"
      },
      "quantity": 1.0,
      "createdDate": "2021-03-05T10:35:13.427",
      "createdBy": "admin",
      "lastModifiedDate": "2021-03-05T10:35:13.427",
      "version": 1
    }
  ],
  "version": 1,
  "customer": {
    "_entityName": "rstex11_Customer",
    "_instanceName": "Randall Bishop",
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835",
    "createdDate": "2021-03-01T08:33:25.326",
    "createdBy": "admin",
    "lastModifiedDate": "2021-03-01T08:33:25.326",
    "name": "Randall Bishop",
    "version": 1
  }
}
----
<1> The first order line references the `Solar-One HUP Flooded Battery 48V` product.
<2> The second order line references the `Cotek Battery Charger` product.

In this example you would like to change the order lines in the following ways:

* The `quantity` of the order line with the product `Solar-One HUP Flooded Battery 48V` should be increased to `3.0`.
* The order line with the product `Cotek Battery Charger` should be removed.
* A new order line with the product `Outback Power Remote Power System` should be added.

[source, http request]
.Update Composition Request
----
PUT http://localhost:8080/rest
            /entities
            /rstex11_Order
            /288a5d75-f06f-d150-9b70-efee1272b96c
            ?responseFetchPlan=product-with-tags

{
  "customer": {
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835"
  },
  "date": "2021-03-01",
  "amount": 249.99,
  "lines": [
    {
      "id": "a1cd778b-fe49-4c74-05a0-6fb207dc11bd", // <1>
      "product": {
        "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19",
        "name": "Solar-One HUP Flooded Battery 48V"
      },
      "quantity": 3.0 // <2>
    },
    { // <3>
      "product": {
        "id": "f6884077-19c4-546f-33d4-a788399337f7",
        "name": "Outback Power Remote Power System"
      },
      "quantity": 1.0
    }
  ]
}
----
<1> The ID of the existing order line is added to update the existing order line
<2> The `quantity` value is set to `3.0` for the `Solar-One HUP Flooded Battery 48V` product
<3> A new order line is added for the product `Outback Power Remote Power System`

WARNING: When updating a child entity, like the order line in the example above, the ID of the existing order line needs to be added, so that Jmix recognises it as an update, not as a new entity.

The response to this update request contains the desired changes:

[source,json]
.Response: 200 - OK
----
{
  "_entityName": "rstex11_Order",
  "_instanceName": "rest.sample.entity.Order-288a5d75-f06f-d150-9b70-efee1272b96c [detached]",
  "id": "288a5d75-f06f-d150-9b70-efee1272b96c",
  "date": "2021-03-01",
  "amount": 249.99,
  "createdDate": "2021-03-05T10:45:21.678",
  "createdBy": "admin",
  "lastModifiedDate": "2021-03-05T10:45:29.31",
  "lastModifiedBy": "admin",
  "lines": [
    {
      "_entityName": "rstex11_OrderLine",
      "_instanceName": "rest.sample.entity.OrderLine-d0fdfaa8-7d65-5e25-49c2-d34fc41c0e55 [detached]",
      "id": "d0fdfaa8-7d65-5e25-49c2-d34fc41c0e55",
      "product": {
        "_entityName": "rstex11_Product",
        "_instanceName": "Solar-One HUP Flooded Battery 48V",
        "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19",
        "name": "Solar-One HUP Flooded Battery 48V"
      },
      "quantity": 3.0, // <1>
      "createdDate": "2021-03-05T10:45:21.678",
      "createdBy": "admin",
      "lastModifiedDate": "2021-03-05T10:45:29.31",
      "lastModifiedBy": "admin",
      "version": 2 // <2>
    },
    {
      "_entityName": "rstex11_OrderLine",
      "_instanceName": "rest.sample.entity.OrderLine-96722466-5164-a48c-b7f6-8d4c1bd605dd [detached]",
      "id": "96722466-5164-a48c-b7f6-8d4c1bd605dd",
      "product": {
        "_entityName": "rstex11_Product",
        "_instanceName": "Outback Power Remote Power System",
        "id": "f6884077-19c4-546f-33d4-a788399337f7",
        "name": "Outback Power Remote Power System" // <3>
      },
      "quantity": 1.0,
      "createdDate": "2021-03-05T10:45:29.301",
      "createdBy": "admin",
      "lastModifiedDate": "2021-03-05T10:45:29.301",
      "version": 1
    }
  ],
  "version": 2,
  "customer": {
    "_entityName": "rstex11_Customer",
    "_instanceName": "Randall Bishop 3",
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835",
    "createdDate": "2021-03-01T08:33:25.326",
    "createdBy": "admin",
    "lastModifiedDate": "2021-03-01T08:33:25.326",
    "name": "Randall Bishop 3",
    "version": 1
  }
}
----
<1> The `quantity` has been updated for `Solar-One HUP Flooded Battery 48V`.
<2> The `version` attribute was increased to indicate the update.
<3> The new order line for `Outback Power Remote Power System` has been added to the order.


[IMPORTANT]
====
When a child entity should not be updated, but kept in the composition, the ID of the existing order line needs to be part of the request. This way Jmix recognises it as still being part of the composition and does not delete it _accidentally_.

In the example from above when the order line for `Cotek Battery Charger (55b925e5-9f3a-a725-9eb3-1240f9c1fe9)` should not be changed at all, in the update it still needs to be listed with its ID:

[source, json]
.Update Composition Request containing non-changing child entities
----
{
  "lines": [
    {
      "id": "55b925e5-9f3a-a725-9eb3-1240f9c1fe9" // <1>
    },
    {
      "id": "a1cd778b-fe49-4c74-05a0-6fb207dc11bd",
      "product": {
        "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19",
        "name": "Solar-One HUP Flooded Battery 48V"
      },
      "quantity": 3.0
    },
    {
      "product": {
        "id": "f6884077-19c4-546f-33d4-a788399337f7",
        "name": "Outback Power Remote Power System"
      },
      "quantity": 1.0
    }
  ]
}
----
<1> Child entities that are not changed (like `Cotek Battery Charger`) but should still be part of the composition is referenced through its `id`.

====

=== Partial Updates

It is possible to only send in the attributes that should be changed. In this case, all other attributes of the entity will stay untouched.

In the example below, you can send in an updated order date of the `Order` entity. The Order entity actually contains more attributes like `customer`, `amount`, `lines` that have been set during the creation of the entity.

[source, http request]
.Partial Order Update Request
----
PUT http://localhost:8080
         /entities
         /rstex11_Order
         /5a8adc2f-f4ef-17a9-9f97-1e715b3ade3d
         ?responseFetchPlan=order-with-details

{
  "date": "2020-12-06"
}
----


[source, json]
.Response: 200 - OK
----
{
  "_entityName": "rstex11_Order",
  "_instanceName": "rest.sample.entity.Order-5a8adc2f-f4ef-17a9-9f97-1e715b3ade3d [detached]",
  "id": "5a8adc2f-f4ef-17a9-9f97-1e715b3ade3d",
  "date": "2020-12-06", //<1>
  "amount": 130.08, //<2>
  "createdDate": "2021-03-04T07:14:52.806",
  "createdBy": "admin",
  "lastModifiedDate": "2021-03-04T07:46:11.041",
  "lastModifiedBy": "admin",
  "lines": [
    {
      "_entityName": "rstex11_OrderLine",
      "_instanceName": "rest.sample.entity.OrderLine-50a21098-9fec-0a0a-ab51-76705bd3a672 [detached]",
      "id": "50a21098-9fec-0a0a-ab51-76705bd3a672",
      "product": {
        "_entityName": "rstex11_Product",
        "_instanceName": "Cotek Battery Charger",
        "id": "1ed85c7a-89f1-c339-a738-16307ed6003a",
        "name": "Cotek Battery Charger"
      },
      "quantity": 1.0,
      "createdDate": "2021-03-05T08:51:00.645",
      "createdBy": "admin",
      "lastModifiedDate": "2021-03-05T08:51:00.645",
      "version": 1
    },
    {
      "_entityName": "rstex11_OrderLine",
      "_instanceName": "rest.sample.entity.OrderLine-be0e5392-2cc1-ee05-7720-63c46c5260c1 [detached]",
      "id": "be0e5392-2cc1-ee05-7720-63c46c5260c1",
      "product": {
        "_entityName": "rstex11_Product",
        "_instanceName": "Solar-One HUP Flooded Battery 48V",
        "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19",
        "name": "Solar-One HUP Flooded Battery 48V"
      },
      "quantity": 2.0,
      "createdDate": "2021-03-05T08:51:00.644",
      "createdBy": "admin",
      "lastModifiedDate": "2021-03-05T08:51:00.644",
      "version": 1
    }
  ],
  "version": 2, //<3>
  "customer": {
    "_entityName": "rstex11_Customer",
    "_instanceName": "Randall Bishop",
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835",
    "createdDate": "2021-03-01T08:33:25.326",
    "createdBy": "admin",
    "lastModifiedDate": "2021-03-01T08:33:25.326",
    "name": "Randall Bishop",
    "version": 1
  }
}
----
<1> The `date` attribute was updated to the new order date.
<2> Other attributes of the entity stay untouched.
<3> The `version` attribute of the Order entity was increased to indicate the update.