= LDAP

The add-on provides an easy way to enable LDAP authentication in Jmix applications. It allows you to synchronize users and map LDAP groups and user attributes to Jmix security roles. You can use the add-on with Active Directory and with any other LDAP implementation.

Also, the add-on supports the case when users are managed only in LDAP, and you don't store a user entity in the database.

The add-on uses the Spring Security LDAP and provides a ready-to-go security configuration that could be easily enabled by including the add-on in the application. The process and main settings of the LDAP authentication are described in the https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-authentication-ldap[Spring documentation^].
[[installation]]
== Installation

Follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section to install the add-on into your application.

To start working with the application, you need to configure main LDAP properties. See an example in the xref:ldap:getting-started.adoc#configuring-main-properties[Getting Started] section.

