= settings
:page-aliases: facets/screen-settings-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/settings-facet" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`settings` facet 可以保存和恢复当前用户的可视化组件设置。支持以下组件：

* xref:flow-ui:vc/components/dataGrid.adoc[dataGrid]、xref:vc/components/treeDataGrid.adoc[treeDataGrid] - 可以保存列的顺序和列宽的设置，以及排序参数的设置。
* xref:flow-ui:vc/layouts/details.adoc[details]、xref:vc/components/genericFilter.adoc[genericFilter] - 保存打开的状态。
* xref:vc/components/simplePagination.adoc[simplePagination] - 如果 `itemsPerPageVisible` 为 `true`，则 facet 可以保存所选的每页显示的数据量。

[[basic-usage]]
== 基本用法

当在界面内添加 `auto="true"` 属性的 `settings` 时，facet 会自动管理视图内具有标识符的所有支持的组件配置：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customer/customer-list-view.xml[tags=facets;settings]
----

如需管理视图内的特定组件配置，可以用 `component` 内嵌元素，示例：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/city/city-list-view.xml[tags=facets;settings]
----

如需排除某些组件，可以先设置 `auto="true"`，然后用配置特定组件的 `enabled="false"`：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/hobby/hobby-list-view.xml[tags=facets;settings]
----

组件的配置以 JSON 格式保存在主数据存储的 `FLOWUI_USER_SETTINGS` 表中。可以在 xref:data-tools:entity-inspector.adoc[实体探查] 中打开 `flowui_UserSettingsItem` 实体对保存的数据进行管理。

[[handlers]]
== 事件和处理器

include::flow-ui:vc/handler-generation-tip.adoc[]

[[applySettingsDelegate]]
=== applySettingsDelegate

`applySettingsDelegate` 在视图的 `ReadyEvent` 处理方法之前调用。

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/SettingsFacetView.java[tags=checkbox;settings;applySettingsDelegate]
----

[[applyDataLoadingSettingsDelegate]]
=== applyDataLoadingSettingsDelegate

`applyDataLoadingSettingsDelegate` 在视图的 `BeforeShowEvent` 处理方法之前调用，并支持恢复与数据加载有关的配置。

[[saveSettingsDelegate]]
=== saveSettingsDelegate

The `saveSettingsDelegate` handler 在视图的 `DetachEvent` 处理方法之前调用。

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/SettingsFacetView.java[tags=checkbox;settings;saveSettingsDelegate]
----
