= Events

The map and features has the following events.

== Map Events

[[MapClickEvent]]
=== MapClickEvent

An event that is fired when the map is clicked. Please note that if the user double-clicks, the event will be triggered twice.

Below is an example of handling a map click event. When a user clicks on the map, a notification is displayed with the event name and the coordinates of the map click location:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geometryFactory;notifications;MapClickEvent]
----

[[MapSingleClickEvent]]
=== MapSingleClickEvent

A map single event is fired after 250 ms to ensure that it is not a double click.

[[MapDoubleClickEvent]]
=== MapDoubleClickEvent

An event is fired when user makes double-click on a map.

Below is an example of handling a map double-click event.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geoMap;MapDoubleClickEvent]
----

[[MapMoveEndEvent]]
=== MapMoveEndEvent

An event is fired after the map is moved (for instance, after zooming, panning, or dragging the map).

Here's an example of how to handle a map move event.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapMoveEndEvent]
----

[[MapZoomChangedEvent]]
=== MapZoomChangedEvent

An event is triggered when the resolution of the map view is changed.

Here's an example demonstrating how to handle a map zoom change event.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapZoomChangedEvent]
----

== Source Events

[[SourceFeatureClickEvent]]
=== SourceFeatureClickEvent

An event that is fired when the xref:maps:features-geometries.adoc[feature] is clicked. Note, if the user makes double click, event will be fired twice.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=vectorSource;onInit;addSourceFeatureClickListener]
----

[[SourceFeatureSingleClickEvent]]
=== SourceFeatureSingleClickEvent

A feature single click event is fired after 250 ms to ensure that it is not a double click.

[[SourceFeatureDoubleClickEvent]]
=== SourceFeatureDoubleClickEvent

An event is fired when user makes double click on a feature.

[[GeoObjectClickEvent]]
=== GeoObjectClickEvent

An event that is fired when the geo-object is clicked. Note, if the user makes double click, event will be fired twice.

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/location/LocationDetailView.java[tags=dataVectorSource;notifications;onInit;addGeoObjectClickListener]
----

[[GeoObjectSingleClickEvent]]
=== GeoObjectSingleClickEvent

A geo-object single click event is fired after 250 ms to ensure that it is not a double click.

[[GeoObjectDoubleClickEvent]]
=== GeoObjectDoubleClickEvent

An event is fired when user makes double click on a geo-object.

== Feature Events

[[FeatureClickEvent]]
=== FeatureClickEvent

An event that is fired when feature is clicked. Note, if the user makes double click, event will be fired twice.

[[FeatureSingleClickEvent]]
=== FeatureSingleClickEvent

An event is fired after 250 ms to ensure that it is not a double click.

[[FeatureDoubleClickEvent]]
=== FeatureDoubleClickEvent

An event is fired when user makes double click on a feature.