= 事件

地图和地图要素具有下列事件。

== 地图事件

[[MapClickEvent]]
=== MapClickEvent

用户点击地图触发的事件。注意，如果用户双击地图，该事件会触发两次。


下面是处理地图点击事件的示例。用户点击时，显示一条消息，包含事件的名称和地图中点击的坐标：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geometryFactory;notifications;MapClickEvent]
----

[[MapSingleClickEvent]]
=== MapSingleClickEvent

地图单击事件会延迟 250ms 发送，以确保用户不是双击。

[[MapDoubleClickEvent]]
=== MapDoubleClickEvent

用户双击地图时发送的事件。

下面是处理地图双击事件的示例。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geoMap;MapDoubleClickEvent]
----

== 源事件

[[SourceFeatureClickEvent]]
=== SourceFeatureClickEvent

用户点击 xref:maps:features-geometries.adoc[地图要素] 时触发的事件。注意，如果用户双击，该事件会触发两次。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geoMap;onInit;getSource;addSourceFeatureClickListener]
----

[[SourceFeatureSingleClickEvent]]
=== SourceFeatureSingleClickEvent

地图要素单击事件会延迟 250ms 发送，以确保用户不是双击。

[[SourceFeatureDoubleClickEvent]]
=== SourceFeatureDoubleClickEvent

用户双击地图要素时发送的事件。

[[GeoObjectClickEvent]]
=== GeoObjectClickEvent

用户点击地理对象时发送的事件。注意，如果用户双击，该事件会触发两次。

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/location/LocationDetailView.java[tags=geometryFactory;map;notifications;onInit;addGeoObjectClickListener]
----

[[GeoObjectSingleClickEvent]]
=== GeoObjectSingleClickEvent

地理对象单击事件会延迟 250ms 发送，以确保用户不是双击。

[[GeoObjectDoubleClickEvent]]
=== GeoObjectDoubleClickEvent

用户双击地理对象时发送的事件。

== 要素事件

[[FeatureClickEvent]]
=== FeatureClickEvent

用户点击地图要素时触发的事件。注意，如果用户双击地图，该事件会触发两次。

[[FeatureSingleClickEvent]]
=== FeatureSingleClickEvent

地图要素单击事件会延迟 250ms 发送，以确保用户不是双击。

[[FeatureDoubleClickEvent]]
=== FeatureDoubleClickEvent

用户双击地图要素时发送的事件。
