= Getting Started with Maps
:page-aliases: maps:quick-start.adoc

This tutorial provides instructions on getting started with integrating maps into your application.

We will use the Onboarding application as a starting point.

If you haven't created this application, you can refer to the xref:tutorial:index.adoc[Tutorial] section, which offers a detailed, step-by-step guide for developing the application.

Otherwise, download the complete application source code from the https://github.com/jmix-framework/jmix-onboarding-2[jmix-framework/jmix-onboarding-2^] GitHub repository. Next, follow the instructions in the xref:studio:project.adoc#opening-existing-project[Opening Existing Project] section to open it in Jmix Studio.

Add the Maps add-on according to the xref:index.adoc#installation[installation] section.

Let’s look at the model of the sample onboarding application.

image::data-model-diagram.svg[align="center"]

We will add a new entity - `Location`. The application features two types of locations: office and coworking space. When the HR manager creates a user card, they select the base location — the office where the user is assigned to work.

* Users should have the ability to view all available locations marked with map markers.
* Offices and coworking spaces should be marked by different markers.
* Users should be able to modify the base location by clicking on the map marker.

