[[maps]]
= Maps
:page-aliases: additional-options.adoc, canvas-layer.adoc, drawing-geometry.adoc, getting-started.adoc, heatmap-layer.adoc, \
  layers.adoc, map-services.adoc, maps-ui.adoc, raster-layers.adoc, vector-layers.adoc

CAUTION: Данное дополнение предоставляется в режиме предварительного просмотра. Документация не полная.

Это дополнение помогает вам обогатить ваше приложение визуальным представлением и манипуляцией пространственными данными. Вы можете использовать различных поставщиков карт.

Дополнение Maps поддерживает традиционную многослойную структуру, которая широко используется в профессиональных геоинформационных системах. Слои представлены как структурные единицы карт.

Дополнение основано на JavaScript-библиотеке https://openlayers.org/[OpenLayers^].

[[installation]]
== Установка

NOTE: Для этого дополнения требуется https://www.jmix.io/subscription-plans-and-prices/[подписка^] Enterprise. Если у вас нет подписки, узнайте, как получить пробную версию <<trial,ниже>>.

Для автоматической установки через маркетплейс Jmix следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие действия.

. Настройте доступ к премиум-репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в свой `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.maps:jmix-maps-starter'
implementation 'io.jmix.maps:jmix-maps-flowui-starter'
----

include::ROOT:partial$private-repo.adoc[]

[[trial]]
== Пробная версия

include::ROOT:partial$get-trial.adoc[]
