= 4. Setting Up Interaction Between UserDetail and LocationLookupView

The user should be able to change and save the base location by clicking on the map marker. Our application does not provide this feature yet.

Open the `LocationLookupView` view controller and create setter ang getter methods to pass the location we want to display or save.

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/locationlookup/LocationLookupView.java[tags=location-param]
----

Open the `UserDetailView` view controller and find the `onLocationFieldSelect()` handler. We need to not just open a dialog, but pass the location saved for edited user to it. Also, we need to get a result from the opened dialog after it is closed. Let's make changes to the handler:

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/user/UserDetailView.java[tags=locationField;onLocationFieldSelect]
----
<1> The `AfterCloseEvent` object contains `CloseAction` passed to the view’s `close()` method. We analyze the close action using the `closedWith()` method of the event object. Remember: in the previous section, we created a xref:maps:dispay-markers.adoc#select-action-handler[handler] for the `select` action.
<2> Passes the location of the edited user to the setter of `LocationLookupView`.

Launch the application and make sure that the interaction between `UserDetailView` and `LocationLookupView` is configured properly.