= Layers and Sources

Layer – is a way to organize data on a map.

//Layers are lightweight containers that get their data from sources.

Layers can be raster or vector. Raster layers consist of raster images which is a grid of pixels, while vector layers consist of vector geometries.

[[tile-layer]]
== TileLayer

Layer with sources that provide pre-rendered, tiled images in grids that are organized by zoom levels for specific resolutions.

For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_layer_Tile-TileLayer.html[TileLayer documentation^].

`TileLayer` supports three sources:

* OsmSource
* XyzSource
* WmsSource

[[osm-source]]
=== OsmSource

Source for the loading tiles from an https://www.openstreetmap.org[OpenStreetMap^] tile server. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_OSM-OSM.html[OSM documentation^].

The following example demonstrates how to display an OpenStreetMap tile layer.

[[xyz-source]]
=== XyzSource

[[wms-source]]
=== WmsSource

[[image-layer]]
== ImageLayer

[[image-static-source]]
=== ImageStaticSource

[[image-wms-source]]
=== ImageWmsSource

[[vector-layer]]
== VectorLayer

[[vector-source]]
=== VectorSource

[[data-vector-source]]
=== DataVectorSource