[[layers]]
= Layers

Basically, layers are divided into raster and vector layers. Raster layers consist of raster images, while vector layers consist of vector geometries.

To add a layer on a map declare the `layers` element and its configuration in the `geoMap` element in the XML descriptor. Here is an example of the map with one raster and one vector layer.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/maps/ex1/screen/order/order-edit1.xml[tags=layers-xml]
----

`selectedLayer` is a layer which the map is focused on. Selected layer fires events, reacts on user clicks and can be modified by UI interaction in case the layer is editable.

Parameters are common for every type of layers:

 * `id` — required parameter, specifies the id of the layer.
 * `visible` — whether the layer is visible.
 * `minZoom` — minimum zoom level down to which the layer is visible (inclusive).
 * `maxZoom` — maximum zoom level up to which the layer is visible (inclusive).

Also, you can add layers and perform configuration of the layers in the screen controller:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/maps/ex1/screen/order/OrderEdit2.java[tags=layers-java]
----

By default, the `GeoMap` UI component has a special utility layer — xref:canvas-layer.adoc#canvas-layer[Canvas]. Canvas provides a straightforward API to display and draw geometries on a map.