= Настройка

[[app_properties]]
== Свойства приложения

В данном разделе в алфавитном порядке описаны свойства приложения, имеющие отношение к дополнению Reports.

[[jmix.reports.client.background-report-processing-timeout-ms]]
jmix.reports.client.background-report-processing-timeout-ms::
+
--
Определяет таймаут для выполнения отчета в миллисекундах, если свойство <<jmix.reports.client.use-background-report-processing,jmix.reports.client.use-background-report-processing>> имеет значение `true`.

Значение по умолчанию: `10000`.
--

[[jmix.reports.client.enable-tab-symbol-in-data-set-editor]]
jmix.reports.client.enable-tab-symbol-in-data-set-editor::
+
--
Указывает, должно ли нажатие клавиши TAB в полях Script редактора отчета обрабатываться как символ табуляции вместо смены фокуса для навигации по экрану.

Значение по умолчанию: `false`
--

[[jmix.reports.client.use-background-report-processing]]
jmix.reports.client.use-background-report-processing::
+
--
Позволяет задать выполнение отчета в качестве фоновой задачи. Это свойство используется для добавления возможности отмены отчета.

Значение по умолчанию: `false`.
--

[[jmix.reports.curl-path]]
jmix.reports.curl-path::
+
--
Дополнение Reports использует инструмент cURL для создания отчетов по URL-адресу. Значение свойства представляет собой системный путь к инструменту.

Значение по умолчанию: `curl`.
--

[[jmix.reports.display-device-available]]
jmix.reports.display-device-available::
+
--
Значение `false` позволяет запускать LibreOffice в серверной операционной системе без оконного интерфейса.

Значение по умолчанию: `false`
--

[[jmix.reports.doc-formatter-timeout]]
jmix.reports.doc-formatter-timeout::
+
--
Задает время ожидания LibreOffice в секундах для преобразования DOCX/XLSX в HTML/PDF.

По истечении указанного таймаута пользователь получит сообщение об ошибке.

Значение по умолчанию: `20`
--

[[jmix.reports.history-cleanup-max-days]]
jmix.reports.history-cleanup-max-days::
+
--
Назначенное задание удаляет все записи xref:exec-history.adoc[истории выполнения отчетов] старше указанного количества дней. Если значение свойства = 0, то назначенное задание не учитывает это свойство при удалении записей. Подробнее про настройку назначенного задания см. xref:exec-history.adoc#execution_history_cleanup[Удаление истории].

Значение по умолчанию: `730`
--

[[jmix.reports.history-cleanup-max-items-per-report]]
jmix.reports.history-cleanup-max-items-per-report::
+
--
Назначенное задание оставляет то количество записей в xref:exec-history.adoc[истории выполнения] для каждого отчета, которое указано в этом свойстве, остальные удаляет. Не рекомендуется использовать в качестве значения число, больше 1000. Если значение = 0, то назначенное задание не учитывает это свойство при удалении записей. Это полезно для часто запускаемых отчетов, таких как шаблоны писем, выставление счетов, шаблоны документов и т. д. Подробнее про настройку назначенного задания см. xref:exec-history.adoc#execution_history_cleanup[Удаление истории].

Значение по умолчанию: `1000`.
--

[[jmix.reports.history-recording-enabled]]
jmix.reports.history-recording-enabled::
+
--
Включает механизм управления xref:exec-history.adoc[историей выполнения отчtтов].

Значение по умолчанию: `false`.
--

[[jmix.reports.office-path]]
jmix.reports.office-path::
+
--
Задает путь к LibreOffice.

Значение по умолчанию: `/`
--

[[jmix.reports.office-ports]]
jmix.reports.office-ports::
+
--
Задает список портов для LibreOffice, разделенный запятыми или вертикальной чертой.

Например: `jmix.reports.office-ports = 8100|8101|8102|8103|8104|8105`.

Значение по умолчанию: `8100, 8101, 8102, 8103`.
--

[[jmix.reports.pdf-fonts-directory]]
jmix.reports.pdf-fonts-directory::
+
--
Задает путь к каталогу со шрифтами для конвертации HTML в PDF.

Значение по умолчанию: `jmix.reports.pdf-fonts-directory = C:/Windows/Fonts`.
--

[[jmix.reports.put-empty-row-if-no-data-selected]]
jmix.reports.put-empty-row-if-no-data-selected::
+
--
Задает режим, в котором полосы, наборы данных которых не вернули ни одной записи, все равно выводятся один раз.

Значение по умолчанию: `true`
--

[[jmix.reports.save-output-documents-to-history]]
jmix.reports.save-output-documents-to-history::
+
--
При установке в `true` файлы результатов отчетов сохраняются в xref:files:index.adoc[хранилище файлов], если свойство <<jmix.reports.history-recording-enabled,jmix.reports.history-recording-enabled>> включено. См. также xref:exec-history.adoc#history_output_documents[Выходные документы].

Значение по умолчанию: `false`.
--

[[jmix.reports.use-office-for-document-conversion]]
jmix.reports.use-office-for-document-conversion::
+
--
Включает использование LibreOffice для вывода отчета с DOCX шаблоном в HTML/PDF, что значительно увеличивает точность конвертации.

Значение по умолчанию: `false`
--

[[libre_office]]
== Установка и настройка LibreOffice

Дополнение Reports использует пакет *LibreOffice* для вывода отчетов в xref:creation/templates.adoc#output_format_compliance[форматах] PDF и DOC. Ниже рассмотрена установка и настройка данного пакета на компьютере, содержащем сервер приложения.

*Установка и настройка LibreOffice для Microsoft Windows*

* Скачайте дистрибутив программы по адресу http://www.libreoffice.org/download/download/[www.libreoffice.org^].
* Установите программу.
* Укажите в свойстве приложения <<jmix.reports.office-path,jmix.reports.office-path>> путь к установленному *LibreOffice*:

[source, properties,indent=0]
----
jmix.reports.office-path = C:/Program Files (x86)/LibreOffice 5/program
----

*Установка и настройка LibreOffice на сервере Ubuntu*

* Установите пакет `libreoffice`, например, следующей командой:
+
[source, properties,indent=0]
----
$ sudo apt-get install libreoffice
----
    
* Укажите в свойстве приложения <<jmix.reports.office-path,jmix.reports.office-path>> путь к установленному *LibreOffice*:
+
[source, properties,indent=0]
----
jmix.reports.office-path = /usr/lib/libreoffice/program
----

* Если на сервере не установлен оконный интерфейс, то LibreOffice при старте будет выдавать ошибку вида `Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it`, или же просто завершаться без сообщений об ошибках. Для устранения проблемы установите свойство приложения <<jmix.reports.display-device-available, jmix.reports.display-device-available>>:
+
[source, properties,indent=0]
----
jmix.reports.display-device-available = false
----

* Для диагностики ошибок при старте LibreOffice выполните следующую команду:
+
[source, properties,indent=0]
----
$ strace -e trace=signal /usr/lib/libreoffice/program/soffice.bin --headless --accept="socket,host=localhost,port=8100;urp" --nologo --nolockcheck
----

[TIP]
====
Если в Ubuntu вы установили tomcat с помощью пакетного менеджера apt, вам необходимо также скопировать каталог `~/.config/libreoffice` в `$CATALINA_HOME`. Для tomcat8, это `/usr/share/tomcat8`.

Затем измените пользователя этого каталога:

[source, properties,indent=0]
----
sudo mkdir /usr/share/tomcat8/.config
sudo cp -pr ~/.config/libreoffice /usr/share/tomcat8/.config/
sudo chown -R tomcat8.tomcat8 /usr/share/tomcat8/.config/
----
====

*Установка и настройка LibreOffice для macOS*

* Скачайте дистрибутив программы по адресу https://www.libreoffice.org/get-help/install-howto/macos/[www.libreoffice.org^].
* Установите программу.
* Укажите в свойстве приложения <<jmix.reports.office-path, jmix.reports.office-path>> путь к *LibreOffice.app*, например:

[source, properties,indent=0]
----
jmix.reports.office-path = /Applications/LibreOffice.app/Contents/MacOS
----
