= Creating Reports

Creating a report in the system involves two dependent elements: report visual presentation template and report data description. The template is created in XLS(X), DOC(X), HTML formats using external tools, and the report data description is created in the report designer view or programmed in a Java class that implements a special interface.

The Reports add-on uses the item `band` to describe data zone in templates and datasets in the report data structure. When populating data from the application to templates, the band of data structure will be applied to the band of the same name in the templates.

The report can take parameters from the user or the calling code. You can specify users who will have access to the report and the views where the report should appear.

Depending on the template and report parameters, the generated report can be in PDF, XLS(X), CSV, DOC(X), HTML, or Table format.

The main components of the Reports add-on are shown in the following diagram:

image::reporting.svg[align="center"]

* `Report Engine` provides output report generation and additional functionality such as UI integration and reports access rights.
* `Report Designer` is a tool for defining and storing reports. It includes the infrastructure for storing report descriptions and templates, as well as views to create and manage reports.
* `Report` - report data structure descriptor, including _Bands_ (report bands) and _Datasets_ (datasets which are being output in the bands).
* `Report Template` - the report visualization template.