= Reports

Reporting add-on is designed to provide an easy way of report generation in a Jmix application. 

Creating a report normally requires 3 steps: defining a data source, creating templates, and running the report. The data source can be defined at runtime using the Jmix data model, SQL, JPQL, or scripts. You can create report templates in most popular editors like Microsoft Office or LibreOffice then import them into a Jmix application. Finally, reports can be executed in any application screen.

This add-on supports the following features:

* Building report templates visually at runtime with a step-by-step wizard;
* Generating reports in DOC/DOCX, ODT, XLS/XLSX, HTML, or in arbitrary text formats;
* Creating complex XLS(X) reports: multi-tiered reports, reports with data aggregation, crosstab reports;
* Using diagrams and formulas in XLS(X) reports;
* Converting reports in office formats or HTML to PDF;
* Report access rights, REST API, and execution history.

[[installation]]
== Installation

Follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section to install required add-ons into your application:

* Reports add-on - the basic add-on to support report generation.
* Charts add-on - to support chart report output.
* Pivot Table add-on - to support pivot table report output.

[TIP]
====
The Reports add-on uses the *LibreOffice* package to output reports in PDF and DOC formats. xref:configuration.adoc#libre_office[Install] *LibreOffice* to support PDF and DOC output.
====
