= Reports

Reporting add-on is designed to provide an easy way of report generation in a Jmix application. 

Creating a report normally requires 3 steps: create templates, define a data source, and run the report. You can create report templates in most popular editors like Microsoft Office or LibreOffice/OpenOffice then import them into a Jmix application. The data source can be defined at runtime using the Jmix data model, SQL, JPQL, or scripts. Finally, reports can be executed via any screen defined in the application.

This add-on supports the following features:

* Building report templates visually at runtime with a step-by-step wizard;
* Generating reports in DOC/DOCX, ODT, XLS/XLSX, HTML, or in arbitrary text formats;
* Creating complex XLS(X) reports: multi-tiered reports, reports with data aggregation, crosstab reports;
* Using diagrams and formulas in XLS(X) reports;
* Converting reports in office formats or HTML to PDF;
* Report access rights, REST API, and execution history.

[[installation]]
== Installation

To include Reports functionality in your application, add the following lines to the `dependencies` section of your `build.gradle` file:

[source,java,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----
