= 报表

报表扩展组件支持开发者和用户设计报表，并通过对 Jmix 应用程序的数据进行格式化的方式生成各种报表，报表的模板可以用熟悉的 office 软件或 HTML 创建。

该扩展组件提供下列功能：

* 设计时使用带注解的 Java 类或在运行时使用管理 UI 和分步向导创建报表。
* 生成 DOCX、XLSX、HTML、CSV、PDF 和文本格式的报表， 或显示为应用程序中的表格。
* 创建具有复杂结构的 XLSX 报表，包括数据分组、数据聚合和交叉表特性。
* 在 XLSX 报表中使用图表和公式。
* 管理报表访问权限、使用 REST API 以及查看报表执行历史。

另请参阅 xref:reports-guide:index.adoc[] 指南，其中包含具有复杂结构和各种输出类型的报表的实际示例。

[[installation]]
== 安装

按照 xref:ROOT:add-ons.adoc#installation[扩展组件] 章节的说明通过 Jmix 市场进行自动安装。

手动安装，在 `build.gradle` 添加下列依赖：

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=dependencies]
----

如需使用 xref:creation/templates.adoc#template_jasper[JasperReports 模板]，添加以下依赖：

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=jasper-dependencies]
----

如需通过 xref:reports:rest-api.adoc[REST API] 访问报表，还需要安装以下依赖：

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=rest-dependencies]
----

// 注意，xref:rest:index.adoc[] 扩展组件也用到了 `jmix-security-oauth2-starter`，因此，你的 `build.gradle` 中可能已经包含此依赖。

[TIP]
====
报表扩展组件使用 *LibreOffice* 输出 PDF 和 DOC 格式的报表。因此，请 xref:configuration.adoc#libre_office[安装] *LibreOffice* 支持 PDF 和 DOC 格式。
====

include::ROOT:single-menu-note.adoc[]