= Reports

The Reports add-on is designed to provide an easy way of report generation in a Jmix application.

Creating a report normally requires 3 steps: defining a data source, creating templates, and running the report. The data source can be defined at runtime using the Jmix data model, SQL, JPQL, or scripts. You can create report templates in most popular editors like Microsoft Office or LibreOffice then import them into a Jmix application. Finally, reports can be executed in any application view.

This add-on supports the following features:

* Building report templates visually at runtime with a step-by-step wizard;
* Generating reports in DOC/DOCX, ODT, XLS/XLSX, HTML, or in arbitrary text formats;
* Creating complex XLS(X) reports: multi-tiered reports, reports with data aggregation, crosstab reports;
* Using diagrams and formulas in XLS(X) reports;
* Converting reports in office formats or HTML to PDF;
* Report access rights, REST API, and execution history.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.reports:jmix-reports-starter'
implementation 'io.jmix.reports:jmix-reports-flowui-starter'
----

// To access reports through xref:reports:rest-api.adoc[REST API], add also the following dependencies:
//
// [source,groovy,indent=0]
// ----
// include::example$/ex1/build.gradle[tags=reports-rest-dep]
// ----
//
// Note that the `jmix-security-oauth2-starter` is used also by the xref:rest:index.adoc[] add-on, so it may already exist in your `build.gradle`.

[TIP]
====
The Reports add-on uses the *LibreOffice* package to output reports in PDF and DOC formats. xref:configuration.adoc#libre_office[Install] *LibreOffice* to support PDF and DOC output.
====