= 报表

报表扩展组件为 Jmix 应用程序提供了一个生成报表的简单方式。

创建一个报表通常需要三个步骤：定义数据源、创建模板以及运行报表。数据源可以在运行时使用 Jmix 数据模型、SQL、JPQL 或脚本创建。报表模板可以用流行的编辑器，例如，微软 Office 或 LibreOffice 创建，然后导入 Jmix 应用程序中。最后，报表支持在任一应用程序界面中运行。

该扩展组件提供下列功能：

* 运行时通过向导一步一步可视化地创建报表模板；
* 报表格式支持 DOC/DOCX、ODT、XLS/XLSX、HTML 或任一纯文本类型；
* 创建复杂的 XLS(X) 报表：多区域报表、带数据聚合的报表、交叉报表；
* 在 XLS(X) 报表中使用图表和公式；
* 将 Office 或 HTML 格式的报表转换成 PDF 格式；
* 报表访问权限、REST API 以及报表执行历史。

[[installation]]
== 安装

按照 xref:ROOT:add-ons.adoc#installation[扩展组件] 章节的说明通过 Jmix 市场进行自动安装。

手动安装，在 `build.gradle` 添加下列依赖：

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----

如需通过 xref:reports:rest-api.adoc[REST API] 访问报表，需要添加下列依赖：

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=reports-rest-dep]
----

注意，xref:rest:index.adoc[] 扩展组件也用到了 `jmix-security-oauth2-starter`，因此，你的 `build.gradle` 中可能已经包含此依赖。


[TIP]
====
报表扩展组件使用 *LibreOffice* 输出 PDF 和 DOC 格式的报表。因此，请 xref:configuration.adoc#libre_office[安装] *LibreOffice* 支持 PDF 和 DOC 格式。
====
