
= Reports

Дополнение Reports предназначено для обеспечения простого способа создания отчетов в приложениях Jmix.

Создание отчета обычно требует выполнения 3 шагов: определение источника данных, создание шаблонов и запуск отчета. Источник данных можно определить во время выполнения приложения, используя модель данных Jmix, SQL, JPQL или скрипты Groovy. Создать шаблон отчета можно в большинстве популярных редакторов, таких как Microsoft Office или LibreOffice, а затем импортировать их в приложение Jmix. Наконец, отчеты могут быть запущены на выполнение из любого экрана приложения.

Данное дополнение поддерживает следующие функции:

* Визуальное создание шаблонов отчетов во время работы приложения с помощью пошагового мастера;
* Генерация отчетов в DOC/DOCX, ODT, XLS/XLSX, HTML или произвольных текстовых форматах;
* Создание сложных XLS(X)-отчетов: многоуровневые отчеты, отчеты с агрегированием данных, перекрестные таблицы;
* Использование диаграмм и формул в XLS(X)-отчетах;
* Создание выходных документов в офисных форматах или HTML и преобразование их в PDF;
* Права доступа к отчетам, REST API и история выполнения отчетов.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующие зависимости в `build.gradle`:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----

Для доступа к отчетам через xref:reports:rest-api.adoc[REST API], добавьте также следующие зависимости:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=reports-rest-dep]
----

Обратите внимание, что зависимость `jmix-security-oauth2-starter` также используется дополнением xref:rest:index.adoc[], поэтому она может уже присутствовать в вашем `build.gradle`.

[TIP]
====
Дополнение Reports использует пакет *LibreOffice* для вывода отчетов в форматах PDF и DOC. xref:configuration.adoc#libre_office[Установите] *LibreOffice* для поддержки вывода в формате PDF и DOC.
====
