= 自定义项目模板

Studio 支持引入包含项目模板的自定义制件，因此可以在新建项目、UI 界面或者 FlowUI 视图中使用自定义的模板。

如需设置自定义制件坐标，点击 Jmix 工具窗口中的 *Settings* -> *Jmix Plugin Settings* 然后在 *Additional templates artifact* 字段输入制件的组名和包名。制件的版本必须与制件中项目模板使用的 Jmix BOM 的版本一致。

Studio 会从 *New Project* 新建项目向导选择的仓库中查找标准的模板制件（`io.jmix.templates.studio:jmix-studio-templates`）和自定义制件。如果都找到了，则会将模板合并，且自定义模板的优先级更高。也支持覆盖标准模板，只需要在同一个目录下提供自定义的模板，例如 `content/project/application`。

按照下面的步骤可以构建一个包含自定义模板的制件。

. 克隆 https://github.com/jmix-framework/jmix[^] 仓库，将 `jmix-templates` 子目录复制到点到的其他文件夹。

. 修改 `build.gradle` 文件的 `group` 属性，示例：
+
[source,groovy]
----
group = 'com.company.templates'
----

. 修改 `gradle.properties` 里面的 `version` 为需要的 Jmix BOM 版本，示例：
+
[source,properties]
----
version = 1.5.0
----

. 修改已有的模板或添加自己的模板。例如，将 `content/project/application` 复制为 `my-application` 并修改 `template.json` 文件的 `name` 和 `order` 设置：
+
[source,json]
----
{
  "version": 1,
  "name": "My Full-Stack Application",
  "order": 50,
  "addon": false,
    ...
}
----

. 构建并发布至本地 Maven 仓库：
+
[source,shell]
----
./gradlew publishToMavenLocal
----

. 点击 *Settings* -> *Jmix Plugin Settings* 然后在 *Additional templates artifact* 字段输入 `com.company.templates:jmix-studio-templates`。

. 从 IDE 配置文件夹删除模板缓存：
* 按照 https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory[IntelliJ IDEA 文档^] 的说明找到 IDE 的配置文件夹。
* 删除 `jmix/templates` 子目录内的所有内容。

. 新建一个项目，选中 *Use local Maven repository* 复选框。在 *Jmix version* 下拉框，选择自定义制件的版本。

. 在向导的下一步，可以看到模板列表中包含了自定义的模板。
