= Hot Deploy

Платформа CUBA поддерживает технологию Hot Deploy, которая позволяет мгновенно отображать сделанные в проекте изменения в работающем приложении без необходимости перезапускать сервер. Принцип работы Hot deploy заключается во временном копировании измененных ресурсов и исходных файлов Java проекта в конфигурационный каталог приложения, откуда они загружаются и компилируются работающим приложением.

Расположение конфигурационного каталога определяется свойством приложения `jmix.core.conf-dir`. Значение по умолчанию – `{user.dir}/.jmix/conf/`.

По умолчанию конфигурационный каталог очищается при запуске приложения. Можно отключить это поведение, изменив xref:studio:project.adoc#run-debug-configuration-settings[параметры конфигурации Run/Debug].

Когда в каком-то файле исходного кода производятся изменения, Studio копирует этот файл в конфигурационный каталог приложения. Ресурсы в конфигурационном каталоге имеют приоритет над ресурсами в JAR-файлах приложения, поэтому работающее приложение загрузит именно эти ресурсы, когда они понадобятся. Если загружается файл исходного кода на Java, то приложение компилирует его на лету и загружает результирующий класс.

Кроме того, Studio посылает приложению специальные сигналы, для того чтобы заставить его очистить кэши и перезагрузить измененные ресурсы. Это кэш локализованных сообщений и конфигурации представлений, зарегистрированных экранов и меню.

Технология Hot deploy доступна для следующих классов и ресурсов:

* Дескрипторы и контроллеры экранов
* Фетч-планы
* Локализованные сообщения
* Меню
* Ресурсные роли
* Роли на уровне строк

Изменения в прочих классах и бинах, включая их статические методы, могут применяться на лету только тогда, когда изменяется еще хотя бы один файл экрана или реализации сервиса, который их используют.

Hot deploy недоступен для классов сущностей и слушателей сущностей.

