= Использование Studio

Jmix Studio IDE предлагает функции для повышения производительности при разработке приложений на основе фреймворка Jmix.

Jmix Studio основана на https://www.jetbrains.com/opensource/idea/[платформе IntelliJ^] с открытым исходным кодом и расширяет ее возможности за счет следующих особых функций:

* Генерация скриптов сборки Gradle.
* Генерация модели данных, схемы базы данных и CRUD UI.
* WYSIWYG дизайнер компоновки экранов.
* Удобные для разработчиков функции, ускоряющие написание кода: контекстные действия, инспекции и ссылки.
* Поддержка простой интернационализации.
* Создание моделей данных и экранов UI для уже существующих (legacy) баз данных.
* Технология hot (re)deploy.
* Простая миграция на новые версии фреймворка и дополнений Jmix.

Платформа IntelliJ обеспечивает прочную основу для Jmix Studio. Она содержит множество функций, повышающих производительность разработчиков Jmix, таких как эргономичный пользовательский интерфейс, автодополнение и рефракторинг кода, фоновые инспекции, встроенный контроль версий и интеграция с Gradle. Если вы не использовали IntelliJ IDEA раннее, мы настоятельно рекомендуем вам посетить раздел https://www.jetbrains.com/idea/resources/[Обучение и поддержка^] на сайте IntelliJ IDEA, чтобы быстро ознакомиться с ее основными функциями.

