= Свойства, зависящие от профиля

Studio может читать свойства приложения из https://docs.spring.io/spring-boot/reference/features/profiles.html#features.profiles[файлов, зависящих от профиля^], если в основном файле `application.properties` установлено свойство `spring.profiles.active`. Это позволяет иметь отдельный профиль для среды разработки.

Приведенный ниже пример показывает, как создать профиль `dev`, в котором определяются свойства для подключения к базе данных, и использовать его по умолчанию для среды разработки.

.application.properties
[source,properties,indent=0]
----
spring.profiles.active = dev

# ...
----

.application-dev.properties
[source,properties,indent=0]
----
main.datasource.url = jdbc:postgresql://localhost/onboarding
main.datasource.username = root
main.datasource.password = root
----

После внесения этих изменений xref:studio:data-stores.adoc[редактор свойств хранилища данных] в Studio будет читать и записывать свойства из файла `application-dev.properties`, а не из `application.properties`.

Вы можете исключить файл `application-dev.properties` из системы управления версиями, чтобы не раскрывать свои настройки подключения. При запуске приложения в тестовой или производственной среде профиль можно указать с помощью аргумента командной строки или переменной окружения.