= avatar

`avatar` is a content area that displays an image, typically a photo of a person or a company logo.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`avatar`

|Java Class
|`Avatar`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/avatar" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The following example demonstrates a name-derived abbreviation, an explicit abbreviation, and an image supplied by the view controller.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/avatar/avatar.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/avatar/AvatarSample.java[tags=image-handler-field;image-handler-method]
----

An avatar without any of these attributes displays a fallback image.

[[image-resource]]
== Image Resource

The `avatar` component can display an image from different resources. You can set a path to the resource declaratively with the <<image, image>> attribute, or set it programmatically.

[[static-image]]
== Static Image

An image can be served statically by the application.

By default, static content is served from `/static`, `/public`, `/resources`, or `/META-INF/resources` directories of the classpath (see details in the https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[Spring Boot documentation^]).

* In XML:
+
For example, if your image is located
under `/src/main/resources/META-INF/resources`, such as `/src/main/resources/META-INF/resources/icons/mary.png`, you can specify the image as follows:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/avatar/avatar-view.xml[tags=static-image]
----
+
* In Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/component/avatar/AvatarView.java[tags=static-image]
----

[[url-image]]
== URL Image

Similarly, an image can be loaded from an arbitrary URL.

* In XML:
+
[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/avatar/avatar-view.xml[tags=url-image]
----

* In Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/component/avatar/AvatarView.java[tags=url-image]
----

[[stream-image]]
== Image Provided by a DownloadHandler

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/avatar" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

An image can be provided by a `DownloadHandler`.

Use the `com.vaadin.flow.server.streams.DownloadHandler` factory methods to create a handler for the image source.

For example, `DownloadHandler.forClassResource()` creates a handler for an image located in the application classpath.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/avatar/AvatarSample.java[tags=image-handler-field;image-handler-method]
----

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/avatar" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`xsmall`
|Makes the avatar extra small.
|Aura, Lumo

|`small`
|Makes the avatar small.
|Aura, Lumo

|`large`
|Makes the avatar large.
|Aura, Lumo

|`xlarge`
|Makes the avatar extra large.
|Aura, Lumo

|`filled`
|Applies a filled surface style.
|Aura
|===

== Attributes

The following attributes are specific to `avatar`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[abbreviation]]`abbreviation`
|Sets an abbreviation to display in the component.
|—

|[[colorIndex]]`colorIndex`
|Specifies the background color for the avatar component.
|—

|[[image]]`image`
|Specifies a path to an image resource.
|—

|[[name]]`name`
|Sets a name of the avatar holder.
|—
|===

The following shared attributes are supported by `avatar`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following shared handlers are supported by `avatar`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== See Also

* https://vaadin.com/docs/v25/components/avatar[Vaadin Avatar documentation^]
