= avatar

`avatar` — это область содержимого, в которой отображается изображение, обычно фотография человека или логотип компании.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`avatar`

|Java-класс
|`Avatar`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/avatar" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В следующем примере показаны сокращение, сформированное из имени, явно заданное сокращение и изображение, переданное контроллером экрана.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/avatar/avatar.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/avatar/AvatarSample.java[tags=image-handler-field;image-handler-method]
----

Если ни один из этих атрибутов не задан, аватар отображает резервное изображение.

[[image-resource]]
== Источник изображения

Компонент `avatar` может отображать изображение из различных источников. Путь к изображению можно задать декларативно с помощью атрибута <<image, image>> или установить программно.

[[static-image]]
== Статическое изображение

Изображение может быть статически загружено приложением.

По умолчанию статический контент расположен в `/static`, `/public`, `/resources` или `/META-INF/resources` в classpath (подробности см. в документации https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[Spring Boot^]).

* В XML:
+
Если ваше изображение находится по пути `/src/main/resources/META-INF/resources`, например, `/src/main/resources/META-INF/resources/icons/mary.png`, вы можете указать его следующим образом:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/avatar/avatar-view.xml[tags=static-image]
----
+
* В Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/component/avatar/AvatarView.java[tags=static-image]
----

[[url-image]]
== Изображение из URL

Аналогично, изображение можно загрузить с любого URL-адреса.

* В XML:
+
[source, xml, indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/component/avatar/AvatarView.java[tags=url-image]
----

* В Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/component/avatar/AvatarView.java[tags=url-image]
----

[[stream-image]]
== Изображение, предоставляемое DownloadHandler

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/avatar" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Изображение можно предоставить с помощью `DownloadHandler`.

Используйте фабричные методы `com.vaadin.flow.server.streams.DownloadHandler` для создания обработчика источника изображения.

Например, `DownloadHandler.forClassResource()` создаёт обработчик для изображения, расположенного в classpath приложения.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/avatar/AvatarSample.java[tags=image-handler-field;image-handler-method]
----

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/avatar" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`xsmall`
|Делает аватар очень маленьким.
|Aura, Lumo

|`small`
|Делает аватар маленьким.
|Aura, Lumo

|`large`
|Делает аватар большим.
|Aura, Lumo

|`xlarge`
|Делает аватар очень большим.
|Aura, Lumo

|`filled`
|Применяет заливку поверхности.
|Aura
|===

== Атрибуты

`avatar` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[abbreviation]]`abbreviation`
|Устанавливает аббревиатуру для отображения в компоненте.
|—

|[[colorIndex]]`colorIndex`
|Указывает цвет фона для компонента аватара.
|—

|[[image]]`image`
|Указывает путь к ресурсу изображения.
|—

|[[name]]`name`
|Устанавливает имя владельца аватара.
|—
|===

`avatar` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`avatar` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Смотрите также

* https://vaadin.com/docs/v25/components/avatar[Документация Vaadin: Avatar^]