= button
:page-aliases: vcl/components/button.adoc, vcl/components/link-button.adoc

Компонент `button` позволяет пользователю запускать действие.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`button`

|Java-класс
|`JmixButton`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/button-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Кнопка может отображать текст, значок или оба элемента. Всплывающая подсказка задаётся атрибутом `title`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/button/simple/button-simple.xml[tags=basics]
----

[[action]]
== Использование Action

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/button-action" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут `action`, чтобы связать кнопку с существующим xref:actions.adoc[действие]. Кнопка автоматически отображает текст действия, значок, включенное и видимое состояния и вызывает действие при нажатии.

Для действия экрана укажите в `action` его идентификатор. Для действия другого компонента используйте формат `<componentId>.<actionId>`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/button/action/button-action.xml[tags=action]
----

[[programmatic-action]]
== Кнопка с программным действием

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/button-programmatic-action" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Действие можно создать в Java и назначить кнопке методом `setAction()`. Оно задаёт текст кнопки и операцию, которая выполняется при нажатии.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/button/programmaticaction/button-programmatic-action.xml[tags=programmatic-action]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/button/programmaticaction/ButtonProgrammaticActionSample.java[tags=programmatic-action]
----

[[image-button]]
== Кнопка с изображением

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/button-image" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Значок кнопки может быть компонентом, например xref:vc/html-components/image.adoc[image]. В следующем примере загружается изображение и присваивается его кнопке с помощью метода `setIcon()`.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/button/image/button-image.xml[tags=image-button]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/button/image/ButtonImageSample.java[tags=image-button-constant;image-button-field;image-button-init]
----

[[variants]]
== Варианты

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/button-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`primary`
|Применяет основной стиль кнопки.
|Aura, Lumo

|`success`
|Применяет стиль успеха.
|Aura, Lumo

|`warning`
|Применяет стиль предупреждения.
|Aura, Lumo

|`error`
|Применяет стиль ошибки.
|Aura, Lumo

|`contrast`
|Применяет контрастный стиль.
|Lumo

|`large`
|Увеличивает размер кнопки.
|Aura, Lumo

|`small`
|Уменьшает размер кнопки.
|Aura, Lumo

|`icon`
|Уменьшает отступы вокруг значка.
|Aura, Lumo

|`tertiary`
|Применяет стиль кнопки с меньшим визуальным акцентом.
|Aura, Lumo

|`tertiary-inline`
|Применяет встроенный стиль кнопки для использования внутри текстового содержимого.
|Lumo
|===

== Атрибуты

`button` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|`action`
|Связывает кнопку с действием экрана или компонента. См. <<action,Кнопка с декларативным действием>>.
|—

|[[disable-on-click]]`disableOnClick`
|Отключает кнопку сразу после нажатия, чтобы предотвратить повторную отправку. Чтобы снова включить кнопку, вызовите `setEnabled(true)`.
|`false`

|[[icon]]`icon`
|Устанавливает значок, отображаемый кнопкой.
|—

|[[iconAfterText]]`iconAfterText`
|Помещает значок после текста кнопки.
|`false`

|[[whiteSpace]]`whiteSpace`
|Управляет обработкой пробелов и разрывов строк в тексте кнопки.
|`NORMAL`
|===

`button` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#text[text] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`button` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClickEvent]]`clickListener`
|Запускается, когда пользователь нажимает кнопку. Чтобы зарегистрировать обработчик программно, используйте метод `addClickListener()`.

|[[doubleClickListener]]`doubleClickListener`
|Запускается, когда пользователь дважды нажимает кнопку в течение короткого интервала.

|[[singleClickListener]]`singleClickListener`
|Запускается после небольшой задержки, когда определяется, что щелчок не является частью двойного щелчка.
|===

`button` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Элементы

Компонент `button` может содержать следующие вложенные элементы: xref:icons/custom-icons.adoc[icon], xref:vc/miscellaneous/prefix-suffix.adoc[prefix and suffix], и xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/button[Документация Vaadin: Button^]
