= checkbox
:page-aliases: vcl/components/check-box.adoc

`checkbox` — компонент с двумя состояниями: выбран или не выбран.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`checkbox`

|Java-класс
|`JmixCheckbox`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/checkbox-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Пример использования `checkbox`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkbox/simple/checkbox-simple.xml[tags=basics]
----

== `checkbox` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/checkbox-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Привязка данных означает связывание визуального компонента с xref:data/data-containers.adoc[контейнером данных]. Изменения в визуальном компоненте или соответствующем контейнере данных могут вызывать обновления друг друга. Смотрите xref:flow-ui:data/data-examples.adoc[Использование компонентов данных] для получения дополнительной информации.

Следующий пример создаёт `checkbox`, связанный с данными. Атрибут сущности должен быть типа `Boolean`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkbox/dataaware/checkbox-dataaware.xml[tags=data-binding]
----

Контейнер экземпляра `customerDc` загружает сущность `Customer` с локальными атрибутами. Атрибут `dataContainer` связывает компонент с контейнером, а `property` выбирает логический атрибут `active`.

== Состояния

`checkbox` может находиться в нескольких состояниях, определяющих его внешний вид и функциональность.

[[enabled-state]]
*Enabled*

* Включено: Флажок интерактивный и реагирует на действия пользователя. Пользователи могут щелкнуть по нему, чтобы изменить его состояние.
* Отключено: Флажок неактивен и не реагирует на действия пользователя. Визуально он часто отображается серым цветом, чтобы указать на его неактивное состояние.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/checkbox/check-box-view.xml[tags=checkbox-enabled]
----

[[read-only-state]]
*Только чтение*

Атрибут `readOnly` управляет возможностью взаимодействия пользователя с компонентом `checkbox`. Если он установлен в `true`, флажок становится доступным только для чтения, то есть пользователь не может изменить его состояние.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/checkbox/check-box-view.xml[tags=checkbox-readOnly]
----

[[indeterminate-state]]
*Indeterminate*

Атрибут `indeterminate` управляет тем, находится ли флажок в неопределённом состоянии. Это состояние представляет собой ситуацию, когда флажок не полностью отмечен и не полностью снят.

Визуально это меняет внешний вид флажка, чтобы указать на неопределённое состояние.

NOTE: В соответствии со стандартом HTML5, это влияет только на внешний вид, а не на значение "checked".

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/checkbox/check-box-view.xml[tags=checkbox-indeterminate]
----

[[required-state]]
*Required*

Компонент можно настроить как обязательный, используя атрибут <<required,required>> или связав его с обязательным атрибутом c @NotNull валидацией.

NOTE: Как и поля ввода, `checkbox` пройдёт проверку `@NotNull`, только если он отмечен. Поведение по умолчанию можно изменить с помощью свойства xref:ui-properties.adoc#jmix.ui.component.checkbox-required-state-initialization-enabled[jmix.ui.component.checkbox-required-state-initialization-enabled], которое позволяет считать неотмеченное состояние значением `false`.

[[click-events]]
== События клика мыши

Событие `com.vaadin.flow.component.ClickEvent` генерируется при клике на компонент. Этот обработчик должен указать один из трех следующих субъектов, чтобы определить количество кликов, связанных с событием.

* click - запускает событие при каждом клике на компонент.

* singleClick - запускает событие после таймаута, чтобы убедиться, что это не двойной щелчок.

* doubleClick - запускает событие, когда по компоненту происходит двойной щелчок.

Например:

Событие `com.vaadin.flow.component.ClickEvent` отправляется, когда пользователь кликает по флажку.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/checkbox/CheckBoxView.java[tags=notifications;ClickEvent]
----

== Атрибуты

`checkbox` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[enabled]]`enabled`
|Устанавливает компонент явно отключенным или включенным. См. <<enabled-state,Включенное состояние>>.
|`true`

|[[indeterminate]]`indeterminate`
|Установите неопределённое состояние `checkbox`. См. <<indeterminate-state,Неопределённое состояние>>.
|`false`

|[[readOnly]]`readOnly`
|Указывает, находится ли компонент `checkbox` в режиме только для чтения. См. <<read-only-state,Состояние только для чтения>>.
|`false`

|[[required]]`required`
|Установите необходимое состояние `checkbox`. См. <<required-state,Требуемое состояние>>.
|`false`

|[[value]]`value`
|Задаёт значение компонента.
|—
|===

`checkbox` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clickShortcut[clickShortcut] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`checkbox` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClickEvent]]`ClickEvent`
|`com.vaadin.flow.component.ClickEvent` запускается при щелчке по компоненту. См. <<click-events,Нажмите «События»>>.
|===

`checkbox` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Элементы

Компонент `checkbox` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/checkbox[Документация Vaadin: Checkbox^]
