= checkboxGroup
:page-aliases: vcl/components/check-box-group.adoc

`checkboxGroup` allows users to select multiple values from a list using checkboxes.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`checkboxGroup`

|Java Class
|`JmixCheckboxGroup`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/checkbox-group-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The following example populates two `checkboxGroup` components from an enumeration and displays the items vertically and horizontally.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkboxgroup/simple/checkbox-group-simple.xml[tags=basics]
----

== Data-aware `checkboxGroup`

You can bind a component to an attribute of an entity held in a xref:data/data-containers.adoc[data container].

To bind `checkBoxGroup` to an entity attribute:

. Specify the name of the data container as the xref:flow-ui:vc/common-attributes.adoc#dataContainer[dataContainer] attribute value.
. Specify the name of the entity attribute as the xref:flow-ui:vc/common-attributes.adoc#property[property] attribute value.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/checkboxgroup/checkboxgroup-view.xml[tags=data;userDc;hobbiesDc;layout;data-bind]
----

In this case, `checkBoxGroup` will display instance names of the `Hobby` entity, and its `getTypedValue()` method will return the `Collection` of selected entity instances.

== Custom Items

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/checkbox-group-custom-items" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

To set the list of `checkBoxGroup` items, use the following methods:

== Items List

The `setItems()` method allows you to specify component items programmatically.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/checkboxgroup/customitems/CheckboxGroupCustomItemsSample.java[tags=items-list-field;items-list-set;items-list-source]
----

== Items Map

`ComponentUtils.setItemsMap()` allows you to specify a string label for each item value explicitly.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/checkboxgroup/customitems/CheckboxGroupCustomItemsSample.java[tags=items-map-field;items-map-set;items-map-source]
----

== Enumeration Items

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/checkbox-group-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

You can use either a declarative or programmatic approach to set the values of an enum as `checkBoxGroup` items.

The following example demonstrates the declarative approach.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkboxgroup/simple/checkbox-group-simple.xml[tags=basics]
----

The example below uses the programmatic approach.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/checkboxgroup/customitems/CheckboxGroupCustomItemsSample.java[tags=items-enum-field;items-enum-set]
----

[[orientation]]
== Orientation

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/checkbox-group-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to explicitly control the layout of items:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkboxgroup/simple/checkbox-group-simple.xml[tags=basics]
----

[[custom-item-presentation]]
== Custom Item Presentation

It is possible to customize the render of elements. You can use the `setRenderer()` method or the `@Supply` annotation for it.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/checkboxgroup/CheckboxgroupView.java[tags=renderer]
----

[[fragment-renderer]]
Alternatively, you can render items using a nested `fragmentRenderer` element. Refer to the xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Fragment Renderer] section for more information.

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`vertical`
|Displays items vertically.
|Lumo

|`horizontal`
|Displays items horizontally.
|Aura

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `checkboxGroup`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[itemsContainer]]`itemsContainer`
|Sets the items container.
|—

|[[itemsEnum]]`itemsEnum`
|Sets the items enum.
|—
|===

The following shared attributes are supported by `checkboxGroup`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `checkboxGroup`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[itemEnabledProvider]]`itemEnabledProvider`
|Determines whether each item is enabled.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Provides the text shown for each item.

|[[renderer]]`renderer`
|Provides the component used to render each item. See <<custom-item-presentation,Custom Item Presentation>>.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `checkboxGroup`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `checkboxGroup` can include <<fragment-renderer,fragmentRenderer>> and xref:vc/components/tooltip.adoc[tooltip] as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/checkbox[Vaadin Checkbox documentation^]
