= checkboxGroup
:page-aliases: vcl/components/check-box-group.adoc

`checkboxGroup` позволяет пользователям выбирать несколько значений из списка с помощью флажков.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`checkboxGroup`

|Java-класс
|`JmixCheckboxGroup`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/checkbox-group-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В следующем примере два компонента `checkboxGroup` заполняются значениями перечисления и отображают элементы вертикально и горизонтально.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkboxgroup/simple/checkbox-group-simple.xml[tags=basics]
----

== `checkboxGroup` связанный с данными

Компонент можно связать с атрибутом сущности, которая хранится в xref:data/data-containers.adoc[контейнере данных].

Чтобы связать `checkBoxGroup` с атрибутом сущности:

. Укажите имя контейнера данных в атрибуте xref:flow-ui:vc/common-attributes.adoc#dataContainer[dataContainer].
. Укажите имя атрибута сущности в атрибуте xref:flow-ui:vc/common-attributes.adoc#property[property].

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/checkboxgroup/checkboxgroup-view.xml[tags=data;userDc;hobbiesDc;layout;data-bind]
----

В этом случае `checkBoxGroup` будет отображать имена экземпляров сущности `Hobby`, а метод `getTypedValue()` вернёт коллекцию выбранных экземпляров этой сущности.

== Пользовательские элементы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/checkbox-group-custom-items" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Для задания списка элементов в `checkBoxGroup` используйте следующие методы:

== Список элементов

Метод `setItems()` позволяет программно задать элементы компонента.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/checkboxgroup/customitems/CheckboxGroupCustomItemsSample.java[tags=items-list-field;items-list-set;items-list-source]
----

== Список элементов с описаниями

`ComponentUtils.setItemsMap()` позволяет вам явно указать строковое описание для каждого значения элемента.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/checkboxgroup/customitems/CheckboxGroupCustomItemsSample.java[tags=items-map-field;items-map-set;items-map-source]
----

== Список значений перечисления

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/checkbox-group-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Значения перечисления можно задать как элементы `checkBoxGroup` декларативно или программно.

Ниже приведён пример декларативного подхода.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkboxgroup/simple/checkbox-group-simple.xml[tags=basics]
----

Пример ниже использует программный подход.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/checkboxgroup/customitems/CheckboxGroupCustomItemsSample.java[tags=items-enum-field;items-enum-set]
----

[[orientation]]
== Ориентация

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/checkbox-group-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы явно задать расположение элементов:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/checkboxgroup/simple/checkbox-group-simple.xml[tags=basics]
----

[[custom-item-presentation]]
== Рендеринг элементов

Есть возможность настроить рендеринг элементов. Для этого вы можете использовать метод `setRenderer()` или аннотацию `@Supply`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/checkboxgroup/CheckboxgroupView.java[tags=renderer]
----

[[fragment-renderer]]
Кроме того, элементы можно отображать с помощью вложенного `fragmentRenderer`. Подробнее см. в разделе xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[FragmentRenderer].

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`vertical`
|Располагает элементы вертикально.
|Lumo

|`horizontal`
|Располагает элементы горизонтально.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo
|===

== Атрибуты

`checkboxGroup` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[itemsContainer]]`itemsContainer`
|Задаёт контейнер элементов.
|—

|[[itemsEnum]]`itemsEnum`
|Задаёт перечисление элементов.
|—
|===

`checkboxGroup` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`checkboxGroup` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[itemEnabledProvider]]`itemEnabledProvider`
|Определяет, включен ли каждый элемент.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Предоставляет текст, отображаемый для каждого элемента.

|[[renderer]]`renderer`
|Предоставляет компонент для отображения каждого элемента. See <<custom-item-presentation,Пользовательская презентация товара>>.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`checkboxGroup` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `checkboxGroup` может содержать следующие вложенные элементы: <<fragment-renderer,fragmentRenderer>> и xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/checkbox[Документация Vaadin: Checkbox^]
