= comboBox
:page-aliases: vcl/components/combo-box.adoc, vcl/components/suggestion-field.adoc

`comboBox` позволяет пользователям выбирать одно значение из предопределённого списка элементов.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`comboBox`

|Java-класс
|`JmixComboBox`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`comboBox` обеспечивает фильтрацию значений по мере ввода пользователем текста и разбиение на страницы доступных значений.

Используйте `comboBox`, когда вам нужны:

* *Динамическая фильтрация*. Вам необходимо, чтобы пользователи могли фильтровать элементы в выпадающем списке по мере ввода текста. `comboBox` предоставляет встроенные возможности фильтрации.
* *Большие наборы данных*. Вы работаете с большим количеством элементов в выпадающем списке. `comboBox` обрабатывает пагинацию, позволяя отображать только ограниченное количество вариантов за раз, что повышает производительность.
* *Настройка отображения*. Вы хотите настроить внешний вид элементов в выпадающем списке, возможно, с дополнительной информацией или стилями. `comboBox` предлагает большую гибкость для настройки отображения элементов.

Простейший вариант использования `comboBox` — выбор значения перечисления для атрибута сущности. В следующем примере компонент редактирует атрибут `grade` сущности `Customer`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/combobox/simple/combobox-simple.xml[tags=basics]
----

Контейнер экземпляра `customerDc` хранит сущность. Атрибуты `dataContainer` и `property` связывают `comboBox` с её атрибутом `grade`.

[[custom-items]]
== Пользовательские элементы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-custom-items" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

[[items-list]]
== Список элементов

Вы можете задать список элементов `comboBox` с помощью метода `setItems()`.

Сначала объявите компонент в XML-дескрипторе:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/combobox/customitems/combobox-custom-items.xml[tags=order-data;items-list-field]
----

Затем инжектируйте компонент в контроллер и задайте список элементов в методе `onInit()`:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/combobox/customitems/ComboBoxCustomItemsSample.java[tags=items-list-field;items-list-set;items-list-source]
----

В раскрывающемся списке компонента отобразятся значения `1000`, `2000`, `3000` и `4000`. Выбранное значение будет помещено в атрибут `amount` сущности, расположенной в контейнере данных `orderDc`.

[[items-map]]
== Список элементов с описаниями

Метод `ComponentUtils.setItemsMap()` позволяет явно задать строковые описания для каждого значения элемента.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/combobox/customitems/ComboBoxCustomItemsSample.java[tags=items-map-field;items-map-set;items-map-source]
----

[[items-enum]]
== Список значений перечисления

Вы можете использовать декларативный или программный подход для установки значений перечисления как элементов `comboBox`.

Атрибут `itemsEnum` определяет класс перечисления для создания списка элементов. В выпадающем списке будут отображаться локализованные имена значений перечисления; значение компонента будет являться значением перечисления.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/combobox/customitems/combobox-custom-items.xml[tags=items-enum]
----

Пример ниже использует программный подход.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/combobox/ComboBoxView.java[tags=setItemsEnum;onInit]
----

[[custom-filtering]]
== Пользовательская фильтрация

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-custom-filtering" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

По умолчанию `comboBox` выполняет нечувствительное к регистру сопоставление подстрок для фильтрации. Это означает, что он будет показывать любые элементы, где введённый текст встречается где-либо в названии элемента, независимо от регистра.

Вы также можете настроить фильтрацию. Чтобы установить собственный фильтр для `comboBox`, используйте метод `setItems()`.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/combobox/customfiltering/ComboBoxCustomFilteringSample.java[tags=custom-filtering]
----

[[custom-value-entry]]
== Обработка пользовательского ввода

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-user-input" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`comboBox` позволяет вам настроить его для принятия пользовательских значений, отсутствующих в списке элементов.

Когда атрибут `allowCustomValue` установлен в `true`, пользователи могут вводить произвольные строковые значения, не совпадающие с существующими элементами. Это приводит к событию <<CustomValueSetEvent,CustomValueSetEvent>>.

NOTE: `comboBox` автоматически не обрабатывает строку с пользовательским значением. Используйте событие `CustomValueSetEvent`, чтобы определить, как следует обработать введённое пользователем значение.

Этот пример демонстрирует возможность добавления новых значений в список элементов, делая их доступными для будущего выбора:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/combobox/userinput/combobox-user-input.xml[tags=custom-value]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/combobox/userinput/ComboBoxUserInputSample.java[tags=custom-value]
----

//Lazy Loading
[[lazy-loading]]
== Получение элементов списка

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-items-query" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`comboBox` может загружать элементы по частям в ответ на действия пользователя.

Например, когда пользователь вводит `foo`, компонент загружает из базы данных не более 50 элементов, содержащих `foo` в названии, и показывает их в выпадающем списке. Когда пользователь прокручивает список вниз, компонент извлекает следующую группу из 50 элементов с тем же запросом и добавляет их в список.

[[itemsQuery]]
== Декларативная конфигурация

Чтобы реализовать такое поведение, задайте вложенный элемент `itemsQuery`.

Для реализации этого поведения определите вложенный элемент `itemsQuery`.

Элемент `itemsQuery` должен содержать текст запроса JPQL во вложенном элементе `query` и несколько дополнительных атрибутов, определяющих, что и как загружать данные:

* `escapeValueForLike` - включает поиск значений, содержащих специальные символы: `%,` `\`, и так далее. Значение по умолчанию - `false`.
* `searchStringFormat` - строка Groovy. C её помощью вы можете использовать любые допустимые строковые выражения Groovy.

Пример `itemsQuery` в `comboBox`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/combobox/itemsquery/combobox-items-query.xml[tags=declarative-fetch]
----
Атрибут компонента `pageSize` задаёт размер порции при загрузке данных из базы. Значение по умолчанию — `50`.

Для `itemsQuery` в `comboBox` не нужны атрибуты `class` и `fetchPlan`, поскольку запрос возвращает список скалярных значений — обратите внимание на `e.name` в результирующем наборе. Для работы с сущностями используйте компонент xref:vc/components/entityComboBox.adoc[entityComboBox].

include::flow-ui:vc/items-fetch-callback-note.adoc[]

[[itemsFetchCallback-handler]]
== Программная конфигурация

Извлечение элементов также может быть определено программно с помощью обработчика `itemsFetchCallback`. Например:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/combobox/itemsquery/ComboBoxItemsQuerySample.java[tags=programmatic-fetch]
----

В этом примере данные извлекаются с помощью xref:data-access:data-manager.adoc[DataManager], но вы можете использовать этот подход для загрузки из собственного сервиса.

[[customizing-item-labels]]
== Настройка отображения элементов

`itemLabelGenerator` позволяет вам настроить отображение элементов в выпадающем списке. Это дает вам контроль над текстом, который видят пользователи, позволяя представлять информацию более удобным для пользователя или контекстно-специфичным образом.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/combobox/ComboBoxView.java[tags=itemLabelGenerator]
----

[[rendering-items]]
== Рендеринг элементов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-custom-renderer" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фреймворк предоставляет гибкость в настройке отображения элементов. Вы можете использовать либо метод `setRenderer()`, либо аннотацию `@Supply`, чтобы добиться этого.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/combobox/customrenderer/combobox-custom-renderer.xml[tags=custom-renderer]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/combobox/customrenderer/ComboBoxCustomRendererSample.java[tags=custom-renderer]
----

[[overlay]]
== Оверлей

Оверлей - это полупрозрачный или непрозрачный слой, который используется для создания выпадающего списка элементов.

Атрибут `overlayClass` позволяет вам добавлять пользовательские CSS-классы к элементу оверлея.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/combobox/combo-box-view.xml[tags=overlayClass]
----

Определите свой собственный стиль в вашем CSS-файле:

[source,css,indent=0]
----
include::example$/onboarding/frontend/themes/onboarding/onboarding.css[tags=overlay]
----

[[validation]]
== Валидация

Чтобы проверять значения, введённые в `comboBox`, добавьте xref:vc/miscellaneous/validator.adoc[валидатор] во вложенный элемент `validators`.

Для `comboBox` доступны следующие стандартные валидаторы:

[cols="1h,6", grid=none]
|===
|XML-элемент
|`validators`
|elements
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#DecimalMaxValidator[decimalMax] - xref:vc/miscellaneous/validator.adoc#DecimalMinValidator[decimalMin] - xref:vc/miscellaneous/validator.adoc#DigitsValidator[digits] - xref:vc/miscellaneous/validator.adoc#DoubleMaxValidator[doubleMax] - xref:vc/miscellaneous/validator.adoc#DoubleMinValidator[doubleMin] - xref:vc/miscellaneous/validator.adoc#EmailValidator[email] - xref:vc/miscellaneous/validator.adoc#MaxValidator[max] - xref:vc/miscellaneous/validator.adoc#MinValidator[min] - xref:vc/miscellaneous/validator.adoc#NegativeOrZeroValidator[negativeOrZero] - xref:vc/miscellaneous/validator.adoc#NegativeValidator[negative] - xref:vc/miscellaneous/validator.adoc#NotBlankValidator[notBlank] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#PositiveOrZeroValidator[positiveOrZero] - xref:vc/miscellaneous/validator.adoc#PositiveValidator[positive] - xref:vc/miscellaneous/validator.adoc#RegexpValidator[regexp] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/combobox-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`small`
|Уменьшает размер компонента.
|Aura, Lumo

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo
|===

== Атрибуты

`comboBox` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|Если атрибут `allowCustomValue` равен `true`, пользователь может ввести строковые значения, которые не соответствуют ни одной существующей метке элемента, что приведет к срабатыванию <<CustomValueSetEvent,CustomValueSetEvent>>. См. <<custom-value-entry,Ввод пользовательского значения>>.
|`false`

|[[autoOpen]]`autoOpen`
|Если атрибут `autoOpen` равен `true`, раскрывающийся список `comboBox` открывается автоматически, когда поле фокусируется с помощью мыши или касания, или когда пользователь вводит текст в поле. Установите значение `false`, чтобы отключить это поведение.
|`true`

|[[clearButtonVisible]]`clearButtonVisible`
|Определяет, отображается ли в поле кнопка очистки.
|`false`

|[[itemsEnum]]`itemsEnum`
|Атрибут `itemsEnum` определяет класс перечисления для создания списка элементов. См. <<items-enum,Перечисление предметов>>.
|—

|[[overlayClass]]`overlayClass`
|Определяет список имен классов CSS, разделенных пробелами, для установки в элементе наложения. См. <<overlay, Overlay>>.
|—

|[[pageSize]]`pageSize`
|Устанавливает максимальное количество элементов, отправляемых за один запрос, должно быть больше нуля. См. <<itemsQuery,Обратный вызов получения предметов>>.
|`50`
|===

`comboBox` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#pattern[pattern] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`comboBox` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|`com.vaadin.flow.component.combobox.ComboBoxBase.CustomValueSetEvent` запускается, когда пользователь вводит непустое значение, которое не соответствует ни одному из существующих элементов. Чтобы включить ввод пользовательских значений, установите для атрибута <<allowCustomValue,allowCustomValue>> значение `true`.

|[[itemLabelGenerator]]`itemLabelGenerator`
|`com.vaadin.flow.component.ItemLabelGenerator` можно использовать для настройки строки, отображаемой пользователю для элемента. См. <<customizing-item-labels,Настройка меток предметов>>.

|[[itemsFetchCallback]]`itemsFetchCallback`
|Этот обработчик извлекает данные только тогда, когда это необходимо. См. <<itemsFetchCallback-handler,Получение программных элементов>>.

|[[renderer]]`renderer`
|Устанавливает `Renderer` ответственным за отображение отдельных элементов в списке возможных вариантов `comboBox`. Это не влияет на то, как отображается выбранный элемент — это можно настроить с помощью <<itemLabelGenerator,ItemLabelGenerator>>. См. <<rendering-items,Рендеринг предметов>>.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`comboBox` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `comboBox` может содержать следующие вложенные элементы: <<itemsQuery,itemsQuery>>, xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/components/tooltip.adoc[tooltip], и <<validation,validator>>.

== Смотрите также

* https://vaadin.com/docs/v25/components/combo-box[Документация Vaadin: Combo Box^]
