= datePicker
:page-aliases: vcl/components/date-picker.adoc

`datePicker` lets users enter a date by typing or select it using a calendar overlay.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`datePicker`

|Java Class
|`TypedDatePicker`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-picker-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Unlike a regular input field, `datePicker` has a calendar button and a calendar overlay. The calendar opens when the user clicks the button or the field itself, or starts entering a date.

The calendar is scrollable and allows selecting a year in the right pane. Click *Today* at the bottom to navigate back to the current date.

The following example defines a `datePicker` with a label:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datepicker/simple/date-picker-simple.xml[tags=basics]
----

== Data Types

`datePicker` is a typed component which supports common data types for storing a date:

* `date`
* `dateTime`
* `localDateTime`
* `offsetDateTime`
* `localDate`

When you <<data-binding, bind the component>> to an entity attribute, it will automatically assume the data type of that attribute. To set the type explicitly, use the xref:vc/common-attributes.adoc#datatype[datatype] attribute.

[[data-binding]]
== Data-aware `datePicker`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-picker-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the `dataContainer` and `property` attributes to bind `datePicker` to an entity attribute. The data container provides the entity instance, and `property` identifies the date attribute to edit.

The following example produces a data-aware `datePicker`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datepicker/dataaware/date-picker-dataaware.xml[tags=data-binding]
----

== Date Format

//todo: make changes upon completing jmix#858 ticket
The default date and time format in the application is defined by the xref:data-model:datatype.adoc#localized-format-strings[localized format strings]. To use a different format, add your own format strings to the message bundle.

To change the format for a particular component, use its xref:vc/common-attributes.adoc#dateFormat[dateFormat] attribute.

== Date Range

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-picker-custom-range" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

To restrict the input to a specific date range, specify the minimum and maximum dates using the <<max, max>> and <<min, min>> attributes:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datepicker/date-picker-view.xml[tags=range]
----

Or specify a dynamic date range within the view controller:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/datepicker/customrange/DatePickerCustomRange.java[tags=dynamic-range]
----

[[validation]]
== Validation

To check values entered into `datePicker`, add a xref:vc/miscellaneous/validator.adoc[validator] element. This allows adding a custom validation criterion or select one of the following predefined validators:

* xref:vc/miscellaneous/validator.adoc#FutureOrPresentValidator[FutureOrPresent]
* xref:vc/miscellaneous/validator.adoc#FutureValidator[Future]
* xref:vc/miscellaneous/validator.adoc#NotNullValidator[NotNull]
* xref:vc/miscellaneous/validator.adoc#PastOrPresentValidator[PastOrPresent]
* xref:vc/miscellaneous/validator.adoc#PastValidator[Past]

This example demonstrates how to use the `FutureValidator` to ensure that the selected date is in the future:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datepicker/date-picker-view.xml[tags=future]
----

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-picker-theme-variant" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`small`
|Makes the component smaller.
|Aura, Lumo

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `datePicker`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[autoOpen]]`autoOpen`
|Defines whether an overlay calendar opens when the user starts typing a date.
|—

|[[max]]`max`
|Specifies the latest date that can be selected.
|—

|[[min]]`min`
|Specifies the earliest date that can be selected.
|—

|[[name]]`name`
|Specifies a name for an HTML element that can be used to reference the component.
|—

|[[opened]]`opened`
|Specifies whether the calendar overlay is opened.
|—
|===

The following shared attributes are supported by `datePicker`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clearButtonVisible[clearButtonVisible] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#dateFormat[dateFormat] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#weekNumbersVisible[weekNumbersVisible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `datePicker`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[ClientValidatedEvent]]`ClientValidatedEvent`
|Fired after client-side validation changes the component's validity.

|[[InvalidChangeEvent]]`InvalidChangeEvent`
|Fired when the component's invalid state changes.

|[[OpenedChangeEvent]]`OpenedChangeEvent`
|Fired when the component overlay opens or closes.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `datePicker`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `datePicker` can include xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/components/tooltip.adoc[tooltip], and <<validation,validator>> as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/date-picker[Vaadin Date Picker documentation^]
