= datePicker
:page-aliases: vcl/components/date-picker.adoc

`datePicker` позволяет вводить дату вручную или выбирать её во всплывающем календаре.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`datePicker`

|Java-класс
|`TypedDatePicker`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В отличие от обычного поля ввода, `datePicker` содержит кнопку и всплывающий календарь. Календарь открывается при нажатии на кнопку или поле, а также при вводе даты.

Календарь можно прокручивать, и он позволяет выбирать год в правой панели. Нажмите *Today* внизу, чтобы вернуться к текущей дате.

В следующем примере определяется `datePicker` с меткой:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datepicker/simple/date-picker-simple.xml[tags=basics]
----

== Типы данных

`datePicker` - это типизированный компонент, который поддерживает распространенные типы данных для хранения даты:

* `date`
* `dateTime`
* `localDateTime`
* `offsetDateTime`
* `localDate`

Когда вы <<data-binding,связываете компонент>> с атрибутом сущности, он автоматически принимает тип данных этого атрибута. Чтобы установить тип явно, используйте атрибут xref:vc/common-attributes.adoc#datatype[datatype].

[[data-binding]]
== `datePicker` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-picker-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибуты `dataContainer` и `property`, чтобы связать `datePicker` с атрибутом сущности. Контейнер данных предоставляет экземпляр сущности, а `property` указывает редактируемый атрибут даты.

В следующем примере создаётся компонент `datePicker`, работающий с данными:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datepicker/dataaware/date-picker-dataaware.xml[tags=data-binding]
----

== Формат даты

//todo: make changes upon completing jmix#858 ticket

Формат даты и времени по умолчанию в приложении определяется xref:data-model:datatype.adoc#localized-format-strings[локализованными строками формата]. Чтобы использовать другой формат, добавьте собственные строки формата в пакет сообщений.

Чтобы изменить формат для конкретного компонента, используйте его атрибут xref:vc/common-attributes.adoc#dateFormat[dateFormat].

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-picker-custom-range" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Чтобы ограничить ввод диапазоном дат, задайте минимальную и максимальную даты с помощью атрибутов <<max,max>> и <<min,min>>:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datepicker/date-picker-view.xml[tags=range]
----

Или укажите адаптируемый диапазон дат внутри контроллера экрана:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/datepicker/customrange/DatePickerCustomRange.java[tags=dynamic-range]
----

[[validation]]
== Валидация

Чтобы проверять значения, введённые в `datePicker`, добавьте элемент xref:vc/miscellaneous/validator.adoc[валидатор]. Можно задать пользовательский критерий проверки или выбрать один из стандартных валидаторов:

* xref:vc/miscellaneous/validator.adoc#FutureOrPresentValidator[FutureOrPresent]
* xref:vc/miscellaneous/validator.adoc#FutureValidator[Future]
* xref:vc/miscellaneous/validator.adoc#NotNullValidator[NotNull]
* xref:vc/miscellaneous/validator.adoc#PastOrPresentValidator[PastOrPresent]
* xref:vc/miscellaneous/validator.adoc#PastValidator[Past]

В следующем примере `FutureValidator` проверяет, что выбранная дата находится в будущем:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datepicker/date-picker-view.xml[tags=future]
----

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-picker-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`small`
|Уменьшает размер компонента.
|Aura, Lumo

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo
|===

== Атрибуты

`datePicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[autoOpen]]`autoOpen`
|Определяет, открывается ли накладной календарь, когда пользователь начинает вводить дату.
|—

|[[max]]`max`
|Указывает самую позднюю дату, которую можно выбрать.
|—

|[[min]]`min`
|Указывает самую раннюю дату, которую можно выбрать.
|—

|[[name]]`name`
|Указывает имя элемента HTML, которое можно использовать для ссылки на компонент.
|—

|[[opened]]`opened`
|Указывает, открывается ли наложение календаря.
|—
|===

`datePicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clearButtonVisible[clearButtonVisible] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#dateFormat[dateFormat] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#weekNumbersVisible[weekNumbersVisible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`datePicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClientValidatedEvent]]`ClientValidatedEvent`
|Возникает после изменения состояния допустимости компонента при проверке на стороне клиента.

|[[InvalidChangeEvent]]`InvalidChangeEvent`
|Возникает при изменении состояния недопустимости компонента.

|[[OpenedChangeEvent]]`OpenedChangeEvent`
|Запускается, когда оверлей компонента открывается или закрывается.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`datePicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `datePicker` может содержать следующие вложенные элементы: xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/components/tooltip.adoc[tooltip], и <<validation,validator>>.

== Смотрите также

* https://vaadin.com/docs/v25/components/date-picker[Документация Vaadin: Date Picker^]
