= dateTimePicker
:page-aliases: vcl/components/date-field.adoc

`dateTimePicker` lets users enter or select both a date and a time.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`dateTimePicker`

|Java Class
|`TypedDateTimePicker`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-time-picker-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The date and time can be entered directly using the keyboard or selected from the corresponding overlay. The overlay opens when the respective field is clicked or any input is entered.

The following example defines a `dateTimePicker` with a label:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datetimepicker/simple/date-time-picker-simple.xml[tags=basics]
----

== Data Types

`dateTimePicker` is a typed component which supports common data types for storing both a date and a time:

* `date`
* `dateTime`
* `localDateTime`
* `offsetTime`
* `localTime`
* `offsetDateTime`
* `time`
* `localDate`

When you <<data-binding, bind the component>> to an entity attribute, it will automatically assume the data type of that attribute. To set the type explicitly, use the xref:vc/common-attributes.adoc#datatype[datatype] attribute.

[[data-binding]]
== Data-aware `dateTimePicker`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-time-picker-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the `dataContainer` and `property` attributes to bind `dateTimePicker` to an entity attribute. The data container provides the entity instance, and `property` identifies the date-time attribute to edit.

The following example produces a data-aware `dateTimePicker`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datetimepicker/dataaware/date-time-picker-dataaware.xml[tags=data-binding]
----

[[step]]
== Step

The default interval between the items displayed in the time overlay is set to one hour. To customize this interval, use the xref:vc/common-attributes.adoc#step[step] attribute either in XML or programmatically. The `step` attribute supports flexible time interval configuration using different chrono units. You can specify values with unit suffixes for clarity.

Setting the `step` attribute in the view descriptor XML:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datetimepicker/date-time-picker-view.xml[tags=step]
----
<1> 2 hour intervals.
<2> 1600 second (26m 40s) intervals.
<3> 20 minute intervals.
<4> A number without a suffix means minutes.

This can also be done in the view controller:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/datetimepicker/DateTimePickerView.java[tags=dateTimePicker;onInit;step]
----

The step must divide an hour or day evenly. For example, "15 minutes", "30 minutes" and "2 hours" are valid steps, whereas "42 minutes" isn’t.

NOTE: The overlay doesn't appear for steps less than 15 minutes, to avoid showing an impractical number of choices.

== Date Format

//todo: make changes upon completing jmix#858 ticket
The default date and time format in the application is defined by the xref:data-model:datatype.adoc#localized-format-strings[localized format strings]. To use a different format, add your own format strings to the message bundle.

To change the format for a particular component, use its xref:vc/common-attributes.adoc#dateFormat[dateFormat] attribute.

== Date and Time Range

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-time-picker-custom-range" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

To restrict the input to a specific date range, specify the minimum and maximum dates using the <<max, max>> and <<min, min>> attributes.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datetimepicker/date-time-picker-view.xml[tags=range]
----

Or specify a dynamic date range within the view controller:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/datetimepicker/customrange/DateTimePickerCustomRange.java[tags=dynamic-range]
----

[[validation]]
== Validation

To check values entered into `dateTimePicker`, add a xref:vc/miscellaneous/validator.adoc[validator] element. This allows adding a custom validation criterion or select one of the following predefined validators:

* xref:vc/miscellaneous/validator.adoc#FutureOrPresentValidator[FutureOrPresent]
* xref:vc/miscellaneous/validator.adoc#FutureValidator[Future]
* xref:vc/miscellaneous/validator.adoc#NotNullValidator[NotNull]
* xref:vc/miscellaneous/validator.adoc#PastOrPresentValidator[PastOrPresent]
* xref:vc/miscellaneous/validator.adoc#PastValidator[Past]

This example demonstrates how to use the `FutureValidator` to ensure that the selected time and date are in the future:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datetimepicker/date-time-picker-view.xml[tags=future]
----

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/date-time-picker-theme-variant" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`small`
|Makes the component smaller.
|Aura, Lumo

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `dateTimePicker`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[autoOpen]]`autoOpen`
|Defines whether the overlays open when the user starts typing a date.
|—

|[[datePlaceholder]]`datePlaceholder`
|Specifies a text that will be displayed inside the date field when it is empty.
|—

|[[max]]`max`
|Specifies the latest date and time that can be selected.
|—

|[[min]]`min`
|Specifies the earliest date and time that can be selected.
|—

|[[timePlaceholder]]`timePlaceholder`
|Specifies a text that will be displayed inside the time field when it is empty.
|—
|===

The following shared attributes are supported by `dateTimePicker`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#dateFormat[dateFormat] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#step[step] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#weekNumbersVisible[weekNumbersVisible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `dateTimePicker`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[ClientValidatedEvent]]`ClientValidatedEvent`
|Fired after client-side validation changes the component's validity.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `dateTimePicker`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `dateTimePicker` can include xref:vc/components/tooltip.adoc[tooltip] and <<validation,validator>> as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/date-time-picker[Vaadin Date Time Picker documentation^]
