= dateTimePicker
:page-aliases: vcl/components/date-field.adoc

`dateTimePicker` позволяет пользователям вводить или выбирать дату и время.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`dateTimePicker`

|Java-класс
|`TypedDateTimePicker`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-time-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Дату и время можно ввести с клавиатуры или выбрать во всплывающем окне. Оно открывается при нажатии на соответствующее поле или при начале ввода.

В следующем примере определяется компонент `dateTimePicker` с меткой:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datetimepicker/simple/date-time-picker-simple.xml[tags=basics]
----

== Типы данных

`dateTimePicker` - это типизированный компонент, который поддерживает общие типы данных для хранения как даты, так и времени:

* `date`
* `dateTime`
* `localDateTime`
* `offsetTime`
* `localTime`
* `offsetDateTime`
* `time`
* `localDate`

Когда вы <<data-binding, связываете компонент>> с атрибутом сущности, он автоматически принимает тип данных этого атрибута. Чтобы установить тип явно, используйте атрибут xref:vc/common-attributes.adoc#datatype[datatype].

[[data-binding]]
== `dateTimePicker` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-time-picker-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибуты `dataContainer` и `property`, чтобы связать `dateTimePicker` с атрибутом сущности. Контейнер данных предоставляет экземпляр сущности, а `property` указывает редактируемый атрибут даты и времени.

В следующем примере создаётся компонент `dateTimePicker`, работающий с данными:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/datetimepicker/dataaware/date-time-picker-dataaware.xml[tags=data-binding]
----

[[step]]
== Шаг

По умолчанию интервал между значениями во всплывающем списке времени составляет один час. Чтобы изменить его в XML или программно, используйте атрибут xref:vc/common-attributes.adoc#step[step]. Значение можно задавать в разных единицах времени с соответствующим суффиксом.

Установка атрибута `step` в XML-дескрипторе экрана:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datetimepicker/date-time-picker-view.xml[tags=step]
----
<1> Интервалы в 2 часа.
<2> Интервалы в 1600 секунд (26 минут 40 секунд).
<3> Интервалы в 20 минут.
<4> Число без суффикса означает минуты.

То же самое можно сделать в контроллере экрана:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/datetimepicker/DateTimePickerView.java[tags=dateTimePicker;onInit;step]
----

Шаг должен разделить час или день поровну. Например, «15 минут», «30 минут» и «2 часа» являются допустимыми шагами, а «42 минуты» — нет.

NOTE: Всплывающая панель не отображается для шагов менее 15 минут, чтобы избежать показа непрактичного количества вариантов выбора.

== Формат даты

//todo: make changes upon completing jmix#858 ticket

Формат даты и времени по умолчанию в приложении определяется xref:data-model:datatype.adoc#localized-format-strings[локализованными строками формата]. Чтобы использовать другой формат, добавьте собственные строки формата в пакет сообщений.

Чтобы изменить формат для конкретного компонента, используйте его атрибут xref:vc/common-attributes.adoc#dateFormat[dateFormat].

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-time-picker-custom-range" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Чтобы ограничить ввод диапазоном дат, задайте минимальную и максимальную даты с помощью атрибутов <<max,max>> и <<min,min>>.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datetimepicker/date-time-picker-view.xml[tags=range]
----

Или укажите адаптируемый диапазон даты и времени внутри контроллера экрана:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/datetimepicker/customrange/DateTimePickerCustomRange.java[tags=dynamic-range]
----

[[validation]]
== Валидация

Чтобы проверить значения, введённые в `dateTimePicker`, добавьте элемент xref:vc/miscellaneous/validator.adoc[валидатор]. Это позволяет добавить пользовательский критерий проверки или выбрать один из следующих предопределённых валидаторов:

* xref:vc/miscellaneous/validator.adoc#FutureOrPresentValidator[FutureOrPresent]
* xref:vc/miscellaneous/validator.adoc#FutureValidator[Future]
* xref:vc/miscellaneous/validator.adoc#NotNullValidator[NotNull]
* xref:vc/miscellaneous/validator.adoc#PastOrPresentValidator[PastOrPresent]
* xref:vc/miscellaneous/validator.adoc#PastValidator[Past]

Этот пример демонстрирует, как использовать `FutureValidator`, чтобы убедиться, что выбранные дата и время находятся в будущем:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/datetimepicker/date-time-picker-view.xml[tags=future]
----

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/date-time-picker-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`small`
|Уменьшает размер компонента.
|Aura, Lumo

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo
|===

== Атрибуты

`dateTimePicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[autoOpen]]`autoOpen`
|Определяет, открываются ли наложения, когда пользователь начинает вводить дату.
|—

|[[datePlaceholder]]`datePlaceholder`
|Указывает текст, который будет отображаться внутри поля даты, когда оно пусто.
|—

|[[max]]`max`
|Указывает последнюю дату и время, которые можно выбрать.
|—

|[[min]]`min`
|Указывает самую раннюю дату и время, которые можно выбрать.
|—

|[[timePlaceholder]]`timePlaceholder`
|Указывает текст, который будет отображаться внутри поля времени, когда оно пусто.
|—
|===

`dateTimePicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#dateFormat[dateFormat] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#step[step] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#weekNumbersVisible[weekNumbersVisible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`dateTimePicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClientValidatedEvent]]`ClientValidatedEvent`
|Возникает после изменения состояния допустимости компонента при проверке на стороне клиента.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`dateTimePicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `dateTimePicker` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip] и <<validation,validator>>.

== Смотрите также

* https://vaadin.com/docs/v25/components/date-time-picker[Документация Vaadin: Date Time Picker^]
