= decimalSlider

[.since]
Since Jmix 3.1

`decimalSlider` lets users select a `Double` value by dragging a handle along a track. Users can also move the handle with the arrow keys.

To work with `Integer` values, use xref:vc/components/integerSlider.adoc[integerSlider]. To select a range of values, use xref:vc/components/decimalRangeSlider.adoc[decimalRangeSlider].

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`decimalSlider`

|Java Class
|`JmixDecimalSlider`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/slider-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

By default, the slider takes values from 0 to 100 with a step of 1. Set <<step,step>> to a fractional number to let users select fractional values.

An example of `decimalSlider` that takes values from 0 to 1 with a step of 0.1:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/slider/simple/slider-simple.xml[tags=decimal-basics]
----

[[data-binding]]
== Data-aware `decimalSlider`

Data binding refers to linking a visual component to a xref:data/data-containers.adoc[data container]. Changes in the visual component or corresponding data container can trigger updates to one another. See xref:data/data-examples.adoc[] for more details.

To bind `decimalSlider` to an entity attribute, use the xref:vc/common-attributes.adoc#dataContainer[dataContainer] and xref:vc/common-attributes.adoc#property[property] attributes. The entity attribute must be of `Double` type.

The slider sends a new value to the server when the user releases the handle. To send the value on every step of the drag, set xref:vc/common-attributes.adoc#valueChangeMode[valueChangeMode] to `EAGER`.

[[empty-value]]
== Empty Value

A slider cannot show an empty value. When it has no value, it shows the <<min,min>> value instead. The slider treats it as an empty value:

* If the bound attribute is `null`, the slider shows `min`, but does not write it to the entity, and the xref:data/data-context.adoc[DataContext] does not register a change. The attribute gets a value only when the user moves the handle or when you set a value in code.
* An unbound slider is empty until the user moves the handle or you set a value in code.
* Calling `clear()` or `setValue(null)` moves the handle to `min` and makes the slider empty. A bound slider also sets the attribute to `null`.

The `isEmpty()` method returns `true` for an empty slider, although `getValue()` returns `min`. Validators get `null` as the value of an empty slider. If the slider is xref:vc/common-attributes.adoc#required[required], an empty slider fails validation.

[[range-and-step]]
== Range and Step

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/v25/components/slider#step" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

The <<min,min>> and <<max,max>> attributes set the range of values, and <<step,step>> sets the interval between them. The values that the user can select are counted from `min`: `min`, `min + step`, `min + 2 * step`, and so on. See the <<basics,example above>>.

The slider does not change a value that is outside the range. Such a value can come from the bound attribute or from code. The slider checks the value with the xref:vc/miscellaneous/validator.adoc#DoubleMinValidator[doubleMin] and xref:vc/miscellaneous/validator.adoc#DoubleMaxValidator[doubleMax] validators and shows a validation error. The validators are added automatically and are updated when you change `min` or `max`.

[[value-display]]
== Value Display

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/slider-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

By default, the slider shows the current value above the handle only while the user interacts with it. Set <<valueAlwaysVisible,valueAlwaysVisible>> to `true` to show the value all the time, as in the <<basics,example above>>.

The <<minMaxVisible,minMaxVisible>> attribute shows the `min` and `max` values below the track.

[[validation]]
== Validation

To check the value of `decimalSlider`, you can use a xref:vc/miscellaneous/validator.adoc[validator] in a nested `validators` element. Validators run each time the value changes.

The following predefined validators are available for `decimalSlider`:

[cols="1h,6", grid=none]
|===
|XML Element
|`validators`
|Predefined validators
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#DoubleMaxValidator[doubleMax] - xref:vc/miscellaneous/validator.adoc#DoubleMinValidator[doubleMin] - xref:vc/miscellaneous/validator.adoc#NegativeValidator[negative] - xref:vc/miscellaneous/validator.adoc#NegativeOrZeroValidator[negativeOrZero] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#PositiveValidator[positive] - xref:vc/miscellaneous/validator.adoc#PositiveOrZeroValidator[positiveOrZero]
|===

== Attributes

The following attributes are specific to `decimalSlider`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[max]]`max`
|Sets the maximum value of the slider. A value greater than `max` invalidates the component. See <<range-and-step>>.
|`100`

|[[min]]`min`
|Sets the minimum value of the slider. A value less than `min` invalidates the component. An empty slider shows this value. See <<empty-value>>.
|`0`

|[[minMaxVisible]]`minMaxVisible`
|Shows the `min` and `max` values below the track.
|`false`

|[[step]]`step`
|Sets the interval between the values that the user can select. The step must be greater than 0. See <<range-and-step>>.
|`1`

|[[value]]`value`
|Sets the component value.
|—

|[[valueAlwaysVisible]]`valueAlwaysVisible`
|Shows the current value above the handle all the time. If `false`, the value is shown only while the user interacts with the slider.
|`false`
|===

The following shared attributes are supported by `decimalSlider`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#justifySelf[justifySelf] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#valueChangeMode[valueChangeMode] -
xref:vc/common-attributes.adoc#valueChangeTimeout[valueChangeTimeout] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `decimalSlider`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `decimalSlider`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#KeyDownEvent[KeyDownEvent] -
xref:vc/common-handlers.adoc#KeyPressEvent[KeyPressEvent] -
xref:vc/common-handlers.adoc#KeyUpEvent[KeyUpEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `decimalSlider` can include xref:vc/components/tooltip.adoc[tooltip] and <<validation,validators>> as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/slider[Vaadin Slider documentation^]
