= dropdownButton
:page-aliases: vcl/components/popup-button.adoc

`dropdownButton` presents a main button, which, when clicked, reveals a dropdown menu containing a list of items.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`dropdownButton`

|Java Class
|`DropdownButton`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/dropdown-button-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The main button displays the primary xref:vc/common-attributes.adoc#text[text], or xref:vc/components/button.adoc#icon[icon] (or both) for the component. Users click this button to access the dropdown menu.

The dropdown menu contains a list of actions, each represented by a clickable item.

Each item in the dropdown menu can represent an action. When a user clicks on an action, the corresponding event handler is triggered.

Here's an example of defining a `dropdownButton` with a `text`, an `icon` and a tooltip (using the `title` attribute) retrieved from the xref:localization:message-bundles.adoc[message bundle]:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/dropdownbutton/simple/dropdown-button-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/dropdownbutton/simple/DropdownButtonSimpleSample.java[tags=programmatic-item-field;programmatic-items]
----

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/dropdown-button-theme-variant" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`primary`
|Applies the primary button style.
|Aura, Lumo

|`success`
|Applies the success style.
|Aura, Lumo

|`warning`
|Applies the warning style.
|Aura, Lumo

|`error`
|Applies the error style.
|Aura, Lumo

|`contrast`
|Applies the contrast style.
|Lumo

|`large`
|Makes the button larger.
|Aura, Lumo

|`small`
|Makes the button smaller.
|Aura, Lumo

|`icon`
|Applies the icon-button style.
|Aura, Lumo

|`tertiary`
|Applies a lower-emphasis button style.
|Aura, Lumo

|`tertiary-inline`
|Applies an inline button style intended for use inside text content.
|Lumo
|===

== Attributes

The following attributes are specific to `dropdownButton`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[dropdownIndicatorVisible]]`dropdownIndicatorVisible`
|Sets the visibility of the dropdown indicator.
|`true`

|`icon`
|Sets the icon.
|—

|[[openOnHover]]`openOnHover`
|If the `openOnHover` attribute is `true`, the drop-down list of items is opened automatically when the field is focused using a mouse or touch.
|`false`
|===

The following shared attributes are supported by `dropdownButton`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#text[text] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#whiteSpace[whiteSpace] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following shared handlers are supported by `dropdownButton`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Elements

`dropdownButton` defined in the XML descriptor can contain nested elements:

[[actionItem]]
=== actionItem

The `actionItem` element creates a link between a dropdown menu item and a specific xref:actions/declarative-actions.adoc[action] that should be executed when that item is clicked.

Use the `ref` attribute to point to the `id` of a defined `action`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/dropdownbutton/dropdown-button-view.xml[tags=actions;layout;dropdownButton;actionItem]
----

When a user clicks on an `actionItem` in the dropdown, Jmix automatically triggers the `action` referenced by the `ref` attribute. Generate an `ActionPerformedEvent` handler method for this action. Add the logic to it:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/dropdownbutton/DropdownButtonView.java[tags=callAction]
----

[[componentItem]]
=== componentItem

The `componentItem` element allows you to define custom inner content for `dropdownButton`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/dropdownbutton/dropdown-button-view.xml[tags=layout;dropdownButton;componentItem]
----

You can generate a `DropdownButtonItem.ClickEvent` handler stub for `componentItem` using Jmix Studio.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/dropdownbutton/DropdownButtonView.java[tags=emailIt]
----

[[textItem]]
=== textItem

The `textItem` element holds text.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/dropdownbutton/dropdown-button-view.xml[tags=layout;dropdownButton;textItem]
----

You can generate a `DropdownButtonItem.ClickEvent` handler stub for `textItem` using Jmix Studio.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/dropdownbutton/DropdownButtonView.java[tags=whatsAppIt]
----

[[separator]]
=== separator

The `separator` element is used to visually separate items in the dropdown menu.

[[icon]]
=== icon

The `icon` element adds a xref:icons/custom-icons.adoc[custom icon].
