= dropdownButton
:page-aliases: vcl/components/popup-button.adoc

`dropdownButton` представляет собой главную кнопку, при нажатии на которую открывается раскрывающееся меню, содержащее список элементов.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`dropdownButton`

|Java-класс
|`DropdownButton`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/dropdown-button-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Основная кнопка отображает xref:vc/common-attributes.adoc#text[text], xref:vc/components/button.adoc#icon[icon] или оба элемента. При нажатии на кнопку открывается выпадающее меню.

Выпадающее меню содержит список действий, каждое из которых представлено кликабельным элементом.

Каждый элемент в выпадающем меню может представлять действие. Когда пользователь нажимает на действие, срабатывает соответствующий обработчик события.

Вот пример определения `dropdownButton` с помощью `text`, `icon` и всплывающей подсказки (с использованием атрибута `title`), полученной из xref:localization:message-bundles.adoc[пакет сообщений]:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/dropdownbutton/simple/dropdown-button-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/dropdownbutton/simple/DropdownButtonSimpleSample.java[tags=programmatic-item-field;programmatic-items]
----

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/dropdown-button-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`primary`
|Применяет основной стиль кнопки.
|Aura, Lumo

|`success`
|Применяет стиль успеха.
|Aura, Lumo

|`warning`
|Применяет стиль предупреждения.
|Aura, Lumo

|`error`
|Применяет стиль ошибки.
|Aura, Lumo

|`contrast`
|Применяет контрастный стиль.
|Lumo

|`large`
|Увеличивает размер кнопки.
|Aura, Lumo

|`small`
|Уменьшает размер кнопки.
|Aura, Lumo

|`icon`
|Применяет стиль кнопки-значка.
|Aura, Lumo

|`tertiary`
|Применяет стиль кнопки с меньшим визуальным акцентом.
|Aura, Lumo

|`tertiary-inline`
|Применяет встроенный стиль кнопки для использования внутри текстового содержимого.
|Lumo
|===

== Атрибуты

`dropdownButton` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[dropdownIndicatorVisible]]`dropdownIndicatorVisible`
|Устанавливает видимость индикатора раскрывающегося списка.
|`true`

|`icon`
|Задаёт значок.
|—

|[[openOnHover]]`openOnHover`
|Если атрибут `openOnHover` равен `true`, раскрывающийся список элементов открывается автоматически при наведении фокуса на поле с помощью мыши или касания.
|`false`

|[[overlayClass]]`overlayClass`
|Добавляет имена CSS-классов во всплывающий элемент компонента.
|—
|===

`dropdownButton` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#text[text] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#whiteSpace[whiteSpace] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`dropdownButton` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Элементы

`dropdownButton`, определённый в дескрипторе XML, может содержать вложенные элементы:

[[actionItem]]
=== actionItem

Элемент `actionItem` связывает пункт выпадающего меню с xref:actions/declarative-actions.adoc[действием], которое выполняется при выборе этого пункта.

В атрибуте `ref` укажите `id` объявленного `action`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/dropdownbutton/dropdown-button-view.xml[tags=actions;layout;dropdownButton;actionItem]
----

Когда пользователь выбирает `actionItem` в выпадающем меню, Jmix автоматически запускает `action`, указанный в атрибуте `ref`. Создайте для действия метод-обработчик `ActionPerformedEvent` и добавьте в него необходимую логику:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/dropdownbutton/DropdownButtonView.java[tags=callAction]
----

[[componentItem]]
=== componentItem

Элемент `componentItem` задаёт произвольное содержимое `dropdownButton`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/dropdownbutton/dropdown-button-view.xml[tags=layout;dropdownButton;componentItem]
----

В Jmix Studio можно создать заготовку обработчика `DropdownButtonItem.ClickEvent` для `componentItem`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/dropdownbutton/DropdownButtonView.java[tags=emailIt]
----

[[textItem]]
=== textItem

Элемент `textItem` содержит текст.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/dropdownbutton/dropdown-button-view.xml[tags=layout;dropdownButton;textItem]
----

В Jmix Studio можно создать заготовку обработчика `DropdownButtonItem.ClickEvent` для `textItem`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/dropdownbutton/DropdownButtonView.java[tags=whatsAppIt]
----

[[separator]]
=== separator

Элемент `separator` визуально разделяет пункты выпадающего меню.

[[icon]]
=== icon

Элемент `icon` добавляет xref:icons/custom-icons.adoc[пользовательский значок].
