= entityComboBox
:page-aliases: vcl/components/entity-combo-box.adoc

`entityComboBox` позволяет пользователям выбирать экземпляр xref:data-model:entities.adoc[сущность] из раскрывающегося списка и выполнять для него действия.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`entityComboBox`

|Java-класс
|`EntityComboBox`
|===

[[basics]]
== Быстрый старт

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/entity-combobox-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент `entityComboBox` обычно используют, когда значение поля должно хранить ссылку на сущность. Пользователь может выбрать экземпляр сущности и выполнить связанные с ним действия.

При нажатии на поле или кнопку со стрелкой открывается выпадающий список существующих экземпляров сущности.

Если <<lazy-loading,ленивая загрузка>> не настроена, компонент загружает список всех доступных экземпляров в память браузера и сервера. При большом количестве элементов это расходует значительные системные ресурсы и снижает производительность. Кроме того, в длинном выпадающем списке сложно найти нужный экземпляр.

TIP: Если ожидаемое количество элементов велико, например, тысячи или больше, или если выбор требует предоставления дополнительного контекста о каждом элементе, рекомендуется использовать xref:flow-ui:vc/components/entityPicker.adoc[entityPicker].

// === When to use
//
// Use `entityComboBox` if:
//
// * The field value is a reference to an entity instance.
// * Users need to select a single item.
// * The number of items is too large for xref:flow-ui:vc/components/radioButtonGroup.adoc[radioButtonGroup] or xref:flow-ui:vc/components/listBox.adoc[listBox].
// * Users need to perform actions on the selected entity instance.

В следующем примере `entityComboBox` используется для выбора отдела пользователя:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/simple/entity-combobox-simple.xml[tags=simple]
----

Дополнительные интерактивные примеры использования `entityComboBox` и его вариантов:

* https://demo.jmix.ru/ui-samples/sample/entity-combobox-simple[entityCombobox с действиями]
* https://demo.jmix.ru/ui-samples/sample/entity-combobox-items-query[entityComboBox с обратным вызовом для получения элементов^]

[[data-binding]]
== `entityComboBox` связанный с данными

Используйте атрибуты `dataContainer` и `property`, чтобы связать `entityComboBox` с атрибутом сущности. Контейнер данных предоставляет экземпляр сущности, `property` указывает изменяемый ссылочный атрибут, а `itemsContainer` — доступные для выбора сущности.

== Выбор сущности

Если вам просто нужно выбрать экземпляр конкретной сущности, укажите эту сущность, используя атрибут `metaClass`. Чтобы указать коллекцию экземпляров для выбора, используйте атрибут <<itemsContainer,itemsContainer>>.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitycombobox/entity-combobox-view.xml[tags=binding-metaclass]
----

== Обновление атрибута связанной сущности

Выбор экземпляра часто изменяет атрибут другого экземпляра. В <<basics,приведённом выше примере>> выбор `Department` связывает экземпляр `User` с выбранным отделом.

В таких случаях вам нужно будет привязать компонент к контейнеру данных, содержащему экземпляр, и указать атрибут для обновления, используя атрибуты xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property] соответственно. Чтобы указать коллекцию экземпляров для выбора, используйте атрибут <<itemsContainer,itemsContainer>>.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitycombobox/entity-combobox-view.xml[tags=binding-container]
----

[[actions]]
== Действия

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/entity-combobox-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Изначально `entityComboBox` не содержит действий. Добавьте их явно, например:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/simple/entity-combobox-simple.xml[tags=simple]
----

[TIP]
====
Чтобы добавить действие в Jmix Studio, выберите компонент в XML-дескрипторе экрана или в панели структуры *Jmix UI* и нажмите кнопку xref:studio:screen-designer.adoc#add-picker-action[Add->Action] в панели инспектора *Jmix UI*.
====

Подробную информацию об определении пользовательских и предопределённых действий смотрите в разделе xref:flow-ui:vc/components/entityPicker.adoc#actions[Действия] для `entityPicker`.

[[lazy-loading]]
== Ленивая загрузка

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/entity-combobox-items-query" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент может загружать элементы порциями по мере ввода, а не все сразу. Это обеспечивает быструю работу даже с большим количеством элементов.

[[declarative-lazy-loading]]
== Декларативная конфигурация

Чтобы реализовать ленивую загрузку в дескрипторе экрана, вместо указания атрибута `itemsContainer`, настройте вложенный элемент `itemsQuery`. Например, чтобы загружать не более 30 элементов и отображать их в списке, сделайте следующее:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/itemsquery/entity-combobox-items-query.xml[tags=items-query]
----

Атрибут `pageSize` задаёт размер порции при загрузке данных из базы. Значение по умолчанию — `50`.

Атрибуты `itemsQuery` управляют загрузкой данных:
* `class` – указывает полное имя класса сущностей, экземпляры которого будут выбраны.
* `searchStringFormat` – строка, содержащая заполнитель переменной, который впоследствии заменяется фактическим значением.
* `escapeValueForLike` – указывает, следует ли искать значения, содержащие специальные символы. По умолчанию это значение `false`.
* `fetchPlan` – и необязательный дескриптор встроенного плана выборки.
JPQL-запрос определяет загружаемые элементы.

include::flow-ui:vc/items-fetch-callback-note.adoc[]

[[programmatic-lazy-loading]]
== Программная конфигурация

Получение элементов также можно определить программно, используя обработчик `itemsFetchCallback`. Например:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/itemsquery/entity-combobox-items-query.xml[tags=items-query]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/entitycombobox/itemsquery/EntityComboBoxItemsQuery.java[tags=programmatic-fetch]
----

В этом примере данные извлекаются с использованием xref:data-access:data-manager.adoc[DataManager], но вы можете использовать этот подход для загрузки из пользовательского сервиса.

[[renderer]]
== Пользовательский рендерер

По умолчанию экземпляры, отображаемые в выпадающем списке, обычно отображаются как простой текст. Пользовательский рендерер позволяет задать собственную логику отображения для каждого элемента, включая различные компоненты, значки или даже контейнеры.

Например, определим следующий рендерер, чтобы добавить значок перед названием отдела:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitycombobox/EntityComboBoxView.java[tags=renderer]
----

[[fragment-renderer]]
В качестве альтернативы вы можете отображать элементы, используя вложенный элемент `fragmentRenderer`. Обратитесь к разделу xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Рендерер фрагментов] для получения дополнительной информации.

// [[filtering]]
// == Custom Filtering
//
// `entityComboBox` filtering, by default, is configured to only show items that contain the entered value. Custom filtering is also possible. For example, if you only want to show items that start with the user’s input:
//
// [source,java,indent=0]
// ----
// include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitycombobox/EntityComboBoxView.java[tags=departmentsDc;filterEntityComboBox;filter]
// ----

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`entityComboBox` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|Если атрибут `allowCustomValue` равен `true`, пользователь может ввести строковые значения, которые не соответствуют ни одной существующей метке элемента, что приведет к срабатыванию <<CustomValueSetEvent,CustomValueSetEvent>>.
|—

|[[autoOpen]]`autoOpen`
|Определяет, открывается ли всплывающий список элементов при получении полем фокуса.
|—

|[[itemsContainer]]`itemsContainer`
|Задаёт имя контейнера данных со списком элементов.
|—

|[[metaClass]]`metaClass`
|Задаёт метакласс.
|—

|[[opened]]`opened`
|Определяет, открыт ли выпадающий список.
|—

|[[pageSize]]`pageSize`
|Задаёт размер страницы.
|—
|===

`entityComboBox` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#pattern[pattern] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`entityComboBox` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|`com.vaadin.flow.component.combobox.ComboBoxBase.CustomValueSetEvent` запускается, когда пользователь вводит непустое значение, которое не соответствует ни одному из существующих элементов.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Предоставляет текст, отображаемый для каждого элемента.

|[[validator]]`validator`
|Проверяет значение компонента.

|`renderer`
|Предоставляет компонент для отображения каждого элемента. See <<renderer,Пользовательский рендерер>>.
|===

`entityComboBox` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `entityComboBox` может содержать следующие вложенные элементы: <<actions,actions>>, <<fragment-renderer,fragmentRenderer>>, <<declarative-lazy-loading, itemsQuery>>, xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/components/tooltip.adoc[tooltip], и xref:vc/miscellaneous/validator.adoc[validator].
