= entityComboBox
:page-aliases: vcl/components/entity-combo-box.adoc

`entityComboBox` lets users select an xref:data-model:entities.adoc[entity] instance from a drop-down list and run actions for it.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`entityComboBox`

|Java Class
|`EntityComboBox`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/entity-combobox-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The `entityComboBox` component is commonly used when the field value must represent a reference to an entity. It enables users to select a particular entity instance with the ability to perform relevant actions.

Clicking the field or arrow button opens a drop-down list containing all existing instances of the entity.

Note that unless you have configured <<lazy-loading, lazy loading>>, the component will load a list of all available instances into both the browser's memory and the server's memory. This can consume substantial system resources and may impact performance, especially for large number of items. Furthermore, users may find it challenging to search for a specific instance within a lengthy drop-down list.

TIP: If the expected number of items is large, such as thousands or more, or if making a selection requires providing additional context about each item, it is recommended to use xref:flow-ui:vc/components/entityPicker.adoc[entityPicker].

// === When to use
//
// Use `entityComboBox` if:
//
// * The field value is a reference to an entity instance.
// * Users need to select a single item.
// * The number of items is too large for xref:flow-ui:vc/components/radioButtonGroup.adoc[radioButtonGroup] or xref:flow-ui:vc/components/listBox.adoc[listBox].
// * Users need to perform actions on the selected entity instance.

The following example uses `entityComboBox` to select the department to which a user belongs:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/simple/entity-combobox-simple.xml[tags=simple]
----

For more interactive examples of the `entityComboBox` and its variations, see:

* https://demo.jmix.io/ui-samples/sample/entity-combobox-simple[entityCombobox with actions]
* https://demo.jmix.io/ui-samples/sample/entity-combobox-items-query[entityComboBox with items fetchCallback^]

[[data-binding]]
== Data-aware `entityComboBox`

Use the `dataContainer` and `property` attributes to bind `entityComboBox` to an entity attribute. The data container provides the entity instance, `property` identifies the reference attribute to update, and `itemsContainer` supplies the entities available for selection.

== Selecting an Entity

If you simply need a way to select an instance of a specific entity, specify that entity using the `metaClass` attribute. To specify a collection of instances for selection use the <<itemsContainer,itemsContainer>> attribute.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitycombobox/entity-combobox-view.xml[tags=binding-metaclass]
----

== Updating a Related Entity Attribute

Selecting an instance is often intended to update an attribute within another instance. In the <<basics, example above>>, selecting a `Department` instance updates the `User` instance by associating it with the chosen department.

In such cases you will need to bind the component to the data container holding the instance and specify the attribute to be updated using the xref:vc/common-attributes.adoc#dataContainer[dataContainer] and xref:vc/common-attributes.adoc#property[property] attributes respectively. To specify a collection of instances for selection use the <<itemsContainer,itemsContainer>> attribute.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitycombobox/entity-combobox-view.xml[tags=binding-container]
----

[[actions]]
== Actions

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/entity-combobox-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Initially `entityComboBox` does not have any actions. You need to add them explicitly, for example:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/simple/entity-combobox-simple.xml[tags=simple]
----

[TIP]
====
To add `action` in Jmix Studio, select the component in the view descriptor XML or in the *Jmix UI* structure panel and click on the xref:studio:screen-designer.adoc#add-picker-action[Add->Action] button in the *Jmix UI* inspector panel.
====

See detailed information on defining custom and predefined actions in the xref:flow-ui:vc/components/entityPicker.adoc#actions[Actions] section for `entityPicker`.

[[lazy-loading]]
== Lazy Loading

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/entity-combobox-items-query" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The component supports loading items in batches in response to user input, rather than loading all items at once. This helps to ensure a smooth user experience, even when dealing with a large number of items.

[[declarative-lazy-loading]]
== Declarative Items Query

To implement lazy loading in the view descriptor, instead of specifying the `itemsContainer` attribute configure the `itemsQuery` nested element. For example, to load at most 30 items and show them in the list, do the following:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/itemsquery/entity-combobox-items-query.xml[tags=items-query]
----

The `pageSize` attribute defines the batch size when loading data from the database. It is 50 by default.

Attributes in the `itemsQuery` provide control over the fetching process. They are as follows:
    *  `class` – specifies a full qualified name of the entity class which instances will be fetched.
    *  `searchStringFormat` – a string that contains a variable placeholder, which is subsequently replaced with an actual value.
    * `escapeValueForLike` – specifies whether to search for values containing special symbols. By default, this value is `false`.
    * `fetchPlan` – and optional descriptor of inline fetch plan.
A JPQL query specifies the items to load.

include::flow-ui:vc/items-fetch-callback-note.adoc[]

[[programmatic-lazy-loading]]
== Programmatic Items Fetching

Items fetching can also be defined programmatically using the `itemsFetchCallback` handler. For example:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitycombobox/itemsquery/entity-combobox-items-query.xml[tags=items-query]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/entitycombobox/itemsquery/EntityComboBoxItemsQuery.java[tags=programmatic-fetch]
----

In this example, data is fetched using xref:data-access:data-manager.adoc[DataManager], but you can use this approach to load from a custom service as well.

[[renderer]]
== Custom Renderer

By default, instances displayed in a drop-down list are typically rendered as plain text. A custom renderer allows you to define a rendering logic for each item in the drop-down, enabling you to include various components, icons, or even layouts.

For example, define the following renderer to add an icon before a department name:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitycombobox/EntityComboBoxView.java[tags=renderer]
----

[[fragment-renderer]]
Alternatively, you can render items using a nested `fragmentRenderer` element. Refer to the xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Fragment Renderer] section for more information.

// [[filtering]]
// == Custom Filtering
//
// `entityComboBox` filtering, by default, is configured to only show items that contain the entered value. Custom filtering is also possible. For example, if you only want to show items that start with the user’s input:
//
// [source,java,indent=0]
// ----
// include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitycombobox/EntityComboBoxView.java[tags=departmentsDc;filterEntityComboBox;filter]
// ----

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`align-start`
|Aligns the field value to the start side, taking the current text direction into account.
|Aura

|`align-end`
|Aligns the field value to the end side, taking the current text direction into account.
|Aura

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo

|`small`
|Makes the component smaller.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `entityComboBox`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[allowCustomValue]]`allowCustomValue`
|If the `allowCustomValue` attribute is `true`, the user can input string values that do not match any existing item labels, which will fire <<CustomValueSetEvent,CustomValueSetEvent>>.
|—

|[[autoOpen]]`autoOpen`
|Controls whether the item overlay opens when the field receives focus.
|—

|[[itemsContainer]]`itemsContainer`
|Sets the name of a data container which contains a list of items.
|—

|[[metaClass]]`metaClass`
|Sets the meta class.
|—

|[[opened]]`opened`
|Sets whether the drop-down list should be opened or not.
|—

|[[pageSize]]`pageSize`
|Sets the page size.
|—
|===

The following shared attributes are supported by `entityComboBox`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#pattern[pattern] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `entityComboBox`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|`com.vaadin.flow.component.combobox.ComboBoxBase.CustomValueSetEvent` is fired when the user enters a non-empty value that does not match any of the existing items.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Provides the text shown for each item.

|[[validator]]`validator`
|Validates the component value.

|`renderer`
|Provides the component used to render each item. See <<renderer,Custom Renderer>>.
|===

The following shared handlers are supported by `entityComboBox`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

An `entityComboBox` can include <<actions,actions>>, <<fragment-renderer,fragmentRenderer>>, <<declarative-lazy-loading, itemsQuery>>, xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/components/tooltip.adoc[tooltip], and xref:vc/miscellaneous/validator.adoc[validator] as its nested elements.
