= entityPicker
:page-aliases: vcl/components/entity-picker.adoc

`entityPicker` позволяет пользователям выбирать экземпляр xref:data-model:entities.adoc[сущности] на экране поиска и выполнять для него действия.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`entityPicker`

|Java-класс
|`EntityPicker`
|===

[[basics]]
== Быстрый старт

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/entity-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент `entityPicker` обычно используют, когда значение поля должно хранить ссылку на сущность. Он позволяет выбрать экземпляр сущности и выполнить связанные с ним действия.

Нажатие на кнопку выбора открывает диалоговое окно с xref:views/view-classes.adoc#standard-list-view[экраном списка], содержащим экземпляры сущности.

Как и другие экраны приложения, этот экран можно настроить и вывести несколько атрибутов, чтобы пользователю было проще найти нужный экземпляр. Он предоставляет больше контекста, чем xref:vc/components/entityComboBox.adoc[], который отображает только имена экземпляров.

Если количество экземпляров велико, дополнительные элементы загружаются динамически при прокрутке списка.

В следующем примере `entityPicker` используется для выбора отдела пользователя:

NOTE: Для корректной работы примера убедитесь, что определили xref:views/view-classes.adoc#standard-list-view[экран списка] для сущности `Department`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitypicker/simple/entity-picker-simple.xml[tags=quick-start]
----

Дополнительные интерактивные примеры использования `entityPicker` и его вариантов:

* https://demo.jmix.ru/ui-samples/sample/entity-picker-actions[Действия EntityPicker^]
* https://demo.jmix.ru/ui-samples/sample/entity-picker-meta-class[EntityPicker и MetaClass^]

== `entityPicker` связанный с данными

Используйте атрибуты `dataContainer` и `property`, чтобы связать `entityPicker` с атрибутом сущности. Контейнер данных предоставляет экземпляр сущности, а `property` указывает изменяемый ссылочный атрибут.

== Выбор сущности

Если вам просто нужен способ выбора экземпляра определённой сущности, укажите эту сущность, используя атрибут <<metaClass,metaClass>>:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=binding-metaclass]
----

== Обновление атрибута связанной сущности

Выбор экземпляра часто изменяет атрибут другого экземпляра. В <<basics,приведённом выше примере>> выбор `Department` связывает экземпляр `User` с выбранным отделом.

В таких случаях вам нужно будет привязать компонент к контейнеру данных, содержащему экземпляр, и указать атрибут для обновления, используя xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property] соответственно:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=binding-container]
----

[[actions]]
== Действия

Вы можете определить пользовательские и предопределённые действия для `entityPicker`, отображаемые в виде кнопок справа. Это можно сделать либо в XML-дескрипторе, используя вложенный элемент `actions`, либо программно в контроллере, используя метод `addAction()`.

[TIP]
====
Чтобы добавить действие в Jmix Studio, выберите компонент в XML-дескрипторе экрана или в панели структуры *Jmix UI* и нажмите кнопку xref:studio:screen-designer.adoc#add-picker-action[Add] в панели инспектора *Jmix UI*.
====

[[predefined-action]]
== Предопределенные действия

Когда Studio генерирует `entityPicker` на экране деталей, он также генерирует два предопределённых стандартных действия: `entity_lookup` и `entity_clear`. Существуют также действия `entity_open` и `entity_openComposition`.

Используйте атрибуты `type` и `id` для объявления предопределённого действия в XML.

Если вы создаёте `entityPicker` без действий, загрузчик XML определит только действия `entity_lookup` и `entity_clear`. Чтобы добавить другое предопределённое действие, например, `entity_open`, необходимо указать элемент `actions` следующим образом:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=actions]
----

Элемент `actions` не расширяет, а переопределяет набор стандартных действий. Вам следует явно определить идентификаторы всех необходимых действий.

[[custom-actions]]
== Пользовательские действия

Чтобы определить пользовательское действие в XML, используйте вложенный элемент `actions`. Укажите атрибуты `id` и `icon` для действия:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=custom]
----

Затем реализуйте пользовательскую логику в контроллере экрана, подписавшись на `ActionPerformedEvent`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitypicker/EntityPickerView.java[tags=departmentEntityPicker;notifications;onKnowManager]
----

[TIP]
====
Вы можете сгенерировать заглушку обработчика `ActionPerformedEvent` с помощью Jmix Studio.
====

[[add-actions-programmatically]]
== Добавление действий программно

Используйте метод `addAction()` для установки действий программно.

* *Добавление стандартного действия*
+
Например, если компонент определен в XML-дескрипторе без вложенного элемента `actions`, достаточно добавить недостающие стандартные действия:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitypicker/EntityPickerView.java[tags=departmentEntityPicker;actions;onInit;addAction]
----

* *Добавление пользовательского действия*
+
Пример создания пользовательского действия:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitypicker/EntityPickerView.java[tags=departmentEntityPicker;onInit;addCustomAction]
----

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`entityPicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|Определяет, могут ли пользователи вводить значения, отсутствующие среди доступных элементов.
|—

|[[metaClass]]`metaClass`
|Вы можете использовать `entityPicker` без привязки к контейнеру данных, то есть без установки `dataContainer` и `property`.
|—
|===

`entityPicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`entityPicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Возникает, когда пользователь вводит в поле пользовательское значение.

|[[formatter]]`formatter`
|Преобразует значение компонента в текст, отображаемый в поле.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`entityPicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `entityPicker` может содержать следующие вложенные элементы: <<actions,actions>>, xref:vc/miscellaneous/formatter.adoc[formatter], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/miscellaneous/prefix-suffix.adoc[suffix], xref:vc/components/tooltip.adoc[tooltip], и xref:vc/miscellaneous/validator.adoc[validator].
