= entityPicker
:page-aliases: vcl/components/entity-picker.adoc

`entityPicker` lets users select an xref:data-model:entities.adoc[entity] instance in a lookup view and run actions for it.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`entityPicker`

|Java Class
|`EntityPicker`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/entity-picker-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The `entityPicker` component is commonly used when the field value must represent a reference to an entity. It combines the ability to select a particular entity instance with the ability to perform relevant actions.

Clicking the lookup button opens a dialog with a xref:flow-ui:views/view-classes.adoc#standard-list-view[list view] containing entity instances.

Like other views in the application, this view is configurable, allowing multiple attributes to help users easily identify the needed instance. It provides more context than the xref:vc/components/entityComboBox.adoc[] which only shows instance names.

When the number of instances is large, additional instances are loaded dynamically as you navigate the list.

The following example uses `entityPicker` to select the department to which a user belongs:

NOTE: For the example to work correctly, ensure that you define a xref:flow-ui:views/view-classes.adoc#standard-list-view[list view] for the Department entity.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/entitypicker/simple/entity-picker-simple.xml[tags=quick-start]
----

For more interactive example of `entityPicker` and its variations, see:

* https://demo.jmix.io/ui-samples/sample/entity-picker-actions[entityPicker with actions^]
* https://demo.jmix.io/ui-samples/sample/entity-picker-meta-class[entityPicker with metaClass^]

== Data-aware `entityPicker`

Use the `dataContainer` and `property` attributes to bind `entityPicker` to an entity attribute. The data container provides the entity instance, and `property` identifies the reference attribute to update.

== Selecting an Entity

If you simply need a way to select an instance of a specific entity, specify that entity using the <<metaClass,metaClass>> attribute:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=binding-metaclass]
----

== Updating a Related Entity Attribute

Selecting an instance is often intended to update an attribute within another instance. In the <<basics, example above>>, selecting a `Department` instance updates the `User` instance by associating it with the chosen department.

In such cases you will need to bind the component to the data container holding the instance and specify the attribute to be updated using the xref:vc/common-attributes.adoc#dataContainer[dataContainer] and xref:vc/common-attributes.adoc#property[property] attributes respectively:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=binding-container]
----

[[actions]]
== Actions

You can define custom and predefined actions for `entityPicker` displayed as buttons on the right.
You can do it either in the XML descriptor using the `actions` nested element or programmatically in the controller using the `addAction()` method.

[TIP]
====
To add `action` in Jmix Studio, select the component in the screen descriptor XML or in the *Jmix UI* structure panel and click on the xref:studio:screen-designer.adoc#add-picker-action[Add] button in the *Jmix UI* inspector panel.
====

[[predefined-action]]
== Entity Picker with Predefined Actions

When Studio generates `entityPicker` in the detail view, it also generates two predefined standard actions: `entity_lookup` and `entity_clear`. There are also the `entity_open` and `entity_openComposition` actions.

Use the `type` and `id` attributes for declaring predefined action in XML.

If you create `entityPicker` without actions, the XML loader will define only the `entity_lookup` and `entity_clear` actions. To add another predefined action, for example, the `entity_open`, you should specify the `actions` element as follows:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=actions]
----

The `actions` element does not extend but overrides a set of standard actions. You should define the identifiers of all required actions explicitly.

[[custom-actions]]
== Entity Picker with Custom Actions

To define a custom action in XML, use the `actions` nested element. Specify the `id` and `icon` attributes for the `action`:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/entitypicker/entity-picker-view.xml[tags=custom]
----

Then implement custom logic in the view controller by subscribing to `ActionPerformedEvent`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitypicker/EntityPickerView.java[tags=departmentEntityPicker;notifications;onKnowManager]
----

[TIP]
====
You can generate the `ActionPerformedEvent` handler implementation stub using Studio.
====

[[add-actions-programmatically]]
== Programmatically Added Actions

Use the `addAction()` method to set actions programmatically.

* *Adding Standard Action*
+
For example, if the component is defined in the XML descriptor without the `actions` nested element, it is sufficient to add missing standard actions:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitypicker/EntityPickerView.java[tags=departmentEntityPicker;actions;onInit;addAction]
----

* *Adding Custom Action*
+
An example of creating a custom action:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/entitypicker/EntityPickerView.java[tags=departmentEntityPicker;onInit;addCustomAction]
----

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`align-start`
|Aligns the field value to the start side, taking the current text direction into account.
|Aura

|`align-end`
|Aligns the field value to the end side, taking the current text direction into account.
|Aura

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo

|`small`
|Makes the component smaller.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `entityPicker`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[allowCustomValue]]`allowCustomValue`
|Controls whether users can enter values that are not in the available items.
|—

|[[metaClass]]`metaClass`
|You can use `entityPicker` without binding to the data container, that is, without setting `dataContainer` and `property`.
|—
|===

The following shared attributes are supported by `entityPicker`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `entityPicker`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Fired when the user enters a custom value in the field.

|[[formatter]]`formatter`
|Converts the component value to the text shown in the field.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `entityPicker`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

An `entityPicker` can include <<actions,actions>>, xref:vc/miscellaneous/formatter.adoc[formatter], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/miscellaneous/prefix-suffix.adoc[suffix], xref:vc/components/tooltip.adoc[tooltip], and xref:vc/miscellaneous/validator.adoc[validator] as its nested elements.
