= fileUploadField
:page-aliases: vcl/components/file-upload-field.adoc

`fileUploadField` загружает файл в память в виде массива байтов.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`fileUploadField`

|Java-класс
|`FileUploadField`
|===

[[basics]]
== Основы

Компонент может содержать надпись, ссылку на загруженный файл и кнопку загрузки. При нажатии на кнопку загрузки появляется стандартное диалоговое окно выбора файла, позволяющее пользователю выбрать файл.

`fileUploadField` может работать как без привязки к атрибуту сущности, так и с <<data-binding,привязка данных>>.

Ниже мы покажем пример использования компонента без привязки данных. Вы можете использовать его для непосредственной обработки загруженного файла, не связывая его ни с какой сущностью Jmix. Это отлично подходит для ситуаций, когда вы хотите обработать файл, сохранить его в другом месте или выполнить другую операцию, не сохраняя его постоянно в базе данных.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/fileuploadfield/file-upload-field-view.xml[tags=basics-0]
----

[[FileUploadSucceededEvent-example]]
Теперь вы можете обрабатывать загруженный файл непосредственно в обработчике события `FileUploadSucceededEvent`:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/fileuploadfields/fileuploadfield/FileUploadFieldSample.java[tags=upload-succeeded]
----

NOTE: Внутренне `fileUploadField` использует Vaadin API `UploadHandler` и сохраняет загруженный файл в памяти как массив байтов. Физический файл в файловой системе не создаётся, поэтому такой подход лучше всего подходит для небольших файлов, не требующих постоянного хранения.

[TIP]
====
Для загрузки и сохранения больших файлов рекомендуется использовать компонент xref:flow-ui:vc/components/fileStorageUploadField.adoc[fileStorageUploadField].

Для одновременной загрузки нескольких файлов следует использовать компонент xref:flow-ui:vc/components/upload.adoc[upload] вместо `fileUploadField`.
====

[[data-binding]]
== `fileUploadField` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/file-upload-field" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`fileUploadField` позволяет пользователям сохранять загруженный файл в атрибуте сущности в виде массива байтов.

В примере ниже атрибут `document` сущности `User` имеет тип массива байтов.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/entity/User.java[tags=document]
----

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/fileuploadfields/fileuploadfield/file-upload-field.xml[tags=data-binding]
----

`fileUploadField` имеет ссылку на контейнер, указанный в атрибуте `dataContainer`; атрибут `property` содержит имя атрибута сущности, который отображается в `fileUploadField`.

Чтобы сохранить файл в файловом хранилище и связать его с сущностью как `FileRef`, используйте компонент xref:flow-ui:vc/components/fileStorageUploadField.adoc[fileStorageUploadField].

== Атрибуты

`fileUploadField` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[acceptedFileTypes]]`acceptedFileTypes`
|Задаёт допустимые типы файлов.
|—

|[[clearButtonAriaLabel]]`clearButtonAriaLabel`
|Устанавливает метку арии кнопки очистки.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Определяет, отображается ли в поле кнопка очистки.
|`false`

|[[connectingStatusText]]`connectingStatusText`
|Устанавливает текст состояния соединения.
|—

|[[dropAllowed]]`dropAllowed`
|Определяет, могут ли пользователи перетаскивать файлы в область загрузки.
|—

|[[fileName]]`fileName`
|Устанавливает текст, который должен отображаться, если значение задано из контейнера данных.
|—

|[[fileNameVisible]]`fileNameVisible`
|Управляет отображением выбранного имени файла.
|—

|[[fileNotSelectedText]]`fileNotSelectedText`
|Устанавливает невыбранный текст файла.
|—

|[[fileTooBigText]]`fileTooBigText`
|Устанавливает в файле слишком большой текст.
|—

|[[incorrectFileTypeText]]`incorrectFileTypeText`
|Устанавливает неправильный текст типа файла.
|—

|[[maxFileSize]]`maxFileSize`
|Задаёт максимальный размер файла.
|—

|[[processingStatusText]]`processingStatusText`
|Устанавливает текст статуса обработки.
|—

|[[remainingTimeText]]`remainingTimeText`
|Устанавливает текст оставшегося времени.
|—

|[[remainingTimeUnknownText]]`remainingTimeUnknownText`
|Устанавливает оставшееся время неизвестного текста.
|—

|[[uploadDialogCancelText]]`uploadDialogCancelText`
|Устанавливает текст отмены диалога загрузки.
|—

|[[uploadDialogTitle]]`uploadDialogTitle`
|Устанавливает заголовок диалога загрузки.
|—

|[[uploadIcon]]`uploadIcon`
|Задаёт значок загрузки.
|—

|[[uploadText]]`uploadText`
|Задаёт текст загрузки.
|—
|===

`fileUploadField` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`fileUploadField` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[FileUploadFailedEvent]]`FileUploadFailedEvent`
|Запускается при сбое загрузки файла.

|[[FileUploadFileRejectedEvent]]`FileUploadFileRejectedEvent`
|Вызывается, когда выбранный файл отклонен, поскольку он нарушает ограничение загрузки.

|[[FileUploadFinishedEvent]]`FileUploadFinishedEvent`
|Запускается после завершения загрузки.

|[[FileUploadProgressEvent]]`FileUploadProgressEvent`
|Запускается при изменении хода загрузки.

|[[FileUploadStartedEvent]]`FileUploadStartedEvent`
|Вызывается при начале загрузки файла.

|[[FileUploadSucceededEvent]]`FileUploadSucceededEvent`
|`io.jmix.flowui.kit.component.upload.event.FileUploadSucceededEvent` запускается, когда компонент `Upload` запускает `SucceededEvent`.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`fileUploadField` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `fileUploadField` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip] и xref:icons/custom-icons.adoc[uploadIcon].
