= fileUploadField
:page-aliases: vcl/components/file-upload-field.adoc

`fileUploadField` uploads a file into memory as a byte array.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`fileUploadField`

|Java Class
|`FileUploadField`
|===

[[basics]]
== Basics

The component can contain a label, a link to the uploaded file, and an upload button. When the upload button is clicked, a standard file picker dialog pops up, allowing the user to select a file.

`fileUploadField` can work both without being bound to an entity attribute and with <<data-binding,data binding>>.

Below we will show an example of using the component without data binding. You can use it to handle the uploaded file directly without associating it with any Jmix entity. This is great for situations where you want to process the file, save it to a different location, or perform some other operation without storing it persistently in the database.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/fileuploadfield/file-upload-field-view.xml[tags=basics-0]
----

[[FileUploadSucceededEvent-example]]
Now you can handle the uploaded file directly within the `FileUploadSucceededEvent`:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/fileuploadfields/fileuploadfield/FileUploadFieldSample.java[tags=upload-succeeded]
----

NOTE: Internally, `fileUploadField` uses Vaadin's `UploadHandler` API and stores the uploaded file in memory as a byte array. No physical file is created on the file system, so this approach is best suited for smaller files that don't require persistent storage.

[TIP]
====
For uploading and saving large files it is recommended to use the xref:flow-ui:vc/components/fileStorageUploadField.adoc[fileStorageUploadField] component.

To upload multiple files simultaneously, you should use the xref:flow-ui:vc/components/upload.adoc[upload] component instead of `fileUploadField`.
====

[[data-binding]]
== Data-aware `fileUploadField`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/file-upload-field" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`fileUploadField` allows users to save the uploaded file to an entity attribute as a byte array.

In the example below, the `document` attribute of the `User` entity has the byte array type.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/entity/User.java[tags=document]
----

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/fileuploadfields/fileuploadfield/file-upload-field.xml[tags=data-binding]
----

`fileUploadField` has a link to the container specified in the `dataContainer` attribute; the `property` attribute contains the name of the entity attribute that is displayed in `fileUploadField`.

To store the file in the file storage and link to the entity as `FileRef`, use the xref:flow-ui:vc/components/fileStorageUploadField.adoc[fileStorageUploadField] component.

== Attributes

The following attributes are specific to `fileUploadField`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[acceptedFileTypes]]`acceptedFileTypes`
|Sets the accepted file types.
|—

|[[clearButtonAriaLabel]]`clearButtonAriaLabel`
|Sets the clear button aria label.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Controls whether the field displays a clear button.
|`false`

|[[connectingStatusText]]`connectingStatusText`
|Sets the connecting status text.
|—

|[[dropAllowed]]`dropAllowed`
|Controls whether users can drag files onto the upload area.
|—

|[[fileName]]`fileName`
|Sets the text that should be shown if the value is set from the data container.
|—

|[[fileNameVisible]]`fileNameVisible`
|Controls whether the selected file name is displayed.
|—

|[[fileNotSelectedText]]`fileNotSelectedText`
|Sets the file not selected text.
|—

|[[fileTooBigText]]`fileTooBigText`
|Sets the file too big text.
|—

|[[incorrectFileTypeText]]`incorrectFileTypeText`
|Sets the incorrect file type text.
|—

|[[maxFileSize]]`maxFileSize`
|Sets the maximum file size.
|—

|[[processingStatusText]]`processingStatusText`
|Sets the processing status text.
|—

|[[remainingTimeText]]`remainingTimeText`
|Sets the remaining time text.
|—

|[[remainingTimeUnknownText]]`remainingTimeUnknownText`
|Sets the remaining time unknown text.
|—

|[[uploadDialogCancelText]]`uploadDialogCancelText`
|Sets the upload dialog cancel text.
|—

|[[uploadDialogTitle]]`uploadDialogTitle`
|Sets the upload dialog title.
|—

|[[uploadIcon]]`uploadIcon`
|Sets the upload icon.
|—

|[[uploadText]]`uploadText`
|Sets the upload text.
|—
|===

The following shared attributes are supported by `fileUploadField`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `fileUploadField`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[FileUploadFailedEvent]]`FileUploadFailedEvent`
|Fired when uploading a file fails.

|[[FileUploadFileRejectedEvent]]`FileUploadFileRejectedEvent`
|Fired when a selected file is rejected because it violates an upload constraint.

|[[FileUploadFinishedEvent]]`FileUploadFinishedEvent`
|Fired after an upload finishes.

|[[FileUploadProgressEvent]]`FileUploadProgressEvent`
|Fired as upload progress changes.

|[[FileUploadStartedEvent]]`FileUploadStartedEvent`
|Fired when uploading a file starts.

|[[FileUploadSucceededEvent]]`FileUploadSucceededEvent`
|`io.jmix.flowui.kit.component.upload.event.FileUploadSucceededEvent` is fired when the `Upload` component fires `SucceededEvent`.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `fileUploadField`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `fileUploadField` can include xref:vc/components/tooltip.adoc[tooltip] and xref:icons/custom-icons.adoc[uploadIcon] as its nested elements.
