= geoMap
:page-aliases: maps:map-component.adoc

[NOTE.addon-component]
====
This component requires the commercial xref:maps:index.adoc#installation[Maps add-on].
====

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/maps" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`geoMap` displays geographical data.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`geoMap`

|Java Class
|`GeoMap`
|===

[[basics]]
== Basics

[[map]]

Declare the `maps` namespace in the view's XML descriptor:

[source,xml,indent=0]
----
include::maps:example$/maps-ex2/src/main/resources/com/company/mapssample/view/mapbasic/map-basic-view.xml[tags=xmlns]
----

[TIP]
====
Studio adds the namespace automatically when you add the component using the *Add Component* action in the top actions panel. See xref:studio:view-designer.adoc#component-palette[Component Palette].
====

Then add the `geoMap` element:

[source,xml,indent=0]
----
<maps:geoMap id="map"
             height="100%"
             width="100%"/>
----

[[how-to-inject]]
With the `id` attribute set, inject the `GeoMap` component into the controller to access its API directly:

[source,java,indent=0]
----
include::maps:example$/maps-ex2/src/main/java/com/company/mapssample/view/mapbasic/MapBasicView.java[tags=geoMap;onInit]
----

[[layer]]
== Layer

The `GeoMap` component can include multiple layers that display different types of geographic information.
Initially, the map does not have layers.

The Maps add-on provides the following layer types:

* xref:maps:layers-sources.adoc#tile-layer[TileLayer] displays pre-rendered tiled images organized by zoom levels.
* xref:maps:layers-sources.adoc#image-layer[ImageLayer] displays static images or images obtained from a Web Map Service (WMS).
* xref:maps:layers-sources.adoc#vector-layer[VectorLayer] displays features and geometries.
* xref:maps:high-density-data-visualization.adoc#heatmap[HeatmapLayer] renders point features as a heatmap.

See xref:maps:layers-sources.adoc[Layers and Sources] for the sources supported by each layer type and usage examples.

You can inject a layer into the controller and interact with it programmatically by accessing its methods directly:

[source,java,indent=0]
----
include::maps:example$/maps-ex2/src/main/java/com/company/mapssample/view/mapbasic/MapBasicView.java[tags=mapTile;onInit]
----

[[source]]
== Source

A xref:maps:layers-sources.adoc[source] represents the data used to render map layers on the map component. Sources provide the spatial information that defines the content and appearance of the map layers.

The Maps add-on provides the following source types:

* For `TileLayer`: xref:maps:layers-sources.adoc#osm-source[`OsmSource`], xref:maps:layers-sources.adoc#xyz-source[`XyzSource`], and xref:maps:layers-sources.adoc#wms-source[`WmsSource`].
* For `ImageLayer`: xref:maps:layers-sources.adoc#image-static-source[`ImageStaticSource`] and xref:maps:layers-sources.adoc#image-wms-source[`ImageWmsSource`].
* For `VectorLayer`: xref:maps:layers-sources.adoc#vector-source[`VectorSource`], xref:maps:layers-sources.adoc#data-vector-source[`DataVectorSource`], and xref:maps:high-density-data-visualization.adoc#cluster-source[`ClusterSource`].
* For `HeatmapLayer`: xref:maps:high-density-data-visualization.adoc#heatmap[`HeatmapDataVectorSource`] and `VectorSource`.

See xref:maps:layers-sources.adoc[Layers and Sources] for source descriptions and usage examples.

The following example defines an `OsmSource` for a tile layer:

[source,xml,indent=0]
----
include::maps:example$/maps-ex2/src/main/resources/com/company/mapssample/view/mapbasic/map-basic-view.xml[tags=osmSource]
----

You can <<how-to-inject,inject>> a source into the controller and interact with it programmatically by accessing its methods directly:

[source,java,indent=0]
----
include::maps:example$/maps-ex2/src/main/java/com/company/mapssample/view/mapbasic/MapBasicView.java[tags=osmSource;onInit]
----
// You can specify additional parameters:
//
// * `attributions` - information about copyrights and licences that need to be displayed on the map when using data from that source. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_Source-Source.html[Source^].
// * `cacheSize` - the tile cacheSize. Note, the `cacheSize` attribute is set only at creation time and cannot be changed at runtime. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_Tile-TileSource.html[TileSource^].
// * `crossOrigin` is used for loaded images. Note, `crossOrigin` is set only at creation time and cannot be changed at runtime. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_OSM-OSM.html[OSM^].
// * `maxZoom` sets the maximum zoom level. The default value is 42. Note, the `maxZoom` attribute is set only at creation time and cannot be changed at runtime. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_XYZ-XYZ.html[XYZ^].
// * `opaque` sets whether the layer is opaque. The default value is `true`. Note, the `opaque` attribute is set only at creation time and cannot be changed at runtime. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_OSM-OSM.html[OSM].
// * `url` sets the URL template. Must include \{x}, \{y} or {-y}, and \{z} placeholders. The default value is `++https://tile.openstreetmap.org/{z}/{x}/{y}.png++`. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_OSM-OSM.html[OSM^].
// * `wrapX` sets whether the source should be looped along the X coordinate. The default value for `Source` is `false`. Note, the `wrapX` attribute is set only at creation time and cannot be changed at runtime. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_source_Source-Source.html[Source^].

[[view]]
== View

https://openlayers.org/en/v8.2.0/apidoc/module-ol_View-View.html[View^] defines how the map is displayed in terms of its center, zoom level, rotation, and projection. It essentially sets the initial state of the map when it is loaded in the user interface.

By default, the `geoMap` component displays a world map with an initial geographical center at `(0,0)`.

[source,xml,indent=0]
----
include::maps:example$/maps-ex2/src/main/resources/com/company/mapssample/view/mapbasic/map-basic-view.xml[tags=mapView]
----

You can specify additional parameters:

* `centerX` defines latitude of the initial geographical center of the map. It is passed to the `org.locationtech.jts.geom.Coordinate` object.
* `centerY` defines longitude of the initial geographical center of the map. It is passed to the `org.locationtech.jts.geom.Coordinate` object.
* `maxZoom` - sets the maximum zoom level for the view.
//The default value is 28. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_View-View.html#setMaxZoom[setMaxZoom^].
* `minZoom` - sets a minimum zoom level for the view.
//The default value is 0. For more details see https://openlayers.org/en/v8.1.0/apidoc/module-ol_View-View.html#setMinZoom[setMinZoom^].
* `projection` defines the coordinate reference system (CRS) used to display geographic data on a map. It transforms three-dimensional Earth coordinates onto a two-dimensional plane. Common projections include `EPSG:3857` (Web Mercator) and `EPSG:4326` (WGS 84). The default projection is https://epsg.io/3857[EPSG:3857^]. You can set a <<custom-projection,custom projection>>.
* `rotation` - sets the rotation for the view in radians (positive rotation clockwise, 0 means North). For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_View-View.html#setRotation[setRotation^].
* `zoom` defines the specific zoom level. The zoom level begins at 0, representing the maximum zoomed-out view, and progressively rises as you zoom in for a closer perspective.

[[custom-projection]]
== [[set-custom-projection]]Custom Projection

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/geo-map-custom-projection" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Follow these steps to configure a custom projection:

. *Define Projection Bean*. Register the projection in your Spring configuration using https://epsg.io/21781.proj4[PROJ.4^] format:
+
[source,java,indent=0]
----
include::maps:example$/maps-ex2/src/main/java/com/company/mapssample/MapsEx2Application.java[tags=register-projection]
----

. *Configure Map Component*. Specify the `projection` attribute for a `mapView` in your XML descriptor:
+
[source,xml,indent=0]
----
include::maps:example$/maps-ex2/src/main/resources/com/company/mapssample/view/customprojection/custom-projection-view.xml[tags=map]
----

. *Initialize in Controller*. Apply the projection programmatically to all map components on the page:
+
[source,java,indent=0]
----
include::maps:example$/maps-ex2/src/main/java/com/company/mapssample/view/customprojection/CustomProjectionView.java[tags=set-projection]
----
+
NOTE: The projection applies to all map components on the page. Once set, all coordinate operations use the projection's units (meters, degrees, etc.).

[[extent]]
== Extent

The https://openlayers.org/en/v8.2.0/apidoc/module-ol_extent.html#~Extent[extent^] specifies the geographic boundaries of the map <<view,view>> or a specific <<layer,layer>> in terms of coordinates, defining the visible area on the map.

Extent is typically defined by minimum (top-left corner) and maximum (bottom-right corner) coordinate values in the form of [`minX`, `minY`, `maxX`, `maxY`], representing the bounding box of the area.

Choose a layer or the `mapView` element in the *Jmix UI* structure panel or in the view XML descriptor, and then click the *Add* button in the inspector panel. From the drop-down list, select *Extent*, and configure the `minX`, `minY`, `maxX` and `maxY` attributes as indicated below.

[source,xml,indent=0]
----
include::maps:example$/maps-ex2/src/main/resources/com/company/mapssample/view/mapbasic/map-basic-view.xml[tags=extent]
----

[[extent-constraint-options]]
=== Extent Constraint Options

By default, when `mapView` has an `extent`, OpenLayers constrains the whole viewport to stay inside this extent. In responsive layouts, this can force the map to zoom in when the map container aspect ratio differs from the extent aspect ratio.

Use the following `mapView` attributes to adjust this behavior:

* `showFullExtent` - allows zooming out far enough to show the whole configured extent, even when the container's aspect ratio differs from it. The default value is `false`.
* `constrainOnlyCenter` - applies the extent constraint only to the view center, so viewport edges may move outside the extent. The default value is `false`.
* `smoothExtentConstraint` - applies the extent constraint smoothly, allowing slight overscroll with an ease-back effect instead of a hard stop. The default value is `true`.

These attributes are creation-time options. They are passed to the OpenLayers view during initialization and cannot be changed at runtime.

[source,xml,indent=0]
----
include::maps:example$/maps-ex2/src/main/resources/com/company/mapssample/view/mapcomponent/map-component-view.xml[tags=extentConstraintOptions]
----

== Attributes

`geoMap` does not define component-specific attributes.

The following shared attributes are supported by `geoMap`:

xref:flow-ui:vc/common-attributes.adoc#id[id] -
xref:flow-ui:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:flow-ui:vc/common-attributes.adoc#classNames[classNames] -
xref:flow-ui:vc/common-attributes.adoc#colspan[colspan] -
xref:flow-ui:vc/common-attributes.adoc#css[css] -
xref:flow-ui:vc/common-attributes.adoc#height[height] -
xref:flow-ui:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:flow-ui:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:flow-ui:vc/common-attributes.adoc#minHeight[minHeight] -
xref:flow-ui:vc/common-attributes.adoc#minWidth[minWidth] -
xref:flow-ui:vc/common-attributes.adoc#visible[visible] -
xref:flow-ui:vc/common-attributes.adoc#width[width]

== Handlers

The following events are specific to `geoMap`:

include::flow-ui:vc/handler-generation-tip.adoc[]

[cols="2,5", options="header"]
|===
|Name
|Description

|[[MapClickEvent]]`MapClickEvent`
|Fired for a map click. A double-click causes this event to be fired twice.

|[[MapDoubleClickEvent]]`MapDoubleClickEvent`
|Fired when the user double-clicks the map.

|[[MapMoveEndEvent]]`MapMoveEndEvent`
|Fired after the map view finishes moving.

|[[MapSingleClickEvent]]`MapSingleClickEvent`
|Fired for a single click after the component determines that the interaction is not a double-click.

|[[MapZoomChangedEvent]]`MapZoomChangedEvent`
|Fired when the map zoom level changes.
|===

The following shared handlers are supported by `geoMap`:

xref:flow-ui:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:flow-ui:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Elements

A `geoMap` can include one `mapView` element and a required `layers` element. The `layers` element can contain `tile`, `image`, `vector`, and `heatmap` layers, each with the source and styling elements supported by its layer type.

== See Also

* xref:maps:layers-sources.adoc[]
* xref:maps:events.adoc[]
* xref:maps:reference.adoc[]
