= html

`html` отображает собственный HTML-код, представленный в виде строки, раздела CDATA или файла.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`html`

|Java-класс
|`Html`
|===

[[basics]]
== Основы

Этот элемент предназначен для встраивания HTML в структуру XML. Он позволяет встраивать отдельные HTML-элементы или блоки HTML-кода. Блок должен состоять из одного корневого элемента, такого как `<header>`, `<footer>`, `<main>` или `<div>`. Внутри этого корневого элемента может быть любое количество вложенных элементов `<div>` для эффективной структуризации содержимого.

CAUTION: Обратите внимание, что разработчик несёт ответственность за очистку и удаление любых опасных частей HTML перед отправкой его пользователю через этот компонент. Передача необработанных входных данных пользователю может привести к межсайтовым скриптовым атакам (XSS).

== Пакет сообщений

Этот пример демонстрирует, как добавить HTML-контент через строку в xref:localization:message-bundles.adoc[пакете сообщений]:

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/html/html-view.xml[tags=basics]
----

.messages.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/messages_en.properties[tags=html-content]
----

== Символьные данные

Тот же HTML-блок можно добавить в секцию символьных данных `CDATA`:

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/html/html-view.xml[tags=cdata]
----

[[file-content]]
== Содержимое файла

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/html-component" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Код HTML-блока также можно получить из файла одним из следующих способов.

[[static-resource]]
== Статический ресурс

Файл может обслуживаться приложением статически. Если ваш файл находится по адресу `/src/main/resources/META-INF/resources/html/html-file.html`, укажите его следующим образом:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/html/htmlcomponent/html-component.xml[tags=file-content]
----

NOTE: По умолчанию статическое содержимое обслуживается из каталогов `/static`, `/public`, `/resources` или `/META-INF/resources` в classpath. Подробности смотрите в https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[документации Spring Boot^].

[[stream-resource]]
== Потоковый ресурс

HTML-код может быть предоставлен в виде файла через `InputStream`, а затем компонент может быть инициализирован путем его передачи.

NOTE: Компонент нельзя создать с помощью бина `UiComponents`, так как он не предоставляет конструктор без аргументов.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/html/htmlcomponent/HtmlComponentSample.java[tags=stream-resource]
----

== Атрибуты

`html` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[content]]`content`
|Указывает содержимое HTML, которое будет отображаться компонентом, либо в виде строки в пакете сообщений, либо в разделе CDATA.
|—

|[[file]]`file`
|Указывает путь к файлу, из которого нужно получить HTML-код.
|—
|===

`html` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#visible[visible]

== Обработчики

`html` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]
