= icon

`icon` displays an image sourced from an icon set. There are two built-in icon sets: Vaadin and Lumo.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`icon`

|Java Class
|`Icon`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/icon-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use `icon` to add a standalone icon anywhere on the view.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/icon/simple/icon-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/icon/simple/IconSimpleSample.java[tags=basics]
----

[[icon-sets]]
== Icon Sets

There are two built-in icon sets containing frequently used icons: Vaadin and Lumo. To differentiate between sets, add its prefix before the icon name. If no prefix is present, the Vaadin set is used.

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/icon/icon-view.xml[tags=icon-sets]
----

[[embedding]]
== Components with Icons

Icon can be a part of a component. See an example of using an icon with the xref:vc/components/button.adoc[button] component.

== Attributes

The following attributes are specific to `icon`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[color]]`color`
|Sets the color for icon.
|—

|[[icon]]`icon`
|Specifies the icon to be displayed.
|—

|[[size]]`size`
|Specifies the size of the icon.
|—
|===

The following shared attributes are supported by `icon`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clickShortcut[clickShortcut] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#visible[visible]

== Handlers

The following handlers are specific to `icon`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[ClickEvent]]`ClickEvent`
|The `com.vaadin.flow.component.ClickEvent` is fired when the component is clicked.
|===

The following shared handlers are supported by `icon`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Elements

An `icon` can include xref:vc/components/tooltip.adoc[tooltip] as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/icons[Vaadin Icons documentation^]
