= icon

`icon` отображает изображение, полученное из набора значков. Есть два встроенных набора значков: Vaadin и Lumo.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`icon`

|Java-класс
|`Icon`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/icon-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте `icon`, чтобы добавить отдельный значок в любую область экрана.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/icon/simple/icon-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/icon/simple/IconSimpleSample.java[tags=basics]
----

[[icon-sets]]
== Наборы иконок

Существуют два встроенных набора, содержащих часто используемые иконки: Vaadin и Lumo. Чтобы различать наборы, добавьте его префикс перед именем иконки. Если префикс отсутствует, используется набор Vaadin.

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/icon/icon-view.xml[tags=icon-sets]
----

[[embedding]]
== Компоненты с иконками

Иконка может быть частью компонента. Смотрите пример использования иконки с компонентом xref:vc/components/button.adoc[button].

== Атрибуты

`icon` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[color]]`color`
|Устанавливает цвет значка.
|—

|[[icon]]`icon`
|Указывает значок, который будет отображаться.
|—

|[[size]]`size`
|Определяет размер значка.
|—
|===

`icon` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clickShortcut[clickShortcut] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#visible[visible]

== Обработчики

`icon` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClickEvent]]`ClickEvent`
|`com.vaadin.flow.component.ClickEvent` запускается при щелчке по компоненту.
|===

`icon` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Элементы

Компонент `icon` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/icons[Документация Vaadin: Icons^]
