= listBox
:page-aliases: vcl/components/single-select-list.adoc

`listBox` allows users to select a single value from a scrollable list of items.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`listBox`

|Java Class
|`JmixListBox`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/list-box-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

A `listBox` can be populated programmatically with `setItems()`. Components such as separators can be inserted between particular items.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/simple/list-box-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/simple/ListBoxSimpleSample.java[tags=basics]
----

[[items-container]]
== Items from a Data Container

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/list-box-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use `itemsContainer` to populate the component with entities from a collection data container.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/dataaware/list-box-dataaware.xml[tags=items-container]
----

[[enum-items]]
== Enumeration Items

Use `itemsEnum` to populate `listBox` with the values of an enumeration:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/listbox/list-box-view.xml[tags=itemsEnum]
----

[[disabled-items]]
== Disabled Items

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/list-box-custom-disabled" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`itemEnabledProvider` is applied to each item of this `listBox` to determine whether the item should be enabled (`true`) or disabled (`false`). Disabled items are displayed as grayed out and the user cannot select them. All the items are enabled by default.

Imagine `listBox` displaying a list of users. You want to display only users that have the "Completed" onboarding status as enabled, while users with "In progress" or "Not started" status should be disabled.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/customdisabled/ListBoxCustomDisabledSample.java[tags=disabled-items]
----

In this example, `itemEnabledProvider` checks the status of each user. Only users with `OnboardingStatus.COMPLETED` will be displayed as enabled in `listBox`.

[[renderer]]
== Rendering Items

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/list-box-custom-renderer" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The framework provides flexibility in customizing the rendering of items. You can use either the `setRenderer()` method or the `@Supply` annotation to achieve this.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/customrenderer/list-box-custom-renderer.xml[tags=custom-renderer]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/customrenderer/ListBoxCustomRendererSample.java[tags=custom-renderer]
----

[[fragment-renderer]]
Alternatively, you can render items using a nested `fragmentRenderer` element. Refer to the xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Fragment Renderer] section for more information.

== Attributes

The following attributes are specific to `listBox`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[itemsContainer]]`itemsContainer`
|Sets the items container.
|—

|[[itemsEnum]]`itemsEnum`
|Sets the items enum.
|—
|===

The following shared attributes are supported by `listBox`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `listBox`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[itemEnabledProvider]]`itemEnabledProvider`
|Determines whether each item is enabled. See <<disabled-items,Disabled Items>>.

|[[itemsLabelGenerator]]`itemsLabelGenerator`
|Provides the text shown for each item.

|`renderer`
|Provides the component used to render each item. See <<renderer,Rendering Items>>.
|===

The following shared handlers are supported by `listBox`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Elements

A `listBox` can include <<fragment-renderer,fragmentRenderer>> and xref:vc/components/tooltip.adoc[tooltip] as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/list-box[Vaadin List Box documentation^]
