= listBox
:page-aliases: vcl/components/single-select-list.adoc

`listBox` позволяет пользователям выбирать одно значение из прокручиваемого списка элементов.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`listBox`

|Java-класс
|`JmixListBox`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/list-box-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`listBox` можно заполнить программно с помощью `setItems()`. Между отдельными элементами можно вставлять компоненты, например разделители.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/simple/list-box-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/simple/ListBoxSimpleSample.java[tags=basics]
----

[[items-container]]
== Элементы из контейнера данных

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/list-box-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте `itemsContainer`, чтобы заполнить компонент сущностями из контейнера коллекции.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/dataaware/list-box-dataaware.xml[tags=items-container]
----

[[enum-items]]
== Элементы перечисления

Используйте `itemsEnum`, чтобы заполнить `listBox` значениями перечисления:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/listbox/list-box-view.xml[tags=itemsEnum]
----

[[disabled-items]]
== Элементы, недоступные для выбора

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/list-box-custom-disabled" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`itemEnabledProvider` применяется к каждому элементу этого `listBox`, чтобы определить, должен ли элемент быть активным (`true`) или неактивным (`false`). Неактивные элементы отображаются серым цветом, и пользователь не может их выбрать. По умолчанию все элементы активны.

Представьте, что `listBox` отображает список пользователей. Вы хотите, чтобы только пользователи со статусом "Завершен" в обучении были активны, а пользователи со статусами "В процессе" или "Не начато" - неактивными.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/customdisabled/ListBoxCustomDisabledSample.java[tags=disabled-items]
----

В этом примере `itemEnabledProvider` проверяет статус каждого пользователя. Только пользователи со статусом `OnboardingStatus.COMPLETED` будут отображаться как активные в `listBox`.

[[renderer]]
== Рендеринг элементов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/list-box-custom-renderer" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фреймворк предоставляет гибкость в настройке отображения элементов. Вы можете использовать либо метод `setRenderer()`, либо аннотацию `@Supply`, чтобы добиться этого.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/customrenderer/list-box-custom-renderer.xml[tags=custom-renderer]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/customrenderer/ListBoxCustomRendererSample.java[tags=custom-renderer]
----

[[fragment-renderer]]
В качестве альтернативы вы можете отображать элементы, используя вложенный элемент `fragmentRenderer`. Дополнительную информацию смотрите в разделе xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Рендерер фрагментов].

== Атрибуты

`listBox` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[itemsContainer]]`itemsContainer`
|Задаёт контейнер элементов.
|—

|[[itemsEnum]]`itemsEnum`
|Задаёт перечисление элементов.
|—
|===

`listBox` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`listBox` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[itemEnabledProvider]]`itemEnabledProvider`
|Определяет, включен ли каждый элемент. См. <<disabled-items,Отключенные элементы>>.

|[[itemsLabelGenerator]]`itemsLabelGenerator`
|Предоставляет текст, отображаемый для каждого элемента.

|`renderer`
|Предоставляет компонент для отображения каждого элемента. See <<renderer,Рендеринг предметов>>.
|===

`listBox` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Элементы

Компонент `listBox` может содержать следующие вложенные элементы: <<fragment-renderer,fragmentRenderer>> и xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/list-box[Документация Vaadin: List Box^]
