= multiSelectListBox
:page-aliases: vcl/components/multi-select-list.adoc

`multiSelectListBox` allows users to select multiple values from a scrollable list of items using checkboxes.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`multiSelectListBox`

|Java Class
|`JmixMultiSelectListBox`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/list-box-multi-select" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/components/entityComboBox.adoc#itemsContainer[itemsContainer] or xref:vc/components/comboBox.adoc#itemsEnum[itemsEnum] attribute to create a list of items:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/multiselect/list-box-multi-select.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/multiselect/ListBoxMultiSelectSample.java[tags=basics]
----

[[item-enabled-provider]]
== Item Enabled Provider

`itemEnabledProvider` allows you to dynamically control the enabled state of individual items based on specific conditions. Disabled items appear grayed out and cannot be selected by the user. All items are enabled by default.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/multiselectlistbox/MultiSelectListBoxView.java[tags=itemEnabledProvider]
----

[[customizing-item-labels]]
== Customizing Item Labels

`itemLabelGenerator` allows you to customize how items are displayed in the `multiSelectListBox` component. This gives you control over the text that users see, enabling you to present information in a more user-friendly or context-specific manner.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/multiselectlistbox/MultiSelectListBoxView.java[tags=itemLabelGenerator]
----

[[rendering-items]]
== Rendering Items

It is possible to customize the render of items. The renderer is applied to each item to create a component which represents the item.

You can use the `setRenderer()` method or the `@Supply` annotation for it.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/multiselectlistbox/MultiSelectListBoxView.java[tags=renderer]
----

[[fragment-renderer]]
Alternatively, you can render items using a nested `fragmentRenderer` element. Refer to the xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Fragment Renderer] section for more information.

== Attributes

The following attributes are specific to `multiSelectListBox`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[itemsContainer]]`itemsContainer`
|Sets the items container.
|—

|[[itemsEnum]]`itemsEnum`
|Sets the items enum.
|—
|===

The following shared attributes are supported by `multiSelectListBox`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `multiSelectListBox`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[itemEnabledProvider]]`itemEnabledProvider`
|`itemEnabledProvider` is applied to each item of this `multiSelectListBox` to determine whether the item should be enabled (`true`) or disabled (`false`). See <<item-enabled-provider,Item Enabled Provider>>.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Allows you to customize the labels displayed for each item in `multiSelectListBox`. See <<customizing-item-labels,Customizing Item Labels>>.

|[[renderer]]`renderer`
|Sets the item renderer for this `multiSelectListBox`. See <<rendering-items,Rendering Items>>.
|===

The following shared handlers are supported by `multiSelectListBox`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent]

== Elements

A `multiSelectListBox` can include xref:vc/components/select.adoc#fragment-renderer[fragmentRenderer] and xref:vc/components/tooltip.adoc[tooltip] as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/list-box#multi[Vaadin List Box documentation^]
