= multiSelectComboBoxPicker

`multiSelectComboBoxPicker` lets users choose multiple items from a drop-down list or by running picker actions.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`multiSelectComboBoxPicker`

|Java Class
|`JmixMultiSelectComboBoxPicker`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/multi-select-combo-box-picker" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The drop-down list opens when the user clicks the field using a pointing device. Using the `Up` and `Down` keys or typing a character when the field is focused also opens the drop-down list.

For `multiSelectComboBoxPicker`, you can define an arbitrary number of actions, displayed as buttons on the right. It can be done either in the XML descriptor using the `actions` nested element, or programmatically in the controller using `addAction()`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/picker/multi-select-combo-box-picker.xml[tags=picker]
----

[[data-binding]]
== Data-aware `multiSelectComboBoxPicker`

Data binding refers to linking a visual component to a xref:data/data-containers.adoc[data container]. Changes in the visual component or corresponding data container can trigger updates to one another. See xref:data/data-examples.adoc[] for more details.

Like `multiSelectComboBox`, `multiSelectComboBoxPicker` is designed for properties that store multiple values, for example `List` or `Set`. See xref:vc/components/multiSelectComboBox.adoc#data-binding[Data Binding] for common data structures and use cases.

To create `multiSelectComboBoxPicker` connected to data, use the xref:vc/common-attributes.adoc#dataContainer[dataContainer] and xref:vc/common-attributes.adoc#property[property] attributes. The xref:vc/components/entityComboBox.adoc#itemsContainer[itemsContainer] attribute is used to provide the list of available items. The following example produces a data-aware `multiSelectComboBoxPicker`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/multiselectcomboboxpicker/multi-select-combo-box-picker-view.xml[tags=data;userDc;hobbiesDc;facets;layout;data-bind]
----

<1> Data container to hold the `User` instance which is currently being edited.
<2> Fetch plan extended to retrieve a collection of `Hobby` instances that will be available for selection.
<3> `CollectionContainer` for the `Hobby` entity.
<4> Data load coordinator to automatically supply the component with instances to select from.
<5> `multiSelectComboBoxPicker` gets `hobbiesDc` as an items container to show a drop-down list of hobbies.
<6> Adding a predefined action to clear the selection.
<7> Adding a predefined action to open the lookup view.

The component value contains the selected items. When the component is bound to a collection property, Jmix converts the selected items to the property collection type, for example `List` or `Set`.

[[meta-class]]
== Using MetaClass

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/multi-select-combo-box-picker" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

You can use `multiSelectComboBoxPicker` without directly referencing data, meaning you don't need to specify `dataContainer` or `property` attributes. In this case, use the `metaClass` attribute to specify the entity type for `multiSelectComboBoxPicker`. To specify a collection of instances for selection use the `itemsContainer` attribute.

For example, the component can work with the `Hobby` entity, which has the metadata class name `Hobby`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/picker/multi-select-combo-box-picker.xml[tags=picker]
----

[[basic-features]]
== Basic Features

The following features, common to `comboBox` or `multiSelectComboBox` components, are supported:

* xref:vc/components/comboBox.adoc#custom-items[Custom Items]
* xref:vc/components/comboBox.adoc#custom-filtering[Custom Filtering]
* xref:vc/components/comboBox.adoc#custom-value-entry[Custom Value Entry]
* xref:vc/components/comboBox.adoc#rendering-items[Rendering Items]
* xref:vc/components/multiSelectComboBox.adoc#auto-expand[Auto Expand]
* xref:vc/components/multiSelectComboBox.adoc#selected-items-on-top[Selected Items on Top]
* xref:vc/components/multiSelectComboBox.adoc#items-fetch-callback[Items Fetch Callback]

[[validation]]
== Validation

To check values entered into the `multiSelectComboBoxPicker` component, you can use a xref:vc/miscellaneous/validator.adoc[validator] in a nested `validators` element.

The following predefined validators are available for `multiSelectComboBoxPicker`:

[cols="1h,6", grid=none]
|===
|XML Element
|`validators`
|Predefined validators
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`align-start`
|Aligns the field value to the start side, taking the current text direction into account.
|Aura

|`align-end`
|Aligns the field value to the end side, taking the current text direction into account.
|Aura

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo

|`small`
|Makes the component smaller.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `multiSelectComboBoxPicker`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[allowCustomValue]]`allowCustomValue`
|Controls whether users can enter values that are not in the available items.
|—

|[[autoExpand]]`autoExpand`
|Controls whether selected values expand automatically when the field receives focus.
|—

|[[autoOpen]]`autoOpen`
|Controls whether the item overlay opens when the field receives focus.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Controls whether the field displays a clear button.
|`false`

|[[itemsContainer]]`itemsContainer`
|Sets the items container.
|—

|[[itemsEnum]]`itemsEnum`
|Sets the items enum.
|—

|[[metaClass]]`metaClass`
|Sets the meta class.
|—

|[[opened]]`opened`
|Controls whether the item overlay is open.
|—

|[[overlayClass]]`overlayClass`
|Adds CSS class names to the component overlay.
|—

|[[pageSize]]`pageSize`
|Sets the page size.
|—

|[[selectedItemsOnTop]]`selectedItemsOnTop`
|Sets the selected items on top.
|—
|===

The following shared attributes are supported by `multiSelectComboBoxPicker`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `multiSelectComboBoxPicker`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Fired when the user enters a custom value in the field.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Provides the text shown for each item.

|[[itemsFetchCallback]]`itemsFetchCallback`
|Loads items in response to a filter query and paging request.

|[[renderer]]`renderer`
|Provides the component used to render each item.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `multiSelectComboBoxPicker`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent]

== Elements

A `multiSelectComboBoxPicker` can include xref:vc/components/entityPicker.adoc#actions[actions], xref:vc/components/select.adoc#fragment-renderer[fragmentRenderer], xref:vc/components/multiSelectComboBox.adoc#itemsQuery[itemsQuery], xref:vc/components/tooltip.adoc[tooltip], and <<validation,validators>> as its nested elements.
