= multiSelectComboBox
:page-aliases: vcl/components/tag-field.adoc, vcl/components/tag-picker.adoc

`multiSelectComboBox` позволяет пользователям выбирать один или несколько элементов из раскрывающегося списка. Этот компонент аналогичен xref:vc/components/comboBox.adoc[comboBox].

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`multiSelectComboBox`

|Java-класс
|`JmixMultiSelectComboBox`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Выпадающий список открывается при нажатии на поле указателем. Если поле находится в фокусе, список также открывается клавишами `Up` и `Down` или при вводе символа.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/simple/multi-select-combo-box-simple.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/multiselectcombobox/simple/MultiSelectComboBoxSimpleSample.java[tags=basics]
----

[[data-binding]]
== `multiSelectComboBox` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Привязка данных означает связывание визуального компонента с xref:data/data-containers.adoc[контейнером данных]. Изменения в визуальном компоненте или соответствующем контейнере данных могут вызывать обновления друг друга. Смотрите xref:flow-ui:data/data-examples.adoc[Использование компонентов данных] для получения дополнительной информации.

`multiSelectComboBox` предназначен для свойств, которые хранят несколько значений. Когда компонент привязан к атрибуту сущности, тип атрибута должен быть коллекцией, например `List` или `Set`.

Наиболее распространённый сценарий использования — выбор связанных сущностей для связи «многие ко многим»:

.Хобби.java
[source,java,indent=0]
----
@JmixEntity
@Table(name = "HOBBY")
@Entity
public class Hobby {
    /* attributes */
}
----

.User.java
[source,java,indent=0]
----
@JmixEntity
@Entity
@Table(name = "USER_")
public class User {

    /* other attributes */

    @JoinTable(name = "USER_HOBBY_LINK",
            joinColumns = @JoinColumn(name = "USER_ID"),
            inverseJoinColumns = @JoinColumn(name = "HOBBY_ID"))
    @ManyToMany
    private List<Hobby> userHobbies;
}
----

В этом случае `multiSelectComboBox` позволяет пользователю выбрать несколько экземпляров `Hobby`, а связь сохраняется в таблице связей.

Чтобы создать `multiSelectComboBox`, работающий с данными, используйте атрибуты xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property], чтобы привязать компонент к свойству-коллекции. Используйте атрибут xref:vc/components/entityComboBox.adoc#itemsContainer[itemsContainer], чтобы задать список доступных элементов. Следующий пример создаёт `multiSelectComboBox`, работающий с данными.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/dataaware/multi-select-combo-box-dataaware.xml[tags=data-binding]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/multiselectcombobox/dataaware/MultiSelectComboBoxDataawareSample.java[tags=data-binding]
----

[NOTE]
====
`itemsContainer` определяет доступные варианты в выпадающем списке. Выбранные значения хранятся в свойстве-коллекции, указанном атрибутами `dataContainer` и `property`.
====

Значение компонента содержит выбранные элементы. Когда компонент привязан к свойству-коллекции, Jmix преобразует выбранные элементы к типу коллекции свойства, например `List` или `Set`.

[[meta-class]]
== MultiSelectComboBox c MetaClass

Вы можете использовать `multiSelectComboBox` без прямой ссылки на данные, то есть без указания атрибутов `dataContainer` и `property`. В этом случае используйте атрибут `metaClass` для указания типа сущности для `multiSelectComboBox`. Чтобы указать набор экземпляров для выбора, используйте атрибут `itemsContainer`.

Например, компонент может работать с сущностью `Hobby`, которая имеет имя класса метаданных `Hobby`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/multiselectcombobox/multi-select-combo-box-view.xml[tags=metaClass]
----

== Общие функции comboBox

`multiSelectComboBox` поддерживает следующие функции из обычного `comboBox`:

* xref:vc/components/comboBox.adoc#custom-items[Пользовательские предметы]
* xref:vc/components/comboBox.adoc#custom-filtering[Пользовательская фильтрация]
* xref:vc/components/comboBox.adoc#custom-value-entry[Ввод пользовательского значения]

[[custom-item-labels]]
== Пользовательские этикетки для предметов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-item-label" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Установите `itemLabelGenerator`, чтобы настроить отображение значений во всплывающем списке и чипах выбранных элементов.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/itemlabel/multi-select-combo-box-item-label.xml[tags=data;item-label]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/multiselectcombobox/itemlabel/MultiSelectComboBoxItemLabelSample.java[tags=item-label]
----

[[custom-item-renderer]]
== Пользовательский рендерер предметов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-custom-renderer" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Передайте компонентный рендерер, чтобы отображать во всплывающем списке составные элементы. В примере каждое значение перечисления показано со значком Vaadin и именем.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/customrenderer/multi-select-combo-box-custom-renderer.xml[tags=custom-renderer]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/multiselectcombobox/customrenderer/MultiSelectComboBoxCustomRendererSample.java[tags=custom-renderer]
----

[[auto-expand]]
== Автоматическое расширение

Вы можете настроить `multiSelectComboBox` для автоматического увеличения ширины, чтобы вместить теги, представляющие выбранные элементы. Расширение работает только с неопределённым размером в нужном направлении (например, установка `max-width` ограничивает ширину компонента). Возможные значения:

* `VERTICAL` - поле расширяется вертикально, и теги переносятся на следующую строку.
+
* `HORIZONTAL` — поле расширяется по горизонтали до достижения максимальной ширины, затем сжимается до переполнения чипа.
+
* `BOTH` — поле расширяется по горизонтали до достижения максимальной ширины, затем расширяется по вертикали и происходит перенос фишек.
+
* `NONE` - поле не расширяется и сворачивается до переполнения чипа.
+

[[selected-items-on-top]]
== Отображение выбранных элементов

Атрибут `selectedItemsOnTop` управляет способом отображения выбранных элементов в выпадающем списке.

Как это работает:

* Если `selectedItemsOnTop` установлен в `true`, выбранные элементы отображаются в верхней части выпадающего списка, а не выбранные остаются внизу. Такое расположение может быть визуально привлекательным и интуитивно понятным, особенно если пользователи часто выбирают подмножество элементов и нуждаются в быстром доступе к последним выбранным.
* Если `selectedItemsOnTop` установлен в `false` (значение по умолчанию), выбранные элементы отображаются в том порядке, в котором они были выбраны, без перемещения в верхнюю часть выпадающего списка. Такое расположение сохраняет порядок выбора и может быть предпочтительным в сценариях, где порядок имеет решающее значение, или если важна визуальная согласованность с другими элементами интерфейса.

[[items-fetch-callback]]
== Получение элементов списка

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-items-query" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`multiSelectComboBox` может загружать элементы по частям в ответ на действия пользователя.

Например, когда пользователь вводит `foo`, компонент загружает из базы данных не более 50 элементов, содержащих `foo` в названии, и показывает их в выпадающем списке. Когда пользователь прокручивает список вниз, компонент извлекает следующую группу из 50 элементов с тем же запросом и добавляет их в список.

[[itemsQuery]]
== Декларативная конфигурация

Для реализации этого поведения определите вложенный элемент `itemsQuery`.

Элемент `itemsQuery` должен содержать текст запроса JPQL во вложенном элементе `query` и несколько дополнительных атрибутов, определяющих, что и как загружать данные:

* `escapeValueForLike` - включает поиск значений, содержащих специальные символы: `%,` `\`, и так далее. Значение по умолчанию - `false`.
* `searchStringFormat` - строка Groovy. C её помощью вы можете использовать любые допустимые строковые выражения Groovy.
* `class` (необязательный) - указывает полное имя класса сущности, экземпляры которой будут получены.
* `fetchPlan` - необязательный атрибут, указывающий фетч-план для загрузки запрошенной сущности.

Элемент `itemsQuery` содержит следующие вложенные элементы:

* `query` - элемент, содержащий запрос JPQL.
* `fetchPlan` - необязательный элемент, задающий встроенный фетч-план.

Пример использования `itemsQuery` в `multiSelectComboBox`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/itemsquery/multi-select-combo-box-items-query.xml[tags=items-query]
----

include::flow-ui:vc/items-fetch-callback-note.adoc[]

[[itemsFetchCallback-handler]]
== Программная конфигурация

Извлечение элементов также может быть определено программно с помощью обработчика `itemsFetchCallback`. Например:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/multiselectcombobox/itemsquery/MultiSelectComboBoxItemsQuery.java[tags=items-fetch-callback]
----

В этом примере данные извлекаются с помощью xref:data-access:data-manager.adoc[DataManager], но вы можете использовать этот подход для загрузки из собственного сервиса.

[[validation]]
== Валидация

Чтобы проверить значения, введённые в компонент `multiSelectComboBox`, вы можете использовать xref:vc/miscellaneous/validator.adoc[валидатор] в элементе `validators`.

Доступны следующие предопределённые валидаторы для `multiSelectComboBox`:

[cols="1h,6", grid=none]
|===
|XML-элемент
|`validators`
|Предопределённые валидаторы
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`small`
|Уменьшает размер компонента.
|Aura, Lumo

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo
|===

== Атрибуты

`multiSelectComboBox` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|Определяет, могут ли пользователи вводить значения, отсутствующие среди доступных элементов.
|—

|[[autoExpand]]`autoExpand`
|Управляет поведением компонента, когда недостаточно места для отображения всех выбранных элементов в виде фишек в пределах текущей ширины поля. См. <<auto-expand,Автоматическое расширение>>.
|`NONE`

|[[autoOpen]]`autoOpen`
|Определяет, открывается ли всплывающий список элементов при получении полем фокуса.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Определяет, отображается ли в поле кнопка очистки.
|`false`

|[[itemsContainer]]`itemsContainer`
|Задаёт контейнер элементов.
|—

|[[itemsEnum]]`itemsEnum`
|Задаёт перечисление элементов.
|—

|[[metaClass]]`metaClass`
|Определяет класс сущности для `multiSelectComboBox`. Установите этот атрибут, если компонент не связан с контейнером данных. В противном случае тип сущности определяется контейнером данных. См. <<meta-class,MultiSelectComboBox с метаклассом>>.
|—

|[[opened]]`opened`
|Определяет, открыт ли выпадающий список.
|`false`

|[[overlayClass]]`overlayClass`
|Добавляет имена CSS-классов во всплывающий элемент компонента.
|—

|[[pageSize]]`pageSize`
|Задаёт размер страницы.
|—

|[[selectedItemsOnTop]]`selectedItemsOnTop`
|Включает или отключает группировку выбранных элементов вверху наложения. См. <<selected-items-on-top,Выбранные элементы сверху>>.
|`false`
|===

`multiSelectComboBox` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`multiSelectComboBox` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Возникает, когда пользователь вводит в поле пользовательское значение.

|[[itemLabelGenerator]]`itemLabelGenerator`
|`com.vaadin.flow.component.ItemLabelGenerator` можно использовать для настройки строки, отображаемой пользователю для элемента. См. xref:vc/components/comboBox.adoc#itemLabelGenerator[itemLabelGenerator] для `comboBox` и https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-item-label[интерактивный пример^].

|[[itemsFetchCallback]]`itemsFetchCallback`
|Этот обработчик извлекает данные только тогда, когда это необходимо. См. <<itemsFetchCallback-handler,Обратный вызов получения предметов>>.

|[[renderer]]`renderer`
|Устанавливает `Renderer` ответственным за отображение отдельных элементов в списке возможных вариантов `multiSelectComboBox`. Это не влияет на то, как отображается выбранный элемент — это можно настроить с помощью <<itemLabelGenerator,ItemLabelGenerator>>. См. https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-custom-renderer[интерактивный пример^].

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`multiSelectComboBox` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent]

== Элементы

Компонент `multiSelectComboBox` может содержать следующие вложенные элементы: xref:vc/components/select.adoc#fragment-renderer[fragmentRenderer], <<itemsQuery,itemsQuery>>, xref:vc/components/tooltip.adoc[tooltip], и <<validation,validator>>.

== Смотрите также

* https://vaadin.com/docs/v25/components/multi-select-combo-box[Документация Vaadin: Multi-Select Combo Box^]
