= multiValuePicker
:page-aliases: vcl/components/values-picker.adoc

`multiValuePicker` works with a list of values of any type. It consists of a text field and a set of buttons defined by actions.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`multiValuePicker`

|Java Class
|`JmixMultiValuePicker`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/value-picker-multi" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`multiValuePicker` is ideal for editing lists of values through actions, rather than typing directly in a text field.

Basic `multiValuePicker` example:

[[values-picker-example1]]
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/multi/value-picker-multi.xml[tags=basics]
----

When users click the value selection button, the *Select Value* view appears. Here, they can add new values to a result list or remove existing ones. To add a value, they can either click the *Add* button or press *Enter*.

NOTE: You can create a custom *Select Value* view. This view needs to implement the `MultiValueSelectView` interface and then be set to the `action` as either `viewClass` or `viewId`.

[[actions]]
== Actions

You can add custom or predefined actions to your `multiValuePicker`, displayed as buttons on the right side. You can do this in two ways:

* **XML Descriptor:** Define your actions within the nested `<actions>` element in your XML descriptor.
* **Controller:** Programmatically add actions to `multiValuePicker` using the `addAction()` method in your controller.

[TIP]
====
To add `action` in Jmix Studio, select the component in the view descriptor XML or in the *Jmix UI* structure panel and click on the xref:studio:view-designer.adoc#add-picker-action[Add] button in the *Jmix UI* inspector panel.
====

[[predefined-action]]
== Predefined Action

The framework provides two predefined actions for `multiValuePicker`: `value_clear` and `multi_value_select`.

The `multi_value_select` action populates `multiValuePicker` using a value selection view. This view dynamically generates a component for selecting or creating a value based on the data type provided. The `multi_value_select` action can handle various data types, including:

* Java types, such as `String`, `Integer`, `Long`, `Double`, `BigDecimal`, date and time types, and `UUID`
* xref:data-model:enumerations.adoc[enum] values
* xref:data-model:entities.adoc[entity] instances

[[java-class]]
Use the `javaClass` property to specify a Java data type. For instance, the <<values-picker-example1,previous>> example uses `java.lang.String`.

[[enum-class]]
== Enumeration Values

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/value-picker-multi-enum" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the `enumClass` property to specify the enumeration class that represents the data type of the selected value.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/multienum/value-picker-multi-enum.xml[tags=enum]
----

When dealing with enums, a `comboBox` is generated on the *Select Value* view, providing a dropdown list of available enum values.

[[entity-name]]
== Entity Values

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/value-picker-multi-entity" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the `entityName` property to set the name of the entity class that represents the data type of the selected value.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/multientity/value-picker-multi-entity.xml[tags=entity]
----

[[use-combo-box]]
The `useComboBox` property controls whether an `entityComboBox` should be used in the *Select Value* view. The default value is `false`.

[[custom-actions]]
== Custom Actions

Custom actions for `multiValuePicker` are similar to xref:flow-ui:vc/components/valuePicker.adoc#custom-actions[custom actions] used with `valuePicker`.

[[validation]]
== Validation

To check values entered into the `multiValuePicker` component, you can use a xref:vc/miscellaneous/validator.adoc[validator] in a nested `validators` element.

The following predefined validators are available for `multiValuePicker`:

[cols="1h,6", grid=none]
|===
|XML Element
|`validators`
|Predefined validators
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#DecimalMaxValidator[decimalMax] - xref:vc/miscellaneous/validator.adoc#DecimalMinValidator[decimalMin] - xref:vc/miscellaneous/validator.adoc#DigitsValidator[digits] - xref:vc/miscellaneous/validator.adoc#DoubleMaxValidator[doubleMax] - xref:vc/miscellaneous/validator.adoc#DoubleMinValidator[doubleMin] - xref:vc/miscellaneous/validator.adoc#EmailValidator[email] - xref:vc/miscellaneous/validator.adoc#MaxValidator[max] - xref:vc/miscellaneous/validator.adoc#MinValidator[min] - xref:vc/miscellaneous/validator.adoc#NegativeValidator[negative] - xref:vc/miscellaneous/validator.adoc#NegativeOrZeroValidator[negativeOrZero] - xref:vc/miscellaneous/validator.adoc#NotBlankValidator[notBlank] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#PositiveValidator[positive] - xref:vc/miscellaneous/validator.adoc#PositiveOrZeroValidator[positiveOrZero] - xref:vc/miscellaneous/validator.adoc#RegexpValidator[regexp] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`align-start`
|Aligns the field value to the start side, taking the current text direction into account.
|Aura

|`align-end`
|Aligns the field value to the end side, taking the current text direction into account.
|Aura

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo

|`small`
|Makes the component smaller.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `multiValuePicker`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[allowCustomValue]]`allowCustomValue`
|Controls whether users can enter values that are not in the available items.
|—
|===

The following shared attributes are supported by `multiValuePicker`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `multiValuePicker`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Fired when the user enters a custom value in the field.

|[[formatter]]`formatter`
|Converts the component value to the text shown in the field.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `multiValuePicker`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `multiValuePicker` can include <<actions,actions>>, xref:vc/miscellaneous/formatter.adoc[formatter], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/miscellaneous/prefix-suffix.adoc[suffix], xref:vc/components/tooltip.adoc[tooltip], and <<validation,validator>> as its nested elements.
