= multiSelectComboBoxPicker

`multiSelectComboBoxPicker` позволяет пользователям выбирать несколько элементов из раскрывающегося списка или с помощью действий выбора.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`multiSelectComboBoxPicker`

|Java-класс
|`JmixMultiSelectComboBoxPicker`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-picker" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Выпадающий список открывается при нажатии на поле указателем. Если поле находится в фокусе, список также открывается клавишами `Up` и `Down` или при вводе символа.

Для `multiSelectComboBoxPicker` можно определить произвольное количество действий, отображаемых в виде кнопок справа. Это можно сделать либо в XML-дескрипторе, используя вложенный элемент `actions`, либо программно в контроллере, используя метод `addAction()`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/picker/multi-select-combo-box-picker.xml[tags=picker]
----

[[data-binding]]
== `multiSelectComboBoxPicker` связанный с данными

Привязка данных - это процесс связывания визуального компонента с xref:data/data-containers.adoc[контейнером данных]. Изменения в визуальном компоненте или в соответствующем контейнере данных могут вызывать обновления друг в друге. Подробности смотрите в разделе xref:data/data-examples.adoc[].

Как и `multiSelectComboBox`, компонент `multiSelectComboBoxPicker` предназначен для свойств, хранящих несколько значений, например `List` или `Set`. Обычные структуры данных и сценарии использования смотрите в разделе xref:vc/components/multiSelectComboBox.adoc#data-binding[Привязка данных].

Чтобы создать `multiSelectComboBoxPicker`, подключенный к данным, используйте атрибуты xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property]. Атрибут xref:vc/components/entityComboBox.adoc#itemsContainer[itemsContainer] используется для предоставления списка доступных элементов. Следующий пример создаёт компонент `multiSelectComboBoxPicker`, работающий с данными.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/multiselectcomboboxpicker/multi-select-combo-box-picker-view.xml[tags=data;userDc;hobbiesDc;facets;layout;data-bind]
----

<1> Контейнер данных для хранения экземпляра `User`, который в данный момент редактируется.
<2> Фетч-план расширен для извлечения коллекции экземпляров `Hobby`, которые будут доступны для выбора.
<3> `CollectionContainer` для сущности `Hobby`.
<4> Координатор загрузки данных для автоматического предоставления компоненту экземпляров для выбора.
<5> `multiSelectComboBoxPicker` получает `hobbiesDc` в качестве контейнера элементов, чтобы отобразить список хобби в выпадающем списке.
<6> Добавление предопределённого действия для очистки выбора.
<7> Добавление предопределённого действия для открытия экрана поиска.

Значение компонента содержит выбранные элементы. Когда компонент привязан к свойству-коллекции, Jmix преобразует выбранные элементы к типу коллекции свойства, например, `List` или `Set`.

[[meta-class]]
== Использование MetaClass

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/multi-select-combo-box-picker" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Вы можете использовать `multiSelectComboBoxPicker` без прямой ссылки на данные, то есть вам не нужно указывать атрибуты `dataContainer` или `property`. В этом случае используйте атрибут `metaClass`, чтобы указать тип сущности для `multiSelectComboBoxPicker`. Чтобы указать коллекцию экземпляров для выбора, используйте атрибут `itemsContainer`.

Например, компонент может работать с сущностью `Hobby`, которая имеет имя класса метаданных `Hobby`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/multiselectcombobox/picker/multi-select-combo-box-picker.xml[tags=picker]
----

[[basic-features]]
== Основные возможности

Поддерживаются следующие возможности, общие для компонентов `comboBox` или `multiSelectComboBox`:

* xref:vc/components/comboBox.adoc#custom-items[Пользовательские элементы]
* xref:vc/components/comboBox.adoc#custom-filtering[Пользовательская фильтрация]
* xref:vc/components/comboBox.adoc#custom-value-entry[Обработка пользовательского ввода]
* xref:vc/components/comboBox.adoc#rendering-items[Рендеринг элементов]
* xref:vc/components/multiSelectComboBox.adoc#auto-expand[Автоматическое расширение]
* xref:vc/components/multiSelectComboBox.adoc#selected-items-on-top[Отображение выбранных элементов]
* xref:vc/components/multiSelectComboBox.adoc#items-fetch-callback[Получение элементов списка]

[[validation]]
== Валидация

Чтобы проверить значения, введённые в компонент `multiSelectComboBoxPicker`, вы можете использовать xref:vc/miscellaneous/validator.adoc[валидатор] во вложенном элементе `validators`.

Для `multiSelectComboBoxPicker` доступны следующие предопределённые валидаторы:

[cols="1h,6", grid=none]
|===
|XML-элемент
|`validators`
|Предопределённые валидаторы
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`multiSelectComboBoxPicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|Определяет, могут ли пользователи вводить значения, отсутствующие среди доступных элементов.
|—

|[[autoExpand]]`autoExpand`
|Определяет, будут ли выбранные значения автоматически расширяться, когда поле получает фокус.
|—

|[[autoOpen]]`autoOpen`
|Определяет, открывается ли всплывающий список элементов при получении полем фокуса.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Определяет, отображается ли в поле кнопка очистки.
|`false`

|[[itemsContainer]]`itemsContainer`
|Задаёт контейнер элементов.
|—

|[[itemsEnum]]`itemsEnum`
|Задаёт перечисление элементов.
|—

|[[metaClass]]`metaClass`
|Задаёт метакласс.
|—

|[[opened]]`opened`
|Определяет, открыто ли наложение элемента.
|—

|[[pageSize]]`pageSize`
|Задаёт размер страницы.
|—

|[[selectedItemsOnTop]]`selectedItemsOnTop`
|Устанавливает выбранные элементы сверху.
|—
|===

`multiSelectComboBoxPicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`multiSelectComboBoxPicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Возникает, когда пользователь вводит в поле пользовательское значение.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Предоставляет текст, отображаемый для каждого элемента.

|[[itemsFetchCallback]]`itemsFetchCallback`
|Загружает элементы по запросу фильтрации и параметрам постраничного вывода.

|[[renderer]]`renderer`
|Предоставляет компонент для отображения каждого элемента.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`multiSelectComboBoxPicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent]

== Элементы

Компонент `multiSelectComboBoxPicker` может содержать следующие вложенные элементы: xref:vc/components/entityPicker.adoc#actions[actions], xref:vc/components/select.adoc#fragment-renderer[fragmentRenderer], xref:vc/components/multiSelectComboBox.adoc#itemsQuery[itemsQuery], xref:vc/components/tooltip.adoc[tooltip], и <<validation,validators>>.
