= multiValuePicker
:page-aliases: vcl/components/values-picker.adoc

`multiValuePicker` работает со списком значений любого типа. Он состоит из текстового поля и набора кнопок, определяемых действиями.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`multiValuePicker`

|Java-класс
|`JmixMultiValuePicker`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-multi" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`multiValuePicker` идеально подходит для редактирования списков значений с помощью действий, а не ввода непосредственно в текстовое поле.

Пример базового `multiValuePicker`:

[[values-picker-example1]]
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/multi/value-picker-multi.xml[tags=basics]
----

Когда пользователь нажимает кнопку выбора значения, открывается экран *Выбор значения*. На нём можно добавлять новые значения в результирующий список и удалять существующие. Чтобы добавить значение, нажмите кнопку *Добавить* или клавишу *Enter*.

NOTE: Можно создать собственный экран *Выбор значения*. Он должен реализовывать интерфейс `MultiValueSelectView` и указываться для `action` в свойстве `viewClass` или `viewId`.

[[actions]]
== Действия

Вы можете добавлять пользовательские или предопределённые действия в ваш `multiValuePicker`, которые будут отображаться в виде кнопок справа. Сделать это можно двумя способами:

* **XML-дескриптор:** Определите ваши действия вложенным элементом `<actions>` в XML-дескрипторе.
* **Контроллер:** Программно добавьте действия в `multiValuePicker` с помощью метода `addAction()` в контроллере.

[TIP]
====
Чтобы добавить действие в Jmix Studio, выберите компонент в XML-дескрипторе экрана или в панели структуры *Jmix UI*, и нажмите кнопку xref:studio:view-designer.adoc#add-picker-action[Add] на панели инспектора *Jmix UI*.
====

[[predefined-action]]
== Предопределенные действия

Фреймворк предоставляет два предопределённых действия для `multiValuePicker`: `value_clear` и `multi_value_select`.

Действие `multi_value_select` заполняет `multiValuePicker` с помощью экрана выбора значения. Этот экран динамически генерирует компонент для выбора или создания значения, основанный на предоставленном типе данных. Действие `multi_value_select` может обрабатывать различные типы данных, включая:

* Типы Java, такие как `String`, `Integer`, `Long`, `Double`, `BigDecimal`, типы даты и времени и `UUID`.
* значения xref:data-model:enumerations.adoc[перечислений];
* экземпляры xref:data-model:entities.adoc[сущностей].

[[java-class]]
Укажите тип данных Java в свойстве `javaClass`. Например, в <<values-picker-example1,предыдущем>> примере используется `java.lang.String`.

[[enum-class]]
== Значения перечисления

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-multi-enum" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Укажите в свойстве `enumClass` класс перечисления, который определяет тип выбранного значения.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/multienum/value-picker-multi-enum.xml[tags=enum]
----

Для перечислений на экране *Выбор значения* создаётся `comboBox` с выпадающим списком доступных значений.

[[entity-name]]
== Значения сущности

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-multi-entity" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Укажите в свойстве `entityName` имя класса сущности, который определяет тип выбранного значения.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/multientity/value-picker-multi-entity.xml[tags=entity]
----

[[use-combo-box]]
Свойство `useComboBox` определяет, следует ли использовать `entityComboBox` на экране *Выбор значения*. Значение по умолчанию — `false`.

[[custom-actions]]
== Пользовательские действия

Пользовательские действия для `multiValuePicker` аналогичны xref:flow-ui:vc/components/valuePicker.adoc#custom-actions[пользовательским действиям], используемым с `valuePicker`.

[[validation]]
== Валидация

Чтобы проверить значения, введённые в компонент `multiValuePicker`, вы можете использовать xref:vc/miscellaneous/validator.adoc[валидатор] в элементе `validators`.

Доступны следующие предопределённые валидаторы для `multiValuePicker`:

[cols="1h,6", grid=none]
|===
|XML-элемент
|`validators`
|Предопределённые валидаторы
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#DecimalMaxValidator[decimalMax] - xref:vc/miscellaneous/validator.adoc#DecimalMinValidator[decimalMin] - xref:vc/miscellaneous/validator.adoc#DigitsValidator[digits] - xref:vc/miscellaneous/validator.adoc#DoubleMaxValidator[doubleMax] - xref:vc/miscellaneous/validator.adoc#DoubleMinValidator[doubleMin] - xref:vc/miscellaneous/validator.adoc#EmailValidator[email] - xref:vc/miscellaneous/validator.adoc#MaxValidator[max] - xref:vc/miscellaneous/validator.adoc#MinValidator[min] - xref:vc/miscellaneous/validator.adoc#NegativeValidator[negative] - xref:vc/miscellaneous/validator.adoc#NegativeOrZeroValidator[negativeOrZero] - xref:vc/miscellaneous/validator.adoc#NotBlankValidator[notBlank] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#PositiveValidator[positive] - xref:vc/miscellaneous/validator.adoc#PositiveOrZeroValidator[positiveOrZero] - xref:vc/miscellaneous/validator.adoc#RegexpValidator[regexp] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`multiValuePicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|Определяет, могут ли пользователи вводить значения, отсутствующие среди доступных элементов.
|—
|===

`multiValuePicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`multiValuePicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|Возникает, когда пользователь вводит в поле пользовательское значение.

|[[formatter]]`formatter`
|Преобразует значение компонента в текст, отображаемый в поле.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`multiValuePicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `multiValuePicker` может содержать следующие вложенные элементы: <<actions,actions>>, xref:vc/miscellaneous/formatter.adoc[formatter], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/miscellaneous/prefix-suffix.adoc[suffix], xref:vc/components/tooltip.adoc[tooltip], и <<validation,validator>>.
