= multiSelectListBox
:page-aliases: vcl/components/multi-select-list.adoc

`multiSelectListBox` позволяет пользователям выбирать несколько значений из прокручиваемого списка элементов с помощью флажков.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`multiSelectListBox`

|Java-класс
|`JmixMultiSelectListBox`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/list-box-multi-select" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Чтобы создать список элементов, используйте атрибут xref:vc/components/entityComboBox.adoc#itemsContainer[itemsContainer] или xref:vc/components/comboBox.adoc#itemsEnum[itemsEnum]:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/listbox/multiselect/list-box-multi-select.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/listbox/multiselect/ListBoxMultiSelectSample.java[tags=basics]
----

[[item-enabled-provider]]
== Поставщик itemEnabledProvider

`itemEnabledProvider` позволяет вам динамически управлять активным состоянием отдельных элементов на основе определённых условий. Неактивные элементы отображаются серыми и не могут быть выбраны пользователем. По умолчанию все элементы активны.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/multiselectlistbox/MultiSelectListBoxView.java[tags=itemEnabledProvider]
----

[[customizing-item-labels]]
== Настройка надписей элементов

`itemLabelGenerator` позволяет вам настраивать способ отображения элементов в компоненте `multiSelectListBox`. Это дает вам контроль над текстом, который видят пользователи, позволяя представлять информацию в более удобном или контекстно-зависимом виде.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/multiselectlistbox/MultiSelectListBoxView.java[tags=itemLabelGenerator]
----

[[rendering-items]]
== Рендеринг элементов

Можно настроить рендеринг элементов. Рендерер применяется к каждому элементу для создания компонента, который представляет этот элемент.

Для этого можно использовать метод `setRenderer()` или аннотацию `@Supply`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/multiselectlistbox/MultiSelectListBoxView.java[tags=renderer]
----

[[fragment-renderer]]
В качестве альтернативы вы можете отображать элементы, используя вложенный элемент `fragmentRenderer`. Дополнительную информацию смотрите в разделе xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Рендерер фрагментов].

== Атрибуты

`multiSelectListBox` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[itemsContainer]]`itemsContainer`
|Задаёт контейнер элементов.
|—

|[[itemsEnum]]`itemsEnum`
|Задаёт перечисление элементов.
|—
|===

`multiSelectListBox` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`multiSelectListBox` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[itemEnabledProvider]]`itemEnabledProvider`
|`itemEnabledProvider` применяется к каждому элементу этого `multiSelectListBox`, чтобы определить, должен ли этот элемент быть включен (`true`) или отключен (`false`). См. <<item-enabled-provider,Поставщик, поддерживающий элемент>>.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Позволяет настраивать метки, отображаемые для каждого элемента в `multiSelectListBox`. См. <<customizing-item-labels,Настройка меток предметов>>.

|[[renderer]]`renderer`
|Устанавливает средство рендеринга элементов для этого `multiSelectListBox`. См. <<rendering-items,Рендеринг предметов>>.
|===

`multiSelectListBox` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent]

== Элементы

Компонент `multiSelectListBox` может содержать следующие вложенные элементы: xref:vc/components/select.adoc#fragment-renderer[fragmentRenderer] и xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/list-box#multi[Документация Vaadin: List Box^]
