= progressBar
:page-aliases: vcl/components/progress-bar.adoc

`progressBar` показывает статус завершения длительной задачи.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`progressBar`

|Java-класс
|`ProgressBar`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/progress-bar-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Стандартный индикатор выполнения принимает значения от 0,0 до 1,0, что соответствует прогрессу задачи от 0 % до 100 %.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=basics]
----

[[progress-updates]]
== Обновление прогресса

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/progress-bar-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Значение прогресса обычно обновляется во время выполнения задачи, чтобы индикатор точно отражал её текущее состояние.

Рассмотрим пример простой xref:background-tasks.adoc[фоновой задачи], которая обновляет значение `progressBar`:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=progress-updates]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/progressbar/simple/ProgressBarSimpleSample.java[tags=progress-updates]
----

== Режимы работы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/progress-bar-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В зависимости от типа задачи и доступности сведений о ходе выполнения индикатор может быть определённым или неопределённым.

[[determinate-mode]]
== Детерминированный режим

По умолчанию `progressBar` отображает прогресс в детерминированном режиме. Этот режим предоставляет пользователям визуальное представление оставшегося времени до завершения задачи.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=basics]
----

Используйте детерминированный индикатор прогресса, когда время выполнения задачи известно заранее или можно отслеживать прогресс.

[[indeterminate-mode]]
== Недетерминированный режим

Установив атрибут <<indeterminate,indeterminate>> в значение `true`, вы можете перевести индикатор прогресса в недетерминированный режим. В этом режиме `progressBar` циклически анимируется по всей длине полосы, не отображая конкретного значения прогресса.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=indeterminate]
----

Используйте этот режим для задач, которые не предоставляют значение прогресса или для обозначения непрерывно выполняющегося процесса.

== Диапазон значений

По умолчанию индикатор прогресса принимает значения от 0.0 до 1.0, что соответствует 0% и 100% соответственно. Это стандартное поведение, которое можно изменить с помощью атрибутов <<min,min>> и <<max,max>>.

Например, если ваша задача состоит из 10 шагов, вы можете установить `min="1"` и `max="10"`, чтобы соответствовать диапазону прогресса задачи. Достижение 5-го шага будет означать, что значение прогресса также достигло 5:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/progressbar/progress-bar-view.xml[tags=value-range]
----

== Диалог прогресса

Если требуется, чтобы пользователь дождался завершения задачи, можно использовать xref:dialogs.adoc#background-task-dialog[диалог фоновой задачи].

Это диалоговое окно блокирует работу с остальной частью приложения, пока задача не завершится или пользователь не отменит её.

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/progress-bar-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`success`
|Указывает на удовлетворительный прогресс или близкое завершение.
|Aura, Lumo

|`error`
|Указывает на неудовлетворительный прогресс или привлекает внимание к остановившемуся либо неудачному процессу.
|Aura, Lumo

|`contrast`
|Улучшает заметность компонента.
|Aura, Lumo
|===

== Атрибуты

`progressBar` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[indeterminate]]`indeterminate`
|Включает или отключает режим <<indeterminate-mode,неопределённый прогресс>>.
|—

|[[max]]`max`
|Устанавливает максимальное значение прогресса.
|—

|[[min]]`min`
|Устанавливает минимальное значение прогресса.
|—

|[[value]]`value`
|Задаёт значение компонента.
|—
|===

`progressBar` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`progressBar` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Смотрите также

* https://vaadin.com/docs/v25/components/progress-bar[Документация Vaadin: Progress Bar^]
