= progressBar
:page-aliases: vcl/components/progress-bar.adoc

`progressBar` shows the completion status of a long-running task.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`progressBar`

|Java Class
|`ProgressBar`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/progress-bar-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

A standard progress bar takes values between 0.0 and 1.0, representing the progress of a task from 0% to 100%.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=basics]
----

[[progress-updates]]
== Progress Updates

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/progress-bar-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The progress value is commonly updated within the context of an ongoing task. This allows the progress bar to accurately reflect the current state of the task.

Consider an example of a simple xref:background-tasks.adoc[background task] that updates the `progressBar` value:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=progress-updates]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/progressbar/simple/ProgressBarSimpleSample.java[tags=progress-updates]
----

== Modes

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/progress-bar-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

A progress bar can either be determinate or indeterminate depending on the nature of the task and the availability of progress information.

[[determinate-mode]]
== Determinate Progress

By default, `progressBar` shows progress in the determinate mode. This mode provide users with a visual representation of remaining time to complete the task.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=basics]
----

Use a determinate progress bar when the time required for completion is known in advance or the progress can be tracked.

[[indeterminate-mode]]
== Indeterminate Progress

By setting the <<indeterminate,indeterminate>> attribute to `true` you can switch the progress bar to operate in the indeterminate mode. When in indeterminate mode `progressBar` cycles repeatedly along the length of the bar without showing a specific progress value.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/progressbar/simple/progress-bar-simple.xml[tags=indeterminate]
----

Use this mode for tasks which do not share a progress value or to communicate that the task is running continuously.

== Value Range

By default, a progress bar takes values from 0.0 to 1.0, representing 0% and 100% respectively. This is the standard behavior that can be changed using the <<min,min>> and <<max,max>> attributes.

For instance, if you have a task with 10 steps, you can set `min="1"` and `max="10"` to match the task's progress range. Reaching the 5th step indicates that the progress value has reached 5 as well:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/progressbar/progress-bar-view.xml[tags=value-range]
----

== Progress Dialog

If it is necessary for the user to wait for the completion of a task, a xref:dialogs.adoc#background-task-dialog[background task dialog] can be used.

This dialog blocks user interaction with the rest of the application until the task is either completed or is canceled by the user.

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/progress-bar-theme-variant" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`success`
|Indicates satisfactory progress or nearing completion.
|Aura, Lumo

|`error`
|Indicates unsatisfactory progress or draws attention to a stalled or failed process.
|Aura, Lumo

|`contrast`
|Improves visibility.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `progressBar`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[indeterminate]]`indeterminate`
|Enables or disables the <<indeterminate-mode,indeterminate progress>> mode.
|—

|[[max]]`max`
|Sets the maximum progress value.
|—

|[[min]]`min`
|Sets the minimum progress value.
|—

|[[value]]`value`
|Sets the component value.
|—
|===

The following shared attributes are supported by `progressBar`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following shared handlers are supported by `progressBar`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== See Also

* https://vaadin.com/docs/v25/components/progress-bar[Vaadin Progress Bar documentation^]
