= propertyFilter
:page-aliases: vcl/components/property-filter.adoc

`propertyFilter` filters data by an attribute of an xref:data-model:entities.adoc[entity].

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`propertyFilter`

|Java Class
|`PropertyFilter`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/property-filter-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

At its simplest, `propertyFilter` consists of an input field preceded by the name of the property being filtered and the operation being used.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/simple/property-filter-simple.xml[tags=basics]
----

This component filters data loaded to a data container. It is commonly used in conjunction with xref:vc/components/dataGrid.adoc[] or xref:vc/components/treeDataGrid.adoc[] components, which are bound to the same container. This combination allows for precise control over the rows displayed.

[[filtering-operations]]
== Filtering Operations

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/property-filter-editable-operation" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The component supports numerous filtering <<operation, operations>>. You can limit it to a specific operation or allow users to choose the operation they want at runtime using the <<operationEditable,operationEditable>> attribute.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/editableoperation/property-filter-editable-operation.xml[tags=filtering-operations]
----

The list of available operations depends on the property type.

[[data-binding]]
== Data-aware `propertyFilter`

Set `dataLoader` to the loader that `propertyFilter` should constrain and `property` to the entity attribute used in the condition. The loader can populate either a xref:data/collection-container.adoc[collection container] or a xref:data/key-value-containers.adoc[key-value container].

[[collection-container]]
== Property Filter with a Collection Container

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/property-filter-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The following example demonstrates setting up `propertyFilter` to work with a collection container:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/simple/property-filter-simple.xml[tags=basics]
----

[[key-value-collection-container]]
== Property Filter with a Key-Value Collection Container

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/property-filter-key-value" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The following example demonstrates setting up `propertyFilter` to work with a key-value collection container:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/keyvalue/property-filter-key-value.xml[tags=key-value]
----

[[multi-filtering]]
== Multi-Filtering

Binding multiple `propertyFilter` components to a single data container allows to apply several conditions simultaneously. For example, use two components to support filtering by department and last name:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/propertyfilter/property-filter-view.xml[tags=multiple-filters]
----

[[filtering-dates]]
== Filtering Dates

[[date-equals]]
== Omitting Time

An exact match with `=` may not always fit Date/Time properties. Many situations require filtering by just the date, ignoring the time. In such cases, use `date equals` instead:

[[date-interval]]
== Date Interval

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/property-filter-date-interval-operation" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The component provides several options to filter by date intervals. Choose the `in interval` operator and enter interval values in the dialog.

Choose from:

* *Last*: intervals like "last 3 months" or "last 12 weeks".
* *Next*: intervals such as "next 3 years" or "next 48 hours".
* *Predefined*: quick selections including "today", "tomorrow", "this month", or "this year".
* *Relative date and time*: for conditions like "by the end of the day", "at the start of the hour", "not the last day of the year".
* *Custom*: for any start and end date. The start date is included in the range, the end date is excluded.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/dateinterval/property-filter-date-interval-operation.xml[tags=date-interval]
----

[[customization]]
== Customization

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/property-filter-custom-field" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

You can explicitly specify the component to use as the input field and set its attributes. This enables to change the default `propertyFilter` look and feel and enhance it with additional features. For example:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/customfield/property-filter-custom-field.xml[tags=customization]
----

[[dynamic-attributes]]
== Dynamic Attributes

The component supports filtering by xref:dyn-attr:index.adoc[dynamic attributes]. This does not require having the xref:dyn-attr:dynattr-view.adoc#using-dynamicattributes-facet[dynamicAttributes] facet on that view.

To specify a dynamic attribute, begin its name with a `+` prefix:

[source, xml,indent=0]
----
include::dyn-attr:example$dyn-attr-ex1/src/main/resources/com/company/demo/view/car/car-list-view.xml[tags=property-filter-dynamic-attribute]
----

NOTE: If the dynamic attribute is an entity, it cannot be filtered through its attributes.

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`No predefined variants`
|`propertyFilter` does not define built-in theme variants. Use `themeNames` for custom styles in your application theme.
|Custom themes
|===

[[attributes]]
== Attributes

The following attributes are specific to `propertyFilter`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[autoApply]]`autoApply`
|Sets whether the property filter should be automatically applied to the `DataLoader` when the condition value is changed.
|—

|[[dataLoader]]`dataLoader`
|`dataLoader` is a required attribute.
|—

|[[defaultValue]]`defaultValue`
|Sets the default value for the filter condition.
|—

|[[label]]`label`
|Sets the component label.
|—

|[[labelPosition]]`labelPosition`
|The `labelPosition` attribute defines the filter label position:
|—

|[[labelVisible]]`labelVisible`
|Sets the <<label,label>> visible or not.
|—

|[[labelWidth]]`labelWidth`
|Sets the <<label,label>> width.
|—

|[[operation]]`operation`
|Specifies the filtering operation.
|—

|[[operationEditable]]`operationEditable`
|Sets whether an operation selector is visible.
|—

|[[operationTextVisible]]`operationTextVisible`
|The `operationTextVisible` attribute defines the visibility of the operation label.
|—

|[[parameterName]]`parameterName`
|The `parameterName` attribute sets the name of the associated query parameter name, used by condition.
|—

|[[property]]`property`
|Specifies the entity attribute bound to the component.
|—
|===

The following shared attributes are supported by `propertyFilter`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#invalid[invalid] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `propertyFilter`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[OperationChangeEvent]]`OperationChangeEvent`
|The `OperationChangeEvent` is sent when the operation property is changed.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `propertyFilter`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Elements

A `propertyFilter` can include xref:vc/components/tooltip.adoc[tooltip] and xref:vc/miscellaneous/validator.adoc[validator] as its nested elements.
