= propertyFilter
:page-aliases: vcl/components/property-filter.adoc

`propertyFilter` фильтрует данные по атрибуту xref:data-model:entities.adoc[сущность].

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`propertyFilter`

|Java-класс
|`PropertyFilter`
|===

== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/property-filter-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В простейшем виде `propertyFilter` состоит из поля ввода, перед которым указаны имя фильтруемого атрибута и используемая операция.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/simple/property-filter-simple.xml[tags=basics]
----

Этот компонент фильтрует данные, загруженные в контейнер данных. Он часто используется вместе с компонентами xref:vc/components/dataGrid.adoc[] или xref:vc/components/treeDataGrid.adoc[], которые связаны с тем же контейнером. Такая комбинация позволяет точно управлять отображаемыми строками.

== Операции фильтрации

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/property-filter-editable-operation" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент поддерживает множество <<operation,операций>> фильтрации. Можно выбрать одну операцию или разрешить пользователям менять её во время выполнения с помощью атрибута <<operationEditable,operationEditable>>.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/editableoperation/property-filter-editable-operation.xml[tags=filtering-operations]
----

Список доступных операций зависит от типа свойства.

[[data-binding]]
== `propertyFilter` связанный с данными

В `dataLoader` укажите загрузчик, к которому применяется `propertyFilter`, а в `property` — атрибут сущности для условия. Загрузчик может заполнять xref:data/collection-container.adoc[контейнер коллекции] или xref:data/key-value-containers.adoc[контейнер ключ-значение].

[[collection-container]]
== Контейнер коллекции

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/property-filter-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В следующем примере `propertyFilter` настраивается для работы с контейнером коллекции:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/simple/property-filter-simple.xml[tags=basics]
----

[[key-value-collection-container]]
== Контейнер Key-Value

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/property-filter-key-value" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В следующем примере `propertyFilter` настраивается для работы с контейнером коллекции ключ-значение:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/keyvalue/property-filter-key-value.xml[tags=key-value]
----

== Множественная фильтрация

Привязка нескольких компонентов `propertyFilter` к одному контейнеру данных позволяет применять несколько условий фильтрации одновременно. Например, можно использовать два компонента для фильтрации по отделу и фамилии:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/propertyfilter/property-filter-view.xml[tags=multiple-filters]
----

== Фильтрация по дате

[[date-equals]]
== Фильтрация по дате без учета времени

Операция сравнения `=` не всегда подходит для свойств с типом Date/Time. Для сравнения только по дате (без учета времени), вместо `=` используйте `date equals`:

[[date-interval]]
== Фильтрация по временному интервалу

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/property-filter-date-interval-operation" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент предоставляет несколько способов фильтрации по интервалам дат. Выберите оператор `in interval` и укажите значения интервала в диалоговом окне.

Доступные опции:

* *Прошедший период*: интервалы вида «последние 3 месяца» или «последние 12 недель».
* *Будущий период*: интервалы вида «следующие 3 года» или «следующие 48 часов».
* *Предопределённый интервал*: значения «сегодня», «завтра», «в этом месяце» или «в этом году».
* *Относительные дата и время*: условия «к концу дня», «в начале часа», «не в последний день года».
* *Произвольный интервал*: позволяет указать границы интервала вручную.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/dateinterval/property-filter-date-interval-operation.xml[tags=date-interval]
----

[[customization]]
== Настройка

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/property-filter-custom-field" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Можно явно задать компонент поля ввода и настроить его атрибуты. Это позволяет изменить стандартный внешний вид `propertyFilter` и добавить дополнительные возможности. Например:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/propertyfilter/customfield/property-filter-custom-field.xml[tags=customization]
----

== Динамические атрибуты

Компонент поддерживает фильтрацию по xref:dyn-attr:index.adoc[динамическим атрибутам]. Для этого не требуется наличие фасета xref:dyn-attr:dynattr-view.adoc#using-dynamicattributes-facet[dynamicAttributes] на экране.

Чтобы указать динамический атрибут, начните его имя с префикса `+`:

[source, xml,indent=0]
----
include::dyn-attr:example$dyn-attr-ex1/src/main/resources/com/company/demo/view/car/car-list-view.xml[tags=property-filter-dynamic-attribute]
----

NOTE: Если динамический атрибут является сущностью, фильтрация по его атрибутам невозможна.

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`Предопределённые варианты отсутствуют`
|`propertyFilter` не определяет встроенные варианты оформления. Используйте `themeNames` для пользовательских стилей в теме приложения.
|Пользовательские темы
|===

[[attributes]]
== Атрибуты

`propertyFilter` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[autoApply]]`autoApply`
|Устанавливает, должен ли фильтр по атрибутам автоматически применяться к `DataLoader` при изменении значения условия.
|—

|[[dataLoader]]`dataLoader`
|`dataLoader` — обязательный атрибут.
|—

|[[defaultValue]]`defaultValue`
|Устанавливает значение по умолчанию для условия фильтра.
|—

|[[label]]`label`
|Задаёт подпись компонента.
|—

|[[labelPosition]]`labelPosition`
|Атрибут `labelPosition` определяет положение метки фильтра:
|—

|[[labelVisible]]`labelVisible`
|Устанавливает видимость <<label,label>> или нет.
|—

|[[labelWidth]]`labelWidth`
|Устанавливает ширину <<label,label>>.
|—

|[[operation]]`operation`
|Определяет операцию фильтрации.
|—

|[[operationEditable]]`operationEditable`
|Устанавливает, виден ли селектор операций.
|—

|[[operationTextVisible]]`operationTextVisible`
|Атрибут `operationTextVisible` определяет видимость метки операции.
|—

|[[parameterName]]`parameterName`
|Атрибут `parameterName` задаёт имя связанного имени параметра запроса, используемого условием.
|—

|[[property]]`property`
|Указывает атрибут сущности, связанный с компонентом.
|—
|===

`propertyFilter` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#invalid[invalid] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`propertyFilter` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[OperationChangeEvent]]`OperationChangeEvent`
|`OperationChangeEvent` отправляется при изменении свойства операции.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`propertyFilter` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Элементы

Компонент `propertyFilter` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip] и xref:vc/miscellaneous/validator.adoc[validator].
