= radioButtonGroup
:page-aliases: vcl/components/radio-button-group.adoc

`radioButtonGroup` позволяет пользователям выбирать одно значение из предопределённого списка элементов с помощью переключателей.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`radioButtonGroup`

|Java-класс
|`JmixRadioButtonGroup`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/radio-button-group-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Простейший вариант использования `radioButtonGroup` — выбор значения перечисления для атрибута сущности.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/radiobuttongroup/simple/radio-button-group-simple.xml[tags=basics]
----

В приведенном выше примере сущность `User` имеет атрибут `onboardingStatus` типа `OnboardingStatus`, который является перечислением.

[[data-binding]]
== `radioButtonGroup` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/radio-button-group-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`radioButtonGroup` может получить список элементов из контейнера данных с помощью атрибута `itemsContainer`. Например:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/radiobuttongroup/dataaware/radio-button-group-dataaware.xml[tags=data-binding]
----

В этом случае `radioButtonGroup` будет отображать имена экземпляров сущности `Hobby`, расположенных в контейнере данных `hobbiesDc`, а его метод `getValue()` будет возвращать выбранный в данный момент экземпляр сущности.

[[building-items]]
== Формирование списка опций

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/radio-button-group-custom-items" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Для установки списка элементов `radioButtonGroup` используйте следующие методы:

[[items-list]]
== Список элементов

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/radiobuttongroup/customitems/radio-button-group-custom-items.xml[tags=items-list]
----

Метод `setItems()` позволяет вам программно задать элементы компонента.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/radiobuttongroup/customitems/RadioButtonGroupCustomItemsSample.java[tags=items-list-field;items-list-init;items-list-method]
----

[[items-map]]
== Список элементов с описаниями

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/radiobuttongroup/customitems/radio-button-group-custom-items.xml[tags=items-map]
----

`ComponentUtils.setItemsMap()` позволяет вам явно указать строковое описание для каждого значения элемента.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/radiobuttongroup/customitems/RadioButtonGroupCustomItemsSample.java[tags=items-map-field;items-map-init;items-map-method]
----

[[items-enum]]
== Список значений перечисления

Вы можете использовать либо декларативный, либо программный подход для установки значений перечисления в качестве элементов `radioButtonGroup`.

В следующем примере показан декларативный подход.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/radiobuttongroup/customitems/radio-button-group-custom-items.xml[tags=items-enum]
----

Пример ниже использует программный подход.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/radiobuttongroup/customitems/RadioButtonGroupCustomItemsSample.java[tags=items-enum-field;items-enum-init]
----

[[item-enabled-provider]]
== Настройка активности элементов

`itemEnabledProvider` позволяет вам динамически управлять состоянием включения отдельных радиокнопок в зависимости от конкретных условий. Отключенные элементы отображаются серым цветом и не могут быть выбраны пользователем. По умолчанию все элементы включены.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/radiobuttongroup/RadioButtonGroupView.java[tags=itemEnabledProvider]
----

[[customizing-item-labels]]
== Настройка отображения элементов

`itemLabelGenerator` позволяет вам настроить отображение элементов `radioButtonGroup`. Это дает вам контроль над текстом, который видят пользователи, позволяя представлять информацию более удобным для пользователя или контекстно-специфичным образом.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/radiobuttongroup/RadioButtonGroupView.java[tags=itemLabelGenerator]
----

[[rendering-items]]
== Рендеринг элементов

Можно настроить рендеринг элементов. Рендерер применяется к каждому элементу для создания компонента, который представляет этот элемент.

Для этого можно использовать метод `setRenderer()` или аннотацию `@Supply`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/radiobuttongroup/RadioButtonGroupView.java[tags=autowired;renderer]
----

[[fragment-renderer]]
В качестве альтернативы вы можете отображать элементы, используя вложенный элемент `fragmentRenderer`. Дополнительную информацию смотрите в разделе xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Рендерер фрагментов].

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/radio-button-group-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`vertical`
|Располагает элементы вертикально.
|Lumo

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo
|===

== Атрибуты

`radioButtonGroup` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[itemsContainer]]`itemsContainer`
|Определяет контейнер данных, содержащий список элементов. Компонент отображает имя экземпляра сущности. См. <<data-binding,Привязка данных>>.
|—

|[[itemsEnum]]`itemsEnum`
|Определяет класс перечисления для создания списка элементов. См. <<items-enum,Перечисление предметов>>.
|—
|===

`radioButtonGroup` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`radioButtonGroup` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[itemEnabledProvider]]`itemEnabledProvider`
|`itemEnabledProvider` применяется к каждому элементу этого `radioButtonGroup`, чтобы определить, должен ли этот элемент быть включен (`true`) или отключен (`false`). См. <<item-enabled-provider,Поставщик, поддерживающий элемент>>.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Позволяет настраивать метки, отображаемые для каждого переключателя. См. <<customizing-item-labels,Настройка меток предметов>>.

|[[renderer]]`renderer`
|Устанавливает средство визуализации элемента для этой группы переключателей. См. <<rendering-items,Рендеринг предметов>>.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`radioButtonGroup` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `radioButtonGroup` может содержать следующие вложенные элементы: <<fragment-renderer,fragmentRenderer>> и xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/radio-button[Документация Vaadin: Radio Button^]
