= select

`select` позволяет пользователям выбирать одно значение из списка элементов, представленных в наложении.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`select`

|Java-класс
|`JmixSelect`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/select-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`select` похож на xref:flow-ui:vc/components/comboBox.adoc[comboBox].

Используйте `select`, когда:

* Вам не нужны пользовательский ввод и фильтрация элементов.
* Список должен быть компактным. Это может быть полезно, если список элементов слишком длинный для xref:flow-ui:vc/components/radioButtonGroup.adoc[radioButtonGroup].

Простейший случай использования `select` - это выбор значения из перечисления:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/select/simple/select-simple.xml[tags=basics]
----

[[data-binding]]
== `select` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/select-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибуты `dataContainer` и `property`, чтобы связать `select` с атрибутом сущности. Контейнер данных предоставляет экземпляр сущности, а `property` указывает редактируемый атрибут.

По умолчанию Jmix Studio генерирует `select` при создании экрана деталей сущности с атрибутом типа перечисления. Например, сущность `User` имеет атрибут `onboardingStatus` типа `OnboardingStatus`, который является перечислением.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/select/dataaware/select-dataaware.xml[tags=data-binding]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/select/dataaware/SelectDataawareSample.java[tags=data-binding]
----

В следующем примере показано, как использовать компонент `select` для выбора отдела, к которому принадлежит пользователь:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/select/select-view.xml[tags=data;layout;data-bind]
----
<1> Контейнер данных для хранения экземпляра `User`, который в данный момент редактируется.
<2> Фетч-план расширен для получения коллекции экземпляров `Department`, которые будут доступны для выбора.
<3> Контейнер данных для хранения коллекции всех существующих экземпляров `Department`.
<4> Координатор загрузки данных для автоматического предоставления компоненту экземпляров для выбора.
<5> Привязка компонента к контейнеру данных и свойству. Указание коллекции экземпляров для выбора с использованием атрибута `itemsContainer`.

[[building-items]]
== Формирование списка опций

Для установки списка элементов `select` используйте следующие методы:

[[items-list]]
== Список элементов

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/select/select-view.xml[tags=items-list]
----

Метод `setItems()` позволяет вам программно задать элементы компонента.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=items-list;onInit]
----

[[items-map]]
== Список элементов с описаниями

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/select/select-view.xml[tags=items-map]
----

`ComponentUtils.setItemsMap()` позволяет вам явно указать строковое описание для каждого значения элемента.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=items-map;onInit]
----

[[items-enum]]
== Список значений перечисления

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/select-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Значения перечисления можно задать как элементы `select` декларативно или программно.

В следующем примере показан декларативный подход.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/select/simple/select-simple.xml[tags=basics]
----

Пример ниже использует программный подход.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=items-enum;onInit]
----

[[disabled-items]]
== Неактивные элементы списка

Элементы списка могут быть отключены, чтобы указать, что они недоступны для выбора, но могут быть выбраны при других условиях.

`itemEnabledProvider` позволяет динамически управлять состоянием включения отдельных элементов в зависимости от определённых условий. Отключенные элементы отображаются серым цветом и не могут быть выбраны пользователем. По умолчанию все элементы включены.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=itemEnabledProvider]
----

[[empty-selection-item]]
== Элемент пустого выбора

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/select-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент `select` может отображать пустой элемент выбора. Это удобно, если требуется значение по умолчанию или состояние «ничего не выбрано».

Атрибут `emptySelectionAllowed` устанавливает, разрешено ли пользователю ничего не выбирать. При установке значения `true` пользователю показывается специальный пустой элемент.

Элемент пустого выбора можно настроить с помощью атрибута <<emptySelectionCaption,emptySelectionCaption>>.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/select/simple/select-simple.xml[tags=basics]
----

Атрибут `emptySelectionCaption` задаёт подпись для пустого выбора, когда <<emptySelectionAllowed,пустойSelectionAllowed = истина>>. Эта подпись отображается для элемента пустого выбора в выпадающем списке.

Когда выбран пустой элемент, `select` отображает подпись, которую xref:vc/components/comboBox.adoc#itemLabelGenerator[itemLabelGenerator] возвращает для значения `null`. Если генератор не задан, отображается строка из атрибута xref:vc/common-attributes.adoc#placeholder[placeholder] либо пустая строка.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=emptySelectionAllowed]
----

[[customizing-item-labels]]
== Настройка отображения элементов

`itemLabelGenerator` позволяет вам настроить способ отображения элементов в выпадающем списке. Это даёт вам контроль над текстом, который видят пользователи, позволяя вам представлять информацию более удобным для пользователя или контекстно-зависимым способом.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=itemLabelGenerator]
----

`itemLabelGenerator` управляет как метками для каждого элемента в выпадающем списке, так и текстом, отображаемым в поле ввода компонента `select`, когда выбран элемент.

`textRenderer` управляет метками, отображаемыми в выпадающем списке для каждого элемента.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=textRenderer]
----

NOTE: `textRenderer` не влияет на текст, отображаемый в поле ввода компонента `select` после выбора элемента.

[[rendering-items]]
== Рендеринг элементов

Можно настроить рендеринг элементов. Рендерер применяется к каждому элементу для создания компонента, который представляет этот элемент.

Для этого можно использовать метод `setRenderer()` или аннотацию `@Supply`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/select/SelectView.java[tags=autowired;renderer]
----

<1> `@Supply` привязывает рендерер к `selectWithRenderer`.
<2> Функция получает текущий элемент.
<3> Экземпляр компонента создаётся и настраивается в этом же обработчике.
<4> Функция возвращает компонент для текущего элемента.

[[fragment-renderer]]
В качестве альтернативы вы можете отображать элементы, используя вложенный элемент `fragmentRenderer`. Дополнительную информацию смотрите в разделе xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Рендерер фрагментов].

[[overlay]]
== Оверлей

Оверлей - это полупрозрачный или непрозрачный слой, который используется для создания выпадающего списка элементов.

Атрибут `overlayClass` позволяет вам добавлять пользовательские CSS-классы к элементу оверлея.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/select/select-view.xml[tags=overlay]
----

Определите свой собственный стиль в вашем CSS-файле:

[source,css,indent=0]
----
include::example$/onboarding/frontend/themes/onboarding/onboarding.css[tags=overlay-select]
----

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`select` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[emptySelectionAllowed]]`emptySelectionAllowed`
|Устанавливает, разрешено ли пользователю ничего не выбирать. См. <<empty-selection-item,Пустой элемент выбора>>.
|`false`

|[[emptySelectionCaption]]`emptySelectionCaption`
|Устанавливает пустой заголовок выбора при `emptySelectionAllowed = true`. См. <<empty-selection-item,Пустой элемент выбора>>.
|Пустая строка ""

|[[itemsContainer]]`itemsContainer`
|Определяет контейнер данных, содержащий список элементов. Компонент отображает имя экземпляра сущности. См. второй пример в <<data-binding,Привязка данных>>.
|—

|[[itemsEnum]]`itemsEnum`
|Определяет класс перечисления для создания списка элементов. См. <<items-enum,Перечисление предметов>>.
|—

|[[noVerticalOverlap]]`noVerticalOverlap`
|При `false` наложение отображается поверх поля ввода. При `true` наложение не закрывает поле ввода. См. это в https://vaadin.com/docs/v25/components/select#overlay-position[Vaadin documentation^].
|`false`

|[[overlayClass]]`overlayClass`
|Определяет список имен классов CSS, разделенных пробелами, для установки в элементе наложения. См. <<overlay, Overlay>>.
|—

|[[overlayWidth]]`overlayWidth`
|Определяет ширину наложения. Если этот параметр опущен (по умолчанию), наложение автоматически регулирует свою ширину в соответствии с самым широким параметром или, по крайней мере, с шириной поля ввода. См. это в https://vaadin.com/docs/v25/components/select#overlay-width[Vaadin documentation^].
|—
|===

`select` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`select` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[InvalidChangeEvent]]`InvalidChangeEvent`
|`com.vaadin.flow.component.select.Select.InvalidChangeEvent` отправляется при изменении состояния xref:flow-ui:vc/common-attributes.adoc#invalid[invalid].

|[[OpenedChangeEvent]]`OpenedChangeEvent`
|`com.vaadin.flow.component.select.Select.OpenedChangeEvent` отправляется при изменении состояния наложения `opened`.

|[[itemEnabledProvider]]`itemEnabledProvider`
|`itemEnabledProvider` применяется к каждому элементу этого `select`, чтобы определить, должен ли этот элемент быть включен (`true`) или отключен (`false`). См. <<disabled-items,Отключенные элементы>>.

|[[itemLabelGenerator]]`itemLabelGenerator`
|Позволяет настроить метки, отображаемые для каждого элемента. См. <<customizing-item-labels,Настройка меток предметов>>.

|[[renderer]]`renderer`
|Устанавливает средство визуализации элемента для этой выбранной группы. Средство визуализации применяется к каждому элементу для создания компонента, который представляет параметр элемента в раскрывающемся списке выбора. См. <<rendering-items,Рендеринг предметов>>.

|[[textRenderer]]`textRenderer`
|Это средство визуализации для преобразования элемента в строку. См. <<customizing-item-labels,Настройка меток предметов>>.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`select` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `select` может содержать следующие вложенные элементы: <<fragment-renderer,fragmentRenderer>>, xref:vc/miscellaneous/prefix-suffix.adoc[prefix], и xref:vc/components/tooltip.adoc[tooltip].

== Смотрите также

* https://vaadin.com/docs/v25/components/select[Документация Vaadin: Select^]
