= switch

`switch` lets users toggle a boolean setting on or off.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`switch`

|Java Class
|`Switch`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/switch-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`switch` is an alternative to the xref:flow-ui:vc/components/checkbox.adoc[checkbox] component, designed to represent binary states clearly and intuitively. Switches are best for:

* Toggling between two mutually exclusive options (for example, on/off).
* Providing immediate visual feedback.
* Enabling or disabling settings that take effect right away.

The `checkbox` and xref:flow-ui:vc/components/checkboxGroup.adoc[checkboxGroup] components, on the other hand, are better suited for:

* Selecting one or more options from a list.
* Allowing multiple, non-exclusive choices.
* Scenarios where changes do not take immediate effect.

An example of `switch`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/switchcomponent/simple/switch-simple.xml[tags=basics]
----

== Data-aware `switch`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/switch-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the `dataContainer` and `property` attributes to bind `switch` to a Boolean entity attribute. The data container provides the entity instance, and `property` identifies the attribute to edit.

The following example produces a data-aware `switch`. The entity attribute must be of `Boolean` type.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/switchcomponent/dataaware/switch-dataaware.xml[tags=data-binding]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/switchcomponent/dataaware/SwitchDataawareSample.java[tags=data-binding]
----

== States

`switch` can exist in several states that define its visual appearance and functionality.

[[enabled-state]]
*Enabled*

* Disabled: `switch` is inactive and cannot be interacted with by the user. Visually, it is often grayed out to indicate its inactive state.
* Enabled: `switch` is interactive and responsive to user input. Users can click on it to change its state.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/switchcomponent/switch-view.xml[tags=enabled]
----

[[read-only-state]]
*Read-only*

The `readOnly` attribute controls whether the `switch` component can be interacted with by the user. If set to `true`, `switch` becomes read-only, meaning the user cannot change its state.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/switchcomponent/switch-view.xml[tags=readOnly]
----

[[required-state]]
*Required*

`switch` can be configured as required using its <<required,required>> attribute or by binding it to a mandatory attribute with `@NotNull` validation.

When the field is marked as required, a visual indicator appears next to the label to inform the user. If `switch` is initially turned on (selected) and then turned off (deselected), the field will be marked as invalid until the required condition is met again.

NOTE: Like input fields, `switch` will only pass `@NotNull` validation if it is not empty (i.e., if it is checked). The default behavior can be modified using the xref:ui-properties.adoc#jmix.ui.component.checkbox-required-state-initialization-enabled[jmix.ui.component.checkbox-required-state-initialization-enabled] property, which allows the unchecked state to be treated as `false`.

== Attributes

The following attributes are specific to `switch`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[enabled]]`enabled`
|Sets the component explicitly disabled or enabled. See <<enabled-state,Enabled State>>.
|`true`

|[[readOnly]]`readOnly`
|Specifies whether the `switch` component is in read-only mode. See <<read-only-state,Read-Only State>>.
|`false`

|[[required]]`required`
|Set the required state of `switch`. See <<required-state,Required State>>.
|`false`

|[[value]]`value`
|Sets the component value.
|—
|===

The following shared attributes are supported by `switch`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clickShortcut[clickShortcut] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `switch`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[ClickEvent]]`ClickEvent`
|Fired when the user clicks the component.
|===

The following shared handlers are supported by `switch`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Elements

A `switch` can include xref:vc/components/tooltip.adoc[tooltip] as its nested elements.
