= switch

`switch` позволяет пользователям включать и выключать логические значения.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`switch`

|Java-класс
|`Switch`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/switch-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`switch` — альтернатива компоненту xref:flow-ui:vc/components/checkbox.adoc[checkbox], предназначенная для интуитивного представления двоичных состояний.

Когда использовать `switch`:

* Переключение между двумя взаимоисключающими состояниями (например, Вкл/Выкл).
* Мгновенная визуальная обратная связь.
* Включение/отключение настроек с немедленным применением.

Компоненты `checkbox` и xref:flow-ui:vc/components/checkboxGroup.adoc[checkboxGroup], в свою очередь, больше подходят для:

* Выбора одного или нескольких пунктов из списка.
* Возможности множественного, неисключающего выбора.
* Сценариев, где изменения не применяются мгновенно

Пример использования `switch`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/switchcomponent/simple/switch-simple.xml[tags=basics]
----

== `switch` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/switch-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибуты `dataContainer` и `property`, чтобы связать `switch` с атрибутом сущности типа Boolean. Контейнер данных предоставляет экземпляр сущности, а `property` указывает редактируемый атрибут.

Следующий пример создаёт переключатель, связанный с данными. Атрибут сущности должен быть типа `Boolean`.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/switchcomponent/dataaware/switch-dataaware.xml[tags=data-binding]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/switchcomponent/dataaware/SwitchDataawareSample.java[tags=data-binding]
----

== Состояния

`switch` может находиться в нескольких состояниях, определяющих его внешний вид и функциональность.

[[enabled-state]]
*Enabled*

* Отключено: переключатель неактивен и не реагирует на действия пользователя. Визуально он часто отображается серым цветом, чтобы указать на его неактивное состояние.
* Включено: переключатель интерактивный и реагирует на действия пользователя. Пользователи могут щелкнуть по нему, чтобы изменить его состояние.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/switchcomponent/switch-view.xml[tags=enabled]
----

[[read-only-state]]
*Read-only*

Атрибут `readOnly` управляет возможностью взаимодействия пользователя с компонентом `switch`. Если он установлен в `true`, переключатель становится доступным только для чтения, то есть пользователь не может изменить его состояние.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/switchcomponent/switch-view.xml[tags=readOnly]
----

[[required-state]]
*Required*

Компонент можно настроить как обязательный, используя атрибут <<required,required>> или связав его с обязательным атрибутом c `@NotNull` валидацией.

Если поле обязательное, рядом с подписью отображается соответствующий индикатор. Если `switch` был включён, а затем выключен, поле будет отмечено как недопустимое, пока обязательное условие снова не будет выполнено.

== Атрибуты

`switch` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[enabled]]`enabled`
|Устанавливает компонент явно отключенным или включенным. См. <<enabled-state,Включенное состояние>>.
|`true`

|[[readOnly]]`readOnly`
|Указывает, находится ли компонент `switch` в режиме только для чтения. См. <<read-only-state,Состояние только для чтения>>.
|`false`

|[[required]]`required`
|Установите необходимое состояние `switch`. См. <<required-state,Требуемое состояние>>.
|`false`

|[[value]]`value`
|Задаёт значение компонента.
|—
|===

`switch` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clickShortcut[clickShortcut] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`switch` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClickEvent]]`ClickEvent`
|Запускается, когда пользователь кликает компонент.
|===

`switch` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Элементы

Компонент `switch` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip].
