= tabs

`tabs` позволяет пользователям переключаться между связанными областями контента, не включая сам контент.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`tabs`

|Java-класс
|`Tabs`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/tabs-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

По умолчанию вкладки располагаются горизонтально, а их подписи следуют друг за другом. Такая строка вкладок обычно находится над связанной областью содержимого или под ней.

Следующий пример демонстрирует базовую функциональность `tabs`.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/simple/tabs-simple.xml[tags=basics]
----

В этом примере компонент содержит две вложенные <<tab,вкладки>>. Для обновления контента, связанного с выбранной вкладкой, определите обработчик событий, который отслеживает <<SelectedChangeEvent, SelectedChangeEvent>>. При выборе вкладки это событие срабатывает, позволяя соответствующим образом обновить отображаемое содержимое.

== Ориентация

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/tabs-orientation" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Хотя по умолчанию используется горизонтальная ориентация, в некоторых случаях удобнее вертикальная. Например, при большом количестве вкладок она оставляет больше места для подписей.

Используйте атрибут <<orientation, orientation>> для изменения ориентации компонента tabs.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/orientation/tabs-orientation.xml[tags=orientation]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/tabs/orientation/TabsOrientationSample.java[tags=orientation]
----

== Состояния

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/tabs-states" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Вкладка `tab` может быть выбранной, невыбранной или отключённой:

Эти состояния позволяют пользователям легко определить, какая вкладка активна в данный момент, а какие временно недоступны или отключены.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/states/tabs-states.xml[tags=states]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/tabs/states/TabsStatesSample.java[tags=states]
----

[[labels]]
== Надписи

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/tabs-icons" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В отдельные вкладки можно вкладывать почти любые компоненты, создавая наглядные и выразительные подписи:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/icons/tabs-icons.xml[tags=labels]
----

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/tabs-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`icon-on-top`
|Для отдельного элемента `tab` располагает значок над текстом метки. Установите `themeNames="icon-on-top"` у `tab`.
|Lumo

|`centered`
|Размещает вкладки по центру контейнера.
|Lumo

|`small`
|Уменьшает размер вкладок.
|Aura, Lumo

|`minimal`
|Упрощает визуальный стиль, оставляя акцент только на надписях.
|Lumo

|`hide-scroll-buttons`
|Скрывает кнопки прокрутки для навигации по не помещающимся вкладкам.
|Aura, Lumo

|`equal-width-tabs`
|Выделяет одинаковую ширину для всех вкладок и отключает прокрутку.
|Lumo
|===
[[attributes]]
== Атрибуты

`tabs` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[orientation]]`orientation`
|Определяет ориентацию вкладок.
|—
|===

`tabs` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`tabs` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[SelectedChangeEvent]]`SelectedChangeEvent`
|`com.vaadin.flow.component.tabs.Tabs.SelectedChangeEvent` запускается при выборе другой вкладки.
|===

`tabs` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Элементы

[TIP]
====
Для добавления элемента в Jmix Studio:

. Выберите компонент в XML-дескрипторе экрана или панели Jmix UI Structure

. Нажмите кнопку xref:studio:view-designer.adoc#component-inspector-add-button[*Add*] в панели *Component Inspector*
====

[[tab]]
=== tab

Отдельные вкладки определяются с помощью вложенных элементов `tab`.

.*`tab` attributes*
xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#flexGrow[flexGrow] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible]

.*`tab` handlers*
xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Смотрите также

* https://vaadin.com/docs/v25/components/tabs[Документация Vaadin: Tabs^]
