= tabs

`tabs` lets users switch between associated content areas without containing the content itself.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`tabs`

|Java Class
|`Tabs`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/tabs-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

By default, tabs are displayed in a horizontal row, with the tab labels arranged one after another. This row of tabs is typically positioned at the top or bottom of the associated content area.

The following example demonstrates basic `tabs` functionality.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/simple/tabs-simple.xml[tags=basics]
----

In this example, the component contains two nested <<tab,tab>> elements. To update the content associated with the selected tab, define an event handler that listens for the <<SelectedChangeEvent, SelectedChangeEvent>>. When a tab is selected, this event is fired, allowing you to update the displayed content accordingly.

== Orientation

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/tabs-orientation" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

While horizontal orientation is default, vertical orientation can be alternative option in certain scenarios. For example, with a larger number of tabs, this orientation may provide additional space for their labels.

Use the <<orientation, orientation>> attribute to change the orientation of `tabs`.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/orientation/tabs-orientation.xml[tags=orientation]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/tabs/orientation/TabsOrientationSample.java[tags=orientation]
----

== States

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/tabs-states" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

A `tab` can be selected, unselected, or disabled:

These states allow users to easily determine which tab is currently active and which tabs may be temporarily unavailable or disabled.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/states/tabs-states.xml[tags=states]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/tabs/states/TabsStatesSample.java[tags=states]
----

[[labels]]
== Labels

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/tabs-icons" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Individual tabs can nest almost any components within them. This allows you to compose visually distinctive tab labels:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/tabs/icons/tabs-icons.xml[tags=labels]
----

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/tabs-theme-variant" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`icon-on-top`
|Applies to an individual `tab` element. Set `themeNames="icon-on-top"` on the `tab` to position the icon above the label text.
|Lumo

|`centered`
|Centers the tabs within the container.
|Lumo

|`small`
|Makes the tabs smaller.
|Aura, Lumo

|`minimal`
|Reduces the visual style to emphasize labels only.
|Lumo

|`hide-scroll-buttons`
|Hides the scroll buttons used to navigate overflown tabs.
|Aura, Lumo

|`equal-width-tabs`
|Allocates equal width to all tabs and disables scrolling.
|Lumo
|===

[[attributes]]
== Attributes

The following attributes are specific to `tabs`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[orientation]]`orientation`
|Defines tabs orientation.
|—
|===

The following shared attributes are supported by `tabs`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `tabs`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[SelectedChangeEvent]]`SelectedChangeEvent`
|`com.vaadin.flow.component.tabs.Tabs.SelectedChangeEvent` is fired when another tab is selected.
|===

The following shared handlers are supported by `tabs`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Elements

[TIP]
====
To add an element in Jmix Studio, select the component in the view descriptor XML or in the *Jmix UI* structure panel and click on the xref:studio:view-designer.adoc#component-inspector-add-button[*Add*] button in the *Component Inspector* panel.
====

[[tab]]
=== tab

Individual tabs are defined with nested `tab` elements.

.*`tab` attributes*
xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#flexGrow[flexGrow] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible]

.*`tab` handlers*
xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== See Also

* https://vaadin.com/docs/v25/components/tabs[Vaadin Tabs documentation^]
