= textField
:page-aliases: vcl/components/currency-field.adoc, vcl/components/text-field.adoc

`textField` — поле ввода для редактирования текста или значений других поддерживаемых типов данных.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`textField`

|Java-класс
|`TypedTextField`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/text-field-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

В следующем примере определены стандартное текстовое поле и поле с ограничением максимальной длины ввода:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/simple/text-field-simple.xml[tags=basics]
----

[[data-types]]
== Текстовые поля с разными типами данных

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/text-field-datatype" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`textField` — типизированный компонент, поэтому он поддерживает значения разных типов. Тип определяется при <<data-binding,привязке компонента>> к атрибуту сущности или задаётся явно атрибутом xref:vc/common-attributes.adoc#datatype[datatype].

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/datatype/text-field-datatype.xml[tags=basics]
----

Для работы с типизированными значениями также предназначены методы `setTypedValue()` и `getTypedValue()`. Они позволяют задать или получить значение конкретного типа, например `Integer` или `Long`.

При обработке изменений значений компонента рекомендуется использовать xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] вместо xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent]. Такой подход гарантирует корректность типа значения и исключает необходимость дополнительных преобразований или проверок.

[[data-binding]]
== `textField` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/text-field-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Чтобы связать `textField` с данными, используйте атрибуты xref:flow-ui:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:flow-ui:vc/common-attributes.adoc#property[property].

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/dataaware/text-field-dataaware.xml[tags=data-binding]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/textfield/dataaware/TextFieldDataawareSample.java[tags=data-binding]
----

В приведённом выше примере экран описывает контейнер данных `departmentDc` для сущности `Department`, которая содержит атрибут `name`. Компонент `textField` связан с контейнером через атрибут `dataContainer`; атрибут `property` содержит имя атрибута сущности, отображаемого в `textField`

[[value-change]]
== Режимы изменения значений

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/text-field-value-change" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Атрибут `valueChangeMode` определяет, когда введённые данные обновляют значение на стороне сервера. В примере обработчик изменения значения также обновляет вспомогательный текст по мере ввода.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/valuechange/text-field-value-change.xml[tags=value-change]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/textfield/valuechange/TextFieldValueChangeSample.java[tags=value-change]
----

[[validation]]
== Проверка

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/text-field-validator" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Добавьте вложенные валидаторы для проверки преобразованных значений поля. В примере стандартные валидаторы числового диапазона используются вместе с пользовательским валидатором — Spring-бином.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/validator/text-field-validator.xml[tags=validator]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/bean/PositiveIntegerValidator.java[tags=validator]
----

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`textField` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[autoselect]]`autoselect`
|Установите значение `true`, чтобы значение поля всегда автоматически выбиралось, когда поле получает фокус, в противном случае `false`.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Определяет, отображается ли в поле кнопка очистки.
|`false`

|[[trimEnabled]]`trimEnabled`
|Если `true`, компонент обрезает пробелы в начале и конце введённой строки.
|—

|[[value]]`value`
|Задаёт значение компонента.
|—
|===

`textField` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autocapitalize[autocapitalize] -
xref:vc/common-attributes.adoc#autocomplete[autocomplete] -
xref:vc/common-attributes.adoc#autocorrect[autocorrect] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxLength[maxLength] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minLength[minLength] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#pattern[pattern] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#valueChangeMode[valueChangeMode] -
xref:vc/common-attributes.adoc#valueChangeTimeout[valueChangeTimeout] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`textField` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`textField` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#CompositionEndEvent[CompositionEndEvent] -
xref:vc/common-handlers.adoc#CompositionStartEvent[CompositionStartEvent] -
xref:vc/common-handlers.adoc#CompositionUpdateEvent[CompositionUpdateEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#InputEvent[InputEvent] -
xref:vc/common-handlers.adoc#KeyDownEvent[KeyDownEvent] -
xref:vc/common-handlers.adoc#KeyPressEvent[KeyPressEvent] -
xref:vc/common-handlers.adoc#KeyUpEvent[KeyUpEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent]

== Элементы

Компонент `textField` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip], xref:vc/miscellaneous/validator.adoc[validator], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], и xref:vc/miscellaneous/prefix-suffix.adoc[suffix].

== Смотрите также

* https://vaadin.com/docs/v25/components/text-field[Документация Vaadin: Text Field^]
