= textField
:page-aliases: vcl/components/currency-field.adoc, vcl/components/text-field.adoc

`textField` is an input field for editing text or values of other supported data types.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`textField`

|Java Class
|`TypedTextField`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/text-field-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The following example defines a standard text field and a field with a maximum input length:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/simple/text-field-simple.xml[tags=basics]
----

[[data-types]]
== Text Fields with Different Data Types

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/text-field-datatype" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The `textField` component is a typed component, which means it enables you to work with input of different data types. You can set its type by <<data-binding, binding the component>> to an entity attribute of certain type or by setting type explicitly using the xref:vc/common-attributes.adoc#datatype[datatype] attribute.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/datatype/text-field-datatype.xml[tags=basics]
----

Additional methods to work with typed values include `setTypedValue()` and `getTypedValue()`. These methods are useful when you need to set or retrieve values of specific type, such as `Integer` or `Long`.

When processing changes to the component's values, it is recommended to use xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] instead of xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent]. This approach ensures that the value is of the correct type and avoids the need for additional type conversions or checks.

[[data-binding]]
== Data-aware `textField`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/text-field-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

To create `textField` connected to data, use xref:flow-ui:vc/common-attributes.adoc#dataContainer[dataContainer] and xref:flow-ui:vc/common-attributes.adoc#property[property] attributes.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/dataaware/text-field-dataaware.xml[tags=data-binding]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/textfield/dataaware/TextFieldDataawareSample.java[tags=data-binding]
----

In the example above, the view describes the `departmentDc` data container for the `Department` entity, which has the `name` attribute. The `textField` component has a link to the container specified in the `dataContainer` attribute; the `property` attribute contains the name of the entity attribute that is displayed in `textField`.

[[value-change]]
== Value Change Modes

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/text-field-value-change" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use `valueChangeMode` to control when user input updates the server-side value. The example also uses a value-change handler to update helper text as the user types.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/valuechange/text-field-value-change.xml[tags=value-change]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/textfield/valuechange/TextFieldValueChangeSample.java[tags=value-change]
----

[[validation]]
== Validation

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/text-field-validator" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Add nested validators to check converted field values. The example combines built-in numeric range validators with a custom Spring bean validator.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/textfield/validator/text-field-validator.xml[tags=validator]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/bean/PositiveIntegerValidator.java[tags=validator]
----

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`align-start`
|Aligns the field value to the start side, taking the current text direction into account.
|Aura

|`align-end`
|Aligns the field value to the end side, taking the current text direction into account.
|Aura

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo

|`small`
|Makes the component smaller.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `textField`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[autoselect]]`autoselect`
|Set to `true` to always have the field value automatically selected when the field gains focus, `false` otherwise.
|—

|[[clearButtonVisible]]`clearButtonVisible`
|Controls whether the field displays a clear button.
|`false`

|[[trimEnabled]]`trimEnabled`
|If `true`, the component trims spaces at the beginning and at the end of the entered string.
|—

|[[value]]`value`
|Sets the component value.
|—
|===

The following shared attributes are supported by `textField`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autocapitalize[autocapitalize] -
xref:vc/common-attributes.adoc#autocomplete[autocomplete] -
xref:vc/common-attributes.adoc#autocorrect[autocorrect] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxLength[maxLength] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minLength[minLength] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#pattern[pattern] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#valueChangeMode[valueChangeMode] -
xref:vc/common-attributes.adoc#valueChangeTimeout[valueChangeTimeout] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `textField`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `textField`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ClientValidatedEvent[ClientValidatedEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#CompositionEndEvent[CompositionEndEvent] -
xref:vc/common-handlers.adoc#CompositionStartEvent[CompositionStartEvent] -
xref:vc/common-handlers.adoc#CompositionUpdateEvent[CompositionUpdateEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#InputEvent[InputEvent] -
xref:vc/common-handlers.adoc#KeyDownEvent[KeyDownEvent] -
xref:vc/common-handlers.adoc#KeyPressEvent[KeyPressEvent] -
xref:vc/common-handlers.adoc#KeyUpEvent[KeyUpEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent]

== Elements

A `textField` can include xref:vc/components/tooltip.adoc[tooltip], xref:vc/miscellaneous/validator.adoc[validator], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], and xref:vc/miscellaneous/prefix-suffix.adoc[suffix] as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/text-field[Vaadin Text Field documentation^]
