= timePicker
:page-aliases: vcl/components/time-field.adoc

`timePicker` lets users enter or select a time.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`timePicker`

|Java Class
|`TypedTimePicker`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/time-picker-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Time can be entered directly using a keyboard or selected from an overlay with a list of time values. The overlay appears on clicking the field or the clock button.

The following example defines a `timePicker` of `localTime` type with a label:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/timepicker/simple/time-picker-simple.xml[tags=basics]
----

== Data Types

`timePicker` is a typed component which supports common data types for storing a time value:

* `localTime`
* `offsetTime`
* `time`

To change the type, use the xref:vc/common-attributes.adoc#datatype[datatype] attribute.

[[data-binding]]
== Data-aware `timePicker`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/time-picker-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the `dataContainer` and `property` attributes to bind `timePicker` to an entity attribute. The data container provides the entity instance, and `property` identifies the attribute to edit.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/timepicker/dataaware/time-picker-dataaware.xml[tags=data;data-binding]
----

[[step]]
== Step

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/time-picker-custom-range" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The default interval between the items displayed in the time overlay is set to one hour. To customize this interval, use the xref:vc/common-attributes.adoc#step[step] attribute either in XML or programmatically.

Setting the `step` attribute in the view descriptor XML:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/timepicker/customrange/time-picker-custom-range.xml[tags=step]
----
The `m` <<suffix,suffix>> specifies minutes.

[[suffix]]
The `step` attribute supports flexible time interval configuration using different chrono units. You can specify values with unit suffixes for clarity.

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/timepicker/time-picker-view.xml[tags=step-unit]
----
<1> 2 hour intervals.
<2> 1600 second (26m 40s) intervals.
<3> 20 minute intervals.

This can also be done in the view controller:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/timepicker/TimePickerView.java[tags=timePicker;onInit;step]
----

The step must divide an hour or day evenly. For example, "15 minutes", "30 minutes" and "2 hours" are valid steps, whereas "42 minutes" isn’t.

NOTE: The overlay doesn't appear for steps less than 15 minutes, to avoid showing an impractical number of choices.

// == Time Format
// //todo: make changes upon completing jmix#858 ticket
// The default date and time format in the application is defined by the xref:data-model:datatype.adoc#localized-format-strings[localized format strings]. To use a different format, add your own format strings to the message bundle.

== Time Range

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/time-picker-custom-range" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

To restrict the input to a specific time range, specify a minimum and maximum value using the <<max, max>> and <<min,min>> attributes.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/timepicker/customrange/TimePickerCustomRange.java[tags=time-range]
----

Apply a <<validator, validator>> to set a more specific time range.

[[variants]]
== Theme Variants

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/time-picker-theme-variant" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`small`
|Makes the component smaller.
|Aura, Lumo

|`align-left`
|Aligns the field value to the left side.
|Aura, Lumo

|`align-center`
|Centers the field value.
|Aura, Lumo

|`align-right`
|Aligns the field value to the right side.
|Aura, Lumo

|`helper-above-field`
|Renders the helper text above the field, below the label.
|Aura, Lumo
|===

== Attributes

The following attributes are specific to `timePicker`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[autoOpen]]`autoOpen`
|Defines whether the overlay opens when the user interacts with the component.
|—

|[[max]]`max`
|Specifies the latest time that can be selected.
|—

|[[min]]`min`
|Specifies the earliest time that can be selected.
|—
|===

The following shared attributes are supported by `timePicker`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clearButtonVisible[clearButtonVisible] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#step[step] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `timePicker`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[ClientValidatedEvent]]`ClientValidatedEvent`
|Fired after client-side validation changes the component's validity.

|[[InvalidChangeEvent]]`InvalidChangeEvent`
|Fired when the component's invalid state changes.

|[[validator]]`validator`
|Validates the component value.
|===

The following shared handlers are supported by `timePicker`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Elements

A `timePicker` can include xref:vc/components/tooltip.adoc[tooltip], xref:vc/miscellaneous/validator.adoc[validator], and xref:vc/miscellaneous/prefix-suffix.adoc[prefix] as its nested elements.

== See Also

* https://vaadin.com/docs/v25/components/time-picker[Vaadin Time Picker documentation^]
