= timePicker
:page-aliases: vcl/components/time-field.adoc

`timePicker` позволяет пользователям вводить или выбирать время.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`timePicker`

|Java-класс
|`TypedTimePicker`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/time-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Время можно ввести с клавиатуры или выбрать из всплывающего списка. Список открывается при нажатии на поле или кнопку с часами.

Пример определения `timePicker` типа `localTime` с надписью:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/timepicker/simple/time-picker-simple.xml[tags=basics]
----

== Типы данных

`timePicker` поддерживает основные типы данных для хранения времени:

* `localTime`
* `offsetTime`
* `time`

Для изменения типа используйте атрибут xref:vc/common-attributes.adoc#datatype[datatype].

[[data-binding]]
== `timePicker` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/time-picker-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибуты `dataContainer` и `property`, чтобы связать `timePicker` с атрибутом сущности. Контейнер данных предоставляет экземпляр сущности, а `property` указывает редактируемый атрибут.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/timepicker/dataaware/time-picker-dataaware.xml[tags=data;data-binding]
----

[[step]]
== Шаг интервала

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/time-picker-custom-range" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

По умолчанию интервал между значениями во всплывающем списке равен одному часу. Чтобы изменить его, задайте атрибут xref:vc/common-attributes.adoc#step[step] в XML или программно.

Пример установки атрибута `step` в XML дескрипторе экрана:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/timepicker/customrange/time-picker-custom-range.xml[tags=step]
----
<<suffix,suffix>> `m` обозначает минуты.

[[suffix]]
Атрибут `step` поддерживает гибкую настройку интервалов с использованием суффиксов единиц времени.

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/component/timepicker/time-picker-view.xml[tags=step-unit]
----
<1> Интервал 2 часа.
<2> Интервал 1600 секунд (26м 40с).
<3> Интервал 20 минут.

Аналогично можно настроить в контроллере экрана:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/timepicker/TimePickerView.java[tags=timePicker;onInit;step]
----

Шаг должен равномерно делить час или день. Например, "15 минут", "30 минут" и "2 часа" - допустимые значения, а "42 минуты" - нет.

NOTE: Для шагов менее 15 минут выпадающий список не отображается, чтобы избежать непрактичного количества вариантов.

// == Time Format
// //todo: make changes upon completing jmix#858 ticket
// The default date and time format in the application is defined by the xref:data-model:datatype.adoc#localized-format-strings[строки локализованного формата]. To use a different format, add your own format strings to the message bundle.

== Ограничение временного диапазона

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/time-picker-custom-range" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Чтобы ограничить ввод диапазоном времени, задайте минимальное и максимальное значения с помощью атрибутов <<max,max>> и <<min,min>>.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/timepicker/customrange/TimePickerCustomRange.java[tags=time-range]
----

Для более точного ограничения диапазона используйте <<validator,validator>>.

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/time-picker-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`small`
|Уменьшает размер компонента.
|Aura, Lumo

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`filled`
|Применяет стиль с заливкой фона.
|Aura
|===

== Атрибуты

`timePicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[autoOpen]]`autoOpen`
|Определяет, открывается ли наложение, когда пользователь взаимодействует с компонентом.
|—

|[[max]]`max`
|Указывает самое позднее время, которое можно выбрать.
|—

|[[min]]`min`
|Указывает самое раннее время, которое можно выбрать.
|—
|===

`timePicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#allowedCharPattern[allowedCharPattern] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#clearButtonVisible[clearButtonVisible] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#datatype[datatype] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#overlayClass[overlayClass] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#step[step] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`timePicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[ClientValidatedEvent]]`ClientValidatedEvent`
|Возникает после изменения состояния допустимости компонента при проверке на стороне клиента.

|[[InvalidChangeEvent]]`InvalidChangeEvent`
|Возникает при изменении состояния недопустимости компонента.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`timePicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#TypedValueChangeEvent[TypedValueChangeEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `timePicker` может содержать следующие вложенные элементы: xref:vc/components/tooltip.adoc[tooltip], xref:vc/miscellaneous/validator.adoc[validator], и xref:vc/miscellaneous/prefix-suffix.adoc[prefix].

== Смотрите также

* https://vaadin.com/docs/v25/components/time-picker[Документация Vaadin: Time Picker^]
