= tooltip

`tooltip` отображает дополнительную информацию, когда пользователи наводят курсор мыши на компонент или фокусируют его.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`tooltip`

|Java-класс
|`Tooltip`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/context-help-tooltip" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`tooltip` — вложенный элемент практически всех компонентов и макетов.

TIP: Чтобы добавить вложенный `tooltip` в Jmix Studio, выберите элемент пользовательского интерфейса в XML-дескрипторе экрана или на панели структуры *Jmix UI* и нажмите кнопку xref:studio:screen-designer.adoc#component-inspector-add-button[Add]*->Tooltip* на панели инспектора *Jmix UI*.

Пример определения xref:flow-ui:vc/components/textField.adoc[textField] с `tooltip`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/context-help-tooltip.xml[tags=basics]
----

[[programmatic-tooltip]]
== Программное определение

Компонент `tooltip` можно определить программно в коде вашего приложения. Вот пример того, как вы можете программно определить и использовать всплывающую подсказку для компонента `textField`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/tooltip/TooltipView.java[tags=programmaticField;onInit;set-programmatic]
----

[[about-positioning]]
== Настройка расположения

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/context-help-tooltip" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`tooltip` по умолчанию позиционируется относительно целевого компонента, к которому он прикреплен. Он автоматически вычисляет наилучшее место для появления всплывающей подсказки, принимая во внимание доступное пространство на экране и избегая перекрытия с другими элементами.

Атрибут `position` напрямую влияет на расположение всплывающей подсказки на экране, позволяя вам управлять тем, где она отображается. Атрибут `position` принимает значения из перечисления `TooltipPosition`.

Вы можете задать атрибут `position` с помощью метода `setPosition()` в вашем коде:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/ContextHelpTooltipSample.java[tags=position-field;position-init;position-handler;position-items]
----

В XML-дескрипторе экрана вы можете указать атрибут `position`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/context-help-tooltip.xml[tags=position]
----

[[configuring-delays]]
== Управление задержками

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/context-help-tooltip" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`tooltip` позволяет настроить задержки появления и исчезновения всплывающей подсказки.

[[about-focus-delay]]
*Задержка фокусировки*

Атрибут `focusDelay` управляет задержкой, в миллисекундах, перед появлением всплывающей подсказки, когда курсор мыши наводится на компонент с элементом `tooltip`.

В этом примере всплывающая подсказка появится после 500-миллисекундной задержки, когда курсор мыши наводится на текстовое поле:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/ContextHelpTooltipSample.java[tags=focus-delay]
----

[[about-hide-delay]]
*Задержка скрытия*

Атрибут `hideDelay` управляет задержкой, в миллисекундах, перед скрытием всплывающей подсказки, когда курсор мыши уходит с компонента с элементом `tooltip`.

В этом примере всплывающая подсказка будет оставаться видимой в течение 1 секунды после того, как курсор мыши уйдет с текстового поля, прежде чем исчезнуть:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/ContextHelpTooltipSample.java[tags=hide-delay]
----

[[about-hover-delay]]
*Задержка наведения*

Атрибут `hoverDelay` управляет задержкой, в миллисекундах, перед появлением всплывающей подсказки, когда курсор мыши наводится на компонент с элементом `tooltip`.

В этом примере всплывающая подсказка появится после 500-миллисекундной задержки, когда курсор мыши наводится на текстовое поле:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/ContextHelpTooltipSample.java[tags=hover-delay]
----

[[triggering-manually]]
== Принудительное отображение

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/context-help-tooltip" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Вы можете настроить всплывающие подсказки так, чтобы они отображались программно, то есть они не будут отображаться при наведении или фокусировке, а только при запуске вашего кода. Это особенно полезно, когда:

* Вам необходимо отобразить всплывающую подсказку на основе определённых условий или взаимодействий пользователя.
* Содержимое всплывающей подсказки должно генерироваться или обновляться динамически.

В XML-дескрипторе экрана установите атрибут `manual` в значение `true`. Это означает, что всплывающая подсказка не будет отображаться автоматически и требует ручного управления.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/context-help-tooltip.xml[tags=manual]
----

Затем настройте всплывающую подсказку в контроллере экрана.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/contexthelp/tooltip/ContextHelpTooltipSample.java[tags=manual-field;ui-components;init;manual-init;helper-button]
----

Атрибут `opened` определяет, видна ли всплывающая подсказка в данный момент. Это логическое значение: `true` указывает, что всплывающая подсказка открыта, а `false` — что она закрыта.

NOTE: Хотя `opened` можно задавать вручную, обычно фреймворк управляет им на основе наведения указателя мыши и получения фокуса. Используйте этот атрибут, если всплывающую подсказку требуется открывать или закрывать программно.

== Атрибуты

Ниже представлены атрибуты, специфичные для `tooltip`:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[focusDelay]]`focusDelay`
|Определяет задержку в миллисекундах перед открытием всплывающей подсказки при фокусе клавиатуры, если не в ручном режиме. См. <<about-focus-delay,Задержка фокусировки>>.
|`0`

|[[hideDelay]]`hideDelay`
|Определяет задержку в миллисекундах перед закрытием всплывающей подсказки при потере наведения, если не в ручном режиме. При размытии всплывающая подсказка немедленно закрывается. См. <<about-hide-delay,Скрыть задержку>>.
|`0`

|[[hoverDelay]]`hoverDelay`
|Определяет задержку в миллисекундах перед открытием всплывающей подсказки при наведении курсора, если не в ручном режиме. См. <<about-hover-delay,Задержка при наведении>>.
|`0`

|[[manual]]`manual`
|При `true` подсказка управляется программно, а не реагирует на события фокуса и мыши. См. <<triggering-manually,Запуск вручную>>.
|`false`

|[[opened]]`opened`
|При `true` всплывающая подсказка открывается программно. Работает только в том случае, если для `manual` установлено значение `true`. См. <<triggering-manually,Запуск вручную>>.
|`false`

|[[position]]`position`
|Определяет положение всплывающей подсказки относительно цели. См. <<about-positioning,Позиционирование>>.
|—

|[[text]]`text`
|Определяет строку, используемую в качестве содержимого всплывающей подсказки.
|—
|===

== Смотрите также

* https://vaadin.com/docs/v25/components/tooltip[Документация Vaadin: Tooltip^]
