= twinColumn
:page-aliases: vcl/components/twin-column.adoc

`twinColumn` позволяет пользователям выбирать элементы, перемещая их между доступными и выбранными столбцами.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`twinColumn`

|Java-класс
|`TwinColumn`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент размещает два столбца рядом. В левом находятся доступные для выбора элементы, а в правом — выбранные. Пользователь может выбрать один или несколько элементов и перемещать их между столбцами с помощью кнопок, добавляя в выбор или удаляя из него.

Для создания компонента используйте XML-элемент `twinColumn` и задайте его атрибут `itemsContainer`, указав xref:data/collection-container.adoc[контейнер коллекции]. Элементы из этого контейнера будут отображаться в колонках.

Пример создания базового компонента `twinColumn`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/twincolumn/dataaware/twin-column-dataaware.xml[tags=data;facets;basics]
----

[[data-binding]]
== `twinColumn` связанный с данными

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Привязка данных означает связывание визуального компонента с xref:data/data-containers.adoc[контейнером данных]. Изменения в компоненте или соответствующем контейнере могут вызывать взаимные обновления. Подробнее смотрите в разделе xref:data/data-examples.adoc[].

Для создания `twinColumn` с привязкой к данным используйте атрибуты xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property]. Атрибут `itemsContainer` используется для создания списка элементов.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/twincolumn/dataaware/twin-column-dataaware.xml[tags=data;facets;basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/twincolumn/dataaware/TwinColumnDataawareSample.java[tags=data-binding]
----

[[multi-select]]
== Множественный выбор

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент `twinColumn` всегда работает в режиме множественного выбора: пользователь может выбрать и переместить несколько элементов. Чтобы разрешить перемещение всех элементов сразу, задайте атрибут `selectAllButtonsVisible`:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/twincolumn/simple/TwinColumnSimpleSample.java[tags=twin-column-field;select-all-buttons]
----

[[column-labels]]
== Надписи колонок

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Подписи столбцов задаются атрибутами `itemsColumnLabel` и `selectedItemsColumnLabel`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/twincolumn/simple/twin-column-simple.xml[tags=column-labels]
----

[[items-order]]
== Порядок элементов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

По умолчанию элементы не сохраняют исходное положение в списке: после перемещения в другой столбец элемент добавляется в конец. Чтобы всегда сохранять исходный порядок, задайте `reorderable = "true"`.

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/twincolumn/simple/TwinColumnSimpleSample.java[tags=twin-column-field;reorderable]
----

[[custom-items]]
== Пользовательские предметы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-custom-items" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Заполнить `twinColumn` программно можно из списка, отображения «значение — подпись» или перечисления.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/twincolumn/customitems/twin-column-custom-items.xml[tags=custom-items]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/twincolumn/customitems/TwinColumnCustomItemsSample.java[tags=custom-items]
----

[[variants]]
== Варианты темы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/twin-column-theme-variant" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`no-border`
|Удаляет внешнюю границу компонента.
|Aura, Lumo

|`no-row-border`
|Удаляет разделители между строками.
|Lumo

|`checkmarks`
|Использует галочки для обозначения выбранных элементов вместо изменения цвета фона строки.
|Lumo

|`no-spaces-between-actions`
|Удаляет промежутки между кнопками действий.
|Aura, Lumo
|===

TIP: Вы можете комбинировать несколько тем, перечисляя их через пробел, чтобы изменить несколько аспектов внешнего вида одновременно.

== Атрибуты

`twinColumn` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[itemsColumnLabel]]`itemsColumnLabel`
|Устанавливает метку столбца элементов. См. <<column-labels,Метки столбцов>>.
|—

|[[itemsContainer]]`itemsContainer`
|Задаёт контейнер элементов. See <<basics,Basics>>.
|—

|[[reorderable]]`reorderable`
|Определяет, могут ли пользователи изменять порядок элементов в компоненте. См. <<items-order,Заказ товаров>>.
|—

|[[selectAllButtonsVisible]]`selectAllButtonsVisible`
|Определяет, отображаются ли кнопки выбора и очистки всех элементов. См. <<multi-select,Мультивыбор>>.
|—

|[[selectedItemsColumnLabel]]`selectedItemsColumnLabel`
|Устанавливает метку столбца выбранных элементов. См. <<column-labels,Метки столбцов>>.
|—
|===

`twinColumn` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`twinColumn` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`twinColumn` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

== Элементы

Компонент `twinColumn` может содержать следующие вложенные элементы: xref:vc/miscellaneous/validator.adoc[validator].
