= userMenu

`userMenu` отображает текущего пользователя и открывает меню действий, связанных с пользователем.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`userMenu`

|Java-класс
|`UserMenu`
|===

[[basics]]
== Основы

Основная кнопка отображает компоновку, представляющую текущего пользователя.
Пользователь нажимает эту кнопку, чтобы открыть выпадающее меню.

Выпадающее меню содержит список действий, каждое из которых представлено кликабельным элементом или подменю.

Вот пример определения `userMenu` с отрисовкой кнопок по умолчанию и несколькими пунктами меню:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-basic]
----

[[elements]]

[[renderers]]
== Рендереры

Фреймворк позволяет настраивать содержимое кнопки и необязательного заголовка меню.

[[button-renderer]]
== Рендерер кнопки

Вы можете установить средство рендеринга кнопок либо с помощью метода `setButtonRenderer()`, либо с помощью аннотации `@Install`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=import-ui-components;import-file-storage;import-component;import-autowired;import-user-details;import-user;import-avatar;import-avatar-variant;import-span;import-div;import-file-ref;import-download-handler;import-download-response;some-code;user-menu-renderer-injects;user-menu-button-renderer;user-menu-renderer-helpers]
----
<1> Внутренние отступы `HorizontalLayout` по умолчанию слишком велики, поэтому задаём нужные отступы с помощью стилей.
<2> Экземпляр компонента `Avatar` создаётся с помощью фабрики `UiComponents`.
<3> Полное имя пользователя передаётся в `Avatar`, чтобы при отсутствии изображения компонент сформировал инициалы.
<4> `avatar` по умолчанию может получать фокус, но Java API не позволяет это отключить. Удаляем атрибут `tabindex`, чтобы фокус мог получать только компонент `userMenu`.
<5> `DownloadHandler` передаёт изображение аватара из файлового хранилища по ссылке, сохранённой в атрибуте `picture` сущности `User`.

[[header-renderer]]
== Рендерер заголовка

Средство визуализации заголовка определяет содержимое, отображаемое в верхней части меню. Вы можете установить средство визуализации заголовка, используя метод `setHeaderRenderer()` или аннотацию `@Install`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=import-ui-components;import-file-storage;import-component;import-autowired;import-user-details;import-user;import-avatar;import-avatar-variant;import-span;import-div;import-file-ref;import-download-handler;import-download-response;some-code;user-menu-renderer-injects;user-menu-header-renderer;user-menu-renderer-helpers]
----
<1> Положение компонентов задаётся с помощью стилей.
<2> Экземпляр компонента `Avatar` создаётся с помощью фабрики `UiComponents`.
<3> Полное имя пользователя передаётся в `Avatar`, чтобы при отсутствии изображения компонент сформировал инициалы.
<4> `avatar` по умолчанию может получать фокус, но Java API не позволяет это отключить. Удаляем атрибут `tabindex`, чтобы фокус мог получать только компонент `userMenu`.
<5> `DownloadHandler` передаёт изображение аватара из файлового хранилища по ссылке, сохранённой в атрибуте `picture` сущности `User`.

[source,css,indent=0]
----
include::example$/onboarding/frontend/themes/onboarding/vc/user-menu.css[]
----

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`tertiary`
|Удаляет фон с главной кнопки.
|Aura, Lumo

|`non-checkable`
|Удаляет область, используемую для отображения флажка.
|Aura, Lumo
|===

Тему `non-checkable` можно применить к компоненту `userMenu` или к отдельным пунктам меню.

NOTE: Если подменю содержит отмечаемые пункты, примените `non-checkable` отдельно к каждому пункту первого уровня.

[[attributes]]
== Атрибуты

`userMenu` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[openOnHover]]`openOnHover`
|Если атрибут `openOnHover` равен `true`, раскрывающийся список элементов открывается автоматически при наведении фокуса на поле с помощью мыши или касания.
|`false`
|===

`userMenu` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible]

== Обработчики

`userMenu` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[UserChangedEvent]]`UserChangedEvent`
|`io.jmix.flowui.kit.component.usermenu.JmixUserMenu.UserChangedEvent` запускается при изменении пользователя, связанного с компонентом пользовательского меню.

|[[buttonRenderer]]`buttonRenderer`
|Устанавливает `Renderer`, отвечающий за отображение содержимого кнопки на основе текущего пользователя. См. <<button-renderer,Рендерер кнопок>>.

|[[headerRenderer]]`headerRenderer`
|Задаёт `Renderer`, который формирует содержимое заголовка для текущего пользователя. См. <<header-renderer,Рендерер заголовка>>.
|===

`userMenu` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Элементы

`userMenu`, определённый в XML-дескрипторе, может содержать вложенные элементы:

[[actionItem]]
=== actionItem

Элемент `actionItem` создаёт связь между пунктом пользовательского меню и конкретным xref:actions/declarative-actions.adoc[действие], который должен быть выполнен при щелчке по этому пункту.

Вы можете либо определить действие декларативно, либо использовать атрибут `ref`, чтобы сослаться на `id` уже определённого `action`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=actions;layout;user-menu-action]
----

<1> Декларативно определённое действие.
<2> Ссылка на существующее действие.

Когда пользователь нажимает `actionItem` в выпадающем меню, Jmix автоматически вызывает `action`.
Чтобы реализовать его логику, можно сгенерировать метод-обработчик `ActionPerformedEvent`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=notifications-bean;user-menu-action]
----

Фреймворк предоставляет предопределённые xref:actions/user-menu-actions.adoc[].

[[componentItem]]
=== componentItem

Элемент `componentItem` позволяет определить пользовательское внутреннее содержимое для `userMenu`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-component]
----

С помощью Jmix Studio можно сгенерировать заготовку обработчика `UserMenuItem.HasClickListener.ClickEvent` для `componentItem`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=notifications-bean;user-menu-component]
----

[[textItem]]
=== textItem

Элемент `textItem` содержит текст и значок.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-text]
----

С помощью Jmix Studio можно сгенерировать заготовку обработчика `UserMenuItem.HasClickListener.ClickEvent` для `textItem`.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=notifications-bean;user-menu-text]
----

[[viewItem]]
=== viewItem

Элемент `viewItem` позволяет открыть определённый экран.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-view]
----

<1> Открывает экран с указанным идентификатором.
<2> Открывает экран указанного класса в режиме `DIALOG`.

[[separator]]
=== separator

Элемент `separator` используется для визуального разделения элементов в выпадающем меню.

Разделители автоматически скрываются при следующих условиях:

. Несколько разделителей идут подряд. В этом случае видимым остается только один разделитель.
. Разделитель является первым дочерним элементом, а рендерер заголовка не определен.
. Разделитель является последним дочерним элементом.

[[nested-items]]
=== Вложенные элементы

Элементы `textItem` и `componentItem` поддерживают вложенные элементы, что позволяет определить иерархическое меню.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-nested]
----
