= userMenu

`userMenu` displays the current user and opens a menu of user-related actions.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`userMenu`

|Java Class
|`UserMenu`
|===

[[basics]]
== Basics

The main button displays a layout that represents a current user.
Users click this button to access the dropdown menu.

The dropdown menu contains a list of actions, each represented by a clickable item or submenu.

Here's an example of defining a `userMenu` with default button renderer and several menu items:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-basic]
----

[[elements]]

[[renderers]]
== Renderers

The framework provides flexibility in customizing the content of the button and the optional menu header.

[[button-renderer]]
== Custom Button Renderer

You can set a button renderer either using the `setButtonRenderer()` method or the `@Install` annotation.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=import-ui-components;import-file-storage;import-component;import-autowired;import-user-details;import-user;import-avatar;import-avatar-variant;import-span;import-div;import-file-ref;import-download-handler;import-download-response;some-code;user-menu-renderer-injects;user-menu-button-renderer;user-menu-renderer-helpers]
----
<1> Default `HorizontalLayout` padding is too big, we add padding using styles.
<2> The `Avatar` component instance is created using the `UiComponents` factory.
<3> The full user name is passed to `Avatar` to generate fallback initials when no image is available.
<4> `avatar` is focusable by default, but it doesn't provide a Java API to disable focus. Remove the tab index, so only the `userMenu` component can receive focus.
<5> `DownloadHandler` streams the avatar image from file storage by the reference stored in the `picture` attribute of the `User` entity.

[[header-renderer]]
== Custom Header Renderer

Header renderer defines the content displayed at the top of the menu. You can set a header renderer using either the `setHeaderRenderer()` method or the `@Install` annotation.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=import-ui-components;import-file-storage;import-component;import-autowired;import-user-details;import-user;import-avatar;import-avatar-variant;import-span;import-div;import-file-ref;import-download-handler;import-download-response;some-code;user-menu-renderer-injects;user-menu-header-renderer;user-menu-renderer-helpers]
----
<1> Component positions are defined using styles.
<2> The `Avatar` component instance is created using the `UiComponents` factory.
<3> The full user name is passed to `Avatar` to generate fallback initials when no image is available.
<4> `avatar` is focusable by default, but it doesn't provide a Java API to disable focus. Remove the tab index, so only the `userMenu` component can receive focus.
<5> `DownloadHandler` streams the avatar image from file storage by the reference stored in the `picture` attribute of the `User` entity.

[source,css,indent=0]
----
include::example$/onboarding/frontend/themes/onboarding/vc/user-menu.css[]
----

[[variants]]
== Theme Variants

Use the xref:vc/common-attributes.adoc#themeNames[themeNames] attribute to apply one or more theme variants.

[cols="1,4,1", options="header"]
|===
|Variant
|Description
|Supported By

|`tertiary`
|Removes the background from the main button.
|Aura, Lumo

|`non-checkable`
|Removes the area used to display a check mark.
|Aura, Lumo
|===

The `non-checkable` theme can be applied to both the `userMenu` component and individual menu items.

NOTE: If a submenu contains checkable items, apply `non-checkable` to each first-level item individually.

[[attributes]]
== Attributes

The following attributes are specific to `userMenu`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[openOnHover]]`openOnHover`
|If the `openOnHover` attribute is `true`, the drop-down list of items is opened automatically when the field is focused using a mouse or touch.
|`false`

|[[overlayClass]]`overlayClass`
|Adds CSS class names to the component overlay.
|—
|===

The following shared attributes are supported by `userMenu`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible]

== Handlers

The following handlers are specific to `userMenu`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[UserChangedEvent]]`UserChangedEvent`
|`io.jmix.flowui.kit.component.usermenu.JmixUserMenu.UserChangedEvent` is fired when the user associated with the user menu component changes.

|[[buttonRenderer]]`buttonRenderer`
|Sets the `Renderer` responsible to render the button's content based on the current user. See <<button-renderer,Button Renderer>>.

|[[headerRenderer]]`headerRenderer`
|Sets the `Renderer` responsible to render the header's content based on the current user. See <<header-renderer,Header Renderer>>.
|===

The following shared handlers are supported by `userMenu`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Elements

`userMenu` defined in the XML descriptor can contain nested elements:

[[actionItem]]
=== actionItem

The `actionItem` element creates a link between a user menu item and a specific xref:actions/declarative-actions.adoc[action] that should be executed when that item is clicked.

You can either define an action declaratively or use the `ref` attribute to point to the `id` of an already defined `action`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=actions;layout;user-menu-action]
----

<1> Declaratively defined action.
<2> Reference to the existing action.

When a user clicks on an `actionItem` in the dropdown, Jmix automatically triggers the `action`.
You can generate an `ActionPerformedEvent` handler method for an action to implement its logic:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=notifications-bean;user-menu-action]
----

Framework provides predefined xref:actions/user-menu-actions.adoc[].

[[componentItem]]
=== componentItem

The `componentItem` element allows you to define custom inner content for `userMenu`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-component]
----

You can generate a `UserMenuItem.HasClickListener.ClickEvent` handler stub for `componentItem` using Jmix Studio.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=notifications-bean;user-menu-component]
----

[[textItem]]
=== textItem

The `textItem` element holds text and icon.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-text]
----

You can generate a `UserMenuItem.HasClickListener.ClickEvent` handler stub for `textItem` using Jmix Studio.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/usermenu/UserMenuView.java[tags=notifications-bean;user-menu-text]
----

[[viewItem]]
=== viewItem

The `viewItem` element allows you to open a specific view.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-view]
----

<1> Opens a view with the specified id.
<2> Opens a view with the specified class in the `DIALOG` mode.

[[separator]]
=== separator

The `separator` element is used to visually separate items in the dropdown menu.

Separators automatically hide if they meet the following conditions:

. Several separators go one by one. In this case only one separator remains visible.
. Separator is the first child and the header renderer is not defined.
. Separator is the last child.

[[nested-items]]
=== Nested Items

The `textItem` and `componentItem` elements support nested items, which allows you to define a hierarchical menu.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/usermenu/user-menu-view.xml[tags=user-menu-nested]
----
