= valuePicker
:page-aliases: vcl/components/value-picker.adoc

`valuePicker` отображает значение любого типа. Он состоит из текстового поля и набора кнопок, определяемых действиями.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`valuePicker`

|Java-класс
|`JmixValuePicker`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонент чаще всего используют для выбора сложных значений, когда выбор требует выполнения действия.

Пример определения `valuePicker` c `label` и двумя действиями:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/dataaware/value-picker-dataaware.xml[tags=basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/valuepicker/dataaware/ValuePickerDataawareSample.java[tags=basics-container;basics-data;basics-init;basics-actions]
----

Чтобы создать `valuePicker`, связанный с данными, используйте атрибуты xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property]:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/dataaware/value-picker-dataaware.xml[tags=data;basics]
----

Контейнер экземпляра `customerDc` хранит сущность `Customer`. Компонент связан с её атрибутом `name`.

[[actions]]
== Действия

Вы можете определить пользовательские и предопределённые действия для `valuePicker`, которые отображаются в виде кнопок справа. Это можно сделать либо в XML-дескрипторе, используя вложенный элемент `actions`, либо программно в контроллере, используя метод `addAction()`.

[TIP]
====
Чтобы добавить действие в Jmix Studio, выберите компонент в XML-дескрипторе экрана или в панели структуры *Jmix UI* и нажмите кнопку xref:studio:screen-designer.adoc#add-picker-action[Add] в панели инспектора *Jmix UI*.
====

[[predefined-action]]
== Предопределенные

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

[[clear-action]]
Фреймворк предоставляет только одно предопределённое действие - `value_clear`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/simple/value-picker-simple.xml[tags=actions]
----

Используйте атрибуты `type` и `id` для объявления предопределённого действия в XML.

Используйте `addAction()` для установки предопределённого действия программно:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/valuepicker/ValuePickerView.java[tags=loginValuePicker;actions;onInit;addPredefinedAction]
----

[[custom-actions]]
== Пользовательские

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Чтобы определить пользовательское действие в XML, добавьте вложенный элемент `actions`. Для `action` укажите атрибуты `id` и `icon`:

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/valuepicker/simple/value-picker-simple.xml[tags=actions]
----

Затем реализуйте пользовательскую логику в контроллере экрана, подписавшись на событие `ActionPerformedEvent`:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/valuepicker/simple/ValuePickerSimpleSample.java[tags=custom-action-field;custom-action-handler;generate-value]
----

[[custom-value-entry]]
== Обработка пользовательского ввода

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/value-picker-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`valuePicker` позволяет настроить его для принятия пользовательских значений.

Когда атрибут <<allowCustomValue,allowCustomValue>> установлен в `true`, пользователи могут вводить произвольные строковые значения. Это приводит к событию <<CustomValueSetEvent,CustomValueSetEvent>>.

NOTE: `valuePicker` автоматически не обрабатывает строку с пользовательским значением. Используйте событие `CustomValueSetEvent`, чтобы определить, как следует обработать введённое пользователем значение.

Пример обработки пользовательского ввода:

[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/valuepicker/simple/ValuePickerSimpleSample.java[tags=custom-value-field;custom-value-handler]
----

[[about-formatter]]
== Форматер

Добавляет экземпляр xref:vc/miscellaneous/formatter.adoc[форматера] к компоненту.

В примере ниже мы покажем использование форматера для `vPicker`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/valuepicker/ValuePickerView.java[tags=formatter]
----

Чтобы добавить форматер программно, используйте метод компонента `setFormatter()`.

[[validation]]
== Валидация

Чтобы проверить значения, введённые в компонент `valuePicker` вы можете использовать xref:vc/miscellaneous/validator.adoc[валидатор] в элементе `validators`.

Доступны следующие предопределённые валидаторы для `valuePicker`:

[cols="1h,6", grid=none]
|===
|XML-элемент
|`validators`
|Предопределённые валидаторы
|xref:vc/miscellaneous/validator.adoc#custom-validator[custom] - xref:vc/miscellaneous/validator.adoc#DecimalMaxValidator[decimalMax] - xref:vc/miscellaneous/validator.adoc#DecimalMinValidator[decimalMin] - xref:vc/miscellaneous/validator.adoc#DigitsValidator[digits] - xref:vc/miscellaneous/validator.adoc#DoubleMaxValidator[doubleMax] - xref:vc/miscellaneous/validator.adoc#DoubleMinValidator[doubleMin] - xref:vc/miscellaneous/validator.adoc#EmailValidator[email] - xref:vc/miscellaneous/validator.adoc#MaxValidator[max] - xref:vc/miscellaneous/validator.adoc#MinValidator[min] - xref:vc/miscellaneous/validator.adoc#NegativeOrZeroValidator[negativeOrZero] - xref:vc/miscellaneous/validator.adoc#NegativeValidator[negative] - xref:vc/miscellaneous/validator.adoc#NotBlankValidator[notBlank] - xref:vc/miscellaneous/validator.adoc#NotEmptyValidator[notEmpty] - xref:vc/miscellaneous/validator.adoc#NotNullValidator[notNull] - xref:vc/miscellaneous/validator.adoc#PositiveOrZeroValidator[positiveOrZero] - xref:vc/miscellaneous/validator.adoc#PositiveValidator[positive] - xref:vc/miscellaneous/validator.adoc#RegexpValidator[regexp] - xref:vc/miscellaneous/validator.adoc#SizeValidator[size]
|===

[[variants]]
== Варианты темы

Используйте атрибут xref:vc/common-attributes.adoc#themeNames[themeNames], чтобы применить один или несколько вариантов темы.

[cols="1,4,1", options="header"]
|===
|Вариант
|Описание
|Поддерживается в

|`align-left`
|Выравнивает значение поля по левому краю.
|Aura, Lumo

|`align-center`
|Выравнивает значение поля по центру.
|Aura, Lumo

|`align-right`
|Выравнивает значение поля по правому краю.
|Aura, Lumo

|`align-start`
|Выравнивает значение поля по начальной стороне с учетом текущего направления текста.
|Aura

|`align-end`
|Выравнивает значение поля по конечной стороне с учетом текущего направления текста.
|Aura

|`helper-above-field`
|Размещает вспомогательный текст над полем, под меткой.
|Aura, Lumo

|`small`
|Уменьшает размер компонента.
|Aura, Lumo
|===

== Атрибуты

`valuePicker` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[allowCustomValue]]`allowCustomValue`
|По умолчанию пользователи не могут вручную вводить значения в поле `valuePicker`. Если вы установите для атрибута `allowCustomValue` значение `true`, вы включите ручной ввод. Имейте в виду, что введённое значение не будет автоматически установлено в модели данных. Для обработки пользовательского ввода используйте <<CustomValueSetEvent,CustomValueSetEvent>>. См. <<custom-value-entry,Ввод пользовательского значения>>.
|`false`
|===

`valuePicker` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#autofocus[autofocus] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#errorMessage[errorMessage] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#helperText[helperText] -
xref:vc/common-attributes.adoc#label[label] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#placeholder[placeholder] -
xref:vc/common-attributes.adoc#property[property] -
xref:vc/common-attributes.adoc#readOnly[readOnly] -
xref:vc/common-attributes.adoc#required[required] -
xref:vc/common-attributes.adoc#requiredMessage[requiredMessage] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`valuePicker` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[CustomValueSetEvent]]`CustomValueSetEvent`
|`io.jmix.flowui.kit.component.valuepicker.CustomValueSetEvent` запускается, когда пользователь вводит непустое значение. Чтобы включить ввод пользовательских значений, установите для атрибута <<allowCustomValue,allowCustomValue>> значение `true`. См. <<custom-value-entry,Ввод пользовательского значения>>.

|[[formatter]]`formatter`
|Добавляет экземпляр xref:vc/miscellaneous/formatter.adoc[форматтер] к компоненту. См. <<about-formatter,форматтер>>.

|[[validator]]`validator`
|Проверяет значение компонента.
|===

`valuePicker` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#ComponentValueChangeEvent[ComponentValueChangeEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent] -
xref:vc/common-handlers.adoc#statusChangeHandler[statusChangeHandler]

== Элементы

Компонент `valuePicker` может содержать следующие вложенные элементы: <<actions,actions>>, xref:vc/miscellaneous/formatter.adoc[formatter], xref:vc/miscellaneous/prefix-suffix.adoc[prefix], xref:vc/miscellaneous/prefix-suffix.adoc[suffix], xref:vc/components/tooltip.adoc[tooltip], и <<validation,validator>>.
