= virtualList

`virtualList` эффективно отображает списки с настраиваемым содержимым элементов, отображая только видимые элементы.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML-элемент
|`virtualList`

|Java-класс
|`JmixVirtualList`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/virtual-list-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`virtualList` подключен к xref:flow-ui:data/data-containers.adoc[контейнер данных]. По умолчанию отображается xref:data-model:entities.adoc#instance-name[имя экземпляра] сущности в контейнере. Используя обработчик <<Renderer,renderer>>, вы можете отображать пользовательский контент.

[[fragment-renderer]]
Альтернативно можно рендерить элементы с помощью вложенного элемента `fragmentRenderer`. Подробнее смотрите раздел xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Рендерер фрагментов].

Ниже приведен пример использования `virtualList` в списке вместо `dataGrid`:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/virtuallist/simple/virtual-list-simple.xml[tags=data;facets;basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/simple/VirtualListSimpleSample.java[tags=renderer]
----

Обратите внимание, что элементы в `virtualList` нельзя выделять или перемещаться по ним с помощью клавиатуры. Стандартные xref:flow-ui:actions/list-actions.adoc[действия списка] не работают с `virtualList`. При необходимости определите собственные действия для CRUD-операций.

[[custom-items]]
== Пользовательский рендерер предметов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/virtual-list-custom-items" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонентный рендерер может создавать пользовательское содержимое для каждого элемента списка. В примере каждое значение перечисления отображается с подписью и кнопкой-значком.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/virtuallist/customitems/virtual-list-custom-items.xml[tags=custom-items]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/customitems/VirtualListCustomItemsSample.java[tags=custom-items]
----

[[inline-editor]]
== Встроенный редактор

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/virtual-list-inline-editor" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Компонентный рендерер, контейнер данных и диалоговые окна деталей позволяют создавать и редактировать элементы списка без отдельной таблицы.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/virtual-list-inline-editor.xml[tags=data;inline-editor]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditorSample.java[tags=inline-editor-services;inline-editor-data;inline-editor-renderer;inline-editor-add]
----

== Атрибуты

`virtualList` имеет следующие уникальные атрибуты:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию

|[[itemsContainer]]`itemsContainer`
|Задаёт имя контейнера данных со списком элементов.
|—

|[[itemsEnum]]`itemsEnum`
|Определяет класс xref:data-model:enumerations.adoc[enumeration] для создания списка элементов.
|—
|===

`virtualList` имеет следующие общие атрибуты:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Обработчики

`virtualList` имеет следующие уникальные обработчики:

[cols="2,5", options="header"]
|===
|Имя
|Описание

|[[Renderer]]`Renderer`
|Пользовательский рендерер элементов списка можно установить только в контроллере экрана с помощью Java-кода.

|[[ValueProvider]]`ValueProvider`
|Если вы хотите отображать простой текст, можно указать средство визуализации с помощью `ValueProvider`.
|===

`virtualList` имеет следующие общие обработчики:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== Смотрите также

* https://vaadin.com/docs/v25/components/virtual-list[Документация Vaadin: Virtual List^]
