= virtualList

`virtualList` efficiently displays lists with custom item content by rendering only visible items.

[cols="1h,1", options="autowidth", grid=none, frame=none]
|===
|XML Element
|`virtualList`

|Java Class
|`JmixVirtualList`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/virtual-list-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`virtualList` is connected to a xref:flow-ui:data/data-containers.adoc[data container]. By default, it shows the xref:data-model:entities.adoc#instance-name[instance name] of the entity in the container. Using the <<Renderer,renderer>> handler, you can display custom content.

[[fragment-renderer]]
Alternatively, you can render items using a nested `fragmentRenderer` element. Refer to the xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[Fragment Renderer] section for more information.

Below is an example of using `virtualList` in a list view instead of `dataGrid`:

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/virtuallist/simple/virtual-list-simple.xml[tags=data;facets;basics]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/simple/VirtualListSimpleSample.java[tags=renderer]
----

Note that items in `virtualList` can't be selected or navigated using the keyboard. The standard xref:flow-ui:actions/list-actions.adoc[List Component Actions] will not work with `virtualList`. If needed, define your own actions for CRUD operations.

[[custom-items]]
== Custom Item Renderer

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/virtual-list-custom-items" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

A component renderer can create custom content for every list item. This example renders each enum value with a label and an icon button.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/virtuallist/customitems/virtual-list-custom-items.xml[tags=custom-items]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/customitems/VirtualListCustomItemsSample.java[tags=custom-items]
----

[[inline-editor]]
== Inline Editor

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/virtual-list-inline-editor" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

You can combine a component renderer, a data container, and detail dialogs to create and edit list items without a separate grid.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/virtual-list-inline-editor.xml[tags=data;inline-editor]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditorSample.java[tags=inline-editor-services;inline-editor-data;inline-editor-renderer;inline-editor-add]
----

== Attributes

The following attributes are specific to `virtualList`:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default

|[[itemsContainer]]`itemsContainer`
|Sets the name of a data container which contains a list of items.
|—

|[[itemsEnum]]`itemsEnum`
|Defines the xref:data-model:enumerations.adoc[enumeration] class for creating a list of items.
|—
|===

The following shared attributes are supported by `virtualList`:

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#focusShortcut[focusShortcut] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#tabIndex[tabIndex] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#width[width]

== Handlers

The following handlers are specific to `virtualList`:

[cols="2,5", options="header"]
|===
|Name
|Description

|[[Renderer]]`Renderer`
|A custom renderer for list items can only be set in the view controller using Java code.

|[[ValueProvider]]`ValueProvider`
|It's possible to specify a renderer using `ValueProvider` if you want to display plain text.
|===

The following shared handlers are supported by `virtualList`:

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/common-handlers.adoc#BlurEvent[BlurEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent] -
xref:vc/common-handlers.adoc#FocusEvent[FocusEvent]

== See Also

* https://vaadin.com/docs/v25/components/virtual-list[Vaadin Virtual List documentation^]
