= Chart Component

The Charts add-on integrates the *ECharts library* into Jmix UI to implement various visualization and chart types.

In Jmix, `chart` is a visual component that comes with a range of configurable properties.

== Main Properties

The component is fully integrated into the Jmix framework, and its properties can be customized:

*Declaratively*, in the XML descriptor file:

[source,xml]
----
<charts:chart id="chart" width="100%" height="100%">
    <charts:title text="Value" subtext="By date"/>
    <charts:legend top="0"/>
</charts:chart>
----

*Programmatically*, within the view controller:

[source,java]
----
@ViewComponent
protected Chart chart;

@Subscribe
protected void onInit(InitEvent event) {
    chart.setTitle(new Title().withText("Value").withSubtext("By date"));
    chart.setLegend(new Legend().withTop("0"));
}
----
[TIP]
====
To add any property in Jmix Studio, select the `chart` component in the screen descriptor XML or in the *Component Hierarchy* panel. Select the xref:studio:screen-designer.adoc#component-inspector-add-button[Add] option then choose the desired property in the *Component Inspector* panel.
====

NOTE: To view the full range of available properties, refer to the https://echarts.apache.org/en/option.html#title[official Apache ECharts documentation].

=== Series

The `series` property defines the type of chart to display (e.g., line, bar, scatter), each chart type can then be configured within its `series`.<unclear>

The basic chart types supported by Jmix include:

* Line series
* Bar series
* Scatter and effect-scatter series
* Candle-stick series
* Boxplot series
* Funnel series
* Gauge series
* Radar series

[source,xml]
----
<charts:chart id="chart" width="100%" height="100%">
    <charts:series>
        <charts:pie name="Liters">
            <charts:label formatter="{b}: {d}%"/>
        </charts:pie>
    </charts:series>
    <!-- other chart properties -->
</charts:chart>
----

==== Formatter


=== DataSet

The `dataSet` property defines the data source for the chart's series and enables data reuse by multiple series.
Use the `<charts:dataSet/>` tag to configure.

[source,xml]
----
<charts:chart id="chart" width="100%" height="100%">
    <charts:dataSet>
        <charts:source dataContainer="countryLitresDc"
                       categoryField="country" valueFields="litres"/>
    </charts:dataSet>
    <!-- other chart properties -->
</charts:chart>
----

<explain the example>

=== Title

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://echarts.apache.org/en/option.html#title" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

The `title` property displays the chart's main and sub-titles, customizable in text content, positioning, alignment, and style. Use the `<charts:title/>` tag to configure.

For example:

[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
    <layout>
        <charts:chart id="chart" height="75%" width="75%">
            <charts:title text="Title text"
                          subtext="Subtitle text" top="0" left="35%" textAlign="CENTER">
                <charts:textStyle fontWeight="bold"/>
            </charts:title>
            <!-- other chart properties -->
        </charts:chart>
    </layout>
</view>
----

This configuration specifies both the main title and a subtitle for the chart, with centralized positioning and bold text styling.

=== Legend

The `legend` property shows the symbol, color, and name of different series. Legends can be clicked to toggle the display of series in the chart. The legend is automatically generated based on the provided data. Use the `<charts:legend/>` tag to configure.

For example:

[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
    <layout>
        <charts:chart id="chart" height="75%" width="75%">
            <charts:legend/>
            <!-- other chart properties -->
        </charts:chart>
    </layout>
</view>
----

This setup introduces a legend to the chart, dynamically populated based on the chart series’s data.

=== DataZoom

The `dataZoom` property provides two primary functionalities:

* *Inside data zoom* enables users to zoom or roam within coordinate systems through mouse dragging, mouse wheel movements, or finger touch gestures on touch screens.

* *Slider type data zoom* offers features like a data thumbnail for a quick overview, zooming in/out, selection brushing, drag to move, and click to locate within the chart's data range.

For example:

[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
   <layout>
      <charts:chart id="chart" width="100%" height="100%">
         <charts:dataZoom>
            <charts:sliderDataZoom orientation="HORIZONTAL"/>
            <charts:sliderDataZoom orientation="VERTICAL" right="5%"/>
            <charts:insideDataZoom/>
         </charts:dataZoom>
         <!-- other chart properties -->
      </charts:chart>
   </layout>
</view>
----

This configuration uses both `insideDataZoom` and `sliderDataZoom`.

=== ToolBox

The `toolbox` property includes a group of utility tools, which includes export, data view, dynamic type switching, data area zooming, and reset.