= Chart Component

The Charts add-on integrates the *ECharts library* into Jmix UI to implement various visualization and chart types.

In Jmix, `chart` is a visual component that comes with a range of configurable properties.

== Main Properties

The component is fully integrated into the Jmix framework, and its properties can be customized:

*Declaratively*, in the XML descriptor file:

[source,xml]
----
<charts:chart id="chart" width="100%" height="100%">
    <charts:title text="Value" subtext="By date"/>
    <charts:legend top="0"/>
</charts:chart>
----

*Programmatically*, within the view controller:

[source,java]
----
@ViewComponent
protected Chart chart;

@Subscribe
protected void onInit(InitEvent event) {
    chart.setTitle(new Title().withText("Value").withSubtext("By date"));
    chart.setLegend(new Legend().withTop("0"));
}
----

[TIP]
====
To add any property in Jmix Studio, select the `chart` component in the screen descriptor XML or in the *Component Hierarchy* panel. Select the xref:studio:screen-designer.adoc#component-inspector-add-button[Add] option then choose the desired property in the *Component Inspector* panel.
====

NOTE: To view the full range of available properties, refer to the https://echarts.apache.org/en/option.html#title[official Apache ECharts documentation].

=== Series

++++
<div class="jmix-ui-live-demo-container">
<a href="https://echarts.apache.org/en/option.html#series" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

The `series` property defines the type of chart to display (e.g., line, bar, scatter), each chart type can be separately configured within the `series` tag.

The basic chart types supported by Jmix include:

* Line series
* Bar series
* Scatter and effect-scatter series
* Candle-stick series
* Boxplot series
* Funnel series
* Gauge series
* Radar series

[TIP]
====
https://demo.jmix.io/ui-samples/[*UI Samples demo*] provides various examples for each chart type.
====

For example:

[source,xml]
----
<charts:chart id="chart" width="100%" height="100%">
    <charts:series>
        <charts:pie name="Liters">
            <charts:label formatter="{b}: {d}%"/>
        </charts:pie>
    </charts:series>
    <!-- other chart properties -->
</charts:chart>
----

In this configuration, the `Series` property is used to define a pie chart. the https://echarts.apache.org/en/option.html#series-pie.label.formatter[`<chart:label formatter`] tag configures how each segment's data is displayed, using `{b}` for the category name and `{d}%` for the percentage value.

NOTE: The `<charts:chart>` tag can include multiple `<charts:series>` configuration, in which case the data will be shared across each chart type.

// TODO: add samples UI link in front of each series

=== DataSet

++++
<div class="jmix-ui-live-demo-container">
<a href="https://echarts.apache.org/en/option.html#dataset" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

The `dataSet` property defines the data source for the chart's series and enables data reuse across multiple `series` within one `charts` tag.
Use the `<charts:dataSet/>` tag to configure.

[source,xml]
----
<charts:chart id="chart" width="100%" height="100%">
    <charts:dataSet>
        <charts:source dataContainer="dateValueDc"
                       categoryField="date" valueFields="value"/>
    </charts:dataSet>
    <!-- other chart properties -->
</charts:chart>
----

In this example, the `DataSet` is bound to a standard collection container `dateValueDc`. This binding allows the chart to dynamically fetch data from the database based on the specified `categoryField` and `valueFields`.

Programmatic configuration example:

[source,java]
----
@ViewComponent
protected Chart chart;
@ViewComponent
protected CollectionContainer<DateValue> dateValueDc;

    @Subscribe
    protected void onInit(InitEvent event) {
       chart.setDataSet(
               new DataSet().withSource(
                       new DataSet.Source<EntityDataItem>()
                               .withDataProvider(new ContainerChartItems<>(dateValueDc))
                               .withCategoryField("date")
                               .withValueField("value")
               )
       );
    }
----

In this Java example, the DataSet configuration is programmatically bound to the dateValueDc collection container using the `ContainerChartItems<>` as the data provider.

NOTE: Each `<charts:chart>` tag can include only one `<charts:dataSet>` configuration.

=== Title

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://echarts.apache.org/en/option.html#title" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

The `title` property displays the chart's main and sub-titles, customizable in text content, positioning, alignment, and style. Use the `<charts:title/>` tag to configure.

For example:

[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
    <layout>
        <charts:chart id="chart" height="75%" width="75%">
            <charts:title text="Title text"
                          subtext="Subtitle text" top="0" left="35%" textAlign="CENTER">
                <charts:textStyle fontWeight="bold"/>
            </charts:title>
            <!-- other chart properties -->
        </charts:chart>
    </layout>
</view>
----

This configuration specifies both the main title and a subtitle for the chart, with centralized positioning and bold text styling.

=== Legend

The `legend` property shows the symbol, color, and name of different series. Legends can be clicked to toggle the display of series in the chart. The legend is automatically generated based on the provided data. Use the `<charts:legend/>` tag to configure.

For example:

[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
    <layout>
        <charts:chart id="chart" height="75%" width="75%">
            <charts:legend/>
            <!-- other chart properties -->
        </charts:chart>
    </layout>
</view>
----

This setup introduces a legend to the chart, dynamically populated based on the chart's data.

=== DataZoom

The `dataZoom` property provides two primary functionalities:

* *Inside data zoom* enables users to zoom or roam within coordinate systems through mouse dragging, mouse wheel movements, or finger touch gestures on touch screens.

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://echarts.apache.org/en/option.html#dataZoom-inside" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

* *Slider type data zoom* offers features like data thumbnails for a quick overview, zooming in/out, selection brushing, drag to move, and click to locate within the chart's data range.

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://echarts.apache.org/en/option.html#dataZoom-slider" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

For example:

[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
   <layout>
      <charts:chart id="chart" width="100%" height="100%">
         <charts:dataZoom>
            <charts:sliderDataZoom orientation="HORIZONTAL"/>
            <charts:sliderDataZoom orientation="VERTICAL" right="5%"/>
            <charts:insideDataZoom/>
         </charts:dataZoom>
         <!-- other chart properties -->
      </charts:chart>
   </layout>
</view>
----

This configuration uses both `insideDataZoom` and `sliderDataZoom`.

=== NativeJson

The `nativeJson` property offers an configuration option using direct JSON stringsas an alternative when the component's Java API or XML attributes do not meet specific customization requirements. This feature grants access to the full range of ECharts' configuration options.

For example:

[source,xml]
----
<charts:chart height="100%" width="100%">
    <charts:nativeJson>
        <![CDATA[{
            "title": {
            "subtext": "subtext"
            }
        }]]>
    </charts:nativeJson>
    <!-- other chart properties -->
</charts:chart>
----

In this configuration, the `nativeJson` tag introduces a `chart:title subtext` property through JSON.

NOTE: `nativeJson` can be merged with existing properties and overrides similar properties.

=== ToolBox

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://echarts.apache.org/en/option.html#toolbox" class="vaadin-docs-btn" target="_blank">EChart</a>
</div>
++++

The `toolbox` property provides a group of utility tools, which includes https://echarts.apache.org/en/option.html#toolbox.feature.saveAsImage[export], https://echarts.apache.org/en/option.html#toolbox.feature.dataZoom[data view], https://echarts.apache.org/en/option.html#toolbox.feature.magicType[dynamic type switching], https://echarts.apache.org/en/option.html#toolbox.feature.dataZoom[data area zooming], and https://echarts.apache.org/en/option.html#toolbox.feature.restore[reset configurations].