= Data Binding

[[data-provider]]
== DataProvider

Using a `Data Provider` in charts allows to present non-entity based or dynamically aggregated data.

The `DataProvider` interface has two standard implementations: `ListChartItems` and `ContainerChartItems` classes.

An instance of `DataProvider` is passed to the `withDataProvider()` method within the `DataSet.Source` attribute of chart configuration. This approach requires creating instances of `DataProvider` or `DataItem` in a view controller.

Entity properties or the values contained in an instance of `DataProvider` which are used for display purposes are defined in the chart attributes. The set of chart attributes may differ for different chart types.

[[list-data-provider]]
=== ListChartItems

`ListChartItems` contains a list of the `DataItem` instances from which the data for the chart will be taken. There are several standard implementations of the `DataItem` interface:
`ListChartItems` allows manual addition of data items within the chart suitable for scenarios where data is not directly tied to a database entity or when a customized data structure is needed.

* `EntityDataItem` takes an instance of any entity from which the data for the chart will be taken:
+
[source,java,indent=0]
----
include::example$charts-ex1/src/main/java/com/company/demo/view/dataitems/EntityDataItemSample.java[tags=onInit]
----

* `MapDataItem` is a set of key-value pairs from which the data for the chart will be taken:
+
[source,java,indent=0]
----
include::example$charts-ex1/src/main/java/com/company/demo/view/dataitems/MapDataItemSample.java[tags=onInit]
----

* `SimpleDataItem` takes an instance of any `public` class from which the data for the chart will be taken:
+
[source,java,indent=0]
----
include::example$charts-ex1/src/main/java/com/company/demo/view/dataitems/SimpleDataItemSample.java[tags=onInit]
----

[[container-data-provider]]
=== ContainerDataItems
`ContainerDataItems` is used to assign a xref:flow-ui:data/collection-container.adoc[CollectionContainer]  to a `Chart` component programmatically.

An instance of `ContainerDataItems` is passed to the `withDataProvider()` method.

Suppose we have a data container with a loader which loads the `VehicleCount` instances. Below is the fragment of the view XML descriptor:
[source,xml,indent=0]
----
include::example$charts-ex1/src/main/resources/com/company/demo/view/vehiclecount/vehicle-count-chart-view.xml[tags=dataCollection]
----

The view controller defines the `onInit()` method that sets a data provider for the chart. The data provider is based on the `vehiclesDc` data container.
[source,java,indent=0]
----
include::example$charts-ex1/src/main/java/com/company/demo/view/vehiclecount/VehicleCountChartView.java[tags=dataSet]
----

To bind data declaratively, use the xref:chart-component.adoc#data-set[`dataSet`] component in your XML descriptor file to connect data from the defined `dataContainer`.
[source,xml,indent=0]
----
include::example$charts-ex1/src/main/resources/com/company/demo/view/vehiclecount/vehicle-count-chart-view.xml[tags=dataSet]
----

Both of these approaches require an existing entity that will represent chart data.

[[gauge-series-data-binding]]
== GaugeSeries Data Binding
++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/gauge-series-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The `GaugeSeries` requires its own `DataSet` for specifying series-specific data.

In case of the `Gauge` chart, you will need to define a `dataItem` element inside the chart's `series` as follows.

[source,xml,indent=0]
----
include::example$charts-ex1/src/main/resources/com/company/demo/view/gauge/gauge-series.xml[tags=dataBinding]
----

Or get the `series` attribute in your java controller, and use the `setData` method to bind data programmatically.

[source,java,indent=0]
----
include::example$charts-ex1/src/main/java/com/company/demo/view/gauge/GaugeSeriesColorizedSample.java[tags=dataBinding]
----

These segments demonstrate how to configure a `GaugeSeries` with a `DataItem` instance to bind series-specific data points to the `Gauge` chart.
