= Events

It is possible to configure handling of different event types for each chart type. 

include::backoffice-ui:page$vcl/events-hanlers-generation-tip.adoc[]

You can see a list of events that can be handled for a particular chart in the corresponding part of the xref:charts:types.adoc[Charts Types] section.

Event handling examples are available in xref:charts:examples.adoc#using-events[Using Events] section.

[[common-events]]
== Common Events

You can handle the following events that are available for all chart types:

* `LegendItemHideEvent` - is sent when hiding a legend item.
* `LegendItemShowEvent` - is sent when showing a legend item.
* `LegendLabelClickEvent` - is sent when clicking on a legend label.
* `LegendMarkerClickEvent` - is sent when clicking on a legend marker.

Above the listeners, the `SeriesBasedChart` interface contains `zoomOut`, `zoomToIndexes`, and `zoomToDates` methods for manipulating the chart axis.

The `CoordinateChart` interface similarly provides the following methods for the value axis: `zoomOutValueAxes`, `zoomOutValueAxis`, `zoomValueAxisToValues`, and `zoomValueAxisToValues`.

[[other-events]]
== Other Events

[[axis-zoom-event]]
=== AxisZoomEvent

This event is sent when chart axis scaling.

[[category-item-click-event]]
=== CategoryItemClickEvent

This event is sent when clicking on a category in the category axis.

[[cursor-period-select-event]]
=== CursorPeriodSelectEvent

This event is sent when selecting the display period with a cursor.

[[cursor-zoom-event]]
=== CursorZoomEvent 

This event is sent when scaling of the chart area with a cursor.

[[chart-click-event]]
=== ChartClickEvent

This event is sent when a user clicks on the canvas.

[[chart-right-click-event]]
=== ChartRightClickEvent

This event is sent when a user right-clicks on the canvas.

[[graph-click-event]]
=== GraphClickEvent 

This event is sent when clicking on a graph.

[[graph-item-click-event]]
=== GraphItemClickEvent 

This event is sent when clicking on a graph item.

[[graph-item-right-click-event]]
=== GraphItemRightClickEvent 

This event is sent when right-clicking on a graph item.

[[slice-click-event]]
=== SliceClickEvent

This event is sent when clicking on a slice in a pie chart.

[[slice-pull-in-event]]
=== SlicePullInEvent

This event is sent when shifting of a slice of a pie chart into the chart.

[[slice-pull-out-event]]
=== SlicePullOutEvent

This event is sent when shifting of a slice of a pie chart out of the chart.

[[slice-right-click-event]]
=== SliceRightClickEvent

This event is sent when right-clicking on a slice in a pie chart.

[[roll-out-graph-event]]
=== RollOutGraphEvent 

This event is sent when the user rolls-out of a graph.

[[roll-out-graph-item-event]]
=== RollOutGraphItemEvent 

This event is sent when the user rolls-out of the data item.

[[roll-over-graph-event]]
=== RollOverGraphEvent 

This event is sent when the user rolls-over a graph.

[[roll-over-graph-item-event]]
=== RollOverGraphItemEvent 

This event is sent when the user rolls-over a data item.

[[zoom-event]]
=== ZoomEvent 

This event is sent when scaling the canvas.

