The Jmix Charts add-on integrates Apache ECharts, an open-source JavaScript visualization library, within Jmix UI.
This integration enables developers to use ECharts for creating a wide range of chart types.

[[installation]]
== Installation

To install the Charts add-on automatically, use the Jmix Marketplace and follow the instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

Use the component palette in the *Jmix UI* inspector panel to declare the namespace in the .

For manual installation, follow the steps below:

. Add the Charts add-on dependency to your `build.gradle` file:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.charts:jmix-charts-flowui-starter'
----

. To use the Charts component in a view, declare the `charts` namespace in the root element of your view's XML descriptor file:
+
[source,xml]
----
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:charts="http://jmix.io/schema/charts/ui">
    <!-- view code -->
</view>
----



// TODO: component palette picture
