= Charts

The Charts add-on provides integration of the https://www.amcharts.com/[amCharts^] JavaScript library in Jmix UI. The add-on includes various types of dynamic charts:

* xref:charts:types/angular-gauge-chart.adoc[AngularGaugeChart]
* xref:charts:types/funnel-chart.adoc[FunnelChart]
* xref:charts:types/gantt-chart.adoc[GanttChart]
* xref:charts:types/pie-chart.adoc[PieChart]
* xref:charts:types/radar-chart.adoc[RadarChart]
* xref:charts:types/serial-chart.adoc[SerialChart]
* xref:charts:types/stock-chart-group.adoc[StockChart]
* xref:charts:types/xy-chart.adoc[XYChart]

AmCharts is distributed under a license, which allows its free use if you keep the link to the library website. Alternatively, you can https://www.amcharts.com/online-store/[purchase^] an AmCharts license for your project and remove the link.

[[installation]]
== Installation

Follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section to install the add-on into your application.

To enable using the component in the screen, declare the `chart` namespace in the root element in the screen XML descriptor:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/charts/ex1/screen/charts/config/columnline-screen.xml[tags=namespace]
----