= URL Query Parameters Support

The xref:flow-ui:facets/urlQueryParameters.adoc[] facet supports URL query parameters for the xref:full-calendar-component.adoc[]. You can bind two properties to the URL state:

* xref:full-calendar-component.adoc#calendar-display-modes[Calendar display mode]. This allows you to control which view (for example, day, week, month) is displayed in the calendar.
* *Date to Navigate*: This lets you specify the initial date that the calendar should display.

== Basic Usage

To bind URL query parameters with the `FullCalendar` component, define `urlQueryParameters` facet and include a nested `calendar:calendarParameters` element to connect the existing calendar by its identifier:

[source,xml,indent=0]
----
include::example$fullcalendar-ex2/src/main/resources/com/company/fullcalendarsample/view/demos/url-query-parameters-view.xml[tags=url-query-parameters-calendar1]
----

This will reflect the current display mode and date in the URL, for example:

`++http://localhost:8080/url-query-parameters-view?calendarDisplayMode=dayGridMonth&calendarDate=2024-10-17++`

TIP: You can view and edit facet attributes in Jmix Studio using the *Jmix UI* inspector panel.

== Attributes

The `calendarParameters` element has the following attributes:

* `component`: The identifier of the `FullCalendar` component to connect to.
* `calendarDisplayModeParam` (optional): The name of the query parameter used to represent the calendar display mode.
* `calendarDateParam` (optional): The name of the query parameter used to represent the date to navigate.