= urlQueryParameters

The xref:flow-ui:facets/urlQueryParameters.adoc[] facet supports URL query parameters fo the xref:full-calendar-component.adoc[]. There are two properties that can be bound with URL state:

- xref:full-calendar-component.adoc#calendar-display-modes[Calendar display mode].
- The date to navigate.

== Basic usage

To bind URL query parameters with the `FullCalendar` component, define `urlQueryParameters` facet and define nested `calendar:calendarParameters` element to connect existing calendar by its identifier:

[source,xml,indent=0]
----
include::example$fullcalendar-ex2/src/main/resources/com/company/fullcalendarsample/view/demos/url-query-parameters-view.xml[tags=url-query-parameters-calendar1]
----

As a result, the current display mode and date will be reflected in the URL like this:

`++http://localhost:8080/url-query-parameters-view?calendarDisplayMode=dayGridMonth&calendarDate=2024-10-17++`

TIP: You can view and edit facet attributes in Jmix Studio using the Jmix UI inspector panel.

== calendarProperties attributes

Attributes of the `calendarParameters` element:

- `component` - identifier of the `FullCalendar` component to connect to.
- `calendarDisplayModeParam` - (optional) name of the query parameter for representing the calendar display mode.
- `calendarDateParam` - (optional) name of the query parameter for representing the date to navigate.