= Обработка изменений URL

Фреймворк автоматически реагирует на изменения URL приложения: производится попытка распознать запрошенный маршрут и выполнить навигацию по истории или открыть экран, зарегистрированный для этого маршрута.

Когда экран открыт по маршруту с параметрами, фреймворк отправляет событие `UrlParamsChangedEvent` контроллеру экрана перед тем, как экран будет показан. То же самое происходит при изменении параметров URL во время открытия экрана. Вы можете подписаться на это событие для обработки начальных параметров и их изменений. Например, можно загрузить данные или скрыть/показать компоненты пользовательского интерфейса экрана в зависимости от параметров URL.

Пример подписки на событие в контроллере экрана:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=url-params-changed-event]
----

См. полный пример использования `UrlParamsChangedEvent` xref:url-history-navigation/url-navigation-api-usage.adoc#url-params-changed-event[далее].