= 路由 API
:page-aliases: backoffice-ui:url-history-navigation/routing-api.adoc

本章节介绍路由 API 的主要内容。

[[route-registration]]
== 路由注册

如需为界面注册路由，在界面控制器添加 `@Route` 注解，示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=route;button-screen-start;button-screen-end]
----

该注解有三个参数：

* `path`（或 `value`）表示路由值；
* `parentPrefix` 用来做路由压缩（squashing）（参阅 <<route-squashing,这里>>）。
* `root` 是一个布尔值属性，用来确定一个路由是否定义根界面（例如，xref:screens/root-screens.adoc#login-screen[登录界面] 或 xref:screens/root-screens.adoc#main-screen[主界面]）。默认值为 `false`。

[[root-screen-for-anonymous-user]]
== 为匿名用户创建根界面

如果你创建了一个根界面，使用了非默认 `login` 的其他路径，并且做成了可以不需要登录而通过链接直接访问的界面，则需要为匿名用户启用该界面。否则，当用户输入 URL 时，比如 `/#your-root-screen`，他们会被重定向到 `/#login` 界面，而不会打开需要的根界面。

. 创建一个界面，例如，`MyAnonymousScreen`，带有一个可以打开登录界面的按钮：
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/screen/myanonymous/MyAnonymousScreen.java[tags=my-anonymous-screen]
----

. 创建 `AnonymousRole` 角色，允许访问 `MyAnonymousScreen`：
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/security/AnonymousRole.java[tags=anonymous-role]
----

. 在 `DatabaseUserRepository` 内，为匿名用户添加 `AnonymousRole` 角色：
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/security/DatabaseUserRepository.java[tags=init-anonymous-user]
----

. 在 `application.properties` 文件中，启用匿名访问支持，并设置匿名用户能看到的界面：
+
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=anonymous-access]
----

. 启动应用程序，确保创建的界面通过 `/#anonymous` 路由能打开。

[[route-squashing]]
== 路由压缩

此功能目的是为了在打开多个带有相同部分路由的界面时保持 URL 干净易读。

假设对于 `Customer` 实体，我们有浏览和编辑界面：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerBrowse.java[tags=route;customer-browse-start;customer-browse-end]
----

[source,java,indent=0]
----
@Route("customers/edit")
public class CustomerEdit extends StandardEditor<Customer> {
}
----

在打开浏览界面之后立刻打开编辑界面，此时 URL 压缩能用来避免 URL 中重复的 `customers` 路由部分。需要在编辑界面的 `@Route` 注解中用 `parentPrefix` 参数指定路由的重复部分：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=route;customer-edit-start;customer-edit-end]
----

现在，当与浏览界面在同一标签页打开编辑界面时，地址将像这样：`a#main/0/customers/edit?id=…`

[[mapping-of-UI-state-to-URL]]
== UI 状态映射至 URL

`UrlRouting` 接口支持根据当前界面和一些参数来修改当前应用程序的 URL。其包含如下方法：

* `pushState()` - 更改地址并添加新的浏览器历史记录；
* `replaceState()` - 替换地址但不添加新的浏览器历史记录；
* `getState()` - 将当前状态作为 `NavigationState` 对象返回。

`pushState()/replaceState()` 方法接受当前界面控制器和一组参数（map 形式，可选）为输入参数。

使用 `UrlRouting` 的示例，请参阅 xref:url-history-navigation/url-navigation-api-usage.adoc#mapping-state-to-url[后面] 章节。

[[navigation-filter]]
== 导航过滤

导航过滤器可以用来阻止切换到某些路由。

导航过滤器是实现了 `NavigationFilter` 接口的 Spring bean。可以使用 `@Order` 注解来配置所有导航过滤器的调用顺序。常量 `JmixOrder.HIGHEST_PRECEDENCE` 和 `JmixOrder.LOWEST_PRECEDENCE` 用来定义框架中的过滤器优先级范围。

`NavigationFilter` 接口有 `allowed()` 方法，可以使用两个输入参数：当前导航状态 `fromState` 和请求的导航状态 `toState`。此方法返回 `AccessCheckResult` 实例并检查是否允许从当前导航状态切换到请求导航状态。

参考 `JmixLoginScreenFilter` 作为示例。支持在用户已经登录的情况下，检查当前会话是否已授权，这样能阻止导航至登录界面。


