= Dynamic Attributes

Dynamic attributes are additional entity attributes that extend the data model without changing the database schema and restarting the application. It allows you to define new entity properties at the deployment or production stage.

Dynamic attributes are stored in the xref:data-model:data-stores.adoc#main[main data store] in an https://en.wikipedia.org/wiki/Entity–attribute–value_model[Entity-Attribute-Value^] structure. The framework automatically loads and saves values of dynamic attributes together with entity instances.

Users can view and edit dynamic attributes in tables and forms of existing application screens in xref:backoffice-ui:index.adoc[].

Jmix provides UI to configure dynamic attributes. An administrator can define a name, a type, validation rules, and specify what UI screens and visual components will display a dynamic attribute.

[[installation]]
== Installation

Follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section to install the add-on into your application.

