= InputDialogFacet

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`InputDialogFacet` gives you an alternative way to configure and open an xref:dialogs.adoc#input-dialog[input dialog]. Instead of using the `Dialogs.createInputDialog()` method in the screen controller, you can configure `InputDialogFacet` in the XML descriptor with the help of Studio visual designer.

Component’s XML-name: `inputDialog`.

[[attributes]]
== Attributes

`InputDialogFacet` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

[[dialog-actions]]
* `dialogActions` - allows you to add the most frequently used actions with the corresponding buttons to the dialog. There are the following possible values:
** `OK_CANCEL` - adds the *OK* and *Cancel* buttons. The default value.
** `OK` - adds the *OK* button.
** `YES_NO` - adds the *Yes* and *No* buttons.
** `YES_NO_CANCEL` - adds the *Yes*, *No*, and *Cancel* buttons.

* `onAction` - defines id of an xref:actions.adoc[action] which should trigger the dialog opening.

* `onButton` - defines id of a xref:vcl/components/button.adoc[button] which should trigger the dialog opening.

[[actions]]
== Actions

See xref:facets/option-dialog-facet.adoc#actions[actions].

[[parameters]]
== Parameters

To add input fields to the dialog, create the nested elements listed below inside the `parameters` element. For each parameter, a corresponding xref:vcl/components.adoc[visual component] will be created for entering the value.

[cols="1,2"]
|===
|Parameter |Visual Component

|`bigDecimalParameter`
|xref:vcl/components/text-field.adoc[] with the `decimal` xref:vcl/components/text-field.adoc#data-type[data type]

|`dateParameter`
|xref:vcl/components/date-field.adoc[] with the `DAY` xref:vcl/components/date-field.adoc#resolution[resolution]

|`dateTimeParameter`
|xref:vcl/components/date-field.adoc[] with the `MIN` xref:vcl/components/date-field.adoc#resolution[resolution]

|`doubleParameter`
|xref:vcl/components/text-field.adoc[] with the `double` xref:vcl/components/text-field.adoc#data-type[data type]

|`intParameter`
|xref:vcl/components/text-field.adoc[] with the `int` xref:vcl/components/text-field.adoc#data-type[data type]

|`longParameter`
|xref:vcl/components/text-field.adoc[] with the `long` xref:vcl/components/text-field.adoc#data-type[data type]

|`stringParameter`
|xref:vcl/components/text-field.adoc[]

|`timeParameter`
|xref:vcl/components/time-field.adoc[]

|===

All the parameters described above have the `defaultValue` attribute for setting the default value for the corresponding field.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;big-decimal-parameter;parameters-end]
----

* Use `entityParameter` to display xref:vcl/components/entity-picker.adoc[]. To define the entity class for the corresponding field, use the `entityClass` attribute.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;entity-parameter;parameters-end]
----

* Use `enumParameter` to display xref:vcl/components/combo-box.adoc[]. To define the enum class for the corresponding field, use the `enumClass` attribute.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;enum-parameter;parameters-end]
----

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[input-dialog-close-event]]
=== InputDialogCloseEvent

The `InputDialogCloseEvent` is sent when the dialog is closed. With the help of the `InputDialogCloseEvent.closedWith()` method, you can track how the dialog was closed:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=notifications;input-dialog-close-event]
----

Programmatic registration of the event handler: use the `addCloseListener()` method.

[[dialog-result-handler]]
=== DialogResultHandler

The `DialogResultHandler` delegate method allows you to handle input dialog results:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=notifications;dialog-result-handler]
----

Programmatic usage: call the `setDialogResultHandler()` method.

[[validator]]
=== Validator

The `Validator` delegate method allows you to validate input values. It receives specific `InputDialog.ValidationContext`, which contains entered values. The method must return the `ValidationErrors` instance, which includes descriptions for errors. These errors will be shown in a notification with other validation exceptions.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=validator]
----

Programmatic usage: call the `setValidator()` method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
<<dialog-actions, dialogActions>> -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#id[id] -
xref:facets/message-dialog-facet.adoc#on-action[onAction] -
xref:facets/message-dialog-facet.adoc#on-button[onButton] -
xref:vcl/xml.adoc#width[width]