= Timer

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/1/sample?id=facet-timer" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`Timer` is a facet designed to run some screen controller code at specified time intervals. It works in a thread that handles user interface events.
Therefore it can update xref:vcl/components.adoc[screen components]. `Timer` stops working when a screen it was created for is closed.

[[attributes]]
== Attributes

`Timer` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

[[delay]]
* `delay` - required attribute. Defines timer interval in milliseconds.

[[autostart]]
* `autostart` - optional attribute. The default value is `false`, which means that the timer will start only when its `start()` method is invoked. When it is set to `true`, the timer starts immediately after the screen opening.

[[repeating]]
* `repeating` - optional attribute. Turns on repeated executions of the timer. If the attribute is set to `true`, the timer runs in cycles at equal intervals defined in the `delay` attribute. Otherwise, the timer runs only once as many milliseconds as specified in the delay attribute after the timer start.

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[timer-action-event]]
=== TimerActionEvent

`TimerActionEvent` allows you to execute some code at the time specified in the `delay` attribute. If the `repeating` attribute is set to `true`, the code specified in this event will be executed periodically, until the timer is stopped.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer-action-event-1]
----

Programmatic registration of the event handler: use the `addTimerActionListener()` component method.

[[timer-stop-event]]
=== TimerStopEvent

`TimerStopEvent` allows you to execute some code after the timer is stopped.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer-stop-event]
----

Programmatic registration of the event handler: use the `addTimerStopListener()` component method.

[[usage-example]]
== Usage Example

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/timer/timer-screen.xml[tags=timer]
----

<1> Defining timer in the `facets` element.
<2> Defining the `layout` for controlling the timer.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer]
----

<1> Start the timer when the `startTimer` button is pressed.
<2> Calculate how long the timer works.
<3> Stopping the timer.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<autostart, autostart>> -
<<delay, delay>> -
xref:vcl/xml.adoc#id[id] -
<<repeating, repeating>>