= Getting Started with WebDAV

This tutorial provides instructions on getting started with integrating the WebDAV add-on into your application.

== Project Setup

We are developing an Onboarding Application - a tool designed to assist newcomers as they navigate through all the necessary steps when starting a new role or position.

We will use the Onboarding application as a starting point.

. If you haven't created this application, you can refer to the xref:tutorial:index.adoc[Tutorial] section, which offers a detailed, step-by-step guide for developing the base application.

. Otherwise, download the complete application source code from the https://github.com/jmix-framework/jmix-onboarding-2[jmix-framework/jmix-onboarding-2^] GitHub repository. Next, follow the instructions in the xref:studio:project.adoc#opening-existing-project[Opening Existing Project] section to open it in Jmix Studio.

. Add the WebDAV add-on according to the xref:index.adoc#installation[installation] section.

== What We Are Going to Do

In this tutorial, we'll introduce a new feature to the Onboarding application.

Onboarding involves training new employees, with an essential component being acquainting them with the company's *knowledge base*.

Typically, the knowledge base includes company-wide standards and rules, operational procedures, as well as procedures, instructions, and best practices for each department and position. To ensure that the knowledge base is up-to-date, it is important to monitor updates and support collaborative documentation.

* An internal knowledge management system is essential to ensure that employees have access to current information.
* This system helps to monitor data modifications and establish access controls to safeguard sensitive information.
* It also fosters collaboration on documents, prevents data errors during simultaneous editing, and maintains an audit trail of document revisions. This allows users to access previous versions of documents if necessary.

== Data Model

Let’s look at the model of the sample onboarding application.

image::data-model-diagram.svg[align="center"]

We will add two entities:

* `WebdavDocumentWrapper`
* `WebdavFolder`

image::data-model.svg[align="center"]