= WebDAV

The WebDAV add-on provides the following functionalities:

* Editing and viewing documents using desktop versions of external applications (MS Word, MS Excel, LibreOffice, etc.).

* Document version control. After the document is updated, a new version is created on the server-side. At the same time, the add-on supports working with documents having both enabled and disabled versioning.

* Granting and restricting access to certain documents.

[[requirements]]
== Minimal Requirements

The minimum version of Microsoft Office required for opening documents via the WebDAV protocol is MS Office 2010 SP2 or higher. The minimum version of LibreOffice is 6.3.

To check which versions of Microsoft Office and Service Pack (SP) are installed on your computer, launch MS Word and open the *Product Information* section from *File → Help*.

Service Pack 2 for MS Office 2010 (and later versions) should have the following number: 14.0.7015.1000 (or greater). To update your Service Pack, follow this https://www.microsoft.com/en-US/download/details.aspx?id=39667[link^].

[[installation]]
== Installation

To include WebDAV in your application, follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section.

The add-on uses basic authentication by default, so the SSL must be <<https-configuring,configured>> in Spring Boot.

[[https-configuring]]
== HTTPS

Basic authentication requires an encrypted connection (HTTPS).

You should configure the SSL in Spring Boot.

[IMPORTANT]
====
Below are the steps for setting up a Self-Signed certificate, which is suitable only for local testing. It is recommended to use SSL certificates issued by a trusted https://en.wikipedia.org/wiki/Certificate_authority[Certificate Authority (CA)^] for building production applications.
====

Use either of the following self-signed certificate formats:

* https://en.wikipedia.org/wiki/PKCS_12[Public Key Cryptographic Standards^] (PKCS12) is a password-protected format containing multiple certificates and keys; it's an industry-wide used format.

* https://en.wikipedia.org/wiki/Java_KeyStore[Java KeyStore^] (JKS) is similar to PKCS12; it's a proprietary format limited to the Java environment.

=== Creating a Keystore File Using Java

. Generate keys and certificates with in-built JDK tool https://docs.oracle.com/en/java/javase/11/tools/keytool.html[Java Keytool^]:
+
[source,properties]
----
keytool -genkeypair -alias cert -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore cert.p12 -validity 3650
----
+
You will have to set a new keystore password. The alias and keystore password will be needed later.

. Copy the file named `cert.p12`, generated in the previous step, into the `src/main/resources/keystore` directory.

=== Configuring SSL Properties

Now let us configure the SSL-related properties in the `application.properties` file:

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=configure]
----