= WebDAV

include::ROOT:partial$outdated-ui-warning.adoc[]

The main purpose of the WebDAV add-on is to give access to files located in the xref:files:file-storage.adoc[file storage] through the https://en.wikipedia.org/wiki/WebDAV[WebDAV protocol^]. This allows users to seamlessly open and edit files using their desktop applications (Word, Excel, LibreOffice, etc.) without the need to download and upload files to the web application.

The add-on provides the following additional features:

* Document version control. If the versioning is enabled for a document, a new version of the document is created on the server each time the document is updated.

* Configurable conflict resolution policies that help in collaborative work on documents.

* Granting and restricting access to certain documents.

* UI components to work with files and versions.

* Access to files from external systems using static links.

[[installation]]
== Installation

NOTE: This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see how to get the trial version <<trial,below>>.

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.webdav:jmix-webdav-starter'
implementation 'io.jmix.webdav:jmix-webdav-rest-starter'
implementation 'io.jmix.webdav:jmix-webdav-flowui-starter'
----
// [source,groovy,indent=0]
// ----
// include::webdav:example$ex1/build.gradle[tags=dependencies]
// ----

include::ROOT:partial$private-repo.adoc[]

[[trial]]
== Trial Version

include::ROOT:partial$get-trial.adoc[]

[[https]]
== HTTPS

Desktop applications use basic authentication when connecting to the server through WebDAV, so you have to setup HTTPS for your web application. See xref:configuration.adoc#https[Configuring HTTPS] for an example of setting up HTTPS on localhost for development purposes.

[[requirements]]
== Minimal Requirements

The minimum version of Microsoft Office required for opening documents via the WebDAV protocol is MS Office 2010 SP2 or higher. The minimum version of LibreOffice is 6.3.

To check which versions of Microsoft Office and Service Pack (SP) are installed on your computer, launch MS Word and open the *Product Information* section from *File → Help*. Service Pack 2 for MS Office 2010 (and later versions) should have the following number: 14.0.7015.1000 (or greater). To update your Service Pack, follow this https://www.microsoft.com/en-US/download/details.aspx?id=39667[link^].
