= Main Services

[[webdav-documents-management-service]]
== WebdavDocumentsManagementService

Designed to work with `WebdavDocument`. The service methods allow you to:

* receive a document by a document version id/document id/document URI/document version;
* receive a list of documents of the given document/resource path;
* create/remove a lock for document with a specific timeout;
* create/update/delete a document;
* create/update/delete versions of a particular document.

[[webdav-document-versions-management-service]]
== WebdavDocumentVersionsManagementService

The service is used to work with document versions. It enables you to:

* get the first version of a document;
* receive the latest version of a document;
* get a particular version of a document;
* get all existing versions of a document;
* create/update/delete a document versions.

[[webdav-raw-links-management-service]]
== WebdavRawLinksManagementService

The service is used to work with persistent links. Persistent link is stored in the database as `WebdavLink` entity instance and points to `WebdavDocument` or `WebdavDocumentVersion` entity instance. The link has a look: `\http://localhost:8080/webdav/link/\{linkIdentifier}` where `linkIdentifier` is `WebdavLink` entity instance id.

For example, `\http://localhost:8080/webdav/link/7a53ce0e-1576-ad32-a131-4abcde6b1235`.

After clicking on the link, the non-persistent link will be generated and open.
Each link has context. Context is additional information about how need to open the entity file, to which the link points. By default, a link is created with default (empty) context. It means that context depends on the stored-in link entity type. If the link entity type is `WebdavDocument`, the file will be opened with full access mode. If the link entity type is `WebdavDocumentVersion`, the file will be opened with read-only access mode.

The service methods allow you to create/remove persistent links to a document with a default/read-only/specific context.

[[webdav-url-management-service]]
== WebdavUrlManagementService

The service is used for getting non-persisted links. The link stores information about the opening application/access mode/filename/document version. The link opens the application for the file stored in the `WebdavDocument`/`WebdavDocumentVersion` entity or downloads it.  For example, `ms-word:ofv|u|http://localhost:8080/webdav/document/0e68df0e-8395-4d25-a230-3eb89e6b2674/example.docx`.

The string value of a link is encapsulated by the field `url` of `WebdavUrl`.

Links are not stored in the database and generated on the fly.

[NOTE]
====
We recommend using persistent links from <<webdav-raw-links-management-service,WebdavRawLinksManagementService>>.
====

The service enables executing the following operations:

* getting a link to the latest document version in full access/read-only mode;
* getting a link to a particular document version in full access/read-only mode;
* receiving information about an external application used for opening a document version.

[[webdav-user-details-service]]
== WebdavUserDetailsService

`WebdavUserDetailsService` enables searching for a user by his username. The search may be case-sensitive or case-insensitive in the actual implementation, depending on how the implementation instance is configured. In this case, the `UserDetails` object that comes back, may have a username of a different case than what was actually requested.

[[webdav-user-management-service]]
== WebdavUserManagementService

The service is used for changing a user's password.