= WebDAV Properties

[[jmix-webdav-applications]]
== jmix.webdav.applications

Allows matching which document formats can be opened via various external applications. For each application you can configure a set of file extensions in the `"extensions"` block. For example:

[source,properties,indent=0]
----
"ms-powerpoint":\
  {"name":"Microsoft PowerPoint","protocols":\
  {"writable":"ms-powerpoint:ofe%7Cu%7C","read_only":"ms-powerpoint:ofv%7Cu%7C"},\
  "extensions":["ppt","pptx"]
----

Considering the example given above, we can conclude that if the user tries opening a document with the `*.ppt` extension, it will be opened in Microsoft PowerPoint.

Default value:

[source,properties,indent=0]
----
{"ms-word":{"name":"Microsoft Word","protocols":{"writable":"ms-word:ofe%7Cu%7C",\
  "read_only":"ms-word:ofv%7Cu%7C"},"extensions":["docx","doc","rtf"]},\
  "ms-excel":{"name":"Microsoft Excel","protocols":{"writable":"ms-excel:ofe%7Cu%7C",\
  "read_only":"ms-excel:ofv%7Cu%7C"},"extensions":["xls","xlsx"]},\
  "ms-powerpoint":{"name":"Microsoft PowerPoint",\
  "protocols":{"writable":"ms-powerpoint:ofe%7Cu%7C","read_only":"ms-powerpoint:ofv%7Cu%7C"},\
  "extensions":["ppt","pptx"]}}
----

Example value for LibreOffice:

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=jmix-webdav-applications]
----

[[jmix-webdav-authenticationMethod]]
== jmix.webdav.authenticationMethod

Defines the authentication type.

Default value: `basic`.

You can set the xref:features.adoc#digest-authentication[digest] authentication using this property.

[[jmix-webdav-url-prefix]]
== jmix.webdav.urlPrefix

Defines the prefix for WebDAV document link.

Default value: `\https://localhost:8443/webdav`.

It must match the address of the application + `/webdav` at the end.

[[jmix-webdav-lock-timeout]]
== jmix.webdav.lockTimeout

Defines the default interval in milliseconds for a document xref:webdav:features.adoc#lock-unlock[locking].

Default value: `600000`.

[[jmix-webdav-versioning-enabled]]
== jmix.webdav.versioningEnabled

Enables the versioning functionality for all fields (those that do not have the `@WebdavSupport` annotation) related to a document.

Default value: `true`.

[[jmix-webdav-auto-generate-unique-resource-uri]]
== jmix.webdav.autoGenerateUniqueResourceUri

If this property is set to `false` and a newly uploaded document has the URI already assigned to another document, the unique constraint violation occurs.

If this property is set to `true` and the URI is already assigned to some document, then the new path will be automatically generated with the format `\{id}.extension`.

Default value: `true`.

[[jmix-webdav-file-storage]]
== jmix.webdav.fileStorage

Define a xref:files:file-storage.adoc[file storage] used for storing WebDAV files.

By default, a file storage returned by `FileStorageLocator.getDefault()` is used.

[[jmix-webdav-use-default-expired-lock-cleaner-quartz-configuration]]
== jmix.webdav.useDefaultExpiredLockCleanerQuartzConfiguration

This property allows you to disable the default configuration that creates and schedules a job with the xref:webdav:features.adoc#expired-lock-cleaning-job[ExpiredLockCleaningJob] identity.

Default value: `true`.

[[jmix-webdav-expired-lock-cleaning-cron]]
== jmix.webdav.expiredLockCleaningCron

This property allows you to change the scheduling of xref:webdav:features.adoc#expired-lock-cleaning-job[ExpiredLockCleaningJob] as http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html^[CRON] expression if necessary.

The default value is `0 0 0/2 ? * *` (every two hours).

[[jmix-webdav-use-default-document-versions-cleaner-quartz-configuration]]
== jmix.webdav.useDefaultDocumentVersionsCleanerQuartzConfiguration

This property allows you to disable the default configuration that creates and schedules a job with the xref:webdav:features.adoc#webdav-document-versions-cleaning-job[WebdavDocumentVersionsCleaningJob] identity.

Default value: `true`.

[[jmix-webdav-document-versions-cleaning-cron]]
== jmix.webdav.documentVersionsCleaningCron

This property allows you to change the scheduling of xref:webdav:features.adoc#webdav-document-versions-cleaning-job[WebdavDocumentVersionsCleaningJob] as http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html^[CRON] expression if necessary.

The default value is `0 0 0 1 * ? *` (every one month).