= Services

[[webdav-documents-management-service]]
== WebdavDocumentsManagementService

The service is designed to work with `WebdavDocument`. Its methods allow you to:

* receive a document by a document version id/document id/document URI/document version;
* receive a list of documents of the given document/resource path;
* create/remove a lock for document with a specific timeout;
* create/update/delete a document;
* create/update/delete versions of a particular document.

[[webdav-document-versions-management-service]]
== WebdavDocumentVersionsManagementService

The service is used to work with document versions. It enables you to:

* get the first version of a document;
* receive the latest version of a document;
* get a particular version of a document;
* get all existing versions of a document;
* create/update/delete a document versions.

[[webdav-raw-links-management-service]]
== WebdavRawLinksManagementService

The service is used to work with persistent links. A persistent link is stored in the database as `WebdavLink` entity instance and points to `WebdavDocument` or `WebdavDocumentVersion` entity instance. The link looks like `\http://localhost:8080/webdav/link/\{linkIdentifier}` where `linkIdentifier` is `WebdavLink` entity instance id.

For example, `\http://localhost:8080/webdav/link/7a53ce0e-1576-ad32-a131-4abcde6b1235`.

After opening the persistent link, the non-persistent link is generated and opened.
Each link has a context which specifies an additional information about how the file referenced by the link should be opened. By default, a link is created with the default empty context. With the empty context, if the link entity type is `WebdavDocument`, the file will be opened with the full access mode. If the link entity type is `WebdavDocumentVersion`, the file will be opened with the read-only access mode.

The service methods allow you to create and remove persistent links to a document with a default/read-only/specific context.

[[webdav-url-management-service]]
== WebdavUrlManagementService

The service is used for getting non-persistent links which are generated on the fly and not stored in the database. The link contains information about the opening application/access mode/filename/document version. The link opens the application for the file stored in the `WebdavDocument`/`WebdavDocumentVersion` entity or downloads it.  For example, `ms-word:ofv|u|http://localhost:8080/webdav/document/0e68df0e-8395-4d25-a230-3eb89e6b2674/example.docx`.

The string value of a link is encapsulated by the `url` attribute of the `WebdavUrl` class.

The service provides the following operations:

* getting a link to the latest document version in full access/read-only mode;
* getting a link to a particular document version in full access/read-only mode;
* receiving information about an external application used for opening a document version.
