= 服务

[[webdav-documents-management-service]]
== WebdavDocumentsManagementService

该服务用于处理 `WebdavDocument`，其功能有：

* 通过文档版本 id、文档 id、文档 URI、文档版本接收文档；
* 通过文档、资源路径接收文档列表；
* 新建、删除文档锁，指定锁时限；
* 新建、更新、删除文档；
* 新建、更新、删除特定文档的版本。

[[webdav-document-versions-management-service]]
== WebdavDocumentVersionsManagementService

该服务用于处理文档版本，其功能有：

* 获取文档的第一个版本；
* 获取文档的最新版本；
* 获取文档的特定版本；
* 获取文档已有的所有版本；
* 创建、更新、删除文档版本。

[[webdav-raw-links-management-service]]
== WebdavRawLinksManagementService

该服务用于处理文档的持久化链接。持久化链接在数据库以 `WebdavLink` 实体实例的形式存储，该实例指向 `WebdavDocument` 或 `WebdavDocumentVersion` 实例。链接格式类似 `\http://localhost:8080/webdav/link/\{linkIdentifier}`，其中 `linkIdentifier` 是 `WebdavLink` 实例的 ID。

例如，`\http://localhost:8080/webdav/link/7a53ce0e-1576-ad32-a131-4abcde6b1235`。

在打开持久化链接时，会生成并打开非持久化链接。
每个链接都有一个上下文（context），其中包含链接指向文件的打开方式。默认情况下创建的链接带的是空上下文，此时，如果链接实体类型是 `WebdavDocument`，文件会以完全访问模式打开。如果链接实体类型为 `WebdavDocumentVersion`，则文件将以只读模式打开。

服务中的方法可以用来创建和删除文档的持久化链接，可使用默认、只读或特定的上下文。

[[webdav-url-management-service]]
== WebdavUrlManagementService

该服务用于获取非持久化链接，这些链接是动态生成的，而非存储在数据库中。链接包含有关打开应用程序/访问模式/文件名/文档版本的信息。链接会为存储在 `WebdavDocument`/`WebdavDocumentVersion` 实体中的文件打开相应的 Office 软件或者直接下载。例如，`ms-word:ofv|u|http://localhost:8080/webdav/document/0e68df0e-8395-4d25-a230-3eb89e6b2674/example.docx`。

链接的字符串值由 `WebdavUrl` 类的 `url` 属性封装。

服务提供下列操作：

* 获取文档最新版本的完全/只读模式的链接；
* 获取文档特定版本的完全/只读模式的链接；
* 接收用于打开文档版本的外部应用程序的信息。
