= Image

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=image-url" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`Image` component is designed for displaying images from different sources. The component can be bound to a xref:vcl/xml.adoc#data-container[data container] or configured programmatically.

Component's XML-name: `image`.

[[basics]]
== Basics

The `Image` component can display the value of an entity attribute of `FileRef` or `byte[]` type. In the simplest case image can be declaratively associated with data using the `xref:vcl/xml.adoc#data-container[dataContainer]` and property attributes:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/entity/Person.java[tags=file-storage-upload-field]
----

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=data-start;instance;data-end;layout-start;simple-image;layout-end]
----

In the example above, the component displays the `image` attribute of the `Person` entity located in the `personDc` data container.

[[resources]]
== Resources

Alternatively, the `Image` component can display images from different resources. You can set the resource type declaratively using the image elements listed below:

* `classpath` - resource in the classpath.
* `file` - resource in the file system.
* `relativePath` - resource in the application directory.
* `theme` - theme resource.
* `url` - resource which can be loaded from the given URL.

For example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=classpath]
----

Also, you can do it programmatically, using one of the <<resource-types, resource types>>.

[[resource-settings]]
=== Resource Settings

* `bufferSize` - size of the download buffer in bytes used for this resource.
* `cacheTime` - length of cache expiration time in milliseconds.
* `mimeType` - MIME type of the resource.

For example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=mime]
----

[[attributes]]
== Attributes

[[alternate-text]]
* `alternateText` - sets an alternate text for an image in case the resource is not set or unavailable.

[[scale-mode]]
* `scaleMode` - applies the scale mode to the image. The following scale modes are available:
** `FILL` - the image will be stretched according to the size of the component.
** `CONTAIN` - the image will be compressed or stretched to the minimum dimension of the component while preserving the proportions.
** `COVER` - the image will be compressed or stretched to fill the entire area of the component while maintaining the component’s proportions. If the image proportions do not match the component’s proportions, then the image will be clipped to fit.
** `SCALE_DOWN` - the content changes size by comparing the difference between `NONE` and `CONTAIN` to find the smallest concrete size of the object.
** `NONE` - the image will retain its real size.

[[methods]]
== Methods

To programmatically manage the `Image` component, use the following methods:

* `setValueSource()` - sets the data container, and the entity attribute name. Only `FileRef` and `byte[]` type of attributes are supported.
+
The data container can be set programmatically, for example, to display images in table cells:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=data-start;collection;data-end;layout-start;group-table;layout-end]
----
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/image/ImageScreen.java[tags=value-source]
----

* `setSource()` - sets the content source for the component. The method accepts the resource type and returns the resource object that can be configured using the fluent interface.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=layout-start;programmatic-image;layout-end]
----
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/image/ImageScreen.java[tags=set-source]
----

[[resource-types]]
=== Resource Types

You can use one of the following resource types implementing the `Resource` interface or extend it to create a custom resource:

* `ClasspathResource` - an image located in the classpath.
* `FileResource` - an image stored in the file system.
* `FileStorageResource` - an image stored in the xref:files:file-storage.adoc[file storage].
* `RelativePathResource` - an image stored in a directory of the application.
* `StreamResource` - an image from a stream.
* `ThemeResource` - a theme image, for example, `VAADIN/themes/yourtheme/some/path/image.png`.
* `UrlResource` - an image that can be loaded from the given URL.

[[handlers]]
== Events and Handlers

include::../events-hanlers-generation-tip.adoc[]

[[click-event]]
=== ClickEvent

See xref:vcl/components/button.adoc#click-event[ClickEvent].

[[context-help-icon-click-event]]
=== ContextHelpIconClickEvent

See xref:vcl/api.adoc#context-help-icon-click-handler[ContextHelpIconClickEvent].

[[source-change-event]]
=== SourceChangeEvent

The SourceChangeEvent is sent when a source of an image is changed and has the following methods:

* `getNewSource()`
* `getOldSource()`

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/image/ImageScreen.java[tags=source-change-event]
----

Programmatic registration of the event handler: use the `addSourceChangeListener()` component method.

[[xml]]
== All XML Attributes

include::../xml-studio-tip.adoc[]

xref:vcl/xml.adoc#align[align] -
<<alternate-text, alternateText>> -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#caption[caption] -
xref:vcl/xml.adoc#caption-as-html[captionAsHtml] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#context-help-text[contextHelpText] -
xref:vcl/xml.adoc#context-help-text-html-enabled[contextHelpTextHtmlEnabled] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#data-container[dataContainer] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#editable[editable] -
xref:vcl/xml.adoc#enable[enable] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#required[required] -
xref:vcl/xml.adoc#required-message[requiredMessage] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#required[required] -
xref:vcl/xml.adoc#required-message[requiredMessage] -
xref:vcl/xml.adoc#rowspan[rowspan] -
<<scale-mode, scaleMode>> -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]