= Использование фрагментов

Этот раздел объясняет, как определять и использовать фрагменты. См. также раздел xref:flow-ui:fragments/fragments.adoc#fragment-events[События фрагмента].

[[declarative-usage]]
== Декларативное использование

Предположим, у вас есть фрагмент для ввода адреса:

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var1/AddressFragment.java[tags=fragment-java]
----

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/address-fragment.xml[tags=fragment-xml]
----

TIP: Фрагмент можно создать с помощью xref:studio:view-wizard.adoc[мастера создания экранов] в Студии. Выберите шаблон `Blank fragment` из списка шаблонов экранов.

Фрагмент можно включить в экран, используя элемент `fragment` с атрибутом `class`, в котором указан FQN класса фрагмента:

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/host-view1.xml[tags=fragment-in-view]
----

Элемент `fragment` может быть добавлен к любому UI-контейнеру экрана, включая элемент `layout` верхнего уровня.

TIP: В xref:studio:view-designer.adoc[визуальном дизайнере] Studio используйте действие *Add Component*, чтобы открыть палитру компонентов. Найдите в ней компонент `Fragment` и перетащите его в структуру компонентов или в XML.

[[programmatic-usage]]
== Программное использование

// todo event link when available
Тот же фрагмент может быть включен в экран программно в обработчике `InitEvent`, `BeforeShowEvent` или `ReadyEvent` следующим образом:

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/host-view.xml[tags=fragment-in-view]
----

.HostView.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var1/HostView.java[tags=fragment-in-view]
----
<1> Инжекция бина `Fragments`, который предназначен для создания фрагментов.
<2> Создание экземпляра фрагмента по его классу.
<3> Добавление экземпляра фрагмента в компонент `Details`.


[[passing-parameters-to-fragments]]
== Передача параметров в фрагменты

Контроллер фрагмента может иметь публичные сеттеры для принятия параметров, как это делается при открытии экранов, например:

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var2/AddressFragment.java[tags=fragment-java]
----
<1> Сеттеры позволяют передавать параметры во фрагмент.

Если фрагмент добавляется в экран декларативно в XML, используйте элемент `properties` для передачи параметров, например:

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var2/host-view.xml[tags=fragment-in-view]
----
<1> Передает контейнер данных методу `setCitiesContainer()`.
<2> Передает строковый параметр методу `setZipcodePlaceholder()`.

Используйте атрибут `value` для указания значений и необязательный атрибут `type` для указания того, что строковое значение должно быть преобразовано одним из подключаемых бинов `PropertyParser`. Сеттеры должны иметь параметры соответствующих типов.

[TIP]
====
Для добавления параметра в Jmix Studio выберите `fragment` в XML-дескрипторе экрана или в панели структуры *Jmix UI* и нажмите кнопку xref:studio:view-designer.adoc#component-inspector-add-button[Add]*->Properties->Property* в панели инспектора *Jmix UI*.
====

Если фрагмент создан программным способом, сеттеры могут быть вызваны явно:

.HostView.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var2/HostView.java[tags=fragment-in-view]
----
<1> Перед добавлением в экран в созданный фрагмент передается параметр.


[[using-data-components]]
== Использование компонентов данных

Фрагмент может иметь собственные контейнеры и загрузчики данных, определенные в элементе `data` XML. В то же время фреймворк создает единственный экземпляр xref:flow-ui:data/data-context.adoc[DataContext] для экрана и всех его фрагментов. Следовательно, все загруженные сущности объединяются в один контекст, и их изменения сохраняются при сохранении данных включающего экрана.

Следующий пример демонстрирует использование собственных контейнеров данных и загрузчиков во фрагменте.

Предположим, у вас есть сущность `City`, и вы хотите показать выпадающий список с доступными городами. Вы можете определить компоненты данных в дескрипторе фрагмента так же, как и в обычном экране:

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var3/address-fragment.xml[tags=fragment-xml]
----

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var3/AddressFragment.java[tags=fragment-java]
----
<1> Фрагмент подписывается на `BeforeShowEvent` включающего экрана, поэтому данные фрагмента будут загружены при открытии экрана.


[[provided-data-components]]
=== Предоставляемые компоненты данных

Следующий пример демонстрирует, как использовать контейнеры данных включающего экрана во фрагменте.

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var4/host-view.xml[tags=fragment-in-view]
----
<1> Контейнер данных, который используется во фрагменте ниже.

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var4/address-fragment.xml[tags=fragment-xml]
----
<1> `provided="true"` означает, что контейнер с тем же идентификатором должен существовать во включающем экране или фрагменте.
<2> Компонент UI связан с предоставленным контейнером данных.

В XML-элементе с атрибутом `provided="true"` игнорируются все атрибуты, кроме id, однако они могут присутствовать для предоставления информации IDE.

Фрагмент может определять и загрузчики, предоставляемые включающим экраном. Предоставленный загрузчик должен иметь идентификатор, равный идентификатору загрузчика экрана, и атрибут `provided="true"`. Например:

[source,xml,indent=0]
----
<loader id="addressDl" provided="true"/>
----