= 使用 Fragments

本节介绍如何定义并使用 fragment。以及 xref:flow-ui:fragments/fragments.adoc#fragment-events[Fragment 事件] 部分。

[[declarative-usage]]
== 声明式使用

假设有一个 fragment 用于输入地址：

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var1/AddressFragment.java[tags=fragment-java]
----

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/address-fragment.xml[tags=fragment-xml]
----

TIP: Studio 中可以通过 xref:studio:view-wizard.adoc[] 创建 fragment，创建时，需选择 `Blank fragment` 模板。

然后可以在视图中使用 `fragment` 元素引入 fragment，其中 `class` 属性需要指定为 fragment 类的完全限定名（FQN）：

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/host-view1.xml[tags=fragment-in-view]
----

`fragment` 元素可以添加到视图中的任意布局组件中，包括根元素 `layout`。

TIP: 在 Studio 的 xref:studio:view-designer.adoc[] 中，通过 *Add Component* 操作打开组件工具箱。找到 `Fragment` 组件，拖放至组件结构或 XML 中。

[[programmatic-usage]]
== 编程式使用

// todo event link when available
Fragment 可以通过编程的方式添加到视图中，在 `InitEvent`、`BeforeShowEvent` 或 `ReadyEvent` 中均可：

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/host-view.xml[tags=fragment-in-view]
----

.HostView.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var1/HostView.java[tags=fragment-in-view]
----
<1> 注入 `Fragments` bean 用于初始化 fragment。
<2> 使用 fragment 的类进行创建。
<3> 将 fragment 实例添加至 `Details`布局组件。


[[passing-parameters-to-fragments]]
== 传递参数

Fragment 控制器可以有 public 的 setter，在打开视图时可以用来接收参数。示例：

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var2/AddressFragment.java[tags=fragment-java]
----
<1> setter 方法可以为 fragment 设置参数。

如果 fragment 是通过声明式的方式在 XML 中添加的，可以用 `properties` 元素传参，示例：

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var2/host-view.xml[tags=fragment-in-view]
----
<1> 传递一个数据容器给 `setCitiesContainer()` 方法。
<2> 传递一个字符串参数给 `setZipcodePlaceholder()` 方法。

通过 `value` 属性设置值，可选的 `type` 属性表示值需要通过一个可插拔的 `PropertyParser` bean 进行转换。Setter 的参数类型必须匹配。

[TIP]
====
如需通过 Jmix Studio 添加参数，在视图 XML 或 *Jmix UI* 层级结构面板中选择 `fragment`，然后点击属性面板中的 xref:studio:view-designer.adoc#component-inspector-add-button[Add]*->Properties->Property*。
====

如果 fragment 是以编程的方式创建的，那么可以直接调用 setter：

.HostView.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var2/HostView.java[tags=fragment-in-view]
----
<1> 在添加到视图之前传参。


[[using-data-components]]
== 使用数据组件

一个 fragment 可以有自己的数据容器和加载器，在 XML 的 `data` 元素定义。同时，框架会为视图及其所有的 fragments 创建单一的 xref:flow-ui:data/data-context.adoc[DataContext] 实例。因此，所有加载出来的实体都合并在一个 context 中，父视图保存数据时一同保存。

下面的示例展示了如何在 fragment 中使用自有的数据容器和加载器。

假设有 `City` 实体，需要展示包含所有城市的下拉列表。与普通视图一样，可以在 fragment 的 XML 中定义数据组件：

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var3/address-fragment.xml[tags=fragment-xml]
----

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var3/AddressFragment.java[tags=fragment-java]
----
<1> fragment 订阅父视图的 `BeforeShowEvent` 事件，当父视图打开时加载 fragment 的数据。


[[provided-data-components]]
=== 使用父数据组件

下面的示例展示如何在 fragment 中使用父视图的数据容器。

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var4/host-view.xml[tags=fragment-in-view]
----
<1> 将在下面 fragment 中使用的数据容器。

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var4/address-fragment.xml[tags=fragment-xml]
----
<1> `provided="true"` 表示这个 id 的数据容器必须在父视图或 fragment 中存在。
<2> UI 与父数据容器关联。

在具有 `provided="true"` 的 XML 元素中，除了 id，其他的属性都会被忽略，但是也可以保留为设计时工具提供信息。

Fragment 也可以定义由父视图提供的数据加载器。其 id 必须与父视图的加载器 id 一致，并使用 `provided="true"` 属性。示例：

[source,xml,indent=0]
----
<loader id="addressDl" provided="true"/>
----
