= Using Fragments

In this section, we explain how to define and use fragments. See also xref:fragments/fragments.adoc#fragment-events[Fragment Events] for how to handle fragment lifecycle events.

[[declarative-usage]]
== Declarative Usage

Suppose we have a fragment for entering an address.

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var1/AddressFragment.java[tags=fragment-java]
----

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/address-fragment.xml[tags=fragment-xml]
----

Then we can include it to another view using the `fragment` element with the `class` attribute pointing to the fragment FQN:

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/host-view1.xml[tags=fragment-in-view]
----

The `fragment` element can be added to any UI container of the view, including the top-level layout element.

[[programmatic-usage]]
== Programmatic Usage

// todo event link when available
The same fragment can be included in the view programmatically in a `InitEvent` or `AfterInitEvent` handler as follows:

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var1/host-view.xml[tags=fragment-in-view]
----

.HostView.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var1/HostView.java[tags=fragment-in-view]
----
<1> Injects the `Fragments` bean which is designed to instantiate fragments.
<2> Creates the fragment’s instance by its class.
<3> Add fragment instance to a UI container.


[[passing-parameters-to-fragments]]
== Passing Parameters to Fragments

A fragment controller can have public setters to accept parameters as it is done when opening views, for example:

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var2/AddressFragment.java[tags=fragment-java]
----
<1> Setter methods allows you to pass parameters to the fragment.

If the fragment is added to the view declaratively in XML, use the `properties` element to pass the parameters, for example:

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var2/host-view.xml[tags=fragment-in-view]
----
<1> Passes a data container to the `setCitiesContainer()` method.
<2> Passes a string parameter to the `setZipcodePlaceholder()` method.

Use the `value` attribute to specify values and the optional `type` attribute to indicate that string value representation must be converted by one of pluggable `PropertyParser` beans. Setters must have parameters of appropriate types.

[TIP]
====
To add a parameter in Jmix Studio, select `fragment` in the view descriptor XML or in the *Jmix UI* hierarchy panel and click on the xref:studio:view-designer.adoc#component-inspector-add-button[Add]*->Properties->Property* button in the *Jmix UI* inspector panel.
====

If the fragment is created programmatically, the setters can be invoked explicitly:

.HostView.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var2/HostView.java[tags=fragment-in-view]
----
<1> Passes a parameter before adding the fragment to the view.


[[using-data-components]]
== Using Data Components

A fragment can have its own data containers and loaders defined in the `data` XML element. At the same time, the framework creates a single instance of xref:flow-ui:data/data-context.adoc[DataContext] for the view and all its fragments. Therefore, all loaded entities are merged to the same context, and their changes are saved when the host view saves the data.

In the following example, we consider usage of own data containers and loaders in a fragment.

Suppose we have a `City` entity and in the fragment, instead of the text field, we want to show a drop-down list with available cities. We can define data components in the fragment descriptor as we would in a regular view:

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var3/address-fragment.xml[tags=fragment-xml]
----

.AddressFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/address/var3/AddressFragment.java[tags=fragment-java]
----
<1> The fragment subscribes on the host view `BeforeShowEvent`, so when the host view is opened, data will be loaded in the fragment.


[[provided-data-containers]]
=== Provided Data Containers

The next example demonstrates how to use data containers of the host view in the fragment.

.host-view.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var4/host-view.xml[tags=fragment-in-view]
----
<1> Data container that is used in the fragment below.

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/address/var4/address-fragment.xml[tags=fragment-xml]
----
<1> `provided="true"` means that the container with the same id must exist in a host view or enclosing fragment.
<2> UI component is linked to the provided data container.

In the XML element having `provided="true"`, all attributes except id are ignored but can be present to provide information for design time tools.

A fragment can also define loaders, provided by a host view. A provided loader must have an id equal to the loader of the host view, and `provided="true"` attribute. For example:

[source,xml,indent=0]
----
<loader id="addressDl" provided="true"/>
----