= Свойства доступа к данным

[[jmix.data.include-null-clause-in-not-conditions]]
== jmix.data.include-null-clause-in-not-conditions

Определяет, включаются ли записи с `null` значениями в результат отрицательных условий свойства.

По умолчанию, когда используется отрицательное условие свойства, записи, в которых фильтруемое свойство имеет значение `null`, не включаются в результат из-за стандартной трехзначной логики SQL. Если для этого свойства установлено значение `true`, Jmix добавляет условие `is null` для операторов отрицательных условий свойства.

Свойство влияет на следующие операторы:

[cols="1,2,2", options="header"]
|===
|Оператор
|JPQL по умолчанию
|JPQL, когда свойство равно `true`

|`NOT_EQUAL`
|`e.field <> :p`
|`(e.field <> :p or e.field is null)`

|`NOT_CONTAINS`
|`e.field not like :p`
|`(e.field not like :p or e.field is null)`

|`NOT_IN_LIST`
|`e.field not in :p`
|`(e.field not in :p or e.field is null)`
|===

Коллекции элементов не затрагиваются этим свойством. Отрицательные условия для коллекций элементов уже используют `not exists (...)`, который включает пустые коллекции.

Значение по умолчанию: `false`

[[jmix.data.number-id-cache-size]]
== jmix.data.number-id-cache-size

Когда с помощью метода `Metadata.create()` в памяти создается экземпляр сущности с идентификатором типа `Integer` или `Long`, аннотированным xref:data-model:entities.adoc#jmix-generated-value[@JmixGeneratedValue], значение идентификатора сразу же присваивается этой сущности. Значение получается из механизма xref:features:sequences.adoc[генерации последовательностей], который получает следующий идентификатор из базы данных. Чтобы уменьшить количество вызовов базы данных, инкремент последовательности устанавливается по умолчанию в 100, что означает, что фреймворк за один вызов получает сразу некоторый диапазон идентификаторов. Таким образом, он "кэширует" этот диапазон и выдает идентификаторы, не обращаясь к базе данных для получения следующего значения, пока не будет использован весь диапазон.

Данное свойство определяет инкремент последовательности и соответствующий размер кэшируемого в памяти диапазона.

CAUTION: Если вы изменяете значение этого свойства, когда в базе данных уже есть некоторые сущности, пересоздайте также все имеющиеся последовательности с новым инкрементом (который должен быть равен `jmix.data.number-id-cache-size`) и начальными значениями, соответствующими максимальным значениям имеющихся идентификаторов.

Если вы используете те же самые последовательности для создания сущностей в хранимых процедурах, настоятельно рекомендуется отключить кэширование, установив значение данного свойства в `0` и пересоздав последовательности с инкрементом `1`.

Значение по умолчанию: `100`

[[jmix.data.unique-constraint-violation-pattern]]
== jmix.data.unique-constraint-violation-pattern

Регулярное выражение, которое используется механизмом обработки xref:flow-ui:exception-handlers.adoc#unique-constraint-violation-handler[нарушений уникальности] для определения того, что исключение вызвано нарушением уникального ограничения в базе данных. Имя ограничения будет получено из первой непустой группы выражения. Например:

[source, properties]
----
jmix.data.unique-constraint-violation-pattern = ERROR: duplicate key value violates unique constraint "(.+)"
----

Это свойство позволяет распознавать ошибки нарушения уникальных ограничений для любой версии и локали СУБД.

[[jmix.data.use-entity-data-store-for-id-sequence]]
== jmix.data.use-entity-data-store-for-id-sequence

Если данное свойство установлено в true, то последовательности для генерации идентификаторов сущностей типа `Integer` или `Long`, помеченных аннотацией `@JmixGeneratedValue`, создаются в хранилище данных, которому принадлежит сущность. В противном случае, они создаются в главном хранилище данных.

Значение по умолчанию: `false`

[[jmix.data.use-read-only-transaction-for-load]]
== jmix.data.use-read-only-transaction-for-load

Указывает, что все методы загрузки xref:data-manager.adoc[DataManager] должны использовать read-only транзакции.

Значение по умолчанию: `true`

[[jmix.eclipselink.disable-lazy-loading]]
== jmix.eclipselink.disable-lazy-loading

NOTE: Эта функциональность в настоящее время является экспериментальной. Она может быть доработана или удалена в будущих версиях. Если вы столкнулись с проблемой при использовании этой функциональности, пожалуйста, создайте тикет на https://github.com/jmix-framework/jmix/issues[GitHub^].

Отключает xref:data-access:fetching.adoc#lazy-loading[ленивую загрузку] для всего приложения. Если это свойство установлено в `true`, при обращении к незагруженному атрибуту будет выбрасываться `IllegalStateException`.

Значение по умолчанию: `false`

[[jmix.eclipselink.query-cache-enabled]]
== jmix.eclipselink.query-cache-enabled

Если свойство установлено в `false`, то xref:cache.adoc#query-cache[кэш запросов] полностью отключается для всех методов независимо от их параметров и аннотаций.

Значение по умолчанию: `true`