= Configuration

Before using notifications in the application, you can create notification types and configure notification channels.

[[notification-types]]
== Notification Types

The add-on does not contain notification types by default. You can create a set of `NotificationType` instances and register them via `NotificationTypesRepository` when initializing the application:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/notifications/ex1/Ex1Application.java[tags=notification-type]
----
<1> Creates a notification type with the unique name info and `icon` name `INFO_CIRCLE`.

Localized messages for the notification types can be added with the following template:

`io.jmix.notifications/NotificationType.<name>=<value>`

In case of the example above:

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/notifications/ex1/messages_en.properties[tags=localization]
----

[[in-app-channel]]
== In-App Channel

In order a user can xref:notifications:viewing-notifications.adoc[view notifications] sent them via the in-app channel, it is necessary to add a notification indicator to the screen, for example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/notifications/ex1/screen/main/main-screen.xml[tags=namespace;not1;not2;not3]
----
<1> Declares the `notifications` namespace in the root element.
<2> Adds a visual component that displays a counter of the unread notifications. It can be added in the `TopMenu` or `SideMenu` inside the `drawer` element or any other screen.


[[email-channel]]
== Email Channel

To send notifications by email, you need to add the xref:email:index.adoc[Email] add-on to the application. After that, you will be able to select the email channel in the xref:notifications:creating-notifications.adoc#ntf-editor[notification editor] window.

The address is taken from the property storing the email. By default, it is `email`. The name of the property can be redefined in the `application.properties` file, for example:

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=email]
----

You can create your own Spring bean implementation of the `UserEmailResolver` interface to describe a more complex logic of receiving the user's email address.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/notifications/ex1/service/GetEmailService.java[tags=service]
----

[[setting-roles]]
== Setting Roles

Users with limited access to the system should be assigned one of the roles:

* *Notifications: In-app notifications user* - a user can view the received notifications.
* *Notifications: administrator* - a user can view, create and send notifications.

////
[[using-in-bpm]]
== Using in BPM

You can send notifications in Business Processes. For more details, see the xref:bpm:sending-notifications.adoc[corresponding section] in BPM.
////