= 配置

在应用程序中使用通知之前，你可以创建通知类型并配置通知通道。

[[notification-types]]
== 通知类型

扩展组件中默认不带通知类型。可以在应用程序初始化的时候创建一组 `NotificationType` 的实例并通过 `NotificationTypesRepository` 注册。下面的代码可以添加至应用程序中的任何一个 bean 内，比如添加至带 `@SpringBootApplication` 注解的主应用程序类中：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/notifications/ex1/Ex1Application.java[tags=notification-type]
----
<1> 使用唯一名称 `info` 和图标名称 `INFO_CIRCLE` 创建通知类型。

通知类型的本地化信息可以用下面的格式添加：

`io.jmix.notifications/NotificationType.<name>=<value>`

例如上面示例中的通知：

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/notifications/ex1/messages_en.properties[tags=localization]
----

[[in-app-channel]]
== 站内通道

为了让用户能 xref:notifications:viewing-notifications.adoc[查看] 通过应用程序内部通道发送的通知，需要为界面添加一个通知提示，示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/notifications/ex1/screen/main/main-screen.xml[tags=namespace;not1;not2;not3]
----
<1> 在根元素声明 `notifications` 命名空间。
<2> 添加一个可视化组件用于展示未读通知的数量。可以添加在 `TopMenu` 或 `SideMenu` 内的 `drawer` 中，或者添加在其他界面。


[[email-channel]]
== 邮件通道

如需通过邮件发送通知，需要在应用程序中添加 xref:email:index.adoc[电子邮件] 扩展组件。然后，可以在 xref:notifications:creating-notifications.adoc#ntf-editor[通知编辑] 界面选择邮件通道。

邮件地址从相应的属性获取，默认为 `email`。该属性的名称可以在 `application.properties` 中重定义，示例：

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=email]
----

也可以创建自己的 Spring bean，实现 `UserEmailResolver` 接口，用于更复杂的用户电子邮件地址获取逻辑。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/notifications/ex1/service/GetEmailService.java[tags=service]
----

[[setting-roles]]
== 安全角色

如需处理通知，用户需要具有下列角色之一：

* *Notifications: In-app notifications user* - 用户可以查看收到的通知。
* *Notifications: administrator* - 用户可以查看、创建、并发送通知。

////
[[using-in-bpm]]
== Using in BPM

You can send notifications in Business Processes. For more details, see the xref:bpm:sending-notifications.adoc[corresponding section] in BPM.
////
