= Notifications

The add-on allows you to create and send notifications via various message channels. Users can receive informational messages as well as notifications about system events.

// as well as notifications from business processes.

[[installation]]
== Installation

NOTE: This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see how to get the trial version <<trial,below>>.

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
include::example$ex1/build.gradle[tags=notifications-dep]
----

[[trial]]
== Trial Version

You can get a trial version of the add-on by visiting the add-on https://www.jmix.io/marketplace/notifications/[page^] on the Jmix Marketplace website.

include::ROOT:partial$get-trial.adoc[]
