= Собственные типы действий

В проекте можно создать собственные типы действий или переопределить существующие стандартные типы.

Предположим, что вы хотите создать действие, которое бы показывало имя экземпляра текущей сущности, выбранной в `dataGrid`, и использовать это действие в различных экранах, указывая только его тип. Чтобы это сделать, необходимо выполнить следующие шаги:

. Создайте для действия отдельный класс с аннотацией `@ActionType`, в которой укажите желаемое имя типа:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/ShowSelectedAction.java[]
----

. Теперь вы можете использовать действие в дескрипторах экрана, просто указывая его тип:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=custom-action]
----

[NOTE]
====
Если вы хотите переопределить существующий тип действия, просто зарегистрируйте свое новое действие с таким же именем типа в аннотации `@ActionType`.
====
