= Standard Actions
:page-aliases: actions/standard-actions.adoc

The framework provides standard actions to solve common tasks, such as an invocation of a detail view for an entity selected in a `dataGrid`. A standard action should be used in the view XML descriptor by specifying its type in the `type` attribute of the `action` element.

Each standard action is implemented by a class annotated with `@ActionType("<some_type>")`. The class defines the action’s default properties and behavior.

You can specify any action XML xref:actions/declarative-actions.adoc#attributes[attributes] to override default properties: `text`, `icon`, `shortcutCombination`, etc. For example:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/actions/standard-list-actions-view.xml[tags=override-properties]
----

There are several categories of standard actions:

* xref:actions/view-actions.adoc[]
* xref:actions/list-actions.adoc[]
* xref:actions/entity-picker-actions.adoc[]
* xref:actions/value-picker-actions.adoc[]

[[additional-properties]]
== Additional Properties

Standard actions usually have additional properties that can be set in XML or using setters in Java. In XML, additional properties are configured using the nested `<properties>` element, where each `<property>` element corresponds to a setter of the action class:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/actions/standard-list-actions-view.xml[tags=properties]
----

The same can be done in Java controller:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/StandardListActionsView.java[tags=properties]
----

[[handlers]]
== Installing Handlers

If an action's setter accepts a functional interface (handler), you can install the handler using an annotated method in the view controller. For example, xref:actions/list-actions.adoc#list_create[CreateAction] has the `setAfterSaveHandler(Consumer)` method which is used to set a handler to be invoked after the created entity is saved. Then you can provide the handler in the view controller as follows:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/StandardListActionsView.java[tags=handlers]
----

include::flow-ui:vc/handler-generation-tip.adoc[]

// There is a common `enabledRule` handler available to all actions, which allows you to set the action "enabled" state depending on the situation. In the example below, it disables `RemoveAction` for some entities:
//
// [source,java,indent=0]
// ----
// include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=table;enabledRule]
// ----