= Стандартные действия

Фреймворк Jmix предоставляет стандартные действия, предназначенные для решения типовых задач, таких как вызов экрана деталей сущности, выбранной в `dataGrid`. Стандартные действия объявляются в XML-дескрипторе экрана путем указания их типа в атрибуте `type` элемента `action`.

Каждое стандартное действие реализуется классом, аннотированным `@ActionType("<some_type>")`. Класс задает свойства и поведение действия по умолчанию.

Для переопределения значений свойств по умолчанию можно задать xref:actions/declarative-actions.adoc#attributes[атрибуты] элемента `action`, такие как `text`, `icon`, `shortcutCombination` и др., например:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/actions/standard-list-actions-view.xml[tags=override-properties]
----

Существует несколько категорий стандартных действий:

* xref:actions/view-actions.adoc[]
* xref:actions/list-actions.adoc[]
* xref:actions/entity-picker-actions.adoc[]
* xref:actions/value-picker-actions.adoc[]

[[additional-properties]]
== Дополнительные свойства

Стандартные действия обычно имеют дополнительные свойства, которые могут быть установлены в XML или используя сеттеры в Java. В XML дополнительные свойства конфигурируются во вложенном элементе `<properties>`, где каждый элемент `<property>` соответствует сеттеру, имеющемуся в классе данного действия:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/actions/standard-list-actions-view.xml[tags=properties]
----

То же самое можно сделать в контроллере на Java:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/StandardListActionsView.java[tags=properties]
----

[[handlers]]
== Установка обработчиков

Если сеттер принимает функциональный интерфейс (обработчик), то установить этот обработчик в контроллере можно путем создания аннотированного метода. Например, xref:actions/list-actions.adoc#list_create[CreateAction] имеет метод `setAfterSaveHandler(Consumer)`, который используется для установки обработчика, вызываемого после того как создаваемая сущность сохранена. Тогда обработчик можно задать следующим образом:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/StandardListActionsView.java[tags=handlers]
----

include::flow-ui:vc/handler-generation-tip.adoc[]

// There is a common `enabledRule` handler available to all actions, which allows you to set the action "enabled" state depending on the situation. In the example below, it disables `RemoveAction` for some entities:
//
// [source,java,indent=0]
// ----
// include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=table;enabledRule]
// ----