= 标准操作

框架提供标准操作用于处理常见任务，例如为 `dataGrid` 中选择的实体调用详情界面。通过在 `type` 属性中指定其类型，就可以在视图 XML 描述中声明标准操作。

每个标准操作都通过一个使用了 `@ActionType("<some_type>")` 注解的类实现。该类定义了操作的默认属性和行为。

可以通过指定基本操作的 XML xref:actions/declarative-actions.adoc#attributes[属性] 来覆盖通用的属性：`text`、`icon`、`shortcutCombination` 等。示例：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/actions/standard-list-actions-view.xml[tags=override-properties]
----

有多种类型的标准操作：

* xref:actions/view-actions.adoc[]
* xref:actions/list-actions.adoc[]
* xref:actions/entity-picker-actions.adoc[]
* xref:actions/value-picker-actions.adoc[]

[[additional-properties]]
== 附加属性

标准操作通常带有附加参数，可以在 XML 进行设置或者在 Java 中用 setter 方法进行设置。在 XML 中，使用内部的 `<properties>` 元素设置，其中每个 `<property>` 元素对应一个操作类中的 setter 方法：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/actions/standard-list-actions-view.xml[tags=properties]
----

在 Java 控制器也可以做同样的设置：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/StandardListActionsView.java[tags=properties]
----

[[handlers]]
== 配置处理方法

如果一个操作的 setter 接收 handler 参数，可以在视图控制器安装一个 handler。比如，xref:actions/list-actions.adoc#list_create[CreateAction] 有 `setAfterSaveHandler(Consumer)` 方法，支持设置一个 handler，在创建的实体提交之后调用这个 handler。那么可以按照下面的方式在视图控制器中安装：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/StandardListActionsView.java[tags=handlers]
----

include::flow-ui:vc/handler-generation-tip.adoc[]

// There is a common `enabledRule` handler available to all actions, which allows you to set the action "enabled" state depending on the situation. In the example below, it disables `RemoveAction` for some entities:
//
// [source,java,indent=0]
// ----
// include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=table;enabledRule]
// ----
