= 视图操作

视图操作可以在整个视图中使用。通常在 XML 顶层的 `actions` 元素定义，并通过连接按钮调用。示例：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-detail-view.xml[tags=view-actions]
----

[[detail_close]]
== detail_close

操作类：`DetailCloseAction`

调用视图的 `close()` 方法关闭实体详情视图。如果视图有未保存的改动，会展示一个带有 *Save | Don't save | Cancel* 选项的标准弹窗。

[[detail_discard]]
== detail_discard

操作类：`DetailDiscardAction`

调用视图的 `close()` 方法关闭实体详情视图，并丢弃所有未保存的改动，且不提示用户。

[[detail_enableEditing]]
== detail_enableEditing

操作类：`DetailEnableEditingAction`

如果视图是通过 xref:actions/list-actions.adoc#list_read[list_read] 操作打开的，则允许用户将实体详情视图切换至可编辑模式。

[[detail_save]]
== detail_save

操作类：`DetailSaveAction`

调用视图的 `save()` 方法保存实体详情视图的改动。不关闭视图。

[[detail_saveClose]]
== detail_saveClose

操作类：`DetailSaveCloseAction`

调用视图的 `closeWithSave()` 方法保存实体详情视图的改动并关闭视图。

[[lookup_discard]]
== lookup_discard

操作类：`LookupDiscardAction`

调用视图的 `closeWithDiscard()` 方法关闭实体列表视图。

[[lookup_select]]
== lookup_select

操作类：`LookupSelectAction`

调用视图的 `handleSelection()` 方法处理选择的内容并关闭实体列表视图。

[[view_close]]
== view_close

操作类：`ViewCloseAction`

对任何类型的视图，调用 `close()` 方法进行关闭。
