= Действия экранов

Действия экранов предназначены для работы с экраном целиком. Обычно они задаются в элементе `actions` верхнего уровня и вызываются связанными кнопками. Например:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-detail-view.xml[tags=view-actions]
----

[[detail_close]]
== detail_close

Класс действия: `DetailCloseAction`

Закрывает экран деталей сущности вызовом его метода `close()`. Если в экране есть несохраненные изменения, будет отображен стандартный диалог с опциями *Save | Don't save | Cancel*.

[[detail_discard]]
== detail_discard

Класс действия: `DetailDiscardAction`

Закрывает экран деталей сущности вызовом его метода `close()`. Игнорирует возможные несохраненные изменения без предупреждения пользователя.

[[detail_enableEditing]]
== detail_enableEditing

Класс действия: `DetailEnableEditingAction`

Позволяет пользователю переключить экран деталей сущности в режим редактирования, если он был открыт действием xref:actions/list-actions.adoc#list_read[list_read].

[[detail_save]]
== detail_save

Класс действия: `DetailSaveAction`

Сохраняет изменения в экране деталей сущности вызовом его метода `save()`. Не закрывает экран.

[[detail_saveClose]]
== detail_saveClose

Класс действия: `DetailSaveCloseAction`

Сохраняет изменения в экране деталей сущности и закрывает его вызовом его метода `closeWithSave()`.

[[lookup_discard]]
== lookup_discard

Класс действия: `LookupDiscardAction`

Закрывает экран списка сущности вызовом его метода`closeWithDiscard()`.

[[lookup_select]]
== lookup_select

Класс действия: `LookupSelectAction`

Обрабатывает выбранные элементы и закрывает экран списка сущности вызовом его метода `handleSelection()`.

[[view_close]]
== view_close

Класс действия: `ViewCloseAction`

Для любого экрана, закрывает его вызовом метода `close()`.