= Создание веб-компонента

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/custom-component-from-scratch" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

https://vaadin.com/docs/v25/flow/create-ui/web-components/introduction-to-webcomponents[Web Components^] можно создавать с нуля на основе библиотек https://polymer-library.polymer-project.org/[Polymer 3^] или https://lit.dev/[Lit^]. После реализации веб-компонента на JavaScript, для него можно создать Java API.

Пример ниже показывает, как построить переключатель светлой/темной темы на основе https://lit.dev/[Lit^].

[[web-component]]
== Создание JavaScript веб-компонента

Создайте файл `theme-toggle.js` в папке `frontend/src/component/theme-toggle`. Он содержит веб-компонент, реализующий переключатель светлой/темной темы.

[source,javascript,indent=0]
----
include::example$/onboarding/frontend/src/component/theme-toggle/theme-toggle.js[tags=web-component]
----
<1> Расширяет Vaadin `Button`, чтобы переиспользовать поведение и стилизацию кнопки.
<2> Определяет имя HTML-элемента.
<3> Определяет шаблон Shadow DOM, включая слоты для иконки, текста и всплывающей подсказки.
<4> Определяет клиентские свойства, включая ключ local storage, используемый для сохранения выбранной темы.
<5> Отправляет событие `theme-changed` после переключения темы компонентом.
<6> Экспортирует пользовательский HTML-элемент с именем, определённым в методе `static get is()`.

[[creating-web-component-java-api]]
== Создание Java API для веб-компонента

Создайте файл `ThemeToggle.java`, который является классом UI-компонента. Он определяет API для серверного кода, методы доступа, обработчики событий и подключение источников данных.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/component/ThemeToggle.java[tags=web-component]
----
<1> Определяет корневой элемент, который автоматически создается классом `Component` и к которому можно обращаться с помощью метода `getElement()`. Должен совпадать с экспортом веб-компонента.
<2> Аннотация `@JsModule` определяет импорт JavaScript-модуля.
<3> Использование https://vaadin.com/docs/v25/flow/create-ui/creating-components/mixins[Vaadin Mixin Interfaces^] для предоставления общих API и поведения по умолчанию для наборов функциональности, встречающихся в большинстве веб-компонентов.
<4> Использование аннотации `@DomEvent` для подключения компонента ThemeToggle к событию DOM `theme-changed`.
<5> Использование аннотации `@EventData` для определения дополнительных данных события, в данном случае значения темы.

TIP: Более подробную информацию о создании пользовательских компонентов можно найти в документации Vaadin: https://vaadin.com/docs/v25/flow/create-ui/creating-components[Creating Components^], https://vaadin.com/docs/v25/flow/create-ui/creating-components/mixins[Using Vaadin Mixin Interfaces^], https://vaadin.com/docs/v25/flow/create-ui/creating-components/events[Using Events with Components^].

[[usage-example]]
== Пример использования

После реализации компонента его можно использовать в экранах, например:

=== XML Дескриптор

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customcomponent/themetoggle/theme-toggle-view.xml[tags=theme-toggle-xml]
----
<1> Определяет пространство имен со значением, совпадающим со значением атрибутов `xmlns` и `targetNamespace` XSD компонента.
<2> Добавляет элемент `themeToggle` с префиксом пространства имен.

=== Программное использование

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/customcomponent/themetoggle/ThemeToggleView.java[tags=component-usage]
----