## Execute 'authenticate.http' first to get have a valid access token for the API

# Invoking a Service via POST

POST {{baseRestUrl}}
         /services
         /sample_OrderService
         /calculateTotalAmount
Authorization: Bearer {{access_token}}

{
  orderId: 123
}

> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body < 10000,
          "Calculation did not work correctly"
      );
    });
  %}

###

# Invoking a Service via GET

GET {{baseRestUrl}}
         /services
         /sample_OrderService
         /calculateTotalAmount
         ?orderId=123
Authorization: Bearer {{access_token}}

> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body < 10000,
          "Calculation did not work correctly"
      );
    });
  %}
