## Execute 'authenticate.http' first to get have a valid access token for the API

# Invoking a custom Controller

GET {{baseUrl}}/orders/calculateTotalAmount?orderId=123
#Authorization: Bearer {{access_token}}

> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body.result === 5,
          "Calculation did not work correctly"
      );
    });
  %}

###


GET {{baseUrl}}
      /myapi/sample/unprotectedMethod

###

GET {{baseUrl}}
      /myapi/sample/protectedMethod
Authorization: Bearer {{access_token}}