= Asynchronous Tasks

The `UiAsyncTasks` bean allows you to execute an operation in a separate thread using the security context of the current user, and then update the UI with the result of that operation.

The `UiAsyncTasks` bean uses `CompletableFuture` under the hood.

If you need to show the progress of an operation and give users the ability to abort it, use the more powerful xref:background-tasks.adoc[] mechanism.

[[ascync-tasks-with-result]]
== Async Tasks With Result

To execute a task that returns a result, use the `supplierConfigurer()` builder and the `supplyAsync()` terminal method:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=supply-async;load-customers]
----
<1> Supplier passed into the `supplierConfigurer()` method will be executed with the security context of the current user.
<2> Code executed inside the `withResultHandler()` consumer can safely update view components.

[[ascync-tasks-without-result]]
== Async Tasks Without Result

To execute a task that doesn't return a result, use the `runnableConfigurer()` builder and the `runAsync()` terminal method:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=run-async;synchronize-customers]
----

[[exception-handling]]
== Exception Handling

By default, if the task execution fails with an exception, the exception is written to the application log. You can customize this behavior by providing an exception handler:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=exception-handler]
----

[[timeout-handling]]
== Timeout Handling

Use the `withTimeout()` method to set the execution timeout value. If the timeout is exceeded, the `TimeoutException` will be thrown. The `TimeoutException` can be processed in the `withExceptionHandler()` method.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=timeout]
----

If no explicit timeout values is specified, the default value of 5 minutes will be used. To change this default, use the xref:ui-properties.adoc#jmix.ui.async-task.default-timeout-sec[jmix.ui.async-task.default-timeout-sec] application property.

[[executor-service-configuration]]
== ExecutorService Configuration

The `UiAsyncTasks` bean uses its own `ExecutorService` to run tasks in separate threads. To modify the default pool size of the `ExecutorService`, use the xref:ui-properties.adoc#jmix.ui.async-task.executor-service.maximum-pool-size[jmix.ui.async-task.executor-service.maximum-pool-size] application property.