= 异步任务

`UiAsyncTasks` Bean 支持使用当前用户的安全上下文在单独的线程中执行操作，并使用该操作的结果更新 UI。

`UiAsyncTasks` bean 的核心功能是通过 `CompletableFuture` 实现的。

如果需要显示操作的进度并为用户提供中止操作的功能，请使用更强大的 xref:background-tasks.adoc[] 机制。

[[ascync-tasks-with-result]]
== 带返回结果的异步任务

如需执行一个可返回结果的任务，请使用 `supplierConfigurer()` builder 以及 `supplyAsync()` 方法：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=supply-async;load-customers]
----
<1> 传递给 `supplierConfigurer()` 方法的 supplier 会使用当前用户的安全上下文执行。
<2> 在消费者 `withResultHandler()` 中执行的代码可以更新视图组件。

[[ascync-tasks-without-result]]
== 不带返回结果的异步任务

如需执行一个无返回结果的任务，请使用 `runnableConfigurer()` builder 以及 `runAsync()` 方法：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=run-async;synchronize-customers]
----

[[exception-handling]]
== 异常处理

默认情况下，如果任务的执行过程由于异常中断，该异常会写入应用程序日志。也可以提供自定义的异常处理器：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=exception-handler]
----

[[timeout-handling]]
== 超时处理

使用 `withTimeout()` 方法设置执行的超时时限。任务执行超时会抛出 `TimeoutException` 异常，可以通过 `withExceptionHandler()` 方法处理超时异常。

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/uiasynctaskssample/UiAsyncTasksSampleView.java[tags=timeout]
----

如果未设置特定的超时时限，默认会使用 5 分钟作为时限。可以通过 xref:ui-properties.adoc#jmix.ui.async-task.default-timeout-sec[jmix.ui.async-task.default-timeout-sec] 应用程序属性修改该配置。

[[executor-service-configuration]]
== ExecutorService 配置

`UiAsyncTasks` bean 使用 `ExecutorService` 在单独的线程中运行任务。如需修改 `ExecutorService` 线程池的默认大小，可以通过 xref:ui-properties.adoc#jmix.ui.async-task.executor-service.maximum-pool-size[jmix.ui.async-task.executor-service.maximum-pool-size] 应用程序属性配置。
