= 数据组件

数据组件是视图中的非可视化元素，数据组件可以加载数据，将数据与数据感知可视化组件进行绑定以及保存修改的数据至数据存储。

// Flow UI 数据组件与 xref:ui:data-components.adoc[经典 UI] 的数据组件完全一样，除了 `DataContext` 有下面的不同：

// * 保存修改的方法由 `commit()` 替换为 `save()`。
// * 保存数据前后发送的事件名改为 `PreSaveEvent` 和 `PostSaveEvent`。

* xref:flow-ui:data/data-containers.adoc[Containers - 数据容器] 是连接实体和数据感知可视化组件的粘合剂。框架为单个实体或实体集合提供了不同的数据容器。
* xref:flow-ui:data/data-loaders.adoc[Loaders - 数据加载器] 将数据加载至数据容器。
* xref:flow-ui:data/data-context.adoc[DataContext - 数据上下文] 跟踪实体的改动并按需保存实体改动。

一般来说，数据组件在视图 XML 的 `<data>` 元素中定义：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=data]
----

数据组件与可视化组件一样，能通过注入的方式在控制器使用：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=data]
----

某个特定视图的数据组件注册在 `ViewData` 对象中，该对象可以在视图控制器中通过 `getViewData()` 方法获取。使用该对象可以很方便地为视图加载所有的数据，示例：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=view-data]
----

TIP: 使用 xref:flow-ui:facets/dataLoadCoordinator.adoc[DataLoadCoordinator] facet 可以声明式地将数据加载器与数据容器、可视化组件以及视图事件进行连接。如需设置某些加载参数，可以通过编程的方式，具体参考 xref:flow-ui:data/data-examples.adoc#using-screen-parameters-in-loaders[后面的章节]。
