= Компоненты данных

Компоненты данных – это невизуальные элементы экрана, которые обеспечивают загрузку данных, привязку их к визуальным компонентам и сохранение измененных экземпляров обратно в хранилище данных.

* xref:flow-ui:data/data-containers.adoc[Контейнеры] обеспечивают тонкий слой между сущностями и визуальными компонентами, связанными с данными (data-aware). Разные типы контейнеров могут хранить один экземпляр или коллекцию экземпляров сущностей.
* xref:flow-ui:data/data-loaders.adoc[Загрузчики] загружают данные в контейнеры.
* xref:flow-ui:data/data-context.adoc[DataContext] отслеживает изменения сущностей и сохраняет измененные экземпляры по запросу.

Обычно компоненты данных задаются в XML-дескрипторе экрана внутри элемента `<data>`:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=data]
----

Компоненты данных можно инжектировать в контроллер экрана так же, как и визуальные компоненты:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=data]
----

Компоненты данных конкретного экрана регистрируются в объекте `ViewData`, который связан с контроллером экрана и доступен с помощью метода `getViewData()`. Этот объект полезен в прикладном коде, когда необходимо загрузить все данные экрана, к примеру:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=view-data]
----

TIP: Используйте фасет xref:flow-ui:facets/dataLoadCoordinator.adoc[DataLoadCoordinator] для декларативного связывания загрузчиков данных с контейнерами данных, визуальными компонентами и событиями экрана.