= Data Components
:page-aliases: vcl/data-components.adoc

Data components are non-visual elements of views that provide loading of data, binding it to data-aware visual components and saving changed data back to the data store.

// Flow UI data components are identical to those of xref:ui:data-components.adoc[classic UI], with the following differences in `DataContext`:
//
// * The method of saving changes is called `save()` instead of `commit()`.
// * Events sent before and after saving are called `PreSaveEvent` and `PostSaveEvent`.

* xref:flow-ui:data/data-containers.adoc[Containers] provide the thin layer between entities and data-aware visual components. Different types of containers hold either single instances or collections of entities.
* xref:flow-ui:data/data-loaders.adoc[Loaders] load data to containers.
* xref:flow-ui:data/data-context.adoc[DataContext] tracks changes in entities and saves changed instances upon request.

Usually, data components are defined in the view XML descriptor in the `<data>` element:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=data]
----

Data components can be injected into the controller in the same way as visual components:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=data]
----

Data components of a particular view are registered in the `ViewData` object which is associated with the controller and available through its `getViewData()` method. This object is useful when you need to load all data for the view, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=view-data]
----

TIP: Use xref:flow-ui:facets/dataLoadCoordinator.adoc[DataLoadCoordinator] facet for declarative linking of data loaders to data containers, visual components and view events.