= Dialogs

The `Dialogs` interface is designed to display standard dialog windows. A dialog window is a small popup window that you can use to present information and user interface elements in an overlay.

The `createMessageDialog()` and `createOptionDialog()` methods are the entry points to the fluent interface that allows you to construct and show dialogs.

[[message-dialog]]
== Message Dialog

The most basic use case for a message dialog is showing some message to the user.

In the following example, a message dialog is shown when the user clicks a button:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/dialogssample/DialogsSampleView.java[tags=inject-dialogs;messageDialog-1]
----

[[option-dialog]]
== Option Dialog

The option dialog displays a message and a set of buttons for user reaction.

Use the `withActions()` method to provide xref:actions.adoc[actions], each of which is represented by a button in the dialog. For example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/dialogssample/DialogsSampleView.java[tags=inject-dialogs;optionsDialog-1]
----
