= Фасеты

Фасеты - это невизуальные компоненты, которые добавляют дополнительное поведение к экрану или его компонентам.

[[built-in]]
== Встроенные фасеты

Фреймворк предоставляет следующие фасеты:

* xref:facets/dataLoadCoordinator.adoc[]
* xref:facets/urlQueryParameters.adoc[]

[[custom]]
== Пользовательские фасеты

Приложение или дополнение (add-on) могут предоставить свои собственные фасеты. Чтобы создать пользовательский фасет, выполните следующие шаги:

1. Создайте интерфейс, расширяющий `io.jmix.flowui.facet.Facet`.
2. Создайте класс его реализации на основе `io.jmix.flowui.facet.impl.AbstractFacet`.
3. Создайте Spring бин, реализующий интерфейс `io.jmix.flowui.xml.facet.FacetProvider`, параметризованный типом вашего фасета.
4. Создайте XSD, который будет использоваться в XML-дескрипторах экранов.
5. Опционально можно создать аннотированный интерфейс для поддержки фасета в панели инспектора *Jmix UI* дизайнера экранов Studio.

Классы фреймворка `DataLoadCoordinator` и `UrlQueryParametersFacet` могут быть хорошими примерами создания фасета.