= Пользовательский интерфейс

Jmix UI позволяет разрабатывать насыщенный веб-интерфейс используя Java и XML. Он основан на веб-фреймворке https://vaadin.com[Vaadin^].

В Jmix UI компоненты пользовательского интерфейса работают в той же JVM, что и бэкенд, что значительно упрощает работу с данными и вызов бизнес-логики. Кроме того, он не требует знакомства с современным стеком JavaScript/HTML/CSS для построения пользовательского интерфейса из набора предоставляемых компонентов.

Бэкенд-часть пользовательского интерфейса является stateful и потребляет память сервера в объеме, пропорциональном количеству одновременных пользовательских сеансов. Поэтому Jmix UI подходит для приложений с предсказуемым и не очень большим (до десятков тысяч) количеством пользователей, одновременно работающих с системой. Для web-scale проектов и полной свободы настройки UI рассмотрите возможность создания фронтенд-приложения используя традиционные фронтенд-технологии. Работа с бэкендом Jmix может осуществляться через xref:rest:index.adoc[REST API].
