= UI Properties

[[common]]
== Common

[[jmix.ui.composite-menu]]
=== jmix.ui.composite-menu

Specifies whether the menu is built with menu items from installed xref:jmix:ROOT:add-ons.adoc[add-ons].

When set to `true`, the menu will include both the items from `menu.xml` of the application and the items from `menu.xml` of each installed add-on that has such file.

When set to `false`, the menu will only include those items that you add to the application's `menu.xml`. This gives you full control over which items are displayed, but you have to manually maintain them.

Default value: `true`.

[[jmix.ui.default-max-fetch-size]]
=== jmix.ui.default-max-fetch-size

Specifies the default maximum number of entity instances that can be loaded to the UI layer.

Default value: `10000`

See also <<jmix.ui.entity-max-fetch-size,jmix.ui.entity-max-fetch-size>>.

[[jmix.ui.default-page-size]]
=== jmix.ui.default-page-size

Specifies the default number of items on the page for the xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] component.

Default value: `50`

See also <<jmix.ui.entity-page-size,jmix.ui.entity-page-size>>.

[[jmix.ui.entity-max-fetch-size]]
=== jmix.ui.entity-max-fetch-size

Specifies the default maximum number of entity instances that can be loaded to the UI layer for a particular entity.

The following example configures the maximum fetch size for two entities. For all other entities the value from <<jmix.ui.default-max-fetch-size,jmix.ui.default-max-fetch-size>> is used.

[source,properties]
----
jmix.ui.entity-max-fetch-size.Product = 500
jmix.ui.entity-max-fetch-size.Customer = 1000
----

[[jmix.ui.entity-page-size]]
=== jmix.ui.entity-page-size

Specifies the default page size for the xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] components for a particular entity.

The following example configures the page size for two entities. For all other entities the default value from <<jmix.ui.default-page-size,jmix.ui.default-page-size>> is used.

[source,properties]
----
jmix.ui.entity-page-size.Product = 100
jmix.ui.entity-page-size.Customer = 500
----

[[jmix.ui.main-view-id]]
=== jmix.ui.main-view-id

The identifier of a view to be used as the main page of the application.

Default value: `main`.

[[jmix.ui.menu-config]]
=== jmix.ui.menu-config

Specifies the path to the `menu.xml` file. The file is loaded using the `Resources` interface, so it can be located in classpath or in the configuration directory.

For example:

[source,properties]
----
jmix.ui.menu-config = ui/ex2/menu.xml
----

[[jmix.ui.login-view-id]]
=== jmix.ui.login-view-id

The identifier of a view to be used as the login page of the application.

Default value: `login`.

[[jmix.ui.save-exported-byte-array-data-threshold-bytes]]
=== jmix.ui.save-exported-byte-array-data-threshold-bytes

Specifies the threshold, in bytes, on which downloaded through `ByteArrayDownloadDataProvider` byte arrays will be saved to temporary files to prevent HTTP session memory leaks.

Default value: `102400`

[[jmix.ui.view-file-extensions]]
=== jmix.ui.view-file-extensions

For the `Downloader` bean, specifies the list of file extensions to be shown in the web browser tab instead of downloading them automatically.

Default value: `[htm, html, jpg, png, jpeg, pdf]`

[[jmix.ui.view.close-shortcut]]
=== jmix.ui.view.close-shortcut

Defines the keyboard shortcut that is used to close the current view

[[jmix.ui.view.save-shortcut]]
=== jmix.ui.view.save-shortcut

Defines the keyboard shortcut that is used to save changes.

[[jmix.ui.view.create-action-adds-first]]
=== jmix.ui.view.create-action-adds-first

Specifies whether an entity created in the dialog is added to the beginning or the end of the list.

Default value: `true`

[[jmix.ui.view.reload-unfetched-attributes-from-lookup-views]]
=== jmix.ui.view.reload-unfetched-attributes-from-lookup-views

Specifies whether `LookupBuilder` will reload an entity after it is selected from lookup window if the selected entity doesn't contain all required entity attributes.

Default value: `true`

[[jmix.ui.view.use-save-confirmation]]
=== jmix.ui.view.use-save-confirmation

Determines what options are shown in the dialog when closing a view with unsaved changes in `DataContext`.

If set to `true`, the dialog contains three options: *Save*, *Don’t save*, *Cancel*.

If set to `false`, the dialog contains only two options: *Yes* to close without saving, and *No* to stay and continue editing.

Default value: `true`.

[[jmix.ui.view.validation-notification-duration]]
=== jmix.ui.view.validation-notification-duration

Defines the duration, in milliseconds, to show the view validation error notifications.

Default value: `3000`

[[jmix.ui.view.validation-notification-position]]
=== jmix.ui.view.validation-notification-position

Sets the validation notifications position on the page. Possible values: `TOP_STRETCH`, `TOP_START`, `TOP_CENTER`, `TOP_END`, `MIDDLE`, `BOTTOM_START`, `BOTTOM_CENTER`, `BOTTOM_END`, `BOTTOM_STRETCH`.

Default value: `BOTTOM_END`

[[jmix.ui.view.validation-notification-type]]
=== jmix.ui.view.validation-notification-type

Specifies standard view validation error notifications variant. Accepts one of the `Notifications.Type` enum values: `DEFAULT`, `ERROR`, `SUCCESS`, `SYSTEM`, `WARNING`.

Default value: `DEFAULT`

[[jmix.ui.navigation.use-crockford-uuid-encoder]]
=== jmix.ui.navigation.use-crockford-uuid-encoder

Specifies whether https://www.crockford.com/base32.html[Base32 Crockford Encoding^]  is used for encoding/decoding of UUID URL parameters.

Default value: `false`

[[components]]
== Components

//todo: add links for AddAction, CreateAction, EditAction, ReadAction, RemoveAction

[[jmix.ui.component.default-notification-duration]]
=== jmix.ui.component.default-notification-duration

Specifies the duration, in milliseconds, for which a notification is displayed.

Default value: `3000`

[[jmix.ui.component.default-notification-position]]
=== jmix.ui.component.default-notification-position

Specifies the default notification position on the page. Possible values: `TOP_STRETCH`, `TOP_START`, `TOP_CENTER`, `TOP_END`, `MIDDLE`, `BOTTOM_START`, `BOTTOM_CENTER`, `BOTTOM_END`, `BOTTOM_STRETCH`.

Default value: `MIDDLE`


[[jmix.ui.component.filter-auto-apply]]
=== jmix.ui.component.filter-auto-apply

//todo: add link to Filter component

When set to `true`, the `Filter` component works in the immediate mode when every change of its parameters automatically reloads data.

When set to `false`, reload occurs only after the *Refresh* button is clicked.

This property can be overridden for a particular instance of the `Filter` component using its `autoApply` XML attribute.

Default value: `true`

[[jmix.ui.component.filter-properties-hierarchy-depth]]
=== jmix.ui.component.filter-properties-hierarchy-depth

//todo: add link to Filter component
Defines the properties hierarchy depth in the Add Condition editor in `Filter`. For example, if the depth value is 2, then you can select an entity attribute `contractor.city.country`, if the value is 3, then `contractor.city.country.name`, etc.

Default value: `2`


[[jmix.ui.component.grid-add-shortcut]]
=== jmix.ui.component.grid-add-shortcut
//todo: add links for all actions

Defines the keyboard shortcut that is used to execute AddAction.

[[jmix.ui.component.grid-create-shortcut]]
=== jmix.ui.component.grid-create-shortcut

Defines the keyboard shortcut that is used to execute CreateAction.

[[jmix.ui.component.grid-edit-shortcut]]
=== jmix.ui.component.grid-edit-shortcut

Defines the keyboard shortcut that is used to execute EditAction.

Default value: `ENTER`

[[jmix.ui.component.grid-read-shortcut]]
=== jmix.ui.component.grid-read-shortcut

Defines the keyboard shortcut that is used to execute ReadAction.

Default value: `ENTER`

[[jmix.ui.component.grid-remove-shortcut]]
=== jmix.ui.component.grid-remove-shortcut

Defines the keyboard shortcut that is used to execute RemoveAction.

[[jmix.ui.component.pagination-items-per-page-items]]
=== jmix.ui.component.pagination-items-per-page-items

Specifies the options for number of items per page in the xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] component.

To configure a custom list of options for a concrete instance of simplePagination, use the xref:flow-ui:vc/components/simplePagination.adoc#itemsPerPageItems[itemsPerPageItems] XML attribute.

Default value: `[20, 50, 100, 500, 1000, 5000]`

[[jmix.ui.component.picker-clear-shortcut]]
=== jmix.ui.component.picker-clear-shortcut

// todo: clarify whether it is for certain pickers or for all picker components.
Defines the keyboard shortcut that is used to clear input of a picker component.

[[jmix.ui.component.picker-lookup-shortcut]]
=== jmix.ui.component.picker-lookup-shortcut

Defines the keyboard shortcut that is used to open a lookup view for a picker component.

[[jmix.ui.component.picker-open-shortcut]]
=== jmix.ui.component.picker-open-shortcut

Defines the keyboard shortcut that is used to open the entity selected in a picker component.

[[background-tasks]]
== Background Tasks

[[jmix.ui.background-task.task-killing-latency]]
=== jmix.ui.background-task.task-killing-latency

Specifies the timeout after which xref:background-tasks.adoc[background tasks] that do not update their status are killed (task's timeout plus latency timeout). If the duration suffix is not specified, seconds will be used.

Default value: `60`

[[jmix.ui.background-task.threads-count]]
=== jmix.ui.background-task.threads-count

Specifies the number of xref:background-tasks.adoc[background task] threads.

Default value: `10`

[[jmix.ui.background-task.timeout-expiration-check-interval]]
=== jmix.ui.background-task.timeout-expiration-check-interval

Specifies the interval at which the expiration of the xref:background-tasks.adoc[background task] is checked. If the duration suffix is not specified, milliseconds will be used.

Default value: `5000`