= UI 配置

[[common]]
== 通用配置

[[jmix.ui.composite-menu]]
=== jmix.ui.composite-menu

配置应用程序的菜单是否包含所有已安装的 xref:jmix:ROOT:add-ons.adoc[扩展组件] 菜单。

当设置为 `true` 时，菜单会包含应用中 `menu.xml` 的内容，以及所有扩展组件中 `menu.xml` 的内容（如果有的话）。

而设置为 `false` 时，菜单仅包含应用程序的 `menu.xml`。此时，菜单有完全自定义的灵活度，但是需要手动维护。

默认值：`true`


[[jmix.ui.default-max-fetch-size]]
=== jmix.ui.default-max-fetch-size

配置可以加载至 UI 层实体实例的默认最大数量。

默认值：`10000`

参阅 <<jmix.ui.entity-max-fetch-size,jmix.ui.entity-max-fetch-size>>。

[[jmix.ui.default-page-size]]
=== jmix.ui.default-page-size

对于 xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] 组件，配置显示在每页中的默认数据条数。

默认值：`50`

参阅 <<jmix.ui.entity-page-size,jmix.ui.entity-page-size>>。

[[jmix.ui.entity-max-fetch-size]]
=== jmix.ui.entity-max-fetch-size

对于某个特定实体，配置可以加载至 UI 层实例的默认最大数量。

以下示例展示如何为两个实体配置不同的最大读取数。对其他未配置该属性的实体，按照 <<jmix.ui.default-max-fetch-size,jmix.ui.default-max-fetch-size>> 加载。

[source,properties]
----
jmix.ui.entity-max-fetch-size.Product = 500
jmix.ui.entity-max-fetch-size.Customer = 1000
----

[[jmix.ui.entity-page-size]]
=== jmix.ui.entity-page-size

对于特定实体的 xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] 组件，配置显示在每页中的默认数据条数。

以下示例展示如何为两个实体配置不同的分页数量。对其他未配置该属性的实体，按照 <<jmix.ui.default-page-size,jmix.ui.default-page-size>> 加载。

[source,properties]
----
jmix.ui.entity-page-size.Product = 100
jmix.ui.entity-page-size.Customer = 500
----

[[jmix.ui.main-view-id]]
=== jmix.ui.main-view-id

配置应用程序主页面的视图 ID。

默认值：`main`。

[[jmix.ui.menu-config]]
=== jmix.ui.menu-config

配置 `menu.xml` 文件的路径。该文件通过 `Resources` 接口加载，因此可以位于 classpath 或者配置目录中。

示例：

[source,properties]
----
jmix.ui.menu-config = ui/ex2/menu.xml
----

[[jmix.ui.login-view-id]]
=== jmix.ui.login-view-id

配置应用程序登录页面的视图 ID。

默认值：`login`。

[[jmix.ui.save-exported-byte-array-data-threshold-bytes]]
=== jmix.ui.save-exported-byte-array-data-threshold-bytes

配置一个下载缓存的阈值，单位为字节。在通过 `ByteArrayDownloadDataProvider` 下载时，字节数组会保存在临时文件中，避免 HTTP 会话的内存泄露。

默认值：`102400`

[[jmix.iu.use-session-fixation-protection]]
=== jmix.iu.use-session-fixation-protection

配置是否在登录后重新初始化用户会话，以确保应用程序不会受到会话固定攻击。

默认值：`true`

[[jmix.ui.view-file-extensions]]
=== jmix.ui.view-file-extensions

对于 `Downloader` bean，配置哪些文件后缀类型可以直接展示在浏览器而不下载。

默认值：`[htm, html, jpg, png, jpeg, pdf]`

[[jmix.ui.view.close-shortcut]]
=== jmix.ui.view.close-shortcut

定义关闭当前视图使用的键盘快捷键。

[[jmix.ui.view.save-shortcut]]
=== jmix.ui.view.save-shortcut

定义保存数据更改的键盘快捷键。

[[jmix.ui.view.create-action-adds-first]]
=== jmix.ui.view.create-action-adds-first

配置通过对话框创建的实体是否添加到列表的开头。

默认值：`true`

[[jmix.ui.view.reload-unfetched-attributes-from-lookup-views]]
=== jmix.ui.view.reload-unfetched-attributes-from-lookup-views

当从查找视图选择某个实体后，如果该实体不包含所需的全部实体属性，通过该配置指定 `LookupBuilder` 是否需要重新加载该实体。

默认值：`true`

[[jmix.ui.view.use-save-confirmation]]
=== jmix.ui.view.use-save-confirmation

当关闭对话框时，如果 `DataContext` 包含未保存的改动，通过该配置定义对话框显示的选项。

如果设置为 `true`，对话框包含三个选项：*Save（保存）*、*Don’t save（不保存）*、*Cancel（取消）*。

如果设置为 `false`，对话框包含仅包含两个选项：*Yes（是）* 不保存数据并关闭窗口，以及 *No（否）*，可以继续编辑。

默认值：`true`。

[[jmix.ui.view.validation-notification-duration]]
=== jmix.ui.view.validation-notification-duration

定义视图中数据验证错误通知的显示时间，单位为毫秒。

默认值：`3000`

[[jmix.ui.view.validation-notification-position]]
=== jmix.ui.view.validation-notification-position

设置数据验证通知在页面中的位置。支持：`TOP_STRETCH`、`TOP_START`、`TOP_CENTER`、`TOP_END`、`MIDDLE`、`BOTTOM_START`、`BOTTOM_CENTER`、`BOTTOM_END`、`BOTTOM_STRETCH`。

默认值：`BOTTOM_END`

[[jmix.ui.view.validation-notification-type]]
=== jmix.ui.view.validation-notification-type

配置视图中标准的数据验证错误通知的类型。支持 `Notifications.Type` 的枚举值：`DEFAULT`、`ERROR`、`SUCCESS`、`SYSTEM`、`WARNING`。

默认值：`DEFAULT`

[[jmix.ui.navigation.use-crockford-uuid-encoder]]
=== jmix.ui.navigation.use-crockford-uuid-encoder

指定是否使用 https://www.crockford.com/base32.html[Base32 Crockford Encoding^]  对 UUID URL 参数进行加解密。

默认值：`false`

[[components]]
== 组件配置

[[jmix.ui.component.default-notification-duration]]
=== jmix.ui.component.default-notification-duration

定义通知的显示时间，单位为毫秒。

默认值：`3000`

[[jmix.ui.component.default-notification-position]]
=== jmix.ui.component.default-notification-position

设置默认通知在页面中的位置。支持：`TOP_STRETCH`、`TOP_START`、`TOP_CENTER`、`TOP_END`、`MIDDLE`、`BOTTOM_START`、`BOTTOM_CENTER`、`BOTTOM_END`、`BOTTOM_STRETCH`。

默认值：`MIDDLE`

[[jmix.ui.component.filter-auto-apply]]
=== jmix.ui.component.filter-auto-apply

当设置为 `true` 时，xref:vc/components/genericFilter.adoc[] 组件以“实时”模式工作，所有一旦过滤器参数有改动都会自动重新加载数据。

当设置为 `false` 时，需要点击 *Refresh（刷新）* 按钮才会重新加载数据。

该配置可以在 xref:vc/components/genericFilter.adoc[] 组件实例的级别通过配置实例的 `autoApply` XML 属性进行覆盖。

默认值：`true`

[[jmix.ui.component.filter-properties-hierarchy-depth]]
=== jmix.ui.component.filter-properties-hierarchy-depth

定义 xref:vc/components/genericFilter.adoc[] 组件中添加条件时显示的实体属性层级深度。例如，如果该值设置为 2，那么可以选择 `contractor.city.country`，如果设置为 3，可以选择 `contractor.city.country.name`。

默认值：`2`

[[jmix.ui.component.filter-show-configuration-id-field]]
=== jmix.ui.component.filter-show-configuration-id-field

配置是否在 xref:vc/components/genericFilter.adoc[过滤器] 的配置详情对话框中显示配置id字段。

默认值：`false`


[[jmix.ui.component.grid-add-shortcut]]
=== jmix.ui.component.grid-add-shortcut

定义执行 xref:actions/list-actions.adoc#list_add[list_add] 操作的键盘快捷键。

[[jmix.ui.component.grid-create-shortcut]]
=== jmix.ui.component.grid-create-shortcut

定义执行 xref:actions/list-actions.adoc#list_create[list_create] 操作的键盘快捷键。

[[jmix.ui.component.grid-edit-shortcut]]
=== jmix.ui.component.grid-edit-shortcut

定义执行 xref:actions/list-actions.adoc#list_create[list_edit] 操作的键盘快捷键。

默认值：`ENTER`

[[jmix.ui.component.grid-read-shortcut]]
=== jmix.ui.component.grid-read-shortcut

定义执行 xref:actions/list-actions.adoc#list_read[list_read] 操作的键盘快捷键。

默认值：`ENTER`

[[jmix.ui.component.grid-remove-shortcut]]
=== jmix.ui.component.grid-remove-shortcut

定义执行 xref:actions/list-actions.adoc#list_remove[list_remove] 操作的键盘快捷键。

[[jmix.ui.component.pagination-items-per-page-items]]
=== jmix.ui.component.pagination-items-per-page-items

配置 xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] 组件中展示的“每页显示行数”选项。

如需为某个 simplePagination 的具体实例配置自定义的选项列表，请使用 xref:flow-ui:vc/components/simplePagination.adoc#itemsPerPageItems[itemsPerPageItems] XML 属性。

默认值：`[20, 50, 100, 500, 1000, 5000]`

[[jmix.ui.component.picker-clear-shortcut]]
=== jmix.ui.component.picker-clear-shortcut

定义清空选择器组件输入内容的键盘快捷键。

[[jmix.ui.component.picker-lookup-shortcut]]
=== jmix.ui.component.picker-lookup-shortcut

定义选择器组件中打开选择视图的键盘快捷键。

[[jmix.ui.component.picker-open-shortcut]]
=== jmix.ui.component.picker-open-shortcut

定义选择器组件中打开已选实体详情视图的键盘快捷键。

[[background-tasks]]
== 后台任务

[[jmix.ui.background-task.task-killing-latency]]
=== jmix.ui.background-task.task-killing-latency

定义 xref:background-tasks.adoc[后台任务] 不更新状态时的超时时限。如果达到任务本身的超时时限加上该参数配置的时限，则尝试终止任务。如果没有指定时间后缀，默认单位为 **秒**。

默认值：`60`

[[jmix.ui.background-task.threads-count]]
=== jmix.ui.background-task.threads-count

配置 xref:background-tasks.adoc[后台任务] 线程数。

默认值：`10`

[[jmix.ui.background-task.timeout-expiration-check-interval]]
=== jmix.ui.background-task.timeout-expiration-check-interval

配置检查 xref:background-tasks.adoc[后台任务] 是否超时的间隔。如果没有指定时间后缀，默认单位为 **毫秒**。

默认值：`5000`
