= Компоненты Filter

xref:vcl/components/filter.adoc[Filter] может использовать специальные компоненты фильтра в качестве условий. Компоненты фильтра должны реализовывать интерфейс `FilterComponent`.

По умолчанию доступны три компонента фильтра:

* <<property-filter,PropertyFilter>>;
* <<jpql-filter,JpqlFilter>>;
* <<group-filter,GroupFilter>>.

Чтобы создать собственный компонент см. <<filter-component-registration>>.

[[property-filter]]
== PropertyFilter

Компонент `PropertyFilter` можно использовать внутри компонента `Filter` и отдельно.

Приведенный ниже пример показывает, как создать конфигурацию во время разработки с помощью `PropertyFilter`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/filter/filter-screen.xml[tags=data-start;customersDc;data-end;layout-start;property-filter;layout-end]
----

Дополнительную информацию см. в разделе xref:vcl/components/property-filter.adoc[PropertyFilter].

[[jpql-filter]]
== JpqlFilter

`JpqlFilter` – это компонент UI, используемый для фильтрации сущностей, которых возвращает `DataLoader`. Он содержит выражения JPQL, которые будут добавлены в секции `from` и `where` запроса загрузчика данных. Данный компонент может автоматически отображать правильную компоновку для установки значения условия. В общем случае компоновка `JpqlFilter` содержит надпись и поле для редактирования значения условия. Данный компонент можно использовать только внутри компонента `Filter`.

Приведенный ниже пример показывает, как создать конфигурацию во время разработки с помощью `JpqlFilter`:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/filter/filter-screen.xml[tags=window-start;data-start;customersDc;data-end;layout-start;filter-jpql-filter-start;filter-jpql-filter-simple;filter-jpql-filter-end;layout-end;window-end]
----
<1> Вы должны добавить пространство имен условий JPQL.
<2> Определите условие JPQL с необязательным элементом `join` и обязательным элементом `where`.

Чтобы настроить условие JPQL, определите элемент `condition` внутри `jpqlFilter` с необязательным элементом xref:vcl/components/filter.adoc#jpql-conditions-join[join] и обязательным элементом xref:vcl/components/filter.adoc#jpql-conditions-where[where]. В приведенном ниже примере создадим `jpqlFilter` с элементами `join` и `where`:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/filter/filter-screen.xml[tags=filter-jpql-filter-start;filter-jpql-filter-join-where;filter-jpql-filter-end]
----

Атрибуты `jpqlFilter` внутри компонента `filter`:

[[jpql-filter-caption]]
* Используя атрибут `caption` можно задать имя условия, отображаемое в фильтре.

[[jpql-filter-has-in-expression]]
* Для атрибута `hasInExpression` должно быть установлено значение `true`, если выражение JPQL содержит условия `in (?)`. В этом случае приложение будет использовать компонент xref:vcl/components/values-picker.adoc[ValuesPicker]. Таким образом, пользователь сможет ввести несколько значений параметров условия.
+
Ниже приведен пример `jpqlFilter` с атрибутом `hasInExpression`:
+
[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/filter/filter-screen.xml[tags=filter-jpql-filter-start;filter-jpql-filter-has-in-expression;filter-jpql-filter-end]
----

[[jpql-filter-parameter-class]]
* `parameterClass` – обязательный атрибут; определяет класс Java параметра условия.

[[jpql-filter-parameter-name]]
* `parameterName` – имя параметра запроса. Это имя можно использовать для введения зависимостей между компонентами фильтра в конфигурации. Если значение не задано, то имя параметра генерируется случайным образом.

[[group-filter]]
== GroupFilter

Компонент `GroupFilter` представляет собой композитный компонент, который имеет xref:vcl/containers/group-box-layout.adoc[GroupBoxLayout] с xref:vcl/containers/responsive-grid-layout.adoc[ResponsiveGridLayout] в качестве корневого контейнера. Этот компонент необходим для объединения нескольких условий в логическую группу с использованием логических операторов (`AND` или `OR`). Данный компонент можно использовать только внутри компонента `Filter`.

Приведенный ниже пример показывает, как создать конфигурацию во время разработки с `GroupFilter`:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/filter/filter-screen.xml[tags=filter-group-filter]
----

[[group-filter-operation]]
Атрибут `operation` является обязательным. Доступны две логические операции:

* `AND` – это операция по умолчанию.
* `OR`.

[[filter-component-registration]]
== Регистрация компонента Filter

Чтобы создать и зарегистрировать UI-компонент фильтра во фреймворке, нужны следующие объекты:

* Класс компонента – компонент UI, который будет отображаться внутри компонента `Filter`. Класс компонента должен расширять класс `FilterComponent`. В качестве примера рассмотрим класс `PropertyFilter`.
* Модель – неперсистентный класс, который содержит состояние компонента фильтра. Модель используется для сохранения состояния компонента фильтра в базе данных и отображения и изменения этого состояния во время выполнения. Класс модели должен расширять класс `FilterCondition`. В качестве примера рассмотрим класс `PropertyFilterCondition`.
* Класс конвертера необходим для конвертирования между компонентом и моделью. Класс конвертера должен реализовывать интерфейс `FilterConverter`.
* Экран редактирования – экран редактирования модели. Если идентификатор не указан, то будет использоваться идентификатор по умолчанию (например, `modelName.edit`, `PropertyFilterCondition.edit`).

Пример регистрации `PropertyFilter`:

[source,indent=0]
----
    @Bean
    public FilterComponentRegistration registerPropertyFilter() {
        return FilterComponentRegistrationBuilder.create(PropertyFilter.class,
                PropertyFilterCondition.class,
                PropertyFilterConverter.class)
                .withEditScreenId("ui_PropertyFilterCondition.edit")
                .build();
    }
----

Все зарегистрированные компоненты фильтра отображаются по нажатию xref:vcl/components/filter.adoc#registered-filters-popup-button[всплывающей кнопки] в диалоговом окне `Add Condition`.

Зарегистрированный во фреймворке Jmix компонент фильтра можно заменить своей собственной реализацией, указав аннотацию `@Order` в бине `FilterComponentRegistration` (например, для расширения набора атрибутов модели, сохраняемых фильтром).

[[xml]]
== Все XML-атрибуты

include::../xml-studio-tip.adoc[]

[[xml-property-filter]]
=== XML-атрибуты PropertyFilter

См. xref:vcl/components/property-filter.adoc#xml[PropertyFilter XML Attributes].

[[xml-jpql-filter]]
=== XML-атрибуты JpqlFilter

xref:vcl/xml.adoc#align[align] -
<<jpql-filter-caption,caption>> -
xref:vcl/xml.adoc#caption-as-html[captionAsHtml] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#context-help-text[contextHelpText] -
xref:vcl/xml.adoc#context-help-text-html-enabled[contextHelpTextHtmlEnabled] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/components/property-filter.adoc#default-value[defaultValue] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#editable[editable] -
xref:vcl/xml.adoc#enable[enable] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
<<jpql-filter-has-in-expression,hasInExpression>> -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
<<jpql-filter-parameter-class,parameterClass>> -
<<jpql-filter-parameter-name,parameterName>> -
xref:vcl/xml.adoc#required[required] -
xref:vcl/xml.adoc#required-message[requiredMessage] -
xref:vcl/xml.adoc#responsive[responsive] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#tab-index[tabIndex] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]

[[xml-group-filter]]
=== XML-атрибуты GroupFilter

xref:vcl/xml.adoc#align[align] -
xref:vcl/xml.adoc#caption[caption] -
xref:vcl/xml.adoc#caption-as-html[captionAsHtml] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#enable[enable] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
<<group-filter-operation,operation>> -
xref:vcl/components/property-filter.adoc#operation-caption-visible[operationCaptionVisible] -
xref:vcl/xml.adoc#responsive[responsive] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]