= Image

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=image-url" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Компонент `Image` предназначен для отображения графического содержимого из различных источников. Компонент можно привязать к xref:vcl/xml.adoc#data-container[контейнеру данных] или сконфигурировать программно.

XML-имя компонента: `image`.

[[basics]]
== Основы

Компонент `Image` может отображать значение атрибута сущности с типом `FileRef` или `byte[]`. Для этого используются атрибуты `xref:vcl/xml.adoc#data-container[dataContainer]` и `property`, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/entity/Person.java[tags=file-storage-upload-field]
----

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=data-start;instance;data-end;layout-start;simple-image;layout-end]
----

В данном случае компонент отображает атрибут `image` сущности `Person`, находящейся в контейнере данных `personDc`.

[[resources]]
== Ресурсы

Помимо источников данных, компонент `Image` может использовать в качестве источника содержимого различные типы ресурсов. Тип ресурса можно указать декларативно с помощью элементов `image`, перечисленных ниже:

* `classpath` - ресурс, расположенный в classpath.
* `file` - файл с изображением.
* `relativePath` - относительный путь к файлу в каталоге приложения.
* `theme` - ресурс из темы приложения.
* `url` - ресурс, загружаемый по URL.

Например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=classpath]
----

Также это можно сделать программно, используя один из <<resource-types,типов ресурсов>>.

[[resource-settings]]
=== Настройки ресурсов

* `bufferSize` - размер буфера, используемого для загрузки этого ресурса, в байтах.
* `cacheTime` - время хранения объекта в кэше в миллисекундах.
* `mimeType` - MIME-тип ресурса.

Например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=mime]
----

[[attributes]]
== Атрибуты

[[alternate-text]]
* `alternateText` - устанавливает альтернативный текст на случай, если ресурс недоступен или не задан.

[[scale-mode]]
* `scaleMode` - устанавливает режим масштабирования изображения. Доступны следующие режимы:
** `FILL` - изображение масштабируется, чтобы заполнить всю область компонента: используется вся ширина и высота компонента.
** `CONTAIN` - изображение подстраивается под размер компонента с сохранением пропорций, уменьшаясь или растягиваясь по меньшей стороне компонента.
** `COVER` - изображение масштабируется так, чтобы заполнить всю область компонента, сохраняя при этом соотношения сторон. Если пропорции изображения не совпадают с пропорциями компонента, то изображение будет обрезано по размеру.
** `SCALE_DOWN` - изображение изменяет размер, сравнивая разницу между `NONE` и `CONTAIN`, для того, чтобы найти наименьший конкретный размер объекта.
** `NONE` - изображение сохранит свой исходный размер, размер компонента будет равен размеру изображения.

[[methods]]
== Методы

Для программного управления компонентом `Image` следует использовать следующие методы:

* `setValueSource()` - устанавливает для изображения контейнер данных и его атрибут. Поддерживаются только атрибуты типов `FileRef` и `byte[]`.
+
Программное указание контейнера данных позволяет, к примеру, отображать изображения в ячейках таблицы:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=data-start;collection;data-end;layout-start;group-table;layout-end]
----
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/image/ImageScreen.java[tags=value-source]
----

* `setSource()` - устанавливает источник изображения. Метод принимает тип ресурса и возвращает объект ресурса, который может быть сконфигурирован далее.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/image/image-screen.xml[tags=layout-start;programmatic-image;layout-end]
----
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/image/ImageScreen.java[tags=set-source]
----

[[resource-types]]
=== Типы ресурсов

Можно использовать следующие типы ресурсов, реализующие интерфейс `Resource`, или расширить их:

* `ClasspathResource` - для изображений, хранимых в classpath.
* `FileResource` - для изображений, хранимых в файловой системе.
* `FileStorageResource` - для изображений из xref:files:file-storage.adoc[хранилища данных].
* `RelativePathResource` - для изображений, хранимых в каталоге приложения.
* `StreamResource` - для изображений, получаемых из потока.
* `ThemeResource` - для изображений темы, например, `VAADIN/themes/yourtheme/some/path/image.png`.
* `UrlResource` - для изображений, загружаемых по указанному URL.

[[handlers]]
== События и слушатели

include::../events-hanlers-generation-tip.adoc[]

[[click-event]]
=== ClickEvent

См. xref:vcl/components/button.adoc#click-event[ClickEvent].

[[context-help-icon-click-event]]
=== ContextHelpIconClickEvent

См. xref:vcl/api.adoc#context-help-icon-click-handler[ContextHelpIconClickEvent].

[[source-change-event]]
=== SourceChangeEvent

`SourceChangeEvent` отправляется при изменении источника изображения и имеет следующие методы:

* `getNewSource()`
* `getOldSource()`

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/image/ImageScreen.java[tags=source-change-event]
----

Чтобы создать слушателя события программно, используйте метод компонента  `addSourceChangeListener()`.

[[xml]]
== Все XML-атрибуты

include::../xml-studio-tip.adoc[]

xref:vcl/xml.adoc#align[align] -
<<alternate-text, alternateText>> -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#caption[caption] -
xref:vcl/xml.adoc#caption-as-html[captionAsHtml] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#context-help-text[contextHelpText] -
xref:vcl/xml.adoc#context-help-text-html-enabled[contextHelpTextHtmlEnabled] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#data-container[dataContainer] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#editable[editable] -
xref:vcl/xml.adoc#enable[enable] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#required[required] -
xref:vcl/xml.adoc#required-message[requiredMessage] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#required[required] -
xref:vcl/xml.adoc#required-message[requiredMessage] -
xref:vcl/xml.adoc#rowspan[rowspan] -
<<scale-mode, scaleMode>> -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]