= Label
:page-aliases: backoffice-ui:vcl/components/label.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=label-simple" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`Label - 文本标签` 是一个文本组件，用于展示静态文本或者实体属性值。

组件的 XML 名称：`label`。

[[simple]]
== 简单标签

示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=simple-label-1]
----

`value` 属性设置标签的文本值。

如果 `value` 属性设置的文本长度超出 `xref:vcl/xml.adoc#width[width]` 值，文件会分为多行显示。因此，显示一个多行标签，可以为标签的 `xref:vcl/xml.adoc#width[width]` 指定一个绝对值。如果文本过长但是 `xref:vcl/xml.adoc#width[width]` 值未定，文本会被截断。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=width-label]
----

[[dynamic]]
== 动态标签

可以在界面控制器中设置标签的参数。需要给标签组件设置一个 id，然后在界面控制器中获取引用：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=dynamic-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=dynamic-label]
----

[[data-aware]]
== 数据感知的标签

`Label` 组件还可以显示实体属性值。需要设置 `xref:vcl/xml.adoc#data-container[dataContainer]` 和 `xref:vcl/xml.adoc#property[property]` 属性，示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=data-aware-label]
----

上面例子中，标签组件显示 `customerDc` 数据容器中实体 `Customer` 的 `name` 字段。

[[html-label]]
== HTML 内容

`htmlEnabled` 属性控制如何解析 `value` 属性值：如果 `htmlEnabled="true"`，则 `value` 值以 HTML 代码解析，否则按纯文本解析。

xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] 属性可以启用或禁用 HTML 清理。如果 `htmlEnabled` 和 `htmlSanitizerEnabled` 属性都设置为 `true`，则标签的 `value` 会被清理。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=html-label]
----

[[predefined-styles]]
== 预定义样式

如需为 `Label` 组件设置自定义样式，可以在 XML 配置或者在界面控制器中设置 `stylename` 属性：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=styled-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=styled-label]
----

* `bold` - 粗体字。适用于重要的或者需要突出显示的 UI 文本。
* `colored` - 彩色文本。
* `failure` - 失败标签样式。标签外会有一个边框，文本旁边会有一个图标。适用于一些组件内部的上下文通知。
* `h1` - 标题样式，应用程序主标题。
* `h2` - 标题样式，应用程序章节标题。
* `h3` - 标题样式，应用程序子章节标题。
* `h4` - 标题样式，应用程序子章节标题。
* `light` - 细体字。适用于附加/补充文本。
* `spinner` - 等待中样式。添加到空 `Label` 组件则可以创建一个可用于表示任务进行中的旋转图标。
* `success` - 成功标签样式。标签外会有一个边框，文本旁会有一个图标。适用于一些组件内部的上下文通知。

[[handlers]]
== 事件和处理器

include::../events-hanlers-generation-tip.adoc[]

[[context-help-icon-click-handler]]
=== ContextHelpIconClickHandler

参阅 xref:vcl/api.adoc#context-help-icon-click-handler[ContextHelpIconClickHandler]。

[[formatter]]
=== 格式化器

为组件添加 xref:vcl/miscellaneous/formatter.adoc[formatter] 实例。

下面示例中，我们演示为 `formattedLabel1` 标签使用 `formatter`：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tags=formatter]
----

如需以编程的方式添加 formatter，使用组件的 `addFormatter()` 方法。

[[value-change-event]]
=== ValueChangeEvent

参阅 xref:vcl/api.adoc#value-change-event[ValueChangeEvent]。

[[xml]]
== Label XML 属性

include::../xml-studio-tip.adoc[]

xref:vcl/xml.adoc#align[align] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#context-help-text[contextHelpText] -
xref:vcl/xml.adoc#context-help-text-html-enabled[contextHelpTextHtmlEnabled] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#data-container[dataContainer] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#height[height] -
<<html-label, htmlEnabled>> -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]

== Label XML 元素

xref:vcl/miscellaneous/formatter.adoc[formatter]
