= Label

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=label-simple" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Надпись (`Label`) − это текстовый компонент, отображающий статический текст либо значение атрибута сущности.

XML-имя компонента: `label`.

[[simple]]
== Простой Label

Пример использования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=simple-label-1]
----

Атрибут `value` предназначен для задания текста надписи.

Текст, содержащийся в атрибуте `value`, будет разбит на несколько строк, если по длине он превысит значение атрибута `xref:vcl/xml.adoc#width[width]`. Поэтому для отображения многострочной надписи, достаточно указать абсолютное значение атрибута `xref:vcl/xml.adoc#width[width]`. Если текст надписи слишком длинный, а значение атрибута `xref:vcl/xml.adoc#width[width]` не определено, то текст будет урезан.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=width-label]
----

[[dynamic]]
== Динамический Label

Параметры надписи можно задать в контроллере экрана. Для этого необходимо задать компоненту идентификатор, по которому получить ссылку на него в контроллере:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=dynamic-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=dynamic-label]
----

[[data-aware]]
== Label, связанный с данными

Компонент `Label` может отображать значение атрибута сущности. Для этого используются атрибуты `xref:vcl/xml.adoc#data-container[dataContainer]` и `xref:vcl/xml.adoc#property[property]`. Например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=data-aware-label]
----

В данном случае компонент отображает атрибут `name` сущности `Customer`, находящейся в контейнере данных `customerDc`.

[[html-label]]
== HTML-контент

Атрибут `htmlEnabled` указывает, каким образом будет рассматриваться значение атрибута `value`: при `htmlEnabled="true"` – как HTML-код, иначе – как строка.

Атрибут xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] разрешает или запрещает санитизацию HTML. Если атрибуты `htmlEnabled` и `htmlSanitizerEnabled` установлены в `true`, то значение атрибута `value` будет санитизировано.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=html-label]
----

[[predefined-styles]]
== Предопределенные стили

К компоненту `Label` можно применить предопределенные стилис помощью атрибута `stylename` или в XML-дескрипторе или контроллере экрана:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=styled-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=styled-label]
----

* `bold` - жирный шрифт. Подходит для выделения важных текстовых элементов UI.
* `colored` - цветной текст.
* `failure` - стиль сообщения об ошибке. Добавляет рамку вокруг компонента и значок рядом с текстом. Используется как уведомление рядом с другим компонентом.
* `h1` - стиль основных заголовков приложения.
* `h2` - стиль заголовков разделов приложения.
* `h3` - стиль подзаголовков.
* `h4` - стиль подзаголовков.
* `light` - облегченный шрифт. Подходит для выделения второстепенных текстовых элементов UI.
* `spinner` - стиль спиннера. Используйте для пустых компонентов Label, чтобы создать спиннер.
* `success` - стиль сообщения об успешном выполнении. Добавляет рамку вокруг компонента и значок рядом с текстом. Используется как уведомление рядом с другим компонентом.

[[handlers]]
== События и слушатели

include::../events-hanlers-generation-tip.adoc[]

[[context-help-icon-click-handler]]
=== ContextHelpIconClickHandler

См. xref:vcl/api.adoc#context-help-icon-click-handler[ContextHelpIconClickHandler].

[[formatter]]
=== Formatter

Добавляет экземпляр xref:vcl/miscellaneous/formatter.adoc[formatter] в компонент.

В приведенном ниже примере показано использование `formatter` для надписи `formattedLabel1`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tags=formatter]
----

Чтобы добавить formatter программно, используйте метод компонента `setFormatter()`.

[[value-change-event]]
=== ValueChangeEvent

См. xref:vcl/api.adoc#value-change-event[ValueChangeEvent].

[[xml]]
== XML-атрибуты Label

include::../xml-studio-tip.adoc[]

xref:vcl/xml.adoc#align[align] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#context-help-text[contextHelpText] -
xref:vcl/xml.adoc#context-help-text-html-enabled[contextHelpTextHtmlEnabled] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#data-container[dataContainer] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#height[height] -
<<html-label, htmlEnabled>> -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]

== XML-элементы Label

xref:vcl/miscellaneous/formatter.adoc[formatter]