= Link

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=link-simple" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Ссылка (`Link`) – компонент-гиперссылка, позволяющая открывать внешние веб-ресурсы.

XML-имя компонента: `link`.

Пример XML-описания компонента `link`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/link/link-screen.xml[tags=link]
----

[[attributes]]
== Атрибуты

* `url` – адрес ресурса.
* `target` – для веб-клиента задает способ открытия страницы, аналогичен атрибуту `target` HTML-тега `<a>`.
* `rel` - необязательный атрибут, определяющий отношения между текущим документом и документом, на который ведет ссылка. Он соответствует атрибуту rel HTML-тега <a>. Значение по умолчанию –  `noopener noreferrer`.
* `noopener` - указывает, что открываемая страница не должна иметь доступа к родительской вкладке, иными словами, он устанавливает для `window.opener` значение `null`.
* `noreferrer` - указывает, что при открытии ссылки не будут переданы HTTP-заголовки.

[[xml]]
== Все XML-атрибуты

xref:vcl/xml.adoc#align[align] -
xref:vcl/xml.adoc#caption[caption] -
xref:vcl/xml.adoc#caption-as-html[captionAsHtml] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#enable[enable] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
<<attributes, rel>> -
xref:vcl/xml.adoc#responsive[responsive] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
<<attributes, target>> -
<<attributes, url>> -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]