= Link
:page-aliases: backoffice-ui:vcl/components/link.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=link-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`Link` is a hyperlink which is used to open external web resources.

Component's XML-name: `link`.

An example of XML-description for `link`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/link/link-screen.xml[tags=link]
----

[[attributes]]
== Attributes

* `url` – the URL of the web resource.
* `target` – sets the web page opening mode, the same as the target attribute of the `<a>` HTML element.
* `rel` - an optional attribute that specifies the relationship between the current document and the linked document. It corresponds to the `rel` HTML attribute which is placed within the `<a>` tag. Default value is `noopener noreferrer`.
* `noopener` - indicates that any browsing context created by following the link will not have an opener browsing context, which means that its `window.opener` property will be `null`.
* `noreferrer` - indicates that no HTTP referer header is to be sent when following the link.

[[xml]]
== All XML Attributes

xref:vcl/xml.adoc#align[align] -
xref:vcl/xml.adoc#caption[caption] -
xref:vcl/xml.adoc#caption-as-html[captionAsHtml] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#enable[enable] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
<<attributes, rel>> -
xref:vcl/xml.adoc#responsive[responsive] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
<<attributes, target>> -
<<attributes, url>> -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]