= Аннотации экранов
:page-aliases: screens/annotations.adoc

Аннотации на классах экранов предоставляют информацию об экранах фреймворку. Некоторые аннотации применимы к любому типу экрана, некоторые из них можно использовать только в экранах списков или деталей сущностей.

[[common-annotations]]
== Общие аннотации

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/myonboarding/MyOnboardingView.java[tags=annotations]
----

* `@ViewController` указывает, что класс является экраном. Значением аннотации является идентификатор экрана, который можно использовать для ссылки на экран из xref:menu-config.adoc[главного меню] или при программном открытии экрана.

* `@ViewDescriptor` соединяет класс экрана с его XML-дескриптором. Значение аннотации указывает путь к файлу дескриптора. Если значение содержит только имя файла, предполагается, что файл находится в том же пакете, что и класс экрана.

* `@com.vaadin.flow.router.Route` определяет URL-путь для перехода к этому экрану. Поскольку экран должен открываться внутри основного экрана, `layout` атрибут указывает класс основного экрана.

* `@DialogMode` определяет параметры диалогового окна, когда экран открывается как диалог.

* `@com.vaadin.flow.server.auth.AnonymousAllowed` делает экран доступным без аутентификации. По умолчанию, только экран логина доступен для неаутентифицированной сессии.
+
TIP: Пример https://github.com/jmix-framework/jmix-samples-2/tree/main/user-registration[User Registration^], показывает, как аннотация `@AnonymousAllowed` используется в экране для самостоятельной регистрации пользователей.

[[list-view-annotations]]
== Аннотации экранов списка

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=annotations]
----

[[lookup-component]]
* `@LookupComponent` указывает идентификатор компонента UI, который будет использоваться для получения значения, возвращаемого в результате поиска.

* `@PrimaryLookupView` указывает, что этот экран является экраном поиска по умолчанию для указанной сущности. Аннотация имеет больший приоритет, чем xref:views/opening-views.adoc#view-inference-conventions[соглашение] `\{entity_name}.lookup` / `\{entity_name}.list`.

[[detail-view-annotations]]
== Аннотации экранов деталей

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentDetailView.java[tags=annotations]
----

[[edited-entity-container]]
* `@EditedEntityContainer` указывает контейнер данных, содержащий редактируемую сущность.

* `@PrimaryDetailView` указывает, что этот экран является экраном деталей по умолчанию для указанной сущности. Аннотация имеет больший приоритет, чем xref:views/opening-views.adoc#view-inference-conventions[соглашение] `\{entity_name}.detail`.
