= View Events

This section describes the view lifecycle events that can be handled in controllers.

The diagram below shows the process of opening and closing a xref:views/view-classes.adoc#standard-view[standard view]:

.Opening and closing a standard view
image::views/standard-view-lifecycle.svg[align="center"]

The diagram below shows the process of opening a xref:views/view-classes.adoc#standard-detail-view[detail view], either through navigation or as a dialog:

.Opening a detail view for entity editing
image::views/open-detail-view.svg[align="center"]

The diagram below shows the process of saving changes and closing a detail view:

.Closing the view with xref:actions/view-actions.adoc#detail_saveClose[detail_saveClose] action
image::views/detail-view-close-with-save.svg[align="center"]

[[init-event]]
== InitEvent

`InitEvent` is the first event in the view opening process. The view and all its declaratively defined components are created, and dependency injection is completed. Some visual components are not fully initialized, for example, buttons are not linked with actions. In this event listener, you can create visual and data components.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserDetailEventsView.java[tags=init-event]
----

NOTE: The event is triggered only once after the view is created. This means that if the navigation to the view occurs for the first time, the event triggers. However, if navigation is performed to the same view that is currently open more than once, for example, by clicking on the same menu item multiple times, the event will not be triggered because the view instance has already been created.

[[before-show-event]]
== BeforeShowEvent

`BeforeShowEvent` is the second event (after `View.InitEvent`) in the view opening process. All components have completed their internal initialization procedures. xref:data/data-loaders.adoc[Data loaders] have been triggered by the automatically configured xref:facets/dataLoadCoordinator.adoc[DataLoadCoordinator] facet. Security restrictions are applied to UI components. In this event listener, you can load data, check permissions and modify UI components. For example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=users-loader;before-show-event]
----

NOTE: Consequent navigation to the same view that is currently open, leads to triggering `View.BeforeShowEvent` again for the same instance of the view. For example, the user navigates to a view for the first time, then a view instance is created and `View.BeforeShowEvent` triggers. Then, the user clicks on the same menu item, navigating to the same opened view again. We have the same view instance, but `View.BeforeShowEvent` triggers again. +
If the `View.BeforeShowEvent` listener contains logic to add components or load data, it will be done performed, which could lead to adding duplicate components or reloading data.

[[ready-event]]
== ReadyEvent

`ReadyEvent` is the last event (after `View.BeforeShowEvent`) in the view opening process. In this event listener, you can make final configuration of the view according to loaded data and show notifications or dialogs.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=notifications-bean;ready-event]
----

NOTE: Consequent navigation to the same view that is currently open, leads to triggering `View.ReadyEvent` again for the same instance of the view. For example, the user navigates to a view for the first time, then a view instance is created and `View.ReadyEvent` triggers. Then, the user clicks on the same menu item, navigating to the same opened view again. We have the same view instance, but `View.ReadyEvent` triggers again. +
If the `View.ReadyEvent` listener contains logic to add components or load data, it will be done performed, which could lead to adding duplicate components or reloading data.

IMPORTANT: Both `BeforeShowEvent` and `ReadyEvent` work this way, because in case of navigation, they are fired by Vaadin's `BeforeEnterEvent` and `AfterNavigationEvent` lifecycle event handlers respectively.

[[attach-event]]
== AttachEvent

`AttachEvent` is fired after a view is attached to the UI.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=attach-event]
----

NOTE: This event is fired by Vaadin, since a view is a UI component too.

[[before-close-event]]
== BeforeCloseEvent

`BeforeCloseEvent` is the first event in the view closing process. The view is still displayed and fully functional. In this event listener, you can check any conditions and prevent closing using the `preventClose()` method of the event.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=before-close-event]
----

NOTE: If you prevent closing the view, in case of navigation you need to postpone it too. Check the type of action and if it's `NavigateCloseAction`, then obtain Vaadin's `BeforeLeaveEvent` and call its `postpone()` method. A more complex example that considering both *dialog* mode and *navigation* can be found in the `io.jmix.flowui.view.StandardDetailView#preventUnsavedChanges` method which handles the default `preventUnsavedChanges` logic.


[[after-close-event]]
== AfterCloseEvent

`AfterCloseEvent` is the second event (after `View.BeforeCloseEvent`) in the view closing process. In this event listener, you can show notifications or dialogs after closing the view, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=notifications-bean;after-close-event]
----

[[detach-event]]
== DetachEvent

`DetachEvent` is fired before a view is detached from the UI. This event listener can be used for releasing resources acquired by the view.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=detach-event]
----

NOTE: This event is fired by Vaadin, since a view is a UI component too.

[[query-parameters-change-event]]
== QueryParametersChangeEvent

`QueryParametersChangeEvent` is an event that informs which query parameters a view was opened with.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserListEventsView.java[tags=query-parameters-change-event]
----

[[init-entity-event]]
== InitEntityEvent

`InitEntityEvent` is fired in views inherited from xref:views/view-classes.adoc#standard-detail-view[StandardDetailView] before the new entity instance is set to edited entity container.

Use this event listener to initialize default values in the new entity instance, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserDetailEventsView.java[tags=init-entity-event]
----

[[validation-event]]
== ValidationEvent

`ValidationEvent` is fired in views inherited from `StandardDetailView` when the view is validated on saving the view xref:data/data-context.adoc[DataContext]. Use this event listener to perform additional validation of the view.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserDetailEventsView.java[tags=validation-event]
----

[[before-save-vent]]
== BeforeSaveEvent

`BeforeSaveEvent` is fired in views inherited from `StandardDetailView` before saving the view `DataContext`. Use this event listener to prevent saving, alter entity attribute values before saving or/and interact with the user before save.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserDetailEventsView.java[tags=before-save-event]
----
<1> - Interrupt the saving process if passwords do not match
<2> - Set encoded password to the entity

[[after-save-event]]
== AfterSaveEvent

`AfterSaveEvent` is fired in views inherited from `StandardDetailView` after saving the view `DataContext`. Use this event listener to notify users after save, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/user/UserDetailEventsView.java[tags=notifications-bean;after-save-event]
----