= ClipboardTrigger

++++
<div class="backoffice-ui-live-demo-container">
        <a href="https://demo.jmix.io/sampler/#main/1/sample?id=facet-clipboard-trigger" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`ClipboardTrigger` – это фасет, позволяющий пользователю копировать текст из поля в буфер обмена.

XML-имя компонента: `clipboardTrigger`.

[[basics]]
== Основы

`ClipboardTrigger` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

[[input]] 1. `input` - определяет `id` компонента, из которого будет скопирован текст. `ClipboardTrigger` можно связать со следующими компонентами:

* xref:vcl/components/masked-field.adoc[]
* xref:vcl/components/password-field.adoc[]
* xref:vcl/components/resizable-text-area.adoc[]
* xref:vcl/components/rich-text-area.adoc[]
* xref:vcl/components/text-area.adoc[]
* xref:vcl/components/text-field.adoc[]

[[button]] 2. `button` - определяет `id` xref:vcl/components/button.adoc[кнопки], инициирующей копирование.

[TIP]
С помощью метода `isSupportedByWebBrowser()` можно проверить, поддерживает ли браузер пользователя копирование.

Пример использования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/clipboardtrigger/clipboard-trigger-screen.xml[tags=usage-example]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/clipboardtrigger/ClipboardTriggerScreen.java[tags=clipboard-trigger-usage-example]
----

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[copy-event]]
=== CopyEvent

Это событие отправляется, когда пользователь нажимает на связанную с `ClipboardTrigger` кнопку, и имеет следующие методы:

* `isSuccess()` - возвращает `true`, если текстовое содержимое было успешно скопировано в буфер обмена на стороне клиента.
* `getSource()` - возвращает объект `ClipboardTrigger`, в котором произошло событие.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/clipboardtrigger/ClipboardTriggerScreen.java[tags=clipboard-trigger-copy-event]
----

Чтобы создать слушателя события программно, используйте метод фасета `addCopyListener()`.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

<<button, button>> -
xref:vcl/xml.adoc#id[id] -
<<input, input>>