= DataLoadCoordinator

`DataLoadCoordinator` facet is designed for triggering data loaders and for declarative linking of data loaders to data containers, visual components, and screen events.

Component’s XML-name: `dataLoadCoordinator`.

[[basics]]
== Basic Usage

To trigger all data loaders on screen's xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent] or fragment's xref:screens/screen-fragment-events.adoc#attach-event[AttachEvent], just add `DataLoadCoordinator` with `auto="true"` to the screen XML descriptor:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=basic]
----

[[working-modes]]
== Working Modes

You can configure `DataLoadCoordinator` to work in the automatic, manual or semi-automatic mode.

[[automatic-mode]]
=== Automatic Mode

In this mode, `DataLoadCoordinator` relies on parameter names with particular prefixes. The prefix denotes a component that produces the parameter value and changes events. If the loader has no parameters in its query text, although it can have parameters in query conditions, it is refreshed on `BeforeShowEvent` in `Screen` or `AttachEvent` in `ScreenFragment`.

By default, the parameter prefix is `container_` for data containers and `component_` for visual components. The <<component-prefix,componentPrefix>> and <<container-prefix,containerPrefix>> attributes allow you to use different prefixes.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=automatic-mode]
----

<1> Add XML schema for jpql conditions.
<2> There are no parameters in the query, so the `citiesDl` loader will be triggered on `BeforeShowEvent`.
<3> The `citiesDl` loader will also be triggered on `nameField` component value change.
As the condition uses the like clause, the value will be automatically wrapped in `'(?i)% %'` to provide the case-insensitive search.
<4> The `customersDl` is triggered on the `citiesDc` data container item change.

[[manual-mode]]
=== Manual Mode

In this mode, the nested <<refresh-element,refresh>> elements define when the data loaders must be triggered.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=manual-mode]
----

<1> Add XML schema for JPQL conditions.
<2> The `citiesDl` loader will be triggered on `InitEvent`.
<3> The `citiesDl` loader will also be triggered on the `nameField` component value change.
The `likeClause` attribute causes the value to be wrapped in `'(?i)% %'` to provide the case-insensitive search.
<4> The `customersDl` will be triggered on the `citiesDc` data container item change.

[[semi-automatic-mode]]
=== Semi-automatic Mode

When the `auto` attribute is set to `true`, and there are some manually configured triggers, `DataLoadCoordinator` will automatically configure all loaders having no manual configuration.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/semiautomaticmode/semi-automatic-mode-screen.xml[tags=semi-automatic-mode]
----

<1> The `customersDl` is configured automatically and triggered on the `brandsDc` data container item change.
<2> The `brandsDl` loader is configured manually and will be triggered on `AfterShowEvent`.

[[attributes]]
== Attributes

[[auto]]
* `auto` - defines `DataLoadCoordinator` working mode.
The default value is `false`.

[[component-prefix]]
* `componentPrefix` - defines a prefix for parameters which refer to xref:vcl/components.adoc[visual components] from which `DataLoadCoordinator` will take parameter values in automatic mode. The default value is `component_`.

[[container-prefix]]
* `containerPrefix` - defines a prefix for parameters which refer to xref:data/data-containers.adoc[data containers] from which `DataLoadCoordinator` will take parameter values in automatic mode. The default value is `container_`.

[[refresh-element]]
== Refresh Element

The `refresh` element allows you to define conditions for when a data loader must be refreshed.

[[loader]]
The only attribute of this element is `loader` that defines the loader's `id`.

The `refresh` element can have the following nested elements defining the triggering conditions:

[[on-component-value-changed]]
. `onComponentValueChanged` - to trigger the loader when the value of a visual component is changed. It has the following attributes:
+
--
[[component]]
* `component` - specifies the `id` of the visual component.

[[like-clause]]
* `likeClause` - if you use the `like` expression in query condition, you can define one of three possible search modes:
** `NONE` - the default value.
** `CASE_SENSITIVE` - uppercase and lowercase letters are treated as *distinct*.
** `CASE_INSENSITIVE` - uppercase and lowercase letters are treated as *equivalent*.

[[param-component]]
* `param` - specifies the query parameter name.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-component-value-changed]
----
--
[[on-container-item-changed]]
. `onContainerItemChanged` - to trigger the loader when the current item in a data container is changed. It has the following attributes:
+
--
[[container]]
* `container` - specifies the `id` of the data container.

[[param-container]]
* `param` - specifies the query parameter name.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-container-value-changed]
----
--
[[on-screen-event]]
. `onScreenEvent` - to trigger the loader on a screen event. It has the following attribute:
+
--
[[type-on-screen]]
* `type` - defines the type of the screen event. Possible values:
** `Init` - to trigger on xref:screens/screen-events.adoc#init-event[InitEvent].
** `AfterInit` - to trigger on xref:screens/screen-events.adoc#after-init-event[AfterInitEvent].
** `BeforeShow` - to trigger on xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent].
** `AfterShow` - to trigger on xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-screen-event]
----
--
[[on-fragment-event]]
. `onFragmentEvent` - to trigger the loader on a fragment event. It has the following attribute:
+
--
[[type-on-fragment]]
* `type` - defines the type of the screen fragment event. Possible values:
** `Init` - to trigger on xref:screens/screen-events.adoc#init-event[InitEvent].
** `AfterInit` - to trigger on xref:screens/screen-events.adoc#after-init-event[AfterInitEvent].
** `Attach` - to trigger on xref:screens/screen-fragment-events.adoc#attach-event [AttachEvent].

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-fragment-event]
----
--

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<auto , auto>> -
<<component-prefix, componentPrefix>> -
<<container-prefix, containerPrefix>> -
xref:vcl/xml.adoc#id[id]

[[data-load-coordinator-xml-elements]]
=== DataLoadCoordinator XML Elements

<<refresh-element, refresh>>

[[refresh-xml-attributes]]
=== Refresh XML Attributes

<<loader, loader>>

[[refresh-xml-elements]]
=== Refresh XML Elements

<<on-component-value-changed, onComponentValueChanged>> -
<<on-container-item-changed, onContainerItemChanged>> -
<<on-screen-event, onScreenEvent>> -
<<on-fragment-event, onFragmentEvent>>