= DataLoadCoordinator

`DataLoadCoordinator` – это фасет, предназначенный для запуска загрузчиков данных и для декларативного связывания загрузчиков данных с контейнерами данных, визуальными компонентами и событиями экрана.

XML-имя компонента: `dataLoadCoordinator`.

[[basics]]
== Основы использования

Чтобы запустить все загрузчики данных в xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent] экрана или xref:screens/screen-fragment-events.adoc#attach-event[AttachEvent] фрагмента, просто добавьте `DataLoadCoordinator` с `auto="true"` в XML-дескриптор экрана:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=basic]
----

[[working-modes]]
== Режимы работы

`DataLoadCoordinator` может работать в автоматическом, ручном или полуавтоматическом режиме.

[[automatic-mode]]
=== Автоматический режим

В этом режиме `DataLoadCoordinator` полагается на имена параметров, имеющие специальные префиксы. Префикс указывает, какой компонент является источником значения параметра и событий его изменения. Если у загрузчика нет параметров в тексте запроса (при этом параметры могут быть в условиях), то он срабатывает по событию `BeforeShowEvent` в `Screen` или по событию `attachEvent` в `ScreenFragment`.

По умолчанию используется префикс `container_` для контейнеров данных и `component_` для визуальных компонентов. Атрибуты <<component-prefix,componentPrefix>> и <<container-prefix,containerPrefix>> позволяют использовать другие префиксы.

Пример использования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=automatic-mode]
----

<1> Добавляет XML-схему для условий JPQL.
<2> В запросе нет параметров, поэтому загрузчик `citiesDl` сработает на событие `BeforeShowEvent`.
<3> Загрузчик `citiesDl` также сработает на изменение значения компонента `nameField`.
Так как условие использует оператор `like`, значение будет автоматически завернуто в `'(?i)% %'` для того, чтобы обеспечить нечувствительный к регистру поиск.
<4> Загрузчик `customersDl` сработает при смене выбранной сущности в контейнере `citiesDc`.

[[manual-mode]]
=== Ручной режим

В этом режиме вложенные элементы <<refresh-element,refresh>> определяют, когда должны сработать загрузчики.

Пример использования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=manual-mode]
----

<1> Добавляет XML-схему для условий JPQL.
<2> Загрузчик `citiesDl` сработает на событие `InitEvent`.
<3> Загрузчик `citiesDl` также сработает на изменение значения компонента `nameField`.
Атрибут `likeClause` приводит к заворачиванию значения в `'(?i)% %'` для того, чтобы обеспечить нечувствительный к регистру поиск.
<4> Загрузчик `customersDl` сработает при смене выбранной сущности в контейнере `citiesDc`.

[[semi-automatic-mode]]
=== Полуавтоматический режим

Когда атрибут `auto` установлен в `true` и объявлены некоторые вручную сконфигурированные связи, `DataLoadCoordinator` автоматически сконфигурирует все загрузчики, для которых не указано ни одной связи вручную.

Пример использования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/semiautomaticmode/semi-automatic-mode-screen.xml[tags=semi-automatic-mode]
----

<1> Загрузчик `customersDl` сконфигурирован автоматически и сработает при смене выбранной сущности в контейнере `brandsDc`.
<2> Загрузчик `brandsDl` сконфигурирован вручную и сработает на событие экрана `AfterShowEvent`.

[[attributes]]
== Атрибуты

[[auto]]
* `auto` - определяет режим работы `DataLoadCoordinator`.
Значение по умолчанию – `false`.

[[component-prefix]]
* `componentPrefix` - определяет префикс для параметров, обозначающих xref:vcl/components.adoc[визуальные компоненты], из которых `DataLoadCoordinator` будет принимать значения параметров в автоматическом режиме. Значение по умолчанию – `component_`.

[[container-prefix]]
* `containerPrefix` - определяет префикс для параметров, обозначающих xref:data/data-containers.adoc[контейнеры данных] из которых `DataLoadCoordinator` будет принимать значения параметров в автоматическом режиме. Значение по умолчанию – `container_`.

[[refresh-element]]
== Элемент refresh

Элемент `refresh` позволяет определить условия, при которых должен сработать загрузчик данных.

[[loader]]
Единственным атрибутом этого элемента является `loader`, определяющий `id` загрузчика.

Элемент `refresh` может содержать следующие вложенные элементы, определяющие условия срабатывания:

[[on-component-value-changed]]
. `onComponentValueChanged` – загрузчик срабатывает при изменении значения визуального компонента. Этот элемент имеет следующие атрибуты:
+
--
[[component]]
* `component` - задает `id` визуального компонента.

[[like-clause]]
* `likeClause` - если в условии запроса используется выражение `like`, можно задать один из трех возможных режимов поиска:
** `NONE` - значение по умолчанию.
** `CASE_SENSITIVE` - заглавные и строчные буквы обрабатываются как *различные*.
** `CASE_INSENSITIVE` - заглавные и строчные буквы обрабатываются как *эквивалентные*.

[[param-component]]
* `param` - задает имя параметра запроса.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-component-value-changed]
----
--
[[on-container-item-changed]]
. `onContainerItemChanged` - загрузчик срабатывает при изменении текущего элемента в контейнере данных. Этот элемент имеет следующие атрибуты:
+
--
[[container]]
* `container` - задает `id` контейнера данных.

[[param-container]]
* `param` - задает имя параметра запроса.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-container-value-changed]
----
--
[[on-screen-event]]
. `onScreenEvent` - загрузчик срабатывает по событию экрана. Этот элемент имеет следующие атрибуты:
+
--
[[type-on-screen]]
* `type` - определяет тип экранного события. Возможные значения:
** `Init` - срабатывание по xref:screens/screen-events.adoc#init-event[InitEvent].
** `AfterInit` - срабатывание по on xref:screens/screen-events.adoc#after-init-event[AfterInitEvent].
** `BeforeShow` - срабатывание по xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent].
** `AfterShow` - срабатывание по xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-screen-event]
----
--
[[on-fragment-event]]
. `onFragmentEvent` - загрузчик срабатывает по событию фрагмента экрана. Этот элемент имеет следующий атрибут:
+
--
[[type-on-fragment]]
* `type` - определяет тип события фрагмента. Возможные значения:
** `Init` - срабатывание по xref:screens/screen-events.adoc#init-event[InitEvent].
** `AfterInit` - срабатывание по xref:screens/screen-events.adoc#after-init-event[AfterInitEvent].
** `Attach` - срабатывание по xref:screens/screen-fragment-events.adoc#attach-event [AttachEvent].

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-fragment-event]
----
--

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

<<auto, auto>> -
<<component-prefix, componentPrefix>> -
<<container-prefix, containerPrefix>> -
xref:vcl/xml.adoc#id[id]

[[data-load-coordinator-xml-elements]]
=== XML-элементы DataLoadCoordinator

<<refresh-element, refresh>>

[[refresh-xml-attributes]]
=== XML-атрибуты Refresh

<<loader, loader>>

[[refresh-xml-elements]]
=== XML-элементы Refresh

<<on-component-value-changed, onComponentValueChanged>> -
<<on-container-item-changed, onContainerItemChanged>> -
<<on-screen-event, onScreenEvent>> -
<<on-fragment-event, onFragmentEvent>>