= DataLoadCoordinator
:page-aliases: backoffice-ui:facets/data-load-coordinator.adoc

`DataLoadCoordinator` facet 支持触发数据加载，以及声明式的将数据加载器和数据容器、可视化组件、界面事件进行连接。

组件的 XML 名称：`dataLoadCoordinator`。

[[basics]]
== 基本用法

如需在界面的 xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent] 或 fragment 的 xref:screens/screen-fragment-events.adoc#attach-event[AttachEvent] 事件触发所有的数据加载器，只需在界面的 XML 描述中添加 `DataLoadCoordinator`，其属性 `auto="true"`：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=basic]
----

[[working-modes]]
== 工作模式

可以配置 `DataLoadCoordinator` 在自动、手动或半自动模式下工作。

[[automatic-mode]]
=== 自动模式

此模式中，`DataLoadCoordinator` 依赖使用特定前缀的参数名称。前缀表示提供参数和事件的组件。如果加载器的查询语句中没有参数（尽管在查询条件中可能有参数），则该加载器会在 `界面` 的`BeforeShowEvent` 或 `界面 fragment` 的 `AttachEvent` 中自动刷新。

默认情况下，数据容器的参数前缀是 `container_`，可视化组件的参数前缀是 `component_`。通过 <<component-prefix,componentPrefix>> 和 <<container-prefix,containerPrefix>> 属性可以使用不同的前缀。

示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=automatic-mode]
----

<1> 添加支持 JPQL 条件的 schema。
<2> 查询中没有参数，所以 `citiesDl` 加载器会在 `BeforeShowEvent` 触发。
<3> `citiesDl` 加载器也会在 `nameField` 组件值更改的时候触发。由于条件使用了 `like` 子句，组件值会被自动包装在 `'(?i)% %'` 中，提供大小写不敏感搜索。
<4> `customersDl` 加载器会在 `citiesDc` 数据容器内容变化时触发。

[[manual-mode]]
=== 手动模式

此模式中，内部的 <<refresh-element,refresh>> 元素定义数据加载器何时触发刷新。

示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=manual-mode]
----

<1> 添加支持 JPQL 条件的 schema。
<2> `citiesDl` 加载器会在 `InitEvent` 事件触发。
<3> `citiesDl` 加载器会在 `nameField` 组件值更改的时候触发。由于条件 `likeClause` 属性，组件值会被自动包装在 `'(?i)% %'` 中，提供大小写不敏感搜索。
<4> `customersDl` 加载器会在 `citiesDc` 数据容器内容变化时触发。

[[semi-automatic-mode]]
=== 半自动模式

当 `auto` 属性设置为 `true` 并且也有一些手动配置的触发器，`DataLoadCoordinator` 会为所有没有手动配置的加载器做自动配置。

示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/semiautomaticmode/semi-automatic-mode-screen.xml[tags=semi-automatic-mode]
----

<1> `customersDl` 加载器配置在 `brandsDc` 数据容器内容变化时自动触发。
<2> `brandsDl` 为手动配置，在 `AfterShowEvent` 事件触发。

[[attributes]]
== 属性

[[auto]]
* `auto` - 定义 `DataLoadCoordinator` 的工作模式。默认为 `false`。

[[component-prefix]]
* `componentPrefix` - 定义 xref:vcl/components.adoc[可视化组件] 引用参数的前缀，自动模式下，`DataLoadCoordinator` 从参数定义的组件中获取参数值。默认值为 `component_`。

[[container-prefix]]
* `containerPrefix` - 定义 xref:data/data-containers.adoc[数据容器] 引用参数的前缀，自动模式下，`DataLoadCoordinator` 从参数定义的容器中获取参数值。默认值为 `container_`。

[[refresh-element]]
== refresh 元素

`refresh` 元素支持为数据加载器定义刷新的条件。

[[loader]]
该元素的唯一属性是 `loader`，定义加载器的 `id`。

`refresh` 元素可以有下列内部的元素，用于定义触发条件：

[[on-component-value-changed]]
. `onComponentValueChanged` - 当可视化组价的值改变时触发加载器。有下列属性：
+
--
[[component]]
* `component` - 指定可视化组件的 `id`。

[[like-clause]]
* `likeClause` - 如果在查询条件中使用 `like` 表达式，可以定义下面三种搜索模式之一：
** `NONE` - 默认值。
** `CASE_SENSITIVE` - 大小写敏感。
** `CASE_INSENSITIVE` - 大小写不敏感。

[[param-component]]
* `param` - 指定查询参数名称。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-component-value-changed]
----
--
[[on-container-item-changed]]
. `onContainerItemChanged` - 当数据容器中的内容改变时触发加载器。有下列属性：
+
--
[[container]]
* `container` - 指定数据容器的 `id`。

[[param-container]]
* `param` - 指定查询参数名称。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-container-value-changed]
----
--
[[on-screen-event]]
. `onScreenEvent` - 在界面事件中触发加载器。有下列属性：
+
--
[[type-on-screen]]
* `type` - 定义界面事件的类型，可能值：
** `Init` - 在 xref:screens/screen-events.adoc#init-event[InitEvent] 事件中触发。
** `AfterInit` - 在 xref:screens/screen-events.adoc#after-init-event[AfterInitEvent] 事件中触发。
** `BeforeShow` - 在 xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent] 事件中触发。
** `AfterShow` - 在 xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] 事件中触发。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-screen-event]
----
--
[[on-fragment-event]]
. `onFragmentEvent` - 在 fragment 事件中触发加载器。有下列属性：
+
--
[[type-on-fragment]]
* `type` - 定义界面 fragment 事件的类型，可能值：
** `Init` - 在 xref:screens/screen-events.adoc#init-event[InitEvent] 事件中触发。
** `AfterInit` - 在 xref:screens/screen-events.adoc#after-init-event[AfterInitEvent] 事件中触发。
** `Attach` - 在 xref:screens/screen-fragment-events.adoc#attach-event [AttachEvent] 事件中触发。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-fragment-event]
----
--

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

<<auto , auto>> -
<<component-prefix, componentPrefix>> -
<<container-prefix, containerPrefix>> -
xref:vcl/xml.adoc#id[id]

[[data-load-coordinator-xml-elements]]
=== DataLoadCoordinator XML 元素

<<refresh-element, refresh>>

[[refresh-xml-attributes]]
=== Refresh XML 属性

<<loader, loader>>

[[refresh-xml-elements]]
=== Refresh XML 元素

<<on-component-value-changed, onComponentValueChanged>> -
<<on-container-item-changed, onContainerItemChanged>> -
<<on-screen-event, onScreenEvent>> -
<<on-fragment-event, onFragmentEvent>>
