= EditorScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`EditorScreenFacet` – это, по сути, xref:facets/screen-facet.adoc[] с расширенным набором опций для открытия экранов редактирования сущностей.

XML-имя компонента: `editorScreen`.

[[attributes]]
== Атрибуты

В дополнение к xref:facets/screen-facet.adoc#xml[атрибутам] `ScreenFacet`, `EditorScreenFacet` имеет следующие собственные атрибуты:

[[add-first]]
* `addFirst` - определяет, будет ли новый элемент добавлен в начало или конец коллекции. Это влияет только на автономные контейнеры; во вложенных контейнерах новые элементы всегда добавляются в конец.

[[container]]
* `container` - задает xref:data/collection-container.adoc[]. Контейнер обновляется после коммита экрана. Если контейнер вложенный, фреймворк автоматически инициализирует ссылку на родительский объект и настраивает контекст данных для редактирования композиций.

[[edit-mode]]
* `editMode` - устанавливает режим редактирования экрана, соответствует перечислению `EditMode`:
** `CREATE` - для создания нового экземпляра сущности;
** `EDIT` - для редактирования существующего.

[[entity-class]]
* `entityClass` - полное имя класса сущности.

[[field]]
* `field` - задает id компонента xref:vcl/components/entity-picker.adoc[]. Если поле задано, фреймворк устанавливает в него закоммиченную сущность после успешного коммита редактора.

[[list-component]]
* `listComponent` - задает id компонента-списка. Он используется для получения контейнера, если тот не задан. Обычно это компонент xref:vcl/components/table.adoc[] или xref:vcl/components/data-grid.adoc[], отображающий список сущностей.

Пример использования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/editorscreenfacet/editor-screen-facet-screen.xml[tags=editor-screen-facet]
----

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` отправляется после закрытия настраиваемого фасетом экрана. Подробнее см. в xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent].

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` отправляется после отображения настраиваемого фасетом экрана. Подробнее см. в xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[[entity-provider]]
=== EntityProvider

Метод делегата `EntityProvider`  позволяет передать экземпляр сущности на открывающийся экран:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/editorscreenfacet/EditorScreenFacetScreen.java[tags=entity-provider]
----

Чтобы создать слушателя события программно, используйте метод `setEntityProvider()`.

[[initializer]]
=== Initializer

Слушатель `Initializer` принимает новый экземпляр сущности и может инициализировать его перед отображением на экране редактора. Подробнее см. в xref:actions/standard-actions/create-action.adoc#initializer[Initializer].

Чтобы создать слушателя события программно, используйте метод `setInitializer()`.

[[options-provider]]
=== OptionsProvider

См. xref:facets/screen-facet.adoc#options-provider[OptionsProvider].

[[parent-data-context-provider]]
=== ParentDataContextProvider

Метод делегата `ParentDataContextProvider` позволяет передать xref:data/data-context.adoc#parent-data-context[родительский  DataContext] в открывающийся экран:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/editorscreenfacet/EditorScreenFacetScreen.java[tags=data-context]
----

Чтобы задать провайдер родительского `DataContext` программно, используйте метод `setParentDataContextProvider()`.

[[screen-configurer]]
=== ScreenConfigurer

См. xref:facets/screen-facet.adoc#screen-configurer[ScreenConfigurer].

[[transformation]]
=== Transformation

Этот слушатель вызывается после выбора и валидации сущности в экране редактора. Подробнее см. в xref:actions/standard-actions/create-action.adoc#transformation[Transformation].

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

<<add-first, addFirst>> -
<<container, container>> -
<<entity-class, entityClass>> -
<<edit-mode, entityMode>> -
<<field, field>> -
xref:vcl/xml.adoc#id[id] -
<<list-component, listComponent>> -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]