= EditorScreenFacet
:page-aliases: backoffice-ui:facets/editor-screen-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`EditorScreenFacet` 本质上是一个 xref:facets/screen-facet.adoc[]，但是添加了一组选项，用于打开实体编辑界面。

组件的 XML 名称：`editorScreen`。

[[attributes]]
== 属性

除了支持 `ScreenFacet` 的 xref:facets/screen-facet.adoc#attributes[属性] 外，`EditorScreenFacet` 新增了下列自有属性：

[[add-first]]
* `addFirst` - 定义一个新 item 添加的位置，是集合的开始还是结尾。只影响单独的容器，对内部嵌套容器来说，新 item 总是添加至尾部。

[[container]]
* `container` - 设置 xref:data/collection-container.adoc[]。当界面提交时会更新该容器。如果是内部嵌套容器，框架会自动初始化父实体的引用并设置编辑组件的数据上下文。

[[edit-mode]]
* `editMode` - 设置界面的编辑模式，对应于 `EditMode` 枚举：
** `CREATE` - 新建实体实例。
** `EDIT` - 编辑已有实例。

[[entity-class]]
* `entityClass` - 实体类的全限定名。

[[field]]
* `field` - 设置 xref:vcl/components/entity-picker.adoc[] 组件的 id。如果设置了该字段，框架会在编辑器成功提交后，将提交的实体设置到这个 Field 上。

[[list-component]]
* `listComponent` - 设置列表组件 id。如果没设置数据容器，则通过列表组件获取。通常，列表组件是 xref:vcl/components/table.adoc[] 或 xref:vcl/components/data-grid.adoc[]。

示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/editorscreenfacet/editor-screen-facet-screen.xml[tags=editor-screen-facet]
----

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` 在 facet 配置的界面之后关闭发送。参阅 xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent] 了解细节。

如需以编程的方式注册事件处理器，使用 `addAfterCloseEventListener()` 方法。

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` 在 facet 配置的界面展示之后发送。参阅 xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] 了解细节。

如需以编程的方式注册事件处理器，使用 `addAfterShowEventListener()` 方法。

[[options-provider]]
=== OptionsProvider

参阅 xref:facets/screen-facet.adoc#options-provider[OptionsProvider]。

编程式用法，调用 `setOptionsProvider()` 方法。

[[initializer]]
=== Initializer

是一个处理器，可以接收新实体实例，并在其展示到编辑界面之前初始化该实体。参阅 xref:actions/standard-actions/create-action.adoc#initializer[Initializer] 了解细节。

编程式用法，调用 `setInitializer()` 方法。

[[transformation]]
=== Transformation

是一个处理器，在编辑界面选择实体并验证后调用。参阅 xref:actions/standard-actions/create-action.adoc#transformation[Transformation] 了解细节。

编程式用法，调用 `setTransformation()` 方法。

[[entity-provider]]
=== EntityProvider

`EntityProvider` 代理方法支持为打开的界面传递一个实体实例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/editorscreenfacet/EditorScreenFacetScreen.java[tags=entity-provider]
----

编程式用法，调用 `setEntityProvider()` 方法。

[[parent-data-context-provider]]
=== ParentDataContextProvider

`ParentDataContextProvider` 代理方法支持为打开的界面传递一个 xref:data/data-context.adoc#parent-data-context[父数据上下文]：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/editorscreenfacet/EditorScreenFacetScreen.java[tags=data-context]
----

编程式用法，调用 `setParentDataContextProvider()` 方法。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

<<add-first, addFirst>> -
<<container, container>> -
<<entity-class, entityClass>> -
<<edit-mode, entityMode>> -
<<field, field>> -
xref:vcl/xml.adoc#id[id] -
<<list-component, listComponent>> -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]
