= InputDialogFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`InputDialogFacet` предоставляет вам альтернативный способ настройки и открытия xref:dialogs.adoc#input-dialog[диалогового окна ввода]. Вместо использования метода `Dialogs.createInputDialog()` в контроллере экрана вы можете настроить `InputDialogFacet` в XML-дескрипторе с помощью визуального дизайнера Studio.

XML-имя компонента: `inputDialog`.

[[attributes]]
== Атрибуты

`InputDialogFacet` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

[[dialog-actions]]
* `dialogActions` - позволяет добавлять в диалоговое окно наиболее часто используемые действия с соответствующими кнопками. Возможны следующие значения:
** `OK_CANCEL` - добавляет кнопки *OK* и *Cancel*. Значение по умолчанию.
** `OK` - добавляет кнопку *OK*.
** `YES_NO` - добавляет кнопки *Yes* и *No*.
** `YES_NO_CANCEL` - добавляет кнопки *Yes*, *No*, и *Cancel*.

* `onAction` - определяет id xref:actions.adoc[действия], который должен вызвать открытие диалогового окна.

* `onButton` - определяет id xref:vcl/components/button.adoc[кнопки], которая должна вызвать открытие диалогового окна.

[[actions]]
== Действия

См. xref:facets/option-dialog-facet.adoc#actions[действия OptionDialogFacet].

[[parameters]]
== Параметры

Чтобы добавить поля ввода в диалоговое окно, создайте перечисленные ниже вложенные элементы внутри элемента `parameters`. Для каждого параметра будет создан соответствующий xref:vcl/components.adoc[визуальный компонент] для ввода значения.

[cols="1,2"]
|===
|Параметр |Визуальный компонент

|`bigDecimalParameter`
|xref:vcl/components/text-field.adoc[] с xref:vcl/components/text-field.adoc#data-type[data type] `decimal`

|`dateParameter`
|xref:vcl/components/date-field.adoc[] с xref:vcl/components/date-field.adoc#resolution[resolution] `DAY`

|`dateTimeParameter`
|xref:vcl/components/date-field.adoc[] с xref:vcl/components/date-field.adoc#resolution[resolution] `MIN`

|`doubleParameter`
|xref:vcl/components/text-field.adoc[] с xref:vcl/components/text-field.adoc#data-type[data type] `double`

|`intParameter`
|xref:vcl/components/text-field.adoc[] с xref:vcl/components/text-field.adoc#data-type[data type] `int`

|`longParameter`
|xref:vcl/components/text-field.adoc[] с xref:vcl/components/text-field.adoc#data-type[data type] `long`

|`stringParameter`
|xref:vcl/components/text-field.adoc[]

|`timeParameter`
|xref:vcl/components/time-field.adoc[]

|===

Все описанные выше параметры имеют атрибут `defaultValue` для установки значения по умолчанию для соответствующего поля.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;big-decimal-parameter;parameters-end]
----

* Используйте `entityParameter` для отображения xref:vcl/components/entity-picker.adoc[]. Чтобы определить класс сущности для соответствующего поля, используйте атрибут `entityClass`.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;entity-parameter;parameters-end]
----

* Используйте `enumParameter` для отображения xref:vcl/components/combo-box.adoc[]. Чтобы определить класс enum для соответствующего поля, используйте атрибут `enumClass`.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;enum-parameter;parameters-end]
----

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[input-dialog-close-event]]
=== InputDialogCloseEvent

`InputDialogCloseEvent` отправляется при закрытии диалогового окна. С помощью метода `InputDialogCloseEvent.closedWith()` можно отслеживать, как был закрыт диалог:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=notifications;input-dialog-close-event]
----

Чтобы создать слушателя события программно, используйте метод `addCloseListener()`.

[[dialog-result-handler]]
=== DialogResultHandler

Метод делегата `DialogResultHandler` позволяет обрабатывать результаты диалогового окна ввода:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=notifications;dialog-result-handler]
----

Чтобы использовать его программно, вызовите метод `setDialogResultHandler()`.

[[validator]]
=== Validator

Метод делегата `Validator` позволяет проверять входные значения. Он принимает определенный `InputDialog.ValidationContext`, содержащий введенные значения. Метод должен возвращать экземпляр `ValidationErrors`, который включает описания ошибок. Эти ошибки будут показаны в уведомлении с другими исключениями проверки.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=validator]
----

Чтобы использовать его программно, вызовите метод `setValidator()`.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
<<dialog-actions, dialogActions>> -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#id[id] -
xref:facets/message-dialog-facet.adoc#on-action[onAction] -
xref:facets/message-dialog-facet.adoc#on-button[onButton] -
xref:vcl/xml.adoc#width[width]