= InputDialogFacet
:page-aliases: backoffice-ui:facets/input-dialog-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`InputDialogFacet` 提供另一种配置和打开 xref:dialogs.adoc#input-dialog[输入对话框] 的方法。通过 Studio 可视化设计器的帮助，可以在 XML 描述中配置 `InputDialogFacet`，而无需在界面控制器使用 `Dialogs.createInputDialog()` 方法。

组件的 XML 名称：`inputDialog`.

[[attributes]]
== 属性

`InputDialogFacet` 在界面 XML 描述的 `facets` 元素中定义，有下列属性：

[[dialog-actions]]
* `dialogActions` - 在对话框中添加最常用的操作按钮。可能值：
** `OK_CANCEL` -添加 *OK* 和 *Cancel* 按钮。默认值。
** `OK` -添加 *OK* 按钮
** `YES_NO` -添加 *Yes* 和 *No* 按钮。
** `YES_NO_CANCEL` -添加 *Yes*、*No* 和 *Cancel* 按钮。

* `onAction` - 定义一个 xref:actions.adoc[action] 的 id，用于打开对话框。

* `onButton` - 定义一个 xref:vcl/components/button.adoc[button] 的 id，用于打开对话框。

[[actions]]
== 操作

参阅 xref:facets/option-dialog-facet.adoc#actions[actions]。

[[parameters]]
== 参数

如需在对话框内添加输入控件，可以在 `parameters` 元素中创建下列子元素。框架会为每个参数创建对应的 xref:vcl/components.adoc[可视化组件]，用于输入。

[cols="1,2"]
|===
|参数 |可视化组件

|`bigDecimalParameter`
|xref:vcl/components/text-field.adoc[]，`decimal` xref:vcl/components/text-field.adoc#data-type[数据类型]

|`dateParameter`
|xref:vcl/components/date-field.adoc[]，`DAY` xref:vcl/components/date-field.adoc#resolution[精度]

|`dateTimeParameter`
|xref:vcl/components/date-field.adoc[]，`MIN` xref:vcl/components/date-field.adoc#resolution[精度]

|`doubleParameter`
|xref:vcl/components/text-field.adoc[]，`double` xref:vcl/components/text-field.adoc#data-type[数据类型]

|`intParameter`
|xref:vcl/components/text-field.adoc[]，`int` xref:vcl/components/text-field.adoc#data-type[数据类型]

|`longParameter`
|xref:vcl/components/text-field.adoc[]，`long` xref:vcl/components/text-field.adoc#data-type[数据类型]

|`stringParameter`
|xref:vcl/components/text-field.adoc[]

|`timeParameter`
|xref:vcl/components/time-field.adoc[]

|===

上面列举的所有参数都有 `defaultValue` 属性，支持为对应的控件设置默认值。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;big-decimal-parameter;parameters-end]
----

* 用 `entityParameter` 展示 xref:vcl/components/entity-picker.adoc[]。如需为控件定义实体类，使用 `entityClass` 属性。
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;entity-parameter;parameters-end]
----

* 用 `enumParameter` 展示 xref:vcl/components/combo-box.adoc[]。如需为控件定义枚举类，使用 `enumClass` 属性。
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/inputdialogfacet/input-dialog-facet-screen.xml[tags=parameters-start;enum-parameter;parameters-end]
----

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

[[input-dialog-close-event]]
=== InputDialogCloseEvent

`InputDialogCloseEvent` 在对话框关闭后发送。使用 `InputDialogCloseEvent.closedWith()` 方法，可以跟踪窗口是如何关闭的：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=notifications;input-dialog-close-event]
----

如需以编程的方式注册事件处理器，使用 `addCloseListener()` 方法。

[[dialog-result-handler]]
=== DialogResultHandler

`DialogResultHandler` 代理方法支持处理输入对话框的结果：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=notifications;dialog-result-handler]
----

编程式用法，调用 `setDialogResultHandler()` 方法。

[[validator]]
=== Validator

`Validator` 代理方法支持验证输入值。接收特定的 `InputDialog.ValidationContext`，其中包含输入的值。方法需要返回 `ValidationErrors` 实例，描述错误信息。错误会与其他验证异常一起在通知窗口展示。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/inputdialogfacet/InputDialogFacetScreen.java[tags=validator]
----

编程式用法，调用 `setValidator()` 方法。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
<<dialog-actions, dialogActions>> -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#id[id] -
xref:facets/message-dialog-facet.adoc#on-action[onAction] -
xref:facets/message-dialog-facet.adoc#on-button[onButton] -
xref:vcl/xml.adoc#width[width]
