= LookupScreenFacet
:page-aliases: backoffice-ui:facets/lookup-screen-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`LookupScreenFacet` 本质上是一个 xref:facets/screen-facet.adoc[]，但是添加了一组选项，用于打开实体查找界面。

组件的 XML 名称：`lookupScreen`。

[[attributes]]
== 属性

除了支持 `ScreenFacet` 的 xref:facets/screen-facet.adoc#attributes[属性] 外，`LookupScreenFacet` 具有 xref:facets/editor-screen-facet.adoc[] 的下列属性：

[[container]]
* xref:facets/editor-screen-facet.adoc#container[container]

[[entity-class]]
* xref:facets/editor-screen-facet.adoc#entity-class[entityClass]

[[field]]
* xref:facets/editor-screen-facet.adoc#field[field]

[[list-components]]
* xref:facets/editor-screen-facet.adoc#list-component[listComponents]

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` 在 facet 配置的界面之后关闭发送。参阅 xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent] 了解细节。

如需以编程的方式注册事件处理器，使用 `addAfterCloseEventListener()` 方法。

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` 在 facet 配置的界面展示之后发送。参阅 xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] 了解细节。

如需以编程的方式注册事件处理器，使用 `addAfterShowEventListener()` 方法。

[[options-provider]]
=== OptionsProvider

参阅 xref:facets/screen-facet.adoc#options-provider[OptionsProvider]。

编程式用法，调用 `setOptionsProvider()` 方法。

[[transformation]]
=== Transformation

是一个处理器，在查找界面选择实体并验证后调用。参阅 xref:actions/standard-actions/create-action.adoc#transformation[Transformation] 了解细节。

编程式用法，调用 `setTransformation()` 方法。

[[select-validator]]
=== SelectValidator

是一个处理器，在查找界面点击 *Select* 时调用。参阅 xref:actions/standard-actions/entity-lookup-action.adoc#select-validator[SelectValidator] 了解细节。

编程式用法，调用 `setSelectValidator()` 方法。

[[select-handler]]
=== SelectHandler

`SelectHandler` 代理方法支持获取查找界面选择的实体集合。下面例子中，点击按钮打开 `Customer` 实体的查找界面，所选 customer 的 email 写入 `textField`：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/lookupscreenfacet/lookup-screen-facet-screen.xml[tags=lookup]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/lookupscreenfacet/LookupScreenFacetScreen.java[tags=select-handler]
----

编程式用法，调用 `setSelectHandler()` 方法。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

xref:facets/editor-screen-facet.adoc#container[container] -
xref:facets/editor-screen-facet.adoc#entity-class[entityClass] -
xref:facets/editor-screen-facet.adoc#field[field] -
xref:vcl/xml.adoc#id[id] -
xref:facets/editor-screen-facet.adoc#list-component[listComponent] -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]
