= LookupScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`LookupScreenFacet` is essentially a xref:facets/screen-facet.adoc[] with an extended set of options for opening entity lookup screens.

Component’s XML-name: `lookupScreen`.

[[attributes]]
== Attributes

In addition to the xref:facets/screen-facet.adoc#attributes[attributes] of `ScreenFacet`, `LookupScreenFacet` has the following attributes of xref:facets/editor-screen-facet.adoc[]:

[[container]]
* xref:facets/editor-screen-facet.adoc#container[container]

[[entity-class]]
* xref:facets/editor-screen-facet.adoc#entity-class[entityClass]

[[field]]
* xref:facets/editor-screen-facet.adoc#field[field]

[[list-components]]
* xref:facets/editor-screen-facet.adoc#list-component[listComponents]

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` is sent after the screen configured by the facet is closed. See xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent] for details.

Programmatic registration of the event handler: use the `addAfterCloseEventListener()` method.

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` is sent after the screen configured by the facet is shown. See xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] for details.

Programmatic registration of the event handler: use the `addAfterShowEventListener()` method.

[[options-provider]]
=== OptionsProvider

See xref:facets/screen-facet.adoc#options-provider[OptionsProvider].

Programmatic usage: call the `setOptionsProvider()` method.

[[transformation]]
=== Transformation

It is a handler that is invoked after entities are selected and validated in the lookup screen. See xref:actions/standard-actions/create-action.adoc#transformation[Transformation] for details.

Programmatic usage: call the `setTransformation()` method.

[[select-validator]]
=== SelectValidator

It is a handler that is invoked when the user clicks *Select* in the lookup screen. See xref:actions/standard-actions/entity-lookup-action.adoc#select-validator[SelectValidator] for details.

Programmatic usage: call the `setSelectValidator()` method.

[[select-handler]]
=== SelectHandler

The `SelectHandler` delegate method allows you to get the collection of selected entities from the lookup screen. In the example below, the lookup screen of the `Customer` entity is opened on button clicks, and the email of the selected customer is written to the `textField`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/lookupscreenfacet/lookup-screen-facet-screen.xml[tags=lookup]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/lookupscreenfacet/LookupScreenFacetScreen.java[tags=select-handler]
----

Programmatic usage: call the `setSelectHandler()` method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:facets/editor-screen-facet.adoc#container[container] -
xref:facets/editor-screen-facet.adoc#entity-class[entityClass] -
xref:facets/editor-screen-facet.adoc#field[field] -
xref:vcl/xml.adoc#id[id] -
xref:facets/editor-screen-facet.adoc#list-component[listComponent] -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]