= LookupScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`LookupScreenFacet` - это, по сути, xref:facets/screen-facet.adoc[] с расширенным набором опций для открытия экранов поиска сущностей.

XML-имя компонента: `lookupScreen`.

[[attributes]]
== Атрибуты

В дополнение к xref:facets/screen-facet.adoc#xml[атрибутам] `ScreenFacet`, `LookupScreenFacet` имеет следующие атрибуты xref:facets/editor-screen-facet.adoc[]:

[[container]]
* xref:facets/editor-screen-facet.adoc#container[container]

[[entity-class]]
* xref:facets/editor-screen-facet.adoc#entity-class[entityClass]

[[field]]
* xref:facets/editor-screen-facet.adoc#field[field]

[[list-components]]
* xref:facets/editor-screen-facet.adoc#list-component[listComponents]

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` отправляется после закрытия настраиваемого фасетом экрана. Подробнее см. в xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent].

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` отправляется после отображения настраиваемого фасетом экрана. Подробнее см. в xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[[options-provider]]
=== OptionsProvider

См. xref:facets/screen-facet.adoc#options-provider[OptionsProvider].

[[screen-configurer]]
=== ScreenConfigurer

См. xref:facets/screen-facet.adoc#screen-configurer[ScreenConfigurer].

[[select-handler]]
=== SelectHandler

Метод делегата `SelectHandler` позволяет получить коллекцию выбранных сущностей из экрана поиска. В приведенном ниже примере экран поиска сущности `Customer` открывается при нажатии кнопки, и электронная почта выбранного клиента записывается в `textField`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/lookupscreenfacet/lookup-screen-facet-screen.xml[tags=lookup]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/lookupscreenfacet/LookupScreenFacetScreen.java[tags=select-handler]
----

Чтобы создать слушателя события программно, используйте метод `setSelectHandler()`.

[[select-validator]]
=== SelectValidator

Слушатель `SelectValidator` вызывается, когда пользователь нажимает *Select* на экране поиска. Подробнее см. в xref:actions/standard-actions/entity-lookup-action.adoc#select-validator[SelectValidator].

Чтобы создать слушателя события программно, используйте метод `setSelectValidator()`.

[[transformation]]
=== Transformation

Этот слушатель вызывается после выбора и валидации сущности в экране выбора. Подробнее см. в xref:actions/standard-actions/create-action.adoc#transformation[Transformation].

Чтобы создать слушателя события программно, используйте метод `setTransformation()`.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

xref:facets/editor-screen-facet.adoc#container[container] -
xref:facets/editor-screen-facet.adoc#entity-class[entityClass] -
xref:facets/editor-screen-facet.adoc#field[field] -
xref:vcl/xml.adoc#id[id] -
xref:facets/editor-screen-facet.adoc#list-component[listComponent] -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]