= MessageDialogFacet
:page-aliases: backoffice-ui:facets/message-dialog-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`MessageDialogFacet` 提供另一种配置和打开 xref:dialogs.adoc#message-dialog[消息对话框] 的方法。通过 Studio 可视化设计器的帮助，可以在 XML 描述中配置 `MessageDialogFacet`，而无需在界面控制器使用 `Dialogs.createMessageDialog()` 方法。


组件的 XML 名称：`messageDialog`。

[[basics]]
== 基本用法

下面例子中，当用户点击 `messageDialogBtn` 按钮时，打开消息对话框：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/messagedialogfacet/message-dialog-facet-screen.xml[tags=facets-start;button-message;facets-end;layout-start;message-btn;layout-end]
----

`MessageDialogFacet` 在界面 XML 描述的 `facets` 元素中定义，有下列属性：

* xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside]
* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-modal[modal]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]

`MessageDialogFacet` 可以绑定至 xref:vcl/components/button.adoc[button] 或 xref:actions.adoc[action]，通过按钮点击或执行操作打开对话框。

[[on-action]]
* `onAction` - 定义一个 xref:actions.adoc[action] 的 id，用于打开对话框。

[[on-button]]
* `onButton` - 定义一个 xref:vcl/components/button.adoc[button] 的 id，用于打开对话框。

另外，还可以使用 `MessageDialogFacet.show()` 方法显示对话框：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/messagedialogfacet/MessageDialogFacetScreen.java[tags=show]
----

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:dialogs.adoc#msg-dialog-modal[modal] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]
