= MessageDialogFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`MessageDialogFacet` предоставляет вам альтернативный способ настройки и открытия диалогового окна сообщений. Вместо использования метода `Dialogs.createMessageDialog()` в контроллере экрана вы можете настроить `MessageDialogFacet` в XML-дескрипторе с визуального дизайнера Studio.

XML-имя компонента: `messageDialog`.

[[basics]]
== Основы

В приведенном ниже примере диалоговое окно сообщения откроется, когда пользователь нажмет кнопку `messageDialogBtn`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/messagedialogfacet/message-dialog-facet-screen.xml[tags=facets-start;button-message;facets-end;layout-start;message-btn;layout-end]
----


`MessageDialogFacet` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

* xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside]
* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-modal[modal]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]

Вы можете привязать `MessageDialogFacet` к xref:vcl/components/button.adoc[кнопке] или xref:actions.adoc[действию], чтобы открывать диалоговое окно по нажатию кнопки или выполнению действия.

[[on-action]]
* `onAction` - определяет id xref:actions.adoc[действия], которое должно вызвать открытие диалогового окна.

[[on-button]]
* `onButton` - определяет id xref:vcl/components/button.adoc[кнопки], которая должна вызвать открытие диалогового окна.

Для отображения диалогового окна также можно использовать метод `MessageDialogFacet.show()`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/messagedialogfacet/MessageDialogFacetScreen.java[tags=show]
----

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:dialogs.adoc#msg-dialog-modal[modal] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]