= MessageDialogFacet
:page-aliases: backoffice-ui:facets/message-dialog-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`MessageDialogFacet` gives you an alternative way to configure and open a xref:dialogs.adoc#message-dialog[message dialog]. Instead of using the `Dialogs.createMessageDialog()` method in the screen controller, you can configure `MessageDialogFacet` in the XML descriptor with the help of Studio visual designer.

Component’s XML-name: `messageDialog`.

[[basics]]
== Basics

In the example below, the message dialog will be opened when the user clicks `messageDialogBtn` button:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/messagedialogfacet/message-dialog-facet-screen.xml[tags=facets-start;button-message;facets-end;layout-start;message-btn;layout-end]
----


`MessageDialogFacet` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

* xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside]
* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-modal[modal]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]

You can bind `MessageDialogFacet` to a xref:vcl/components/button.adoc[button] or an xref:actions.adoc[action] to open the dialog on the button click or execution of the action.

[[on-action]]
* `onAction` - defines id of an xref:actions.adoc[action] which should trigger the dialog opening.

[[on-button]]
* `onButton` - defines id of a xref:vcl/components/button.adoc[button] which should trigger the dialog opening.

Also, you can use the `MessageDialogFacet.show()` method to show the dialog:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/messagedialogfacet/MessageDialogFacetScreen.java[tags=show]
----

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:dialogs.adoc#msg-dialog-modal[modal] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]