= NotificationFacet
:page-aliases: backoffice-ui:facets/notification-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/5/sample?id=facet-notification" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`NotificationFacet` facet 支持预配置一个 xref:notifications.adoc[通知]。用声明式的定义替代 `Notifications.create()` 方法。

组件的 XML 名称：`notification`。

[[attributes]]
== 属性

`NotificationFacet` 在界面 XML 描述的 `facets` 元素中定义，有下列属性：

* xref:notifications.adoc#text-content[contentMode]
* xref:notifications.adoc#delay[delay]
* xref:notifications.adoc#notification-type[type]
* xref:notifications.adoc#position[position]

`NotificationFacet` 可以绑定至 xref:actions.adoc[action] 或 xref:vcl/components/button.adoc[button]。此时，当触发 `action` 或点击 `button` 时，会展示通知消息。要使用 `action` 或 `button` 触发 `NotificationFacet`，可以使用下列属性：

[[on-action]]
* `onAction`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/notificationfacet/notification-facet-screen.xml[tags=window-start;actions;facets-start;action-notification;facets-end;layout-start;layout-end;window-end]
----

[[on-button]]
* `onButton`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/notificationfacet/notification-facet-screen.xml[tags=window-start;facets-start;button-notification;facets-end;layout-start;facet-btn;layout-end;window-end]
----

[TIP]
====
`NotificationFacet` 配置的通知消息也可以使用 `show()` 方法展示：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=show]
----

====

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

[[close-event]]
=== CloseEvent

`CloseEvent` 支持处理通知的关闭事件。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=close-event]
----

如需以编程的方式注册事件处理器，使用 `addCloseListener()` 方法。

[[caption-provider]]
=== CaptionProvider

如需修改通知消息的标题，可使用 `NotificationFacet` 的 `CaptionProvider`。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=caption-provider]
----

编程式用法，调用组件的 `setCaptionProvider()` 方法。

[[description-provider]]
=== DescriptionProvider

如需修改通知消息的描述信息，可使用 `NotificationFacet` 的 `DescriptionProvider`。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=description-provider]
----

编程式用法，调用组件的 `setDescriptionProvider()` 方法。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:notifications.adoc#text-content[contentMode] -
xref:notifications.adoc#delay[delay] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:notifications.adoc#position[position] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:notifications.adoc#notification-type[type]
