= NotificationFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/5/sample?id=facet-notification" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Фасет `NotificationFacet` позволяет предварительно настраивать уведомления. Декларативное определение уведомления заменяет существующий метод `Notifications.create()`.

XML-имя компонента: `notification`.

[[attributes]]
== Атрибуты

`NotificationFacet` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

* xref:notifications.adoc#text-content[contentMode]
* xref:notifications.adoc#delay[delay]
* xref:notifications.adoc#notification-type[type]
* xref:notifications.adoc#position[position]

Вы можете привязать `NotificationFacet` к xref:vcl/components/button.adoc[кнопке] или xref:actions.adoc[действию], чтобы уведомление появлялось после нажатия кнопки или выполнения действия. Для этого используйте следующие атрибуты:

[[on-action]]
* `onAction`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/notificationfacet/notification-facet-screen.xml[tags=window-start;actions;facets-start;action-notification;facets-end;layout-start;layout-end;window-end]
----

[[on-button]]
* `onButton`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/notificationfacet/notification-facet-screen.xml[tags=window-start;facets-start;button-notification;facets-end;layout-start;facet-btn;layout-end;window-end]
----

[TIP]
====
Вы также можете настроить отображение уведомлений `ScreenFacet`, используя метод `show()`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=show]
----

====

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[close-event]]
=== CloseEvent

`CloseEvent` обрабатывает закрытие уведомления. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=close-event]
----

Чтобы создать слушателя события программно, используйте метод `addCloseListener()`.

[[caption-provider]]
=== CaptionProvider

`CaptionProvider` изменяет отображаемое название уведомления `NotificationFacet`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=caption-provider]
----

Чтобы создать слушателя события программно, используйте метод `setCaptionProvider()`.

[[description-provider]]
=== DescriptionProvider

`DescriptionProvider` изменяет отображаемое описание уведомления `NotificationFacet`

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=description-provider]
----

Чтобы создать слушателя события программно, используйте метод `setDescriptionProvider()`.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:notifications.adoc#text-content[contentMode] -
xref:notifications.adoc#delay[delay] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:notifications.adoc#position[position] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:notifications.adoc#notification-type[type]