= NotificationFacet
:page-aliases: backoffice-ui:facets/notification-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/5/sample?id=facet-notification" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`NotificationFacet` is a facet that allows you to pre-configure a xref:notifications.adoc[notification]. Declarative definition of the notification replaces existing `Notifications.create()` method.

Component’s XML-name: `notification`.

[[attributes]]
== Attributes

`NotificationFacet` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

* xref:notifications.adoc#text-content[contentMode]
* xref:notifications.adoc#delay[delay]
* xref:notifications.adoc#notification-type[type]
* xref:notifications.adoc#position[position]

You can bind `NotificationFacet` to xref:actions.adoc[action] or xref:vcl/components/button.adoc[button]. In those cases, the notification will appear when `action` is fires or `button` clicks. To aware `NotificationFacet` with `action` or `button`, use the following attributes:

[[on-action]]
* `onAction`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/notificationfacet/notification-facet-screen.xml[tags=window-start;actions;facets-start;action-notification;facets-end;layout-start;layout-end;window-end]
----

[[on-button]]
* `onButton`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/notificationfacet/notification-facet-screen.xml[tags=window-start;facets-start;button-notification;facets-end;layout-start;facet-btn;layout-end;window-end]
----

[TIP]
====
You can also make notification configured with `ScreenFacet` to appear using the `show()` method:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=show]
----

====

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[close-event]]
=== CloseEvent

`CloseEvent` allows you to handle the closure of notification. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=close-event]
----

Programmatic registration of the event handler: use the `addCloseListener()` component method.

[[caption-provider]]
=== CaptionProvider

To change the displayed caption of notification, `NotificationFacet` has `CaptionProvider`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=caption-provider]
----

Programmatic usage: call the `setCaptionProvider()` component method.

[[description-provider]]
=== DescriptionProvider

To change the displayed description of notification, `NotificationFacet` has `DescriptionProvider`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/notificationfacet/NotificationFacetScreen.java[tags=description-provider]
----

Programmatic usage: call the `setDescriptionProvider()` component method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:notifications.adoc#text-content[contentMode] -
xref:notifications.adoc#delay[delay] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:notifications.adoc#position[position] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:notifications.adoc#notification-type[type]