= OptionDialogFacet
:page-aliases: backoffice-ui:facets/option-dialog-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`OptionDialogFacet` facet 支持预配置一个 xref:dialogs.adoc#option-dialog[选项对话框]。用声明式的定义替代 `Dialogs.createOptionDialog()` 方法。

组件的 XML 名称：`optionDialog`。

[[attributes]]
== 属性

`OptionDialogFacet` 在界面 XML 描述的 `facets` 元素中定义，有下列属性：

* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]
* xref:facets/message-dialog-facet.adoc#on-action[onAction]
* xref:facets/message-dialog-facet.adoc#on-button[onButton]

[[actions]]
== 操作

如需添加用户交互按钮，使用界面 XML 描述中的 `actions` 元素。其内部需使用 `action` 元素。示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/optiondialogfacet/option-dialog-facet-screen.xml[tags=actions]
----

`action` 支持下列属性配置：

* `description` - 定义当用户光标悬停至 `button` 时展示的文本信息。
* `icon` - 为对应的 `button` 定义图标。
* `primary` - 定义是否高亮并选中对应的 `button`。默认为 `false`。

如需实现自定义的 `action`，使用 `DialogActionPerformedEvent` 监听器：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/optiondialogfacet/OptionDialogFacetScreen.java[tags=dialog-action-performed-event]
----

当用户在选项对话框中点击 `id="ok"` 时，会执行监听器内的代码。

[[usage-example]]
== 用例

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/optiondialogfacet/option-dialog-facet-screen.xml[tags=option-dialog-facet]
----

<1> 在 `facets` 元素中定义 `OptionDialogFacet`。
<2> 添加第一个 `action` 并设置 `primary` 属性为 `true`。
<3> 添加第二个 `action` 并为其设置 `description` 属性。
<4> 定义打开选项对话框的 `button`。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:facets/message-dialog-facet.adoc#on-action[onAction] -
xref:facets/message-dialog-facet.adoc#on-button[onButton] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]
