= OptionDialogFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Фасет `OptionDialogFacet` позволяет предварительно настраивать xref:dialogs.adoc#option-dialog[диалоговое окно опций]. Декларативное определение диалогового окна заменяет существующий метод `Dialogs.createOptionDialog()`.

XML-имя компонента: `optionDialog`.

[[attributes]]
== Атрибуты

`OptionDialogFacet` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]
* xref:facets/message-dialog-facet.adoc#on-action[onAction]
* xref:facets/message-dialog-facet.adoc#on-button[onButton]

[[actions]]
== Действия

Чтобы добавить кнопки для пользовательского отклика, используйте элемент `actions` XML-дескриптора экрана. Элементы `action` должны быть размещены внутри него. Например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/optiondialogfacet/option-dialog-facet-screen.xml[tags=actions]
----

Для настройки `action` существуют следующие атрибуты:

* `description` - задает текст, который будет отображаться при наведении курсора на соответствующую `button`.
* `icon` - задает значок для соответствующей `button`.
* `primary` - определяет, будет ли соостветсвующая кнопка выделена и подсвечена как главная. Значение по умолчанию – `false`.

Чтобы реализовать собственную логику для `action`, используйте слушатель `DialogActionPerformedEvent`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/optiondialogfacet/OptionDialogFacetScreen.java[tags=dialog-action-performed-event]
----

Код внутри этого слушателя будет выполнен, когда пользователь нажмет кнопку с `id="ok"` в диалоговом окне опций.

[[usage-example]]
== Пример использования

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/optiondialogfacet/option-dialog-facet-screen.xml[tags=option-dialog-facet]
----

<1> Определение `OptionDialogFacet` внутри элемента `facets`.
<2> Добавляет первое `action` и устанавливает для атрибута `primary` значение `true`.
<3> Добавляет второе `action` и определяет для него атрибут `description`.
<4> Определение `button`, которая откроет диалоговое окно опций.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:facets/message-dialog-facet.adoc#on-action[onAction] -
xref:facets/message-dialog-facet.adoc#on-button[onButton] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]