= OptionDialogFacet
:page-aliases: backoffice-ui:facets/option-dialog-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`OptionDialogFacet` is a facet that allows you to pre-configure an xref:dialogs.adoc#option-dialog[option dialog]. Declarative definition of the message dialog replaces existing `Dialogs.createOptionDialog()` method.

Component’s XML-name: `optionDialog`.

[[attributes]]
== Attributes

OptionDialogFacet is defined in the `facets` element of the screen XML descriptor and has the following attributes:

* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]
* xref:facets/message-dialog-facet.adoc#on-action[onAction]
* xref:facets/message-dialog-facet.adoc#on-button[onButton]

[[actions]]
== Actions

To add buttons for user reaction, use the `actions` element of the screen XML descriptor. The `action` elements should be placed inside this element. For example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/optiondialogfacet/option-dialog-facet-screen.xml[tags=actions]
----

To configure `action`, there are the following attributes:

* `description` - defines the text that will be displayed when the cursor hovers over the corresponding `button`.
* `icon` - defines the icon for the corresponding `button`.
* `primary` - defines whether highlighted and selected the corresponding `button` or not. The default value is `false`.

To implement custom logic for `action`, use the `DialogActionPerformedEvent` listener:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/optiondialogfacet/OptionDialogFacetScreen.java[tags=dialog-action-performed-event]
----

The code inside this listener will be executed when the user clicks the button with `id="ok"` in the option dialog.

[[usage-example]]
== Usage Example

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/optiondialogfacet/option-dialog-facet-screen.xml[tags=option-dialog-facet]
----

<1> Define `OptionDialogFacet` inside the `facets` element.
<2> Add the first `action` and set the `primary` attribute to `true`.
<3> Add the second `action` and define the `description` attribute for it.
<4> Define `button` that will open the option dialog.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:facets/message-dialog-facet.adoc#on-action[onAction] -
xref:facets/message-dialog-facet.adoc#on-button[onButton] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]