= ScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`ScreenFacet` gives you an alternative way to xref:opening-screens.adoc[open] related screens and xref:opening-screens.adoc#passing-parameters-to-screens[pass parameters] to them. Instead of using the `ScreenBuilders.screen()` method in the screen controller, you can configure `ScreenFacet` in the XML descriptor with the help of Studio visual designer.

Component’s XML-name: `screen`.

[[basics]]
== Basics

In the example below, the `uiex1_Customer.browse` screen will be opened as a dialog when `openDialogAction` is executed:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=actions;facets-start;action-screen-facet;facets-end]
----

`ScreenFacet` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

[[screen-id]]
* `screenId` - specifies the `id` of the screen to open.

[[screen-class]]
* `screenClass` - specifies the Java class of the screen controller to open.

[[open-mode]]
* `openMode` - defines screen open mode. There are the following possible values:
** `NEW_TAB` - open a screen in the new tab of the main window. This is the default value.
** `THIS_TAB` - open a screen on top of the current tab screens stack.
** `DIALOG` - open a screen as a modal dialog.
** `ROOT` - opens a screen as main.

You can bind `ScreenFacet` to a xref:vcl/components/button.adoc[button] or an xref:actions.adoc[action] to open the screen on the button click or execution of the action.

[[on-action]]
* `onAction` - defines id of an xref:actions.adoc[action] which should trigger the screen opening.

[[on-button]]
* `onButton` - defines id of a xref:vcl/components/button.adoc[button] which should trigger the screen opening.

Also, you can use the `ScreenFacet.show()` method to open the screen:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=show]
----

[[passing-parameters]]
== Passing Parameters

To pass parameters to the screen, use the `properties` element. This element defines a list of properties that will be injected into the opened screen via public setters.

For example, let's pass an integer value to the `num` property of `AnotherScreen` from `ScreenFacetScreen`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/AnotherScreen.java[tags=another-screen]
----

<1> Set label to display received value.
<2> Define setter to assign the transmitted value.
<3> Assign the accepted value to the label.

In the `ScreenFacetScreen` XML descriptor, we define `name` and `value` attributes of the `property` element:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=window-start;facets-start;pass-params;facets-end;layout-start;btn-pass-params;layout-end;window-end]
----

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` is sent after the screen configured by the facet is closed. See xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent] for details.

To register the event handler programmatically, use the `addAfterCloseEventListener()` method.

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` is sent after the screen configured by the facet is shown. See xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] for details.

To register the event handler programmatically, use the `addAfterShowEventListener()` method.

[[options-provider]]
=== OptionsProvider

The `OptionsProvider` delegate method allows you to configure screen parameters programmatically, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=options-provider]
----

To register the options provider programmatically, use the `setOptionsProvider()` method.

[[screen-configurer]]
=== ScreenConfigurer

It is a handler that accepts the configurer and can initialize it before opening. Use the configurer if you need to provide parameters to the opened screen through public setters. The preferred way to set the configurer is using a controller method annotated with `@Install`, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=screen-configurer]
----

To register the screen configurer programmatically, use the `setScreenConfigurer(Consumer<S> screenConfigurer)` method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
<<open-mode, openMode>> -
<<screen-class, screenClass>> -
<<screen-id, screenId>>