= ScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Фасет `ScreenFacet` предоставляет альтернативный способ открывать связанные xref:opening-screens.adoc[экраны] и xref:opening-screens.adoc#passing-parameters-to-screens[передавать им параметры]. Вместо использования метода `ScreenBuilders.screen()` в контроллере экрана вы можете настроить `ScreenFacet` в XML-дескрипторе с помощью визуального дизайнера Studio.

XML-имя компонента: `screen`.

[[basics]]
== Основы

В приведенном ниже примере экран `uiex1_Customer.browse` будет открыт в виде диалогового окна при выполнении `openDialogAction`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=actions;facets-start;action-screen-facet;facets-end]
----

`ScreenFacet` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

[[screen-id]]
* `screenId` - указывает `id` открываемого экрана.

[[screen-class]]
* `screenClass` - указывает класс Java контроллера открываемого экрана.

[[open-mode]]
* `openMode` - определяет режим открытия экрана. Возможны следующие значения:
** `NEW_TAB` - открывает экран на новой вкладке главного окна. Значение по умолчанию.
** `THIS_TAB` - открывает экран поверх стека экранов текущей вкладки.
** `DIALOG` - открывает экран в виде модального диалога.
** `ROOT` - открывает экран в качестве основного.

Вы можете привязать `ScreenFacet` к xref:vcl/components/button.adoc[кнопке] или xref:actions.adoc[действию], чтобы окно открывалось по нажатию кнопки или выполнению действия. Для этого используйте следующие атрибуты:

[[on-action]]
* `onAction` - определяет `id` xref:actions.adoc[действия], которое должно вызвать открытие экрана.

[[on-button]]
* `onButton` - определяет `id` xref:vcl/components/button.adoc[кнопки], которая должно вызвать открытие экрана.

Также вы можете использовать метод `ScreenFacet.show()` для открытия экрана:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=show]
----

[[passing-parameters]]
== Передача параметров

Чтобы передать параметры на экран, используйте элемент `properties`. Он определяет список свойств, которые будут инжектированы в открытый экран с помощью общедоступных сеттеров.

Например, давайте передадим целое значение свойству `num` экрана `AnotherScreen` из `ScreenFacetScreen`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/AnotherScreen.java[tags=another-screen]
----

<1> Надпись будет отображать полученное значение.
<2> Определение сеттера для присвоения передаваемого значения.
<3> Надпись будет отображать принятое значение.

В XML-дескрипторе `ScreenFacetScreen` мы определим атрибуты `name` и `value` элемента `property`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=window-start;facets-start;pass-params;facets-end;layout-start;btn-pass-params;layout-end;window-end]
----

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` отправляется после закрытия экрана, настроенного фасетом. Подробнее см. в xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent].

Чтобы создать слушателя события программно, используйте метод `addAfterCloseEventListener()`.

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` отправляется после отображения настраиваемого фасетом экрана. Подробнее см. в xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

Чтобы создать слушателя события программно, используйте метод `addAfterShowEventListener()`.

[[options-provider]]
=== OptionsProvider

Метод делегата `OptionsProvider`  позволяет настраивать параметры экрана программно. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=options-provider]
----

Чтобы создать `OptionsProvider` программно, используйте метод `setOptionsProvider()`.

[[screen-configurer]]
=== ScreenConfigurer

Это обработчик, который принимает экран и может инициализировать его перед открытием. Используйте конфигуратор, если вам нужно предоставить параметры открытому экрану через общедоступные сеттеры. Предпочтительным способом настройки конфигуратора является использование метода контроллера с аннотацией `@Install`, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=screen-configurer]
----

Чтобы создать `ScreenConfigurer` программно, используйте метод `setScreenConfigurer(Consumer<S> screenConfigurer)`.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
<<open-mode, openMode>> -
<<screen-class, screenClass>> -
<<screen-id, screenId>>