= ScreenSettingsFacet

Фасет `ScreenSettingsFacet` сохраняет настройки, установленные пользователем для xref:vcl/components.adoc[визуальных компонентов].

Component’s XML-name: `screenSettings`.

[[basics]]
== Основы

`ScreenSettingsFacet` определяется в элементе `facets` XML-дескриптора экрана.

[[auto]]
Чтобы включить сохранение настроек экрана для всех его компонентов, установите для атрибута `auto` значение `true`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;auto;facets-end]
----

Вы можете включить сохранение настроек экрана только для конкретных компонентов. Для этого, нужные компоненты должны быть объявлены явно:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;manual;facets-end;layout]
----

При необходимости, вы также можете отключить сохранение настроек экрана для конкретного компонента. Для этого, установите для атрибута `enable` значение `false`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;exclude;facets-end;layout]
----

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

`ScreenSettingsFacet` имеет три делегата для перехвата жизненного цикла настроек экрана.

[[apply-settings-delegate]]
=== ApplySettingsDelegate

Данный слушатель позволяет сохранять состояния компонентов по срабатыванию xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screensettingsfacet/ScreenSettingsFacetScreen.java[tags=apply-settings-delegate]
----

Чтобы создать слушателя события программно, используйте метод `setApplySettingsDelegate()`.

[[apply-data-loading-settings-delegate]]
=== ApplyDataLoadingSettingsDelegate

Данный слушатель позволяет сохранять состояния компонентов по срабатыванию xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent].

См. xref:facets/screen-settings-facet.adoc#apply-settings-delegate[ApplySettingsDelegate].

Чтобы создать слушателя события программно, используйте метод `setApplyDataLoadingSettingsDelegate()`.

[[save-settings-delegate]]
=== SaveSettingsDelegate

Данный слушатель позволяет сохранять состояния компонентов по срабатыванию xref:screens/screen-events.adoc#after-detach-event[AfterDetachEvent].

См. xref:facets/screen-settings-facet.adoc#apply-settings-delegate[ApplySettingsDelegate].

Чтобы создать слушателя события программно, используйте метод `setSaveSettingsDelegate()`.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

<<auto, auto>> -
xref:vcl/xml.adoc#id[id]
