= ScreenSettingsFacet
:page-aliases: backoffice-ui:facets/screen-settings-facet.adoc

`ScreenSettingsFacet` is a facet that saves the settings that the user has set for xref:vcl/components.adoc[visual components].

Component’s XML-name: `screenSettings`.

[[basics]]
== Basics

`ScreenSettingsFacet` is defined in the `facets` element of the screen XML descriptor.

[[auto]]
To enable screen settings saving for all components on the screen, you can set the `auto` attribute to `true`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;auto;facets-end]
----

If you have specific components to enable screen settings saving, you can configure your facet like this:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;manual;facets-end;layout]
----

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

`ScreenSettingsFacet` has three delegates for the screen settings lifecycle.

[[apply-settings-delegate]]
=== ApplySettingsDelegate

This handler allows you to save the states of the components on xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screensettingsfacet/ScreenSettingsFacetScreen.java[tags=apply-settings-delegate]
----

Programmatic usage: call the `setApplySettingsDelegate()` component method.

[[apply-data-loading-settings-delegate]]
=== ApplyDataLoadingSettingsDelegate

This handler allows you to save the states of the components on xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent].

See xref:facets/screen-settings-facet.adoc#apply-settings-delegate[ApplySettingsDelegate].

Programmatic usage: call the `setApplyDataLoadingSettingsDelegate()` component method.

[[save-settings-delegate]]
=== SaveSettingsDelegate

This handler allows you to save the states of the components on xref:screens/screen-events.adoc#after-detach-event[AfterDetachEvent].

See xref:facets/screen-settings-facet.adoc#apply-settings-delegate[ApplySettingsDelegate].

Programmatic usage: call the `setSaveSettingsDelegate()` component method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<auto, auto>> -
xref:vcl/xml.adoc#id[id]
