= ScreenFacet
:page-aliases: backoffice-ui:facets/screen-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`ScreenFacet` 提供另一种 xref:opening-screens.adoc[打开] 关联界面并为之 xref:opening-screens.adoc#passing-parameters-to-screens[传递参数] 的方式。通过 Studio 可视化设计器的帮助，可以在 XML 描述中配置 `ScreenFacet`，而无需在界面控制器使用 `ScreenBuilders.screen()` 方法。

组件的 XML 名称：`screen`。

[[basics]]
== 基本用法

下面例子中，当 `openDialogAction` 执行时，会以对话框的方式打开 `uiex1_Customer.browse` 界面：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=actions;facets-start;action-screen-facet;facets-end]
----

`ScreenFacet` 在界面 XML 描述的 `facets` 元素中定义，有下列属性：

[[screen-id]]
* `screenId` - 指定需要打开的界面 id。

[[screen-class]]
* `screenClass` - 指定需要打开的界面控制器 Java 类。

[[open-mode]]
* `openMode` - 界面打开模式，支持下列值：
** `NEW_TAB` - 在主窗口的新标签页打开界面。默认值。
** `THIS_TAB` - 在当前标签页的界面栈顶打开界面。
** `DIALOG` - 以模态框的形式打开界面。
** `ROOT` - 在主窗口打开界面。

`ScreenFacet` 可以绑定至 xref:vcl/components/button.adoc[button] 或 xref:actions.adoc[action]。此时，当点击 `button` 或触发 `action` 时，会打开界面。

[[on-action]]
* `onAction` - 定义一个 xref:actions.adoc[action] 的 id，用于打开界面。

[[on-button]]
* `onButton` - 定义一个 xref:vcl/components/button.adoc[button] 的 id，用于打开界面。

另外，也支持通过 `ScreenFacet.show()` 方法打开界面：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=show]
----

[[passing-parameters]]
== 传参

如需为界面传递参数，请使用 `properties` 元素。该元素定义属性列表，这些属性用界面的公共 setters 注入打开的界面。

例如，我们从 `ScreenFacetScreen` 界面给 `AnotherScreen` 的 `num` 属性传递一个整数值。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/AnotherScreen.java[tags=another-screen]
----

<1> 设置一个文本标签展示接收到的值。
<2> 定义 setter 用于传递值。
<3> 将收到的值赋值给标签。

在 `ScreenFacetScreen` 的 XML 描述中，我们为 `property` 元素定义 `name` 和 `value` 属性：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=window-start;facets-start;pass-params;facets-end;layout-start;btn-pass-params;layout-end;window-end]
----

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

`AfterCloseEvent` 在 facet 配置的界面关闭之后发送。参阅 xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent] 了解详情。
is sent after the screen configured by the facet is closed. See xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent] for details.

如需以编程的方式注册事件处理器，使用 `addAfterCloseEventListener()` 方法。

[[after-show-event]]
=== AfterShowEvent

`AfterShowEvent` 在 facet 配置的界面展示之后发送。参阅 xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] 了解详情。

如需以编程的方式注册事件处理器，使用 `addAfterShowEventListener()` 方法。

[[options-provider]]
=== OptionsProvider

`OptionsProvider` 代理方法支持编程式配置界面参数，示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=options-provider]
----

编程式用法，调用 `setOptionsProvider()` 方法。

[[screen-configurer]]
=== ScreenConfigurer

该处理方法接收一个界面作为参数，并可以在打开之前对其进行初始化。如果需要通过 public setter 为打开的界面提供参数，可以使用 configurer。设置 configurer 的首选方法是使用带有 `@Install` 注解的控制器方法，示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=screen-configurer]
----

编程式用法，调用 `setScreenConfigurer(Consumer<S> screenConfigurer)` 方法。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
<<open-mode, openMode>> -
<<screen-class, screenClass>> -
<<screen-id, screenId>>
