= ScreenSettingsFacet
:page-aliases: backoffice-ui:facets/screen-settings-facet.adoc

`ScreenSettingsFacet` facet，保存用户对 xref:vcl/components.adoc[可视化组件] 的设置。

组件的 XML 名称：`screenSettings`。

[[basics]]
== 基本用法

`ScreenSettingsFacet` 在界面 XML 描述的 `facets` 元素中定义。

[[auto]]
如需为界面的所有组件启用设置保存功能，可以设置 `auto` 为 `true`：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;auto;facets-end]
----

如需只需为特定组件启用配置保存功能，可以按下面示例配置 facet：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screensettingsfacet/screen-settings-facet-screen.xml[tags=facets-start;manual;facets-end;layout]
----

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

可以使用 `ScreenSettingsFacet` 代理对界面配置的生命周期做拦截处理。

[[apply-settings-delegate]]
=== ApplySettingsDelegate

该处理器支持在 xref:screens/screen-events.adoc#after-show-event[AfterShowEvent] 事件保存组件的状态。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screensettingsfacet/ScreenSettingsFacetScreen.java[tags=apply-settings-delegate]
----

编程式用法，调用组件的 `setApplySettingsDelegate()` 方法。

[[apply-data-loading-settings-delegate]]
=== ApplyDataLoadingSettingsDelegate

该处理器支持在 xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent] 事件保存组件的状态。

参阅 xref:facets/screen-settings-facet.adoc#apply-settings-delegate[ApplySettingsDelegate]。

编程式用法，调用组件的 `setApplyDataLoadingSettingsDelegate()` 方法。

[[save-settings-delegate]]
=== SaveSettingsDelegate

该处理器支持在 xref:screens/screen-events.adoc#after-detach-event[AfterDetachEvent] 事件保存组件的状态。

参阅 xref:facets/screen-settings-facet.adoc#apply-settings-delegate[ApplySettingsDelegate]。

编程式用法，调用组件的 `setSaveSettingsDelegate()` 方法。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

<<auto, auto>> -
xref:vcl/xml.adoc#id[id]
