= Timer
:page-aliases: backoffice-ui:facets/timer-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/1/sample?id=facet-timer" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`Timer` facet 支持以一定的时间间隔运行一些界面控制器的代码。定时器是在一个处理用户事件的线程里面运行的，所以可以更新 xref:vcl/components.adoc[界面组件]。当创建定时器的界面被关闭之后，该界面的定时器就会停止工作了。

[[attributes]]
== 属性

`Timer` 在界面 XML 描述的 `facets` 元素中定义，有下列属性：

[[delay]]
* `delay` - 必需属性。定义定时器执行的时间间隔，以毫秒为单位。

[[autostart]]
* `autostart` - 可选属性。默认值是 `false`，也就是说只有在调用定时器的 `start()` 方法之后才会启动。当设置成 `true` 的时候，定时器会在界面打开的时候立即自动启动。

[[repeating]]
* `repeating` - 可选属性。开启定时器的重复执行模式。如果这个属性设置的是 `true`，定时器会按照 `delay` 设置的时间间隔重复执行。否则只会在 `delay` 设定的时间之后执行一次。

[[handlers]]
== 事件和处理器

include::events-handlers-generation-facet-tip.adoc[]

[[timer-action-event]]
=== TimerActionEvent

`TimerActionEvent` 支持在 `delay` 属性指定的时间间隔执行一些代码。如果 `repeating` 属性设置为 `true`，则该事件中的代码会多次执行，直至定时器结束。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer-action-event-1]
----

如需以编程的方式注册事件处理器，使用组件的 `addTimerActionListener()` 方法。

[[timer-stop-event]]
=== TimerStopEvent

`TimerStopEvent` 支持在定时器结束时执行一些代码。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer-stop-event]
----

如需以编程的方式注册事件处理器，使用组件的 `addTimerStopListener()` 方法。

[[usage-example]]
== Usage Example

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/timer/timer-screen.xml[tags=timer]
----

<1> 在 `facets` 元素中定义 `Timer`。
<2> 定义控制定时器的 UI 组件和布局。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer]
----

<1> 当点击 `startTimer` 按钮时启动定时器。
<2> 计算定时器启动时长。
<3> 停止定时器。

[[xml]]
== XML 属性

include::xml-studio-facet-tip.adoc[]

<<autostart, autostart>> -
<<delay, delay>> -
xref:vcl/xml.adoc#id[id] -
<<repeating, repeating>>
