= Timer

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/1/sample?id=facet-timer" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Фасет `Timer` предназначен для запуска некоторого кода контроллера экрана через определенные промежутки времени. Он работает в потоке, который обрабатывает события пользовательского интерфейса. Следовательно, он может обновлять xref:vcl/components.adoc[экранные компоненты]. `Timer` перестает работать после закрытия экрана, для которого он был создан.

[[attributes]]
== Атрибуты

`Timer` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

[[delay]]
* `delay` - обязательный атрибут. Определяет интервал времени в миллисекундах.

[[autostart]]
* `autostart` - необязательный атрибут. Значение по умолчанию – `false`, что означает, что таймер запустится только при вызове его метода `start()`. Если установлено значение `true`, таймер запускается сразу после открытия экрана.

[[repeating]]
* `repeating` - необязательный атрибут. Включает повторное выполнение таймера. Если для атрибута установлен в `true`, таймер работает циклически с равными интервалами, определенными в атрибуте `delay`. В противном случае таймер запускается только один раз столько миллисекунд, сколько указано в атрибуте `delay`.

[[handlers]]
== События и слушатели

include::events-handlers-generation-facet-tip.adoc[]

[[timer-action-event]]
=== TimerActionEvent

`TimerActionEvent` позволяет выполнить некоторый код во время, указанное в атрибуте `delay`. Если атрибут `repeating` установлен в `true`, указанный в этом событии код будет выполняться периодически, пока таймер не будет остановлен.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer-action-event-1]
----

Чтобы создать слушателя события программно, используйте метод `addTimerActionListener()`.

[[timer-stop-event]]
=== TimerStopEvent

`TimerStopEvent` позволяет выполнить некоторый код после остановки таймера.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer-stop-event]
----

Чтобы создать слушателя события программно, используйте метод `addTimerStopListener()`.

[[usage-example]]
== Пример использования

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/timer/timer-screen.xml[tags=timer]
----

<1> Определение таймера в элементе `facets`.
<2> Определение `layout` для управления таймером.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/timer/TimerScreen.java[tags=timer]
----

<1> Запуск таймера по нажатию кнопки `startTimer`.
<2> Подсчет длительности работы таймера.
<3> Остановка таймера.

[[xml]]
== Все XML-атрибуты

include::xml-studio-facet-tip.adoc[]

<<autostart, autostart>> -
<<delay, delay>> -
xref:vcl/xml.adoc#id[id] -
<<repeating, repeating>>