## Execute 'authenticate.http' first to get have a valid access token for the API

# Create multiple Customers

POST {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

[
  {
    "name": "Randall Bishop"
  },
  {
    "name": "Sarah Doogle"
  }
]


> {%

    client.test("Response Code is 201", function() {
      client.assert(
          response.status === 201,
          "Response status is not 201 - Created"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body.length == 2,
          "ID Attribute of an Entity is not returned"
      );
    });
  %}

###

# Create multiple customers with bean validation failure

POST {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

[
  {
    "name": "Randall Bishop"
  },
  {
    "name": null
  }
]

> {%

    client.test("Response Code is 400", function() {
      client.assert(
          response.status === 400,
          "Response status is not 400"
      );
    });
  %}
