## Execute 'authenticate.http' first to get have a valid access token for the API


# Create an order with many order lines
# 1:N Composition


POST {{baseRestUrl}}
         /entities
         /rstex11_Order?responseFetchPlan=order-with-details
Authorization: Bearer {{access_token}}

{
  "customer": {
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835"
  },
  "date": "2021-03-01",
  "amount": 130.08,
  "lines": [
    {
      "product": {
        "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19"
      },
      "quantity": 2
    },
    {
      "product": {
        "id": "1ed85c7a-89f1-c339-a738-16307ed6003a"
      },
      "quantity": 1
    }
  ]
}

###

# Create an order with many wrong order lines
# 1:N Composition with Validation errors

POST {{baseRestUrl}}
         /entities
         /rstex11_Order?responseFetchPlan=order-with-details
Authorization: Bearer {{access_token}}

{
  "customer": null,
  "date": "2021-03-01",
  "amount": 130.08,
  "lines": [
    {
      "product": null,
      "quantity": 2
    },
    {
      "product": null,
      "quantity": 1
    }
  ]
}