## Execute 'authenticate.http' first to get have a valid access token for the API

# Create a Customer

POST {{baseRestUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{access_token}}

{
  name: "Randall Bishop Wurst"
}

> {%

    client.test("Response Code is 201", function() {
      client.assert(
          response.status === 201,
          "Response status is not 201 - Created"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body["id"],
          "ID Attribute of an Entity is not returned"
      );
    });
  %}

###

# Create an Order with bean validation failure

POST {{baseRestUrl}}
         /entities
         /rstex11_Order
Authorization: Bearer {{access_token}}

{
  "date": "2022-01-01",
  "amount": 49.99
}

> {%

    client.test("Response Code is 400", function() {
      client.assert(
          response.status === 400,
          "Response status is not 400"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body["id"],
          "ID Attribute of an Entity is not returned"
      );
    });
  %}
