## Execute 'authenticate.http' first to get have a valid access token for the API

# Create an order with association to the customer
# N:1 Association

POST {{baseRestUrl}}
         /entities
         /rstex11_Order?responseFetchPlan=order-with-details
Authorization: Bearer {{access_token}}

{
  "customer": {
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835"
  },
  "date": "2021-03-01",
  "amount": 130.08
}

###

# Create a product with many tags
# 1:N Association


POST {{baseRestUrl}}
         /entities
         /rstex11_Product?responseFetchPlan=product-with-tags
Authorization: Bearer {{access_token}}

{
  "name": "123",
  "price": 99.95,
  "tags": [
    {
      "id": "333f3a20-c47b-4bc9-ba34-a72d2d815695"
    },
    {
      "id": "c4c028f0-fec1-7512-83cd-c17537d1f502"
    }
  ]
}