= Pivot Table

The PivotTable add-on provides a table component for Jmix UI with drag-and-drop functionality that enables turning a data set into a summary table and manipulate it using 2D drag-and-drop UI.

The add-on is based on the PivotTable is based on the external https://github.com/nicolaskruchten/pivottable[PivotTable.js^] JavaScript library. You can find more examples of PivotTable on its author’s http://nicolas.kruchten.com/pivottable/examples/[website^].


[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, do the following:

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dep]
----

. Remove `implementation 'io.jmix.ui:jmix-ui-widgets-compiled'` dependency.

. Add `compileWidgets` task (change paths according to your application base package):
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=compile-widgets]
----

. Add `jmix.ui.widget-set` property to your `application.properties` file (adjust location according to the `compileWidgets` task above):
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=custom-widgetset]
----

To enable using the component in a screen, declare the `pivot` namespace in the root element of the screen XML descriptor:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/pivottable/ex1/screen/simple-pivot.xml[tags=namespace]
----
