= 使用 ShowPivotTableAction

`ShowPivotTableAction` 是一个特殊的操作，可以从扩展自 `ListDataComponent` 的组件中导出数据，例如 xref:flow-ui:vc/components/dataGrid.adoc[DataGrid] 和 xref:flow-ui:vc/components/treeDataGrid.adoc[TreeDataGrid]，以及透视表。

使用该操作最直接的方法是在 `dataGrid` 中定义并与按钮关联。

[source,xml,indent=0]
----
include::../examples/pivottable-ex1/src/main/resources/com/company/ex1/view/pivottableshowaction/pivottable-show-action-view.xml[tags=data-grid-action,button-action]
----

也可以在视图控制器中编程式创建，然后与按钮关联：

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=manual-set-action]
----

`ShowPivotTableAction` 有两个导出数据的模式：

* *所有行*：导出 `DataGrid` 或 `TreeDataGrid` 中的所有行。
* *已选择行*：仅导出 `DataGrid` 或 `TreeDataGrid` 中选中的行。

如果没有选择行，则默认导出所有行。

xref:pivottable-component.adoc#ui-mode[UI 模式] 的透视表会显示在一个新的 tab 中。默认情况下，会显示组件数据容器中的所有属性，但不包括：

* `Collection`（集合）类型的属性。
* `byte[]`（字符数组）类型的属性。
* `UUID` 属性。
* 带 xref:data-model:entities.adoc#system-level[@SystemLevel] 注解的属性。

如需排除某些属性或仅包含特定属性子集，请使用 `PivotTableViewBuilder` Bean，其提供了流式 API 接口，可以在打开的视图中配置数据透视表组件。

实现自定义配置时，在 `ActionPerformedEvent` 事件监听器中处理：

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=custom-action]
----
<1> `withIncludedProperties()` 方法仅考虑需要显示包含的属性，忽略其他属性。如需排除特定属性，请使用 `withExcludedProperties()` 方法。
<2> 其他以 `"with"` 开头的方法可由于配置透视表的选项。包括 `withHiddenFromAggregations()`、`withHiddenFromDragDrop()`、`withAggregationProperties()` 等。

展示的透视表数据可以导出为 Excel（需要支持当前渲染器）。在打开的 tab 中有一个默认的按钮可以用于导出。
