= Using ShowPivotTableAction

++++
<div class="jmix-ui-live-demo-container">

</div>
++++

`ShowPivotTableAction` is a special action that enables exporting data from the components that extend `ListDataComponent`, such as DataGrid and TreeDataGrid, to a pivot table.
The easiest way to use action is to define action inside `dataGrid and` set the action to the button.
[source,xml,indent=0]
----
include::../examples/pivottable-ex1/src/main/resources/com/company/ex1/view/pivottableshowaction/pivottable-show-action-view.xml[tags=data-grid-action,button-action]
----

Also action can be created programmatically in the screen controller and used, for example, in a button

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=manual-set-action]
----

`ShowPivotAction` has two modes for export: all rows and selected rows. If no rows are selected, all rows will be exported by default without confirmation.

The editable `PivotTable` component will be shown in a new tab. By default, all the attributes included in the component’s data container view will be displayed, except the following:

* attributes of `Collection` type;
* attributes of byte array type;
* `UUID` attributes;
* annotated with xref:data-model:entities.adoc#system-level[@SystemLevel].

If you want to exclude certain attributes or include only a part of them, use the `PivotTableViewBuilder` Spring bean.
It provides a fluent API for configuring the `PivotTable` component in the opened view.
To make custom configuration, handle `ActionPerformedEvent`.

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=custom-action]
----

<1> The `withIncludedProperties()` method takes only included properties, the other properties will be ignored. To exclude properties, use the `withExcludedProperties()` method.
<2> All other methods starting from `with'. Using these methods we can configure all PivotTable options.

You can export the displayed pivot data to Excel (if the current renderer is supported). The corresponding button will be displayed by default in the opened tab.