= Использование ShowPivotTableAction

Действие `ShowPivotTableAction` - это специальное действие, которое позволяет экспортировать данные из компонентов, наследующих от `ListDataComponent`, таких как xref:flow-ui:vc/components/dataGrid.adoc[DataGrid] и xref:flow-ui:vc/components/treeDataGrid.adoc[TreeDataGrid], в сводную таблицу.

Проще всего использовать это действие, определив его в вашем `dataGrid`, а затем связав с кнопкой.

[source,xml,indent=0]
----
include::../examples/pivottable-ex1/src/main/resources/com/company/ex1/view/pivottableshowaction/pivottable-show-action-view.xml[tags=data-grid-action,button-action]
----

Вы также можете создать действие программно в вашем контроллере экрана и использовать его с кнопкой.

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=manual-set-action]
----

Действие `ShowPivotTableAction` имеет два режима для экспорта данных:

* *Все строки (All rows)*: Экспортирует все строки в `DataGrid` или `TreeDataGrid`.
* *Выбранные строки (Selected rows)*: Экспортирует только выбранные строки в `DataGrid` или `TreeDataGrid`.

Если ни одна строка не выбрана, по умолчанию будут экспортированы все строки без подтверждения.

Сводная таблица в xref:pivottable-component.adoc#ui-mode[режиме UI] будет отображена в новой вкладке. По умолчанию будут отображены все атрибуты, включенные в представление контейнера данных компонента, за исключением:

* Атрибутов типа `Collection`.
* Атрибутов типа `byte[]` (массив байтов).
* Атрибутов типа `UUID`.
* Атрибутов, аннотированных xref:data-model:entities.adoc#system-level[@SystemLevel].

Чтобы исключить определенные атрибуты или включить только определенный набор атрибутов, используйте бин Spring `PivotTableViewBuilder`. Этот бин предоставляет простой API для настройки компонента сводной таблицы в открытом экране.

Чтобы реализовать пользовательскую конфигурацию, обработайте событие `ActionPerformedEvent`.

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=custom-action]
----
<1> Метод `withIncludedProperties()` учитывает только свойства, которые вы явно включаете, игнорируя все остальные. Чтобы исключить определенные свойства, используйте метод `withExcludedProperties()`.
<2> Все остальные методы, начинающиеся с `"with"`, могут быть использованы для настройки параметров сводной таблицы. К ним относятся методы `withHiddenFromAggregations()`, `withHiddenFromDragDrop()`, `withAggregationProperties()` и другие.

Вы можете экспортировать отображаемые данные сводной таблицы в Excel (если текущий рендерер поддерживается). Для этой цели соответствующая кнопка будет отображена по умолчанию на открытой вкладке.