= PivotTable onboarding

The PivotTable can be very useful for analysing data. Let's see an example of how we can use the component for this purpose. Suppose we are going to analyse tips dataset and determine whether the spending in a restaurant differs between smokers and non-smokers.

== Create entity TipInfo
В соответствии с данными из csv файла создадим сущность.

[source,java,indent=0]
----
include::../examples/pivottable-onboarding/src/main/java/com/company/pivottableonboarding/entity/TipInfo.java[tags=onboarding-tip-info]
----

== Export data

Next, export tips dataset into the application by any way. For example, you can add `liquibase` changelog which runs export data from `tips.csv`.
[source,xml,indent=0]
----
include::../examples/pivottable-onboarding/src/main/resources/com/company/pivottableonboarding/liquibase/changelog/2024/10/21-02-init-tip-info-data.xml[tags=onboarding-tip-info-data-changelog]
----

== Create UI
Create blank view.
Specify the data container.
[source,xml,indent=0]
----
include::../examples/pivottable-onboarding/src/main/resources/com/company/pivottableonboarding/view/tipsanalyse/tips-analyse-view.xml[tags=onboarding-tip-info-dc]
----

Add extension PivotTable. Through marketplace or manually.


Press Add Component and select PivotTable.
Add dataContainer and configure properties.
[source,xml,indent=0]
----
include::../examples/pivottable-onboarding/src/main/resources/com/company/pivottableonboarding/view/tipsanalyse/tips-analyse-view.xml[tags=onboarding-pivot-table]
----

== Analyse
Now you can run application and try to analyse data.
We don't set any predefined rows, columns, aggregations and renderers.
So we see component with all not used properties.

Move `Smoker` to rows section and `Day` to columns section.
Click on the `Day` and choose `Saturday` and `Sunday`.
Select `Average` aggregation. Then if select `Tips` and after `Total bill` in the `Aggregation Property`, we can notice that `smokers` leave about the same tips as `non-smokers` `3.08` vs `3.14`, but spend 10% more `22.16` vs `20.13` at average.




