= Exporting PivotTable Data

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`PivotTableExporter` is the bean that provides an API for downloading a table with aggregated data in the XLS format.

An instance of the bean should be created in the screen controller using the PivotTable and PivotTableExcelExporter parameters.

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableexport/PivottableExportView.java[tags=export]
----

TIP: The extension works only for the following xref:pivot-table:elements.adoc#renderers[renderers] types: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP`, `ROW_HEATMAP`, and doesn’t get the color of cells.

The `exportTableToXls()` method allows you to download the table data as an XLS file, for example, on a button click:

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableexport/PivottableExportView.java[tags=run-export]
----

TIP: The XLS format implies the limitation for 65536 table rows. If `PivotTable` contains more than 65536 rows, its content will be cut by the last row, and you will see the corresponding warning message.