= Configuration

Email sending parameters consist of two groups: 

* https://docs.spring.io/spring-boot/docs/2.1.18.RELEASE/reference/html/boot-features-email.html[Spring Boot] mail properties such as host, port, protocol, etc.
* Jmix application properties.

You should set the necessary parameters in the `application.properties` file of your project.

[[spring-boot-mail-properties]]
== Spring Boot Mail Properties

Spring Boot mail properties must be set in the following format – `spring.mail.*`.

NOTE: Property `spring.mail.host` is required to send emails.

[source, properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=spring-boot-properties]
----

Also, you can specify JavaMail properties in the format `spring.mail.properties.*`. For example, the `mail.smtp.auth` property should be specified in the following way:

[source, properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=java-mail-properties]
----

[[application-properties]]
== Application Properties

[[jmix.email.fromAddress]]
=== jmix.email.fromAddress

Defines the default sender's address. It is used if the `EmailInfo.from` attribute is not specified.

Default value: `DoNotReply@localhost`

[[jmix.email.scheduledSendingDelayCallCount]]
=== jmix.email.scheduledSendingDelayCallCount

Property is used in asynchronous sending of emails to skip the first few calls of `Emailer.processQueuedEmails()` after server startup to reduce the load during application initialization. Email sending will start with the next call.

Default value: `2`

[[jmix.email.messageQueueCapacity]]
=== jmix.email.messageQueueCapacity

Property is used for asynchronous sending, the maximum number of messages read from the queue and sent in one call of `Emailer.processQueuedEmails()`.

Default value: `100`

[[jmix.email.defaultSendingAttemptsCount]]
=== jmix.email.defaultSendingAttemptsCount

Property is used for asynchronous sending, the default number of attempts to send an email. It is used if the `attemptsCount` parameter is not specified when calling `Emailer.sendEmailAsync()`.

Default value: `10`

[[jmix.email.sendingTimeoutSec]]
=== jmix.email.sendingTimeoutSec

Defines the maximum expected time in seconds, which is required to send an email to the SMTP server. It is used for asynchronous sending to optimize the selection of `SendingMessage` objects from the DB queue.

Default value: `240`

[[jmix.email.adminAddress]]
=== jmix.email.adminAddress

Defines the address, to which all messages are sent if the `jmix.email.sendAllToAdmin` property is switched on.

Default value: `admin@localhost`

[[jmix.email.sendAllToAdmin]]
=== jmix.email.sendAllToAdmin

Indicates that all messages should be sent to the `jmix.email.adminAddress` address, regardless of the specified recipient’s address. It is recommended to use this parameter during system development and debugging.

Default value: `false`

[[jmix.email.isFileStorageUsed]]
=== jmix.email.isFileStorageUsed

When turned on, email body text and attachments will be stored in file storage instead of BLOB columns in the database. Should be used if the application stores lots of emails and/or email attachments.

Default value: `false`

[[jmix.emailerUserLogin]]
=== jmix.emailerUserLogin

Defines the login of the system user, used by asynchronous email sending code to be able to persist the information to the database. It is recommended to create a separate user (for example, emailer) without a password so that it will be impossible to log in under their name via user interface. This is also convenient to search for messages related to email sending in the server log.

Default value: `admin`

[[file-storage-usage]]
== File Storage Usage

You can store email body text and attachments in File Storage instead of BLOB columns in the database.

To use File Storage:

. Add the following line to the `dependencies` section of your `build.gradle` file:
+
[source,java,indent=0]
----
include::example$/ex1/build.gradle[tags=fs-dependency]
----
+
. Enable File Storage usage and configure default File Storage. Set in `application.properties` file:
+
[source, properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=fs-enable]
----
