= Email Sending Guide

This section contains a practical guide on sending emails.

Let’s consider the following task:
--
* There are the `NewsItem` entity and the `NewsItemEdit` and `NewsItemBrowse` screen.
* The `NewsItem` entity contains the following attributes: `date`, `caption`, `content`.
* Emails will send to some addresses every time a new instance of `NewsItem` is created through the `NewsItemEdit` screen. An email should contain `NewsItem.caption` as a subject and `NewsItem.content` as a body of the message.
* Every message will contain a picture of the company's logo as an attachment.
--

. Add the following code to `NewsItemEdit.java`:
+
[source,java]
----
include::example$/ex1/src/main/java/sample/screen/newsitem/NewsItemEdit.java[tags=news-item-edit1;news-item-edit2]
----
+
<1> Indicates that a new item was created in this editor.
<2> This method is invoked when a new item is initialized.
<3> This method is invoked after commit of data context.
<4> If a new entity was saved to the database, ask a user about sending an email.
<5> Queues an email for sending asynchronously.
<6> Gets a file as a byte array.
<7> Creates `EmailAttachment` object.
<8> Recipients.
<9> Subject.
<10> The `from` address will be taken from the xref:properties.adoc#jmix.email.fromAddress[jmix.email.fromAddress] application property.
<11> Attachments.
+
. Launch the application, open the `NewsItem` entity browser and click *Create*. The editor screen will be opened. Fill in the fields and press *OK*. The confirmation dialog with the question about sending emails will be shown. Click *Yes*.
. Go to the *Administration > Email History* screen of your application. You will see two records (by the number of recipients) with the `Queue` status. It means that the emails are in the queue and not yet sent.
. Set up the SMTP server xref:properties.adoc#spring-boot-mail-properties[parameters]. You can set the parameters in the `application.properties` file of your application. Add the required parameters:
+
[source,properties]
----
jmix.email.fromAddress = do-not-reply@company.com
spring.mail.host = mail.company.com
----
. To send emails, choose them in the *Administration > Email History* screen and click *Resent email*. You can change or add recepients before sending. State of the messages will be `Sent` after sending.

