= Email Sending

include::ROOT:partial$outdated-ui-warning.adoc[]

Jmix provides the following email sending functionality:

* Synchronous or asynchronous sending. In case of synchronous sending, the calling code waits till the message is sent to the SMTP server. In case of asynchronous sending, the message is saved to the database, and the control is returned immediately to the calling code. Later, a scheduled task sends the message using a preconfigured number of attempts.

* Reliable tracking of message sending timestamp or errors in the database for both synchronous and asynchronous modes.

* User interface to search and view information about sent messages, including all message attributes and content, sending status and the number of attempts.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----
