= Sending Methods

//здесь надо примеры?
To send emails, you should use the following methods of the `Emailer` bean:

* `sendEmail()` – synchronous message sending. The calling code is blocked while sending the message to the SMTP server. The message can be transmitted in the form of a set of parameters - the comma-separated list of recipients, subject, content, array of attachments, and in the form of a special `EmailInfo` object, which encapsulates all this information and allows you to explicitly set the sender’s address.
+
`EmailException` may be thrown during synchronous sending, containing the information on the recipient addresses, where delivery has failed, and the corresponding error messages.
+
During the execution of the method, one `SendingMessage` instance is created in the database for all recipients. It has the initial `SendingStatus.SENDING` status, and `SendingStatus.SENT` after successful sending. In case of a message sending error, the message status changes to `SendingStatus.NOT_SENT`.
+
* sendEmailAsync() – asynchronous message sending. This method returns `SendingMessage` instance in `SendingStatus.QUEUE` status, which was created in the database. The actual sending is performed with the subsequent call of the `Emailer.processQueuedEmails()` method.

To view all emails with their statuses, go to the *Administration -> Email History* screen.

