= Label

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/sample?id=label-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`Label` is a text component that displays static text or value of an entity attribute.

Component's XML-name: `label`.

[[simple]]
== Simple Label

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=simple-label-1]
----

The `value` attribute sets the text for a label.

The text contained in `value` will be split into multiple lines if its length exceeds the `xref:vcl/xml.adoc#width[width]` value. Therefore, to display a multiline label, it is sufficient to specify an absolute value of `xref:vcl/xml.adoc#width[width]`. If the label text is too long and the value of `xref:vcl/xml.adoc#width[width]` is not specified, the text will be truncated.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=width-label]
----

[[dynamic]]
== Dynamic Label

You can set label parameters in the screen controller. To do this, you should specify a component `id` and get a reference to the component in the controller:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=dynamic-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=dynamic-label]
----

[[data-aware]]
== Data-aware Label

The `Label` component can display the value of an entity attribute. Use `xref:vcl/xml.adoc#data-container[dataContainer]` and `xref:vcl/xml.adoc#property[property]` attributes, for example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=data-aware-label]
----

In the example above, the component displays the `name` attribute of the Customer entity located in the `customerDc` data container.

[[html-label]]
== HTML Content

`htmlEnabled` attribute indicates the way the `value` attribute will be interpreted: if `htmlEnabled="true"`, the attribute will be treated as HTML code, otherwise as a plain string.

The xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] attribute enables or disables HTML sanitization. If `htmlEnabled` and `htmlSanitizerEnabled` attributes are set to `true`, then the label `value` will be sanitized.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=html-label]
----

[[predefined-styles]]
== Predefined Styles

You can set predefined styles to the `Label` component using the `stylename` attribute either in the XML descriptor or in the screen controller:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/label-screen.xml[tags=styled-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/LabelScreen.java[tag=styled-label]
----

* `bold` - bolder font weight. Suitable for important/prominent UI text.
* `colored` - colored text.
* `failure` - failure badge style. Adds a border around the label and an icon next to the text. Suitable for UI notifications that need to be used in the direct context of some component.
* `h1` - header style for main application headings.
* `h2` - header style for different sections in the application.
* `h3` - header style for different sub-sections in the application.
* `h4` - header style for different sub-sections in the application.
* `light` - lighter font weight. Suitable for additional/supplementary UI text.
* `spinner` - spinner style. Add this style name to an empty Label to create a spinner.
* `success` - success badge style. Adds a border around the label and an icon next to the text. Suitable for UI notifications that need to be used in the direct context of some component.

[[xml]]
== All XML Attributes

xref:vcl/xml.adoc#align[align] -
xref:vcl/xml.adoc#colspan[colspan] -
xref:vcl/xml.adoc#context-help-text[contextHelpText] -
xref:vcl/xml.adoc#context-help-text-html-enabled[contextHelpTextHtmlEnabled] -
xref:vcl/xml.adoc#css[css] -
xref:vcl/xml.adoc#data-container[dataContainer] -
xref:vcl/xml.adoc#description[description] -
xref:vcl/xml.adoc#description-as-html[descriptionAsHtml] -
xref:vcl/xml.adoc#box-expand-ratio[box.expandRatio] -
xref:vcl/xml.adoc#height[height] -
<<html-label, htmlEnabled>> -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] -
xref:vcl/xml.adoc#icon[icon] -
xref:vcl/xml.adoc#id[id] -
xref:vcl/xml.adoc#property[property] -
xref:vcl/xml.adoc#rowspan[rowspan] -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#visible[visible] -
xref:vcl/xml.adoc#width[width]