= Label

Label is a text component that displays static text or value of an entity attribute.

Component's XML-name: `label`

== Simple label

Below is an example of setting a label with text taken from the localized message pack:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/simplelabel/simpleLabel-screen.xml[tags=simple-label-1]
----

The value attribute sets text for a label.

In a web client, the text contained in value will be split into multiple lines if its length exceeds the xref:vcl/xml.adoc#width[width] value. Therefore, to display a multiline label, it is sufficient to specify an absolute value of xref:vcl/xml.adoc#width[width]. If the label text is too long and the value of xref:vcl/xml.adoc#width[width] is not specified, the text will be truncated.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/simplelabel/simpleLabel-screen.xml[tags=simple-label-2]
----

== Dynamic label

You can set label parameters in the screen controller. To do this, you should specify a component identifier and get a reference to the component in the controller:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/dynamiclabel/dynamicLabel-screen.xml[tags=dynamic-label]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/dynamiclabel/DynamicLabelScreen.java[tag=dynamic-label]
----

== Dataaware label

The Label component can display value of an entity attribute. For this purpose, xref:vcl/xml.adoc#data-container[dataContainer] and xref:vcl/xml.adoc#property[property] attributes are used. For example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/dataawarelabel/dataawareLabel-screen.xml[tags=dataaware-label]
----

In the example above, component displays the name attribute of the Customer entity located in the customerDc data container.

== Label with HTML content

htmlEnabled attribute indicates the way the value attribute will be interpreted: if htmlEnabled="true", the attribute will be treated as HTML code, otherwise as a plain string.

The htmlSanitizerEnabled attribute enables or disables HTML sanitization. If htmlEnabled and htmlSanitizerEnabled attributes are set to true, then the label value will be sanitized.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/label/htmllabel/HtmlLabelScreen.java[tag=html-label]
----

== Label styles

In Web Client with a Halo-based theme, you can set predefined styles to the Label component using the stylename attribute either in the XML descriptor or in the screen controller:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/label/simplelabel/simpleLabel-screen.xml[tags=styled-label]
----

[[xml]]
=== Predefined styles of label
* bold - bolder font weight. Suitable for important/prominent UI text.
* colored - colored text.
* failure - failure badge style. Adds a border around the label and an icon next to the text. Suitable for UI notifications that need to be used in the direct context of some component.
* dropzone-description
* failure
* h1 - header style for main application headings.
* h2 - header style for different sections in the application.
* h3 - header style for different sub-sections in the application.
* h4 - header style for different sub-sections in the application.
* huge
* large
* light - lighter font weight. Suitable for additional/supplementary UI text.
* no-margin - removes default margins from the header.
* small
* spinner - spinner style. Add this style name to an empty Label to create a spinner.
* success - success badge style. Adds a border around the label and an icon next to the text. Suitable for UI notifications that need to be used in the direct context of some component.
* tiny

=== Attributes of label
TODO

=== Elements of label
TODO

=== API
TODO