= Customize the Helium Theme

The simplest way to customize the default *Helium* theme is to use the interactive editor https://helium-editor.cuba-platform.com/#main[available online]. Here you can create your color preset and then use it in your project. To do this, follow steps:

. Extend the Helium theme in your project using JMIX Studio: right-click on the *Backoffice UI* node in the Jmix project window and select *New -> Custom Theme*. Enter the new theme name, for example, `helium-extended`, and select the *helium* theme in the *Base theme* dropdown.
. Open the online https://helium-editor.cuba-platform.com/#main[Theme editor]. Here you can play around with the available styling variables and see the result right away.
. Once the theme meets your requirements, tap the *Download* button.
. Copy variable declarations and place them to the `helium-extended.scss` file, for example:
+
[source, css,indent=0]
----
include::example$/ex1/src/main/themes/helium-extended/helium-extended.scss[tags=start;helium-extended;end]
----
. Restart the application. Now the user will see the application in the *Helium-extended* theme on the first login.