= Extending an Existing Theme

You should modify a built-in theme in the real project. In the modified theme, you can:

* Change branding images.

* Add icons to use them in visual components. See the xref:icons.adoc[Icons] section below.

* Create new styles for visual components and use them in the xref:vcl/xml.adoc#stylename[stylename] attribute. This requires some expertise in CSS.

* Modify existing styles of the visual components.

* Modify common parameters, such as background color, margins, spacing, etc.

An extended theme must comply with the following requirements:

* A theme must have a unique name.
* A theme with its resources must be located in the `src/main/themes/<theme-name>` directory.
* A `<theme-name>-theme.properties` file must be located in the resources.
* `styles.scss` is an entry point to compile the theme

== File Structure and Build Scripts

Themes are defined in https://sass-lang.com/[SCSS] files. To modify a theme in the project, you should create a specific file structure in the `src/main/themes/<theme-name>` directory.

A convenient way to do this is to use JMIX Studio: right-click on the *Backoffice UI* node in the Jmix project window and select *New -> Custom Theme*. Enter a unique theme name and select the theme you want to extend in the *Base theme* dropdown.

As a result, the following directory structure will be created in the modules/web directory (for Halo theme extension):

//Applying Custom Color Preset
== Customize the Helium Theme

The Helium theme has the ability to customize styling with minimal efforts for both end-users and developers.

. Extend the Helium theme: right-click on the *Backoffice UI* node in the Jmix project window and select *New -> Custom Theme*. Enter the new theme name and select the *helium* theme in the *Base theme* dropdown.
. Open the https://helium-editor.cuba-platform.com/#main[Theme editor]. Here you can play around with the available styling variables and see the result right away.
. Once the theme meets your requirements tap the *Download* button.
. Copy variable declarations and place them to the `helium-extended.scss` file, for example:
+
[source, scss,indent=0]
----
include::example$/ex1/src/main/themes/helium-extended/helium-extended.scss[tags=helium-extended]
----