= BulkEditAction

`BulkEditAction` – это действие с xref:actions/standard-actions.adoc#list-actions[коллекцией], предназначенное для изменения значений атрибутов сразу нескольких выбранных экземпляров xref:data-model:entities.adoc[сущностей]. Оно открывает специальный экран, в котором пользователь может ввести желаемые значения атрибутов. После этого, действие обновляет выбранные сущности в базе данных и в контейнере данных UI-компонента.

Действие реализовано классом `io.jmix.ui.action.list.BulkEditAction` и объявляется в XML с помощью атрибута `type="bulkEdit"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `BulkEditAction`.

== Свойства

Следующие параметры можно установить и в XML, и в Java:

* `openMode` - режим открытия экрана задания значений атрибутов, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию, экран открывается в режиме `DIALOG`.
* `columnsMode` - количество колонок в экране, задаваемое значением перечисления `ColumnsMode`. По умолчанию `TWO_COLUMNS`.
* `exclude` - регулярное выражение для исключения некоторых атрибутов сущности из экрана.
* `includeProperties` - список атрибутов сущности, которые должны быть показаны в экране. Данный список имеет более высокий приоритет чем выражение `exclude`.
* `loadDynamicAttributes` - отображать ли xref:dyn-attr:index.adoc[динамические атрибуты в экране]. По умолчанию `true`.
* `useConfirmDialog` - отображать ли диалог подтверждения перед применением изменений. По умолчанию `true`.

Например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=bulk-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=bulk-action;on-init-start;bulk-action-set;on-init-end]
----

== Слушатели

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== fieldSorter

Это обработчик, принимающий список объектов MetaProperty, соответствующих атрибутам сущности, и возвращающий мэп этих объектов на желаемую позицию в экране. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=field-sorter]
----

== Использование ActionPerformedEvent

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается кастомный диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=bulk-action;bulk-action-performed-event]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать `BulkEditors` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры: `caption`, `icon`, и т.д. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=for-bulk-action;bulk-edit-action-performed-event]
----