= BulkEditAction
:page-aliases: backoffice-ui:actions/standard-actions/bulk-edit-action.adoc

`BulkEditAction` is a xref:actions/standard-actions.adoc#list-actions[list action] designed to change attribute values for multiple xref:data-model:entities.adoc[entity] instances at once. It opens a special screen where the user can enter desired attribute values. After that, the action updates the selected entities in the database and in the data container of the UI component.

The action is implemented by the `io.jmix.ui.action.list.BulkEditAction` class and should be defined in XML using `type="bulkEdit"` action’s attribute. You can configure common action parameters using XML attributes of the action element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details. Below we describe parameters specific to the `BulkEditAction` class.

== Properties

The following parameters can be set both in XML and in Java:

* `openMode` - the bulk edit screen opening mode as a value of the `OpenMode` enum: `NEW_TAB`, `DIALOG`, etc. By default, the screen is opened in the `DIALOG` mode.
* `columnsMode` - the number of columns in the bulk edit screen as a value of the `ColumnsMode` enum. `TWO_COLUMNS` by default.
* `exclude` - a regular expression to exclude entity attributes from displaying in the editor.
* `includeProperties` - a list of entity attributes to be shown in the editor. This list has a higher priority than the `exclude` expression.
* `loadDynamicAttributes` - whether to display xref:dyn-attr:index.adoc[dynamic attributes] in the editor screen. The default value is `true`.
* `useConfirmDialog` - whether to show a confirmation dialog before saving the changes. The default value is `true`.

For example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=bulk-action]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=bulk-action;on-init-start;bulk-action-set;on-init-end]
----

== Handlers

Now let's consider parameters that can be configured only in Java code. To generate correctly annotated method stubs for these parameters, use xref:studio:index.adoc[Studio].

=== fieldSorter

It is a handler that accepts the MetaProperty objects' list denoting entity attributes and returns a map of these objects to the desired index in the edit screen. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=field-sorter]
----

== Using ActionPerformedEvent

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent` and invoke the `execute()` method of the action when needed. In the example below, we show a custom confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=bulk-action;bulk-action-performed-event]
----

You can also subscribe to `ActionPerformedEvent`, and instead of invoking the action’s `execute()` method, use `BulkEditors` API directly. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like `caption`, `icon`, etc. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=for-bulk-action;bulk-edit-action-performed-event]
----