= EditAction

`EditAction` – это xref:actions/standard-actions.adoc#list-actions[действие с коллекцией], предназначенное для редактирования экземпляров xref:data-model:entities.adoc[сущности]. Оно открывает экран редактирования с экземпляром сущности, выбранным в UI-компоненте. После того, как экземпляр сохранен в базу данных экраном редактирования, действие обновляет его в контейнере данных UI-компонента.

Действие реализовано классом `io.jmix.ui.action.list.EditAction` и объявляется в XML с помощью атрибута `type="edit"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `EditAction`.

== Параметры

Следующие параметры можно установить и в XML, и в Java:

* `openMode` - режим открытия экрана редактирования, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию экран открывается в режиме `THIS_TAB`.
* `screenId` - строковый идентификатор экрана редактирования. По умолчанию используется экран, аннотированный `@PrimaryEditorScreen`, или имеющий идентификатор вида `<entity_name>.edit`, например `demo_Order.edit`.
* `screenClass` - класс Java экрана редактирования. Данный параметр имеет более высокий приоритет, чем `screenId`.

Например, если необходимо открыть определенный экран редактирования в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=edit-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-edit-action;on-init-start;edit-action-set;on-init-end]
----

== Обработчики

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

Это обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран редактирования. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-screen-options-supplier]
----

Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

=== screenConfigurer

Это обработчик, принимающий экран редактирования для его конфигурации перед открытием. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-screen-configurer]
----

Обратите внимание, что конфигуратор экрана вступает в действие, когда экран уже инициализирован, но еще не показан, то есть после `InitEvent` и `AfterInitEvent`, и до `BeforeShowEvent`.

=== transformation

Это обработчик, вызываемый после того, как сущность выбрана и прошла валидацию в экране редактирования. Он принимает выбранную сущность и может быть использован для того, чтобы преобразовать закоммиченную сущность перед ее установкой в целевой контейнер данных. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-transformation]
----

=== afterCommitHandler

Это обработчик, вызываемый после коммита созданного экземпляра сущности в экране редактирования. Принимает созданную сущность. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-after-commit-handler]
----

=== afterCloseHandler

Это обработчик, вызываемый после закрытия экрана выбора. Принимает `AfterCloseEvent`. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-after-close-handler]
----

== Использование ActionPerformedEvent

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-edit-action;edit-action-performed-event]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана выбора `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры: `caption`, `icon`, и т.д. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-screen-builders;edit-action-performed-event-2]
----