= 编辑
:page-aliases: backoffice-ui:actions/standard-actions/edit-action.adoc

`EditAction` 是一个 xref:actions/standard-actions.adoc#list-actions[列表操作]，用来编辑实体实例。能为在 UI 组件中选择的实体打开编辑界面。在编辑界面保存了实体实例之后，会将其添加至 UI 组件的数据容器。

该操作通过 `io.jmix.ui.action.list.EditAction` 类实现，在 XML 中需要使用操作属性 `type="edit"` 定义。可以用 `action` 元素的 XML 属性定义通用的操作参数，参阅 xref:actions/declarative-actions.adoc[声明式操作] 了解细节。下面我们介绍 `EditAction` 类特有的参数。

== 属性

下列参数可以在 XML 或 Java 中设置：

* `openMode` - 编辑界面的打开模式，是 `OpenMode` 枚举类型值：`NEW_TAB`、`DIALOG` 等。默认情况下，`EditAction` 用 `THIS_TAB` 模式打开编辑界面。
* `screenId` - 编辑界面的字符串 id。`EditAction` 默认会使用带有 `@PrimaryEditorScreen` 注解的界面，或标识符为 `<entity_name>.edit` 格式的界面，例如，`demo_Customer.edit`。
* `screenClass` - 编辑界面控制器的 Java 类。比 `screenId` 有更高的优先级。

示例，需要以对话框方式打开一个特定的编辑界面，可以在 XML 中这样配置操作：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=edit-action]
----

或者，可以在界面控制器注入该操作，然后用 setter 配置：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-edit-action;on-init-start;edit-action-set;on-init-end]
----

== 处理器

下面了解这些只能用 Java 配置的参数。用 xref:studio:index.adoc[Studio] 能为这些参数正确生成带注解的方法。

=== screenOptionsSupplier

返回 `ScreenOptions` 对象，返回值可以传递给打开的编辑界面。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-screen-options-supplier]
----

返回的 `ScreenOptions` 对象可以在打开界面的 `InitEvent` 中使用。

=== screenConfigurer

接收编辑界面作为参数并能在打开之前初始化界面。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-screen-configurer]
----

注意，界面 configurer 会在界面已经初始化但是还未显示时生效，即在界面的 `InitEvent` 和 `AfterInitEvent` 事件之后，但是在 `BeforeShowEvent` 之前。

=== transformation

在编辑界面选择实体并验证之后调用。接收选中的实体作为参数。可以用这个处理器对选中的实体做一些处理，然后再传递给接收的数据容器。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-transformation]
----

=== afterCommitHandler

当实体实例在编辑界面提交之后会调用。接收更新的实体作为参数。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-after-commit-handler]
----

=== afterCloseHandler

在编辑界面关闭后调用。`AfterCloseEvent` 事件会传递给该处理器。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=edit-after-close-handler]
----

== 使用 ActionPerformedEvent

如果需要在该操作执行前做一些检查或者与用户做一些交互，可以订阅操作的 `ActionPerformedEvent` 事件并按需调用操作的 `execute()` 方法。操作会使用你为它定义的所有参数进行调用。下面的例子中，我们在执行操作前展示了一个确认对话框：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-edit-action;edit-action-performed-event]
----

另外，还可以先订阅 `ActionPerformedEvent`，但是不调用操作的 `execute()` 方法，而是使用 `ScreenBuilders` API 直接打开查找界面。此时，会忽略所有特殊的操作参数和行为，只能用其通用参数，比如 `caption`、`icon` 等。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-screen-builders;edit-action-performed-event-2]
----
