= EntityLookupAction

`EntityLookupAction` – это xref:actions/standard-actions.adoc#picker-actions[действие поля выбора] сущности, предназначенное для установки экземпляра xref:data-model:entities.adoc[сущности] в поле из xref:vcl/components/entity-picker.adoc[EntityPicker].

Действие реализовано классом `io.jmix.ui.action.entitypicker.EntityLookupAction` и объявляется в XML с помощью атрибута `type="entity_lookup"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `LookupAction`.

== Параметры

Следующие параметры можно установить и в XML, и в Java:

* `openMode` - режим открытия экрана выбора, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию экран открывается в режиме `THIS_TAB`.
* `screenId` - строковый идентификатор экрана выбора. По умолчанию используется экран, аннотированный `@PrimaryEditorScreen`, или имеющий идентификатор вида `<entity_name>.browse`, например `demo_Customer.browse`.
* `screenClass` - класс Java экрана выбора. Данный параметр имеет более высокий приоритет, `screenId`.

Например, если необходимо открыть определенный экран выбора в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=lookup-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-customer-lookup;on-init-start;set-entity-lookup-action;end]
----

== Обработчики

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

Это обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран выбора. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=lookup-screen-options-supplier]
----

Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

=== screenConfigurer

Это обработчик, принимающий экран выбора для его конфигурирования перед открытием. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=lookup-screen-configurer]
----

Обратите внимание, что конфигуратор экрана вступает в действие, когда экран уже инициализирован, но еще не показан, то есть после `InitEvent` и `AfterInitEvent`, и до `BeforeShowEvent`.

[[select-validator]]
=== selectValidator

Это обработчик, вызываемый когда пользователь нажимает *Select* в экране выбора. Он принимает объект, содержащий коллекцию выбранных сущностей. Первый элемент коллекции будет установлен в поле. Данный обработчик можно использовать для проверки выбора по каким-либо критериям. Обработчик должен вернуть `true` для того, чтобы процесс был продолжен и экран выбора закрылся. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=lookup-select-validator]
----

[[transformation]]
=== transformation

Это обработчик, вызываемый после того, как сущность выбрана и прошла валидацию в экране выбора. Первый элемент коллекции будет установлен в поле. Он принимает выбранную сущность и может быть использован для того, чтобы преобразовать закоммиченную сущность перед ее установкой в целевой контейнер данных. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=lookup-transformation]
----

=== afterCloseHandler

Это обработчик, вызываемый после закрытия экрана выбора. Принимает `AfterCloseEvent`. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=lookup-after-close-handler]
----

== Использование ActionPerformedEvent

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=lookup-action-performed-event]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана выбора `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры: `caption`, `icon`, и т.д. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-screen-builders;inject-cEntityField;lookup-action-performed-event-2]
----