= EntityOpenAction

`EntityOpenAction` is an entity picker action designed to open an editor screen for the entity currently selected in the xref:vcl/components/entity-picker.adoc[entity picker].

The action is implemented by `io.jmix.ui.action.entitypicker.EntityOpenAction` class and should be defined in XML using `type="entity_open"` action’s attribute. You can configure common action parameters using XML attributes of the `action` element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details. Below we describe parameters specific to the `EntityOpenAction` class.

== Properties

The following parameters can be set both in XML and in Java:

* `openMode` - the editor screen opening mode as a value of the `OpenMode` enum: `NEW_TAB`, `DIALOG`, etc. By default, `EntityOpenAction` opens the editor in `THIS_TAB` mode.
* `screenId` - string id of the editor screen to use. By default, `EntityOpenAction` uses either a screen, annotated with `@PrimaryEditorScreen`, or having identifier in the format of `<entity_name>.edit`, for example, `demo_Customer.edit`.
* `screenClass` - Java class of the editor screen controller to use. It has a higher priority than `screenId`.

For example, if you want to open a specific editor screen as a dialog, you can configure the action in XML:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=open-action]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-open-action;on-init-start;set-entity-open-action;end]
----

== Handlers

Now let’s consider parameters that can be configured only in Java code. To generate correctly annotated method stubs for these parameters, use xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

It is a handler that returns the `ScreenOptions` object to be passed to the opened editor screen. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-screen-options-supplier]
----

The returned `ScreenOptions` object will be available in the `InitEvent` of the opened screen.

=== screenConfigurer

It is a handler that accepts the editor screen and can initialize it before opening. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-screen-configurer]
----

=== afterCloseHandler

It is a handler that is invoked after the editor screen is closed. `AfterCloseEvent` is passed to the handler. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-after-close-handler]
----

== Using ActionPerformedEvent

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent` and invoke the `execute()` method of the action when needed. The action will be invoked with all parameters that you defined for it. In the example below, we show a confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-action-performed-event]
----
<1> Execute action

You can also subscribe to `ActionPerformedEvent`, and instead of invoking the action’s `execute()` method, use `ScreenBuilders` API directly to open the edit screen. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like `caption`, `icon`, etc. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-screen-builders;inject-cEntityField;open-action-performed-event-2]
----