= EntityClearAction

`EntityClearAction` – это xref:actions/standard-actions.adoc#picker-actions[действие поля выбора] сущности, предназначенное для очистки значения xref:vcl/components/entity-picker.adoc[EntityPicker]. Если поле связано с атрибутом, являющимся one-to-one composition, то экземпляр xref:data-model:entities.adoc[сущности], отображаемый в поле, будет удален при коммите `DataContext` (если экран является редактором сущности, это происходит при нажатии пользователем на *OK*).

Действие реализовано классом `io.jmix.ui.action.entitypicker.EntityClearAction` и объявляется в XML с помощью атрибута `type="entity_clear"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[].

== Использование ActionPerformedEvent

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-customerFieldClear;entity-clear-action-performed-event]
----