= 打开实体
:page-aliases: backoffice-ui:actions/standard-actions/entity-open-action.adoc

`EntityLookupAction` 是一个实体选择器操作，支持为 xref:vcl/components/entity-picker.adoc[EntityPicker] 中选择的实体打开编辑界面。

该操作通过 `io.jmix.ui.action.entitypicker.EntityOpenAction` 类实现，在 XML 中需要使用操作属性 `type="entity_open"` 定义。可以用 `action` 元素的 XML 属性定义通用的操作参数，参阅 xref:actions/declarative-actions.adoc[声明式操作] 了解细节。下面我们介绍 `EntityOpenAction` 类特有的参数。

== 属性

下列参数可以在 XML 或 Java 中设置：

* `openMode` - 编辑界面的打开模式，是 `OpenMode` 枚举类型值：`NEW_TAB`、`DIALOG` 等。默认情况下，`EntityOpenAction` 用 `THIS_TAB` 模式打开编辑界面。
* `screenId` - 编辑界面的字符串 id。`EntityOpenAction` 默认会使用带有 `@PrimaryEditorScreen` 注解的界面，或标识符为 `<entity_name>.edit` 格式的界面，例如，`demo_Customer.edit`。
* `screenClass` - 编辑界面控制器的 Java 类。比 `screenId` 有更高的优先级。

示例，需要以对话框方式打开一个特定的编辑界面，可以在 XML 中这样配置操作：

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=open-action]
----

或者，可以在界面控制器注入该操作，然后用 setter 配置：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-open-action;on-init-start;set-entity-open-action;end]
----

== 处理器

下面了解这些只能用 Java 配置的参数。用 xref:studio:index.adoc[Studio] 能为这些参数正确生成带注解的方法。

=== screenOptionsSupplier

返回 `ScreenOptions` 对象，返回值可以传递给打开的编辑界面。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-screen-options-supplier]
----

返回的 `ScreenOptions` 对象可以在打开界面的 `InitEvent` 中使用。

=== screenConfigurer

接收编辑界面作为参数并能在打开之前初始化界面。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-screen-configurer]
----

=== afterCloseHandler

在编辑界面关闭后调用。`AfterCloseEvent` 事件会传递给该处理器。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-after-close-handler]
----

== 使用 ActionPerformedEvent

如果需要在该操作执行前做一些检查或者与用户做一些交互，可以订阅操作的 `ActionPerformedEvent` 事件并按需调用操作的 `execute()` 方法。操作会使用你为它定义的所有参数进行调用。下面的例子中，我们在执行操作前展示了一个确认对话框：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-action-performed-event]
----
<1> 执行操作

另外，还可以先订阅 `ActionPerformedEvent`，但是不调用操作的 `execute()` 方法，而是使用 `ScreenBuilders` API 直接打开查找界面。此时，会忽略所有特殊的操作参数和行为，只能用其通用参数，比如 `caption`、`icon` 等。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-screen-builders;inject-cEntityField;open-action-performed-event-2]
----
