= EntityOpenAction

`EntityOpenAction`  – это xref:actions/standard-actions.adoc#picker-actions[действие поля выбора] сущности, предназначенное для открытия экрана редактирования для выбранного в xref:vcl/components/entity-picker.adoc[EntityPicker] в данный момент экземпляра сущности.

Действие реализовано классом `io.jmix.ui.action.entitypicker.EntityOpenAction` и объявляется в XML с помощью атрибута `type="entity_open"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `EntityOpenAction`.

== Параметры

The following parameters can be set both in XML and in Java:

* `openMode` - режим открытия экрана редактирования, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию экран открывается в режиме `THIS_TAB`.
* `screenId` - строковый идентификатор экрана выбора. По умолчанию используется экран, аннотированный `@PrimaryEditorScreen`, или имеющий идентификатор вида `<entity_name>.edit`, например `demo_Customer.edit`.
* `screenClass` - класс Java экрана редактирования. Данный параметр имеет более высокий приоритет, `screenId`.

Например, если необходимо открыть определенный экран редактирования в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source, xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=open-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-open-action;on-init-start;set-entity-open-action;end]
----

== Обработчики

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

Это обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран редактирования. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-screen-options-supplier]
----

Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

=== screenConfigurer

Это обработчик, принимающий экран редактирования для его конфигурации перед открытием. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-screen-configurer]
----

=== afterCloseHandler

Это обработчик, вызываемый после закрытия экрана редактирования. Принимает `AfterCloseEvent`. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-after-close-handler]
----

== Использование ActionPerformedEvent

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=open-action-performed-event]
----
<1> Выполнение действия

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана редактирования `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры: `caption`, `icon`, и т.д. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/entitypicker/EntityPickerScreen.java[tags=inject-screen-builders;inject-cEntityField;open-action-performed-event-2]
----