= ExcludeAction

`ExcludeAction` – это xref:actions/standard-actions.adoc#list-actions[действие с коллекцией], предназначенное для удаления экземпляров xref:data-model:entities.adoc[сущности] из контейнера данных в UI. В отличие от `RemoveAction`, `ExcludeAction` не удаляет сущности из базы данных, что требуется, например, при работе с many-to-many коллекциями.

Действие реализовано классом `io.jmix.ui.action.list.ExcludeAction` и объявляется в XML с помощью атрибута `type="exclude"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `ExcludeAction`.

== Параметры

Следующие параметры можно установить и в XML, и в Java:

* `confirmation` - булевское значение, указывающее, отображать ли диалог подтверждения перед удалением выбранных сущностей. По умолчанию `true`.
* `confirmationMessage` - сообщение диалога подтверждения. По умолчанию, берется из главного пакета сообщений по ключу `dialogs.Confirmation.Remove`.
* `confirmationTitle` - заголовок диалога подтверждения. По умолчанию, берется из главного пакета сообщений по ключу `dialogs.Confirmation`.

Например, если необходимо задать определенное сообщение диалога подтверждения, можно сконфигурировать действие в XML:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/entity/customer/customer-edit.xml[tags=exclude-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action;on-init-start;exclude-action-set;on-init-end]
----

== Обработчики

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== afterActionPerformedHandler

Это обработчик, вызываемый после того, как выбранные сущности удалены. Принимает объект события, который можно использовать для получения выбранных для удаления экземпляров. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-after-action-performed-handler]
----

=== actionCancelledHandler

Это обработчик, вызываемый если операция удаления отменена пользователем в диалоге подтверждения. Принимает объект события, который можно использовать для получения выбранных для удаления экземпляров. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action-cancelled-handler]
----

== Использование ActionPerformedEvent

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action-performed-event]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана выбора `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры: `caption`, `icon`, и т.д. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=inject-remove-operation;exclude-action-performed-event-2]
----