= 移除
:page-aliases: backoffice-ui:actions/standard-actions/exclude-action.adoc

`ExcludeAction` 是一个 xref:actions/standard-actions.adoc#list-actions[列表操作]，用来从 UI 的数据容器中移除实体实例。与 `RemoveAction（删除）` 不同，`ExcludeAction` 不会从数据库删除选中的实例。在处理多对多集合的时候，需要该操作。

该操作通过 `io.jmix.ui.action.list.ExcludeAction` 类实现，在 XML 中需要使用操作属性 `type="exclude"` 定义。可以用 `action` 元素的 XML 属性定义通用的操作参数，参阅 xref:actions/declarative-actions.adoc[声明式操作] 了解细节。下面我们介绍 `ExcludeAction` 类特有的参数。

== 属性

下列参数可以在 XML 或 Java 中设置：

* `confirmation` - 布尔值，配置是否需要在移除选中实体之前展示确认对话框。默认为 `true`。
* `confirmationMessage` - 确认窗口的消息。默认从主消息包的 `dialogs.Confirmation.Remove` 键值获取。
* `confirmationTitle` - 确认窗口标题。默认从主消息包的 `dialogs.Confirmation` 键值获取。

比如，希望展示特殊的确认消息，可以在 XML 中如下配置：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/entity/customer/customer-edit.xml[tags=exclude-action]
----

或者，可以在界面控制器注入该操作，然后用 setter 配置：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action;on-init-start;exclude-action-set;on-init-end]
----

== 处理器

下面了解这些只能用 Java 配置的参数。用 xref:studio:index.adoc[Studio] 能为这些参数正确生成带注解的方法。

=== afterActionPerformedHandler

在选中实体移除之后调用。接收 `event` 对象作为参数，可以用来获取要移除的实体。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-after-action-performed-handler]
----

=== actionCancelledHandler

当用户在确认窗口取消移除操作时会调用。接收 `event` 对象，可以用来获取要移除的实体。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action-cancelled-handler]
----

== 使用 ActionPerformedEvent

如果需要在该操作执行前做一些检查或者与用户做一些交互，可以订阅操作的 `ActionPerformedEvent` 事件并按需调用操作的 `execute()` 方法。操作会使用你为它定义的所有参数进行调用。下面的例子中，我们在执行操作前展示了一个自定义对话框：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=exclude-action-performed-event]
----

另外，还可以先订阅 `ActionPerformedEvent`，但是不调用操作的 `execute()` 方法，而是使用 `RemoveOperation` API 直接移除选择的实体。此时，会忽略所有特殊的操作参数和行为，只能用其通用参数，比如 `caption`、`icon` 等。示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerEdit.java[tags=inject-remove-operation;exclude-action-performed-event-2]
----
