= RefreshAction

`RefreshAction`  – это xref:actions/standard-actions.adoc#list-actions[действие с коллекцией], предназначенное для перезагрузки контейнера данных, используемого таблицей или деревом.

Действие реализовано классом `io.jmix.ui.action.list.RefreshAction` и объявляется в XML с помощью атрибута `type="refresh"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[].

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-refresh-action;refresh-action-performed-event]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, запустить нужный загрузчик напрямую. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-customersDl;refresh-action-performed-event-2]
----