= RefreshAction
:page-aliases: backoffice-ui:actions/standard-actions/refresh-action.adoc

`RefreshAction` is a xref:actions/standard-actions.adoc#list-actions[list action]  designed to reload the data container used by the table or tree component.

The action is implemented by the `io.jmix.ui.action.list.RefreshAction` class and should be defined in XML using `type="refresh"` action’s attribute. You can configure common action parameters using XML attributes of the action element. See xref:actions/declarative-actions.adoc[Declarative Actions] for details.

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action’s `ActionPerformedEvent` and invoke the `execute()` method of the action when needed. In the example below, we show a custom confirmation dialog before executing the action:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-refresh-action;refresh-action-performed-event]
----

You can also subscribe to `ActionPerformedEvent`, and instead of invoking the action’s `execute()` method, trigger the data loader directly. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-customersDl;refresh-action-performed-event-2]
----