= RelatedAction

`RelatedAction` – это xref:actions/standard-actions.adoc#list-actions[действие с коллекцией], предназначенное для открытия экрана браузера со списком связанных сущностей. Связанные сущности отбираются с учетом пользовательских разрешений для сущностей, атрибутов сущностей и экранов.

[NOTE]
====
Экран браузера со списком связанных сущностей должен содержать компонент Filter.
====

Действие реализовано классом `io.jmix.ui.action.list.RelatedAction` и объявляется в XML с помощью атрибута `type="related"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `RelatedAction`.

== Параметры

Следующие параметры можно установить и в XML, и в Java:

* `openMode` - режим открытия экрана, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию экран открывается в режиме `THIS_TAB`.
* `screenId` - строковый идентификатор экрана. По умолчанию используется экран, аннотированный `@PrimaryEditorScreen`, или имеющий идентификатор вида `<entity_name>.browse`, например `demo_Customer.browse`.
* `screenClass` - класс Java экрана. Данный параметр имеет более высокий приоритет, `screenId`.
* `property` - свойство, из которого нужно отобразить связанные сущности.
* `configurationName` - заголовок, который будет присвоен фильтру в открывшемся экране.

Например, если необходимо открыть определенный экран в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/entity/customer/customer-browse.xml[tags=related-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerBrowse.java[tags=inject-relatedAction;onInit-start;relatedAction-set;onInit-end]
----

== Обработчики

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== screenOptionsSupplier

Это обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран выбора. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerBrowse.java[tags=related-screen-options-supplier]
----

Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

=== screenConfigurer

Это обработчик, принимающий экран для его конфигурирования перед открытием. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerBrowse.java[tags=related-screen-configurer]
----

Обратите внимание, что конфигуратор экрана вступает в действие, когда экран уже инициализирован, но еще не показан, то есть после `InitEvent` и `AfterInitEvent`, и до `BeforeShowEvent`.

=== afterCloseHandler

Это обработчик, вызываемый после закрытия экрана. Принимает `AfterCloseEvent`. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerBrowse.java[tags=related-after-close-handler]
----

== Using ActionPerformedEvent
Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана выбора `ScreenBuilders` API напрямую. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/customer/CustomerBrowse.java[tags=related-action-performed-event]
----