= RemoveAction

`RemoveAction` is a xref:actions/standard-actions.adoc#list-actions[list action] designed to remove xref:data-model:entities.adoc[entity] instances from a data container in UI and the database.

Действие реализовано классом `io.jmix.ui.action.list.RemoveAction` и объявляется в XML с помощью атрибута `type="remove"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел xref:actions/declarative-actions.adoc[]. Ниже рассматриваются параметры, специфичные для класса `RemoveAction`.

== Параметры

Следующие параметры можно установить и в XML, и в Java:

* `confirmation` - булевское значение, указывающее, отображать ли диалог подтверждения перед удалением. По умолчанию true.
* `confirmationMessage` - сообщение диалога подтверждения. По умолчанию, берется из главного пакета сообщений по ключу `dialogs.Confirmation.Remove`.
* `confirmationTitle` - заголовок диалога подтверждения. По умолчанию, берется из главного пакета сообщений по ключу `dialogs.Confirmation`.

Например, если необходимо задать определенное сообщение диалога подтверждения, можно сконфигурировать действие в XML:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=remove-action]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-remove-action;on-init-start;remove-action-set;on-init-end]
----

== Обработчики

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте xref:studio:index.adoc[Studio].

=== afterActionPerformedHandler

Это обработчик, вызываемый после того, как выбранные сущности удалены. Принимает объект события, который можно использовать для получения выбранных для удаления экземпляров. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=remove-after-action-performed-handler]
----

=== actionCancelledHandler

Это обработчик, вызываемый если операция удаления отменена пользователем в диалоге подтверждения. Принимает объект события, который можно использовать для получения выбранных для удаления экземпляров. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=remove-action-cancelled-handler]
----

== Использование ActionPerformedEvent

Для того чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:


[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-table-remove-action;remove-action-performed-event]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана выбора `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры: `caption`, `icon`, и т.д. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-remove-operation;remove-action-performed-event-2]
----