= ClipboardTrigger

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/1/sample?id=facet-clipboard-trigger" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`ClipboardTrigger` is a facet that allows a user to copy text from a field to the clipboard.

Component’s XML-name: `clipboardTrigger`.

[[basics]]
== Basics

`ClipboardTrigger` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

[[input]] 1. `input` - defines `id` of the component from which the text content will be copied. It is possible to associate the `ClipboardTrigger` with the following components:

* xref:vcl/components/masked-field.adoc[]
* xref:vcl/components/password-field.adoc[]
* xref:vcl/components/resizable-text-area.adoc[]
* xref:vcl/components/rich-text-area.adoc[]
* xref:vcl/components/text-area.adoc[]
* xref:vcl/components/text-field.adoc[]

[[button]] 2. `button` - defines `id` of the xref:vcl/components/button.adoc[] that triggers the copying.

[TIP]
With the help of `isSupportedByWebBrowser()` method you can check whether the user’s browser supports copying or not.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/clipboardtrigger/clipboard-trigger-screen.xml[tags=usage-example]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/clipboardtrigger/ClipboardTriggerScreen.java[tags=clipboard-trigger-usage-example]
----

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[copy-event]]
=== CopyEvent

This event fires when the user clicks on the button related to `ClipboardTrigger` and has the following methods:

* `isSuccess()` - returns `true` if the text content was successfully copied to the client-side clipboard.
* `getSource()` - returns the object of `ClipboardTrigger` on which the event initially occurred.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/clipboardtrigger/ClipboardTriggerScreen.java[tags=clipboard-trigger-copy-event]
----

Programmatic registration of the event handler: use the `addCopyListener()` facet method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<button, button>> -
xref:vcl/xml.adoc#id[id] -
<<input, input>>