= DataLoadCoordinator

`DataLoadCoordinator` facet is designed for declarative linking of data loaders to data containers, visual components, and screen events.

Component’s XML-name: `dataLoadCoordinator`.

[[attributes]]
== Attributes

[[auto]]
* `auto` - defines `DataLoadCoordinator` working mode.
The default value is `false`.

[[component-prefix]]
* `componentPrefix` - defines a special prefix for the xref:vcl/components.adoc[component], on which `DataLoadCoordinator` will rely in automatic working mode.
The default value is `component_`.

[[container-prefix]]
* `containerPrefix` - defines a special prefix for the xref:vcl/containers.adoc[container], on which `DataLoadCoordinator` will rely in automatic working mode.
The default value is `container_`.

[[refresh-element]]
== Refresh Element

`Refresh` is a nested element that allows you to define the loader to which the current `DataLoadCoordinator` will be bound.

[[loader]]
The only attribute of this element is the `loader`, that defines the loader `id`.

It has four subelements to define the trigger for a refresh:

[[on-component-value-changed]] 1. `onComponentValueChanged` - has the following attributes:

[[component]]
* `component` - specifies the `id` of the component to which the trigger will be bound.

[[like-clause]]
* `likeClause` - if you use the `like` expression in query condition, you can define one of three possible search modes:
** `NONE` - the default value.
** `CASE_SENSITIVE` - uppercase and lowercase letters are treated as *distinct*.
** `CASE_INSENSITIVE` - uppercase and lowercase letters are treated as *equivalent*.

[[param-component]]
* `param` - defines the parameter name for the query.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-component-value-changed]
----

[[on-container-item-changed]] 2. `onContainerItemChanged` - has the following attributes:

[[container]]
* `container` - this attribute specifies the `id` of the container to which the trigger will be bound.

[[param-container]]
* `param` - defines the parameter name for the query.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-container-value-changed]
----

[[on-screen-event]] 3. `onScreenEvent` - has the following attribute:

[[type-on-screen]]
* `type` - defines the type of screen event.
There are four possible values:
** `Init` - see xref:screens/screen-events.adoc#init-event[InitEvent].
** `AfterInit` - see xref:screens/screen-events.adoc#after-init-event[AfterInitEvent].
** `BeforeShow` - see xref:screens/screen-events.adoc#before-show-event[BeforeShowEvent].
** `AfterShow` - see xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-screen-event]
----

[[on-fragment-event]] 4. `onFragmentEvent` - has the following attribute:

[[type-on-fragment]]
* `type` - defines the type of screen event.
There are four possible values:
** `Init` - see xref:screens/screen-events.adoc#init-event[InitEvent].
** `AfterInit` - see xref:screens/screen-events.adoc#after-init-event[AfterInitEvent].
** `Attach` - see xref:screens/screen-fragment-events.adoc#attach-event [AttachEvent].

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=on-fragment-event]
----

[[working-modes]]
== Working Modes

You can configure `DataLoadCoordinator` to work in three modes:

1. In automatic mode.
2. In manual mode.
3. In semi-automatic mode.

[[automatic-mode]]
=== Automatic Mode

In this mode, `DataLoadCoordinator` relies on parameter names with particular prefixes. The prefix denotes a component that produces the parameter value and changes events. If the loader has no parameters in its query text, although it can have parameters in query conditions, it is refreshed on `BeforeShowEvent` in `Screen` or `AttachEvent` in `ScreenFragment`.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/automaticmode/automatic-mode-screen.xml[tags=automatic-mode]
----

<1> Add XML schema for jpql conditions.
<2> There are no parameters in the query, so the `brandsDl` loader will be triggered on `BeforeShowEvent`.
<3> The `brandsDl` loader will also be triggered on `nameField` component value change.
As the condition uses the like clause, the value will be automatically wrapped in `'(?i)% %'` to provide the case-insensitive search.
<4> The `customersDl` is triggered on the `brandsDc` data container item change.

[[manual-mode]]
=== Manual Mode

In this mode, the nested entries define when the data loaders must be triggered.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/manualmode/manual-mode-screen.xml[tags=manual-mode]
----

<1> Add XML schema for JPQL conditions.
<2> The `citiesDl` loader will be triggered on `InitEvent`.
<3> The `citiesDl` loader will also be triggered on the `nameField` component value change.
The `likeClause` attribute causes the value to be wrapped in `'(?i)% %'` to provide the case-insensitive search.
<4> The `customersDl` will be triggered on the `citiesDc` data container item change.

[[semi-automatic-mode]]
=== Semi-automatic Mode

When the `auto` attribute is set to `true`, and there are some manually configured triggers, `DataLoadCoordinator` will automatically configure all loaders with no manual configuration.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dataloadcoordinator/semiautomaticmode/semi-automatic-mode-screen.xml[tags=semi-automatic-mode]
----

<1> The `customersDl` is configured automatically and triggered on the `brandsDc` data container item change.
<2> The `brandsDl` loader is configured manually and will be triggered on `BeforeShowEvent`.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<auto , auto>> -
<<component-prefix, componentPrefix>> -
<<container-prefix, containerPrefix>> -
xref:vcl/xml.adoc#id[id]

[[data-load-coordinator-xml-elements]]
=== DataLoadCoordinator XML Elements

<<refresh-element, refresh>>

[[refresh-xml-attributes]]
=== Refresh XML Attributes

<<loader, loader>>

[[refresh-xml-elements]]
=== Refresh XML Elements

<<on-component-value-changed, onComponentValueChanged>> -
<<on-container-item-changed, onContainerItemChanged>> -
<<on-screen-event, onScreenEvent>> -
<<on-fragment-event, onFragmentEvent>>