= DialogModeFacet

`DialogModeFacet` allows you to define settings of geometry and behavior of the screen when it is opened as a dialog.

Component’s XML-name: `dialogMode`.

[[basics]]
== Basics

`DialogModeFacet` is defined in the `window` element of the screen XML descriptor and has the following attributes:

[[closeable]]
* `closeable` - defines whether the dialog window has a close button. Possible values:
** `true` - the default value.
** `false`

[[close-on-click-outside]]
* `closeOnClickOutside` - defines if the dialog window should be closed by click outside the window area when the window has a modal mode. Possible values:
** `true`
** `false` - the default value.

[[force-dialog]]
* `forceDialog` - specifies that the screen should always be opened as a dialog. Possible values:
** `true`
** `false` - the default value.

[[height]]
* `height` - sets the height of the dialog window.

[[modal]]
* `modal` - specifies the modal mode for the dialog window. Possible values:
** `true` - the default value.
** `false`

[[position-x]]
* `positionX` - sets the x position of the top-left corner of the dialog window.

[[position-y]]
* `positionY` - sets the y position of the top-left corner of the dialog window.

[[resizable]]
* `resizable` - defines whether a user can change the size of the dialog window. Possible values:
** `true`
** `false` - the default value.

[[width]]
* `width` - sets the width of the dialog window.

[[windowMode]]
* `windowMode` - defines window mode. Possible values:
** `NORMAL` - the default value. The screen will open based on the size and position settings.
** `MAXIMIZED` - the dialog window will be maximized across the screen.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/dialogmodefacet/dialog-mode-facet-screen.xml[tags=dialog-mode]
----

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<close-on-click-outside, closeOnClickOutside>> -
<<closeable, closeable>> -
<<force-dialog, forceDialog>> -
<<height, height>> -
<<modal, modal>> -
<<position-x, positionX>> -
<<position-y, positionY>> -
<<resizable, resizable>> -
<<width, width>> -
<<windowMode, windowMode>>