= EditorScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`EditorScreenFacet` is essentially a xref:facets/screen-facet.adoc[] with an extended set of options for opening the editing screen.

Component’s XML-name: `editorScreen`.

[[attributes]]
== Attributes

In addition to all the xref:facets/screen-facet.adoc#attributes[attributes] that `ScreenFacet` has, `EditorScreenFacet` has its own attributes:

[[add-first]]
* `addFirst` - defines whether a new item will be added to the beginning or the end of the collection. It affects only standalone containers; for nested containers, new items are always added to the end.

[[container]]
* `container` - sets a xref:data/collection-container.adoc[]. The container is updated after the screen is committed. If the container is nested, the framework automatically initializes the reference to the parent entity and sets up data context for editing compositions.

[[edit-mode]]
* `editMode` - sets the screen edit mode, corresponds to the `EditMode` enum:
** `CREATE` - to create a new entity instance.
** `EDIT` - to edit an existing one.

[[entity-class]]
* `entityClass` - the full name of an entity class.

[[field]]
* `field` - sets the xref:vcl/components/entity-picker.adoc[] component id. The framework sets the committed entity to the field after a successful editor commit if the field is set.

[[list-component]]
* `listComponent` - sets the list component id. The component is used to get the container if it is not set. Usually, the list component is a xref:vcl/components/table.adoc[] or xref:vcl/components/data-grid.adoc[] displaying the list of entities.

Usage example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/editorscreenfacet/editor-screen-facet-screen.xml[tags=editor-screen-facet]
----

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

See xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent].

Programmatic registration of the event handler: use the `addAfterCloseEventListener()` component method.

[[after-show-event]]
=== AfterShowEvent

See xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

Programmatic registration of the event handler: use the `addAfterShowEventListener()` component method.

[[options-provider]]
=== OptionsProvider

See xref:facets/screen-facet.adoc#options-provider[OptionsProvider].

Programmatic usage: call the `setOptionsProvider()` component method.

[[initializer]]
=== Initializer

See xref:actions/standard-actions/create-action.adoc#initializer[Initializer].

Programmatic usage: call the `setInitializer()` component method.

[[transformation]]
=== Transformation

See xref:actions/standard-actions/create-action.adoc#transformation[Transformation].

Programmatic usage: call the `setTransformation()` component method.

[[entity-provider]]
=== EntityProvider
To pass entity to the opening screen, `EditorScreenFacet` has `EntityProvider`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/editorscreenfacet/EditorScreenFacetScreen.java[tags=entity-provider]
----

Programmatic usage: call the `setEntityProvider()` component method.

[[parent-data-context-provider]]
=== ParentDataContextProvider
To pass data context to the opening screen, `EditorScreenFacet` has `ParentDataContextProvider`. To learn more about parent `DataContext`, see the xref:data/data-context.adoc#parent-data-context[DataContext] page.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/editorscreenfacet/EditorScreenFacetScreen.java[tags=data-context]
----

Programmatic usage: call the `setParentDataContextProvider()` component method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

<<add-first, addFirst>> -
<<container, container>> -
<<entity-class, entityClass>> -
<<edit-mode, entityMode>> -
<<field, field>> -
xref:vcl/xml.adoc#id[id] -
<<list-component, listComponent>> -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]