= LookupScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`LookupScreenFacet` is essentially a xref:facets/screen-facet.adoc[] with an extended set of options for opening the lookup screen.

Component’s XML-name: `lookupScreen`.

[[attributes]]
== Attributes

In addition to all the xref:facets/screen-facet.adoc#attributes[attributes] that `ScreenFacet` has, `LookupScreenFacet` has the following attributes from xref:facets/editor-screen-facet.adoc[]:

[[container]]
* xref:facets/editor-screen-facet.adoc#container[container]

[[entity-class]]
* xref:facets/editor-screen-facet.adoc#entity-class[entityClass]

[[field]]
* xref:facets/editor-screen-facet.adoc#field[field]

[[list-components]]
* xref:facets/editor-screen-facet.adoc#list-component[listComponents]

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

See xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent].

Programmatic registration of the event handler: use the `addAfterCloseEventListener()` component method.

[[after-show-event]]
=== AfterShowEvent

See xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

Programmatic registration of the event handler: use the `addAfterShowEventListener()` component method.

[[options-provider]]
=== OptionsProvider

See xref:facets/screen-facet.adoc#options-provider[OptionsProvider].

Programmatic usage: call the `setOptionsProvider()` component method.

[[transformation]]
=== Transformation

See xref:actions/standard-actions/entity-lookup-action.adoc#transformation[Transformation].

Programmatic usage: call the `setTransformation()` component method.

[[select-validator]]
=== SelectValidator

See xref:actions/standard-actions/entity-lookup-action.adoc#select-validator[SelectValidator].

Programmatic usage: call the `setSelectValidator()` component method.

[[select-handler]]
=== SelectHandler

To get collection of selected entities' from lookup screen, `LookupScreenFacet` has `SelectHandler`. In the example below, the lookup screen of the `Customer` entity is opened on button clicks, and the email of the selected customer is written to the `textField`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/lookupscreenfacet/lookup-screen-facet-screen.xml[tags=lookup]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/lookupscreenfacet/LookupScreenFacetScreen.java[tags=select-handler]
----

Programmatic usage: call the `setSelectHandler()` component method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:facets/editor-screen-facet.adoc#container[container] -
xref:facets/editor-screen-facet.adoc#entity-class[entityClass] -
xref:facets/editor-screen-facet.adoc#field[field] -
xref:vcl/xml.adoc#id[id] -
xref:facets/editor-screen-facet.adoc#list-component[listComponent] -
xref:facets/screen-facet.adoc#on-action[onAction] -
xref:facets/screen-facet.adoc#on-button[onButton] -
xref:facets/screen-facet.adoc#open-mode[openMode] -
xref:facets/screen-facet.adoc#screen-class[screenClass] -
xref:facets/screen-facet.adoc#screen-id[screenId]