= MessageDialogFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/4/sample?id=facet-dialog" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`MessageDialogFacet` is a facet that allows you to pre-configure a xref:dialogs.adoc#message-dialog[message dialog]. Declarative definition of the message dialog replaces existing `Dialogs.createMessageDialog()` method.

Component’s XML-name: `messageDialog`.

[[attributes]]
== Attributes

`MessageDialogFacet` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

* xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside]
* xref:dialogs.adoc#msg-dialog-content-mode[contentMode]
* xref:dialogs.adoc#msg-dialog-message[message]
* xref:dialogs.adoc#msg-dialog-modal[modal]
* xref:dialogs.adoc#msg-dialog-windowMode[windowMode]

You can bind `MessageDialogFacet` to xref:actions.adoc[action] or xref:vcl/components/button.adoc[button]. In those cases, the dialog will appear when action is fires or button clicks. To aware `MessageDialogFacet` with `action` or `button`, use the following attributes:

[[on-action]]
* `onAction`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/messagedialogfacet/message-dialog-facet-screen.xml[tags=window-start;actions;facets-start;action-message;facets-end;layout-start;layout-end;window-end]
----

[[on-button]]
* `onButton`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/messagedialogfacet/message-dialog-facet-screen.xml[tags=window-start;facets-start;button-message;facets-end;layout-start;message-btn;layout-end;window-end]
----

[TIP]
====
You can also make dialog configured with `MessageDialogFacet` to appear using the `show()` method:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/messagedialogfacet/MessageDialogFacetScreen.java[tags=show]
----

====

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#caption[caption] -
xref:dialogs.adoc#msg-dialog-close-on-click-outside[closeOnClickOutside] -
xref:dialogs.adoc#msg-dialog-content-mode[contentMode] -
xref:vcl/xml.adoc#height[height] -
xref:vcl/xml.adoc#html-sanitizer-enabled[htmISanitizerEnabled] -
xref:vcl/xml.adoc#id[id] -
xref:dialogs.adoc#msg-dialog-message[message] -
xref:dialogs.adoc#msg-dialog-modal[modal] -
<<on-action, onAction>> -
<<on-button, onButton>> -
xref:vcl/xml.adoc#stylename[stylename] -
xref:vcl/xml.adoc#width[width] -
xref:dialogs.adoc#msg-dialog-windowMode[windowMode]