= ScreenFacet

++++
<div class="backoffice-ui-live-demo-container">
    <a href="https://demo.jmix.io/sampler/#main/3/sample?id=facet-screen" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`ScreenFacet` is a facet that provides an ability to pre-configure xref:opening-screens.adoc[screen opening] and xref:opening-screens.adoc#passing-parameters-to-screens[passing parameters]. Declarative definition of the screen replaces existing `ScreenBuilders.screen()` method.

Component’s XML-name: `screen`.

[[attributes]]
== Attributes

`ScreenFacet` is defined in the `facets` element of the screen XML descriptor and has the following attributes:

[[screen-id]]
* `screenId` - specifies the `id` of the screen to open.

[[screen-class]]
* `screenClass` - specifies the Java class of the screen controller to open.

[[open-mode]]
* `openMode` - defines screen open mode. There are the following possible values:
** `NEW_TAB` - open a screen in the new tab of the main window. This is the default value.
** `THIS_TAB` - open a screen on top of the current tab screens stack.
** `DIALOG` - open a screen as a modal dialog.
** `NEW_WINDOW` - open a screen in the new tab of the main window.
** `ROOT` - opens a screen as main.

You can also bind `ScreenFacet` to xref:actions.adoc[action] or xref:vcl/components/button.adoc[button]. In those cases, the screen will open when `action` is fires or `button` clicks. To aware `ScreenFacet` with `action` or `button`, use the following attributes:

[[on-action]]
* `onAction`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=window-start;actions;facets-start;action-screen-facet;facets-end;layout-start;layout-end;window-end]
----

[[on-button]]
* `onButton`

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=window-start;facets-start;button-screen-facet;facets-end;layout-start;open-new-btn;layout-end;window-end]
----

[TIP]
====
You can also open screen configured with `ScreenFacet` using the `show()` method:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=show]
----

====

[[passing-parameters]]
== Passing Parameters

To pass parameters to the screen, use the `ScreenFacet` `properties` element. This element represents a list of properties that will be injected into the opened screen via public setters.

For example, lets pass `Integer` value for `num` property from `ScreenFacetScreen` to `AnotherScreen`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/AnotherScreen.java[tags=another-screen]
----

<1> Set label to display received value.
<2> Define setter to assign the transmitted value.
<3> Assign the accepted value to the label.

In the `ScreenFacetScreen` XML-descriptor we need to define `value` and `name` attributes of the `property` element.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/facets/screenfacet/screen-facet-screen.xml[tags=window-start;facets-start;pass-params;facets-end;layout-start;btn-pass-params;layout-end;window-end]
----

[[handlers]]
== Events and Handlers

include::events-handlers-generation-facet-tip.adoc[]

[[after-close-event]]
=== AfterCloseEvent

See xref:screens/screen-events.adoc#after-close-event[AfterCloseEvent].

Programmatic registration of the event handler: use the `addAfterCloseEventListener()` component method.

[[after-show-event]]
=== AfterShowEvent

See xref:screens/screen-events.adoc#after-show-event[AfterShowEvent].

Programmatic registration of the event handler: use the `addAfterShowEventListener()` component method.

[[options-provider]]
=== OptionsProvider

To pass parameters `ScreenFacet` has options provider.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/facets/screenfacet/ScreenFacetScreen.java[tags=options-provider]
----

Programmatic usage: call the `setOptionsProvider()` component method.

[[xml]]
== All XML Attributes

include::xml-studio-facet-tip.adoc[]

xref:vcl/xml.adoc#id[id] -
<<on-action, onAction>> -
<<on-button, onButton>> -
<<open-mode, openMode>> -
<<screen-class, screenClass>> -
<<screen-id, screenId>>