= gridLayout

`gridLayout` arranges components or data items in a responsive, two-dimensional CSS grid.

[cols="1h,1" grid=none, width=50%, frame=none]
|===
|XML Element
|`gridLayout`

|Java Class
|`GridLayout`
|===

[[basics]]
== Basics

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/grid-layout-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Add child components declaratively and use `gap` and `columnMinWidth` to control spacing and responsive column sizing. Both attributes accept CSS length values and variables.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/containers/gridlayout/simple/grid-layout-simple.xml[tags=basics]
----

[[data-binding]]
== Data-aware `gridLayout`

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/grid-layout-dataaware" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Set `itemsContainer` to connect `gridLayout` to a xref:data/data-containers.adoc[collection container]. The layout creates one rendered component for each item in the container.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/containers/gridlayout/dataaware/grid-layout-dataaware.xml[tags=data-aware]
----

By default, the component displays the xref:data-model:entities.adoc#instance-name[instance name] of the entity.

TIP: You can override the default display by configuring a <<rendering-items,custom renderer>>.

[[enumeration-items]]
== Enumeration Items

The component also supports displaying enumeration values using the `itemsEnum` attribute.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/layout/gridlayout/grid-layout-view.xml[tags=itemsEnum]
----

[[rendering-items]]
[[programmatically]]
== Custom Item Renderer

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/grid-layout-renderer" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Use a renderer to replace the default item label with a component. The example connects `gridLayout` to a collection container in XML and supplies a `ComponentRenderer` from the controller with `@Supply`.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/containers/gridlayout/renderer/grid-layout-renderer.xml[tags=renderer]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/containers/gridlayout/renderer/GridLayoutRendererSample.java[tags=renderer]
----

[[fragment-renderer]]
== Fragment Renderer

Alternatively, you can render items using a nested xref:vc/miscellaneous/renderers.adoc#fragment-renderer[fragmentRenderer] element.

. Create the fragment descriptor:
+
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/layout/gridlayout/card-fragment.xml[tags=fragment-descriptor]
----

. Create the fragment controller.
+
Extend `FragmentRenderer` using the fragment root component and rendered entity as its type parameters:
+
.Show code
[%collapsible]
====
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/layout/gridlayout/CardFragment.java[tags=cardFragment]
----
====

. Use `fragmentRenderer` for a `gridLayout` component:
+
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/layout/gridlayout/grid-layout-view.xml[tags=fragmentRenderer]
----

== Attributes

xref:vc/common-attributes.adoc[Common attributes] serve the same purpose for all components. The following attributes configure `gridLayout` or its direct child elements:

[cols="2,5,1", options="header"]
|===
|Name
|Description
|Default
|[[alignSelf]]alignSelf
|Set on a child element to control its alignment within the grid cell along the block (column) axis. This corresponds to the CSS https://developer.mozilla.org/en-US/docs/Web/CSS/align-self[align-self^] property.
|`AUTO`
|[[columnMinWidth]]columnMinWidth
|Sets the minimum width for the grid columns in `gridLayout`. This ensures columns don't become too narrow when the container resizes.
The value must be a valid CSS length (for example, `"50px"` or `"10rem"`).
|`19rem`
|[[gap]]gap
|Controls the spacing between grid cells, including both row and column gaps. The value must be a valid CSS length (for example, `"10px"` or `"1rem"`).
|`0.5rem`
|[[justifySelf]]justifySelf
|Set on a child element to control its alignment within the grid cell along the inline (row) axis. This corresponds to the CSS https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/justify-self[justify-self^] property.
|`AUTO`
|===

== Handlers

xref:vc/common-handlers.adoc[Common handlers] are configured in the same way for all components.

The following handlers are specific to `gridLayout`.

[cols="2,5", options="header"]
|===
|Name
|Description
|[[itemLabelGenerator]]itemLabelGenerator
|Customizes the text produced by the default item renderer.
|[[renderer]]renderer
|Sets the renderer used to create a component for each item. See <<rendering-items,Custom Item Renderer>>.
|===

== Elements

A non-data-aware `gridLayout` can contain components directly. A data-aware layout can contain a xref:vc/miscellaneous/renderers.adoc#fragment-renderer[`fragmentRenderer`] that creates a component for each item.
