= gridLayout

`gridLayout` располагает компоненты или элементы данных в адаптивной двумерной CSS-сетке.

[cols="1h,1" grid=none, width=50%, frame=none]
|===
|XML-элемент
|`gridLayout`

|Java-класс
|`GridLayout`
|===

[[basics]]
== Основы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/grid-layout-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Добавьте дочерние компоненты декларативно и используйте `gap` и `columnMinWidth`, чтобы настроить интервалы и адаптивную ширину столбцов. Оба атрибута принимают CSS-величины длины и переменные.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/containers/gridlayout/simple/grid-layout-simple.xml[tags=basics]
----

[[data-binding]]
== Привязка к данным

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/grid-layout-dataaware" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Задайте `itemsContainer`, чтобы связать `gridLayout` с xref:data/data-containers.adoc[контейнером коллекции]. Контейнер создаёт по одному отображаемому компоненту для каждого элемента контейнера данных.

[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/containers/gridlayout/dataaware/grid-layout-dataaware.xml[tags=data-aware]
----

По умолчанию компонент отображает xref:data-model:entities.adoc#instance-name[имя экземпляра] сущности.

TIP: Вы можете переопределить отображение по умолчанию, настроив <<rendering-items,пользовательский рендерер>>.

[[enumeration-items]]
== Элементы перечисления

Компонент также поддерживает отображение значений перечисления с помощью атрибута `itemsEnum`.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/layout/gridlayout/grid-layout-view.xml[tags=itemsEnum]
----

[[rendering-items]]
[[programmatically]]
== Пользовательский рендерер элементов

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/grid-layout-renderer" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Используйте рендерер, чтобы заменить стандартную текстовую надпись элемента компонентом. В примере `gridLayout` связывается с контейнером коллекции в XML, а контроллер передаёт `ComponentRenderer` с помощью `@Supply`.

.XML
[source,xml,indent=0]
----
include::example$ui-samples/main/resources/io/jmix/uisamples/view/flowui/containers/gridlayout/renderer/grid-layout-renderer.xml[tags=renderer]
----

.Java
[source,java,indent=0]
----
include::example$ui-samples/main/java/io/jmix/uisamples/view/flowui/containers/gridlayout/renderer/GridLayoutRendererSample.java[tags=renderer]
----

[[fragment-renderer]]
== Рендерер фрагмента

Элементы также можно отображать с помощью вложенного элемента xref:vc/miscellaneous/renderers.adoc#fragment-renderer[fragmentRenderer].

. Создайте дескриптор фрагмента:
+
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/layout/gridlayout/card-fragment.xml[tags=fragment-descriptor]
----

. Создайте контроллер фрагмента.
+
Расширьте `FragmentRenderer`, указав корневой компонент фрагмента и отображаемую сущность как параметры типа:
+
.Показать код
[%collapsible]
====
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/layout/gridlayout/CardFragment.java[tags=cardFragment]
----
====

. Используйте `fragmentRenderer` для компонента `gridLayout`:
+
[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/layout/gridlayout/grid-layout-view.xml[tags=fragmentRenderer]
----

== Атрибуты

xref:vc/common-attributes.adoc[Общие атрибуты] имеют одинаковое назначение для всех компонентов. Следующие атрибуты настраивают `gridLayout` или его непосредственные дочерние элементы:

[cols="2,5,1", options="header"]
|===
|Имя
|Описание
|По умолчанию
|[[alignSelf]]alignSelf
|Задаётся у дочернего элемента и управляет его выравниванием внутри ячейки сетки по блочной оси (оси столбца). Соответствует CSS-свойству https://developer.mozilla.org/en-US/docs/Web/CSS/align-self[align-self^].
|`AUTO`
|[[columnMinWidth]]columnMinWidth
|Задает минимальную ширину для столбцов сетки в `gridLayout`. Это гарантирует, что столбцы не станут слишком узкими при изменении размера контейнера.
Значение должно быть допустимой CSS-величиной длины, например `"50px"` или `"10rem"`.
|`19rem`
|[[gap]]gap
|Задаёт интервалы между ячейками сетки по строкам и столбцам. Значение должно быть допустимой CSS-величиной длины, например `"10px"` или `"1rem"`.
|`0.5rem`
|[[justifySelf]]justifySelf
|Задаётся у дочернего элемента и управляет его выравниванием внутри ячейки сетки по строчной оси (оси строки). Соответствует CSS-свойству https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/justify-self[justify-self^].
|`AUTO`
|===

== Обработчики

xref:vc/common-handlers.adoc[Общие обработчики] настраиваются одинаково для всех компонентов.

Следующие обработчики специфичны для `gridLayout`.

[cols="2,5", options="header"]
|===
|Имя
|Описание
|[[itemLabelGenerator]]itemLabelGenerator
|Настраивает текст, который создаёт стандартный рендерер элементов.
|[[renderer]]renderer
|Задаёт рендерер, который создаёт компонент для каждого элемента. См. <<rendering-items,Пользовательский рендерер элементов>>.
|===

== Элементы

`gridLayout` без привязки к данным может содержать компоненты напрямую. Контейнер с привязкой к данным может содержать xref:vc/miscellaneous/renderers.adoc#fragment-renderer[`fragmentRenderer`], который создаёт компонент для каждого элемента.
