= initialLayout

`initialLayout` отображает содержимое по умолчанию в xref:flow-ui:views/view-classes.adoc#standard-main-view[главном экране], когда другие экраны не открыты.

[cols="1h,1" grid=none, width=50%, frame=none]
|===
|XML-элемент
|`initialLayout`

|Java-класс
|`VerticalLayout`
|===

[[basics]]
== Основы

`initialLayout` — вложенный элемент компонента `appLayout`.

Пример определения `initialLayout` в `main-view.xml`:

[source,xml,indent=0]
----
<mainView xmlns="http://jmix.io/schema/flowui/main-view"
          title="msg://MainView.title">
    <appLayout>
        <navigationBar .../>
        <drawerLayout .../>
        <initialLayout>
            <image id="urlImage"
                   resource="https://www.jmix.io/uploads/framework_image_9efadbc372.svg"
                   width="100%"
                   height="100%"/>
        </initialLayout>
    </appLayout>
</mainView>
----

В XML корневой элемент `initialLayout` загружается как xref:vc/layouts/vbox.adoc[`VerticalLayout`].

Также исходный контейнер можно получить или заменить с помощью Java API `StandardMainView`:

* `getInitialLayout()` возвращает корневой компонент исходного контейнера.
* `setInitialLayout()` заменяет компонент исходного контейнера.

Компоненты внутри `initialLayout` могут быть инжектированы в `MainView`, например:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/main/MainView.java[tags=initialLayout;!init-onBoardingStatus;!get-menu-item;!new-menu-item]
----

== Атрибуты

`initialLayout` поддерживает xref:vc/common-attributes.adoc[общие атрибуты компонентов] и атрибуты контейнера, описанные для xref:vc/layouts/vbox.adoc[`vbox`].

[[handlers]]
== Обработчики

[cols="2,5", options="header"]
|===
|Имя
|Описание

|xref:vc/common-handlers.adoc#AttachEvent[`AttachEvent`]
|Срабатывает при присоединении контейнера к UI.

|xref:vc/layouts/vbox.adoc#ClickEvent[`ClickEvent`]
|Срабатывает при нажатии на контейнер.

|xref:vc/common-handlers.adoc#DetachEvent[`DetachEvent`]
|Срабатывает при отсоединении контейнера от UI.
|===

== Элементы

`initialLayout` может содержать компоненты и контейнеры, которые отображаются как исходное содержимое главного экрана.
