= initialLayout

`initialLayout` displays default content in the xref:flow-ui:views/view-classes.adoc#standard-main-view[main view] when no other view is open.

[cols="1h,1" grid=none, width=50%, frame=none]
|===
|XML Element
|`initialLayout`

|Java Class
|`VerticalLayout`
|===

[[basics]]
== Basics

`initialLayout` is a nested element of the `appLayout` component.

An example of defining `initialLayout` in `main-view.xml`:

[source,xml,indent=0]
----
<mainView xmlns="http://jmix.io/schema/flowui/main-view"
          title="msg://MainView.title">
    <appLayout>
        <navigationBar .../>
        <drawerLayout .../>
        <initialLayout>
            <image id="urlImage"
                   resource="https://www.jmix.io/uploads/framework_image_9efadbc372.svg"
                   width="100%"
                   height="100%"/>
        </initialLayout>
    </appLayout>
</mainView>
----

In XML, the root `initialLayout` element is loaded as a xref:vc/layouts/vbox.adoc[`VerticalLayout`].

Alternatively, use the `StandardMainView` Java API to access or replace the initial layout:

* `getInitialLayout()` returns the root component of the initial layout.
* `setInitialLayout()` replaces the initial layout component.

Components inside `initialLayout` can be injected into the `MainView`, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/main/MainView.java[tags=initialLayout;!init-onBoardingStatus;!get-menu-item;!new-menu-item]
----

== Attributes

`initialLayout` supports xref:vc/common-attributes.adoc[common component attributes] and the layout attributes documented for xref:vc/layouts/vbox.adoc[`vbox`].

[[handlers]]
== Handlers

[cols="2,5", options="header"]
|===
|Name
|Description

|xref:vc/common-handlers.adoc#AttachEvent[`AttachEvent`]
|Fires when the layout is attached to the UI.

|xref:vc/layouts/vbox.adoc#ClickEvent[`ClickEvent`]
|Fires when the layout is clicked.

|xref:vc/common-handlers.adoc#DetachEvent[`DetachEvent`]
|Fires when the layout is detached from the UI.
|===

== Elements

`initialLayout` can contain components and layouts displayed as the main view's initial content.
