= initialLayout

The `initialLayout` component is a layout that will be displayed when no views are opened in the xref:flow-ui:views.adoc#standard-main-view[main view]. This component can be useful when you need to show some default content, such as a logo or dashboard, before any other views are opened.

* XML element: `initialLayout`

== Basics

`initialLayout` is a nested element of the `appLayout` component.

TIP: To add a nested `initialLayout` element in Jmix Studio, select the `appLayout` element in the main view descriptor XML or in the *Jmix UI* structure panel and click on the xref:studio:screen-designer.adoc#component-inspector-add-button[Add]*->InitialLayout* button in the *Jmix UI* inspector panel.

An example of defining `initialLayout` in `main-view.xml`:

[source,xml,indent=0]
----
<mainView xmlns="http://jmix.io/schema/flowui/main-view"
          title="msg://MainView.title">
    <appLayout>
        <navigationBar .../>
        <drawerLayout .../>
        <initialLayout>
            <image id="urlImage"
                   resource="https://www.jmix.io/uploads/framework_image_9efadbc372.svg"
                   width="100%"
                   height="100%"/>
        </initialLayout>
    </appLayout>
</mainView>
----

When added in XML, the root `<initialLayout>` element effectively is xref:vc/layouts/vbox.adoc[VerticalLayout].

Alternatively, the `StandardMainView` Java API can be used to set/get the initial layout:

* `getInitialLayout()` - returns the root component of the initial layout.
* `setInitialLayout()` - sets a component that will be the initial layout.

Components inside `initialLayout` can be injected into the `MainView`, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/main/MainView.java[tags=initialLayout;!init-onBoardingStatus]
----

== Attributes

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignItems[alignItems] -
xref:vc/layouts/vbox.adoc#boxSizing[boxSizing] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/layouts/vbox.adoc#expand[expand] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/layouts/vbox.adoc#justifyContent[justifyContent] -
xref:vc/layouts/vbox.adoc#margin[margin] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/layouts/vbox.adoc#padding[padding] -
xref:vc/layouts/vbox.adoc#spacing[spacing] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#width[width]

[[handlers]]
== Handlers

include::../handler-generation-tip.adoc[]

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/layouts/vbox.adoc#ClickEvent[ClickEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]