= initialLayout 初始布局

`initialLayout` 组件是在 xref:flow-ui:views/views.adoc#standard-main-view[主视图] 中还没有打开任何视图时显示的布局。如果需要在打开其他视图之前显示某些默认内容（如 logo 或仪表板）时，可以使用该组件。

* XML 元素：`initialLayout`

== 基本用法

`initialLayout` 是 `appLayout` 的内部组件。

TIP: 如需通过 Jmix Studio 添加内部的 `initialLayout` 元素，请在 XML 或 *Jmix UI* 层级面板中选择 `appLayout` 元素，并在属性面板点击 xref:studio:view-designer.adoc#component-inspector-add-button[Add]*->InitialLayout* 按钮。

在 `main-view.xml` 中定义 `initialLayout` 的示例：

[source,xml,indent=0]
----
<mainView xmlns="http://jmix.io/schema/flowui/main-view"
          title="msg://MainView.title">
    <appLayout>
        <navigationBar .../>
        <drawerLayout .../>
        <initialLayout>
            <image id="urlImage"
                   resource="https://www.jmix.io/uploads/framework_image_9efadbc372.svg"
                   width="100%"
                   height="100%"/>
        </initialLayout>
    </appLayout>
</mainView>
----

添加到 XML 之后，`<initialLayout>` 元素其实是 xref:vc/layouts/vbox.adoc[VerticalLayout]。

`StandardMainView` Java API 也可以用来设置/获取初始布局：

* `getInitialLayout()` - 返回初始布局的根组件。
* `setInitialLayout()` - 设置初始布局的组件。

`initialLayout` 中的组件可以在 `MainView` 中注入，示例：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/main/MainView.java[tags=initialLayout;!init-onBoardingStatus]
----

== XML 属性

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignItems[alignItems] -
xref:vc/layouts/vbox.adoc#boxSizing[boxSizing] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/layouts/vbox.adoc#expand[expand] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/layouts/vbox.adoc#justifyContent[justifyContent] -
xref:vc/layouts/vbox.adoc#margin[margin] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/layouts/vbox.adoc#padding[padding] -
xref:vc/layouts/vbox.adoc#spacing[spacing] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#width[width]

[[handlers]]
== 事件和处理器

include::../handler-generation-tip.adoc[]

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/layouts/vbox.adoc#ClickEvent[ClickEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]
