= UI Constraints

The *UI Constants* add-on allows you to control the visibility and accessibility of UI components using resource roles.

For instance, you can define that if a user has the `Manager` role, the `orderDateField` field in the order details view should be read-only and the `orderStatusField` field should be hidden.

[[installation]]
== Installation

[NOTE]
====
This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial] section for how to get a trial version.
====

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.uiconstraints:jmix-uiconstraints-starter'
----

[[ui-component-policy-annotation]]
== UiComponentPolicy Annotation

Like any other resource policy type, UI component policies should be defined in resource roles. This is done using the `@UiComponentPolicy` annotation.

[source,java,indent=0]
----
include::example$uiconstraints-ex1/src/main/java/com/company/demo/security/UiConstraintsSampleRole.java[tags=role]
----

[[ui-component-policy-annotation-attributes]]
=== UiComponentPolicy Annotation Attributes

[[view-class-and-view-id]]
==== viewClass and viewId

For each UI component, you must define a view. A view can be defined in two ways: either by its class (via the `viewClass` attribute), or by its ID (via the `id` attribute).

[[component-ids]]
==== componentIds

Each `@UiComponentPolicy` annotation can define policies for one or more UI components. Their ID must be listed in the `componentIds` attribute. A policy can be applied to the following UI component types:

* UI component (field, button, etc.) that belongs to a given view. Examples: `firstNameField`, `importButton`.
* Action that belongs to a given view. Example: `save`.
* Action that belongs to UI component. Example: `userGrid.edit`.
* Component or action located inside the fragment. Example: `addressFragment.cityField`.

[[action]]
==== action

UI component policy supports two types of actions:

* *VISIBLE* - manages the visibility of the component.
* *ENABLED* - manages accessibility of the component. If the component can be made read-only, it will be set to read-only. Otherwise, it will be disabled.

[[effect]]
==== effect

The effect attribute can have two values: *ALLOW* and *DENY*.

In most cases the *DENY* effect will be used. By default, if no roles are applied, all UI components in the view will be visible and accessible. Unlike other resource policy types (for example, entity attribute policies), UI component policies will revoke permissions rather than grant them.

The *ALLOW* effect can be used if you need to override the effect of another policy that has been applied to the same component by a different role. For example, if a user has already been assigned the role A and this role prevents access to a certain UI component, using the role B with the *ALLOW* effect will grant access to that component.