## Execute 'authenticate.http' first to get have a valid access token for the API

# Get current permissions

GET {{baseRestUrl}}
         /permissions
         ?entities=true&entityAttributes=true
Authorization: Bearer {{access_token}}
