## Execute 'authenticate.http' first to get have a valid access token for the API

# Get current permissions

GET {{baseRestUrl}}
         /userInfo
Authorization: Bearer {{access_token}}

> {%
    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });

    client.test("username is admin", function() {
      client.assert(
          response.body.username === "admin"
      );
    });

  %}