## Execute 'authenticate.http' first to get have a valid access token for the API

POST {{baseRestUrl}}
         /entities
         /rstex11_Product?responseFetchPlan=_local
Authorization: Bearer {{access_token}}

{
  "name": "Product with Image",
  "price":100,
  "image": "fs://2021/03/13/f623e8ab-524e-51ed-1a9f-b1c1369239e3.jpg?name=cat.jpg"
}

> {%

    client.test("Response Code is 201", function() {
      client.assert(
          response.status === 201,
          "Response status is not 201 - Created"
      );
    });

    client.test("new Entity is returned", function() {
      client.assert(
          response.body["id"],
          "ID Attribute of an Entity is not returned"
      );
    });
  %}

###