= Create Index Definitions

In the Jmix application, we need to create an Index Definition - interface that describes what entity and what properties should be indexed. The interface definition should meet the following criteria:

* Java interface with any name
* Must be annotated with `@JmixEntitySearchIndex` annotation.
* Annotation has mandatory parameter `entity` - java class of entity this Index Definition is created for (one Index Definition per one searchable entity)

[source,java]
----
@JmixEntitySearchIndex(entity = Order.class)
public interface OrderIndexDefinition {
}
----

After that, we need to define entity properties that should be indexed. For that purpose, we need to create at least one method within the previously created Index Definition.

These methods should be:

* void
* with any name
* without parameters
* without implementation
* annotated with at least one Mapping annotation

Currently, only one Mapping annotation is available - `@AutoMappedField`. It automatically maps requested properties the common way depending on their data type.

[source,java]
----
@JmixEntitySearchIndex(entity = Order.class)
public interface OrderIndexDefinition {
	@AutoMappedField(includeProperties = {"name", "description", "customer.name"})
	void orderMapping();
}
----