= Indexing API

If you want to index/delete entity instances directly (without enqueuing event) you should use methods of `EntityIndexer`:

* `index(Object entityInstance)`
Stores provided entity instance to index
* `indexCollection(Collection<Object> entityInstances)`
Stores provided entity instances to index
* `indexByEntityId(Id entityId)`
Stores entity instance to index by provided ID
* `indexCollectionByEntityIds(Collection<Id> entityIds)`
Stores entity instances to index by provided IDs
* `delete(Object entityInstance)`
Deletes provided entity instance from index
* `deleteCollection(Collection<Object> entityInstances)`
Deletes provided entity instances from index
* `deleteByEntityId(Id entityId)`
Deletes entity instance from the index by provided ID
* `deleteCollectionByEntityIds(Collection<Id> entityIds)`
Deletes entity instances from index by provided IDs

If you want to enqueue instances to be indexed/deleted you should use methods of `IndexingQueueManager`:

* `enqueueIndex(Object entityInstance)`
Enqueues index event for provided entity instance
* `enqueueIndexCollection(Collection<Object> entityInstances)`
Enqueues index events for provided entity instances
* `enqueueIndexByEntityId(Id entityId)`
Enqueues index event for provided entity ID
* `enqueueIndexCollectionByEntityIds(Collection<Id> entityIds)`
Enqueues index events for provided entity IDs
* `enqueueIndexAll()`
Enqueues index events for all instances of all entities configured for indexing
* `enqueueIndexAll(String entityName)`
Enqueues index events for all instances of a provided entity. This entity should be previously configured for indexing
* `enqueueDelete(Object entityInstance)`
Enqueues delete event for provided entity instance
* `enqueueDeleteCollection(Collection<Object> entityInstances)`
Enqueues delete events for provided entity instances
* `enqueueDeleteByEntityId(Id entityId)`
Enqueues delete event for provided entity ID
* `enqueueDeleteCollectionByEntityIds(Collection<Id> entityIds)`
Enqueues delete events for provided entity IDs
* `emptyQueue(String entityName)`
Removes all queue items related to provided entity from Indexing Queue
* `processNextBatch()`
Retrieves next batch of items from indexing queue and processes them
* `processNextBatch(int batchSize)`
Retrieves next batch (with size equals to `batchSize`) of items from indexing queue and processes them
* `processEntireQueue()`
Retrieves all items from indexing queue and processes them