= 索引队列

在应用程序中添加了搜索扩展组件后，会开始自动 xref:config-options.adoc#tracking-changes[跟踪实体的修改]。本章节我们介绍如何设置使用新数据自动更新 ES 索引。

跟踪修改的机制会在 `SEARCH_INDEXING_QUEUE` 数据库表保存对修改后实体操作的队列。`IndexingQueueManager` bean 包含处理队列的方法，并将修改的数据发送至 ES。

NOTE: 应设置索引队列的定期处理机制，否则搜索将返回过时的数据。

可以按照下面的介绍使用 Quartz 任务调度定期处理队列。

[[default-quartz-configuration]]
== 默认 Quartz 配置

搜索扩展组件提供 Quartz 任务的默认配置，用于定期处理索引队列。按下列步骤使用：

. 按照 Quartz 章节的说明在项目中安装 xref:quartz:index.adoc#installation[安装] 扩展组件。

. 视情况修改 CRON 表达式。默认值为 `0/5 * * * * ?`（5 秒一次）。
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=cron]
----

默认配置创建并设置 id 为 `IndexingQueueProcessing` 的调度计划。

[[custom-qurtz-configuration]]
== 自定义 Quartz 配置

如需使用自定义 Quartz 配置，请按照下列步骤：

. 按照 Quartz 章节的说明在项目中安装 xref:quartz:index.adoc#installation[安装] 扩展组件。

. 在 `application.properties` 文件添加下列应用程序属性禁用默认配置：
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=not-default]
----

. 创建自定义任务类，调用 `IndexingQueueManager.processNextBatch()`：
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/search/ex1/service/MyCustomQueueProcessingJob.java[tags=custom-job]
----

. 启动程序后，打开 *Administration（管理） -> Quartz jobs（Quartz 任务）* 界面，为 `MyCustomQueueProcessingJob` 类配置调度任务。

. 或者，如需在开发阶段配置调度任务，可以在主程序类中注册下列 bean：
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/search/ex1/SampleSearchApplication.java[tags=beans]
----

//Value of the property `jmix.search.indexingQueueProcessingCron` can be found in `io.jmix.search.SearchProperties` class.
