= Search

The Search add-on provides full-text search functionality for your application.
It allows you to configure indexing of entities and uploaded files, as well as providing API and UI components for searching the indexed data. The search results are filtered based on the xref:security:index.adoc[data access] permissions of the current user.

The add-on utilizes https://www.elastic.co[Elasticsearch^] as its search engine. For more information about the internal search and indexing mechanisms, please refer to the Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[documentation^].

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency]
----

[[connecting-to-elasticsearch-service]]
== Connecting to Elasticsearch Service

To connect to the Elasticsearch service, specify the following properties in the `application.properties` file:

* `jmix.search.elasticsearch.url` - the complete URL of the Elasticsearch service.
* `jmix.search.elasticsearch.login` - the Elasticsearch login for basic authentication.
* `jmix.search.elasticsearch.password` - the user password used to connect to the Elasticsearch service.

By default, the Search add-on is configured for Elasticsearch version 7.11 and higher. If you intend to utilize a version prior to 7.11, you can disable compatibility mode by setting the xref:search-properties.adoc#jmix.search.restHighLevelClientApiCompatibilityModeEnabled[jmix.search.restHighLevelClientApiCompatibilityModeEnabled] application property to `false`.

CAUTION: Note that the Search add-on is not currently compatible with the Elasticsearch service offered by AWS.

// In case you use a local service, you may not specify the properties above.

//[[using-amazon-web-services]]
//=== Using Amazon Web Services
//
//To connect to Elasticsearch deployed in AWS with IAM authentication, add the following properties to your `application.properties` file:
//
//* `jmix.search.elasticsearch.url` - a full URL of Elasticsearch service.
//* `jmix.search.elasticsearch.aws.region` - AWS region, for example, 'eu-central-1'.
//* `jmix.search.elasticsearch.aws.accessKey` - an access key of the target IAM user.
//* `jmix.search.elasticsearch.aws.secretKey` - a secret key of the target IAM user.
