= 搜索

搜索扩展组件为应用程序提供全文搜索的功能。支持配置实体和上传文件的索引，并提供对索引数据进行搜索的 API 和 UI 控制组件。搜索结果会根据当前用户的 xref:security:index.adoc[数据访问] 权限进行过滤。

该扩展组件使用 https://www.elastic.co[Elasticsearch（ES）^] 作为搜索引擎。关于搜索的内部原理和索引构建的更多信息请参阅 Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[文档^]。

[[installation]]
== 安装

按照 xref:ROOT:add-ons.adoc#installation[扩展组件] 章节的说明通过 Jmix 市场进行自动安装。

手动安装，在 `build.gradle` 添加下列依赖：

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----

[[connecting-to-elasticsearch-service]]
== 连接至 ES 服务

// [[using-elasticsearch-cluster]]
// === 使用 ES 集群

如需连接至 ES 服务，需要在 `application.properties` 文件中指定下列属性：

* `jmix.search.elasticsearch.url` - ES 集群的完整 URL。
* `jmix.search.elasticsearch.login` - 连接至 ES 集群的用户名。
* `jmix.search.elasticsearch.password` - 连接至 ES 集群的密码。

默认情况下，搜索扩展组件使用的 ES 为 7.11 及以上版本。如需使用 7.11 以下的版本，设置 xref:search-properties.adoc#jmix.search.rest-high-level-client-api-compatibility-mode-enabled[jmix.search.rest-high-level-client-api-compatibility-mode-enabled] 应用程序属性为 `false`。

CAUTION: 注意，搜索扩展组件目前不支持 AWS 提供的 ES 服务。

// In case you use a local service, you may not specify the properties above.

//[[using-amazon-web-services]]
//=== 使用 AWS
//
//如需连接部署在 AWS 中使用 IAM 认证的 ES 服务，在 `application.properties` 文件中添加下列属性：
//
//* `jmix.search.elasticsearch.url` - ES 服务的完整 URL。
//* `jmix.search.elasticsearch.aws.region` - AWS 区域，例如，'eu-central-1'。
//* `jmix.search.elasticsearch.aws.accessKey` - IAM 用户的 access key。
//* `jmix.search.elasticsearch.aws.secretKey` - IAM 用户的 secret key。
