= Search

This add-on allows you to enable full-text search capabilities in your application with https://www.elastic.co[Elasticsearch^].

Jmix uses Elasticsearch as a base for its search engine. In Jmix, if we need to search data, basically, entities, we need to build indexes for them. More information about search internals and indexing can be found in https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[Elasticsearch documentation^].

[[installation]]
== Installation

To include Search in your application, follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section.

[[connecting-to-elasticsearch-service]]
== Connecting to Elasticsearch Service

[[using-elasticsearch-cluster]]
=== Using Elasticsearch Cluster

To connect to the Elasticsearch service, you need to specify the following properties in the `application.properties` file:

* `jmix.search.elasticsearch.url` - a full URL of the Elasticsearch cluster.
* `jmix.search.elasticsearch.login` - a user login to connect to the Elasticsearch cluster.
* `jmix.search.elasticsearch.password` - a user password to connect to the Elasticsearch cluster.

// In case you use a local service, you may not specify the properties above.

[[using-amazon-web-services]]
=== Using Amazon Web Services

To connect to Elasticsearch deployed in AWS with IAM authentication, add the following properties to your `application.properties` file:

* `jmix.search.elasticsearch.url` - a full URL of Elasticsearch service.
* `jmix.search.elasticsearch.aws.region` - AWS region, for example, 'eu-central-1'.
* `jmix.search.elasticsearch.aws.accessKey` - an access key of the target IAM user.
* `jmix.search.elasticsearch.aws.secretKey` - a secret key of the target IAM user.

[[updating-index-data]]
== Updating Index Data

Jmix application tracks data changes but does not pass them to Elasticsearch automatically. Please refer to section xref:search:indexing-queue-processing.adoc[Indexing Queue Processing] to set up the automatic update. You should do it to make data available for the search engine. Otherwise, your data will not appear in search results.