= Indexing Queue Processing

`IndexingQueue` is a table in the database that stores `IndexingQueue` events.  Every `IndexingQueue` event represents one action on one entity instance: `index` or `delete`.

NOTE: By default, events are not passed to the Elasticsearch engine. To make data appear in Elasticsearch and be available to search, enable event processing explicitly. 

You can use the default configuration of https://www.quartz-scheduler.org[Quartz Job Scheduler^] or create your own.

[[adding-default-quartz-configuration]]
== Adding Default Quartz Configuration

The Search add-on provides the default configuration of https://www.quartz-scheduler.org[Quartz Job Scheduler^]. To process events stored in `IndexingQueue` on a regular basis, do the following:

. Add the line to the `dependencies` section of the `build.gradle` file:
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=quartz]
----
+
. Add the following properties to the `application.properties` file:
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=quartz-properties]
----
+
. Change scheduling as CRON expression if necessary. The default value is `0/5 * * * *` (every 5 seconds).
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=cron]
----

If you use PostgreSQL and get the `org.quartz.JobPersistenceException: Couldn’t retrieve job: Bad value for type long` exception on application start, set the following property:

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=postgres]
----

Default configuration creates and schedules a job with the `IndexingQueueProcessing` identity.

[[creating-custom-qurtz-configuration]]
== Creating Custom Quartz Configuration

If custom Quartz configuration should be used instead of the default one, in addition to the previous steps, do the following:

. Set up the default Quartz Configuration according to the <<adding-default-quartz-configuration, previous>> section.
. Add the following property to the `application.properties` file to disable default configuration:
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=not-default]
----
+
. Create custom job class that invokes `IndexingQueueManager.processNextBatch()`. This method is responsible for sending events to Elasticsearch:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/search/ex1/service/MyCustomQueueProcessingJob.java[tags=custom-job]
----
+
. Register the following beans in the application:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/search/ex1/SampleSearchApplication.java[tags=beans]
----

//Value of the property `jmix.search.indexingQueueProcessingCron` can be found in `io.jmix.search.SearchProperties` class.