= Search

The Search add-on enables full-text search capabilities in your application.
It allows you to set up indexing of entities and uploaded files and provides API and UI controls for searching through the indexed data. Search results are filtered according to the xref:security:index.adoc[data access] permissions of the current user.

The add-on uses https://www.elastic.co[Elasticsearch^] as its search engine. More information about search internals and indexing can be found in Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[documentation^].

[[installation]]
== Installation

To include Search in your application, follow the instructions in the xref:ROOT:add-ons.adoc[Add-ons] section.

[[connecting-to-elasticsearch-service]]
== Connecting to Elasticsearch Service

[[using-elasticsearch-cluster]]
=== Using Elasticsearch Cluster

To connect to the Elasticsearch service, you need to specify the following properties in the `application.properties` file:

* `jmix.search.elasticsearch.url` - a full URL of the Elasticsearch cluster.
* `jmix.search.elasticsearch.login` - a user login to connect to the Elasticsearch cluster.
* `jmix.search.elasticsearch.password` - a user password to connect to the Elasticsearch cluster.

// In case you use a local service, you may not specify the properties above.

[[using-amazon-web-services]]
=== Using Amazon Web Services

To connect to Elasticsearch deployed in AWS with IAM authentication, add the following properties to your `application.properties` file:

* `jmix.search.elasticsearch.url` - a full URL of Elasticsearch service.
* `jmix.search.elasticsearch.aws.region` - AWS region, for example, 'eu-central-1'.
* `jmix.search.elasticsearch.aws.accessKey` - an access key of the target IAM user.
* `jmix.search.elasticsearch.aws.secretKey` - a secret key of the target IAM user.
