= Search UI Component - Fine Tuning

SearchField supports different search strategies - the way of input text handling:

* `anyTermAnyField` - document matches if it contains at least one of input words in any indexed field
* `allTermsAnyField` - document matches if it contains all input words in any field in any order
* `allTermsSingleField` - document matches if it has at least one field that contains all input words in any order
* `phrase` - document matches if it has at least one field that contains all input words in the provided order

You can set the proper strategy by using `strategy` attribute:

[source,xml]
----
<search:searchField id="mySearchField" strategy="allTermsAnyField"/>
----

The default search strategy is `anyTermAnyField`. It can be overridden by adding the following property to your `application.properties` file

[source,properties]
----
jmix.search.defaultSearchStrategy=phrase
----

You can configure SearchField to search within specific entities - specify name of required entity as value of `entities` attribute. Multiple entities can be specified as a comma-separated list:

[source,xml]
----
<search:searchField id="mySearchField" entities="myproject_Order,myproject_Customer"/>
----

You can create your own search strategy. For that purpose you need to create new bean extends `io.jmix.search.searching.SearchStrategy` class and implements two methods:

* `String getName()`

Should return unique strategy name.

* `void configureRequest(SearchRequest searchRequest, SearchContext searchContext)`

Should configure incoming `SearchRequest` the proper way.

After that, you can set your strategy to the `SearchField` component by the strategy name.