= Searching API

If you want to search entities in the index you should use methods of `EntitySearcher`:

* `search(SearchContext searchContext, SearchStrategy searchStrategy)`
Performs search in search indices according to provided `SearchContext` and `SearchStrategy`.
Returns `SearchResult` object contains result data
* `SearchContext` - describes the main settings of the current search:
* `searchText` - the text you want to search
* `size` - the max amount of documents that should be found
* `offset` - the amount of documents that should be skipped
* `entities` - a collection of entity names that should be found. If none is specified search will be performed within all indexed entities
* `SearchStrategy` - describes the way of `searchText` processing
* `search(SearchContext searchContext)`
Similar to previous but uses default `SearchStrategy`.
* `searchNextPage(SearchResult previousSearchResult)`
Performs a search for the next page based on `SearchResult` of the previous search request. Returns its own `SearchResult` that can be used for the next invocation.

`SearchResult` contains details of found instances and matched fields.

Also, you can use it to load a collection of related entity instances. For that purpose, you should use methods of `SearchResultProcessor:`

`loadEntityInstances(SearchResult searchResult)`

`loadEntityInstances(SearchResult searchResult, Map<String, FetchPlan> fetchPlans)`