= Search Properties

[[jmix.search.changed-entities-indexing-enabled]]
== jmix.search.changed-entities-indexing-enabled

Defines whether automatic indexing of xref:config-options.adoc#tracking-changes[changed entities] is enabled.

Default value: `true`

[[jmix.search.default-search-strategy]]
== jmix.search.default-search-strategy

Name of default xref:search-in-ui.adoc#search-strategies[search strategy].

Default value: `anyTermAnyField`

[[jmix.search.enqueue-index-all-on-startup-index-recreation-enabled]]
== jmix.search.enqueue-index-all-on-startup-index-recreation-enabled

Defines whether all entity instances related to indexes created or recreated on startup should be enqueued automatically. See also xref:config-options.adoc#existing-data-indexing[Existing Data Indexing].

Default value: `true`

[[jmix.search.enqueue-index-all-on-startup-index-recreation-entities]]
== jmix.search.enqueue-index-all-on-startup-index-recreation-entities

Defines the list of entities that should be automatically enqueued on startup in case of index recreation. Empty list means all indexed entities. See also xref:config-options.adoc#existing-data-indexing[Existing Data Indexing].

Default value: ``

[[jmix.search.enqueueing-session-processing-cron]]
== jmix.search.enqueueing-session-processing-cron

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] that is used by default Enqueueing Session processing Quartz xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration].

Default value: `0/5 * * * * ?`

[[jmix.search.indexing-queue-processing-cron]]
== jmix.search.indexing-queue-processing-cron

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] that is used by default Indexing Queue processing Quartz xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration].

Default value: `0/5 * * * * ?`

[[jmix.search.index-schema-management-strategy]]
== jmix.search.index-schema-management-strategy

The way of index schema synchronization. See xref:config-options.adoc#indexes-creation[Index Creation] for more detail.

Default value: `create-or-recreate`

[[jmix.search.max-search-page-count]]
== jmix.search.max-search-page-count

Sets the max amount of result pages.

Default value: `100`

[[jmix.search.process-queue-batch-size]]
== jmix.search.process-queue-batch-size

Sets the amount of queue items processed in single batch.

Default value: `100`

[[jmix.search.reindex-entity-enqueue-batch-size]]
== jmix.search.reindex-entity-enqueue-batch-size

Sets the amount of entity instances enqueued in single batch during entity reindex process.

Default value: `100`

[[jmix.search.rest-high-level-client-api-compatibility-mode-enabled]]
== jmix.search.rest-high-level-client-api-compatibility-mode-enabled

If `true`, the add-on is compatible with Elasticsearch 7.11 and above. If you need to use a version below 7.11, set this property to `false`.

Default value: `true`

[[jmix.search.search-index-name-prefix]]
== jmix.search.search-index-name-prefix

Prefix for search index name. Index naming template: <prefix><entity_name>. See xref:getting-started.adoc#configure_index_naming[Configure Index Naming].

Default value: `search_index_`

[[jmix.search.search-reload-entities-batch-size]]
== jmix.search.search-reload-entities-batch-size

Defines the batch size for post-search entity processing, for example, when results are filtered after search due to the row-level security policies, or when entities are fetched from search results with their fetch plans. See xref:search-api.adoc#security-and-pagination[Access Control and Pagination].

Default value: `100`

[[jmix.search.search-result-page-size]]
== jmix.search.search-result-page-size

Sets the max amount of objects displayed on single page of search result.

Default value: `100`

[[jmix.search.use-default-enqueueing-session-processing-quartz-configuration]]
== jmix.search.use-default-enqueueing-session-processing-quartz-configuration

Defines whether the default Enqueueing Session processing Quartz  xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration] is used.

Default value: `true`

[[jmix.search.use-default-indexing-queue-processing-quartz-configuration]]
== jmix.search.use-default-indexing-queue-processing-quartz-configuration

Defines whether the default Indexing Queue processing Quartz  xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration] is used.

Default value: `true`











