= 配置

[[jmix.search.changedEntitiesIndexingEnabled]]
== jmix.search.changedEntitiesIndexingEnabled

定义是否启用对 xref:config-options.adoc#tracking-changes[变更实体] 的自动索引。

默认值：`true`

[[jmix.search.defaultSearchStrategy]]
== jmix.search.defaultSearchStrategy

默认 xref:search-in-ui.adoc#search-strategies[搜索策略] 的名称。

默认值：`anyTermAnyField`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled]]
== jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled

定义是否自动将启动时创建或重建索引的所有实体实例都添加至队列中。参考 xref:config-options.adoc#existing-data-indexing[已有数据索引]。

默认值：`true`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities]]
== jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities

定义在应用程序启动重建索引时需要自动添加到队列中的实体列表。空列表表示全部索引实体。参考 xref:config-options.adoc#existing-data-indexing[已有数据索引]。

默认值：``

[[jmix.search.enqueueingSessionProcessingCron]]
== jmix.search.enqueueingSessionProcessingCron

默认队列会话（Enqueueing Session）处理 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置] 使用的 http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron 表达式^]。

默认值：`0/5 * * * * ?`

[[jmix.search.indexingQueueProcessingCron]]
== jmix.search.indexingQueueProcessingCron

默认索引队列（Indexing Queue）处理 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置] 使用的 http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron 表达式^]。

默认值：`0/5 * * * * ?`

[[jmix.search.indexSchemaManagementStrategy]]
== jmix.search.indexSchemaManagementStrategy

索引结构的同步方式。参阅 xref:config-options.adoc#indexes-creation[索引创建] 了解细节。

默认值：`create-or-recreate`

[[jmix.search.maxSearchPageCount]]
== jmix.search.maxSearchPageCount

设置结果页面的最大数量。

默认值：`100`

[[jmix.search.processQueueBatchSize]]
== jmix.search.processQueueBatchSize

设置每组（batch）中能处理的队列项数量。

默认值：`100`

[[jmix.search.reindexEntityEnqueueBatchSize]]
== jmix.search.reindexEntityEnqueueBatchSize

设置在实体索引重建过程中每个队列组中实体的数量。

默认值：`100`

[[jmix.search.restHighLevelClientApiCompatibilityModeEnabled]]
== jmix.search.restHighLevelClientApiCompatibilityModeEnabled

如果为 `true`，则扩展组件兼容 ES 7.11 及以上版本。如需使用 7.11 以下版本，设置为 `false`。

默认值：`true`

[[jmix.search.searchIndexNamePrefix]]
== jmix.search.searchIndexNamePrefix

索引名称前缀。索引名格式为 `<prefix><entity_name>`。参阅 xref:getting-started.adoc#configure-index-naming[配置索引名]。

默认值：`search_index_`

[[jmix.search.searchReloadEntitiesBatchSize]]
== jmix.search.searchReloadEntitiesBatchSize

定义搜索完成后处理实体的每组（batch）中实体的数量，例如，当搜索接续需要按照行级策略做过滤时，或者当实体从搜索结果中使用 fetch plan 获取时。参阅 See xref:search-api.adoc#security-and-pagination[访问控制和分页]。

默认值：`100`

[[jmix.search.searchResultPageSize]]
== jmix.search.searchResultPageSize

定义搜索结果每页展示对象的最大数量。

默认值：`100`

[[jmix.search.useDefaultEnqueueingSessionProcessingQuartzConfiguration]]
== jmix.search.useDefaultEnqueueingSessionProcessingQuartzConfiguration

定义是否使用默认队列会话（Enqueueing Session）处理的 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置]。

默认值：`true`

[[jmix.search.useDefaultIndexingQueueProcessingQuartzConfiguration]]
== jmix.search.useDefaultIndexingQueueProcessingQuartzConfiguration

定义是否使用默认索引队列（Indexing Queue）处理的 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置]。

默认值：`true`











