= Search Properties

[[jmix.search.changedEntitiesIndexingEnabled]]
== jmix.search.changedEntitiesIndexingEnabled

Defines whether automatic indexing of xref:config-options.adoc#tracking-changes[changed entities] is enabled.

Default value: `true`

[[jmix.search.defaultSearchStrategy]]
== jmix.search.defaultSearchStrategy

Name of default xref:search-in-ui.adoc#search-strategies[search strategy].

Default value: `anyTermAnyField`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled]]
== jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled

Defines whether all entity instances related to indexes created or recreated on startup should be enqueued automatically. See also xref:config-options.adoc#existing-data-indexing[Existing Data Indexing].

Default value: `true`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities]]
== jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities

Defines the list of entities that should be automatically enqueued on startup in case of index recreation. Empty list means all indexed entities. See also xref:config-options.adoc#existing-data-indexing[Existing Data Indexing].

Default value: ``

[[jmix.search.enqueueingSessionProcessingCron]]
== jmix.search.enqueueingSessionProcessingCron

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] that is used by default Enqueueing Session processing Quartz xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration].

Default value: `0/5 * * * * ?`

[[jmix.search.indexingQueueProcessingCron]]
== jmix.search.indexingQueueProcessingCron

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] that is used by default Indexing Queue processing Quartz xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration].

Default value: `0/5 * * * * ?`

[[jmix.search.indexSchemaManagementStrategy]]
== jmix.search.indexSchemaManagementStrategy

The way of index schema synchronization. See xref:config-options.adoc#indexes-creation[Index Creation] for more detail.

Default value: `create-or-recreate`

[[jmix.search.maxSearchPageCount]]
== jmix.search.maxSearchPageCount

Sets the max amount of result pages.

Default value: `100`

[[jmix.search.processQueueBatchSize]]
== jmix.search.processQueueBatchSize

Sets the amount of queue items processed in single batch.

Default value: `100`

[[jmix.search.reindexEntityEnqueueBatchSize]]
== jmix.search.reindexEntityEnqueueBatchSize

Sets the amount of entity instances enqueued in single batch during entity reindex process.

Default value: `100`

[[jmix.search.restHighLevelClientApiCompatibilityModeEnabled]]
== jmix.search.restHighLevelClientApiCompatibilityModeEnabled

If `true`, the add-on is compatible with Elasticsearch 7.11 and above. If you need to use a version below 7.11, set this property to `false`.

Default value: `true`

[[jmix.search.searchIndexNamePrefix]]
== jmix.search.searchIndexNamePrefix

Prefix for search index name. Index naming template: <prefix><entity_name>. See xref:getting-started.adoc#configure-index-naming[Configure Index Naming].

Default value: `search_index_`

[[jmix.search.searchReloadEntitiesBatchSize]]
== jmix.search.searchReloadEntitiesBatchSize

Defines the batch size for post-search entity processing, for example, when results are filtered after search due to the row-level security policies, or when entities are fetched from search results with their fetch plans. See xref:search-api.adoc#security-and-pagination[Access Control and Pagination].

Default value: `100`

[[jmix.search.searchResultPageSize]]
== jmix.search.searchResultPageSize

Sets the max amount of objects displayed on single page of search result.

Default value: `100`

[[jmix.search.useDefaultEnqueueingSessionProcessingQuartzConfiguration]]
== jmix.search.useDefaultEnqueueingSessionProcessingQuartzConfiguration

Defines whether the default Enqueueing Session processing Quartz  xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration] is used.

Default value: `true`

[[jmix.search.useDefaultIndexingQueueProcessingQuartzConfiguration]]
== jmix.search.useDefaultIndexingQueueProcessingQuartzConfiguration

Defines whether the default Indexing Queue processing Quartz  xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration] is used.

Default value: `true`











