= Search MBean

Search provides the following operations within MBean:

* `enqueueIndexAll` - enqueues all instances of indexed entities. There are two variants of this operation - with parameter '`entityName'` (enqueues instances of this entity only) and without parameters (enqueues all instances of all indexed entities)
* `processEntireIndexingQueue` - processes all items in Indexing Queue
* `processIndexingQueueNextBatch` - processes next batch of items in Indexing Queue
* `recreateIndex` - drops and creates index related to provided entity. All data will be lost
* `recreateIndexes` - drops and creates all search indexes defined in application. All data will be lost.
* `synchronizeIndexSchema` - synchronizes schema of index related to provided entity. This may cause deletion of this index with all data - depends on schema management strategy
* `synchronizeIndexSchemas` - synchronizes schemas of all search indexes defined in application. This may cause deletion of indexes with all their data - depends on schema management strategy
* `validateIndex` - validates schema of search index related to provided entity and displays status
* `validateIndexes` - validates schemas of all search indexes defined in application and displays status for all indexes