= Updating Index Data

The Jmix application tracks data changes but does not pass them to Elasticsearch automatically. Please refer to section "[Indexing Queue Processing]" to set up the automatic update. You must do it to make data available for the search engine. Otherwise, your data will not appear in search results.

== Creation of Indexes
Before any data can be indexed and searched the search indexes should be created.

The application provides functionality of index schema synchronization - it checks current configuration of indexes and compares it to the expected ones. Further actions depends on selected Index Schema Management Strategy:

* `create-only` - every missing indexes will be created, exising indexes with irrelevant configuration will be kept as is.
* `create-or-recreate` - every missing indexes will be created, exising indexes with irrelevant configuration will be recreated (all data will be lost). This is the default strategy.
* `none` - *TODO*

Strategy can be configured by adding the following property to your `application.properties` file:

[source,properties]
----
jmix.search.indexSchemaManagementStrategy=create-only
----

Synchronization is automatically performed on application startup. And it can be manually performed using `synchronizeXXX` operations of Search MBean.

Also Search MBean allows to perform force index recreation - this operation drops and creates index without taking into account current Index Schema Management Strategy, even if target index has actual configuration. All data will be lost. For that purpose use `recreateIndex` operation.

== Existing Data Indexing
There are two approaches of existing data indexing:

* Automatic
* Manual

Automatic approach is part of index schema synchronization and enabled by default - it enqueues all instances for every entity whose index has been created (in the background process).
Automatic indexing can be enabled for specific entities only. For that purpose add the following property to your `application.properties` file:

[source,properties]
----
jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities=EntityName_1,EntityName_2
----

Or it can be completely disabled by adding the following property to your `application.properties` file:

[source,properties]
----
jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled=false
----

Manual approach involves using `enqueueIndexAll` operations of Search MBean.