= Свойства приложения

Свойства Динамической модели позволяют настраивать различные аспекты поведения дополнения.

[[jmix.dynmodel.deploy-on-app-start]]
== jmix.dynmodel.deploy-on-app-start

Если установлено значение `true`, активная версия динамической модели применяется автоматически при запуске приложения.

Значение по умолчанию: `true`

[[jmix.dynmodel.static-entity-table-prefix]]
== jmix.dynmodel.static-entity-table-prefix

Префикс для дополнительных таблиц, в которых хранятся динамические атрибуты статических сущностей.

Значение по умолчанию: `DYN_`

[[jmix.dynmodel.dynamic-entity-table-prefix]]
== jmix.dynmodel.dynamic-entity-table-prefix

Префикс для таблиц динамических сущностей.

Значение по умолчанию: `DYN_`

[[jmix.dynmodel.attribute-load-batch-size]]
== jmix.dynmodel.attribute-load-batch-size

Размер пакета для загрузки динамических атрибутов статических сущностей и динамических ссылок.

Значение по умолчанию: `1000`

[[jmix.dynmodel.calculated-attributes.default-evaluator]]
== jmix.dynmodel.calculated-attributes.default-evaluator

Вычислитель по умолчанию, используемый для вычисляемых динамических атрибутов, когда ни один не указан.

Значение по умолчанию: `spel`

[[jmix.dynmodel.security.full-access-roles]]
== jmix.dynmodel.security.full-access-roles

Разделённые запятыми коды ресурсных ролей, которым предоставляется полный доступ к ресурсам, управляемым динамической моделью.

Значение по умолчанию: `system-full-access`
