= Application Properties

Dynamic Model properties allow you to configure different aspects of the behavior of the add-on.

[[jmix.dynmodel.deploy-on-app-start]]
== jmix.dynmodel.deploy-on-app-start

If set to `true`, the active dynamic model version is applied automatically on application start.

Default value: `true`

[[jmix.dynmodel.static-entity-table-prefix]]
== jmix.dynmodel.static-entity-table-prefix

Prefix for the side tables that store dynamic attributes of static entities.

Default value: `DYN_`

[[jmix.dynmodel.dynamic-entity-table-prefix]]
== jmix.dynmodel.dynamic-entity-table-prefix

Prefix for the tables of dynamic entities.

Default value: `DYN_`

[[jmix.dynmodel.attribute-load-batch-size]]
== jmix.dynmodel.attribute-load-batch-size

Batch size for loading dynamic attributes of static entities and dynamic references.

Default value: `1000`

[[jmix.dynmodel.calculated-attributes.default-evaluator]]
== jmix.dynmodel.calculated-attributes.default-evaluator

Default evaluator used for calculated dynamic attributes when none is specified.

Default value: `spel`

[[jmix.dynmodel.security.full-access-roles]]
== jmix.dynmodel.security.full-access-roles

Comma-separated resource role codes that are granted full access to dynamic-model-managed resources.

Default value: `system-full-access`
