= Свойства приложения

Свойства Динамической модели позволяют настраивать различные аспекты поведения дополнения.

[[jmix.dynmodel.attribute-load-batch-size]]
== jmix.dynmodel.attribute-load-batch-size

Размер пакета для загрузки динамических атрибутов статических сущностей и динамических ссылок.

Значение по умолчанию: `1000`

[[jmix.dynmodel.calculated-attributes.default-evaluator]]
== jmix.dynmodel.calculated-attributes.default-evaluator

Вычислитель по умолчанию, используемый для вычисляемых динамических атрибутов, когда ни один не указан.

Значение по умолчанию: `spel`

[[jmix.dynmodel.cluster.apply-lock-timeout-sec]]
== jmix.dynmodel.cluster.apply-lock-timeout-sec

[.since]
Начиная с Jmix 3.1

Время в секундах, по истечении которого блокировка применения снимается, если узел, захвативший её, остановился во время применения. Значение должно быть больше самого долгого применения в вашем приложении. Если применение длится дольше, другой узел может захватить блокировку и одновременно применить модель.

Значение по умолчанию: `300`

[[jmix.dynmodel.cluster.apply-lock-wait-sec]]
== jmix.dynmodel.cluster.apply-lock-wait-sec

[.since]
Начиная с Jmix 3.1

Время в секундах, в течение которого узел ожидает блокировку применения, когда он применяет модель при запуске или применяет модель, полученную от другого узла.

Значение по умолчанию: `60`

[[jmix.dynmodel.cluster.enabled]]
== jmix.dynmodel.cluster.enabled

[.since]
Начиная с Jmix 3.1

Если установлено значение `true`, модель, применённая на одном узле кластера, применяется на всех остальных узлах, и в кластере одновременно может выполняться только одно применение. Требует дополнения xref:pessimistic-lock:index.adoc[]. См. раздел xref:dyn-model:concepts.adoc#cluster[Кластер].

Значение по умолчанию: `false`

[[jmix.dynmodel.deploy-on-app-start]]
== jmix.dynmodel.deploy-on-app-start

Если установлено значение `true`, активная версия динамической модели применяется автоматически при запуске приложения.

Значение по умолчанию: `true`

[[jmix.dynmodel.dynamic-entity-table-prefix]]
== jmix.dynmodel.dynamic-entity-table-prefix

Префикс для таблиц динамических сущностей.

Значение по умолчанию: `DYN_`

[[jmix.dynmodel.security.full-access-roles]]
== jmix.dynmodel.security.full-access-roles

Разделённые запятыми коды ресурсных ролей, которым предоставляется полный доступ к ресурсам, управляемым динамической моделью.

Значение по умолчанию: `system-full-access`

[[jmix.dynmodel.static-entity-table-prefix]]
== jmix.dynmodel.static-entity-table-prefix

Префикс для дополнительных таблиц, в которых хранятся динамические атрибуты статических сущностей.

Значение по умолчанию: `DYN_`

