= Application Properties

Dynamic Model properties allow you to configure different aspects of the behavior of the add-on.

[[jmix.dynmodel.attribute-load-batch-size]]
== jmix.dynmodel.attribute-load-batch-size

Batch size for loading dynamic attributes of static entities and dynamic references.

Default value: `1000`

[[jmix.dynmodel.calculated-attributes.default-evaluator]]
== jmix.dynmodel.calculated-attributes.default-evaluator

Default evaluator used for calculated dynamic attributes when none is specified.

Default value: `spel`

[[jmix.dynmodel.cluster.apply-lock-timeout-sec]]
== jmix.dynmodel.cluster.apply-lock-timeout-sec

[.since]
Since Jmix 3.1

Time in seconds after which the apply lock expires if the node that took it stopped during an apply. The value must be greater than the longest apply in your application. If an apply takes longer, another node can take the lock and apply a model at the same time.

Default value: `300`

[[jmix.dynmodel.cluster.apply-lock-wait-sec]]
== jmix.dynmodel.cluster.apply-lock-wait-sec

[.since]
Since Jmix 3.1

Time in seconds that a node waits for the apply lock when it applies the model at startup or applies a model received from another node.

Default value: `60`

[[jmix.dynmodel.cluster.enabled]]
== jmix.dynmodel.cluster.enabled

[.since]
Since Jmix 3.1

If set to `true`, a model applied on one node of a cluster is applied on all other nodes, and only one apply can run at a time in the cluster. Requires the Pessimistic Lock add-on. See xref:dyn-model:concepts.adoc#cluster[Cluster].

Default value: `false`

[[jmix.dynmodel.deploy-on-app-start]]
== jmix.dynmodel.deploy-on-app-start

If set to `true`, the active dynamic model version is applied automatically on application start.

Default value: `true`

[[jmix.dynmodel.dynamic-entity-table-prefix]]
== jmix.dynmodel.dynamic-entity-table-prefix

Prefix for the tables of dynamic entities.

Default value: `DYN_`

[[jmix.dynmodel.security.full-access-roles]]
== jmix.dynmodel.security.full-access-roles

Comma-separated resource role codes that are granted full access to dynamic-model-managed resources.

Default value: `system-full-access`

[[jmix.dynmodel.static-entity-table-prefix]]
== jmix.dynmodel.static-entity-table-prefix

Prefix for the side tables that store dynamic attributes of static entities.

Default value: `DYN_`

