= DataGrid Exporters

//Coming soon.
The `DataGridExporter` interface is designed to download the `DataGrid` content.

`DataGridExporter` has two standard implementations: <<excel-exporter,ExcelExporter>> class and <<json-exporter,JsonExporter>> class.

An instance of `DataGridExporter` is passed to the `setDataGridExporter()` method of xref:grid-export:actions.adoc[ExportAction].

[[custom-exporter]]
== Custom DataGrid Exporter

You can define a custom implementation of the `DataGridExporter` interface for exporting your format.

An example of declaring a custom data grid exporter:

[source,java,indent=0]
----
include::example$/gridexport-ex1/src/main/java/com/company/demo/exporters/CustomExporter.java[tags=CustomExporter]
----

[[excel-exporter]]
== ExcelExporter

Use the `ExcelExporter` class to export the `DataGrid` content into Excel format.

`ExcelExporter` is used in the standard xref:grid-export:actions.adoc#excel-export-action[ExcelExportAction] action.

[[json-exporter]]
== JsonExporter

Use the `JsonExporter` class to export the `DataGrid` content into JSON format.

`JsonExporter` is used in the standard xref:grid-export:actions.adoc#json-export-action[JsonExportAction] action.