= Grid Export Properties

[[jmix.gridexport.default-columns-to-export]]
== jmix.gridexport.default-columns-to-export

Specifies the default column selection behavior for the Grid Export functionality. This setting determines which columns are included in the xref:grid-export:actions.adoc#columns-export[export] when no other more specific configuration is provided.

Possible values: `ALL_COLUMNS`, `VISIBLE_COLUMNS`.

Default value: `VISIBLE_COLUMNS`.

[[jmix.gridexport.default-export-modes]]
== jmix.gridexport.default-export-modes

Defines the default set of options for the xref:actions.adoc[ExportAction] dialog.

Default value: `ALL_ROWS,CURRENT_PAGE,SELECTED_ROWS`.

[[jmix.gridexport.exportAllBatchSize]]
== jmix.gridexport.exportAllBatchSize

Defines the batch size when exporting all records.

Default value: `1000`.

For example:

[source,properties]
----
jmix.gridexport.exportAllBatchSize = 2000
----

[[jmix.gridexport.excel.useSxssf]]
== jmix.gridexport.excel.useSxssf

Defines whether to use streaming POI SXSSF API for building XLSX files.

Default value: `true`.