= Grid Export Properties

[[jmix.gridexport.export-all-batch-size]]
== jmix.gridexport.export-all-batch-size

Defines the batch size when exporting all records.

Default value: `1000`.

For example:

[source,properties]
----
jmix.gridexport.export-all-batch-size = 2000
----

[[jmix.gridexport.export-all-pagination-strategy]]
== jmix.gridexport.export-all-pagination-strategy

Defines the pagination strategy used when xref:grid-export:actions.adoc#export-modes[exporting] all entities.

Possible values:

* `keyset`: Retrieves entities based on primary key sorting. The next page begins after the last entity of the previous page.
* `limit-offset`: Retrieves entities in the same order as they are stored. Uses two parameters: `offset` (the starting record index) and `limit` (the number of records per page).

Default value: `keyset`.

[[jmix.gridexport.excel.use-sxssf]]
== jmix.gridexport.excel.use-sxssf

Defines whether to use streaming POI SXSSF API for building XLSX files.

Default value: `true`.