POST {{baseUrl}}/rest/oauth/token
Authorization: Basic {{cubaRestClientId}} {{cubaRestClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&username={{username}}&password={{password}}

> {%

    client.test("Response Code is 200", function() {
      client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Authentication Token can be retrieved", function() {
      client.assert(response.body.access_token, "Auth Token is not available in Response");
    });

    client.global.set("auth_token", response.body.access_token);
  %}

###

POST http://localhost:8080/rest/oauth/token
Authorization: Basic client secret
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=admin

###

