# Get initial access token

POST {{baseOauthUrl}}/token
Authorization: Basic {{jmixRestClientId}} {{jmixRestClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&username={{username}}&password={{password}}

> {%

    client.test("Response Code is 200", function() {
      client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Authentication Token can be retrieved", function() {
      client.assert(response.body.access_token, "Auth Token is not available in Response");
    });

    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
  %}

###

# Refresh access token through refresh token

POST {{baseOauthUrl}}/token
Authorization: Basic {{jmixRestClientId}} {{jmixRestClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token={{refresh_token}}

> {%

    client.test("Response Code is 200", function() {
      client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Authentication Token can be retrieved", function() {
      client.assert(response.body.access_token, "Auth Token is not available in Response");
    });

    client.global.set("access_token", response.body.access_token);
  %}

###