####################################################################################################
##
## Jmix Generic REST API
##
####################################################################################################


## Execute 'authenticate.http' first to get have a valid access token for the API

## Get all User entities

GET {{baseUrl}}/entities/sample_Order
Authorization: Bearer {{auth_token}}

> {%

    client.test("Response Code is 200", function() {
      client.assert(
          response.status === 200,
          "Response status is not 200 - OK"
      );
    });

    client.test("Entity List can be retrieved", function() {
      client.assert(
          response.body.length > 0,
          "Entity List does not contain multiple items"
      );
      client.assert(
          response.body[0]["_entityName"] === "sample_Order",
          "Entity List does not contain users"
      );
      client.assert(
          response.body[0]["id"],
          "ID Attribute of an Entity is not returned"
      );
    });
  %}

###