= Common Attributes

[[autocapitalize]]
== autocapitalize

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `autocapitalize` HTML attribute. It is used to define whether the text entered by the user should be automatically capitalized or not.

[[autocomplete]]
== autocomplete

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `autocomplete` HTML attribute for indicating whether the value of this component can be automatically completed by the browser.

[[autocorrect]]
== autocorrect

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Enable or disable the `autocorrect` HTML attribute for the field.

[NOTE]
This only supported by Safari.

[[autofocus]]
== autofocus

Specify that the component should have input focus when the page loads.

Possible values are `true`, `false`. By default, all components are not focused.

[[classNames]]
== classNames

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hasstyle-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Adds a CSS class name to the component.

[[colspan]]
== colspan

Sets the number of grid columns that the component should occupy.

Default is `1`.

[[dataContainer]]
== dataContainer

Sets a data container defined in the `data` section of the screen XML descriptor.

When you set some instance container as a value of the `dataContainer` attribute, you should also set the `property` attribute.

[[datatype]]
== datatype

Sets a xref:data-model:data-types.adoc[data type] of the component's content. Possible values:

* `boolean`
* `byteArray`
* `char`
* `date`
* `dateTime`
* `decimal`
* `double`
* `fileRef`
* `int`
* `localDate`
* `localDateTime`
* `localTime`
* `long`
* `offsetDateTime`
* `offsetTime`
* `string`
* `time`
* `uri`
* `uuid`

[[enabled]]
== enabled

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/enabled-state" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the UI object explicitly disabled or enabled.

[[errorMessage]]
== errorMessage

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets an error message to the component.

[[height]]
== height

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the height of the component.

The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

[[helperText]]
== helperText

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#helper" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Defines a text adjacent to the field that can be used, for example, to inform to the users which values it expects.

[[id]]
== id

An identifier of the component.

It is recommended to create identifiers according to the rules for Java identifiers and use camelСase, for example: `userGrid`, `filterPanel`. The `id` attribute can be specified for any component and should be unique within a view.

[[invalid]]
== invalid

Sets an invalid state to the field considering the result of the field validation.

* If `invalid=false` and validation is not passed, then the field is valid.
* If `invalid=false` and validation is passed, then the field is valid.
* If `invalid=true` and validation is not passed, then the field is invalid.
* If `invalid=true` and validation is passed, then the field is valid.

[[label]]
== label

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#label" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Specifies the label of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

[[maxHeight]]
== maxHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `max-height` CSS property of the component. The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

[[maxWidth]]
== maxWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `max-width` CSS property of the component. The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

[[minHeight]]
== minHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `min-height` CSS property of the component. The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

[[minWidth]]
== minWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `min-width` CSS property of the component. The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

[[pattern]]
== pattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#pattern" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a regular expression for the value to pass on the client-side. The pattern must be a valid JavaScript Regular Expression that matches the entire value, not just some subset.

[[placeholder]]
== placeholder

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#placeholder" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Defines a hint to the user of what can be entered in the component.

[[property]]
== property

Sets the name of an xref:data-model:entities.adoc[entity] attribute, which value will be displayed and edited by this visual component.

`property` is always used together with the <<dataContainer,dataContainer>> attribute.

[[readOnly]]
== readOnly

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#non-editable-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a boolean value specifying whether the component is put read-only mode or not. The component in read-only mode typically looks visually different to signal to the user that the value cannot be edited.

[[required]]
=== required

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#required" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Indicates that this field requires a value.

NOTE: The required indicator will not be visible, if the <<label,label>> property is not set for the component.

[[requiredIndicatorVisible]]
== requiredIndicatorVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#required" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the required indicator visible or not. If set visible, it is visually indicated in the user interface.

[[requiredMessage]]
== requiredMessage

Used together with the <<required,required>> attribute. It sets a message that will be displayed to a user when the component has no value.

The attribute can contain a message or a key from xref:localization:message-bundles.adoc[message bundle], for example: `requiredMessage="msg://infoTextField.requiredMessage"`

[[tabIndex]]
== tabIndex

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `tabindex` attribute in the component. The `tabIndex` indicates if its element can be focused, and if/where it participates in sequential keyboard navigation:

* A negative value (usually `tabindex = -1` means that the component should be focusable, but should not be reachable via sequential keyboard navigation.
* `tabindex = 0` means that the component should be focusable in sequential keyboard navigation, but its order is defined by the document's source order.
* A positive value means the component should be focusable in sequential keyboard navigation, with its order defined by the value of the number. That is, `tabindex = 4` would be focused before `tabindex = 5`, but after `tabindex = 3`. If multiple components share the same positive tabindex value, their order relative to each other follows their position in the document source.

[[text]]
== text

A text content of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

There are two ways of setting a key:

* A short key - in this case the message will be searched in the message group of the current view. For example: `msg://infoField.caption`

* Full key including message group, for example: `msg://com.company.sample.view.user/infoField.caption`

[[themeNames]]
== themeNames

Adds a theme name to the component.

See the `HasTheme` https://vaadin.com/docs/latest/create-ui/creating-components/mixins[mixin interface^] for more information.

[[title]]
== title

The value of the attribute is set to the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^] HTML attributes. Most components interpret it as a tooltip.

[[valueChangeMode]]
== valueChangeMode

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a new value change mode for the component.

[[valueChangeTimeout]]
== valueChangeTimeout

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Applies the value change timeout of the given mode on the registration of the DOM event listener that synchronizes. It has any effect only for `LAZY`, or `TIMEOUT`.

[[visible]]
== visible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/basic-features/#visibility" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets visibility of the component. Possible values - `true`, `false`.

[[width]]
== width

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the width of the component. The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.