= 通用属性

[[allowedCharPattern]]
== allowedCharPattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置客户端侧允许用户输入格式的正则表达式。设置的模式内容必须是合法的 JavaScript 正则表达式，用以匹配单一字符，而非字符序列。

例如，如需允许用户输入数字和短横，可以使用 `"[0-9/]"` 模式。

[[ariaLabel]]
== ariaLabel

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置一个单独的用于辅助功能的隐形标签，比如用于屏幕阅读器。

[[autocapitalize]]
== autocapitalize

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置 `autocapitalize` HTML 属性。定义是否自动将用户输入的文字转换成大写。

[[autocomplete]]
== autocomplete

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置 `autocomplete` HTML 属性。定义该组件的值是否可由浏览器自动填充。

[[autocorrect]]
== autocorrect

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

是否启用字段的 `autocorrect` HTML 属性。

[NOTE]
仅支持 Safari。

[[autofocus]]
== autofocus

指定该组件在页面加载后即获得输入焦点。

属性值可以是 `true` 或 `false`。默认情况下，没有组件自动获得焦点。

[[classNames]]
== classNames

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hasstyle-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

为组件添加一个 CSS 类名。

[[clearButtonVisible]]
== clearButtonVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#clear-button" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置是否显示控件的清除按钮。

[[colspan]]
== colspan

设置组件能占据的列宽。

默认值：`1`。

[[dataContainer]]
== dataContainer

在界面 XML 描述的 `data` 部分设置一个数据容器。

当设置 `dataContainer` 为某个实体实例容器时，需要同时设置 `property` 属性。

[[datatype]]
== datatype

设置组件内容的 xref:data-model:data-types.adoc[数据类型]。支持：

* `boolean`
* `byteArray`
* `char`
* `date`
* `dateTime`
* `decimal`
* `double`
* `fileRef`
* `int`
* `localDate`
* `localDateTime`
* `localTime`
* `long`
* `offsetDateTime`
* `offsetTime`
* `string`
* `time`
* `uri`
* `uuid`

[[dateFormat]]
== dateFormat

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#date-format" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

为组件支持的日期值设置格式偏好。默认情况下，使用当前 locale 的日期格式。

[[enabled]]
== enabled

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/enabled-state" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

显式设置 UI 对象是否启用。

[[errorMessage]]
== errorMessage

设置组件的错误消息。

[[height]]
== height

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的高度。

高度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

[[helperText]]
== helperText

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#helper" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的说明信息，例如，可以告诉用户该组件支持什么类型的值。

[[id]]
== id

组件的标识符。

推荐根据 Java 标识符规则创建组件标识符，使用驼峰命名法，例如：`userGrid`、`filterPanel`。任何组件都可以指定 `id` 属性，要求在同一视图内唯一。

[[invalid]]
== invalid

根据字段验证的结果设置字段的无效状态。

* 如果 `invalid=false` 且验证不通过，该字段有效。
* 如果 `invalid=false` 且验证通过，该字段有效。
* 如果 `invalid=true` 且验证不通过，该字段无效。
* 如果 `invalid=true` 且验证通过，该字段有效。

[[label]]
== label

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#label" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的标签。

该属性的值可以是一个纯文本，或 xref:localization:message-bundles.adoc[消息包] 中的一个键值。如果是键值，需要以 `msg://` 开头。

[[maxHeight]]
== maxHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `max-height` CSS 属性。高度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

[[maxLength]]
== maxLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置字段型组件允许输入的最大字符数。

[[maxWidth]]
== maxWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `max-width` CSS 属性。宽度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

[[metaClass]]
== metaClass

如果没有声明式定义 xref:flow-ui:vc/common-attributes.adoc#dataContainer[dataContainer] 属性的话，用来定义 xref:flow-ui:vc/components/dataGrid.adoc[dataGrid] 的 `columns` 类型。在 XML 定义 `metaClass` 属性等同于为 `dataGrid` 或 `treeDataGrid` 设置空集合。因此，可以在视图控制器中编程式设置集合。

[[minHeight]]
== minHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `min-height` CSS 属性。高度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

[[minLength]]
== minLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#minlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置字段型组件允许输入的最小字符数。

[[minWidth]]
== minWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `min-width` CSS 属性。宽度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

[[pattern]]
== pattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#pattern" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

客户端输入时，设置一个输入值需要符合的正则表达式。表达式必须是有效的 JavaScript 正则表达式，用于匹配整个值，而非部分值。

[[placeholder]]
== placeholder

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#placeholder" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

占位符。用来提示用户组件中可以输入什么内容。

[[property]]
== property

设置一个 xref:data-model:entities.adoc[实体] 属性的名称，可视化组件会显示或者编辑该属性值。

`property` 需要与 <<dataContainer,dataContainer>> 属性同时使用。

[[readOnly]]
== readOnly

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#non-editable-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件是否以只读模式显示。只读模式的组件在外观上会有不同，以告知用户无法修改组件值。

[[required]]
== required

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#required" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

表示该控件为必填项。

NOTE: 如果组件未设置 <<label,label>> 属性，则必填指示符将不可见。

[[requiredIndicatorVisible]]
== requiredIndicatorVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/input-fields/#required" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置是否显示必填指示符。如果设置为显示，会在 UI 展示该指示符。

[[requiredMessage]]
== requiredMessage

与 <<required,required>> 属性同时使用。当组件没有值时，则展示该消息。

属性值可以是一个消息本身，或者 xref:localization:message-bundles.adoc[消息包] 中的键值，示例：`requiredMessage="msg://infoTextField.requiredMessage"`。

[[step]]
== step

自定义 xref:vc/components/timePicker.adoc[] 或 xref:vc/components/dateTimePicker.adoc[] 组件中选择时间的间隔（分钟）。

[[tabIndex]]
== tabIndex

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置组件的 `tabindex` 属性。`tabIndex` 属性控制该元素是否可以获得焦点，以及通过键盘 Tab 键进行跳转时的位置：

* 负值（通常设置 `tabindex = -1`），表示组件可以获得焦点，但是不能通过键盘顺序导航访问到。
* 0，表示组件可以通过键盘顺序导航访问，但是访问顺序是按照 HTML 中 dom 的顺序定义。
* 正值，表示组件可以通过键盘顺序导航访问，并且按照该值定义的顺序进行访问。即，`tabindex = 4` 的组件会在 `tabindex = 5` 的组件之前，`tabindex = 3` 的组件之后。如果多个组件拥有相同的顺序值，则按照 HTML 中 dom 的顺序。

[[text]]
== text

组件的文本内容。

该属性的值可以是文本本身，或者是 xref:localization:message-bundles.adoc[消息包] 的一个键值。如果是消息包键值，则需要使用 `msg://` 前缀。

有两种方式设置键值：

* 短键值 - 此时会在当前视图的消息组中查找该键值。例如，`msg://infoField.caption`

* 包含消息组的全键值，例如，`msg://com.company.sample.view.user/infoField.caption`

[[themeNames]]
== themeNames

为组件添加一个主题。

[[title]]
== title

该属性的值会设置到网页的 https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] 和 https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^] HTML 属性。大多数组件将这个作为 tooltip 使用。

[[valueChangeMode]]
== valueChangeMode

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

为组件设置一个新的值修改模式（Value change mode）。

[[valueChangeTimeout]]
== valueChangeTimeout

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

在注册 DOM 事件同步监听器时，设置值修改模式的超时时限。仅影响 `LAZY` 或 `TIMEOUT` 模式。

[[visible]]
== visible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/basic-features/#visibility" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的可见性。支持 `true`，`false`。

[[weekNumbersVisible]]
== weekNumbersVisible
++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#week-numbers" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置日历的弹窗中是否显示第几周的信息。仅当设置星期一为每周开始时有效。

[[whiteSpace]]
== whiteSpace

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/white-space" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

表示 `"white-space"` 样式值。

默认值：`NORMAL`。

[[width]]
== width

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件宽度。宽度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。
