= Common Attributes

[[id]]
== id

An identifier of the component.

It is recommended to create identifiers according to the rules for Java identifiers and use camelСase, for example: `userGrid`, `filterPanel`. The `id` attribute can be specified for any component and should be unique within a view.

[[text]]
== text

A text content of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

There are two ways of setting a key:

* A short key – in this case the message will be searched in the message group of the current view. For example: `msg://infoField.caption`

* Full key including message group, for example: `msg://com.company.sample.view.user/infoField.caption`

[[title]]
== title

The value of the attribute is set to the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^] HTML attributes. Most components interpret it as a tooltip.