= Общие обработчики

[[AttachEvent]]
== AttachEvent

`com.vaadin.flow.component.AttachEvent` отправляется после присоединения компонента к UI.

[[BlurEvent]]
== BlurEvent

`com.vaadin.flow.component.BlurNotifier.BlurEvent` соответствует DOM-событию `blur`.

[[ClientValidatedEvent]]
== ClientValidatedEvent

`com.vaadin.flow.component.shared.HasClientValidation.ClientValidatedEvent` отправляется веб-компонентом всякий раз, когда он проверяется на стороне клиента. Это событие соответствует DOM-событию `validated`.

[[ComponentValueChangeEvent]]
== ComponentValueChangeEvent

`com.vaadin.flow.component.AbstractField.ComponentValueChangeEvent` отправляется при изменении значения компонента.

[[CompositionEndEvent]]
== CompositionEndEvent

`com.vaadin.flow.component.CompositionEndEvent` отправляется, когда композиция завершена. Соответствует DOM-событию `compositionend`.

[[CompositionStartEvent]]
== CompositionStartEvent

`com.vaadin.flow.component.CompositionStartEvent` отправляется при запуске композиции. Соответствует DOM-событию `compositionstart`.

[[CompositionUpdateEvent]]
== CompositionUpdateEvent

`com.vaadin.flow.component.CompositionUpdateEvent` отправляется при обновлении композиции. Соответствует DOM-событию `compositionupdate`.

[[DetachEvent]]
== DetachEvent

`com.vaadin.flow.component.DetachEvent` отправляется перед тем, как компонент отсоединяется от UI.

[[FocusEvent]]
== FocusEvent

`com.vaadin.flow.component.FocusNotifier.FocusEvent` соответствует DOM-событию `focus`.

[[InputEvent]]
== InputEvent

`com.vaadin.flow.component.InputEvent` отправляется, когда компонент получает любой тип ввода (например, щелчок, нажатие клавиши). Соответствует DOM-событию `input`.

[[KeyDownEvent]]
== KeyDownEvent

`com.vaadin.flow.component.KeyDownEvent` отправляется при нажатии клавиши. Соответствует DOM-событию `keydown`.

[[KeyPressEvent]]
== KeyPressEvent

`com.vaadin.flow.component.KeyPressEvent` отправляется при нажатии клавиши. Соответствует DOM-событию `keypress`.

[[KeyUpEvent]]
== KeyUpEvent

`com.vaadin.flow.component.KeyUpEvent` отправляется при отпускании клавиши. Соответствует DOM-событию `keyup`.

[[statusChangeHandler]]
== statusChangeHandler

`io.jmix.flowui.component.SupportsStatusChangeHandler` используется для обработки изменений состояния компонента, например, сообщений проверки, установленных методом `HasValidation.setErrorMessage(String)`.

Например, вместо отображения сообщений проверки под компонентом, можно использовать отдельный компонент, такой как `Label`:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/textfield/text-field-view.xml[tags=negativeField]
----

Обработчик должен быть определен следующим образом:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/textfield/TextFieldView.java[tags=infoLabel;statusChangeHandler]
----

<1> Делает `infoLabel` видимым.
<2> Получает сообщение об ошибке из объекта `StatusContext` и устанавливает его в текст `infoLabel`.

[[TypedValueChangeEvent]]
== TypedValueChangeEvent

`io.jmix.flowui.component.SupportsTypedValue.TypedValueChangeEvent` отправляется, когда пользователь завершил манипуляции с компонентом. Например, после нажатия `Enter` или когда компонент теряет фокус.

Событие имеет следующие методы:

* `getOldValue()` возвращает типизированное значение компонента до изменения.
* `getValue()` возвращает текущее типизированное значение компонента.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/textfield/TextFieldView.java[tags=autowired-notifications;typedValueChangeEvent]
----