= 通用事件

[[AttachEvent]]
== AttachEvent

`com.vaadin.flow.component.AttachEvent` 在组件添加至 UI 后发送。

[[BlurEvent]]
== BlurEvent

`com.vaadin.flow.component.BlurNotifier.BlurEvent` 对应 `blur` DOM 事件。

[[ComponentValueChangeEvent]]
== ComponentValueChangeEvent

当组件的值发生变化时，发送 `com.vaadin.flow.component.AbstractField.ComponentValueChangeEvent` 事件。

[[CompositionEndEvent]]
== CompositionEndEvent

当文本合成结束时发送 `com.vaadin.flow.component.CompositionEndEvent` 事件。对应于 `compositionend` DOM 事件。

[[CompositionStartEvent]]
== CompositionStartEvent

当文本合成开始时发送 `com.vaadin.flow.component.CompositionStartEvent` 事件。对应于 `compositionstart` DOM 事件。

[[CompositionUpdateEvent]]
== CompositionUpdateEvent

当文本合成更新时发送 `com.vaadin.flow.component.CompositionUpdateEvent` 事件。对应于 `compositionupdate` DOM 事件。

[[DetachEvent]]
== DetachEvent

`com.vaadin.flow.component.DetachEvent` 在组件从 UI 中脱离之前发送。

[[FocusEvent]]
== FocusEvent

`com.vaadin.flow.component.FocusNotifier.FocusEvent` 对应 `focus` DOM 事件。

[[InputEvent]]
== InputEvent

当组件收到任何类型的输入时（例如，点击、或者按下某个键），发送 `com.vaadin.flow.component.InputEvent` 事件。

该事件专门用于 DOM API 中的 `input` 事件。

[[KeyDownEvent]]
== KeyDownEvent

当按下某个键时发送 `com.vaadin.flow.component.KeyDownEvent` 事件。对应于 `keydown` DOM 事件。

[[KeyPressEvent]]
== KeyPressEvent

当按下某个键时发送 `com.vaadin.flow.component.KeyPressEvent` 事件。对应于 `keypress` DOM 事件。

[[KeyUpEvent]]
== KeyUpEvent

当抬起某个键时发送 `com.vaadin.flow.component.KeyUpEvent` 事件。对应于 `keyup` DOM 事件。

[[TypedValueChangeEvent]]
== TypedValueChangeEvent

当用户完成对组件的操作时，发送 `io.jmix.flowui.component.SupportsTypedValue.TypedValueChangeEvent` 事件。例如，当按下 `Enter` 键或者组件失去焦点时。

事件具有下列方法：

* `getOldValue()` 返回修改前的值（带类型）。
* `getValue()` 返回当前输入的值（带类型）。

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/component/textfield/TextFieldView.java[tags=autowired-notifications;typedValueChangeEvent]
----
