= Common Attributes

[[autocapitalize]]
== autocapitalize

Sets the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize[autocapitalize^] HTML attribute. It is used to define whether the text entered by the user should be automatically capitalized or not.

[[autocomplete]]
== autocomplete

Sets the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete[autocomplete^] HTML attribute for indicating whether the value of this component can be automatically completed by the browser.

[[autocorrect]]
== autocorrect

Enable or disable the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect[autocorrect^] HTML attribute for the field.

[NOTE]
This only supported by Safari.

[[autofocus]]
== autofocus

Specify that the component should have input focus when the page loads.

Possible values are `true`, `false`. By default, all components are not focused.

[[classNames]]
== classNames

Adds a CSS class name to the component.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hasstyle-interface[Vaadin Docs^] for more information.

[[dataContainer]]
== dataContainer

Sets a data container defined in the `data` section of the screen XML descriptor.

When you set some instance container as a value of the `dataContainer` attribute, you should also set the `property` attribute.

[[datatype]]
== datatype

Sets a xref:data-model:data-types.adoc[data type] of the component's content. Possible values:

* `boolean`
* `byteArray`
* `char`
* `date`
* `dateTime`
* `decimal`
* `double`
* `fileRef`
* `int`
* `localDate`
* `localDateTime`
* `localTime`
* `long`
* `offsetDateTime`
* `offsetTime`
* `string`
* `time`
* `uri`
* `uuid`

[[enabled]]
== enabled

Sets the UI object explicitly disabled or enabled.

See the https://vaadin.com/docs/latest/create-ui/enabled-state[Vaadin Docs^] for more information.

[[errorMessage]]
== errorMessage

Sets an error message to the component.

See the https://vaadin.com/docs/latest/components/text-field[Vaadin Docs^] for more information.

[[height]]
== height

Sets the height of the component.

The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface[Vaadin Docs^] for more information.

[[helperText]]
== helperText

Defines a text adjacent to the field that can be used, for example, to inform to the users which values it expects.

See the https://vaadin.com/docs/latest/components/input-fields/#helper[Vaadin Docs^] for more information.

[[id]]
== id

An identifier of the component.

It is recommended to create identifiers according to the rules for Java identifiers and use camelСase, for example: `userGrid`, `filterPanel`. The `id` attribute can be specified for any component and should be unique within a view.

[[invalid]]
== invalid

Sets an invalid state to the field considering the result of the field validation.

* If `invalid=false` and validation is not passed, then the field is valid.
* If `invalid=false` and validation is passed, then the field is valid.
* If `invalid=true` and validation is not passed, then the field is invalid.
* If `invalid=true` and validation is passed, then the field is valid.

[[label]]
== label

Specifies the label of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

See the https://vaadin.com/docs/latest/components/input-fields/#label[Vaadin Docs^] for more information.

[[maxHeight]]
== maxHeight

Sets the https://developer.mozilla.org/en-US/docs/Web/CSS/max-height[max-height^] of the component.
The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface[Vaadin Docs^] for more information.

[[maxWidth]]
== maxWidth

Sets the https://developer.mozilla.org/en-US/docs/Web/CSS/max-width[max-width^] of the component.
The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface[Vaadin Docs^] for more information.

[[minHeight]]
== minHeight

Sets the https://developer.mozilla.org/en-US/docs/Web/CSS/min-height[min-height^] of the component.
The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface[Vaadin Docs^] for more information.

[[minWidth]]
== minWidth

Sets the https://developer.mozilla.org/en-US/docs/Web/CSS/min-width[min-width^] of the component.
The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface[Vaadin Docs^] for more information.

[[pattern]]
== pattern

Sets a regular expression for the value to pass on the client-side. The pattern must be a valid JavaScript Regular Expression that matches the entire value, not just some subset.

See the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern[pattern] HTML attribute, and the https://html.spec.whatwg.org/multipage/input.html#attr-input-pattern[pattern] attribute.

See the https://vaadin.com/docs/latest/components/text-field/#pattern[Vaadin Docs^] for more information.

[[placeholder]]
== placeholder

Defines a hint to the user of what can be entered in the component.

See the https://vaadin.com/docs/latest/components/text-field/#placeholder[Vaadin Docs^] for more information.

[[property]]
== property

Sets the name of an xref:data-model:entities.adoc[entity] attribute, which value will be displayed and edited by this visual component.

`property` is always used together with the <<dataContainer,dataContainer>> attribute.

[[readOnly]]
== readOnly

Sets a boolean value specifying whether the component is put read-only mode or not. The component in read-only mode typically looks visually different to signal to the user that the value cannot be edited.

See the https://vaadin.com/docs/latest/components/input-fields/#non-editable-fields[Vaadin Docs^] for more information.

[[requiredIndicatorVisible]]
== requiredIndicatorVisible

Sets the required indicator visible or not.
If set visible, it is visually indicated in the user interface.

See the https://vaadin.com/docs/latest/components/input-fields/#required[Vaadin Docs^] for more information.

[[requiredMessage]]
== requiredMessage

Used together with the xref:flow-ui:vc/components/text-field.adoc#required[required] attribute. It sets a message that will be displayed to a user when the component has no value.

The attribute can contain a message or a key from xref:localization:message-bundles.adoc[message bundle], for example: `requiredMessage="msg://infoTextField.requiredMessage"`

[[text]]
== text

A text content of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

There are two ways of setting a key:

* A short key - in this case the message will be searched in the message group of the current view. For example: `msg://infoField.caption`

* Full key including message group, for example: `msg://com.company.sample.view.user/infoField.caption`

[[themeNames]]
== themeNames

Adds a theme name to the component.

See the `HasTheme` https://vaadin.com/docs/latest/create-ui/creating-components/mixins[mixin interface^] for more information.

[[title]]
== title

The value of the attribute is set to the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^] HTML attributes. Most components interpret it as a tooltip.

[[valueChangeMode]]
== valueChangeMode

Sets new value change mode for the component.

See the https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields[Vaadin Docs^] for more information.

[[valueChangeTimeout]]
== valueChangeTimeout

Applies the value change timeout of the given mode on the registration of the DOM event listener that synchronizes. It has any effect only for `LAZY`, or `TIMEOUT`.

See the https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields[Vaadin Docs^] for more information.

[[visible]]
== visible

Sets visibility of the component. Possible values - `true`, `false`.

See the https://vaadin.com/docs/latest/create-ui/basic-features/#visibility[Vaadin Docs^] for more information.

[[width]]
== width

Sets the width of the component.

The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

See the https://vaadin.com/docs/latest/create-ui/creating-components/mixins#hassize-interface[Vaadin Docs^] for more information.