= Что нового

Jmix 1.0 – это первый стабильный релиз.

Ниже вы можете найти полный список изменений с момента предварительного выпуска версии 0.9, а также инструкции по обновлению вашего проекта с 0.9 до версии 1.0.

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:
** xref:release_1.0.2.adoc[1.0.2]
** xref:release_1.0.1.adoc[1.0.1]
** xref:release_1.0.0.adoc[1.0.0]

* Решенные проблемы в Jmix Studio:
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.0.2[1.0.2^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.0.1[1.0.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.0.0[1.0.0^]

[[upgrade-from-0.9]]
== Переход с Jmix 0.9

. Обновите версию Gradle, используемую в вашем проекте, до версии 7.0. Update Gradle used in your project to 7.0. Откройте терминал в каталоге проекта и выполните:
+
[source,shell script]
----
./gradlew wrapper --gradle-version=7.0.2
----

. В `build.gradle`, замените версии плагина Gradle Jmix и BOM:
+
[source,groovy]
----
plugins {
    id 'io.jmix' version '1.0.2'
    id 'java'
}
// ...
jmix {
    bomVersion = '1.0.1'
}
----
+
Click *Load Gradle Changes* в небольшом всплывающем окне в правом верхнем углу окна редактора или нажмите *Gradle -> Re-import Gradle Project* в окне инструментов *Jmix*.

. В `application.properties`, замените значение свойства `jmix.core.availableLocales`. Это должен быть список кодов локали, разделенных запятыми:
+
[source,properties]
----
jmix.core.availableLocales = en
----

. В `LoginScreen.java`, замените `LoginScreenAuthenticationSupport` на `LoginScreenSupport`, исправьте методы `initLocalesField()` и `login()`:
+
[source,java]
----
import io.jmix.securityui.authentication.LoginScreenSupport;
// ...
public class LoginScreen extends Screen {
    // ...
    @Autowired
    private LoginScreenSupport loginScreenSupport;

    @Autowired
    private MessageTools messageTools;

    @Autowired
    private JmixApp app;
    // ...

    private void initLocalesField() {
        localesField.setOptionsMap(messageTools.getAvailableLocalesMap());
        localesField.setValue(app.getLocale());
    }

    private void login() {
        // ...
        loginScreenSupport.authenticate(/**/);
        // ...
----

. В `login-screen.xml` и `main-screen.xml`, измените префикс имени стиля c `c-` на `jmix-` для всех компонентов, например:
+
[source,xml]
----
<layout stylename="jmix-login-main-layout">
----

. В `main-screen.xml`, исправьте компонент `image`:
+
[source,xml]
----
<image id="logoImage"
       stylename="app-icon"
       scaleMode="SCALE_DOWN">
    <resource>
        <theme path="branding/app-icon-menu.svg"/>
    </resource>
</image>
----

. Если вы используете пользовательскую тему, измените название свойства с `jmix.ui.theme` на `jmix.ui.theme.name`, например:
+
[source,properties]
----
jmix.ui.theme.name = hover
----

. Если вы используете инжектирование `Logger` в контроллеры экранов, перепишите его следующим образом:
+
[source,java]
----
private static final Logger log = LoggerFactory.getLogger(MyScreenController.class);
----

. Если вы используете пользовательскую конфигурацию `DataLoadCoordinator`, перепишите ее как указано в тикете https://github.com/haulmont/jmix-ui/issues/463[#463^].

. Если вы используете formatters в компонентах UI, перепишите их как указано в тикете https://github.com/Haulmont/jmix-ui/issues/452[#452^].

Если в процессе у вас возникнут какие-либо проблемы, попробуйте очистить кэши IntelliJ: нажмите *File -> Invalidate Caches...*, поставьте все галочки и нажмите *Invalidate and Restart*.

// todo versioning policy?