= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 8.6 в `gradle/wrapper/gradle-wrapper.properties`.
* В проектах на Kotlin обновляет версию плагина Kotlin до 1.9.22.
* В связи с перемещением функциональности <<pessimistic-locking, пессимистической блокировки>>, заменяет использования пакетов `io.jmix.core.pessimisticlocking` на `io.jmix.pessimisticlock`, заменяет свойства `jmix.core.pessimistic-lock.\*` на `jmix.pslock.\*` и добавляет зависимости на новый аддон в `build.gradle`.
* Добавляет свойство приложения `spring.main.allow-circular-references = true`. Подробнее см. <<circular-dependencies-between-spring-beans,ниже>>.
* Добавляет свойство приложения `jmix.core.skip-null-or-empty-conditions-by-default = true`. Подробнее см. <<handling-empty-conditions,ниже>>.
* Добавляет свойство приложения `jmix.appsettings.check-permissions-for-app-settings-entity = true` если проект содержит дополнение Application Settings. Подробнее см. <<security-in-application-settings,ниже>>.


См. полный список <<breaking-changes,опасных изменений>>, которые могут затронуть ваш проект после обновления.

[[updated-dependencies]]
== Обновленные зависимости

Следующие важные зависимости были обновлены:

* Spring Boot 3.2. См. его https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes[release notes^] для получения подробной информации.

* Vaadin 24.3. См. release notes для Vaadin https://github.com/vaadin/platform/releases/tag/24.2.0[24.2^] и https://github.com/vaadin/platform/releases/tag/24.3.0[24.3^] для получения подробной информации. Studio удаляет файл `.pnpmfile.cjs` из проекта при миграции на Jmix 2.2 (по причине проблемы, описанной в https://github.com/vaadin/flow/issues/17873[vaadin/flow#17873^]). Убедитесь что данный файл более не существует после миграции.

[[new-features]]
== Новая и улучшенная функциональность

[[java-21]]
=== Поддержка Java 21

Теперь вы можете использовать Java 21 и все её языковые возможности для написания приложений.

Фреймворк по-прежнему собирается с использованием Java 17, поэтому обе версии (и 17 и 21) доступны для прикладных проектов.

[[breaking-changes]]
== Опасные изменения

[[circular-dependencies-between-spring-beans]]
=== Циклические зависимости между бинами Spring

Ранее циклические зависимости между бинами Spring были разрешены в Jmix на уровне фреймворка.

Jmix 2.2 больше не имеет циклических зависимостей и по умолчанию не разрешает их в прикладных проектах.

Есть вероятность того, что ваш проект содержит циклические зависимости между своими бинами, поэтому процедура миграции Studio автоматически добавляет следующее свойство в проект:

[source,properties]
----
spring.main.allow-circular-references = true
----

Мы рекомендуем вам удалить это свойство и попробовать запустить приложение. Если произойдет ошибка инициализации, то либо переработайте свои бины, чтобы устранить циклические зависимости, либо верните данное свойство.

Подробнее см. https://github.com/jmix-framework/jmix/issues/287[#287^].

[[handling-empty-conditions]]
=== Обработка пустых условий

Ранее xref:data-access:data-manager.adoc#load-by-conditions[условия по свойствам] преобразовывались в true если параметр условия был пуст (null, пустая строка или пустая коллекция).

Начиная с Jmix 2.2, null или пустой параметр не приводит к пропуску условия. Для примера рассмотрим следующий код:

[source,java]
----
dataManager.load(User.class)
    .condition(PropertyCondition.contains("email", null))
    .list();
----

В Jmix 2.1 и ранее он выполнял следующий SQL:

[source,sql]
----
SELECT ID, ACTIVE, EMAIL, <...> FROM USER_
----

В Jmix 2.2 по умолчанию он выполняет следующий SQL и передает `null` в качестве значения параметра:

[source,sql]
----
SELECT ID, ACTIVE, EMAIL, <...> FROM USER_ WHERE EMAIL LIKE ?
----

В результате, в Jmix 2.1 возвращается список всех пользователей, а в Jmix 2.2 результирующий список будет пуст.

Чтобы вернуть предыдущее поведение, установите следующее свойство приложения:

[source,properties]
----
jmix.core.skip-null-or-empty-conditions-by-default = true
----

Процедура миграции Studio автоматически добавляет это свойство в ваш проект.

В качестве альтернативы, вы можете пропустить пустые параметры для конкретных условий:

[source,java]
----
dataManager.load(User.class)
    .condition(PropertyCondition.contains("email", null).skipNullOrEmpty())
    .list();
----

Подробнее см. https://github.com/jmix-framework/jmix/issues/2490[#2490^].

[[noResultException]]
=== NoResultException

Исключение `io.jmix.core.NoResultException` теперь выбрасывается вместо `java.lang.IllegalStateException`, если метод `one()` xref:data-access:data-manager.adoc#load-by-id[fluent API загрузки сущностей] DataManager не нашел ни одного экземпляра. См. https://github.com/jmix-framework/jmix/issues/2682[#2682^].

[[pessimistic-locking]]
=== Пессимистическая блокировка

Функция пессимистическая блокировки была выделена в xref:pessimistic-lock:index.adoc[дополнение].

Пакет `io.jmix.core.pessimisticlocking` переименован в `io.jmix.pessimisticlocking`.

Следующие свойства приложения были изменены:

* `jmix.core.pessimistic-lock.use-default-quartz-configuration` -> `jmix.pslock.use-default-quartz-configuration`
* `jmix.core.pessimistic-lock.expiration-cron` -> `jmix.pslock.expiration-cron`

Процедура миграции Studio автоматически добавляет зависимости в ваш `build.gradle` и изменяет импорты и имена свойств.

Подробнее см. https://github.com/jmix-framework/jmix/issues/1958#issuecomment-1792291873[#1958^].

[[validation-in-file-upload-fields]]
=== Валидация в полях загрузки файлов

Метод `isInvalid()` компонентов xref:flow-ui:vc/components/fileUploadField.adoc[] и xref:flow-ui:vc/components/fileStorageUploadField.adoc[] теперь не вызывает валидацию, а только проверяет валидное состояние поля. См. https://github.com/jmix-framework/jmix/issues/2821[#2821^].

[[action-shortcuts]]
=== Сочетания клавиш действий

Клавиатурные сочетания действий, назначенных компонентам типа xref:flow-ui:vc/components/button.adoc[] или xref:flow-ui:vc/components/dataGrid.adoc[] теперь обрабатываются иначе. Подробнее см. https://github.com/jmix-framework/jmix/issues/1758#issuecomment-1859722867[#1758^].

[[security-in-application-settings]]
=== Проверка прав в Application Settings

Дополнение xref:appsettings:index.adoc[] теперь не требует наличия прав на сущность `AppSettingsEntity` для работы с настройками через бин `AppSettings`.

Чтобы вернуть предыдущее поведение,  установите следующее свойство приложения:

[source,properties]
----
jmix.appsettings.check-permissions-for-app-settings-entity = true
----

Процедура миграции Studio автоматически добавляет это свойство в ваш проект.

Подробнее см. https://github.com/jmix-framework/jmix/issues/2710[#2710^].

[[changed-api-in-maps]]
=== Изменения API в дополнении Maps

Следующие изменения произведены в дополнении xref:maps:index.adoc[]:

* `io.jmix.mapsflowui.kit.component.model.style.text.Padding` перемещен в пакет `io.jmix.mapsflowui.kit.component.model`. См. https://github.com/jmix-framework/jmix/issues/2822[#2822^].
* Метод `addStyles()` классов `Feature`, `PointFeature`, `MarkerFeature`, `LineStringFeature`, `PolygonFeature` теперь возвращает `void`. Используйте вместо него метод `withStyles()`, если вам нужно вернуть экземпляр feature. См. https://github.com/jmix-framework/jmix/issues/2807[#2807^].
* Метод `addStyles()` класса `VectorLayer` теперь возвращает `void`. Используйте вместо него метод `withStyles()`, если вам нужно вернуть экземпляр слоя. Кроме того, переименованы методы: `isDeclutter()` -> `getDeclutter()`, `isUpdateWhileAnimating()` -> `getUpdateWhileAnimating()`. См. https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* Метод `addPointStyles()` класса `ClusterSource` теперь возвращает `void`. Используйте вместо него метод `withPointStyles()`, если вам нужно вернуть экземпляр источника. См. https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* В классе `Layer` метод `isVisible()` переименован в `getVisible()`. См. https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* Тип свойств зума в классах `VectorLayer`, `TileLayer`, `ImageLayer` и `GeoMapView` изменен с `Integer` на `Double`. См. https://github.com/jmix-framework/jmix/issues/2701[#2701^].

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aissue+project%3Ajmix-framework%2F18+is%3Aclosed[2.2.0^]
// ** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.2.0[2.2.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.2.0,-2.1.*%20Affected%20versions:%20-SNAPSHOT[2.2.0^]
