= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates the version of Gradle wrapper to 8.8 in `gradle/wrapper/gradle-wrapper.properties`.
* If the project includes the REST API add-on, adds the `jmix.resource-server.authenticated-url-patterns` property, see details <<protecting-generic-rest-endpoints,below>>.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[new-features]]
== New Features and Improvements

[[advanced-endpoints-security-configuration]]
=== Advanced Endpoints Security Configuration

More options have been introduced for configuring endpoints security when using Authorization Server or OpenID Connect add-ons:

* `jmix.resource-server.authenticated-url-patterns` and `jmix.resource-server.anonymous-url-patterns` properties
* `AuthenticatedUrlPatternsProvider` and `AnonymousUrlPatternsProvider`
* `AuthenticatedRequestMatcherProvider` and `AnonymousRequestMatcherProvider`

See xref:security:custom-endpoints.adoc#token-based-authentication[Token Based Authentication] for more information.

The old `AuthorizedUrlsProvider` is deprecated, but still works, as well as `jmix.rest.authenticated-url-patterns` and `jmix.rest.anonymous-url-patterns` properties. It is recommended to move the configuration to the new interfaces or properties.

[[breaking-changes]]
== Breaking Changes

[[protecting-generic-rest-endpoints]]
=== Protecting Generic REST Endpoints

Due to improvements in endpoints security configuration (see <<advanced-endpoints-security-configuration,above>>), the following application property must be set to secure the Generic REST API endpoints:

[source,properties]
----
jmix.resource-server.authenticated-url-patterns = /rest/**
----

The Studio migration procedure adds it to `application.properties` automatically.

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.0[2.4.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.0,-2.3.*%20Affected%20versions:%20-SNAPSHOT[2.4.0^]
