= 最近更新

本章节包含 Jmix 框架和 Studio {page-component-display-version} 的新功能介绍，以及在升级框架版本时需要注意的一些破坏性改动。

[[upgrade]]
== 如何升级

IMPORTANT: 如需新建 Jmix {page-component-display-version} 项目或者升级已有项目，需要使用 Studio {page-component-display-version} 以上版本。因此，先 xref:studio:update.adoc[升级] Jmix Studio 插件。

参阅 xref:studio:project.adoc#upgrading-project[升级项目] 部分的介绍了解如何使用 Studio 升级项目。自动升级迁移过程会对项目做如下修改：

* 升级 Jmix BOM 的版本，BOM 又定义了所有依赖的版本。
* 升级 Jmix Gradle 插件的版本。
* 升级 Gradle wrapper 的版本至 7.4，修改 `gradle/wrapper/gradle-wrapper.properties` 文件。

[[new-features]]
== 新功能

[[business-calendar]]
=== 工作日历扩展组件

此扩展组件可以管理工作日历，包括假日、已计划的和额外的工作日。配置的工作日历提供 API 访问工作日期和时间。

NOTE: 此扩展组件需要企业版 https://www.jmix.cn/subscription-plans-and-prices/[订阅^]。

参阅 xref:business-calendar:index.adoc[] 章节了解详情。

[[notifications]]
=== 通知扩展组件

此扩展组件 allows you to create and send notifications via various message channels. Users can receive informational messages, notifications about system events, as well as notifications from business processes.

NOTE: 此扩展组件需要企业版 https://www.jmix.cn/subscription-plans-and-prices/[订阅^]。

参阅 xref:notifications:index.adoc[] 章节了解详情。

[[oidc]]
=== OpenID Connect 扩展组件

OpenID Connect 扩展组件提供预定义的 Spring Security 配置和一组服务，方便实现下列功能：

* 使用外部 OpenID Provider 进行认证（例如，Keycloak）。
* OpenID Provider 用户和 Jmix 用户的属性和角色映射。
* 用户通过 OpenID Provider 认证成功后，对用户实体和角色分配进行持久化存储。

此时该扩展组件还未在组件市场发布，但是可以在 `build.gradle` 文件中添加下列依赖安装：

[source,groovy,indent=0]
----
implementation 'io.jmix.oidc:jmix-oidc-starter'
----

参阅此扩展组件代码仓库的 https://github.com/Haulmont/jmix-oidc[README^] 了解详情。
CAUTION: OpenID Connect 扩展组件目前还处于孵化状态，其 API 和行为可能会在将来的主要版本或补丁版本中发生改变。

参阅扩展组件仓库中的 https://github.com/jmix-framework/jmix/blob/master/jmix-oidc/README.md[README^] 了解详情。

[[quartz]]
=== Quartz 扩展组件

此扩展组件支持通过用户界面管理 https://www.quartz-scheduler.org/[Quartz^] 作业：

* 使用 `org.quartz.Job` 接口的已有实现新建 Quartz 作业。
* 暂停和继续执行作业。
* 触发非活跃任务立即执行。
* 编辑作业触发器和参数。
* 删除作业。

参阅 xref:quartz:index.adoc[] 章节了解详情。

[[appplication-settings]]
=== 应用程序属性扩展组件

应用程序属性扩展组件提供了简洁的 API 和 UI，用来处理数据库中存储的不同类型参数值。这些值通常作为应用程序不同功能的参数使用。

参阅 xref:appsettings:index.adoc[] 章节了解详情。

[[composite-projects]]
=== 组合项目

Studio 现在支持将多个扩展组件和应用程序作为单一 IDE 项目进行开发，即便这些项目位于不同的源码仓库。

如需创建组合项目，在 Studio 中启动项目创建向导，并选择 Jmix `1.2.1` 或以上版本，以及 *Composite Project* 模板。Studio 创建的项目结构如下（假设项目名为 `demo`）：

----
root-dir/
    demo-all/
        build.gradle
        settings.gradle
----

然后，你可以使用 Jmix 工具窗口的 *New -> Subproject...* 新建或添加子项目。我们推荐将子项目放到组合项目的根目录中，与 `<project-name>-all` 同级。

[[code-snippets]]
=== 插入代码段

为了提升开发者体验，Studio 现在提供一个 xref:studio:code-snippets.adoc[代码段] 工具窗。代码段工具窗位于 IDE 的右侧，当在编辑器打开 Java 或 Kotlin 文件时展示。可以直接将代码片段拖放至你的代码中。

代码段依赖程序上下文，有可能需要开发者补充其所需的参数。

所有的代码段模板位于相关框架模块的 `jmix-code-snippets.xml` 文件中。你可以在项目或者扩展组件级别定义自己的代码段：只需要按照框架中文件的示例在项目的 resource 目录创建 `jmix-code-snippets.xml` 即可。

[[jpql-designer]]
=== JPQL 设计器

JPQL 设计器支持定义 JPQL 查询语句，用于从数据库加载实体或值。

目前，只有当使用 *Data -> Load ... by query* 代码段时会自动展示 JPQL 设计器。在经过完整的测试之后，在源码任何位置创建或编辑查询语句时都将可以使用。

NOTE: 此扩展组件需要快速开发版或企业版 https://www.jmix.cn/subscription-plans-and-prices/[订阅^]。

[[breaking-changes]]
== 破坏性改动

[[breaking-duplicated-jmix-module-id]]
=== 处理重复的 JmixModule id

如果你的应用程序在加载上下文时遇到这样的异常：`java.lang.IllegalStateException: Duplicated Jmix module id 'com.company.untitled3' is provided by XConfiguration and YConfiguration. Consider using @JmixModule.id attribute to specify a unique module id.`，需要为异常中列举的某一个配置类指定唯一 `id`:

[source,java,indent=0]
----
@JmixModule(id = "com.company.myapp.test", dependsOn = MyConfiguration.class)
public class MyTestConfiguration {
    ...
}
----

Jmix module id 默认与配置的包名相同。

详情参考 https://github.com/Haulmont/jmix-core/issues/282。

[[breaking-programmatic-search-index-definition-mapping]]
=== 编程式定义搜索索引映射

在搜索扩展组件中，定义索引映射的 API 发生了改动。参考 xref:search:index-definitions.adoc#programmatic-mapping[编程式映射] 部分新 API 的示例。

[[changelog]]
== 变更日志

* Jmix 框架修复的问题：

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.2.4[1.2.4^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.2.3[1.2.3^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.2.2[1.2.2^]
** xref:release_1.2.1.adoc[1.2.1]
** xref:release_1.2.0.adoc[1.2.0]

* Jmix Studio 修复的问题：

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.2.3[1.2.3^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.2.2[1.2.2^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.2.1[1.2.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.2.0,-1.1.*[1.2.0^]
