= Что нового

IMPORTANT: Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Перейдите к разделу xref:studio:project.adoc#upgrading-project[Апгрейд проекта], чтобы узнать, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 7.4.2 в `gradle/wrapper/gradle-wrapper.properties`.
* Переименовывает свойство `jmix.rest.allowed-origins` в `jmix.cors.allowed-origins`.

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.3.3[1.3.3^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.3.2[1.3.2^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.3.1[1.3.1^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.3.0[1.3.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.3.4[1.3.4^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.3.3[1.3.3^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.3.2[1.3.2^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.3.1[1.3.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.3.0,-1.2.*[1.3.0^]