= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA - {minimal-idea-version}.

Автоматическая миграция с Jmix 1.5 на {page-component-display-version} возможна только в том случае, если ваш проект основан на *Flow UI* и использует *JDK 17*.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 8.0.2 в `gradle/wrapper/gradle-wrapper.properties`.
* Заменяет пакеты Java EE на Jakarta EE (`javax` на `jakarta` за некоторыми исключениями).
* Заменяет использование `io.jmix.core.metamodel.datatype.impl.EnumClass` на `io.jmix.core.metamodel.datatype.EnumClass`.
* Заменяет использование `io.jmix.flow ui.kit.component.FlowuiComponentUtils` на `io.jmix.flow ui.kit.component.ComponentUtils`.
* Заменяет использование `javax.annotation.Nullable` на `org.springframework.lang.Nullable`.
* Заменяет свойства приложения, начинающиеся с `jmix.flowui` на `jmix.ui`.
* Заменяет специальное разрешение `flowui.loginToUi` на `ui.loginToUi`.
* В дескрипторах экранов:
** Изменяет элемент `queryParameters` на `urlQueryParameters`.
** Изменяет стандартные типы действий со списком на `list_`.
* Добавляет блок скрипта в файл `index.html`.

См. полный список <<breaking-changes,опасных изменений>>, которые могут затронуть ваш проект после обновления.

[[updated-dependencies]]
== Обновленные зависимости

Обновлены слеудющие важные зависимости:

* Spring Boot 3.1
* Vaadin 24.0
* EclipseLink 4.0
* Flowable 7.0

Для сборки и запуска приложений теперь требуется JDK 17.

Для WAR-развертывания требуется Tomcat 10.

[[new-features]]
== Новая и улучшенная функциональность

[[add-ons-with-flow-ui]]
=== Дополнения с Flow UI

Следующие дополнения теперь доступны в проектах с Flow UI:

* xref:bpm:index.adoc[]
* xref:business-calendar:index.adoc[]
* xref:email:index.adoc[]
* xref:reports:index.adoc[]

[[flow-ui-test-assist]]
=== Flow UI Test Assist

Модуль Flow UI Test Assist был улучшен и теперь поддерживает взаимодействие между экранами. Пример UI-теста для экранов управления пользователями генерируется в новом проекте приложения.

Подробности в тикете https://github.com/jmix-framework/jmix/issues/1467[#1467].

[[generic-filter]]
=== Компонент GenericFilter

Компонент `genericFilter` теперь позволяет создавать конфигурации и собственные условия во время разработки и во время выполнения. Конфигурациями времени выполнения и пользовательскими условиями могут управлять конечные пользователи.

Пример конфигурации времени разработки:

[source,xml]
----
<genericFilter id="genericFilter" dataLoader="usersDl">
    <properties include=".*"/>
    <configurations>
        <configuration id="byEmail" name="By email">
            <propertyFilter operation="CONTAINS" property="email"/>
        </configuration>
    </configurations>
</genericFilter>
----

Чтобы создать конфигурацию во время работы приложения, добавьте несколько условий, а затем сохраните их как конфигурацию, используя меню настроек фильтра (кнопка "шестеренка").

Чтобы создать пользовательское условие, используйте кнопку *Create* в диалоговом окне *Add condition*.

[[codeeditor-component]]
=== Компонент CodeEditor

Новый компонент `codeEditor`, основанный на Ace editor, позволяет пользователям просматривать и редактировать код с подсветкой синтаксиса, автоматическими отступами и другими расширенными функциями. В то же время он обеспечивает декларативную привязку данных с помощью атрибутов `dataContainer` и `property`.

Например:

[source,xml]
----
<codeEditor id="codeEditor" mode="GROOVY"
            dataContainer="taskDc" property="script"/>
----

[[preventing-browser-tab-closing]]
=== Предотвращение закрытия вкладки браузера

Веб-браузер теперь показывает стандартное подтверждение о выходе со страницы, если пользователь закрывает вкладку браузера при отображении экрана деталей сущности. Это предотвращает случайную потерю несохраненных данных.

Чтобы отключить подтверждение для некоторого экрана, вызовите его метод `setPreventBrowserTabClosing()` в обработчике `InitEvent`:

[source,java]
----
@Subscribe
public void onInit(final InitEvent event) {
    setPreventBrowserTabClosing(false);
}
----

[[passing-parameters-in-navigation]]
=== Передача параметров при навигации

Введен новый способ передачи параметров экранам, открываемым с помощью навигации: использование обработчика `AfterViewNavigationEvent`, создаваемого в вызывающем коде. Данный способ позволяет легко передавать сложные типы данных, но параметры не отражаются в URL-адресе и теряются, если пользователь обновляет веб-страницу.

Подробная информация приведена в разделе xref:flow-ui:opening-views.adoc#passing-parameters[Открытие экранов].

[[quick-cloud-deployment]]
=== Быстрое развертывание в облаке

Функциональность xref:studio:quick-cloud-deployment.adoc[быстрого развертывания в облаке] была полностью переработана и теперь доступна по умолчанию в окне инструментов *Jmix*. Она позволяет вам легко развернуть приложение на автоматически создаваемом сервере AWS EC2.

[[beans-in-jmix-tool-window]]
=== Бины в окне инструментов Jmix

В окне инструментов *Jmix* теперь отображаются все бины, определенные в проекте.

Используйте команду *Options* -> *Group by Packages* чтобы переключиться с плоского списка на структурированное представление.

[[bpm-in-jmix-tool-window]]
=== BPM в окне инструментов Jmix

Если ваш проект включает дополнение xref:bpm:index.adoc[BPM], в окне инструментов *Jmix* появляется раздел `BPM`. В этом разделе отображаются BPMN-процессы, черновики процессов и DMN-таблицы из следующих каталогов проекта:

[cols="1,2,1"]
|===
|Подраздел |Каталог |Расширение файлов

|Processes
|`src/main/resources/processes`
|`.bpmn` или `.bpmn20.xml`

|Process Drafts
|`src/main/resources/process-drafts`
|`.draft.bpmn`

|DMN Tables
|`src/main/resources/dmn`
|`.dmn.xml`
|===

При выполнении команды *New* -> *BPMN Process*, Studio создает новый черновик процесса и отображает его в разделе `Process Drafts`. Когда процесс готов, нажмите кнопку *Copy to Processes* в верхней панели действий дизайнера BPM, или используйте контекстное меню в окне инструментов *Jmix*. Studio скопирует черновик в раздел `Processes` и удалит расширение `draft` из имени файла.

Содержимое разделов `Processes` и `DMN Tables` автоматически развертывается на старте приложения.

[[all-beans-in-inject-dialog]]
=== Все бины в диалоге Inject

В диалоговом окне *Inject* теперь отображаются все бины, определенные в classpath проекта, включая те, которые определены в Java-конфигурациях аннотациями `@Bean`.

Когда включена опция группировки на панели инструментов диалогового окна, разделы `Other Beans` и `Other Properties` группируют содержимое по первой части имени пакета, не являющейся TLD (доменом верхнего уровня).

NOTE: Наличие класса в диалоговом окне *Inject* не гарантирует, что компонент будет успешно инжектирован во время выполнения. Это зависит от многих условий, которые не могут быть надежно проанализированы студией во время разработки.

[[using-final-modifier]]
=== Использование модификатора final

Studio теперь использует модификатор `final` для полей, переменных и параметров метода при генерации кода.

Вы можете отключить эту функцию в разделе *Project Settings* на странице настроек плагина *Jmix*.

[[offsetdatetime-for-audit-fields]]
=== OffsetDateTime для полей аудита

Атрибуты сущности, используемые в качестве временных меток в чертах (traits) `Audit of creation`, `Audit of modification` и `Soft Delete`, теперь создаются с типом `OffsetDateTime`. Таким образом, база данных хранит временную метку с указанием часового пояса.

[[invalidating-studio-caches]]
=== Очистка кэшей Studio

Теперь вы можете удалить информацию, сохраненную Studio в https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory[каталоге конфигурации IDE^], без необходимости поиска нужных каталогов и файлов. Очистка может помочь, если у вас возникли проблемы с шаблонами проектов, созданием экранов или с дизайнером экранов.

Выполните команду *File* -> *Invalidate Caches*, выберите флажок *Delete Jmix Studio templates and artifacts caches* и нажмите *Invalidate and Restart*.

[[breaking-changes]]
== Опасные изменения

[[renamed-classes-and-properties]]
=== Переименованные свойства и классы

. Префикс `jmix.flowui` свойств приложения изменен на `jmix.ui`. footnote:studio-migrator[Процедура миграции Studio производит необходимые изменения в вашем проекте автоматически.]

. Переименованы специальные политики безопасности:

* `datatools.flowui.showEntityInfo` > `datatools.showEntityInfo`
* `flowui.loginToUi` > `ui.loginToUi` footnote:studio-migrator[]
* `flowui.showExceptionDetails` > `ui.showExceptionDetails`
* `flowui.filter.modifyJpqlCondition` > `ui.genericfilter.modifyJpqlCondition`
* `flowui.filter.modifyConfiguration` > `ui.genericfilter.modifyConfiguration`
* `flowui.genericfilter.modifyGlobalConfiguration` > `ui.genericfilter.modifyGlobalConfiguration`

. Базовый класс `io.jmix.core.metamodel.datatype.impl.EnumClass` перемещен в пакет `io.jmix.core.metamodel.datatype`. footnote:studio-migrator[]

. Фасет `queryParameters` переименован в `urlQueryParameters`. footnote:studio-migrator[]

. Префикс `list_` добавлен к именам типов стандартных действий списка. footnote:studio-migrator[]

. Переименованы типы действий:

* `excelExport` -> `grdexp_excelExport`
* `showRoleAssignments` -> `sec_showRoleAssignments`
* `showRoleAssignments` -> `sec_showRoleAssignments`
* `resetPassword` -> `sec_resetPassword`

. Во всех классах фреймворка, за исключением конфигураций и авто-конфигураций Spring, префикс `Flowui` удален или заменен на `Ui`. Использование класса `io.jmix.flowui.kit.component.FlowuiComponentUtils` автоматически заменяется на `ComponentUtils` процедурой миграции Studio. Если в вашем проекте используются другие классы с префиксом `Flowui`, измените имена классов вручную. Детальная информация об изменениях в тикете https://github.com/jmix-framework/jmix/issues/1830[#1830^].

[[removed-features]]
=== Удаленная функциональность

. Удалены методы интерфейса `Actions`, создающие действие по его классу. Замените данные методы методами создания действий по их строковым идентификаторам. Подробнее см. тикет https://github.com/jmix-framework/jmix/issues/1529[#1529^].

. Поддержка xref:flow-ui:vc/components/tooltip.adoc[] удалена из следующий UI компонентов: `ComboButton`, `DropdownButton`, `SimplePagination`, `UserIndicator`.

. Удален класс `UiLoginProperties`, объявленный устаревшим в Jmix 1.5. Если вы создавали проект еще на Jmix 1.4, данный класс используется в вашем LoginView, поэтому вам необходимо изменить класс LoginView и его XML-дескриптор на те, которые предоставляются шаблоном создания проекта в Jmix 2.0.

. Jmix BOM более не описывает зависимость `commons-fileupload:commons-fileupload`.

. Удалено свойство `jmix.rest.max-upload-size`. Вместо него используйте свойство `spring.servlet.multipart.max-file-size` и другие из {spring-boot-api}/org/springframework/boot/autoconfigure/web/servlet/MultipartProperties.html[MultipartProperties^]. Подробнее см. тикет https://github.com/jmix-framework/jmix/issues/1496[#1496^].

[[data-repositories-initialization]]
=== Инициализация репозиториев данных

Опциональная ранее аннотация `@EnableJmixDataRepositories` теперь обязательна для инициализации xref:data-access:data-repositories.adoc[репозиториев данных] в проекте. Подробнее см. тикет https://github.com/jmix-framework/jmix/issues/1589[#1589^].

[[rounding-in-datatypes]]
=== Округление в Datatype

Реализации интерфейса xref:data-model:data-types.adoc[Datatype] для типов `BigDecimal`, `Double` и `Float` теперь округляют значения в соответствии с указанными для них форматами при парсинге из строк. Например, строка `"12.3456"` становится числом `12.35`, если установлен формат `++#.##++`.

Чтобы вернуть предыдущее поведение, установите свойство `jmix.core.round-decimal-value-by-format` в false. Подробности в тикете https://github.com/jmix-framework/jmix/issues/968[#968^].

[[bean-validation-on-persistence-layer]]
=== Bean Validation на уровне персистенции

Bean validation на уровне персистенции теперь включено по умолчанию. Это означает, что при сохранении сущности через `DataManager`, `EntityManager` или репозитории данных, она будет провалидирована и если ее состояние невалидно, будет выброшено исключение.

Bean validation на уровне персистенции можно отключить путем установки следующего свойства приложения:

[source,properties]
----
jakarta.persistence.validation.mode = NONE
----

[[generic-rest-access-control]]
=== Контроль доступа в Generic REST

Дополнение Универсальный REST теперь использует Jmix Authorization Server для получения токенов доступа. Подробная информация приведена в разделе xref:rest:access-control.adoc[].

Если в вашем проекте используется Универсальный REST, необходимо выполнить следующее:

* Заменить зависимость `io.jmix.security:jmix-security-oauth2-starter` на `io.jmix.authserver:jmix-authserver-starter`.
* Сконфигурировать Client Credentials или Authorization Code грант в приложении.
* Адаптировать клиентов вашего REST к новому методу получения токенов доступа.

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.0.0[2.0.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.0.1[2.0.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.0.0,-1.5.*%20Affected%20versions:%20-SNAPSHOT%20[2.0.0^]
