= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

*THIS PAGE IS WORK IN PROGRESS*

[[upgrade]]
== How To Upgrade

IMPORTANT: To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

NOTE: While there is no final Studio 1.2 release, please use the xref:studio:install.adoc#nightly[nightly builds].

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates the version of Gradle wrapper to 7.4 in `gradle/wrapper/gradle-wrapper.properties`.

[[new-features]]
== New Features

[[business-calendar]]
=== Business Calendar Add-on

The add-on allows you to manage business calendars containing holidays, scheduled and additional business days. Configured business calendars provide API to work with working dates and times.

At the moment the add-on is not yet published on Marketplace, but you can install it by adding the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::business-calendar:example$ex1/build.gradle[tags=dependencies]
----

NOTE: This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^].

See the xref:business-calendar:index.adoc[] section for more details.

[[notifications]]
=== Notifications Add-on

The add-on allows you to create and send notifications to users via various message channels. Users can receive notifications about events in the system, simple informational messages, as well as notifications from business processes.

At the moment the add-on is not yet published on Marketplace, but you can install it by adding the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::notifications:example$ex1/build.gradle[tags=dependencies]
----

NOTE: This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^].

See the xref:notifications:index.adoc[] section for more details.

[[oidc]]
=== OpenID Connect Add-on

The OpenID Connect add-on provides predefined Spring Security configurations and a set of services that simplifies the following operations:

* User authentication using an external OpenID Provider (e.g., Keycloak).
* Mapping of user attributes and roles from OpenID Provider user to Jmix user.
* Persisting user entity and role assignments after the user is successfully authenticated at OpenID Provider.

At the moment the add-on is not yet published on Marketplace, but you can install it by adding the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.oidc:jmix-oidc-starter'
----

See https://github.com/Haulmont/jmix-oidc[README^] in the add-on source repository for more details.

[[quartz]]
=== Quartz Add-on

This add-on allows you to manage https://www.quartz-scheduler.org/[Quartz^] jobs via user interface:

* Create new Quartz jobs from the existing implementation of `org.quartz.Job` interface.
* Pause and resume jobs execution.
* Trigger immediate execution of inactive jobs.
* Edit job triggers and parameters.
* Delete jobs.

At the moment the add-on is not yet published on Marketplace, but you can install it by adding the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.quartz:jmix-quartz-starter'
----

To create and schedule a job for execution, do the following:

. Create a class implementing the `org.quartz.Job` interface. It's `execute()` method will be invoked by the scheduler.

. Run the application, open *Administration -> Quartz jobs* screen, click *Create* and find your job class in the *Class* field. After that, create triggers for the job.

The complete documentation for the add-on is coming soon.

[[appplication-settings]]
=== Application Settings Add-on

The Application Settings add-on provides a simple API and UI to work with mutable values of different types stored in database. These values are usually used as parameters of different functionality of the application.

At the moment the add-on is not yet published on Marketplace, but you can install it by adding the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.appsettings:jmix-appsettings-starter'
implementation 'io.jmix.appsettings:jmix-appsettings-ui-starter'
----

To define some settings, create an entity extending the `io.jmix.appsettings.entity.AppSettingsEntity` class:

[source,java]
----
@JmixEntity
@Table(name = "CUSTOMER_SETTINGS")
@Entity
public class CustomerSettings extends AppSettingsEntity {

    @Column(name = "NOTIFICATION_TEXT")
    private String notificationText;

    @AppSettingsDefault("B")
    @Column(name = "DEFAULT_GRADE")
    private String defaultGrade;

    // getters and setters
}
----

After that, you will be able to set values for this entity attributes using the *Administration -> Application settings* screen.

To get settings in the application code, use the `AppSettings` bean, for example:

[source,java,indent=0]
----
@Autowired
private AppSettings appSettings;

@Subscribe
public void onInitEntity(InitEntityEvent<Customer> event) {
    Customer customer = event.getEntity();
    CustomerGrade defaultGrade = appSettings.load(CustomerSettings.class).getDefaultGrade();
    customer.setGrade(defaultGrade);
}
----

The complete documentation for the add-on is coming soon.

[[composite-projects]]
=== Composite Projects

Now Studio allows you to develop multiple add-ons and applications as a single IDE project, even if they are located in different source code repositories.

To create a composite project, start the project wizard and select the Jmix version `1.2.0-RC1` or newer and *Composite Project* template. Studio will create a project with the following structure (provided that the project name is `demo`):

----
root-dir/
    demo-all/
        build.gradle
        settings.gradle
----

After that, you can create or add subprojects using the *New -> Subproject...* actions of the Jmix tool window. We recommend placing subprojects inside the project root next to the `<project-name>-all` aggregator project.

[[code-snippets]]
=== Code Snippets

To improve developer experience, Studio now offers a palette of code snippets. The palette of snippets is displayed in the Code Snippets tool window, which is available on the right side of the IDE when a Java or Kotlin file is opened in the editor. You can drag and drop snippets from the palette to your code.

The snippets are context-dependent and may request parameters from the developer.

All code snippet templates are located in `jmix-code-snippets.xml` files inside the relevant framework modules. You can define your own snippets on the project or an add-on level: just create a `jmix-code-snippets.xml` file in the project's resources using an example from the framework.

[[jpql-designer]]
=== JPQL Designer

The JPQL designer allows you to define JPQL queries for loading entities and scalar values from the database.

At the moment, the JPQL designer is opened automatically when you use the *Data -> Load ... by query* code snippets. After thorough testing, we'll make it available also for creating and editing queries everywhere in your source code.

NOTE: The JPQL designer requires the RAD or Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^].


[[breaking-changes]]
== Breaking Changes

[[breaking-duplicated-jmix-module-id]]
=== Handling of duplicated JmixModule id

If you get an exception like `java.lang.IllegalStateException: Duplicated Jmix module id 'com.company.untitled3' is provided by XConfiguration and YConfiguration. Consider using @JmixModule.id attribute to specify a unique module id.` on context load, specify a unique `id` for one of the configurations:

[source,java,indent=0]
----
@JmixModule(id = "com.company.myapp.test", dependsOn = MyConfiguration.class)
public class MyTestConfiguration {
----

By default, Jmix module's id is equal to the package of the configuration class.

See details at https://github.com/Haulmont/jmix-core/issues/282.

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/issues?q=is%3Aissue+user%3AHaulmont+milestone%3A1.2.0[1.2.0^] (requires login to GitHub)

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.2.0,-1.1.*[1.2.0^]