= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates the version of Gradle wrapper to 8.8 in `gradle/wrapper/gradle-wrapper.properties`.
* If the project includes the REST API add-on, adds the `jmix.resource-server.authenticated-url-patterns` property, see details <<protecting-generic-rest-endpoints,below>>.
* Replaces calls to `dateTimeParameter()`, `dateParameter()` and `timeParameter()` methods of input dialog builder with calls to `localDateTimeParameter()`, `localDateParameter()` and `localTimeParameter()`. See details <<input-dialog-date-parameters,below>>.
* Adds the Grid Export Actions add-on to the project if it includes the Data Tools add-on. See details <<grid-export-actions-add-on-dependency,below>>.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes[3.3^].

* Vaadin https://github.com/vaadin/platform/releases/tag/24.4.0[24.4^].

[[new-features]]
== New Features and Improvements

[[advanced-endpoints-security-configuration]]
=== Advanced Endpoints Security Configuration

More options have been introduced for configuring endpoints security when using Authorization Server or OpenID Connect add-ons:

* `jmix.resource-server.authenticated-url-patterns` and `jmix.resource-server.anonymous-url-patterns` properties
* `AuthenticatedUrlPatternsProvider` and `AnonymousUrlPatternsProvider`
* `AuthenticatedRequestMatcherProvider` and `AnonymousRequestMatcherProvider`

See xref:security:custom-endpoints.adoc#token-based-authentication[Token Based Authentication] for more information.

The old `AuthorizedUrlsProvider` is deprecated, but still works, as well as `jmix.rest.authenticated-url-patterns` and `jmix.rest.anonymous-url-patterns` properties. It is recommended to move the configuration to the new interfaces or properties.

[[breaking-changes]]
== Breaking Changes

[[protecting-generic-rest-endpoints]]
=== Protecting Generic REST Endpoints

Due to improvements in endpoints security configuration (see <<advanced-endpoints-security-configuration,above>>), the following application property must be set to secure the Generic REST API endpoints:

[source,properties]
----
jmix.resource-server.authenticated-url-patterns = /rest/**
----

The Studio migration procedure adds it to `application.properties` automatically.

[[listmenu-styles]]
=== ListMenu Styles

xref:flow-ui:vc/components/listMenu.adoc[] component styles have been changed to fix the issue with focus ring:

- Changed margin and padding for the `ListMenu` itself.
- Increased `margin-inline-start` for list of sub menu.
- Changed paddings for `MenuBarItem`.

If you have defined your own styles for this component, you may need to adjust them.

See https://github.com/jmix-framework/jmix/issues/3589[#3589^] for more information.

[[input-dialog-date-parameters]]
=== Input Dialog Date Parameters

The `dateTimeParameter()`, `dateParameter()` and `timeParameter()` methods of the xref:flow-ui:dialogs.adoc#input-dialog[input dialog] builder have been fixed: now they create parameters of `java.util.Date`, `java.sql.Date` and `java.sql.Time` type respectively. Previously they wrongly created `LocalDateTime`, `LocalDate` and `LocalTime` parameters.

See https://github.com/jmix-framework/jmix/issues/3499[#3499^] for more information.

The Studio migration procedure automatically replaces calls to these methods with calls to `localDateTimeParameter()`, `localDateParameter()` and `localTimeParameter()` to keep compatibility with returning values.

[[grid-export-actions-add-on-dependency]]
=== Grid Export Actions Add-on Dependency

Previously, the xref:data-tools:index.adoc[] add-on contained transitive dependency to the xref:grid-export:index.adoc[] add-on. This dependency has been removed, so now export actions can be used only when the Grid Export Actions add-on is included explicitly.

The Studio migration procedure automatically adds the Grid Export Actions add-on to the project if it includes the Data Tools add-on.

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.0[2.4.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.0,-2.3.*%20Affected%20versions:%20-SNAPSHOT[2.4.0^]
