= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates the version of Gradle wrapper to 8.6 in `gradle/wrapper/gradle-wrapper.properties`.
* In Kotlin projects, updates the version of Kotlin plugin to 1.9.22.
* Due to relocation of the <<pessimistic-locking, pessimistic locking>> feature, replaces usages of `io.jmix.core.pessimisticlocking` package with `io.jmix.pessimisticlock`, replaces `jmix.core.pessimistic-lock.\*` application properties with `jmix.pslock.\*` and adds dependencies to the new add-on to `build.gradle`.
* Adds `jmix.ui.view.prevent-browser-tab-closing = true` application property. See <<browser-tab-closing-prevention,below>> for more information.
* Adds `spring.main.allow-circular-references = true` application property. See <<circular-dependencies-between-spring-beans,below>> for more information.
* Adds `jmix.core.skip-null-or-empty-conditions-by-default = true` application property. See <<handling-empty-conditions,below>> for more information.
* Adds `jmix.appsettings.check-permissions-for-app-settings-entity = true` application property if the project includes the Application Settings add-on. See <<security-in-application-settings,below>> for more information.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot 3.2. See its https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes[release notes^] for more information.

* Vaadin 24.3. See release notes for Vaadin https://github.com/vaadin/platform/releases/tag/24.2.0[24.2^] and https://github.com/vaadin/platform/releases/tag/24.3.0[24.3^] for more information. Studio removes the `.pnpmfile.cjs` file from your project when migrating it to Jmix 2.2 (because of https://github.com/vaadin/flow/issues/17873[vaadin/flow#17873^]). Make sure this file doesn't exist after migration.

[[new-features]]
== New Features and Improvements

[[java-21]]
=== Support for Java 21

You can now use Java 21 and all its language features to write your applications.

The framework is still built using Java 17, so both Java 17 and 21 are available for application projects.

[[charts-add-on]]
=== Charts Add-on

The new Charts add-on integrates the https://echarts.apache.org[Apache ECharts^] JavaScript library into Jmix UI.

See the xref:charts:index.adoc[Charts documentation] and issue https://github.com/jmix-framework/jmix/issues/2437#issuecomment-1926905380[#2437^] for more information.

[[maps-improvements]]
=== Maps Improvements

* Added support for clustering and heatmaps. See xref:maps:high-density-data-visualization.adoc[].

* Added support for MultiPoint, MultiPolygon and MultiLineString. See https://github.com/jmix-framework/jmix/issues/2807#issuecomment-1919332115[#2807^].

[[bpm-improvements]]
=== BPM Improvements

* The BPM form wizard in Studio now supports creating forms for Start events and using entity instances instead of process variables. See the *Form template* and *Form type* dropdowns on the first step of the wizard.

* The *Async* flag can be set for service tasks in the Studio BPMN designer.

* Business process definitions developed in Studio can now be deployed to the running application. Use the *Hot Deploy Process* button in the top panel of the BPMN designer in Studio.

* The runtime BPM modeler now provides support for the `flowable:failedJobRetryTimeCycle` element. See the *Failed job retry time cycle* property when a service task is selected.

* The runtime BPM modeler now allows you to select existing process variables for bean arguments from dropdowns.

[[rich-text-editor]]
=== RichTextEditor Component

The new `richTextEditor` component integrates the https://quilljs.com[Quill^] JavaScript library into Jmix UI. It's available in the standard  *Add component* palette.

[[horizontal-main-menu]]
=== Horizontal Main Menu

The new `horizontalMenu` component allows you to create a main view with a horizontal menu.

The new *Main view with top menu* template is available in the view creation wizard. If you want to use the new view instead of the existing main view, select the *Use as default main view* checkbox on the first step of the wizard. Then Studio will replace the `layout` attribute of the `@Route` annotation in all views and set the new view in the `jmix.ui.main-view-id` application property.

See https://github.com/jmix-framework/jmix/issues/2492#issuecomment-1855606091[#2492^] for more information.

[[filtering-main-menu]]
=== Filtering Main Menu

The new `menuFilterField` component allows users to filter main menu items. It's available in the standard  *Add component* palette.

The `menu` attribute should point to a `listMenu` component to be filtered:

[source,xml,indent=0]
----
<menuFilterField menu="menu"
                 placeholder="Search..." classNames="ms-s me-s"/>
<nav id="navigation" classNames="jmix-main-view-navigation" ariaLabel="msg://navigation.ariaLabel">
    <listMenu id="menu"/>
</nav>
----

Please note that filtering of <<horizontal-main-menu>> is not supported.

[[initial-layout-in-main-view]]
=== Initial Layout in Main View

Now you can declaratively define an initial layout that will be shown when no views are opened in the main view. Use the `initialLayout` element of the `appLayout` component:

[source,xml]
----
<appLayout>
    <navigationBar .../>
    <drawerLayout .../>
    <initialLayout>
        <h2 text="Hello world!"/>
    </initialLayout>
</appLayout>
----

See https://github.com/jmix-framework/jmix/issues/2213[#2213^] for more information.

[[data-grid-enhancements]]
=== Data Grid Improvements

[[data-grid-handling-double-click]]
==== Handling Double-Click

The xref:flow-ui:vc/components/dataGrid.adoc[] component now handles double-click in list views: it either opens a detail view or, in lookup mode, finishes the selection. See https://github.com/jmix-framework/jmix/issues/2582[#2582^] for more information.

[[data-grid-url-parameters-for-filterin-column-headers]]
==== URL Parameters for Filter in Column Headers

The xref:flow-ui:vc/components/dataGrid.adoc[] column header filter can now be reflected in URL to provide a deep link and to save the view state when navigating to a detail view and back.

Use the `dataGridFilter` element of the xref:flow-ui:facets/urlQueryParameters.adoc[] facet, pointing to the data grid:

[source,xml,indent=0]
----
<facets>
    <urlQueryParameters>
        <dataGridFilter component="usersDataGrid"/>
    </urlQueryParameters>
</facets>
<layout>
    <dataGrid id="usersDataGrid" dataContainer="usersDc">
        <columns>
            <column property="username" filterable="true" resizable="false" autoWidth="true"/>
----

[[data-grid-column-visibility-control]]
==== Column Visibility Control

The new `gridColumnVisibility` component allows users to hide and show columns of a data grid. It consists of a button and a dropdown menu with the list of columns.

Usage example:

[source,xml,indent=0]
----
<hbox id="buttonsPanel" classNames="buttons-panel">
    <!-- ... -->
    <gridColumnVisibility icon="COG" themeNames="icon"
                          dataGrid="usersDataGrid" exclude="picture"/>
</hbox>
<dataGrid id="usersDataGrid" dataContainer="usersDc">
    <columns resizable="true">
        <column key="picture" sortable="false" flexGrow="0" resizable="false"/>
        <column property="username"/>
        <column property="firstName"/>
----

[[collection-properties-in-generic-filter]]
=== Collection Properties in Generic Filter

The xref:flow-ui:vc/components/genericFilter.adoc[] component now allows you to create conditions for collection (to-many) properties.

For example, in the xref:tutorial:index.adoc#data-model[Onboarding application], you can filter Users by the `steps` property and its nested properties: `steps.dueDate`, `steps.step.name`, etc. The JPA data store will automatically create an appropriate JPQL query with the `join` clause. Previously, you could achieve this only by defining a xref:flow-ui:vc/components/genericFilter.adoc#jpql-conditions[JPQL condition] manually.

See https://github.com/jmix-framework/jmix/issues/518#issuecomment-1860205607[#518^] for more information.

[[sending-events-to-all-user-sessions]]
=== Sending Events to All User Sessions

The `UiEventPublisher` bean now has the `publishEventForUsers()` method that accepts an application event instance and a collection of usernames. This method allows you to send events to user session of particular users, regardless of whether they are connected to the same server or a different server within the cluster.

Example of sending an event to `alice`:

[source,java,indent=0]
----
public class DepartmentListView extends StandardListView<Department> {
    @Autowired
    private UiEventPublisher uiEventPublisher;

    @Subscribe(id = "sendEventBtn", subject = "clickListener")
    public void onSendEventBtnClick(final ClickEvent<JmixButton> event) {
        uiEventPublisher.publishEventForUsers(new MyUiEvent(this), List.of("alice"));
    }

    public static class MyUiEvent extends ApplicationEvent {

        public MyUiEvent(Object source) {
            super(source);
        }
    }
}
----

Example of an event listener:

[source,java,indent=0]
----
public class MainView extends StandardMainView {
    @Autowired
    private Notifications notifications;

    @EventListener
    public void onMyUiEvent(DepartmentListView.MyUiEvent event) {
        notifications.show("Event received");
    }
}
----

If the second argument of the `publishEventForUsers()` method is null, the event is sent to all connected users.

See https://github.com/jmix-framework/jmix/issues/1235#issuecomment-1820550454[#1235^] for more information.

[[improved-save-performance]]
=== Improved Save Performance

Now edited entity is not reloaded by default after save-and-close action if the detail view was opened by navigation, because in this case the list view reloads the whole list anyway. It improves the performance for complex views that load and save large object graphs.

You can control the reloading of saved instances explicitly using the `setReloadSaved()` method of the `DetailView` interface, for example:

[source,java]
----
@Subscribe
public void onInit(final InitEvent event) {
    setReloadSaved(true);
}
----

See <<detailview-and-datacontext-interfaces,potentially breaking changes>> and https://github.com/jmix-framework/jmix/issues/1725[#1725^] for more information.


[[reduced-build-time]]
=== Reduced Build Time

The build process now skips enhancing entities if they have not been modified since the last build, which significantly reduces build time for projects with a large data model.

For example, if you have built your project, then you modify a view controller and build again, you should see the following message in the console: `Entities enhancing was skipped, because entity classes haven't been changed since the last build`.

To disable this behavior and enhance all entities on each compilation, add the following configuration to `build.gradle`:

[source,groovy]
----
jmix {
    entitiesEnhancing {
        skipUnmodifiedEntitiesEnhancing = false
    }
}
----

[[studio-improvements]]
=== Studio Improvements

[IMPORTANT]
====
Since Jmix Studio 2.2, the premium RAD features are available without an active subscription in small projects with up to 10 entities and roles.
====

[[code-snippets]]
==== Code Snippets

New xref:studio:code-snippets.adoc[code snippets] are available in Studio for xref:bpm:index.adoc[BPM], xref:reports:index.adoc[Reports], xref:notifications:index.adoc[Notifications] and xref:email:index.adoc[Email sending] functionality if the corresponding add-ons are included in your project.

[[adding-components-using-wizards]]
==== Adding Components Using Wizards

The *Add Component* action of xref:studio:view-designer.adoc[] now has two tabs:

* *From Palette* tab shows the component palette as before;

* *Using Wizard* tab contains wizards that help solving complex tasks related to UI. For example, the *Edit entity attributes* wizard creates a `formLayout` with fields for selected entity attributes and a data container with a proper fetch plan.
+
The list of wizards is sensitive to the current view contents: for example, if the view already contains a `dataGrid`, the *Add column to DataGrid* wizard is available.

[[link-to-ui-component-documentation]]
==== Link to UI Component Documentation

The inspector panel of the Jmix UI tool window now shows a link to the documentation on the selected UI component. See the question mark icon next to the component type.

The same link is available as the *Jmix Documentation* item in the component hierarchy context menu.

[[test-scaffolding]]
==== Test Scaffolding

Studio now shows the *Tests* item in the Jmix tool window. Double-click on this item opens the *Project* tree in the `src/test/java` folder.

The *New -> Advanced -> Integration Test* and *New -> Advanced -> UI Integration Test*  actions allow you to quickly create test classes for testing xref:testing:integration-tests.adoc[business logic] and xref:testing:ui-integration-tests.adoc[views].

[[breaking-changes]]
== Breaking Changes

[[browser-tab-closing-prevention]]
=== Browser Tab Closing Prevention

The feature that prevents accidental browser tab closing https://docs.jmix.io/jmix/2.0/whats-new/index.html#preventing-browser-tab-closing[introduced^] in Release 2.0 is now off by default. You can turn it on for a particular view using the `setPreventBrowserTabClosing(true)` method or globally for the application using the following application property:

[source,properties]
----
jmix.ui.view.prevent-browser-tab-closing = true
----

[[circular-dependencies-between-spring-beans]]
=== Circular Dependencies Between Spring Beans

Previously, circular dependencies between Spring beans were enabled by Jmix on the framework level.

Jmix 2.2 doesn't have circular dependencies itself anymore and doesn't enable them in application projects by default.

There is a chance that your project contains circular dependencies between its Spring beans, therefore the Studio migration procedure automatically adds the following property to the project:

[source,properties]
----
spring.main.allow-circular-references = true
----

We recommend you to remove this property and try to start the application. If it fails to initialize, either refactor your beans to eliminate circular dependencies, or return the property.

See https://github.com/jmix-framework/jmix/issues/287[#287^] for more information.

[[handling-empty-conditions]]
=== Handling Empty Conditions

Previously, a xref:data-access:data-manager.adoc#load-by-conditions[property condition] evaluated to true if its parameter value was empty (null, empty string or empty collection).

Since Jmix 2.2, the null or empty parameters do not lead to skipping  conditions. For example, consider the following code:

[source,java]
----
dataManager.load(User.class)
    .condition(PropertyCondition.contains("email", null))
    .list();
----

In Jmix 2.1 and earlier, it executes the following SQL:

[source,sql]
----
SELECT ID, ACTIVE, EMAIL, <...> FROM USER_
----

In Jmix 2.2, by default it executes the following SQL and passes `null` as a parameter:

[source,sql]
----
SELECT ID, ACTIVE, EMAIL, <...> FROM USER_ WHERE EMAIL LIKE ?
----

As a result, in Jmix 2.1 the whole list of users is returned, while in Jmix 2.2 the result list is empty.

If you want to return the previous behavior, set the following application property:

[source,properties]
----
jmix.core.skip-null-or-empty-conditions-by-default = true
----

The Studio migration procedure automatically adds this property to your project.

Alternatively, you can skip empty parameters for particular conditions:

[source,java]
----
dataManager.load(User.class)
    .condition(PropertyCondition.contains("email", null).skipNullOrEmpty())
    .list();
----

See https://github.com/jmix-framework/jmix/issues/2490[#2490^] for more information.

[[noResultException]]
=== NoResultException

`io.jmix.core.NoResultException` is now thrown instead of `java.lang.IllegalStateException` if the `one()` method of DataManager's fluent xref:data-access:data-manager.adoc#load-by-id[loading API] returns no results. See https://github.com/jmix-framework/jmix/issues/2682[#2682^].

[[pessimistic-locking]]
=== Pessimistic Locking

The pessimistic locking feature has been extracted to the xref:pessimistic-lock:index.adoc[add-on].

The `io.jmix.core.pessimisticlocking` package has been renamed to `io.jmix.pessimisticlocking`.

Changed the following properties:

* `jmix.core.pessimistic-lock.use-default-quartz-configuration` -> `jmix.pslock.use-default-quartz-configuration`
* `jmix.core.pessimistic-lock.expiration-cron` -> `jmix.pslock.expiration-cron`

The Studio migration procedure automatically adds dependencies to your `build.gradle` and changes the imports and property names.

See https://github.com/jmix-framework/jmix/issues/1958#issuecomment-1792291873[#1958^] for more information.

[[validation-in-file-upload-fields]]
=== Validation in File Upload Fields

The `isInvalid()` method of xref:flow-ui:vc/components/fileUploadField.adoc[] and xref:flow-ui:vc/components/fileStorageUploadField.adoc[] does not trigger validation anymore. It only checks invalid state of the field. See https://github.com/jmix-framework/jmix/issues/2821[#2821^].

[[action-shortcuts]]
=== Action Shortcuts

Keyboard shortcuts of actions assigned to components like xref:flow-ui:vc/components/button.adoc[] or xref:flow-ui:vc/components/dataGrid.adoc[] are now handled differently. See https://github.com/jmix-framework/jmix/issues/1758#issuecomment-1859722867[#1758^] for more information.

[[security-in-application-settings]]
=== Security in Application Settings

The xref:appsettings:index.adoc[] add-on now doesn't require to add security permissions to `AppSettingsEntity` entity to work with settings through the `AppSettings` bean.

If you want to return the previous behavior, set the following application property:

[source,properties]
----
jmix.appsettings.check-permissions-for-app-settings-entity = true
----

The Studio migration procedure automatically adds this property to your project.

See https://github.com/jmix-framework/jmix/issues/2710[#2710^] for more information.

[[security-views]]
=== Security Views

The layout of the standard security views for resource and row-level roles has been changed for better usability, see https://github.com/jmix-framework/jmix/issues/2519[#2519^].

If you have extended these views, you may have to modify your code.

[[detailview-and-datacontext-interfaces]]
=== DetailView and DataContext Interfaces

The following methods have been added as part of the <<improved-save-performance,detail view save performance improvement>>:

* `DataContext.save(boolean reloadSaved)`
* `DetailView.isReloadSaved()`
* `DetailView.setReloadSaved(boolean reloadSaved)`

You may need to modify your code if you directly implemented these interfaces.

Also, `DataContext.PostSaveEvent.getSavedInstances()` method returns an empty collection if the entities were not reloaded. It can be checked using the new `DataContext.PostSaveEvent.isEntitiesReloaded()` method.

[[dto-entities-in-standard-views]]
=== DTO Entities in Standard Views

The framework now doesn't make any difference between JPA and DTO entities when navigating to a detail view: it passes the entity ID in the route parameter. The detail view for DTO entity is supposed to get this ID and load the entity instance from some data storage using the load delegate. If the `"new"` constant is passed instead of ID, the view creates a new instance.

If the whole entity instance is passed instead of ID (e.g. when opening in a dialog window), `EntityStates.isNew()` is used to distinguish between Edit and Create mode. Consequently, it's important to set the entity in the not-new state after loading it from a storage. For a DTO entity it can be done using the new `EntityStates.setNew()` method, for JPA entity it's done by the standard JPA data store implementation.

If the edited entity should not be reloaded from the data storage before setting to the data container, call `setReloadEdited(false)` in the detail view constructor or the `InitEvent` handler. This is the case for DTO entities existing purely in memory and not mapped directly to external data.

See https://github.com/jmix-framework/jmix/issues/2788#issuecomment-1926273160[#2788^] for more information and recommendations and the https://github.com/jmix-framework/jmix-samples-2/tree/main/external-data-sample#readme[External Data Sample^] project for example code.

[[maps-api]]
=== Maps API

The following changes have been made in the xref:maps:index.adoc[] add-on:

* `io.jmix.mapsflowui.kit.component.model.style.text.Padding` has been moved to `io.jmix.mapsflowui.kit.component.model` package. See https://github.com/jmix-framework/jmix/issues/2822[#2822^].
* The `addStyles()` method of the `Feature`, `PointFeature`, `MarkerFeature`, `LineStringFeature`, `PolygonFeature` classes now returns `void`. Use `withStyles()` instead if you need the current instance of the feature. See https://github.com/jmix-framework/jmix/issues/2807[#2807^].
* In the `VectorLayer` class, the `addStyles()` method now returns `void`. Use `withStyles()` instead if you need the current instance of the layer. Renamed methods: `isDeclutter()` -> `getDeclutter()`, `isUpdateWhileAnimating()` -> `getUpdateWhileAnimating()`. See https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* In the `ClusterSource` class, the `addPointStyles()` method now returns `void`. Use `withPointStyles()` instead if you need the current instance of the source. See https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* In the `Layer` class, the `isVisible()` method is renamed to `getVisible()`. See https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* The type of zoom properties in `VectorLayer`, `TileLayer`, `ImageLayer` and `GeoMapView` has been changed from `Integer` to `Double`. See https://github.com/jmix-framework/jmix/issues/2701[#2701^].

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.2.1[2.2.1^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.2.0[2.2.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.2.2[2.2.2^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.2.1[2.2.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.2.0,-2.1.*%20Affected%20versions:%20-SNAPSHOT[2.2.0^]
