= 最近更新

本章节包含 Jmix 框架 {page-component-display-version} 的新功能介绍，以及在升级框架版本时需要注意的一些破坏性改动。

并没有与版本 {page-component-display-version} 对应的 Studio。我们建议直接使用 Studio 的最新版： https://docs.jmix.cn/jmix/studio/install.html[Studio 2.x^]。

[[upgrade]]
== 如何升级

[IMPORTANT]
====
如需新建 Jmix {page-component-display-version} 项目或者升级已有项目，需要使用 Studio 2.3 以上版本。因此，请先 xref:studio:update.adoc[升级] Jmix Studio 插件。

Studio 2.3 要求 IntelliJ IDEA 的最低版本是 2023.3。
====

参阅 xref:studio:project.adoc#upgrading-project[升级项目] 部分的介绍了解如何使用 Studio 升级项目。自动升级迁移过程会对项目做如下修改：

* 升级 Jmix BOM 的版本，BOM 又定义了所有依赖的版本。
* 升级 Jmix Gradle 插件的版本。
* 在 `gradle/wrapper/gradle-wrapper.properties` 文件中升级 Gradle wrapper 的版本至 8.0.2。

请参考破坏性改动的 <<breaking-changes,完整列表>>，并在升级后做相应修复。

[[updated-dependencies]]
== 更新的依赖

[source]
----
ch.qos.logback:logback-classic:1.2.13
ch.qos.logback:logback-core:1.2.13
com.fasterxml.jackson.core:jackson-core:2.16.1
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.16.1
com.fasterxml.woodstox:woodstox-core:6.5.1
com.google.guava:guava:33.1.0-jre
com.google.gwt:gwt-dev:2.10.0
com.google.protobuf:protobuf-java:3.21.12
com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:20220608.1
com.hazelcast:hazelcast:5.3.6
com.ibm.icu:icu4j:74.2
com.jayway.jsonpath:json-path:2.9.0
com.nimbusds:nimbus-jose-jwt:9.37.3
com.nimbusds:oauth2-oidc-sdk:9.43.4
com.opencsv:opencsv:5.9
com.thoughtworks.xstream:xstream:1.4.20
commons-io:commons-io:2.15.1
net.sf.jasperreports:jasperreports-fonts:6.20.6
net.sf.jasperreports:jasperreports:6.20.6
org.apache.commons:commons-compress:1.26.0
org.apache.james:apache-mime4j-core:0.8.10
org.apache.logging.log4j:log4j-core:2.18.0
org.apache.poi:poi:5.2.5
org.apache.tika:tika-parsers:1.28.5
org.apache.xmlgraphics:batik-*:1.17
org.apache.xmlgraphics:fop:2.8
org.apache.xmlgraphics:xmlgraphics-commons:2.8
org.docx4j:docx4j-ImportXHTML:8.3.11
org.docx4j:docx4j-JAXB-ReferenceImpl:11.3.2
org.docx4j:docx4j-export-fo:11.3.2
org.dom4j:dom4j:2.1.4
org.elasticsearch.client:elasticsearch-rest-high-level-client:7.17.18
org.freemarker:freemarker:2.3.32
org.glassfish:jakarta.el:3.0.4
org.hsqldb:hsqldb:2.7.2
org.jsoup:jsoup:1.17.2
org.postgresql:postgresql:42.7.3
org.springframework:spring-web:5.3.37
org.springframework:spring-webmvc:5.3.37
org.webjars.npm:grapesjs-blocks-basic:1.0.2'
org.webjars.npm:grapesjs-blocks-flexbox:1.0.1'
org.webjars.npm:grapesjs-custom-code:1.0.2'
org.webjars.npm:grapesjs-parser-postcss:1.0.3'
org.webjars.npm:grapesjs-plugin-ckeditor:1.0.1'
org.webjars.npm:grapesjs-plugin-forms:2.0.6'
org.webjars.npm:grapesjs-preset-newsletter:1.0.2'
org.webjars.npm:grapesjs-preset-webpage:1.0.3'
org.webjars.npm:grapesjs-style-filter:1.0.2'
org.webjars.npm:grapesjs-tabs:1.0.6'
org.webjars.npm:grapesjs-tooltip:0.1.8'
org.webjars.npm:grapesjs-tui-image-editor:1.0.2'
org.webjars.npm:grapesjs:0.21.8'
org.webjars.npm:mime-db:1.51.0'
org.webjars:jquery-ui:1.13.2
org.yaml:snakeyaml:2.2
xerces:xercesImpl:2.12.2
----

[[new-features]]
== 新功能和改进

[[sorting-by-multiple-columns-in-datagrid]]
=== DataGrid 支持按多列排序

在 xref:ui:vcl/components/data-grid.adoc[] 中按下 `Shift` 的同时选择多个列的表头，可以按多列排序。

[[grouptable-sorts-by-grouping-columns]]
=== GroupTable 按分则列排序

xref:ui:vcl/components/group-table.adoc[] 现在自动按分组列排序。因此，如果使用了分页，数据会按照分组在不同的页中分布。

可以使用 `groupTable` 的 `sortOnGroupEnabled="false"` 属性关闭该功能。

[[collection-properties-in-generic-filter]]
=== 通用过滤器中使用集合属性

xref:ui:vcl/components/filter.adoc[] 组件支持使用集合（to-many）属性创建过滤条件了。

例如，在 xref:tutorial:index.adoc#data-model[Onboarding 应用程序] 中，可以使用 `steps` 属性或嵌套的 `steps.dueDate`、`steps.step.name` 等属性对用户进行过滤。JPA 数据存储会根据条件使用 `join` 创建对应的 JPQL 查询语句。在以前的版本中，只能通过手动定义 xref:ui:vcl/components/filter.adoc#jpql-conditions[JPQL 条件] 完成该功能。

[[total-progress-in-filemultiuploadfield]]
=== FileMultiUploadField 显示总进度

xref:ui:vcl/components/file-multi-upload-field.adoc[] 现在可以展示所有上传文件的总进度了。在上传多个小文件时可以为用户提供更好的反馈。

用 `totalProgressFormat` 属性设置自定义的总进度文本内容格式，用 `totalProgressEnabled` 属性设置是否显示总进度条。

[[monitoring-loaders-in-screens]]
=== 监控界面内的加载器

数据加载器现在通过 Micrometer API 提供了详细的监控数据。

参考 https://github.com/jmix-framework/jmix/issues/3023[#3023^] 和 https://github.com/jmix-framework/jmix/issues/1704#issuecomment-1943207017[#1704^] 了解更多。

[[breaking-changes]]
== 破坏性改动

[[removed-flow-ui]]
=== 删除 Flow UI

去年我们发布了 Jmix 2.0，并同时声明了 Jmix 1.x 分支将仅包含 Classic UI，而 Flow UI 将仅包含在 Jmix 2.0+ 版本中（参阅 https://mp.weixin.qq.com/s?__biz=MzkxODM5ODIyMg==&mid=2247484256&idx=1&sn=9b3b82e6dbe695afbb5d072ea57db754&chksm=c1b0b701f6c73e17aa9ad69774ec9b8d87ec81f51c452ffcd3384015d50b0586768b99772611#rd[延长免费支持 Classic UI ^]）。

因此，我们从 Jmix 1.6 中删除了 Flow UI。

如果你的 Jmix 1.5 项目使用的是 Flow UI，请迁移至最新的 Jmix 2.x。

[[yarg-classes-moved-into-reports]]
=== YARG 类移至报表组件中

报表中使用的 YARG 引擎从作为外部依赖移至了报表扩展组件的源码中。如果之前 import 了 `++com.haulmont.yarg.*++` 类，请改为 `++io.jmix.reports.yarg.*++`。

[[data-repositories-initialization]]
=== Data Repositories 的初始化

在初始化 Data Repository 时，之前可选的 `@EnableJmixDataRepositories` 注解，现在调整为必需的了。参考 https://github.com/jmix-framework/jmix/issues/3428[#3428^] 和 https://github.com/jmix-framework/jmix/issues/1589[#1589^] 了解更多。

[[lazy-loaded-soft-deleted-onetoone-reference]]
=== 软删除一对一引用的延迟加载

软删除一对一引用的延迟加载问题已经修复。现在行为与使用 fetch plan 进行预加载一致：

* 软删除的一对一引用在所有端（owning side）加载。
* 软删除的一对一引用在映射端（mappedBy side）不加载。

之前的行为是反的。

参考 https://github.com/jmix-framework/jmix/issues/2466[#2466^] 了解更多。

[[changelog]]
== 变更日志

Jmix 框架解决的问题：

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.6.0[1.6.0^]
