= Что нового

IMPORTANT: Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Перейдите к разделу xref:studio:project.adoc#upgrading-project[Апгрейд проекта], чтобы узнать, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 7.2 в `gradle/wrapper/gradle-wrapper.properties`.

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** xref:release_1.1.0.adoc[1.1.0]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.1.1[1.1.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%201.1.0[1.1.0^]
