= 最近更新

本章节包含 Jmix 框架和 Studio {page-component-display-version} 的新功能介绍，以及在升级框架版本时需要注意的一些破坏性改动。

[[upgrade]]
== 如何升级

[IMPORTANT]
====
如需新建 Jmix {page-component-display-version} 项目或者升级已有项目，需要使用 Studio {page-component-display-version} 以上版本。因此，请先 xref:studio:update.adoc[升级] Jmix Studio 插件。

IntelliJ IDEA 的最低版本要求是 {minimal-idea-version}。

从 Jmix 1.5 自动迁移至 {page-component-display-version}，仅支持使用 *Flow UI* 和 *JDK 17* 的项目。
====

参阅 xref:studio:project.adoc#upgrading-project[升级项目] 部分的介绍了解如何使用 Studio 升级项目。自动升级迁移过程会对项目做如下修改：

* 升级 Jmix BOM 的版本，BOM 又定义了所有依赖的版本。
* 升级 Jmix Gradle 插件的版本。
* 在 `gradle/wrapper/gradle-wrapper.properties` 文件中升级 Gradle wrapper 的版本至 8.0.2。
* 替换 Java EE 包为 Jakarta EE（`javax` -> `jakarta`）
* `io.jmix.core.metamodel.datatype.impl.EnumClass` -> `io.jmix.core.metamodel.datatype.EnumClass`。
* `io.jmix.flowui.kit.component.FlowuiComponentUtils` -> `io.jmix.flowui.kit.component.ComponentUtils`。
* `javax.annotation.Nullable` -> `org.springframework.lang.Nullable`。
* 应用程序属性中的 `jmix.flowui` -> `jmix.ui`.
* 特殊权限中的 `flowui.loginToUi` -> `ui.loginToUi`.
* 在视图描述中：
** `queryParameters` -> `urlQueryParameters`。
** 标准的列表操作类型均改为以 `list_` 开头。
* `index.html` 文件中添加了 script 块。

请参考破坏性改动的 <<breaking-changes,完整列表>>，并在升级后做相应修复。

[[updated-dependencies]]
== 依赖更新

更新了下列主要依赖：

* Spring Boot 3.1
* Vaadin 24.0
* EclipseLink 4.0
* Flowable 7.0

项目需要使用 JDK 17 运行。

WAR 部署需要 Tomcat 10。

[[new-features]]
== 新功能和改进

[[add-ons-with-flow-ui]]
=== 支持 Flow UI 的扩展组件

下列扩展组件现在已经支持 Flow UI：

* xref:bpm:index.adoc[]
* xref:business-calendar:index.adoc[]
* xref:email:index.adoc[]
* xref:reports:index.adoc[]

[[flow-ui-test-assist]]
=== Flow UI 测试助手

Flow UI 测试助手（Test Assist）模块已经完成改进，现在支持视图之间的交互。新创建的应用程序项目中会生成一个用户管理视图的 UI 测试示例。

更多信息请参阅 https://github.com/jmix-framework/jmix/issues/1467[GitHub #1467]。

[[generic-filter]]
=== 通用过滤器组件

`genericFilter` 组件现在支持在设计时和运行时创建配置和自定义条件。运行时配置和自定义条件可交由终端用户管理。

设计时配置的示例：

[source,xml]
----
<genericFilter id="genericFilter" dataLoader="usersDl">
    <properties include=".*"/>
    <configurations>
        <configuration id="byEmail" name="By email">
            <propertyFilter operation="CONTAINS" property="email"/>
        </configuration>
    </configurations>
</genericFilter>
----

如需创建运行时配置，在添加完过滤条件之后，使用过滤器设置菜单（“齿轮” 按钮）将条件保存为配置。

如需创建运行时自定义条件，使用 *Add condition（添加条件）* 弹窗中的 *Create* 按钮。

[[codeeditor-component]]
=== CodeEditor Component

基于 Ace 编辑器的全新 `codeEditor` 组件支持用户查看和编辑代码，并支持语法高亮、自动缩进等高级功能。同时，该组件提供了通过 `dataContainer` 和 `property` XML 属性进行声明式数据绑定的功能。

示例：

[source,xml]
----
<codeEditor id="codeEditor" mode="GROOVY"
            dataContainer="taskDc" property="script"/>
----

[[preventing-browser-tab-closing]]
=== 防止浏览器标签页关闭

当展示实体详情视图时，如果用户尝试关闭浏览器标签页，系统会显示一个标准的确认离开页面窗口。这样可以放置意外的数据丢失。

如需为某个特定的视图关闭该窗口，可以在 `InitEvent` 处理方法中调用 `setPreventBrowserTabClosing()`：

[source,java]
----
@Subscribe
public void onInit(final InitEvent event) {
    setPreventBrowserTabClosing(false);
}
----

[[passing-parameters-in-navigation]]
=== 导航时传递参数

导航到不同视图时，我们引入了一种新的传递参数的方式：使用调用端的 `AfterViewNavigationEvent` 处理方法。这种方式支持传递复杂类型的参数，但是这些参数不会显示在 URL 中，用户刷新网页时会丢失状态。

更多信息，请参阅 xref:flow-ui:opening-views.adoc#passing-parameters[打开视图] 部分。

[[quick-cloud-deployment]]
=== 快速云部署

这次我们重新实现了 xref:studio:quick-cloud-deployment.adoc[] 功能，默认在 *Jmix* 工具窗口就能使用。通过几次点击就可以将应用程序部署在一个自动创建的 AWS EC2 实例中。

[[beans-in-jmix-tool-window]]
=== Jmix 工具窗口显示 Beans

*Jmix* 工具窗口现在能显示项目中定义的所有 Beans.

可以通过 *Options* -> *Group by Packages* 操作将 Beans 列表按包名分组。

[[bpm-in-jmix-tool-window]]
=== Jmix 工具窗口显示 BPM

如果你的项目包含了 xref:bpm:index.adoc[BPM add-on]，*Jmix* 工具窗口会显示 `BPM` 部分。其中包含 BPMN 流程、流程草稿以及 DMN 表格，对应项目的这些目录：

[cols="1,2,1"]
|===
|节点 |目录 |文件扩展名

|Processes
|`src/main/resources/processes`
|`.bpmn` 或 `.bpmn20.xml`

|Process Drafts
|`src/main/resources/process-drafts`
|`.draft.bpmn`

|DMN Tables
|`src/main/resources/dmn`
|`.dmn.xml`
|===

当执行 *New* -> *BPMN Process* 操作时，Studio 会创建一个新的流程草稿并展示在 `Process Drafts` 部分。流程准备好后，点击 BPM 设计器顶部的 *Copy to Processes* 按钮，或点击 *Jmix* 工具窗口的右键菜单按钮。Studio 会将草稿复制到 `Processes` 节点并从文件名中删除 `draft` 扩展名。

`Processes` 和 `DMN Tables` 节点的内容会在应用程序启动时自动部署。

[[all-beans-in-inject-dialog]]
=== Inject 窗口包含所有 Beans

*Inject* 窗口现在能展示项目 classpath 中定义的所有 beans，包括使用 `@Bean` 注解在 Java 配置类中定义的 beans。

当启用窗口中的分组选项时，`Other Beans` 和 `Other Properties` 部分按照包名中第一个非顶级域名部分进行分组。

NOTE: 不能保证出现在 *Inject* 窗口中的类在运行时就一定能注入成功。依赖很多运行时的条件，这些条件是 Studio 没有办法在设计时分析出来的。

[[using-final-modifier]]
=== 使用 final 修饰符

Studio 在生成代码是开始使用 `final` 修饰符修饰字段、变量以及方法参数。

可以在 *Jmix* 插件的 *Project Settings* 部分关掉此功能。

[[offsetdatetime-for-audit-fields]]
=== 审计字段使用 OffsetDateTime

时间戳类型的实体属性，包括实体审计特性的创建时间、修改时间和软删除时间现在都使用 `OffsetDateTime` 类型。因此，数据库也保存了时间戳的时区。

[[invalidating-studio-caches]]
=== 清除 Studio 缓存

现在支持删除 Studio 在 https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory[IDE 配置目录^] 中存储的信息。如果你遇到项目模板问题、生成视图有问题，或者视图设计器有问题，可以尝试清除缓存。

如需清理缓存，执行 *File* -> *Invalidate Caches* 命令，然后勾选 *Delete Jmix Studio templates and artifacts caches* 复选框并点击 *Invalidate and Restart*。

// [[preview]]
// == Preview Features

[[breaking-changes]]
== 破坏性改动

[[renamed-classes-and-properties]]
=== 属性和类名变更

. 以 `jmix.flowui` 开头的应用程序属性已经重命名为以 `jmix.ui` 开头。footnote:studio-migrator[Studio 迁移程序会自动对你的项目做必要的改动。]

. 重命名安全模块的特殊策略：

* `datatools.flowui.showEntityInfo` -> `datatools.showEntityInfo`
* `flowui.loginToUi` -> `ui.loginToUi` footnote:studio-migrator[]
* `flowui.showExceptionDetails` -> `ui.showExceptionDetails`
* `flowui.filter.modifyJpqlCondition` -> `ui.genericfilter.modifyJpqlCondition`
* `flowui.filter.modifyConfiguration` -> `ui.genericfilter.modifyConfiguration`
* `flowui.genericfilter.modifyGlobalConfiguration` -> `ui.genericfilter.modifyGlobalConfiguration`

. `io.jmix.core.metamodel.datatype.impl.EnumClass` 基类移至 `io.jmix.core.metamodel.datatype` 包。footnote:studio-migrator[]

. `queryParameters` facet 重命名为 `urlQueryParameters`。footnote:studio-migrator[]

. 标准列表操作类型添加了 `list_` 前缀。footnote:studio-migrator[]

. 重命名的操作类型：

* `excelExport` -> `grdexp_excelExport`
* `showRoleAssignments` -> `sec_showRoleAssignments`
* `showRoleAssignments` -> `sec_showRoleAssignments`
* `resetPassword` -> `sec_resetPassword`

. 框架的所有类中，除了 Spring 配置类和自动配置类，`Flowui` 前缀都改为了 `Ui` 前缀。用到 `io.jmix.flowui.kit.component.FlowuiComponentUtils` 的地方也都由 Studio 迁移程序替换成了 `ComponentUtils`。如果你还用到其他以 `Flowui` 开头的类，请手动替换。更多信息参考 https://github.com/jmix-framework/jmix/issues/1830[GitHub #1830^]。

[[removed-features]]
=== 删除的功能

. 删除了 `Actions` 接口中使用操作类创建操作的方法。有用到的请替换为使用字符串标识符创建操作的方法。详情参阅 https://github.com/jmix-framework/jmix/issues/1529[GitHub #1529^]。

. 删除了一些 UI 组件对 xref:flow-ui:vc/components/tooltip.adoc[] 的支持，包括：`ComboButton`、`DropdownButton`、`SimplePagination`、`UserIndicator`。

. 删除了从 Jmix 1.5 开始标记废弃的 `FlowuiLoginProperties` 类。如果你的项目是用 Jmix 1.4 创建的，这个类用在 LoginView 中，需要按照 Jmix 2.0 的项目模板修改你的 LoginView 及其 XML。

. Jmix BOM 不再提供 `commons-fileupload:commons-fileupload` 依赖。

. 删除了 `jmix.rest.max-upload-size` 属性。请使用 `spring.servlet.multipart.max-file-size` 和其他 {spring-boot-api}/org/springframework/boot/autoconfigure/web/servlet/MultipartProperties.html[MultipartProperties^] 中的属性。详情参阅 https://github.com/jmix-framework/jmix/issues/1496[GitHub #1496^]。

[[data-repositories-initialization]]
=== 初始化 Data Repositories 

在项目中初始化 xref:data-access:data-repositories.adoc[data repositories] 的可选注解 `@EnableJmixDataRepositories` 现在改成了必需注解。详情参阅 https://github.com/jmix-framework/jmix/issues/1589[GitHub #1589^]。

[[rounding-in-datatypes]]
=== 数据类型中的四舍五入

将字符串解析成 `BigDecimal`、`Double` 和 `Float` xref:data-model:data-types.adoc[datatypes] 时，现在能根据指定的格式对结果进行四舍五入处理。例如，如果数字格式设置为 `++#.##++`，当解析 `"12.3456"` 字符串时，结果会是数字 `12.35`。

如需退回到之前不带四舍五入的行为，请设置 `jmix.core.round-decimal-value-by-format` 应用程序属性为 `false`。详情参阅 https://github.com/jmix-framework/jmix/issues/968[GitHub #968^]。

[[bean-validation-on-persistence-layer]]
=== 持久层的 Bean 验证

持久层的 Bean 验证现在默认启用。也就是说当使用 `DataManager`、`EntityManager` 或 data repositories 保存实体实例时，将会对实体进行验证，如果实体状态无效，则会抛出异常。

可以通过配置下面的应用程序属性关闭持久层验证：

[source,properties]
----
jakarta.persistence.validation.mode = NONE
----

[[generic-rest-access-control]]
=== 通用 REST 访问控制

通用 REST 扩展组件现在使用 Jmix Authentication Server（认证服务）获取访问 token。更多信息请参阅 xref:rest:access-control.adoc[] 章节。

如果你的项目使用通用 REST，需要完成下列步骤：

* 替换依赖：`io.jmix.security:jmix-security-oauth2-starter` -> `io.jmix.authserver:jmix-authserver-starter`
* 在项目中配置客户端凭证或者认证码授权。
* 改造你的 REST 客户端，使用新的方式获取访问 token。

[[changelog]]
== 变更日志

* Jmix 框架解决的问题：

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.0.1[2.0.1^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.0.0[2.0.0^]

* Jmix Studio 解决的问题：

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.0.1[2.0.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.0.0,-1.5.*%20Affected%20versions:%20-SNAPSHOT%20[2.0.0^]
