= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates the version of Gradle wrapper to 8.6 in `gradle/wrapper/gradle-wrapper.properties`.
* In Kotlin projects, updates the version of Kotlin plugin to 1.9.22.
* Due to relocation of the <<pessimistic-locking, pessimistic locking>> feature, replaces usages of `io.jmix.core.pessimisticlocking` package with `io.jmix.pessimisticlock`, replaces `jmix.core.pessimistic-lock.\*` application properties with `jmix.pslock.\*` and adds dependencies to the new add-on to `build.gradle`.
* Adds `spring.main.allow-circular-references = true` application property. See <<circular-dependencies-between-spring-beans,below>> for more information.
* Adds `jmix.core.skip-null-or-empty-conditions-by-default = true` application property. See <<handling-empty-conditions,below>> for more information.
* Adds `jmix.appsettings.check-permissions-for-app-settings-entity = true` application property if the project includes the Application Settings add-on. See <<security-in-application-settings,below>> for more information.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot 3.2. See its https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes[release notes^] for more information.

* Vaadin 24.3. See release notes for Vaadin https://github.com/vaadin/platform/releases/tag/24.2.0[24.2^] and https://github.com/vaadin/platform/releases/tag/24.3.0[24.3^] for more information. Studio removes the `.pnpmfile.cjs` file from your project when migrating it to Jmix 2.2 (because of https://github.com/vaadin/flow/issues/17873[vaadin/flow#17873^]). Make sure this file doesn't exist after migration.

[[new-features]]
== New Features and Improvements

[[java-21]]
=== Support for Java 21

You can now use Java 21 and all its language features to write your applications.

The framework is still built using Java 17, so both Java 17 and 21 are available for application projects.

[[charts-add-on]]
=== Charts Add-on

The new Charts add-on integrates the https://echarts.apache.org[Apache ECharts^] JavaScript library into Jmix UI.

To include the add-on in your project, add the following dependency to `build.gradle`:

[source,groovy]
----
implementation 'io.jmix.charts:jmix-charts-flowui-starter'
----

To add a chart to a view, find the `Chart` component in the *Add component* palette.

See https://github.com/jmix-framework/jmix/issues/2437#issuecomment-1926905380[#2437^] for more information.

The complete documentation on the Charts add-on will be available soon.

[[richtextarea]]
=== RichTextArea Component

The new `richTextArea` component integrates the https://quilljs.com[Quill^] JavaScript library into Jmix UI. It's available in the standard  *Add component* palette.

[[horizontal-main-menu]]
=== Horizontal Main Menu

The new `horizontalMenu` component allows you to create a main view with a horizontal menu.

The new *Main view with top menu* template is now available in the view creation wizard. If you want to use the new view instead of the existing main view, select the *Use as default main view* checkbox on the first step of the wizard. Then Studio will replace the `layout` attribute of the `@Route` annotation in all views and set the new view in the `jmix.ui.main-view-id` application property.

See https://github.com/jmix-framework/jmix/issues/2492#issuecomment-1855606091[#2492^] for more information.

[[filtering-main-menu]]
=== Filtering Main Menu

The new `menuFilterField` component allows users to filter main menu items. It's available in the standard  *Add component* palette.

The `menu` attribute should point to a `listMenu` component to be filtered:

[source,xml,indent=0]
----
<menuFilterField menu="menu"
                 placeholder="Search..." classNames="ms-s me-s"/>
<nav id="navigation" classNames="jmix-main-view-navigation" ariaLabel="msg://navigation.ariaLabel">
    <listMenu id="menu"/>
</nav>
----

Please note that filtering of <<horizontal-main-menu>> is not supported.

[[initial-layout-in-main-view]]
=== Initial Layout in Main View

Now you can declaratively define an initial layout that will be shown when no views are opened in the main view. Use the `initialLayout` element of the `appLayout` component:

[source,xml]
----
<appLayout>
    <navigationBar .../>
    <drawerLayout .../>
    <initialLayout>
        <h2 text="Hello world!"/>
    </initialLayout>
</appLayout>
----

See https://github.com/jmix-framework/jmix/issues/2213[#2213^] for more information.

[[data-grid-enhancements]]
=== Data Grid Improvements

[[data-grid-handling-double-click]]
==== Handling Double-Click

The xref:flow-ui:vc/components/dataGrid.adoc[] component now handles double-click in list views: it either opens a detail view or, in lookup mode, finishes the selection. See https://github.com/jmix-framework/jmix/issues/2582[#2582^] for more information.

[[data-grid-url-parameters-for-filterin-column-headers]]
==== URL Parameters for Filter in Column Headers

The xref:flow-ui:vc/components/dataGrid.adoc[] column header filter can now be reflected in URL to provide a deep link and to save the view state when navigating to a detail view and back.

Use the `dataGridFilter` element of the xref:flow-ui:facets/urlQueryParameters.adoc[] facet, pointing to the data grid:

[source,xml,indent=0]
----
<facets>
    <urlQueryParameters>
        <dataGridFilter component="usersDataGrid"/>
    </urlQueryParameters>
</facets>
<layout>
    <dataGrid id="usersDataGrid" dataContainer="usersDc">
        <columns>
            <column property="username" filterable="true" resizable="false" autoWidth="true"/>
----

[[collection-properties-in-generic-filter]]
=== Collection Properties in Generic Filter

The xref:flow-ui:vc/components/genericFilter.adoc[] component now allows you to create conditions for collection (to-many) properties.

For example, in the xref:tutorial:index.adoc#data-model[Onboarding application], you can filter Users by the `steps` property and its nested properties: `steps.dueDate`, `steps.step.name`, etc. The JPA data store will automatically create an appropriate query with the `join` clause. Previously, you could achieve this only by defining a xref:flow-ui:vc/components/genericFilter.adoc#jpql-conditions[JPQL condition] manually.

See https://github.com/jmix-framework/jmix/issues/518#issuecomment-1860205607[#518^] for more information.

=== TO BE CONTINUED

[[breaking-changes]]
== Breaking Changes

[[circular-dependencies-between-spring-beans]]
=== Circular Dependencies Between Spring Beans

Previously, circular dependencies between Spring beans were enabled by Jmix on the framework level.

Jmix 2.2 doesn't have circular dependencies itself anymore and doesn't enable them in application projects by default.

There is a chance that your project contains circular dependencies between its Spring beans, therefore the Studio migration procedure automatically adds the following property to the project:

[source,properties]
----
spring.main.allow-circular-references = true
----

We recommend you to remove this property and try to start the application. If it fails to initialize, either refactor your beans to eliminate circular dependencies, or return the property.

See https://github.com/jmix-framework/jmix/issues/287[#287^] for more information.

[[handling-empty-conditions]]
=== Handling Empty Conditions

Previously, a xref:data-access:data-manager.adoc#load-by-conditions[property condition] evaluated to true if its parameter value was empty (null, empty string or empty collection).

Since Jmix 2.2, the null or empty parameters do not lead to skipping  conditions. For example, consider the following code:

[source,java]
----
dataManager.load(User.class)
    .condition(PropertyCondition.contains("email", null))
    .list();
----

In Jmix 2.1 and earlier, it executes the following SQL:

[source,sql]
----
SELECT ID, ACTIVE, EMAIL, <...> FROM USER_
----

In Jmix 2.2, by default it executes the following SQL and passes `null` as a parameter:

[source,sql]
----
SELECT ID, ACTIVE, EMAIL, <...> FROM USER_ WHERE EMAIL LIKE ?
----

As a result, in Jmix 2.1 the whole list of users is returned, while in Jmix 2.2 the result list is empty.

If you want to return the previous behavior, set the following application property:

[source,properties]
----
jmix.core.skip-null-or-empty-conditions-by-default = true
----

The Studio migration procedure automatically adds this property to your project.

Alternatively, you can skip empty parameters for particular conditions:

[source,java]
----
dataManager.load(User.class)
    .condition(PropertyCondition.contains("email", null).skipNullOrEmpty())
    .list();
----

See https://github.com/jmix-framework/jmix/issues/2490[#2490^] for more information.

[[noResultException]]
=== NoResultException

`io.jmix.core.NoResultException` is now thrown instead of `java.lang.IllegalStateException` if the `one()` method of DataManager's fluent xref:data-access:data-manager.adoc#load-by-id[loading API] returns no results. See https://github.com/jmix-framework/jmix/issues/2682[#2682^].

[[pessimistic-locking]]
=== Pessimistic Locking

The pessimistic locking feature has been extracted to the xref:pessimistic-lock:index.adoc[add-on].

The `io.jmix.core.pessimisticlocking` package has been renamed to `io.jmix.pessimisticlocking`.

Changed the following properties:

* `jmix.core.pessimistic-lock.use-default-quartz-configuration` -> `jmix.pslock.use-default-quartz-configuration`
* `jmix.core.pessimistic-lock.expiration-cron` -> `jmix.pslock.expiration-cron`

The Studio migration procedure automatically adds dependencies to your `build.gradle` and changes the imports and property names.

See https://github.com/jmix-framework/jmix/issues/1958#issuecomment-1792291873[#1958^] for more information.

[[validation-in-file-upload-fields]]
=== Validation in File Upload Fields

The `isInvalid()` method of xref:flow-ui:vc/components/fileUploadField.adoc[] and xref:flow-ui:vc/components/fileStorageUploadField.adoc[] does not trigger validation anymore. It only checks invalid state of the field. See https://github.com/jmix-framework/jmix/issues/2821[#2821^].

[[action-shortcuts]]
=== Action Shortcuts

Keyboard shortcuts of actions assigned to components like xref:flow-ui:vc/components/button.adoc[] or xref:flow-ui:vc/components/dataGrid.adoc[] are now handled differently. See https://github.com/jmix-framework/jmix/issues/1758#issuecomment-1859722867[#1758^] for more information.

[[security-in-application-settings]]
=== Security in Application Settings

The xref:appsettings:index.adoc[] add-on now doesn't require to add security permissions to `AppSettingsEntity` entity to work with settings through the `AppSettings` bean.

If you want to return the previous behavior, set the following application property:

[source,properties]
----
jmix.appsettings.check-permissions-for-app-settings-entity = true
----

The Studio migration procedure automatically adds this property to your project.

See https://github.com/jmix-framework/jmix/issues/2710[#2710^] for more information.

[[security-views]]
=== Security Views

The layout of the standard security views for resource and row-level roles has been changed for better usability, see https://github.com/jmix-framework/jmix/issues/2519[#2519^].

If you have extended these views, you may have to modify your code.

[[maps-api]]
=== Maps API

The following changes have been made in the xref:maps:index.adoc[] add-on:

* `io.jmix.mapsflowui.kit.component.model.style.text.Padding` has been moved to `io.jmix.mapsflowui.kit.component.model` package. See https://github.com/jmix-framework/jmix/issues/2822[#2822^].
* The `addStyles()` method of the `Feature`, `PointFeature`, `MarkerFeature`, `LineStringFeature`, `PolygonFeature` classes now returns `void`. Use `withStyles()` instead if you need the current instance of the feature. See https://github.com/jmix-framework/jmix/issues/2807[#2807^].
* In the `VectorLayer` class, the `addStyles()` method of the `VectorLayer` class now returns `void`. Use `withStyles()` instead if you need the current instance of the layer. Renamed methods: `isDeclutter()` -> `getDeclutter()`, `isUpdateWhileAnimating()` -> `getUpdateWhileAnimating()`. See https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* In the `ClusterSource` class, the `addPointStyles()` method now returns `void`. Use `withPointStyles()` instead if you need the current instance of the source. See https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* In the `Layer` class, the `isVisible()` method is renamed to `getVisible()`. See https://github.com/jmix-framework/jmix/issues/2790[#2790^].
* The type of zoom properties in `VectorLayer`, `TileLayer`, `ImageLayer` and `GeoMapView` has been changed from `Integer` to `Double`. See https://github.com/jmix-framework/jmix/issues/2701[#2701^].

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aissue+project%3Ajmix-framework%2F18+is%3Aclosed[2.2.0^]
// ** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.2.0[2.2.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.2.0,-2.1.*%20Affected%20versions:%20-SNAPSHOT[2.2.0^]
