= Release 3.0

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix 3.0 or to upgrade an existing project, you need Studio 3.0 or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates Gradle wrapper to 8.14.4

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[new-features]]
== New Features and Improvements

[[studio-improvements]]
=== Studio Improvements

[[markdown-editor]]
=== MarkdownEditor Component

The new xref:flow-ui:vc/components/markdownEditor.adoc[markdownEditor] component allows users to write and preview Markdown content within a single field. It provides a formatting toolbar, mode switching between *Edit* and *Preview*, keyboard shortcuts, and standard field features such as data binding, validation, and theming.

[[breaking-changes]]
== Breaking Changes

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A3.0.0[3.0.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%203.0.0,-2.8.*%20Affected%20versions:%20-SNAPSHOT[3.0.0^]
