= Релиз 3.1

[IMPORTANT]
====
Для создания новых проектов в Jmix 3.1 или для апгрейда существующего проекта требуется Studio 3.1 или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA / OpenIDE - 2026.1.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 9.8.0

См. полный список <<breaking-changes,критических изменений>>, которые могут затронуть ваш проект после обновления.

[[updated-dependencies]]
== Обновленные зависимости

Следующие основные зависимости были обновлены:

* Spring Boot 4.1
* Vaadin 25.3

[[new-features]]
== Новая и улучшенная функциональность

[[studio-improvements]]
=== Улучшения Studio

[[dynamic-model]]
=== Дополнение Dynamic Model

[[breaking-changes]]
== Критические изменения

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A3.1.0[3.1.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%203.1.0,-3.0.*%20Affected%20versions:%20-SNAPSHOT[3.1.0^]
