= Release 3.1

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix 3.1 or to upgrade an existing project, you need Studio 3.1 or newer, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

Jmix Studio 3.1 requires IntelliJ IDEA 2026.1 or newer.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates Gradle wrapper to 9.8.0

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot 4.1
* Vaadin 25.3

[[new-features]]
== New Features and Improvements

[[studio-improvements]]
=== Studio Improvements

[[resizable-side-panel]]
=== Resizable Side Panel

Users can now xref:flow-ui:vc/layouts/sidePanelLayout.adoc#resizing[resize the `sidePanelLayout` component] at runtime by dragging the handle on the side panel's inner edge. Resizing works for horizontal and vertical positions and respects the configured minimum and maximum sizes. The xref:flow-ui:facets/settings.adoc[`settings`] facet can save and restore the size selected by the current user.

[[dynamic-model]]
=== Dynamic Model Add-on

The xref:dyn-model:index.adoc[Dynamic Model] add-on is no longer experimental. It has the following new features:

* xref:dyn-model:handlers.adoc[UI handlers] add behavior to views: short expressions that run on button clicks, value changes and view events, and can call application methods marked with `@DynamicModelOperation`.
* xref:dyn-model:search.adoc[Full-text search] indexes dynamic attributes marked as searchable.
* xref:dyn-model:concepts.adoc#cluster[Cluster support]: a model applied on one node is applied on all other nodes.
* The xref:dyn-model:defining-model.adoc#safe-modify-role[Dynamic model: modify settings without data loss] role lets users apply only changes that cannot lose stored data.
* The xref:dyn-model:defining-model.adoc#model-history[model history] shows all applied versions of the model.
* You can change the xref:dyn-model:defining-model.adoc#attribute-order[order of attributes].
* You can set the xref:dyn-model:defining-model.adoc#lookup-field[lookup field type and actions] for reference attributes.
* Menu items of dynamic views can have an xref:dyn-model:views.adoc#menu-items[icon].
* The *Generate XML* button xref:dyn-model:views.adoc#generate-xml[renders a view template into XML] that you can edit.
* Dynamic entities and attributes are shown in the xref:dyn-model:concepts.adoc#data-tools[Data Tools] views.

[[bpm]]
=== BPM Add-on

The xref:bpm:index.adoc[BPM] add-on has the following new features in the xref:bpm:menu-views/modeler-web.adoc[BPMN modeler]:

* You can edit the *History level* of a process along with other xref:bpm:bpmn/bpmn-process.adoc#properties[process properties]. The selected level overrides the xref:bpm:history.adoc#history-levels[history level] of the process engine.
* You can set the `flowable:exclusive`, `flowable:asyncLeave`, and `flowable:asyncLeaveExclusive` attributes for tasks, embedded subprocesses, call activities, gateways, and most events. For user tasks, gateways, and events, `flowable:async` is now available as well. See xref:bpm:bpmn/transactions.adoc#asynchronous-execution-properties[Asynchronous Execution Properties].
* You can add xref:bpm:bpmn/bpmn-events.adoc#escalation-events[escalation events] to processes, set their properties, and manage *Escalation definitions* in the xref:bpm:bpmn/bpmn-process.adoc#escalation-definition[process properties].

[[grouping-data-grid]]
=== Grouping Data Grid Add-on

You can preserve the applied xref:flow-ui:vc/components/groupDataGrid.adoc#column-filtering[column header filters] in URL query parameters by adding the xref:flow-ui:facets/urlQueryParameters.adoc#groupDataGridFilter[`groupDataGridFilter`] element to the xref:flow-ui:facets/urlQueryParameters.adoc[`urlQueryParameters`] facet.

[[breaking-changes]]
== Breaking Changes

[[dynamic-model-yaml]]
=== Dynamic Model: Stricter Reading of YAML

The Dynamic Model add-on now reads the YAML model definition strictly (see https://github.com/jmix-framework/jmix/issues/5731[#5731^]). The rules are described in xref:dyn-model:yaml-reference.adoc#writing-yaml[Writing YAML by Hand].

This affects only models that were written or edited by hand in the *Code* presentation. Models saved from the visual editor always have quoted values and are read as before.

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A3.1.0[3.1.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%203.1.0,-3.0.*%20Affected%20versions:%20-SNAPSHOT[3.1.0^]
