= Релиз 3.0

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA / OpenIDE - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 8.14.4

См. полный список <<breaking-changes,критических изменений>>, которые могут затронуть ваш проект после обновления.

[[new-features]]
== Новая и улучшенная функциональность

[[studio-improvements]]
=== Улучшения Studio

[[markdown-editor]]
=== MarkdownEditor Component

The new xref:flow-ui:vc/components/markdownEditor.adoc[markdownEditor] component allows users to write and preview Markdown content within a single field. It provides a formatting toolbar, mode switching between *Edit* and *Preview*, keyboard shortcuts, and standard field features such as data binding, validation, and theming.

[[breaking-changes]]
== Критические изменения

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A3.0.0[3.0.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%203.0.0,-2.8.*%20Affected%20versions:%20-SNAPSHOT[3.0.0^]
