= Release 3.1

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix 3.1 or to upgrade an existing project, you need Studio 3.1 or newer, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

Jmix Studio 3.1 requires IntelliJ IDEA 2026.1 or newer.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates Gradle wrapper to 9.8.0

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot 4.1
* Vaadin 25.3

[[new-features]]
== New Features and Improvements

[[studio-improvements]]
=== Studio Improvements

[[dynamic-model]]
=== Dynamic Model Add-on

[[breaking-changes]]
== Breaking Changes

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A3.1.0[3.1.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%203.1.0,-3.0.*%20Affected%20versions:%20-SNAPSHOT[3.1.0^]
