= Email Templates

The add-on enables creating and configuring outbound email templates containing a constant body and variable parameters. A template is created in the visual HTML designer or by using reports. The add-on provides a visual HTML editor with an extensive set of HTML elements.

Sending emails from templates can be set as a reaction to different events in your application. You can preset recipients, configure parameters and upload attachment files to be sent with emails.

Key features:

* Visual HTML templates builder based on https://grapesjs.com[GrapesJs^] JavaScript library.
* HTML reports as a base for outbound emails body.
* Downloading/uploading HTML code of a template.
* User interface for configuring and managing templates.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----


