= Начало работы с Kanban

Данное руководство поможет вам интегрировать Kanban в ваше приложение.

[[project-setup]]
== Настройка проекта

Мы разрабатываем приложение Kanban Board, которое позволит пользователям управлять задачами визуально, обеспечивая совместную работу над проектами.

. Создайте базовый проект Jmix. Вы можете воспользоваться разделом xref:tutorial:project-setup.adoc[Самоучителя], где представлено пошаговое руководство по разработке базового приложения.
. Добавьте дополнение Kanban в соответствии с разделом xref:index.adoc#installation[Установка].

[[about-app]]
== О приложении

Вы создадите приложение kanban-доски, которое позволит пользователям визуально управлять задачами, назначать их членам команды, устанавливать сроки и отслеживать прогресс с легкостью.

Мы создадим новую сущность JPA под названием `KanbanTask` для представления задачи, которая будет назначена пользователю.

Затем мы интегрируем компонент `kanban`-доски в наше приложение. Этот компонент должен:

* Отображать колонки Kanban, представляющие статусы задач: `"В работе"` (`"Todo"`), `"В процессе"` (`"In progress"`), `"Проверка"` (`"Verification"`), `"Завершено"` (`"Done"`).
* Отображать карточки Kanban, представляющие экземпляры сущности `KanbanTask`. Каждая карточка должна отображать название задачи, статус и, возможно, другую релевантную информацию, такую как исполнитель и срок.
* Разрешать пользователям перетаскивать карточки между колонками для обновления статуса задачи.
* Предоставлять опции добавления, редактирования и удаления задач.

Чтобы увидеть несколько задач в демонстрационных данных, создайте экземпляры сущности в классе `DemoDataInitializer` или просто создайте задачи вручную при запуске приложения.