= Getting Started with Kanban

This tutorial will guide you through the process of integrating Kanban into your application.

[[project-setup]]
== Project Setup

We are developing a Kanban Board Application, allowing users to manage tasks in a visual and collaborative way.

. Create a base Jmix project. You can refer to the xref:tutorial:project-setup.adoc[Tutorial] section, which offers a detailed, step-by-step guide for developing the base application.
. Add the Kanban add-on according to the xref:index.adoc#installation[installation] section.

[[about-app]]
== About the Sample Application

You will build the Kanban board application, which allows you to manage tasks visually, assign them to team members, set deadlines, and track progress with ease.

We will create a new JPA entity called `KanbanTask` to represent a task, which will be assigned to a `User`.

Then we will integrate a `kanban` board component into our application. This component should:

* Display Kanban columns representing the task statuses (`"Todo"`, `"In progress"`, `"Verification"`, `"Done"`).
* Display Kanban cards representing the `KanbanTask` entity instances. Each card should display the task title, status, and potentially other relevant information like assignee and due date.
* Allow users to drag and drop cards between columns to update the task’s status.
* Provide options to add, edit, and delete tasks.

To see some tasks in the demonstration data, create entity instances in the `DemoDataInitializer` class, or just create tasks manually when you run the application.