= GrapesJS UI Components

The Jmix framework supports several GrapesJS UI components:

* `grapesJsHtmlEditor` - a base HTML editor without any applied <<plugins,plugins>>.
* `grapesJsWebpageHtmlEditor` - an HTML editor suitable for webpage development with applied `webpage`, `customcode` plugins.
* `grapesJsNewsletterHtmlEditor` - an HTML editor suitable for newsletter development with applied `newsletter`, `customcode` plugins.
+
The `grapesJsNewsletterHtmlEditor` component has an additional `inlineCss` attribute. If it is enabled, then CSS classes will be inlined in HTML.

The example below demonstrates how to create a `grapesJsHtmlEditor` component:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/grapesjs/ex1/screen/grapesjs/grapesjs-screen.xml[tags=schema;screen]
----

All GrapesJS UI components provide following methods:

* `setValue(String value)` - to set HTML content for the component;
* `getValue()` - to get HTML content from the component;
* `runCommand(String command)` - to run command;
* `stopCommand(String command)` - to stop command.

[[disabled-blocks]]
== Disabled Blocks

You can define a comma-separated list of xref:html-editor-ui.adoc#blocks-tab[blocks] that should be disabled, 示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/grapesjs/ex1/screen/grapesjs/custom-block-screen.xml[tags=html-editor-start;html-editor-end]
----

[[plugins]]
== Plugins

UI components can be extended with plugins using the `plugin` element. A plugin can be selected from the predefined plugins list or configured as a new plugin.

The following default available plugins are supported:

* `basicBlocks` - this plugin contains some basic blocks for the GrapesJS editor (see the https://github.com/artf/grapesjs-blocks-basic[GrapesJS Basic Blocks^] documentation).
* `ckeditor` - this plugin replaces the default `Rich Text Editor` with `CKEditor` (see the https://github.com/artf/grapesjs-plugin-ckeditor[GrapesJS CKEditor^] documentation).
* `customcode` - this plugin adds a possibility to embed custom code (see the https://github.com/artf/grapesjs-custom-code[GrapesJS Custom Code^] documentation).
* `flexBlocks` - this plugin adds the `Flexbox` block, which allows creating easily flexible and responsive columns (see the https://github.com/artf/grapesjs-blocks-flexbox[GrapesJS Blocks Flexbox^] documentation).
* `forms` - this plugin adds some basic form components and blocks to make working with forms easier (see the https://github.com/artf/grapesjs-plugin-forms[GrapesJS Forms^] documentation).
* `newsletter` - this preset configures GrapesJS to be used as a Newsletter Builder with some unique features and blocks composed specifically for being rendered correctly inside all major email clients (see the https://github.com/artf/grapesjs-preset-newsletter[GrapesJS Newsletter Preset^] documentation).
* `postcss` - this plugin enables custom CSS parser via `PostCSS` (see the https://github.com/artf/grapesjs-parser-postcss[GrapesJS Parser PostCSS^] documentation).
* `styleFilter` - this plugin adds the `filter` type input to the *Style Manager* in GrapesJS (see the https://github.com/artf/grapesjs-style-filter[GrapesJS Style Filter^] documentation).
* `tabs` - simple tabs component plugin for GrapesJS (see the https://github.com/artf/grapesjs-tabs[GrapesJS Tabs^] documentation).
* `tooltip` - simple, CSS only, tooltip component for GrapesJS (see the https://github.com/artf/grapesjs-tooltip[GrapesJS Tooltip^] documentation).
* `touch` - this plugin enables touch support for the GrapesJS editor (see the https://github.com/artf/grapesjs-touch[GrapesJS Touch^] documentation).
* `tuiImageEditor` - this plugin adds the `TOAST UI Image Editor` on Image Components in GrapesJS (see the https://github.com/artf/grapesjs-tui-image-editor[GrapesJS TOAST UI Image Editor^] documentation).
* `webpage` - this preset configures GrapesJS to be used as a Webpage Builder (see the https://github.com/artf/grapesjs-preset-webpage[GrapesJS Preset Webpage^] documentation).

Here is an example of defining `grapesJsNewsletterHtmlEditor` with plugins:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/grapesjs/ex1/screen/grapesjs/plugin-screen.xml[tags=using-plugins]
----

<1> Define custom plugin options.

Custom project plugins can be registered via the `io.jmix.grapesjs.component.GjsPluginsRepository` class.

[[custom-blocks]]
== Custom Blocks

Custom xref:html-editor-ui.adoc#blocks-tab[blocks] can be added to the component using the `block` element with the following parameters:

* `name` - a unique block id;
* `label` - a name of the block;
* `category` - group the block inside a category;
* `content` - HTML content;
* `contentPath` - path to HTML content;
* `attributes` - block attributes.

The example below demonstrates how to create a custom block:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/grapesjs/ex1/screen/grapesjs/custom-block-screen.xml[tags=custom-block]
----

Custom project blocks can be registered via the `io.jmix.grapesjs.component.GjsBlocksRepository` class. Registered blocks can be added to UI components by the `name` attribute.

In the example below, we create a Spring bean, where register a new custom block:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/grapesjs/ex1/app/BlocksRegister.java[tags=blocks-register]
----

<1> Create an instance of GrapesJS block.
<2> Register custom GrapesJS block, which can be used in the XML descriptor.

Then we add an earlier registered block in the XML descriptor:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/grapesjs/ex1/screen/grapesjs/custom-block-screen.xml[tags=html-editor-start;custom-registered-block;html-editor-end]
----

[NOTE]
====
Please use `class:'fa <fa-icon>'` in the `attributes` parameter to use Font Awesome icon.
====
