= Anonymous Access to Screens

By default, only the xref:ui:screens/root-screens.adoc#login-screen[login screen] is available to the anonymous (not authenticated) session. By creating the new login screen, you can add any information on it or even add the `WorkArea` component and be able to open inside it other screens available to the anonymous user. But as soon as the user logs in, all screens opened in the anonymous mode will be closed.

Sometimes it is necessary to provide some application screens regardless of whether the user is authenticated in the system or not. Consider the following requirements:

* When users open the application, they see the main screen with the side menu available for anonymous users.
* There is an *Info* screen with some publicly available information. By clicking the *Show the Login Screen* button, users can go to the login screen and continue working with the rest of the system as authenticated users.
* Users can open the *Info* screen both from the main menu and by entering a xref:url-history-navigation.adoc[URL] in the web browser.

Implementation steps are described below.

. Create the new xref:ui:screens/root-screens.adoc#main-screen[main screen] using the *Main screen with side menu* template.
. Create your screen, for example, `MyAnonymousScreen`, with some information for anonymous users and a button that opens the login screen:
+
.my-anonymous-screen.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/screen/myanonymous/my-anonymous-screen.xml[]
----
+
Annotate the controller with xref:url-history-navigation/routing-api.adoc#route-registration[@Route] to be able to open it using a link:
+
.MyAnonymousScreen.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/screen/myanonymous/MyAnonymousScreen.java[tags=my-anonymous-screen]
----
<1> Specifies the screen’s address. When the screen is opened in the top-level window (as root), its address will be `++http://localhost:8080/#anonymous++`.
. Define the new menu item under the *Application* menu:
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=anonymous-screen]
----
. Create the `AnonymousRole` xref:security:resource-roles.adoc[resource role] and allow access to `MyAnonymousScreen` and `MainScreenSideMenu`:
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/security/AnonymousRole.java[tags=anonymous-role]
----
. Grant `AnonymousRole` to the anonymous user in `DatabaseUserRepository`:
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/security/DatabaseUserRepository.java[tags=init-anonymous-user]
----
. In the `application.properties` file enable anonymous access and specify which screen appears for the anonymous user:
+
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=anonymous-access]
----
+
[NOTE]
====
Keep in mind that you'll have two main screens in your app. The default one will be used for authenticated users and the anonymous one for anonymous:

[source,properties,indent=0]
----
jmix.ui.main-screen-id=MainScreen
jmix.ui.initial-screen-id=MainScreenSideMenu
----
====

. Launch the application and make sure that the screen you created opens from the main menu and at `/#anonymous`.