= Анонимный доступ к экранам

По умолчанию для анонимной (неаутентифицированной) сессии доступен только xref:ui:screens/root-screens.adoc#login-screen[экран логина]. Путем создания нового экрана логина в приложении можно добавить на него любую информацию или даже добавить компонент `WorkArea` и открывать в нем любые экраны системы, если на них есть права у анонимного пользователя. Однако как только пользователь войдет в систему, все экраны, открытые в анонимном режиме, будут закрыты.

Иногда бывает необходимо предоставить некоторые экраны приложения вне зависимости от того, аутентифицирован пользователь в системе или нет. Рассмотрим следующие требования:

* Когда пользователи открывают приложение, они видят главный экран с боковым меню, доступным для анонимных пользователей.
* В приложении есть экран *Info* с некоторой общедоступной информацией. Нажав кнопку *Show the Login Screen*, пользователи могут перейти к экрану логина и продолжить работу с остальной частью системы как аутентифицированные пользователи.
* Пользователь может открыть экран *Info* из главного меню, либо вводом URL в веб-браузере.

Ниже описаны шаги реализации данных требований.

. Создайте новый xref:ui:screens/root-screens.adoc#main-screen[главный экран], используя шаблон *Main screen with side menu*.
. Создайте свой экран, например, `MyAnonymousScreen`, с некоторой информацией для анонимных пользователей и кнопкой, открывающей экран логина:
+
.my-anonymous-screen.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/screen/myanonymous/my-anonymous-screen.xml[]
----
+
Добавьте его контроллеру аннотацию xref:url-history-navigation/routing-api.adoc#route-registration[@Route] для того, чтобы иметь возможность открывать его по ссылке:
+
.MyAnonymousScreen.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/screen/myanonymous/MyAnonymousScreen.java[tags=my-anonymous-screen]
----
<1> Задает адрес экрана. Если экран открыт в окне верхнего уровня (в корне), его адрес будет `++http://localhost:8080/#anonymous++`.
. Определите новый пункт меню в меню *Application*:
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=anonymous-screen]
----
. Создайте xref:security:resource-roles.adoc[ресурсную роль] `AnonymousRole` и дайте ей доступ к `MyAnonymousScreen` и `MainScreenSideMenu`:
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/security/AnonymousRole.java[tags=anonymous-role]
----
. Назначьте роль `AnonymousRole` пользователю anonymous в `DatabaseUserRepository`:
+
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/security/DatabaseUserRepository.java[tags=init-anonymous-user]
----
. В файле `application.properties` включите анонимный доступ и укажите, какой экран отображается для анонимного пользователя:
+
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=anonymous-access]
----
+
[NOTE]
====
Учитывайте, что в вашем приложении будет два основных экрана. Экран по умолчанию будет использоваться для аутентифицированных пользователей, а анонимный – для анонимных:

[source,properties,indent=0]
----
jmix.ui.main-screen-id=MainScreen
jmix.ui.initial-screen-id=MainScreenSideMenu
----
====

. Запустите приложение и убедитесь, что созданный вами экран открывается из главного меню и по ссылке `/#anonymous`.