= Обработчики исключений

Необработанные исключения, выбрасываемые клиенту, передаются специальному механизму обработчиков.

Обработчик исключений – это бин Spring, реализующий интерфейс `UiExceptionHandler`. Его метод `handle()` должен обработать исключение и вернуть `true` или немедленно вернуть `false`, если данный обработчик не может обработать переданное исключение. Такое поведение создает "цепочку ответственности" для обработчиков.

Рекомендуется наследовать обработчики от базового класса `AbstractUiExceptionHandler`, который может разбирать цепочку исключений (включая упакованные внутри `RemoteException`) и обрабатывать определенные их типы. Поддерживаемые этим обработчиком типы исключений определяются путем передачи массива строк базовому конструктору из конструктора обработчика. Каждая строка массива должна содержать одно полное имя класса обрабатываемых исключений.

Предположим, у вас есть следующий класс исключений:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/exception/ZeroBalanceException.java[tags=exception]
----

Создайте обработчик для этого исключения со следующим конструктором:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/exception/ZeroBalanceExceptionHandler.java[tags=zero-balance-exception-handler;constructor]
----

Если класс исключения недоступен на стороне клиента, укажите его имя с помощью строкового литерала:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/exception/ForeignKeyViolationExceptionHandler.java[tags=foreign-key-violation-exception-handler]
----

В случае использования `AbstractUiExceptionHandler` в качестве базового класса логика обработки находится в методе `doHandle()` и выглядит следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/exception/ZeroBalanceExceptionHandler.java[tags=zero-balance-exception-handler;constructor;do-handle]
----

Если имени класса исключения недостаточно для принятия решения о том, может ли данный обработчик быть применен к данному исключению, определите метод `canHandle()`. Этот метод также принимает текст исключения. Если обработчик применим для исключения, метод возвращает `true`. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/exception/ZeroBalanceExceptionHandler.java[tags=zero-balance-exception-handler;can-handle]
----

Интерфейс xref:dialogs.adoc[Dialogs], доступный через параметр `UiContext` метода `doHandle()`, предоставляет специальный диалог для отображения исключений, содержащий сворачиваемую область с полным стектрейсом исключения. Это диалоговое окно используется в обработчике по умолчанию, но вы можете использовать его и для собственных исключений, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/exception/ZeroAccountBalanceExceptionHandler.java[tags=do-handle]
----