= MenuConfig

`MenuConfig` is a special class that loads the main menu structure based on a file specified in the xref:ui:app-properties.adoc#jmix.ui.menu-config[jmix.ui.menu-config] property.

//TODO: добавить сюда ссылку на дизайнер меню, когда описание появится в документации по студии
//[TIP]
// Use the Studio menu designer to define the menu structure.
When you create a new project in Studio, it generates the `menu.xml` file that defines the structure of the application main menu.

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=menu-config;menu]
----

There are two xref:studio:menu-designer.adoc#menu-modes[modes] of loading files that define menu structure: composite (default) and single.

Use the xref:ui:app-properties.adoc#jmix.ui.composite-menu[jmix.ui.composite-menu] property to switch these modes.

Let’s consider the `menu.xml` file in detail.

`menu-config` is the root XML element. Elements of `menu-config` form a tree structure where `menu` elements are branches and `item` and `separator` elements are leaves.

[[menu-attributes]]
== Menu Attributes

`menu` is a nested element of `menu-config`. It has the following attributes:

* `id` - unique identifier of the element.
* `caption` - caption of the `menu` element. If not set, the caption will be determined by the rule explained <<defining-menu-caption,below>>.
* `description` - a text shown as a tooltip on mouse hover. You can use localized messages from the xref:localization:message-bundles.adoc[message bundle].
* `icon` - icon of the `menu` element. See xref:ui:icons.adoc[Icons] for details.
* `insertBefore`, `insertAfter` - determine whether the item should be inserted before or after a particular element or a menu item with the specified identifier. These attributes are used to insert an item to an appropriate place in the menu defined in the files of xref:jmix:ROOT:add-ons.adoc[add-ons]. Do not use the `insertBefore` and `insertAfter` attributes at the same time.
* `stylename` - defines a style name for the menu item. See xref:jmix:ui:themes.adoc[Themes] for details.
* `expanded` - determines whether the `menu` element should be expanded when opening the main screen. The default value is `false`.

For example:

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=menu]
----

== Item Attributes

`item` is a nested element of `menu`. It has the following attributes:

* `id` - unique identifier of the element. If no screen, bean, class attributes are defined, the id is used to point to a screen with the same id. When the user clicks on the menu item, the corresponding screen will be opened on the xref:ui:screens/root-screens.adoc#main-screen[main screen].
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-id]
----

* `caption` - caption of the `item` element. If not set, the caption will be determined by the rule explained <<defining-menu-caption,below>>.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-caption]
----

* `description` - a text which is shown as a tooltip on mouse hover. You can also use localized messages from the xref:localization:message-bundles.adoc[message bundle].

* `screen` - a screen identifier. It can be used to include one screen into the menu multiple times. When the user clicks on the menu item, the corresponding screen will be opened on the main screen.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-screen]
----
* `bean` - a bean name. Must be used together with `beanMethod`. When the user clicks on the menu item, the method of the bean is invoked.
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-bean]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/bean/MenuBean.java[tags=menu-bean]
----

* `class` - fully qualified name of a class that implements the `MenuItemRunnable` interface. When the user clicks on the menu item, an instance of the specified class is created and its method is invoked.
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-class]
----
+
.CustomMenu.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/app/CustomMenu.java[tags=custom-menu]
----

* `shortcut` - a keyboard shortcut for this menu item. Possible modifiers - `ALT`, `CTRL`, `SHIFT` - are separated with “-”. For example:
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-shortcut]
----
+
Shortcuts can also be configured in the `application.properties` file and then used in the `menu.xml` file in the following way:
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-shortcut-prop]
----
+
.application.properties
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=menu-item-shortcut]
----
* The `openMode` attribute defines how a screen will be opened. It corresponds to the `OpenMode` enumeration with the values: `NEW_TAB`, `DIALOG`, `NEW_WINDOW`. Default value is `NEW_TAB`.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-open-mode]
----
* `icon` - icon of the `item` element. See xref:ui:icons.adoc[Icons] for details.
* `insertBefore`, `insertAfter` - determine whether the item should be inserted before or after a particular element or a menu item with the specified identifier.
* `resizable` - only relevant to the `DIALOG` screen open mode. Controls window resizing ability. Possible values − `true`, `false`. By default, the main menu does not affect the ability to resize dialog windows.
* `stylename` - defines a style name for the menu item. See xref:jmix:ui:themes.adoc[Themes] for details.

== Item Properties

`properties` is a nested element of `item`. It defines a set of properties to pass to the screen’s public setters. Each property is defined in the `property` element with the `name` attribute, which corresponds to a setter method. The setters are invoked by the framework between sending xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] and xref:ui:screens/screen-events.adoc#before-show-event[BeforeShowEvent].

`property` attributes:

* `name` - property name.
* `value` - property value for non-entity properties.
* `entityClass` - class of entity property.
* `entityId` - id of entity property.
//TODO after https://github.com/jmix-framework/jmix/issues/696
//** `entityView` - optional view for loading an entity property.

For example, the `filterVisible` boolean property in `menu.xml` corresponds to the void `setFilterVisible(Boolean value)` method in the screen controller:

.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-properties]
----

.CityBrowse.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/screen/city/CityBrowse.java[tags=set-value]
----

[[defining-menu-caption]]
== Defining Menu Caption

If the `caption` attribute is not specified, the localized name of a `menu` or `item` element is defined the following way: the `menu-config` prefix with a dot at the end is added to the element identifier; the resulting string is used as a key for the xref:localization:message-bundles.adoc[message bundle]. For example:

.messages.properties
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/messages.properties[tags=captions]
----

If the `id` is not set, the caption will be generated from the class name (if the `class` attribute is set), or the bean name and the bean method name (if the `bean` attribute is set). Therefore, setting the `id` attribute is recommended.

