= MenuConfig

`MenuConfig` – это специальный класс, который загружает структуру главного меню на основе файла, указанного в свойстве xref:ui:app-properties.adoc#jmix.ui.menu-config[jmix.ui.menu-config].

TIP: Используйте xref:studio:menu-designer.adoc[Дизайнер меню Studio] для определения структуры меню.

При создании нового проекта в Studio генерируется файл `menu.xml`, определяющий структуру главного меню приложения.

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=menu-config;menu]
----

Существует два xref:studio:menu-designer.adoc#menu-modes[режима] загрузки файлов, которые определяют структуру меню: composite (по умолчанию) и single.

Используйте свойство xref:ui:app-properties.adoc#jmix.ui.composite-menu[jmix.ui.composite-menu] для переключения между режимами.

Давайте детально рассмотрим файл `menu.xml`.

`menu-config` – это корневой XML-элемент. Элементы `menu-config` образуют древовидную структуру, где элементы `menu` являются ветвями, а элементы `item` и `separator` - листьями.

[[menu-attributes]]
== Атрибуты меню

`menu` – это вложенный элемент `menu-config`. Он обладает следующими атрибутами:

* `id` - уникальный идентификатор элемента.
* `caption` - заголовок элемента меню. Если он не задан, заголовок будет определяться в соответствии с правилом, описанным <<defining-menu-caption,ниже>>.
* `description` - текст, отображаемый в виде всплывающей подсказки при наведении курсора мыши. Вы можете использовать локализованные сообщения из xref:localization:message-bundles.adoc[пакета сообщений].
* `icon` - значок элемента `menu`. Подробнее см. в разделе xref:ui:icons.adoc[Значки].
* `insertBefore`, `insertAfter` - определяют, должен ли элемент быть вставлен до или после определенного элемента или пункта меню с указанным идентификатором. Эти атрибуты используются для вставки элемента в соответствующее место в меню, определенном в файлах xref:jmix:ROOT:add-ons.adoc[дополнений]. Не используйте атрибуты `insertBefore` и `insertAfter` одновременно.
* `stylename` - определяет название стиля для пункта меню. Подробнее см. в разделе xref:jmix:ui:themes.adoc[Темы].
* `expanded` - определяет, должен ли элемент `menu` быть развернут при открытии главного экрана. Значение по умолчанию - `false`.

Например:

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=menu]
----

[[item-attributes]]
== Атрибуты Item

`item` – это вложенный элемент `menu`. Он обладает следующими атрибутами:

* `id` - уникальный идентификатор элемента. Если атрибуты `screen`, `bean`, `class` не определены, `id` используется для указания на экран с тем же `id`. Когда пользователь нажимает на пункт меню, на xref:ui:screens/root-screens.adoc#main-screen[главном экране] открывается соответствующий экран.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-id]
----

* `caption` - заголовок элемента `item`. Если значение не задано, заголовок будет определяться в соответствии с правилом, описанным <<defining-menu-caption,ниже>>.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-caption]
----

* `description` - текст, который отображается в виде всплывающей подсказки при наведении курсора мыши. Вы также можете использовать локализованные сообщения из xref:localization:message-bundles.adoc[пакета сообщений].

* `screen` - идентификатор экрана. Его можно использовать для многократного включения одного экрана в меню. Когда пользователь нажимает на пункт меню, на главном экране открывается соответствующий экран.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-screen]
----
* `bean` - имя бина. Должен использоваться вместе с `beanMethod`. Метод бина вызывается, когда пользователь нажимает на пункт меню.
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-bean]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/bean/MenuBean.java[tags=start;menu-bean;end]
----
+
Вы можете передать параметры из пункта меню в метод бина, используя вложенный элемент <<item-properties,properties>>. Например:
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=bean-method]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/bean/MenuBean.java[tags=start;method-with-params;end]
----

* `class` - полное имя класса, который реализует интерфейс `MenuItemRunnable`. Когда пользователь нажимает на пункт меню, создается экземпляр указанного класса и вызывается его метод.
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-class]
----
+
.CustomMenu.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/app/CustomMenu.java[tags=custom-menu]
----

* `shortcut` - сочетание клавиш для данного пункта меню. Возможные модификаторы - `ALT`, `CTRL`, `SHIFT` - разделяются знаком “-”. Например:
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-shortcut]
----
+
Сочетания клавиш также можно настроить в файле `application.properties` и затем следующим образом использовать в файле `menu.xml`:
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-shortcut-prop]
----
+
.application.properties
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=menu-item-shortcut]
----
* Атрибут `openMode` определяет, как будет открываться экран. Он соответствует перечислению `OpenMode` со значениями: `NEW_TAB`, `DIALOG`, `NEW_WINDOW`. Значение по умолчанию - `NEW_TAB`.
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-open-mode]
----
* `icon` - значок элемента `item`. Подробнее см. в xref:ui:icons.adoc[Значки].
* `insertBefore`, `insertAfter` - определяют, должен ли элемент быть вставлен до или после определенного элемента или пункта меню с указанным идентификатором.
* `resizable` - относится только к режиму открытия окна `DIALOG`. Управляет возможностью изменения размера окна. Возможные значения − `true`, `false`. По умолчанию главное меню не влияет на возможность изменять размер диалоговых окон.
* `stylename` - определяет название стиля для пункта меню. Подробнее см. в xref:jmix:ui:themes.adoc[Темы].

[[item-properties]]
== Свойства Item

`properties` – это вложенный элемент `item`. Он определяет набор свойств для передачи публичным сеттерам экрана. Каждое свойство определяется в элементе `property` с атрибутом `name`, который соответствует методу сеттера. Сеттеры вызываются фреймворком между отправкой xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] и xref:ui:screens/screen-events.adoc#before-show-event[BeforeShowEvent].

Атрибуты `property`:

* `name` - название свойства.
* `value` - значение `property` для свойств, не являющихся сущностями.
* `entityClass` - класс свойства сущности.
* `entityId` - идентификатор свойства сущности.
* `entityFetchPlan` - необязательный xref:data-access:fetching.adoc#fetch-plan[фетч-план] для загрузки свойства сущности.

Например, логическое свойство `filterVisible` в `menu.xml` соответствует недействительному методу `setFilterVisible(Boolean value)` в контроллере экрана:

.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-properties]
----

.CityBrowse.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/screen/city/CityBrowse.java[tags=set-value]
----

Пример со свойством сущности:

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=property-entity]
----

[[defining-menu-caption]]
== Определение заголовка меню

Если атрибут `caption` не указан, локализованное имя элемента `menu` или `item` определяется следующим образом: к идентификатору элемента добавляется префикс `menu-config` с точкой в конце; результирующая строка используется в качестве ключа для xref:localization:message-bundles.adoc[пакета сообщений]. Например:

.messages.properties
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/messages.properties[tags=captions]
----

Если `id` не задан, заголовок будет сгенерирован на основе имени класса (если установлен атрибут `class`) или имени бина и имени метода бина (если установлен атрибут `bean`). Поэтому рекомендуется все же установить атрибут `id`.

