= MenuConfig

`MenuConfig` 是一个特殊的类，根据 xref:ui:app-properties.adoc#jmix.ui.menu-config[jmix.ui.menu-config] 应用程序属性的定义加载主菜单结构。

TIP: 使用 xref:studio:menu-designer.adoc[Studio 菜单设计器] 定义菜单结构。

当使用 Studio 新建项目时，会生成包含应用程序主菜单结构的 `menu.xml` 文件。

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=menu-config;menu]
----

有两种加载菜单结构定义文件的 xref:studio:menu-designer.adoc#menu-modes[模式]：composite（默认）和 single。

使用 xref:ui:app-properties.adoc#jmix.ui.composite-menu[jmix.ui.composite-menu] 应用程序属性切换这两种模式。

下面详细了解 `menu.xml` 文件的内容。

`menu-config` 是 XML 根元素。`menu-config` 内部的元素组成了一个树状结构，其中 `menu` 元素是分枝而 `item` 和 `separator` 元素是叶子结点。

[[menu-attributes]]
== menu 属性

`menu` 是 `menu-config` 的内部元素。具有下列属性：

* `id` - 元素的唯一标识符。
* `caption` - `menu` 元素的标题。如果未设置，则会用 <<defining-menu-caption,下面>> 介绍的规则确定标题。
* `description` - 鼠标悬停时展示的提示文字。可以使用 xref:localization:message-bundles.adoc[消息包] 中的本地化消息。
* `icon` - `menu` 元素的图标。参阅 xref:ui:icons.adoc[图标] 章节了解详情。
* `insertBefore`、`insertAfter` - 将当前菜单放在某个特定元素或指定了 id 的菜单项之前或之后。这些属性用来将一个菜单项放置于 xref:jmix:ROOT:add-ons.adoc[扩展组件] 中定义菜单中的合适位置。不要同时使用 `insertBefore` 和 `insertAfter`。
* `stylename` - 定义菜单项的样式名。参阅 xref:jmix:ui:themes.adoc[主题] 了解详情。
* `expanded` - 定义是否在打开主界面时展开此 `menu` 元素。默认为 `false`。

示例：

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=menu]
----

[[item-attributes]]
== item 属性

`item` 是 `menu` 的内部元素。具有下列属性：

* `id` - 元素的唯一标识符。如果没有定义 `screen`、`bean`、`class` 属性，则可以使用 `id` 指向同名界面。当用户点击时，会在 xref:ui:screens/root-screens.adoc#main-screen[主界面] 打开相应的界面。
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-id]
----

* `caption` - `item` 元素的标题。如果未设置，则会用 <<defining-menu-caption,下面>> 介绍的规则确定标题。
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-caption]
----

* `description` - 鼠标悬停时展示的提示文字。可以使用 xref:localization:message-bundles.adoc[消息包] 中的本地化消息。

* `screen` - 界面标识符。可以用来在多个菜单打开同一界面。当用户点击时，会在 xref:ui:screens/root-screens.adoc#main-screen[主界面] 打开相应的界面。
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-screen]
----
* `bean` - bean 名称。必须与 `beanMethod` 一起使用。当用户点击时，执行 bean 方法。
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-bean]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/bean/MenuBean.java[tags=start;menu-bean;end]
----
+
使用 <<item-properties,properties>> 内部元素可以从菜单项传递参数至 bean 方法。示例：
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=bean-method]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/bean/MenuBean.java[tags=start;method-with-params;end]
----

* `class` - 一个实现了 `MenuItemRunnable` 接口的类全限定名称。当用户点击时，会创建指定类的实例并执行接口方法。
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-class]
----
+
.CustomMenu.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/app/CustomMenu.java[tags=custom-menu]
----

* `shortcut` - 菜单项的键盘快捷键。可选的修饰键：`ALT`、`CTRL`、`SHIFT`，由“-”字符分隔。示例：
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-shortcut]
----
+
快捷键可以在 `application.properties` 文件配置，在 `menu.xml` 文件使用：
+
.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-shortcut-prop]
----
+
.application.properties
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=menu-item-shortcut]
----
* `openMode` 属性定义界面打开的方式。对应 `OpenMode` 枚举，支持：`NEW_TAB`、`DIALOG`、`NEW_WINDOW`。默认值为 `NEW_TAB`。
+
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-open-mode]
----
* `icon` - `item` 元素的图标。参阅 xref:ui:icons.adoc[图标] 章节了解详情。
* `insertBefore`、`insertAfter` - 将当前菜单放在某个特定元素或指定了 id 的菜单项之前或之后。
* `resizable` - 仅在以 `DIALOG` 模式打开界面有效。控制弹窗是否可改变大小。可设置为 `true` 或 `false`。默认情况下，主菜单对窗口是否可以改变大小没有限制。
* `stylename` - 定义菜单项的样式名。参阅 xref:jmix:ui:themes.adoc[主题] 了解详情。

[[item-properties]]
== item 的元素

`properties` 是 `item` 的内部元素。用于定义传递给界面公共 setter 的一组属性参数。每个属性参数在 `property` 元素内使用 `name` 属性定义，名称对应于一个 setter 方法。框架在界面的 xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] 和 xref:ui:screens/screen-events.adoc#before-show-event[BeforeShowEvent] 事件之间调用 setter。

`property` 属性：

* `name` - 属性名称。
* `value` - 非实体属性的属性值。
* `entityClass` - 实体属性的类。
* `entityId` - 实体属性的 id。
* `entityFetchPlan` - 可选参数，设置用于加载实体属性的 xref:data-access:fetching.adoc#fetch-plan[fetch plan]。

例如，`menu.xml` 中的 `filterVisible` 布尔属性对应界面控制器中的 `void setFilterVisible(Boolean value)` 方法：

.menu.xml
[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=item-properties]
----

.CityBrowse.java
[source,java,indent=0]
----
include::example$/ex2/src/main/java/ui/ex2/screen/city/CityBrowse.java[tags=set-value]
----

使用实体属性的示例：

[source,xml,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/menu.xml[tags=property-entity]
----

[[defining-menu-caption]]
== 定义菜单标题

如果 `caption` 属性未定义，则 `menu` 或 `item` 元素的本地化名称通过这种方式定义：以 `menu-config` 作为前缀，再加上元素的 `id`，中间以 “.” 分隔。形成的字符串作为 xref:localization:message-bundles.adoc[消息包] 的键值。示例：

.messages.properties
[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/ui/ex2/messages.properties[tags=captions]
----

如果 `id` 未设置，则标题会使用类名（如果设置了 `class` 属性）或 bean 名称及方法（如果设置了 `bean` 属性）生成。因此，我们推荐最好设置 `id` 属性。

