= Opening Screens
:page-aliases: backoffice-ui:opening-screens.adoc

You can open screens from the xref:ui:screens/root-screens.adoc#main-screen[main screen], by a xref:ui:actions/standard-actions.adoc[standard action] when working with browse and edit entity screens or programmatically from another screen. This section describes how to open screens programmatically.
//or by navigating to a URL

[[using-screens-interface]]
== Using Screens Interface

The `Screens` interface allows you to create and show screens of any type.

Suppose we have a screen to show a message with some special formatting. A controller can look this way:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/FancyMessageScreen.java[tags=fancy-screen1;label;fancy-screen2;end]
----
<1> Injects xref:ui:vcl/components/label.adoc[Label] component.
<2> The method receives a `String` screen parameter.
<3> Subscribtion on the `ClickEvent`. 

XML descriptor:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/open/fancy-message-screen.xml[tags=fancy-screen]
----

Then we can create and open it from another screen as follows:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=inject-screens;show-screen]
----
<1> Creates a screen instance.
<2> Provides a parameter for the screen.
<3> Shows the screen.

If the screen does not require any parameters from the caller code, you can create and open it in one line:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=inject-screens;show-line]
----

NOTE: Pay attention that `Screens` is not a Spring bean, so you can only inject it to screen controllers or obtain using `ComponentsHelper.getScreenContext(component).getScreens()` static method.

[[using-screenbuilders-bean]]
== Using ScreenBuilders Bean

`ScreenBuilders` bean allows you to open all kinds of screens with various parameters.

Below is an example of using it for opening a screen and executing some code after the screen is closed:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=screen-builders;notifications;show-other-screen]
----

[[opening-editor-screens]]
=== Opening Editor Screens

In most cases you can open editor screens using xref:ui:actions/standard-actions.adoc[standard actions] such as xref:ui:actions/standard-actions/create-action.adoc[CreateAction]. Let's look at the examples when you can use the `ScreenBuilders` API directly to open a screen from xref:ui:actions/base-action.adoc[BaseAction] or xref:ui:vcl/components/button.adoc[Button] handler.

The default editor screen is determined by the following procedure:

. If an editor screen annotated with xref:ui:screens/annotations.adoc#primary-editor-screen[@PrimaryEditorScreen] exists, it is used.
. Otherwise, an editor screen with `<entity_name>.edit` id is used, for example, `sales_Customer.edit`.

Example of opening a default editor for the `Customer` entity instance:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=screen-builders;edit-customer]
----

In this case, the editor will update the entity, but the caller screen will not receive the updated instance.

Often you need to edit an entity displayed by some `Table` or `DataGrid` component. Then you should use the following form of invocation, which is more concise and automatically updates the table:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=group-table;screen-builders;edit-from-table]
----

In order to create a new entity instance and open the editor screen for it, just call the `newEntity()` method on the builder:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=group-table;screen-builders;create]
----

`ScreenBuilder` provides a lot of methods to set optional parameters of the opened screen. For example, the following code creates an entity first initializing the new instance, in a particular editor opened as a dialog:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=group-table;screen-builders;edit-customer;create-with-parameter]
----
<1> Initializes a new instance.
<2> Specifies an editor screen.
<3> Opens as a dialog.

[[opening-lookup-screens]]
=== Opening Lookup Screens

Let's look at some examples of working with lookup screens. As with editor screens, you mostly open such screens using xref:ui:actions/standard-actions.adoc[standard actions] such as xref:ui:actions/standard-actions/entity-lookup-action.adoc[EntityLookupAction]. The examples below shows the usage of `ScreenBuilders` API and can be useful if you don’t use standard actions.

The default lookup screen is determined by the following procedure:

. If a lookup screen annotated with xref:ui:screens/annotations.adoc#primary-lookup-screen[@PrimaryLookupScreen] exists, it is used.
. Otherwise, if a screen with `<entity_name>.lookup` id exists, it is used, for example, `sales_Customer.lookup`.
. Otherwise, a screen with `<entity_name>.browse` id is used, for example, `sales_Customer.browse`.

Entity lookup screens can also be opened with various parameters. In the example below, lookup screen of the `Customer` entity is opened and the name of the selected customer is written to the `textField`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=text-field;screen-builders;lookup]
----

If you need to set the looked up entity to a field, use the more concise form:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=entity-picker;screen-builders;lookup-select]
----

As with edit screens, use the builder methods to set optional parameters of the opened screen. For example, the following code looks up the `Customer` entity using a particular lookup screen opened as a dialog:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens.java[tags=text-field;screen-builders;lookup-with-parameter]
----

[[passing-parameters-to-screens]]
== Passing Parameters to Screens

The recommended way of passing parameters to an opened screen is to use public setters of the screen controller, as demonstrated in the example <<using-screens-interface,above>>. With this approach, you can pass parameters to screens of any type, including entity edit and lookup screens opened using <<using-screenbuilders-bean,ScreenBuilders>> or from the main menu. 

The invocation of the `FancyMessageScreen` using `ScreenBuilders` with passing the parameter looks as follows:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens2.java[tags=screen-builders;show-fancy-message]
----

If you are opening a screen using a standard action such as xref:ui:actions/standard-actions/create-action.adoc[CreateAction], use its `screenConfigurer` handler to pass parameters via screen public setters.

Another way is to define a special class for parameters and pass its instance to the standard `withOptions()` method of the screen builder. The parameters class must implement the `ScreenOptions` marker interface. For example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/FancyMessageOptions.java[tags=fancy-options]
----

In the opened `FancyMessageScreen` screen, the options can be obtained in xref:ui:screens/screen-events.adoc#init-event[InitEvent] and xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] handlers:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/FancyMessageScreen.java[tags=label;on-init]
----

The invocation of the `FancyMessageScreen` screen using `ScreenBuilders` with passing `ScreenOptions` looks as follows:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens3.java[tags=screen-builders;fancy-screen]
----

As you can see, this approach requires type casting in the controller receiving the parameters, so use it wisely and prefer the type-safe setters approach explained above.

If you are opening a screen using a standard action such as xref:ui:actions/standard-actions/create-action.adoc#create-action[CreateAction], use its `screenOptionsSupplier` handler to create and initialize the required `ScreenOptions` object.

Usage of the `ScreenOptions` object is the only way to get parameters if the screen is opened from a screen based on the legacy API. In this case, the options object is of type `MapScreenOptions` and you can handle it in the opened screen as follows:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/FancyMessageScreen2.java[tags=label;on-init]
----

[[executing-code-after-close]]
== Executing Code after Close and Returning Values

Each screen sends `AfterCloseEvent` when it closes. You can add a listener to a screen to be notified when the screen is closed, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens2.java[tags=screens;notifications;show-other-screen]
----

When using `ScreenBuilders`, the listener can be provided in the `withAfterCloseListener()` method:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens3.java[tags=screen-builders;notifications;show-other-screen]
----

The event object provides information about how the screen was closed. This information can be obtained in two ways: 

* By testing whether the screen was closed with one of standard outcomes defined by the `StandardOutcome` enum.
* By getting the `CloseAction` object. The former approach is simpler, while the latter is much more flexible.

Let’s consider the first approach: close a screen with a standard outcome and test it in the calling code. Here is the screen that we envoke:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/OtherScreen.java[tags=other-screen]
----
<1> By clicking the *Ok* button sets some result state and close the screen with `StandardOutcome.COMMIT` enum value.
<2> By clicking the *Cancel* button closes the screen with `StandardOutcome.CLOSE`.

In the `AfterCloseEvent` listener, you can check how the screen was closed using the `closedWith()` method of the event, and read the result value if needed:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens4.java[tags=screen-builders;notifications;show-other-screen]
----

[[using-custom-close-action]]
=== Using Custom CloseAction
Another way of returning values from screens is using custom `CloseAction` implementations. Let’s rewrite the above example to use the following action class:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/MyCloseAction.java[tags=my-close-action]
----

Then we can use this action when closing the screen:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/NewOtherScreen.java[tags=new-other-screen]
----
<1> By clicking the *Ok* button creates the custom close action and sets the result value in it.
<2> By clicking the *Cancel* button closes with a default action provided by the framework.

In the `AfterCloseEvent` listener, you can get the `CloseAction` from the event and read the result value:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/open/ShowScreens4.java[tags=screens;notifications;show-new-other-screen]
----

As you can see, when values are returned through a custom `CloseAction`, the caller doesn’t have to know the opened screen class because it doesn’t invoke methods of the concrete screen controller. So the screen can be created by its string id.

Of course, the same approach for returning values through close actions can be used when opening screens using `ScreenBuilders`.
