= Подключаемые фабрики компонентов

Механизм подключаемых фабрик компонентов расширяет процедуру генерации компонентов и позволяет создавать различные поля редактирования в xref:ui:vcl/components/form.adoc[Form], xref:ui:vcl/components/table.adoc[Table] и xref:ui:vcl/components/data-grid.adoc[DataGrid]. Это означает, что компоненты приложения или сам ваш проект могут предоставлять собственные стратегии, которые будут создавать нестандартные компоненты и/или поддерживать кастомные типы данных.

Точкой входа в данный механизм является метод `UiComponentsGenerator.generate(ComponentGenerationContext)`. Сначала он пытается найти все реализации интерфейса `ComponentGenerationStrategy`. Если как минимум одна реализация существует, то он обходит все реализации в соответствии с интерфейсом `org.springframework.core.Ordered` и возвращает первый созданный не нулевой компонент.

Реализации интерфейса `ComponentGenerationStrategy` используются при создании UI компонентов. Проект может содержать любое количество таких стратегий.

`ComponentGenerationContext` – класс, содержащий следующую информацию, которая может быть использована при создании компонента:

* `metaClass` - задает сущность, для которой создается компонент.
* `property` - задает атрибут сущности, для которой создается компонент.
* `valueSource` - источник данных, который может быть связан с компонентом.
* `options` - источник данных, который может быть связан с компонентом для показа опций.
* `xmlDescriptor` - XML-дескриптор с дополнительной информацией, в случае, если компонент объявлен в XML-дескрипторе.
* `targetClass` - целевой класс, для которого должен быть создан компонент, например `Form`, `Table`, `DataGrid`.

Существуют две встроенные стратегии:

* `DefaultComponentGenerationStrategy` используется для создания компонентов в соответствии с переданным объектом `ComponentGenerationContext`. Имеет значение `order` равное `JmixOrder.LOWEST_PLATFORM_PRECEDENCE` (1000). Более высокие значения интерпретируются как имеющие более низкий приоритет; самое низкое значение имеет самый высокий приоритет; одинаковые значения `order` приведут к произвольным позициям сортировки для затронутых объектов.
* `CustomDatatypesComponentGenerationStrategy` предназначена для генерации поля по умолчанию в соответствии с datatype, для которого не создали поле другие стратегии генерации. Например, если datatype является кастомным и не соответствует ни одному типу, для которого создает поля `DefaultComponentGenerationStrategy`. Имеет значение `order` равное `Integer.MAX_VALUE` (0x7fffffff).

Пример ниже показывает, как заменить стандартную генерацию поля в компоненте Form для определенного атрибута некоторой сущности.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/factory/SalesComponentGenerationStrategy.java[tags=strategy]
----
<1> Проверяет конкретное поле сущности `Order`.
<2> Проверяет, что компонент создан для компонента `Form`.
<3> Создает конкретный компонент `DatePicker`.
<4> Привязывает компонент к источнику данных.
<5> Возвращает значение `order` этого объекта.

Пример ниже показывает, как определить `ComponentGenerationStrategy` для некоторого xref:data-model:data-types.adoc[datatype].

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/factory/ColorComponentGenerationStrategy.java[tags=strategy]
----
