= Screens and Fragments
:page-aliases: backoffice-ui:screens.adoc

A screen is a main unit of Jmix UI. It contains visual components, data containers, and non-visual components. A screen can be displayed inside the main application window either in a tab or as a modal dialog.

The main part of the screen is a Java or Groovy class called xref:ui:screens/screen-controllers.adoc[controller]. A layout of the screen is usually defined in an XML file called xref:ui:screens/descriptors.adoc[descriptor].

In order to show a screen, the framework creates a new instance of the `Window` visual component, connects the window with the screen controller and loads the screen layout components as child components of the window. After that, the screen’s window is added to the main application window.

A fragment is another UI building block that can be used as a part of screens and other fragments. It is very similar to screen internally but has a specific lifecycle and the `Fragment` visual component instead of `Window` at the root of the components tree. Fragments also have controllers and XML descriptors.

TIP: Use xref:studio:screen-wizard.adoc[Studio screen wizard] to create screens from templates, and xref:studio:screen-designer.adoc[Studio screen designer] to set up screens.
