= Using Screen Fragments
:page-aliases: backoffice-ui:using-fragments.adoc

This section explains how to define and use xref:ui:screens.adoc[screen fragments]. See also xref:ui:screens/screen-fragment-events.adoc[ScreenFragment Events] for how to handle fragment lifecycle events.

[[declarative-usage]]
== Declarative Usage

Suppose we have a fragment for entering an address.

.AddressFragment.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java1;fragment-java2]
----

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/address-fragment2.xml[tags=fragment-xml]
----

Then we can include it to another screen using the `fragment` element with the `screen` attribute pointing to the fragment id, specified in its `@UiController` annotation:

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/host-screen1.xml[tags=fragment-in-screen]
----

The `fragment` element can be added to any UI container of the screen, including the top-level layout element.

[[programmatic-usage]]
== Programmatic Usage

The same fragment can be included in the screen programmatically in a xref:ui:screens/screen-events.adoc#init-event[InitEvent] or xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] handler as follows:

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/host-screen.xml[tags=fragment-in-screen]
----

.HostScreen.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/HostScreen.java[tags=host-screen]
----
<1> Injects the `Fragments` bean which is designed to instantiate screen fragments.
<2> Creates the fragment’s controller by its class.
<3> Gets the `Fragment` visual component from the controller and adds it to a UI container.

TIP: If a fragment has parameters, you can set them via public setters prior to adding the fragment to the screen. Then the parameters will be available in `InitEvent` and `AfterInitEvent` handlers of the fragment controller.

[[passing-parameters-to-fragments]]
== Passing Parameters to Fragments

A fragment controller can have public setters to accept parameters as it is done when opening screens, for example:

.AddressFragment.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java3;fragment-java4;fragment-java2]
----
<1> Setter methods allows you to pass parameters to the screen fragment.
<2> An example of parameters usage.

If the fragment is opened programmatically, the setters can be invoked explicitly:

.HostScreen.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/HostScreen2.java[tags=param]
----
<1> Passes a parameter before adding the fragment to the screen.

If the fragment is added to the screen declaratively in XML, use the `properties` element to pass the parameters, for example:

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/host-screen3.xml[tags=param]
----
<1> Passes a string parameter to the `setZipcode()` method.
<2> Passes a data container to the `setAddressContainer()` method.

Use the `value` attribute to specify values and the `ref` attribute to specify identifiers of the screen components. Setters must have parameters of appropriate types.

[[using-data-components]]
== Using Data Components

A screen fragment can have its own data containers and loaders defined in the `data` XML element. At the same time, the framework creates a single instance of xref:ui:data/data-context.adoc[DataContext] for the screen and all its fragments. Therefore all loaded entities are merged to the same context, and their changes are saved when the host screen is committed.

In the following example, we consider usage of own data containers and loaders in a screen fragment.

Suppose we have a `Country` entity and in the fragment, instead of the text field, we want to show a drop-down list with available cities. We can define data components in the fragment descriptor as we would in a regular screen:

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/address-fragment3.xml[tags=country]
----

When the host screen is opened, data will be loaded in the fragment.

[[provided-data-containers]]
=== Provided Data Containers 

The next example demonstrates how to use data containers of the host screen in the fragment.

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/country-screen.xml[tags=host-screen]
----
<1> Data container that is used in the fragment below.

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/address-fragment.xml[tags=fragment]
----
<1> `provided="true"` means that the container with the same id must exist in a host screen or enclosing fragment.
<2> UI component is linked to the provided data container.

In the XML element having `provided="true"`, all attributes except id are ignored but can be present to provide information for design time tools.

[CAUTION]
====
When providing a data container from the host screen to a fragment, make sure that the loaders' identifiers correspond.

. If you set `provided="true"` for the fragment’s container, loaders' identifiers are not necessary (as in the example above).
. If you define the loader in the fragment explicitly, its `id` should be the same as the host loader `id`. In this case, please don't forget to set `provided="true"` for the fragment loader:
+
[source,xml,indent=0]
----
<loader id="addressDl" provided="true"/>
----
====