= Использование фрагментов экранов

В данном разделе рассматриваются примеры определения и использования xref:ui:screens.adoc[фрагментов экранов]. См. также раздел xref:ui:screens/screen-fragment-events.adoc[События ScreenFragment] для получения информации о событиях жизненного цикла фрагментов.

[[declarative-usage]]
== Декларативное использование

Предположим, имеется фрагмент для ввода адреса:

.AddressFragment.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java1;fragment-java2]
----

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/address-fragment2.xml[tags=fragment-xml]
----

Он может быть включен в некоторый экран с помощью элемента `fragment` с атрибутом `screen`, указывающим на id фрагмента, который задан в аннотации `@UiController`:

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/host-screen1.xml[tags=fragment-in-screen]
----

Элемент `fragment` может быть добавлен в любой UI-контейнер экрана, в том числе в корневой элемент `layout`.

[[programmatic-usage]]
== Программное использование

Тот же самый фрагмент может быть включен в экран программно в обработчике xref:ui:screens/screen-events.adoc#init-event[InitEvent] или xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] как показано ниже:

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/host-screen.xml[tags=fragment-in-screen]
----

.HostScreen.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/HostScreen.java[tags=host-screen]
----
<1> Инжектирование бина `Fragments`, который предназначен для инстанциирования фрагментов.
<2> Создание экземпляра контроллера фрагмента по его классу.
<3> Получение визуального компонента `Fragment` из контроллера и добавление его в UI-контейнер.

TIP: Если фрагменту нужны какие-либо параметры, установите их через публичные сеттеры перед добавлением фрагмента в экран. Тогда параметры будут доступны в обработчиках событий `InitEvent` и `AfterInitEvent` контроллера фрагмента.

[[passing-parameters-to-fragments]]
== Передача параметров в фрагменты

Контроллер фрагмента может иметь публичные сеттеры для получения параметров, как это делается при открытии экранов. Например:

.AddressFragment.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java3;fragment-java4;fragment-java2]
----
<1> Setter methods allows you to pass parameters to the screen fragment.
<2> An example of parameters usage.

Если фрагмент открывается программно, то сеттеры можно вызвать явно:

.HostScreen.java
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/HostScreen2.java[tags=param]
----
<1> Передача параметра перед добавлением фрагмента в экран.

Если фрагмент добавляется в экран декларативно в XML, для передачи параметров можно использовать элемент `properties`, например:

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/host-screen3.xml[tags=param]
----
<1> Передача строкового параметра в метод `setZipcode()`.
<2> Передача контейнера данных в метод `setAddressContainer()`.

Атрибут `value` используется для указания значений, атрибут `ref` – для указания идентификаторов компонентов экрана. Сеттеры должны иметь параметры подходящего типа.

[[using-data-components]]
== Компоненты данных в фрагментах

Фрагмент экрана может иметь свои собственные контейнеры и загрузчики данных, определенные в XML-элементе `data`. В то же время, фреймворк создает единственный экземпляр xref:ui:data/data-context.adoc[DataContext] для экрана и всех его фрагментов. Поэтому все загруженные сущности помещаются в один контекст и их изменения сохраняются, когда экран выполняет коммит.

Далее рассматривается пример использования собственных контейнеров и загрузчиков в фрагменте.

Предположим, имеется сущность `Country`, и во фрагменте вместо текстового поля необходимо отобразить выпадающий список с имеющимися городами. Во фрагменте можно определить компоненты данных точно так же, как в обычном экране:

.address-fragment.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/address-fragment3.xml[tags=country]
----

Когда откроется включающий экран, данные будут загружены в фрагмент.

[[provided-data-containers]]
=== Контейнеры данных, предоставляемые экраном

Следующий пример демонстрирует использование контейнеров данных, предоставляемых включающим экраном.

.host-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/country-screen.xml[tags=host-screen]
----
<1> Контейнер данных, который используется фрагментом ниже.

.addreess-fragment.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/fragments/address-fragment.xml[tags=fragment]
----
<1> `provided="true"` означает, что контейнер с таким же id должен существовать во включающем экране или фрагменте, т.е. должен быть предоставлен извне.
<2> UI-компоненты соединены с предоставленным контейнером данных.

В XML-элементе, имеющем `provided="true"`, все атрибуты за исключением id игнорируются, но могут присутствовать для обеспечения работы инструментов разработки.