= image 图片
:page-aliases: vcl/components/image.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/image-simple" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`image` 用户展示不同来源的图片。该组件可以与 xref:vc/common-attributes.adoc#dataContainer[数据容器] 绑定或通过编程的方式设置。

* XML 元素：`image`

* Java 类：`JmixImage`

[[basics]]
== 基本用法

图片可以作为 `FileRef` 或 `byte[]` 类型的实体属性。下面的示例中，`User` 实体的 `picture` 属性关联 xref:files:file-storage.adoc[文件存储] 中的某个文件：

[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/entity/User.java[tags=user-entity;picture]
----

如需展示该属性的图片，可直接在组件中指定 xref:vc/common-attributes.adoc#dataContainer[dataContainer] 和 xref:vc/common-attributes.adoc#property[property] 属性。

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=data;instance;facets;layout;fileRefImage]
----

[[resources]]
== 资源

此外，`image` 组件可以展示不同资源的图片。可以在 XML中声明式的配置资源类型，或通过 `setSrc()` 方法编程式设置。

[[static-resource]]
=== 静态资源

应用程序可以提供静态图片地址。

默认情况下，静态内容在 classpath 的 `/static`、`/public`、`/resources` 或 `/META-INF/resources` 文件夹（详情请参考： https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[Spring Boot 文档^]）。

* XML 中：
+
如果图片位于 `/src/main/resources/META-INF/resources`，比如 `/src/main/resources/META-INF/resources/icons/icon.png`，可以按照下列方式指定图片：
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=static-resource]
----
+
* Java 中：
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-static]
----

[[url-resource]]
=== URL 资源

类似地，图片也可以通过任意 URL 加载。

* XML 中：
+
[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=url-resource]
----

* Java 中：
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-url]
----

// [[file-resource]]
// === FileResource

// [[file-storage-resource]]
// === FileStorageResource

[[stream-resource]]
=== 图片流

图片可以通过 `InputStream` 提供。

* Java 中：使用 `StreamResource` 接口。
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-stream]
----

// [[theme-resource]]
// === ThemeResource

== XML 属性

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
<<alternateText, alternateText>> -
<<ariaLabel, ariaLabel>> -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
<<resource, resource>> -
xref:vc/common-attributes.adoc#text[text] -
<<themeNames,themeNames>> -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
<<whiteSpace, whiteSpace>> -
xref:vc/common-attributes.adoc#width[width]

[[alternateText]]
=== alternateText

设置替换文本，当资源未设置或加载失败时展示。

[[ariaLabel]]
=== ariaLabel

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置一个单独的用于辅助功能的隐形标签，比如用于屏幕阅读器。

[[resource]]
=== resource

设置图片的资源。

[[themeNames]]
=== themeNames

为组件添加主题。支持：

* `fill`
* `contain`
* `cover`
* `scale-down`

[[whiteSpace]]
=== whiteSpace

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/white-space" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

定义组件的 `white-space` 样式值。支持：

* `NORMAL`
* `NOWRAP`
* `PRE`
* `PRE_WRAP`
* `PRE_LINE`
* `BREAK_SPACES`
* `INHERIT`
* `INITIAL`

== 事件和处理器

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
<<ClickEvent, ClickEvent>> -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

include::../handler-generation-tip.adoc[]

[[ClickEvent]]
=== ClickEvent

`com.vaadin.flow.component.ClickEvent` 在用户点击时发送。
