= image
:page-aliases: vcl/components/image.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/image-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`image` is designed to display images from different sources. The component can be bound to a xref:vc/common-attributes.adoc#dataContainer[data container] or configured programmatically.

* XML element: `image`

* Java class: `JmixImage`

[[basics]]
== Basics

An image can be represented as an entity attribute of `FileRef` or `byte[]` type. In the example below, the `picture` attribute of the `User` entity is a reference to a file in xref:files:file-storage.adoc[file storage]:

[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/entity/User.java[tags=user-entity;picture]
----

To display the image provided by this attribute, specify it in the component. For that, specify the xref:vc/common-attributes.adoc#dataContainer[data container] and xref:vc/common-attributes.adoc#property[property] attributes.

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=data;instance;facets;layout;fileRefImage]
----

[[resources]]
== Resources

Alternatively, the `image` component can display images from different resources. You can set the resource type declaratively using the nested XML elements described below, or programmatically using the `setSrc()` method.

[[static-resource]]
=== Static Resource

An image can be served statically by the application.

By default, static content is served from `/static`, `/public`, `/resources`, or `/META-INF/resources` directories of the classpath (see details in the https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[Spring Boot documentation^]).

* In XML:
+
For example, if your image is located
under `/src/main/resources/META-INF/resources`, such as `/src/main/resources/META-INF/resources/icons/icon.png`, you can specify the resource as follows:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=static-resource]
----
+
* In Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-static]
----

[[url-resource]]
=== URL Resource

Similarly, an image can be loaded from an arbitrary URL.

* In XML:
+
[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=url-resource]
----

* In Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-url]
----

// [[file-resource]]
// === FileResource

// [[file-storage-resource]]
// === FileStorageResource

[[stream-resource]]
=== Stream Resource

An image can be provided by an `InputStream`.

* In Java: `StreamResource` interface.
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-stream]
----

// [[theme-resource]]
// === ThemeResource

== Attributes

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
<<alternateText, alternateText>> -
<<ariaLabel, ariaLabel>> -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan]
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
<<resource, resource>> -
xref:vc/common-attributes.adoc#text[text] -
<<themeNames,themeNames>> -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
<<whiteSpace, whiteSpace>> -
xref:vc/common-attributes.adoc#width[width]

[[alternateText]]
=== alternateText

Sets an alternate text for an image in case the resource is not set or unavailable.

[[ariaLabel]]
=== ariaLabel

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets a separate, visually hidden label for accessibility technologies, such as screen readers.

[[resource]]
=== resource

Specifies the resource from which the image is obtained.

[[themeNames]]
=== themeNames

Adds a theme to the component. Possible values are:

* `fill`
* `contain`
* `cover`
* `scale-down`

[[whiteSpace]]
=== whiteSpace

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/white-space" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Defines the component's `white-space` style value. Possible values are:

* `NORMAL`
* `NOWRAP`
* `PRE`
* `PRE_WRAP`
* `PRE_LINE`
* `BREAK_SPACES`
* `INHERIT`
* `INITIAL`

== Handlers

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
<<ClickEvent, ClickEvent>> -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]

include::../handler-generation-tip.adoc[]

[[ClickEvent]]
=== ClickEvent

`com.vaadin.flow.component.ClickEvent` is sent when the user clicks on the image.