= Superset Properties

[[jmix.superset.url]]
== jmix.superset.url

Specifies Apache Superset server URL.

[[jmix.superset.username]]
== jmix.superset.username

The username of a Superset user under which Jmix application will communicate with Superset.

[[jmix.superset.password]]
== jmix.superset.password

The password of a Superset user under which Jmix application will communicate with Superset.

[[jmix.superset.access-token-refresh-schedule]]
== jmix.superset.access-token-refresh-schedule

The schedule delay that is used for monitoring whether the access token is expired.

Default value: `1m`

[[jmix.superset.csrf-token-refresh-schedule]]
== jmix.superset.csrf-token-refresh-schedule

The schedule delay that is used for monitoring whether the CSRF token is expired.

Default value: `1m`

[[jmix.superset.csrf-token-expiration]]
== jmix.superset.csrf-token-expiration

Specifies a lifespan of CSRF tokens. Unlike access tokens, a CSRF token does not contain information about expiration time, so the start time point is the timestamp of the successfully finished request.

If the value of CSRF token expiration time is changed in Superset, this property should be changed accordingly. By default, Superset configures 1 week for CSRF token.

Default value: `7d`

[[jmix.superset.csrf-protection-enabled]]
== jmix.superset.csrf-protection-enabled

Enables CSRF protection. CSRF token will be taken on Spring context refresh and will be sent in a guest token request.

Default value: `true`

[[jmix.superset.tokens-refresh-enabled]]
== jmix.superset.tokens-refresh-enabled

Enables configuration for automatically getting and refreshing Superset tokens (access, refresh, CSRF).

[[jmix.superset.ui.background-fetching-guest-token-timeout]]
== jmix.superset.ui.background-fetching-guest-token-timeout

Defines a timeout of background task that fetches guest token for xref:dashboard-component.adoc[SupersetDashboard] component in the default guest token provider.

Default value: `1m`