= Свойства Superset

[[jmix.superset.url]]
== jmix.superset.url

Указывает URL сервера Apache Superset.

[[jmix.superset.username]]
== jmix.superset.username

Имя пользователя Superset, под которым приложение Jmix будет взаимодействовать с сервером Superset.

[[jmix.superset.password]]
== jmix.superset.password

Пароль пользователя Superset, под которым приложение Jmix будет взаимодействовать с сервером Superset.

[[jmix.superset.access-token-refresh-schedule]]
== jmix.superset.access-token-refresh-schedule

Интервал проверки, истек ли срок действия токена доступа.

Значение по умолчанию: `1m`

[[jmix.superset.csrf-token-refresh-schedule]]
== jmix.superset.csrf-token-refresh-schedule

Интервал проверки, истек ли срок действия токена CSRF.

Значение по умолчанию: `1m`

[[jmix.superset.csrf-token-expiration]]
== jmix.superset.csrf-token-expiration

Указывает срок службы токенов CSRF. В отличие от токенов доступа, токен CSRF не содержит информации о времени истечения срока действия, поэтому начальной точкой является временная метка успешно завершенного запроса.

Если в Superset изменено значение времени истечения срока действия токена CSRF, это свойство должно быть изменено соответствующим образом. По умолчанию в Superset для токена CSRF задается 1 неделя.

Значение по умолчанию: `7d`

[[jmix.superset.csrf-protection-enabled]]
== jmix.superset.csrf-protection-enabled

Включает защиту CSRF. Токен CSRF будет получен при обновлении контекста Spring и отправлен в запросе гостевого токена.

Значение по умолчанию: `true`

[[jmix.superset.tokens-refresh-enabled]]
== jmix.superset.tokens-refresh-enabled

Включает настройку для автоматического получения и обновления токенов Superset (access, refresh, CSRF).

[[jmix.superset.ui.background-fetching-guest-token-timeout]]
== jmix.superset.ui.background-fetching-guest-token-timeout

Задает интервал выполнения фонового задания, которое извлекает гостевой токен для компонента xref:dashboard-component.adoc[SupersetDashboard] в провайдере гостевых токенов по умолчанию.

Значение по умолчанию: `1m`