= Аннотации контроллеров

Аннотации на классе контроллера используются для предоставления фреймворку информации об экране. Некоторые аннотации применимы для любого типа экрана, некоторые должны быть использованы только в экранах редактирования или поиска.

[[common-annotations]]
== Общие аннотации

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderScreen.java[tags=common-annotations]
----

* `@UiController` указывает, что данный класс является контроллером экрана. Значение аннотации задает id экрана, который используется для ссылки на экран из главного меню или при открытии экрана программно.
* `@UiDescriptor` соединяет контроллер с xref:ui:screens/descriptors.adoc[XML-дескриптором]. Значение аннотации указывает путь к файлу. Если значение содержит только имя файла, подразумевается что файл находится в том же пакете что и класс контроллера.
* `@MultipleOpen` указывает, что из главного меню можно открыть несколько экземпляров данного экрана. По умолчанию, когда пользователь выбирает пункт главного меню, фреймворк проверяет, не открыт ли наверху какой-либо вкладки главного окна экран с тем же классом и id. Если такой экран найден, он закрывается, и новый экран открывается в новой вкладке. Когда на экране присутствует аннотация @MultipleOpen, никаких проверок не производится, и новый экземпляр экрана просто открывается в новой вкладке.
+
Можно предоставить собственный способ проверки, является ли экран тем же самым, переопределив метод `isSameScreen()` контроллера.
+
* `@DialogMode` позволяет указать параметры геометрии и поведения экрана при открытии его в диалоговом окне. Данная аннотация соответствует элементу `<dialogMode>` дескриптора экрана и может быть использована вместо него. Значения из XML имеют более высокий приоритет для всех параметров кроме `forceDialog`. Если его значение `true` или в XML, или в аннотации, то экран всегда открывается в диалоге.

[[lookup-annotations]]
== Аннотации экранов выбора

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/order/OrderBrowse.java[tags=lookup-annotations]
----

* `@LookupComponent` указывает id UI-компонента, который должен быть использован для получения значения из экрана выбора.
+
Вместо использования данной аннотации, можно указать компонент выбора программно, переопределив метод контроллера `getLookupComponent()`.
+
[[primary-lookup-screen]]
* `@PrimaryLookupScreen` указывает, что данный экран является экраном выбора по умолчанию для сущностей заданного типа. Данная аннотация имеет больший приоритет чем конвенция `\{entity_name}.lookup` / `\{entity_name}.browse`.

[[editor-annotations]]
== Аннотации экранов редактирования

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/entity/order/OrderEdit.java[tags=edit-annotations]
----

[[edited-entity-container]]
* `@EditedEntityContainer` указывает xref:ui:data/data-containers.adoc[контейнер данных], содержащий редактируемую сущность.
+
Вместо использования данной аннотации, можно указать контейнер программно, переопределив метод контроллера `getEditedEntityContainer()`.
+
[[primary-editor-screen]]
* `@PrimaryEditorScreen` указывает, что данный экран является экраном редактирования по умолчанию для сущностей заданного типа. Данная аннотация имеет больший приоритет чем конвенция `\{entity_name}.edit`
