= XML-дескриптор экрана

Дескриптор экрана – это файл формата XML, декларативно описывающий xref:ui:vcl.adoc[визуальные компоненты], xref:ui:data-components.adoc[компоненты данных] и некоторые параметры экрана.

TIP: Используйте xref:studio:screen-designer.adoc[дизайнер экранов] Studio чтобы конфигурировать XML-дескрипторы.

Например, рассмотрим XML-дескриптор экрана редактирования:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/sample-screen.xml[tags=sample]
----

Корневой элемент `window` содержит следующие атрибуты:

* `messagesGroup` - an arbitrary xref:localization:message-bundles.adoc#group-and-key[message group] associated with this window. If the `messagesGroup` attribute is not defined messages are loaded from the package, associated with this screen class.
* `class` − имя xref:ui:screens/screen-controllers.adoc[контроллера].
* `caption` − заголовок экрана, который может содержать ссылку на сообщение из вышеуказанного пакета.
* `focusComponent` − идентификатор компонента, который получит фокус ввода при отображении экрана.
* `icon` - a window xref:vcl/xml.adoc#icon[icon].
* `extend` is used for xref:modularity:extension.adoc#ui[extending UI].

Элементы дескриптора:

* `data` − описывает компоненты данных экрана.
* `facets` - defines the list of xref:ui:facets.adoc[facets] for the screen.
* `actions` - defines the list of xref:ui:actions.adoc[actions] for the screen.
* `dialogMode` - определяет параметры геометрии и поведения экрана при открытии его в виде диалогового окна.
+
Атрибуты элемента `dialogMode`:
+
** `closeable` - определяет наличие в диалоговом окне кнопки закрытия. Возможные значения: `true`, `false`.
** `closeOnClickOutside` - определяет возможность закрыть окно кликом по окружающей области, если диалог открыт в модальном режиме. Возможные значения: `true`, `false`.
** `forceDialog` - указывает, что экран всегда должен открываться в виде диалога. Возможные значения: `true`, `false`.
** `height` - устанавливает высоту диалогового окна.
** `modal` - устанавливает модальный режим диалогового окна. Возможные значения: `true`, `false`.
** `positionX` - задает положение левого верхнего угла диалога по оси x.
** `positionY` - задает положение левого верхнего угла диалога по оси y.
** `resizable` - определяет возможность пользователя изменять размеры диалога. Возможные значения: `true`, `false`.
** `width` - устанавливает ширину диалогового окна.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/order-edit1.xml[tags=dialog-mode]
----
+
* `actions` – определяет список xref:ui:actions.adoc[действий] данного экрана.
* `facets` – определяет список фасетов данного экрана.
* `layout` − корневой элемент компоновки экрана.

* `layout` - a root element of the screen xref:ui:vcl/containers/layout.adoc[layout].