= XML Descriptors
:page-aliases: backoffice-ui:screens/descriptors.adoc

A screen descriptor is an XML file containing the declarative definition of xref:ui:vcl.adoc[visual components], xref:ui:data-components.adoc[data components], and some screen parameters.

TIP: Use xref:studio:screen-designer.adoc[Studio screen designer] to set up your XML descriptor.

For example, look at the XML descriptor of the edit screen:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/sample-screen.xml[tags=sample]
----

The `window` element is a root element that has the following attributes:

* `messagesGroup` - an arbitrary xref:localization:message-bundles.adoc#group-and-key[message group] associated with this window. If the `messagesGroup` attribute is not defined messages are loaded from the package, associated with this screen class.
* `caption` - a window xref:ui:vcl/xml.adoc#caption[caption] that can contain a link to a message from the messages group mentioned above.
* `description` - additional information about the window that can contain a link to a message from the messages group mentioned above.
* `icon` - a window xref:vcl/xml.adoc#icon[icon].
* `extend` is used for extending UI.
* `focusComponent` - an identifier of a component that should get input focus when the screen is displayed.

Elements of the descriptor:

* `data` - defines xref:ui:data-components.adoc[data components] of the screen.
* `facets` - defines the list of xref:ui:facets.adoc[facets] for the screen.
* `actions` - defines the list of xref:ui:actions.adoc[actions] for the screen.
* `dialogMode` - defines settings of geometry and behavior of the screen when it is opened as a dialog.
+
Attributes of the `dialogMode` element:
+
** `closeable` - defines whether the dialog window has a close button. Possible values: `true`, `false`.
** `closeOnClickOutside` - defines if the dialog window should be closed by clicking outside the window area when the window has a modal mode. Possible values: `true`, `false`.
** `forceDialog` - specifies that the screen should always be opened as a dialog. Possible values: `true`, `false`.
** `height` - sets the height of the dialog window.
** `modal` - specifies the modal mode for the dialog window. Possible values: `true`, `false`.
** `positionX` - sets the x position of the top-left corner of the dialog window.
** `positionY` - sets the y position of the top-left corner of the dialog window.
** `resizable` - defines whether a user can change the size of the dialog window. Possible values: `true`, `false`.
** `width` - sets the width of the dialog window.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/order-edit1.xml[tags=dialog-mode]
----

* `layout` - a root element of the screen layout.