= XML Descriptors
:page-aliases: backoffice-ui:screens/descriptors.adoc

Screen descriptor is an XML file containing declarative definition of xref:ui:vcl.adoc[visual components], xref:ui:data-components.adoc[data components] and some screen parameters. 

TIP: Use xref:studio:screen-designer.adoc[Studio screen designer] to set up your XML descriptor.

For example, look at the XML descriptor of the edit screen:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/sample-screen.xml[tags=sample]
----

The `window` element is a root element that has the following attributes:

* `class` − a name of the xref:ui:screens/screen-controllers.adoc[controller].
* `caption` − a window caption that can contain a link to a message from the pack mentioned above.
* `focusComponent` − an identifier of a component that should get input focus when the screen is displayed.

Elements of the descriptor:

* `data` − defines data components of the screen.
* `dialogMode` - defines settings of geometry and behavior of the screen when it is opened as a dialog.
+
Attributes of the `dialogMode` element:
+
** `closeable` - defines whether the dialog window has a close button. Possible values: `true`, `false`.
** `closeOnClickOutside` - defines if the dialog window should be closed by click outside the window area when the window has a modal mode. Possible values: `true`, `false`.
** `forceDialog` - specifies that the screen should always be opened as a dialog. Possible values: `true`, `false`.
** `height` - sets the height of the dialog window.
** `modal` - specifies the modal mode for the dialog window. Possible values: `true`, `false`.
** `positionX` - sets the x position of the top-left corner of the dialog window.
** `positionY` - sets the y position of the top-left corner of the dialog window.
** `resizable` - defines whether a user can change the size of the dialog window. Possible values: `true`, `false`.
** `width` - sets the width of the dialog window.
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/order-edit1.xml[tags=dialog-mode]
----
+
* `actions` – defines the list of xref:ui:actions.adoc[actions] for the screen.
* `facets` – defines the list of facets for the screen.
* `layout` − root element of the screen layout.
