= Методы контроллеров

В данном разделе описаны некоторые методы базовых классов контроллеров экранов, которые можно вызывать или переопределять в коде приложения.

[[methods-of-all-screens]]
== Методы всех экранов

* `show()` - отображает экран. Данный метод обычно вызывается после создания экрана, как описано в разделе xref:ui:opening-screens.adoc[Открытие экранов].
* `close()` - закрывает экран с переданным enum значением `StandardOutcome` или объектом `CloseAction`. Например:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderScreen.java[tags=close]
----
+
Значение параметра доступно в xref:ui:screens/screen-events.adoc#before-close-event[BeforeCloseEvent] и xref:ui:screens/screen-events.adoc#after-close-event[AfterCloseEvent], поэтому информация о причине закрытия экрана может быть получена в слушателях этих событий. Подробная информация об использовании этих слушателей приведена в разделе xref:ui:opening-screens.adoc#executing-code-after-close[Выполнение кода после закрытия и возврат значений].
+
* `getScreenData()` - возвращает объект `ScreenData`, в котором зарегистрированы все xref:ui:data-components.adoc[компоненты данных], объявленные в XML-дескрипторе экрана. Метод `loadAll()` этого объекта можно вызывать для срабатывания всех загрузчиков данных экрана:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderScreen.java[tags=get-screen-data]
----

[methods-of-standard-editor]
== Методы StandardEditor

* `getEditedEntity()` - когда экран открыт, возвращает экземпляр редактируемой сущности. Это экземпляр, установленный в контейнере данных, указанном аннотацией xref:ui:screens/annotations.adoc#edited-entity-container[@EditedEntityContainer].
+
В слушателях xref:ui:screens/screen-events.adoc#init-event[InitEvent] и xref:ui:screens/screen-events.adoc#after-init-event[AfterInitEvent] данный метод возвращает `null`. В слушателе xref:ui:screens/screen-events.adoc#before-show-event[BeforeShowEvent] данный метод возвращает экземпляр, переданный в экран для редактирования (позднее в процессе открытия экрана сущность перезагружается, и другой ее экземпляр устанавливается в контейнере данных).

Для закрытия экрана редактирования можно использовать следующие методы:

* `closeWithCommit()` - валидирует и сохраняет данные, затем закрывает экран с `StandardOutcome.COMMIT`.
* `closeWithDiscard()` - игнорирует несохраненные изменения и закрывает экран с `StandardOutcome.DISCARD`.

Если в экране есть несохраненные изменения в xref:ui:data/data-context.adoc[DataContext], при закрытии экрана отображается соответствующее сообщение. Вид данного сообщения можно настроить с помощью свойства приложения xref:ui:app-properties.adoc#jmix.ui.screen.use-save-confirmation[jmix.ui.screen.use-save-confirmation]. Если экран закрывается методом `closeWithDiscard()` или `close(StandardOutcome.DISCARD)` то несохраненные изменения игнорируются без каких-либо сообщений.

* `commitChanges()` - сохраняет изменения не закрывая экран. Данный метод можно вызвать из собственного слушателя события (например нажатия кнопки), или переопределить слушатель действия `windowCommit`, чтобы выполнить какие-либо операции после сохранения данных, например:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit1.java[tags=commit]
----
<1> Этот флажок используется для возврата правильного результата при последующем закрытии экрана.
<2> Вы можете выполнять действия после сохранения данных.

* `validateAdditionalRules()` можно переопределить для выполнения дополнительной валидации перед сохранением данных. Данный метод должен сохранить информацию об ошибках валидации в переданном ему объекте `ValidationErrors`. Впоследствии эта информация будет отображена вместе с ошибками стандартной процедуры валидации. Например:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit1.java[tags=validate]
----

[[methods-of-master-detail-screen]]
== Методы MasterDetailScreen

* `getEditedEntity()` - когда экран находится в режиме редактирования, возвращает экземпляр редактируемой сущности. Это экземпляр, установленный в контейнере данных компонента `form`. Если экран не в режиме редактирования, данный метод выбрасывает `IllegalStateException`.
* Метод `validateAdditionalRules()` можно переопределить для выполнения дополнительной валидации перед сохранением данных, как описано выше для `StandardEditor`.
