= Примеси экранов

Примеси позволяют создавать функциональность, которая может быть переиспользована во разных экранах без необходимости наследования этих экранов от общих базовых классов. Примеси реализуются с помощью интерфейсов Java с default-методами.

Примеси имеют следующие характеристики:

* Экран может иметь несколько примесей.
* В интерфейсе примеси можно подписываться на xref:ui:screens/screen-events.adoc[события экрана].
* Если необходимо, примесь может сохранять некоторое состояние в экране.
* Примесь может обращаться к компонентам экрана и инфраструктурным бинам, например xref:ui:dialogs.adoc[Dialogs], xref:ui:notifications.adoc[Notifications] и пр.
* Для параметризации поведения примеси, она может полагаться на аннотации экрана или вводить абстрактные методы, которые должен будет реализовать экран.

Обычно использование примеси заключается просто в реализации определенного интерфейса в контроллере экрана.

Примесь может использовать следующие классы для работы с экраном и инфраструктурой:

* `io.jmix.ui.screen.Extensions` предоставляет статические методы для сохранения и извлечения состояния из экрана, в котором примесь используется, а также для получения бина `BeanLocator`, который в свою очередь позволяет получить любой Spring бин.
* `io.jmix.ui.screen.UiControllerUtils` предоставляет доступ к UI-компонентам и компонентам данных экрана.

== Примеры

В примерах ниже демонстрируется создание и использование примесей.

=== Примесь Banner

Это очень простая примесь, которая отображает надпись вверху экрана.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/mixins/HasBanner.java[tags=has-banner]
----

<1> Получение `ApplicationContext`.
<2> Получение фабрики UI-компонентов.
<3> Создание компонента `Label` и установка его параметров.
<4> Добавление компонента `Label` в корневой UI-компонент экрана.

Примесь может быть использована в экране следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/mixins/DemoOrderEdit.java[tags=has-banner]
----

=== Примесь DeclarativeLoaderParameters

Следующая примесь помогает устанавливать отношения master-detail между контейнерами данных. Обычно для этого необходимо подписаться на `ItemChangeEvent` master-контейнера и задать параметр для detail-загрузчика, как описано в разделе xref:ui:data/data-examples.adoc#dependencies-between-data-components[Зависимости между компонентами данных]. Примесь сможет сделать это автоматически, если параметр будет иметь специальное имя, указывающее на master-контейнер.

Создаваемая примесь будет использовать объект-состояние для передачи информации между обработчиками событий экрана. Это сделано в основном в целях демонстрации, так как в данном случае можно было бы разместить всю логику в единственном обработчике `BeforeShowEvent`.

Сначала создадим класс объекта состояния. Он содержит единственное поле для сохранения набора загрузчиков, которые должны сработать в обработчике `BeforeShowEvent`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/mixins/DeclarativeLoaderParametersState.java[tags=state]
----

Теперь создадим интерфейс примеси:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/mixins/DeclarativeLoaderParameters.java[tags=interface]
----

<1> Подписка на xref:ui:screens/screen-events.adoc#init-event[InitEvent].
<2> Получение объекта `ScreenData`, в котором зарегистрированы все контейнеры и загрузчики данных, объявленные в XML-дескрипторе.
<3> Проверка, соответствует ли имя параметра загрузчика паттерну `:container$masterContainerId`.
<4> Извлечение id master-контейнера из имени параметра и регистрация слушателя `ItemChangeEvent` для этого контейнера.
<5> Перезагрузка detail-загрузчика для нового выбранного элемента в master-контейнере.
<6> Добавление master-загрузчика в набор для вызова позже в обработчике `BeforeShowEvent`.
<7> Создание объекта состояния и сохранение его в экране с помощью класса `Extensions`.
<8> Подписка на xref:ui:screens/screen-events.adoc#before-show-event[BeforeShowEvent].
<9> Вызов всех master-загрузчиков в обработчике `InitEvent`.

Определим master и detail контейнеры и загрузчики в XML-дескрипторе экрана. Detail-загрузчик должен иметь параметр с именем вида `:container$masterContainerId`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/screens/mixins/demo-order-browse.xml[tags=container]
----

В контроллере экрана достаточно добавить интерфейс примеси, и она будет вызывать загрузчики нужным образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/mixins/DemoOrderBrowse.java[tags=interface]
----