= Корневые экраны

Корневой экран – это экран Jmix UI, который отображается непосредственно во вкладке веб-браузера. Существует два типа таких экранов: экран логина и главный экран. Помимо обычных компонентов, любой корневой экран может содержать компонент `WorkArea`, который позволяет открывать другие экраны приложения во внутренних вкладках. Если корневой экран не содержит `WorkArea`, то экраны приложения могут быть открыты только в режиме `DIALOG`.

[[login-screen]]
== Экран логина

Экран логина отображается перед входом пользователя в систему. Существующий экран входа в систему можно кастомизировать, изменив его дескриптор и контроллер.

Кроме того, для создания нового экрана логина можно использовать шаблон *Login screen with branding image* в мастере Studio. Идентификатор созданного экрана будет задан в свойстве xref:ui:app-properties.adoc#jmix.ui.login-screen-id[jmix.ui.login-screen-id].

////
If you want to create a new login screen from scratch, use *Blank screen* template. The source code of a minimalistic login screen can look as follows:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/login/my-login-screen.xml[tags=my-login]
----

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/login/MyLoginScreen.java[tags=my-login]
----

In order to use this login screen instead of the default one, set its id to the `jmix.ui.loginScreenId` property in the `application.properties` file:

[source,properties,indent=0]
----
jmix.ui.loginScreenId = myLogin
----
////

[[main-screen]]
== Главный экран

Главный экран – это корневой экран, отображаемый после входа пользователя в систему. По умолчанию фреймворком предоставляется главный экран с боковым меню.

В приложении можно использовать следующие типы главных экранов:

* *Main screen with side menu* позволяет разворачивать и сворачивать боковое меню с помощью кнопки *Collapse*, находящейся в нижнем левом углу меню.
* *Main screen with top menu* создает экран с строкой меню в верхней части окна приложения. Его можно создать с помощью шаблона в мастере Studio. Идентификатор созданного экрана будет задан в свойстве xref:ui:app-properties.adoc#jmix.ui.main-screen-id[jmix.ui.main-screen-id].

Следующие специальные компоненты могут быть использованы в главном экране в дополнение к стандартным UI-компонентам:

* xref:vcl/components/side-menu.adoc[SideMenu] - боковое меню приложения в виде вертикального дерева.
* xref:vcl/components/app-menu.adoc[AppMenu] - главное меню приложения.
* xref:vcl/containers/drawer.adoc[Drawer] - панель, которую можно свернуть на левую сторону. Используется в качестве контейнера бокового меню.
* `AppWorkArea` - рабочая область, обязательный компонент для работы с экранами в режимах `THIS_TAB`, `NEW_TAB`, и `NEW_WINDOW`.
* `NewWindowButton` - кнопка открытия нового главного экрана в отдельной вкладке браузера.
* `TimeZoneIndicator` - надпись, которая отображает часовой пояс текущего пользователя.
* `UserIndicator` - поле, отображающее имя текущего пользователя.
+
Метод `setFormatter()` используется для отображения имени пользователя в виде, отличном от стандартного имени экземпляра сущности `User`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/main/MainScreenTopMenu.java[tags=user-indicator;formatter]
----
* `LogoutButton` - кнопка выхода из приложения.

На главный экран могут влиять следующие свойства приложения :

* xref:ui:app-properties.adoc#jmix.ui.app-window-mode[jmix.ui.app-window-mode] - задает начальный режим главного окна: с вкладками (`TABBED`) или одноэкранный (`SINGLE`).
//Впоследствии пользователь может задать желаемый режим в экране *Settings*, доступный через `UserActionsButton`.
* xref:ui:app-properties.adoc#jmix.ui.max-tab-count[jmix.ui.max-tab-count] - когда главное окно находится в режиме c вкладками, это свойство задает максимальное количество вкладок, которое может открыть пользователь.
* xref:ui:app-properties.adoc#jmix.ui.default-screen-id[jmix.ui.default-screen-id] - задает экран по умолчанию, который должен быть открыт в главном экране автоматически.
* xref:ui:app-properties.adoc#jmix.ui.default-screen-can-be-closed[jmix.ui.default-screen-can-be-closed] - указывает, может ли пользователь закрыть экран по умолчанию.
