= ScreenFragment 事件
:page-aliases: backoffice-ui:screens/screen-fragment-events.adoc

本节介绍界面 fragment 控制器能处理的生命周期事件。

[[init-event]]
== InitEvent
该事件在 fragment 控制器和其所有以声明方式定义的组件创建之后，并且依赖注入完成才触发。此时，内部的 fragment 还没有初始化。有些可视化组件没有完全初始化，比如按钮还没有连接到操作。如果该 fragment 是通过 XML 的方式绑定到宿主界面的话，该事件会在宿主控制器的 `InitEvent` 事件之后触发。否则会在该 fragment 被添加到宿主组件树的时候触发。

[[after-init-event]]
== AfterInitEvent
该事件会在 fragment 控制器和其所有以声明方式定义的组件创建之后，并且依赖注入完成，所有组件内部的初始化过程也已经结束之后触发。此时，内部的界面 fragment（如果有的话）已经触发了它们自己的 `InitEvent` 和 `AfterInitEvent` 事件。在该事件的监听器中，可以创建可视化和数据组件，并能执行依赖内部 fragment 初始化完成的额外初始化过程。

[[attach-event]]
== AttachEvent
该事件会在 fragment 被添加到宿主的组件树时触发，fragment 已经完全初始化了，`InitEvent` 和 `AfterInitEvent` 事件已经触发。在该事件的监听器中，可以通过 `getHostScreen()` 和 `getHostController()` 访问宿主界面的界面和方法。

监听 `AttachEvent` 事件的示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java1;logger;events]
----

[[detach-event]]
== DetachEvent
该事件会在 fragment 以编程的方式从宿主的组件树中移除时触发。在该事件监听器中也能访问宿主界面。

[[listening-to-host-screen-events]]
== 监听宿主界面事件
在 fragment 控制器中，可以订阅父界面的事件，需要在注解中为 `target` 属性指定 `PARENT_CONTROLLER` 值，示例：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=target]
----

这个方法可以处理任何事件，包括实体编辑界面发送的 xref:ui:screens/screen-events.adoc#init-entity-event[InitEntityEvent] 事件。
