= События Screen

В данном разделе описаны события жизненного цикла экрана, которые могут обрабатываться в контроллерах.

[[init-event]]
== InitEvent

`InitEvent` посылается, когда контроллер экрана и все его декларативно заданные компоненты созданы, а инжекция зависимостей завершена. Вложенные фрагменты на этом этапе еще не инициализированы. Некоторые визуальные компоненты инициализированы не полностью: например, кнопки ещё не связаны с действиями.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderBrowse1.java[tags=init-event]
----

[[after-init-event]]
== AfterInitEvent

`AfterInitEvent` посылается, когда контроллер экрана и все его декларативно заданные компоненты созданы, инжекция зависимостей завершена, и все компоненты завершили свою внутреннюю процедуру инициализации. Вложенные фрагменты (при наличии) опубликовали свои события `InitEvent` и `AfterInitEvent`. В слушателе этого события можно создавать визуальные компоненты и компоненты данных, а также выполнить дополнительную инициализацию, если она зависит от инициализации вложенных фрагментов.

[[init-entity-event]]
== InitEntityEvent

`InitEntityEvent` посылается в экранах, унаследованных от `StandardEditor` и `MasterDetailScreen`, перед тем, как новый экземпляр сущности будет установлен для контейнера редактируемой сущности.

Используйте слушатель этого события, чтобы инициализировать значения по умолчанию для новых экземпляров сущностей, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit1.java[tags=init-entity]
----

[[before-show-event]]
== BeforeShowEvent

`BeforeShowEvent` посылается непосредственно перед тем, как экран будет отображен, например, если он еще не добавлен к интерфейсу приложения. Ограничения безопасности уже применены к компонентам UI. В слушателе этого события можно загружать данные, проверять разрешения безопасности и изменять компоненты интерфейса. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderBrowse1.java[tags=before-show1;before-show2]
----

[[after-show-event]]
== AfterShowEvent

`AfterShowEvent` посылается сразу после отображения экрана, например, когда экран уже добавлен к интерфейсу приложения. В слушателе этого события можно отображать уведомления, диалоговые окна или другие экраны. Например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderBrowse1.java[tags=after-show1;after-show2]
----

[[before-commit-changes-event]]
== BeforeCommitChangesEvent

`BeforeCommitChangesEvent` посылается в экранах, унаследованных от `StandardEditor` и `MasterDetailScreen`, перед сохранением измененных данных методом `commitChanges()`. В слушателе этого события можно проверить некоторые условия и прервать или продолжить операцию сохранения с помощью методов `preventCommit()` и `resume()` объекта события.

Рассмотрим некоторые варианты использования.

* Прервать операцию сохранения с выводом уведомления:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit1.java[tags=before-commit1;before-commit2]
----
+
* Прервать операцию сохранения, показать диалог и продолжить после подтверждения пользователем:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderBrowse2.java[tags=before-commit]
----
+
* Прервать операцию сохранения, показать диалог и повторить `commitChanges()` после подтверждения пользователем:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit3.java[tags=before-commit]
----

[[after-commit-changes-event]]
== AfterCommitChangesEvent

`AfterCommitChangesEvent` посылается в экранах, унаследованных от `StandardEditor` и `MasterDetailScreen`, после сохранения измененных данных методом `commitChanges()`. Пример использования:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit1.java[tags=before-commit1;after-commit]
----

[[before-close-event]]
== BeforeCloseEvent

`BeforeCloseEvent` посылается непосредственно перед закрытием экрана с помощью метода `close(CloseAction)`. На этом этапе экран еще отображается и полностью функционален. В слушателе этого события можно проверить некоторые условия и предотвратить закрытие экрана, используя метод события `preventWindowClose()`, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit1.java[tags=before-close1;before-close2]
----

Одноименный метод также определен в интерфейсе `Window`. Он вызывается перед тем, как экран будет закрыт неким внешним (относительно контроллера) действием, таким как нажатие кнопки во вкладке окна или клавиши *Escape* на клавиатуре. Способ, которым экран был закрыт, можно получить с помощью метода `getCloseOrigin()`, который возвращает значение в виде объекта, реализующего интерфейс `CloseOrigin`. Реализация этого интерфейса по умолчанию `CloseOriginType` включает в себя три значения:

* `BREADCRUMBS` - экран закрыт по клику на цепочке ссылок (breadcrumbs).
* `CLOSE_BUTTON` - экран закрыт по нажатию на кнопку закрытия в заголовке окна, на кнопку закрытия вкладки или через действия в контекстном меню: Close, Close All, Close Others.
* `SHORTCUT` - экран закрыт нажатием горячих клавиш, определенных в свойстве приложения xref:ui:app-properties.adoc#jmix.ui.screen.close-shortcut[jmix.ui.screen.close-shortcut].

Вы можете подписаться на событие `Window.BeforeCloseEvent`, указав `Target.FRAME` в аннотации `@Subscribe`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit3.java[tags=before-close]
----

[[after-close-event]]
== AfterCloseEvent

`AfterCloseEvent` посылается после того, как экран будет закрыт методом `close(CloseAction)`, и после события `Screen.AfterDetachEvent`. Слушатель этого события можно использовать для вывода уведомлений или диалоговых окон после закрытия экрана, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderEdit3.java[tags=after-close1;after-close2]
----

[[after-detach-event]]
== AfterDetachEvent

`AfterDetachEvent` посылается после того, как экран удаляется из интерфейса приложения после закрытия экрана пользователем или выхода пользователя из системы. Слушатель этого события можно использовать для освобождения ресурсов, захваченных экраном. Обратите внимание, что при истечении HTTP-сессии это событие не публикуется.

[[url-params-changed-event]]
== UrlParamsChangedEvent

`UrlParamsChangedEvent` посылается, когда изменяются параметры URL браузера, соответствующие данному экрану. Событие вызывается перед отображением экрана, что позволяет произвести некоторую подготовительную работу. В слушателе этого события можно загружать данные или изменять состояние элементов управления в экране в соответствии с новыми параметрами:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/OrderBrowse2.java[tags=url-params]
----
