= События ScreenFragment

В данном разделе описаны события жизненного цикла фрагмента, которые могут обрабатываться в контроллерах фрагментов.

[[init-event]]
== InitEvent
Это событие посылается, когда контроллер фрагмента и все его декларативно заданные компоненты созданы, а инжекция зависимостей завершена. Вложенные фрагменты на этом этапе еще не инициализированы. Некоторые визуальные компоненты инициализированы не полностью: например, кнопки еще не связаны с действиями. Если фрагмент подключается к включающему экрану декларативно в XML, данное событие посылается после `InitEvent` контроллера включающего экрана. В противном случае событие посылается, когда фрагмент подключается к дереву компонентов включающего экрана.

[[after-init-event]]
== AfterInitEvent
Это событие посылается, когда контроллер фрагмента и все его декларативно заданные компоненты созданы, инжекция зависимостей завершена, и все компоненты завершили свою внутреннюю процедуру инициализации. Вложенные фрагменты (при наличии) опубликовали свои события `InitEvent` и `AfterInitEvent`. В слушателе этого события можно создавать визуальные компоненты и компоненты данных, а также выполнить дополнительную инициализацию, если она зависит от инициализации вложенных фрагментов.

[[attach-event]]
== AttachEvent
Это событие  посылается после того, как фрагмент добавлен к дереву компонентов включающего экрана. В этот момент фрагмент полностью инициализирован, события `InitEvent` и `AfterInitEvent` отосланы. В слушателе данного события можно обращаться к включающему экрану, используя методы `getHostScreen()` и `getHostController()`.

Пример подписки на `AttachEvent`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-java1;logger;events]
----

[[detach-event]]
== DetachEvent
Это событие посылается после того, как фрагмент программно удален из дерева компонентов включающего экрана. В слушателе данного события нельзя обращаться к включающему экрану.

[[listening-to-host-screen-events]]
== Подписка на события включающего экрана
В контроллере фрагмента можно также подписаться на события включающего экрана путем указания значения `PARENT_CONTROLLER` в атрибуте `target` аннотации, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=target]
----

Таким способом можно обработать любое событие, в том числе xref:ui:screens/screen-events.adoc#init-entity-event[InitEntityEvent], посылаемое экранами редактирования.

[[listening-to-fragment-events-in-host]]
== Listening to Fragment Events in Host Screen

In a host screen controller, you can subscribe to the events sent in a fragment controller. Below is an example of handling a custom event sent by the fragment when the value of its component changes.

In the fragment controller, create the event class and a method for registering listeners of this event:

[source,java,indent=0]
.AddressFragment.java
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/AddressFragment.java[tags=fragment-event]
----
<1> Create a custom event class by extending `EventObject`.
<2> Create a method for registering listeners of the custom event.
<3> Send the custom event using `fireEvent()` method.

Now you can declaratively subscribe to the custom fragment event in the host controller as follows:

[source,java,indent=0]
.HostScreen.java
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/fragments/HostScreen3.java[tags=fragment-event]
----
<1> Use the fragment id and `Target.CONTROLLER` to subscribe to the fragment event.
