= 界面中的验证
:page-aliases: backoffice-ui:screens/validation.adoc

`ScreenValidation` bean 可以用来运行界面中的验证逻辑，有如下方法：

* `validateUiComponents()` 在 `StandardEditor`，`InputDialog` 和 `MasterDetailScreen` 提交改动时默认使用。该方法接收一组界面组件或者一个组件容器作为参数，返回这些组件中的验证错误 - `ValidationErrors` 对象。`validateUiComponents()` 方法还可以用在其他任意的界面中。示例：
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/DemoScreen.java[tags=demo-screen;screen-validation;validate-ui;end]
----

* `showValidationErrors()` - 显示所有的错误和有问题的组件。该方法接收界面和 `ValidationErrors` 对象作为参数。默认在 `StandardEditor`，`InputDialog` 和 `MasterDetailScreen` 中使用。

* `validateCrossFieldRules()` - 接收界面和实体作为参数，返回 `ValidationErrors` 对象。默认情况下，在 `StandardEditor`，`MasterDetailScreen` 以及 `DataGrid` 的编辑界面使用。该方法可进行跨字段验证。
+
--
如果编辑界面的约束中包含 `UiCrossFieldChecks` 并且所有的属性级别验证通过，则会在提交时，进行类级别约束的验证。可以使用控制器的 `setCrossFieldValidate()` 方法禁用此类验证。另外，`validateCrossFieldRules()` 方法也可以用在任意界面中。

举个例子，对于 `Event` 实体，我们可以定义类级别注解 `@EventDate` 来检查 *Start date* 必须小于 *End date*。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/entity/Event.java[tags=validate-cross]
----

注解定义如下：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/EventDate.java[tags=event-date-annotation]
----

`EventDateValidator` 类：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/EventDateValidator.java[tags=event-date-validator]
----

然后可以在任意界面中使用 `validateCrossFieldRules()` 方法。

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/DemoScreen.java[tags=demo-screen;screen-validation;validate-cross;validate-date;end]
----
--

* `showUnsavedChangesDialog()` 和 `showSaveConfirmationDialog()` 方法为没保存的数据显示对话框，对话框中带有 *Yes* 和 *No* 按钮或 *Save*，*Do not save* 和 *Cancel* 按钮。这些方法用于 `StandardEditor` 的 xref:ui:screens/methods.adoc#prevent-unsaved-changes[preventUnsavedChanges()] 方法。可以用 xref:ui:app-properties.adoc#jmix.ui.screen.use-save-confirmation[jmix.ui.screen.use-save-confirmation] 应用程序属性选择对话框类型。
