= Screen Validation
:page-aliases: backoffice-ui:screens/validation.adoc

The `ScreenValidation` bean is used to run validation in screens. It has the following methods:

* `validateUiComponents()` is used by default when committing changes in the `StandardEditor`, `InputDialog`, and `MasterDetailScreen`. The method accepts a collection of components or a component container and returns validation errors in these components - `ValidationErrors` object. The `validateUiComponents()` method also can be used in an arbitrary screen. For example:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/DemoScreen.java[tags=demo-screen;screen-validation;validate-ui;end]
----

* `showValidationErrors()` - displays a notification with all errors and problematic components. The method accepts the screen and `ValidationErrors` object. It is also used by default in the `StandardEditor`, `InputDialog`, and `MasterDetailScreen`.

* `validateCrossFieldRules()` - accepts a screen and an entity and returns the `ValidationErrors` object.  By default, it is used in the `StandardEditor`, `MasterDetailScreen`, and in the editor of the `DataGrid`. This method performs cross-field validation rules.
+
--
Editor screens validate class-level constraints on the commit if the constraints include the `UiCrossFieldChecks` group and all attribute-level constraint checks are successful. You can disable this type of validation using the `setCrossFieldValidate()` method of the controller. The `validateCrossFieldRules()` method also can be used in an arbitrary screen.

As an example, let’s look at the `Event` entity for which we can define a class-level annotation `@EventDate` to check that the start date must be lower than the end date:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/entity/Event.java[tags=validate-cross]
----

The annotation definition looks like this:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/EventDate.java[tags=event-date-annotation]
----

Here is the `EventDateValidator` class:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/EventDateValidator.java[tags=event-date-validator]
----

Then you can use the `validateCrossFieldRules()` method in an arbitrary screen.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/DemoScreen.java[tags=demo-screen;screen-validation;validate-cross;validate-date;end]
----
--

* `showUnsavedChangesDialog()` and `showSaveConfirmationDialog()`  methods show dialogs for unsaved changes with either *Yes* and *No* buttons or *Save*, *Do not save*, and *Cancel* buttons. These methods are used in the xref:ui:screens/methods.adoc#prevent-unsaved-changes[preventUnsavedChanges()] method of `StandardEditor`. You can select what type of the dialog is used in the xref:ui:app-properties.adoc#jmix.ui.screen.use-save-confirmation[jmix.ui.screen.use-save-confirmation] application property.
