= Валидация в экранах

Бин `ScreenValidation` используется для запуска валидации в экранах. Он имеет следующие методы:

* `validateUiComponents()` - используется при коммите изменений в экранах `StandardEditor`, `InputDialog`, и `MasterDetailScreen`. Принимает коллекцию из компонентов или контейнер компонентов и возвращает ошибки валидации в этих компонентах – объект `ValidationErrors`. Метод `validateUiComponents()` также может быть использован в произвольном экране. Например:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/DemoScreen.java[tags=demo-screen;screen-validation;validate-ui;end]
----
+
* `showValidationErrors()` - показывает уведомление со всеми ошибками и проблемными компонентами. Метод принимает экран и объект `ValidationErrors`. Также используется по умолчанию в экранах `StandardEditor`, `InputDialog`, и `MasterDetailScreen`.
* `validateCrossFieldRules()` - accepts a screen and an entity and returns the `ValidationErrors` object.  By default, it is used in the `StandardEditor`, `MasterDetailScreen`, and in the editor of the `DataGrid`. Выполняет правила перекрестной проверки, установленные на поля сущности.
+
--
Editor screens validate class-level constraints on the commit if the constraints include the `UiCrossFieldChecks` group and all attribute-level constraint checks are successful. You can disable this type of validation using the `setCrossFieldValidate()` method of the controller. The `validateCrossFieldRules()` method also can be used in an arbitrary screen.

В качестве примера рассмотрим сущность `Event`, для которой можно определить аннотацию уровня класса `@EventDate`, для проверки того, что дата *Start date* должна быть раньше даты *End date*.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/entity/Event.java[tags=validate-cross]
----

Определение аннотации выглядит следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/EventDate.java[tags=event-date-annotation]
----

Вот класс `EventDateValidator`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/EventDateValidator.java[tags=event-date-validator]
----

Теперь можно использовать метод `validateCrossFieldRules()` в произвольном экране.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/screens/validate/DemoScreen.java[tags=demo-screen;screen-validation;validate-cross;validate-date;end]
----
--

* Методы `showUnsavedChangesDialog()` и `showSaveConfirmationDialog()`  показывают диалоги с предупреждением о несохраненных изменениях либо с кнопками *Yes* и *No*, либо *Save*, *Do not save*, и *Cancel*. Используются в методе `StandardEditor` xref:ui:screens/methods.adoc#prevent-unsaved-changes[preventUnsavedChanges()]. Выбрать тип диалога можно с помощью свойства приложения xref:ui:app-properties.adoc#jmix.ui.screen.use-save-confirmation[jmix.ui.screen.use-save-confirmation].
