= UI Recovery Properties

[[jmix.uirecovery.drafts.enabled]]
== jmix.uirecovery.drafts.enabled

Defines whether the xref:ui-recovery:drafts-facet.adoc[drafts facet] saves and restores drafts. If set to `false`, the facet does nothing in all views.

Default value: `true`

[[jmix.uirecovery.drafts.default-min-save-interval]]
== jmix.uirecovery.drafts.default-min-save-interval

Defines the minimum time between two saves of the draft of a view. The xref:ui-recovery:drafts-facet.adoc#minSaveInterval[minSaveInterval] attribute of the facet overrides it.

Default value: `5s`

[[jmix.uirecovery.drafts.default-restore-mode]]
== jmix.uirecovery.drafts.default-restore-mode

Defines how a draft is restored when a view is opened: `ASK` or `AUTO`. See xref:ui-recovery:drafts-facet.adoc#restore-modes[Restore Modes]. The xref:ui-recovery:drafts-facet.adoc#restoreMode[restoreMode] attribute of the facet overrides it.

Default value: `ASK`

[[jmix.uirecovery.drafts.retention]]
== jmix.uirecovery.drafts.retention

Defines how long a draft is kept. A draft older than this period is expired. The add-on doesn't offer it to the user and deletes it when it finds the draft. To delete expired drafts of the views that users never open again, set up a regular job as described in xref:ui-recovery:deleting-expired-drafts.adoc[].

Default value: `30d`

[[jmix.uirecovery.drafts.show-on-login]]
== jmix.uirecovery.drafts.show-on-login

Defines whether the xref:ui-recovery:drafts-list.adoc[Unsaved drafts] view is opened after login when the user has drafts. See xref:ui-recovery:drafts-list.adoc#show-on-login[Showing Drafts After Login].

Default value: `false`
