= Удаление устаревших черновиков

Черновик устаревает, когда он становится старше срока, заданного в свойстве xref:ui-recovery:app-properties.adoc#jmix.uirecovery.drafts.retention[jmix.uirecovery.drafts.retention]. Дополнение удаляет устаревший черновик, когда находит его, то есть когда пользователь открывает экран черновика или экран xref:ui-recovery:drafts-list.adoc[Unsaved drafts]. Черновики экранов, которые пользователи больше не открывают, остаются в базе данных. Чтобы удалять их, настройте регулярное задание.

Задание вызывает метод `deleteExpired()` бина `ViewDraftService`. Метод удаляет устаревшие черновики всех пользователей и не требует аутентифицированного пользователя, поэтому его можно вызывать из любой задачи по расписанию.

Например, следующий бин использует аннотацию Spring `@Scheduled`:

[source,java,indent=0]
----
include::example$ui-recovery-ex1/src/main/java/com/company/sample/job/DraftsCleanupJob.java[tags=cleanup-job]
----
<1> Запускает метод каждый день в 3 часа ночи.
<2> Удаляет устаревшие черновики и возвращает их количество.

Выполнение по расписанию с помощью `@Scheduled` должно быть включено в конфигурационном классе:

[source,java,indent=0]
----
include::example$ui-recovery-ex1/src/main/java/com/company/sample/job/SchedulingConfiguration.java[tags=enable-scheduling]
----

Также метод можно вызывать из задания дополнения xref:quartz:index.adoc[Quartz].
