= Обзор архитектуры

В данном разделе представлены несколько диаграмм, которые показывают  общую картину ландшафта Jmix.

[[scope]]
== Область Jmix

В простейшем случае информационная система, созданная с использованием Jmix, состоит из веб-приложения на Java и реляционной базы данных.

.Простое Jmix-приложение
image::architecture-scope-1.svg[align="center"]

Веб-приложение основано на Spring Boot и может быть написано на Java или Kotlin. Реляционная база данных используется для хранения данных подсистем Jmix (например, конфигурации безопасности) и в качестве основного хранилища данных приложений.

Приложение Jmix может подключаться к любому количеству дополнительных хранилищ данных и использовать отдельное файловое хранилище в файловой системе или в облаке. Кроме того, Jmix предлагает интеграцию с сервером xref:oidc:index.adoc[OIDC] или xref:ldap:index.adoc[LDAP] для внешней аутентификации и единого входа, и с OpenSearch или Elasticsearch для xref:search:index.adoc[полнотекстового поиска] по данным приложения.

.Jmix-приложение с дополнительными сервисами
image::architecture-scope-2.svg[align="center"]

Приложение Jmix предоставляет пользователям веб-интерфейс. Он создается на Java/Kotlin и XML с использованием подсистемы xref:flow-ui:index.adoc[пользовательского интерфейса Jmix].

Вы также можете создать отдельное фронтенд-приложение и подключить его к бэкенду Jmix через xref:rest:index.adoc[Jmix REST API] или путем создания собственного API. Обратите внимание, что фронтенд-приложения выходят за рамки Jmix, и вы можете создавать их с помощью любой технологии по вашему выбору.

.Jmix-приложение с дополнительным фронтендом
image::architecture-scope-3.svg[align="center"]

Jmix-приложение можно горизонтально масштабировать, используя xref:features:cluster-communication.adoc[кластер] серверов и балансировщик нагрузки.

.Масштабирование Jmix-приложения
image::architecture-scope-4.svg[align="center"]


[[components]]
== Компоненты Jmix

Давайте подробнее рассмотрим приложение Jmix и его компоненты.

.Компоненты Jmix-приложения
image::architecture-components-1.svg[align="center"]

Приложение Jmix всегда содержит зависимости от Spring Boot и ряда подсистем Jmix. Существует две категории подсистем Jmix:

* _Основные подсистемы (Core subsystems)_ обеспечивают функциональность системного уровня и включены в большинство проектов.

* _Дополнения (Add-ons)_ – это дополнительные подсистемы, которые могут быть включены в проект по требованию. Они публикуются на https://www.jmix.ru/marketplace/[маркетплейсе^] Jmix.

Технически, как основные подсистемы, так и дополнения организованы одинаково. Подсистема содержит один или несколько функциональных модулей и соответствующие стартеры Spring Boot, упакованные в JAR-файлы. Подсистема может зависеть от других подсистем: например, многие дополнения содержат экраны, которые требуют зависимости от основной подсистемы пользовательского интерфейса.
