= 概念

Jmix 是一个开发平台，包含开源框架、扩展组件以及 Studio IDE。

如果想对 Jmix 有个大概了解，可以查看 <<architecture,below>> 的架构图，或观看 7 分钟的 https://www.bilibili.com/video/BV1TV4y1U7Dc[Bilibili 视频^]。

如果想了解 Jmix 背后的设计理念和功能点，以及找寻诸如“Jmix 为什么是这样的？”之类的问题，请阅读 xref:principles.adoc[] 和 xref:features.adoc[] 部分。对于您做出明智的决定或高效使用 Jmix 很有帮助。

[[architecture]]
== 架构概览

这里我们采用 C4 模型表示法，展示 Jmix 架构的鸟瞰图。

[[architecture-containers]]
=== 容器

首先，我们将一个用 Jmix 构建的典型信息系统划分成不同的容器。这里的容器是指可以单独运行/部署的单元，负责执行代码或者存储数据。

image:ROOT:architecture-containers.drawio.svg[align="center"]

可以看到，系统的主要部分包括运行在 JVM 上的 Web 应用程序以及一个关系型数据库。Web 应用程序基于 Spring Boot，支持用 Java 或 Kotlin 编写。关系型数据库用于保存 Jmix 子系统的数据（例如，安全配置）以及作为应用程序的数据的主要存储。

Jmix 应用程序可以与多个附加数据存储连接，并支持使用文件系统或云环境作为独立的文件存储。此外，Jmix 还支持集成 Elasticsearch 实现对应用程序数据的全文检索功能，支持通过 OIDC（或 LDAP） 服务进行外部认证和单点登录（SSO）。

Jmix 应用程序为用户提供 web 界面，界面使用 Jmix UI 子系统通过 Java/Kotlin 和 XML 创建。

当然，你也可以创建独立的前端应用，然后通过 Jmix REST API 或自定义接口与 Jmix 后端连接。这里的前端应用并不在 Jmix 的范围内，可以选择任何技术进行构建。

[[architecture-components]]
=== 组件

我们进入 Jmix 容器更进一步了解其内部组件。

image:ROOT:architecture-jmix-application.drawio.svg[align="center"]

Jmix 应用程序包含对 Spring Boot 和其他 Jmix 子系统的依赖关系。Jmix 有两类子系统：

* _核心子系统_ 提供系统级别的功能，包含在绝大多数项目中。

* _扩展组件_ 是可选的子系统，根据需要添加至项目中。扩展组件在 Jmix https://www.jmix.cn/marketplace/[市场^] 发布。

技术上来说，核心子系统和扩展组件都是以相同的方式进行组织。子系统包含一个或多个功能模块以及对应的 Spring Boot starter，均以 JAR 文件格式打包。子系统可以依赖其他子系统，例如，很多包含视图的扩展组件依赖核心 UI 子系统。
