= Inside Jmix

In this section, we will discuss the inner workings of the framework that enable the implementation of the principles described in the xref:principles.adoc[previous section].

// todo Recommendations who should read this

== Data Model and Metadata

The xref:principles.adoc#_lean_data_model[lean data model] approach allows you to avoid duplicating the data model across different layers and writing boilerplate code. This section explains how Jmix offers efficient methods for working with a single model of heterogeneous data.

=== Building Metadata

Let's take a look at the various options for application data sources, ranging from simple to more complex.

In the simplest case, the application connects to a single relational database, and its data model consists of a number of interconnected JPA entities:

*picture: DB1, JPA Entities*

Sometimes data are located in several databases. Then you have multiple persistence units with JPA entities:

*picture: DB1, DB2, JPA Entities*

If you need to connect to an external data source, then you also need some POJOs or DTOs to represent its data:

*picture: DB1, DB2, External Service, JPA Entities, DTOs*

So in the source code, you can have separate collections of Java classes, differently structured and annotated, and handled by different mechanisms of loading and saving data.

But Jmix also combines all these fragments into a common data model and treats all classes as just "entities" with equal characteristics:

*picture: Data Model, entities*

The data model can even contain references between entities from different storages (as shown by dotted lines) and Jmix helps to maintain these references on the application level.

The common data model with the unified information about all entities, attributes and relations is provided by the xref:data-model:metadata.adoc[Metadata] mechanism. It scans Java classes and represents entities by `MetaClass` objects and entity attributes by `MetaProperty` objects.

The picture below shows an example of how some JPA entities are reflected in metadata:

*picture: source code -> metadata*

Note that the `employeeCount` attribute here is transient and is not handled by JPA. But in metadata, it has the same set of characteristics as other attributes.

You may notice that the Java classes have some unusual annotations: `@JmixEntity`, `@InstanceName`, `@Secret`. They are specific to Jmix: `@JmixEntity` is required, it indicates that the class should be included in the metadata, the others are optional and just provide additional information about attributes.

You can add the `@JmixEntity` to any POJO, thus including it in the metadata as an entity. This is how the common data model is built - by annotating all data model classes regardless of their storage technology.

Actually, the metadata API is rarely used in the application code. When you write business logic and code for loading and saving entities, you use Java classes and their getter/setter methods and enjoy static typing and coding assistance in the IDE.

But the unified API for the whole data model is indispensable for generic mechanisms of the framework, first of all for data-aware UI components. It provides an abstraction over various methods of specifying data model characteristics, so UI components are completely agnostic of Java classes and annotations. They can work equally well directly with JPA entities or with POJOs if you need to transform the stored data for the UI.

Other features working with data model can also benefit from the metadata API. Below is the code that could be used by an auditing solution to get all non-collection attributes of an entity:

[source, java]
----
Class<?> javaClass = // ...
MetaClass metaClass = metadata.getClass(javaClass);
List<MetaProperty> singleValueProperties = metaClass.getProperties().stream()
        .filter(metaProperty ->
                !metaProperty.getRange().getCardinality().isMany())
        .toList();
----

An entity in Jmix can even be defined dynamically at runtime by a set of key-value pairs. Such entities do not have a specific Java class, but nevertheless can be displayed and edited in user interface. UI components do not need a Java class, they need only an object that can read/write properties by name, and a corresponding `MetaClass` with the collection of `MetaProperty` to describe these properties.

=== Enhancing Entities

Now we'll briefly discuss another aspect of the unified data model maintained by Jmix: _enhancing_ of entity classes, which is also known as bytecode modification. Jmix enhances entity classes at build time to provide required characteristics for all types of entities. These characteristics include the presence of an identifier, suitable `equals()` and `hashCode()` methods, ability to read/write entity attributes by name and listen to changes in attribute values.

For example, a DTO entity can have no identifier attribute if it is not stored in any persistent storage and exists purely in memory. But for uniformity with persistent entities, Jmix modifies the entity bytecode and adds an identifier field with automatically generated value. The same with `equals()` and `hashCode()` - they are added to the entity classes at build time with the implementation based on comparing identifiers.

The following diagram shows that after enhancement the `User` entity class implements the `Entity` interface, contains generated `equals()` and `hashCode()` methods and a reference to the `EntityEntry` object which provides common methods required by the framework.

*picture: enhanced entity class diagram*

The most interesting feature that all entities acquire from enhancing is their observability. It is possible to register listeners with an entity instance and get notified about changes in its attributes. It simplifies working with data on UI layer: any changes in entities made by the application code, like `user.setFirstName("Joe")` are immediately shown by the linked UI components, and the changed entities are automatically saved in the database. The application developer doesn't need to write any special code for this, it happens because the framework components listen to changes in entities.

== Data Access

// todo intro

=== DataManager

Jmix provides its own abstraction for loading and saving entities: xref:data-access:data-manager.adoc[DataManager]. It has a simple fluent API:

[source,java]
----
// Load all customers
List<Customer> customers = dataManager.load(Customer.class)
        .all()
        .list();

// Load customers by query
List<Customer> customers = dataManager.load(Customer.class)
        .query("e.email like ?1", "%@company.com")
        .maxResults(1000)
        .list();

// Load a customer by id
Customer customer = dataManager.load(Customer.class)
        .id(customerId)
        .one();

// Save a customer instance
dataManager.save(customer);
----

The main reason for introducing DataManager was not its API, but the need to establish a central point through which all data could flow in and out of data stores. It serves as a hub that provides additional data processing to enable Jmix functionality.

In a typical scenario, DataManager is invoked directly from UI views and REST controllers (if you build a REST API in your application). Both can delegate to a service layer, which in turn works with entities through the DataManager:

*picture: data-manager-1*

Jmix also supports the popular Spring Data API, which allows all data access methods for a particular entity to be concentrated in a repository. In this case, the repository interface should be extended from `JmixDataRepository`, and its implementation will delegate to the DataManager as well:

*picture: data-manager-2*

Jmix doesn't prevent you from bypassing DataManager and accessing data stores through an alternative API like JPA EntityManager or JDBC:

*picture: data-manager-3*

However, in this case Jmix will not be able to intercept the data flow and provide its advanced features.

Now, let's discuss the capabilities that Jmix offers through the Data Manager.

. One of the key features of Jmix is its built-in data access control mechanism. By default, DataManager applies xref:security:row-level-roles.adoc#policies[row-level constraints] and xref:security:resource-roles.adoc#entity-policy[entity operations policy]. When loading entities in pages, it makes sure that each page (except the last one) has a requested number of rows, even if some entities have been filtered out by a row-level constraint.
+
As a result, when writing business logic, you can be sure your code operates only on data permitted for the current user.

. DataManager maintains xref:data-model:entities.adoc#cross-data-store-ref[cross-datastore references] that allow you to link entities located in different databases without writing any code.

. DataManager sends entity lifecycle events, which allows you to perform additional actions when loading and saving entity instances: copy data between persistent and transient attributes, update related entities, send notifications and so on.

. References of entities loaded using DataManager can be loaded xref:data-access:fetching.adoc#lazy-loading[lazily], when they are first accessed. This allows for easy navigation through the entity graph, regardless of what initial graph was loaded with the root entity:
+
[source,java]
----
Order order = dataManager.load(Order.class).id(orderId).one();
String cityName = order.getCustomer().getAddress().getCity().getName();
----

. DataManager supports a pluggable mechanism for integrating add-ons into the process of loading and saving data. It is used, for example, by the Dynamic Attributes add-on to mix in dynamic attributes to entity instances and by the Search add-on to automatically send changed instances to indexing.

The DataManager does not perform all the work on its own. Instead, it delegates the actual loading and saving tasks to the DataStore implementations. The DataStore interface is an abstraction for a concrete storage system, such as a database or other service that can store entities.

Jmix contains a single built-in implementation of the DataStore interface: `JpaDataStore`. It can work with entities located in a relational database, using the EntityManager provided by JPA (Jakarta Persistence API).

An application or an add-on can provide custom DataStore implementations to work with entities from non-relational databases or from various web services.

So the DataManager itself serves mostly as a gateway, providing a convenient API and dispatching requests between DataStore implementations:

*picture: data-manager-4*

// The complete set of Jmix features listed above is implemented by `JpaDataStore` for JPA entities, that is for data located in relational databases. A custom data store can provide similar features

=== JPA Specifics

Let's discuss the DataManager features provided by `JpaDataStore` and what Jmix adds on top of the standard JPA capabilities.

==== Loading Object Graphs

Jmix offers advanced ways of retrieving object graphs that are not available in the mainstream implementation of JPA based on Hibernate. Below you can see an overview and motivation behind these features. For more details, see the xref:data-access:fetching.adoc[] section.

First of all, Jmix provides _lazy loading_ of references for detached objects, that is outside the initial transaction. You can traverse the whole object graph by accessing reference attributes at any time in your business logic or UI component bindings, and Jmix will load the related entities from the database on demand.

The second feature is about _eager loading_. Jmix offers the mechanism of _Fetch Plans_, similar to the JPA Entity Graphs. A fetch plan allows you to control the set of related entities loaded with the root one, and, optionally, the set of local attributes for each entity of the object graph. The ability to restrict the set of loaded local attributes can significantly reduce the database workload, especially in enterprise applications where entities with dozens or even hundreds of attributes are not uncommon.

The Jmix fetch plans provide a completely dynamic way to eagerly load your data model entities _partially_, without the need to introduce any static partial objects. As opposed to Jmix capabilities, the JPA Entity Graphs implemented by Hibernate allow you to define the loaded graph only at the level of related entities. In order to restrict the set of local attributes, you have to use a separate mechanism, for example Spring Data Projections. Such a mechanism requires additional boilerplate code and bloats your data model with DTOs that serve as partial entities.

The ability to load partial entities for improving performance is the main reason why Jmix uses EclipseLink as a JPA implementation. On top of EclipseLink capabilities, Jmix adds convenient definition of fetch plans, automatic selection of fetch modes (JOIN or BATCH), and lazy loading that delegates to DataManager.

==== Soft Deletion

Another distinctive Jmix feature implemented at the JPA level is soft deletion. This is a popular approach in enterprise applications, as it helps to reduce the risk of data loss due to incorrect user actions.

Soft deletion in Jmix is fully transparent and easy to use. You can just add a couple of annotated attributes to your entity, and Jmix will record who and when "deleted" the entity instance in these attributes, instead of physically removing the row from the database table.

When loading entities by any JPQL query, the soft deleted instances will be automatically filtered out from the list of the root entity instances and from all nested collections (to-many references).

Moreover, the soft deletion in Jmix can be dynamically switched off for a particular operation. So depending on your requirements, you can load only non-deleted instances or mix them with soft deleted ones. When the soft deletion is off, the delete operation removes the row from the database.

See more information in the xref:data-model:soft-deletion.adoc[] section.

== User Interface

// - Server-driven UI
// - What's the difference from pure Vaadin?
//      - View abstraction, navigation and dialogs
//      - UI descriptors and controllers
//      - Event listeners and delegates
//      - Data containers
//      - Data context
//      - Editing compositions

To adhere to the full-stack development xref:principles.adoc#_full_stack_development[principle], Jmix uses the https://vaadin.com/[Vaadin^] framework for user interface development. In this section, we describe features that Jmix adds on top of Vaadin to maximize the productivity of creating enterprise applications with large data models and UI.

=== Views

A Jmix application UI consists of a number of views. A view is a separate part of UI that serves a specific function. For example, a view can display a list of customers or manage customer attributes.

Jmix provides a set of base classes for views, typical for enterprise applications.

* `StandardMainView` helps in building a main view which defines the root page with the application main menu.

* `StandardView` is a generic purpose base class which can be used for creating any view opened from the main view.

* `StandardListView` and `StandardDetailView` are subclasses of `StandardView` designed for managing your data model entities.

The views in Jmix have several distinctive features, which are discussed in detail below.

==== Navigation and Dialogs

A view can be mapped to a URL and opened inside the main layout by navigating to this URL. In addition, Jmix allows you to open the same view in a dialog window popped up on the current page without changing the URL. In the former case, the previous view will be closed, while the latter will keep the URL unchanged and the previous view open.

This feature is designed to satisfy two typical requirements in enterprise applications: selecting related entities and editing aggregates.

Let's discuss the first requirement below and the second one in the <<_editing_aggregates,subsequent section>>.

Usually web applications offer dropdown lists for selecting related entities. For example, when a user creates an order, they can select a related customer from a dropdown list displaying the names of all customers. But what if the customer should be found not by its name but by their VAT number or some other attribute? Or the customer isn't registered yet and need to be entered along with the order?

Jmix offers a universal solution for the problem of advanced selection of related entities: it allows users to open a CRUD list view for the desired entity in a dialog window, find the entity instance and return it from there. This feature is implemented by the xref:flow-ui:actions/entity-picker-actions.adoc[lookup action]. By default, it uses the same CRUD view as for managing entities, but you can create a specific variant for the lookup.

Opening a lookup view in a dialog, which doesn't destroy the original view, makes returning results from the opened view straightforward - they are just passed as Java objects on the server side.

Dialog windows with lookup views can automatically stack on top of each other, providing the way to drill down into your data model without losing the initial context. For example, when creating an order, a user can open the list of customers in a dialog, then create a customer in a separate dialog, then create a customer's contact in its own dialog, and finally select the customer and continue editing the order. Jmix provides this functionality out-of-the-box by reusing the CRUD views created for managing entities.

==== XML Descriptors

A view layout can be defined declaratively in XML.

// todo

==== Event Listeners and Delegates

A view has a specific set of lifecycle events and provides a declarative way to handle all UI events (generated by the view and its components) using annotated methods.

// todo

=== Data Containers

// todo

=== DataContext

// todo

=== Editing Aggregates

// todo

== Security

// todo
