= Using Icons from Other Font Libraries

To enhance the custom theme, you may need to create icons and embed them into fonts, as well as use any external icons library. As an example, consider using the *Font Awesome 5* with the *Brands* style.

. Create the enum class implementing the `com.vaadin.server.FontIcon` interface for the new icons:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/FontAwesome5Brands.java[tags=new-font-icon]
----

. Add new styles to the xref:ui:themes/custom_theme.adoc[custom theme]. We recommend creating special subfolder `fonts` in the main folder of the custom theme, for example, `themes/helium-extended/fonts`. Put the styles and font files in their own subfolders, for example, `fonts/fontawesome`.
+
Files of fonts are represented by the following extensions:

* `.eot`,
* `.svg`,
* `.ttf`,
* `.woff`,
* `.woff2`.

+
--
The set of fonts `fontawesome` with the *Brands* style consists of 5 joint used files: `fa-brands-400.eot`, `fa-brands-400.svg`, `fa-brands-400.ttf`, `fa-brands-400.woff`, `fa-brands-400.woff2`.

If you want to use other styles (*Solid*, *Regular*, and so on), you need to define a unique class name for every FontAwesome variant. Also, you need to implement separate `IconSets` and `Providers` for every variant.
--
. Create a file with styles that includes `@font-face` and a CSS class with the icon style. Below is an example of the `fontawesome5.scss` file, where the `FontAwesome5Brands` class name corresponds to the value returned by the `FontIcon.getFontFamily()` method:
+
[source,css,indent=0]
----
include::example$/ex1/src/main/themes/helium-extended/fonts/fontawesome5/fontawesome5.scss[]
----

. Create a reference to the file with font styles in `helium-extended.scss` or other files of the custom theme:
+
[source,css,indent=0]
----
include::example$/ex1/src/main/themes/helium-extended/helium-extended.scss[tags=import-fontawesome5]
----

. Then create a new xref:ui:icons/icon-sets.adoc[icon set] which is an enumeration implementing the `Icons.Icon` interface:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/FontAwesome5Icon.java[tags=new-font-icon-set]
----

. Create a new `IconProvider`.
+
For managing custom icon sets Jmix framework provides the mechanism that consists of `IconProvider` and `IconResolver`.
+
`IconProvider` is a marker interface that can provide resources (`com.vaadin.server.Resource`) by the icon path.
+
The `IconResolver` bean obtains all beans that implement the `IconProvider` interface and iterates over them to find the one that can provide a resource for the icon.
+
To use this mechanism, you should create your implementation of `IconProvider`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/FontAwesome5BrandsIconProvider.java[tags=icon-provider]
----
+
Here we explicitly assign an order for this bean with the `@Order` annotation.

. Register your icon set in the `application.properties` file:
+
[source,properties,indent=0]
----
jmix.ui.icons-config = ui.ex1.icon.FontAwesome5Icon
----

Now you can use new icons by direct reference to their class and enum element in the XML descriptor of the screen:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=custom-icon]
----
or in the Java controller:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=set-custom-icon]
----

[[overriding-icons]]
== Overriding Icons with Icon Sets

The mechanism of icon sets enables you to override icons from other sets. To do this, you should create and register a new icon set (enumeration) with the same icons (options) but with different icon paths (`source`). In the following example, the new `MyIcon` enum is created to override the standard icons from the `JmixIcon` set.

. Create the new icon set:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/NewIcon.java[tags=override-icon]
----
. Register the new icon set in `application.properties`:
+
[source,properties,indent=0]
----
jmix.ui.icons-config = ui.ex1.icon.NewIcon
----

Now, the new *OK* icon will be used instead of the standard one:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=inject-icons;init-start;set-icon;init-end]
----

In case you need to ignore redefinitions, you still can use the standard icons by using the icon source instead of the option name:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=custom-ok-icon]
----

or

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=set-icon-source]
----
