= Icon Sets

Icon sets allow you to decouple the usage of icons in visual components from real paths to images in theme or font element constants. They also simplify the overriding of icons used in the UI inherited from add-ons.

Icon sets are enumerations with items corresponding to icons. An icon set must implement the `Icons.Icon` interface which has one parameter: a string that denotes the source of an icon, for example, `font-icon:CHECK` or `icons/myawesomeicon.png`. To obtain the source, use the `Icons` bean provided by the framework.

Consider the process of creating an icon set.

. Create an enum that will contain icons. All names of icon set items should match the regexp: `[A-Z]_`, that is, they should contain only upper-case letters and underscores.
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/MyIcon.java[tags=icon-set]
----
+
<1> Override a Jmix default icon.
<2> Add new icon.

. Register an icon set in the xref:ui:app-properties.adoc#jmix.ui.icons-config[jmix.ui.icons-config] property of the `application.properties` file:
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=register-icon-set]
----
. Now you can use the icons from this icon set simply by its name declaratively in the screen XML descriptor:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-set]
----
+
or programmatically in the screen controller:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=set-icon-from-set]
----

The following prefixes allow you to use icons from different sources in a declarative way:

* `theme` - the icon will be served from the current theme directory, for example, `themes/helium-extended/icons/check-mark.png`:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-theme]
----
* `file` - the icon will be served from the file system:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-file]
----
* `classpath` - the icon will be served from classpath:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-classpath]
----