= Наборы значков

Наборы значков (icon sets) позволяют отвязать использование значков в визуальных компонентах от конкретных путей к изображениям в теме или констант элементов шрифтов. Кроме того, они упрощают переопределение значков, используемых в UI, унаследованном от xref:modularity:index.adoc#subsystems[дополнений].

Наборы значков – это перечисления, каждый элемент которых соответствует некоторому значку. Класс перечисления должен реализовывать интерфейс `Icons.Icon` с единственным параметром - строкой, задающей источник получения значка, например, `font-icon:CHECK` или `icons/myawesomeicon.png`. Для получения источника значка следует использовать предоставляемый фреймворком бин `Icons`.

Рассмотрим процесс создания набора значков.

. Создайте перечисление, которое будет содержать значки. Имена элементов перечисления в наборе должны соответствовать регулярному выражению `[A-Z]_`, то есть содержать только заглавные буквы и нижнее подчеркивание.
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/MyIcon.java[tags=icon-set]
----
+
<1> Переопределение стандартного значка Jmix.
<2> Добавление нового значка.

. Зарегистрируйте набор значков в свойстве xref:ui:app-properties.adoc#jmix.ui.icons-config[jmix.ui.icons-config] файла `application.properties`:
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=register-icon-set]
----
. Теперь вы можете использовать значки из созданного набора, декларативно указывая имя соответствующего элемента enum в XML-дескрипторе:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-set]
----
+
или программно в контроллере экрана:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=set-icon-from-set]
----

Используя специальные префиксы, вы можете декларативно использовать значки из разных источников:

* `theme` - значок из темы приложения, например, `themes/helium-extended/icons/check-mark.png`:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-theme]
----
* `file` - файл с изображением:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-file]
----
* `classpath` - значок, расположенный в classpath:
+
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=icon-classpath]
----