= Добавление значков из других библиотек шрифтов

Для более тонкой настройки расширенной темы можно создать значки, встроенные в шрифты, либо использовать готовые внешние библиотеки значков. В качестве примера рассмотрим использование шрифта *Font Awesome 5* со стилем *Brands*.

. Создайте класс enum, реализующий интерфейс `com.vaadin.server.FontIcon`, в который поместите новые значки:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/FontAwesome5Brands.java[tags=new-font-icon]
----

. Добавьте новые стили и файлы шрифта в xref:ui:themes/custom_theme.adoc[свою тему]. Рекомендуется создать отдельную папку `fonts` в главном каталоге расширения темы, например, `themes/helium-extended/fonts`. Поместите в нее стили и файлы шрифтов в своих собственных подпапках, например, `fonts/fontawesome`.
+
Файлы шрифта включают в себя набор следующих расширений:

* `.eot`,
* `.svg`,
* `.ttf`,
* `.woff`,
* `.woff2`.

+
--
Набор шрифтов `fontawesome` со стилем *Brands* представлен в виде 5 файлов: `fa-brands-400.eot`, `fa-brands-400.svg`, `fa-brands-400.ttf`, `fa-brands-400.woff`, `fa-brands-400.woff2`, которые используются совместно.

Если вы хотите использовать другие стили (*Solid*, *Regular* и так далее), нужно определить уникальное имя класса для каждого варианта FontAwesome. Также необходимо реализовать отдельные `IconSets` и `Providers` для каждого варианта.
--
. Создайте файл стилей, в который включите `@font-face` и CSS класс со стилем для значка. Ниже представлен пример файла `fontawesome5.scss`, где имя класса `FontAwesome5Brands` соответствует значению, возвращаемому методом `FontIcon.getFontFamily()`:
+
[source,css,indent=0]
----
include::example$/ex1/src/main/themes/helium-extended/fonts/fontawesome5/fontawesome5.scss[]
----

. Подключите файл стилей шрифта в `helium-extended.scss` или другой файл данной темы:
+
[source,css,indent=0]
----
include::example$/ex1/src/main/themes/helium-extended/helium-extended.scss[tags=import-fontawesome5]
----

. Затем создайте новый xref:ui:icons/icon-sets.adoc[набор значков], то есть enum, реализующий интерфейс `Icons.Icon`:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/FontAwesome5Icon.java[tags=new-font-icon-set]
----

. Создайте новый `IconProvider`.
+
Для работы с наборами значков в фреймворке Jmix есть механизм, основанный на использовании `IconProvider` и `IconResolver`.
+
`IconProvider` – это интерфейс-маркер, который предоставляет доступ к ресурсу (`com.vaadin.server.Resource`) по переданному пути.
+
Бин `IconResolver` проходится по всем бинам, реализующим `IconProvider`, в поисках того, кто может предоставить ресурс к данному значку.
+
Чтобы использовать этот механизм, необходимо создать собственную реализацию `IconProvider`, например, так:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/FontAwesome5BrandsIconProvider.java[tags=icon-provider]
----
+
Здесь мы явно назначаем порядок для этого бина аннотацией `@Order`.

. Далее нужно зарегистрировать набор значков в файле `application.properties`:
+
[source,properties,indent=0]
----
jmix.ui.icons-config = ui.ex1.icon.FontAwesome5Icon
----

Теперь вы можете использовать значки по прямой ссылке на класс и элемент enum в XML-дескрипторе экрана:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=custom-icon]
----
или в контроллере Java:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=set-custom-icon]
----

[[overriding-icons]]
== Переопределение значков с помощью наборов

Механизм наборов значков позволяет переопределять некоторые значки из других наборов. Для этого необходимо создать и зарегистрировать новый набор значков (enumeration) с теми же именами значков (options), но с другими путями (`source`). В примере ниже создан новый набор `MyIcon`, в котором переопределены стандартные значки из набора `JmixIcon`.

. Создайте новый набор значков:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/icon/NewIcon.java[tags=override-icon]
----
. Зарегистрируйте новый набор значков в `application.properties`:
+
[source,properties,indent=0]
----
jmix.ui.icons-config = ui.ex1.icon.NewIcon
----

Теперь вместо стандартного значка *OK* будет использован новый:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=inject-icons;init-start;set-icon;init-end]
----

При необходимости игнорировать переопределение и использовать стандартные значки, просто используйте путь к значку вместо имени элемента перечисления:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/button/button-screen.xml[tags=custom-ok-icon]
----

или

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/button/ButtonScreen.java[tags=set-icon-source]
----
