[[permissions]]
= Report Access Rights

You can define user rights to access the report as well as report availability in certain application screens in the *Roles and Screens* tab of the report editor.

If the *Resource roles* list contains at least one role, the report will be available only to users with this role. If no role is specified, the report is available to everyone.

[TIP]
====
Keep in mind that in the reports browser (the *Reports->Reports* menu item) all system reports are visible because this screen is considered administrative.
====

The *Screens* list allows you to specify, in which screens the report will be available when invoking xref:run-report.adoc#run_report_action[RunReportAction], xref:run-report.adoc#list_print_form_action[ListPrintFormAction], xref:run-report.adoc#editor_print_form_action[EditorPrintFormAction] or xref:exec-history.adoc#execution_history_action[ExecutionHistoryAction] actions. If no screen is specified, the report won't be available from any application screen.

