[[permissions]]
= Roles and Views

You can define user rights to access the report as well as report availability in certain application views in the *Roles and views* tab of the report detail view.

If the *Resource roles* list contains at least one role, the report will be available only to users with this role. If no role is specified, the report is available to everyone.

[TIP]
====
Keep in mind that in the report list view (the *Reports->Reports* menu item) all system reports are visible because this view is considered administrative.
====

The *Views* list allows you to specify, in which views the report will be available when invoking xref:run-report.adoc#run_report_action[RunReportAction], xref:run-report.adoc#run-list-entity-report-action[RunListEntityReportAction], xref:run-report.adoc#run-single-entity-report-action[RunSingleEntityReportAction] or xref:exec-history.adoc#execution_history_action[ShowExecutionReportHistoryAction] actions. If no view is specified, the report won't be available from any application view.

