= Backoffice UI Properties

[[jmix.ui.appWindowMode]]
== jmix.ui.appWindowMode

Determines an initial mode for the main application window – `TABBED` or `SINGLE`. In the `SINGLE` mode, when a screen opens with the `NEW_TAB` parameter, it completely replaces the current screen instead of opening a new tab.

Default value: `TABBED`

[[jmix.ui.htmlSanitizerEnabled]]
== jmix.ui.htmlSanitizerEnabled

Determines whether the `HtmlSanitizer` bean should be used by the UI components implementing the `HasHtmlSanitizer` interface to prevent cross-site scripting (XSS) in HTML content. The sanitization can also be enabled or disabled by individual components using xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] attribute.

Default value: `true`

[[jmix.ui.comboBoxPageLength]]
== jmix.ui.comboBoxPageLength

Defines the default number of options on one page of the drop-down list in the xref:vcl/components/combo-box.adoc[ComboBox] and xref:vcl/components/entity-combo-box.adoc[EntityComboBox] components. It can be overridden for a concrete instance of the component using the xref:vcl/components/combo-box.adoc#paging[pageLength] XML attribute.

Default value: 10.

[[jmix.ui.defaultScreenCanBeClosed]]
== jmix.ui.defaultScreenCanBeClosed

Defines whether the default screen can be closed by close button, *ESC* button or `TabSheet` context menu when `TABBED` <<jmix.ui.appWindowMode,work area mode>> is used.

Default value: `true`

[[jmix.ui.defaultScreenId]]
== jmix.ui.defaultScreenId

Defines a screen to be opened after login. This setting will be applied to all users.

For example:

[source,properties]
----
jmix.ui.defaultScreenId = sample_Order.browse
----

[[jmix.ui.mainScreenId]]
== jmix.ui.mainScreenId

An identifier of a screen to be used as xref:backoffice-ui:screens/root-screens.adoc#main-screen[main screen] of the application.

Default value: `MainScreen`

[[jmix.ui.maxTabCount]]
== jmix.ui.maxTabCount

Defines the maximum number of tabs that can be opened in the main application window. The value of 0 disables this limitation.

Default value: `20`

[[jmix.ui.maxUploadSizeMb]]
== jmix.ui.maxUploadSizeMb

Maximum file size (in megabytes) that can be uploaded using the xref:vcl/components/file-upload-field.adoc[FileUploadField], xref:vcl/components/file-multi-upload-field.adoc[FileMultiUploadField], xref:vcl/components/file-storage-upload-field.adoc[FileStorageUploadField]  components.

Default value: `20`.

[[jmix.ui.loginScreenId]]
== jmix.ui.loginScreenId

An identifier of a screen to be used as xref:backoffice-ui:screens/root-screens.adoc#login-screen[login screen] of the application.

Default value: `LoginScreen`

[[jmix.ui.theme]]
== jmix.ui.theme

Defines the name of the xref:themes.adoc[theme] used as default. See also <<jmix.ui.themeConfig,jmix.ui.themeConfig>>.

Default value: `helium`.

[[jmix.ui.themeConfig]]
== jmix.ui.themeConfig

Defines a `<theme-name>-theme.properties` file or files that store theme variables, such as default popup window dimensions and input field width.

Default value:
[source, code,indent=0]
----
io/jmix/ui/theme/helium-theme.properties \
io/jmix/ui/theme/halo-theme.properties \
io/jmix/ui/theme/hover-theme.properties
----

[[jmix.ui.screen.closeShortcut]]
== jmix.ui.screen.closeShortcut

Defines the keyboard shortcut that closes the current xref:backoffice-ui:screens.adoc[screen].

Default value: `ESCAPE`

[[jmix.ui.screen.useSaveConfirmation]]
== jmix.ui.screen.useSaveConfirmation

Defines the layout of the dialog displayed when a user attempts to close a xref:backoffice-ui:screens.adoc[screen] with unsaved changes in `DataContext`.

Value of `true` corresponds to a layout with three possible actions: "Save changes", "Don’t save", "Don’t close the screen".

The value of `false` corresponds to a form with two options: "Close the screen without saving changes", "Don’t close the screen".

Default value: `true`