= Backoffice UI Properties

[[jmix.ui.appWindowMode]]
== jmix.ui.appWindowMode

Determines an initial mode for the main application window – `TABBED` or `SINGLE`. In the `SINGLE` mode, when a screen opens with the `NEW_TAB` parameter, it completely replaces the current screen instead of opening a new tab.

Default value: `TABBED`.

[[jmix.ui.defaultScreenCanBeClosed]]
== jmix.ui.defaultScreenCanBeClosed

Defines whether the default screen can be closed by close button, *ESC* button or `TabSheet` context menu when `TABBED` <<jmix.ui.appWindowMode,work area mode>> is used.

Default value: `true`.

[[jmix.ui.defaultScreenId]]
== jmix.ui.defaultScreenId

Defines a screen to be opened after login. This setting will be applied to all users.

For example:

[source,properties]
----
jmix.ui.defaultScreenId = sample_Order.browse
----

[[jmix.ui.mainScreenId]]
== jmix.ui.mainScreenId

An identifier of a screen to be used as xref:backoffice-ui:screens/root-screens.adoc#main-screen[main screen] of the application.

Default value: `MainScreen`.

[[jmix.ui.maxTabCount]]
== jmix.ui.maxTabCount

Defines the maximum number of tabs that can be opened in the main application window. The value of 0 disables this limitation.

Default value: `20`.

[[jmix.ui.loginScreenId]]
== jmix.ui.loginScreenId

An identifier of a screen to be used as xref:backoffice-ui:screens/root-screens.adoc#login-screen[login screen] of the application.

Default value: `LoginScreen`.

[[jmix-ui-component-combo-box-page-length]]
== jmix.ui.component.comboBoxPageLength

Defines the default number of options on one page of the drop-down list in the xref:vcl/components/combo-box.adoc[ComboBox] and xref:vcl/components/entity-combo-box.adoc[EntityComboBox] components. It can be overridden for a concrete instance of the component using the xref:vcl/components/combo-box.adoc#paging[pageLength] XML attribute.

Default value: `10`.

[[jmix-ui-component-filter-auto-apply]]
== jmix.ui.component.filterAutoApply

When set to `true`, the xref:vcl/components/filter.adoc[Filter] component works in the immediate mode when every change of filter parameters automatically reloads data. When set to `false`, filter will be applied only after the *Refresh* button is clicked. This property can be overridden for a concrete instance of the `Filter` component using the xref:vcl/components/filter.adoc#filter-attribute-auto-apply[autoApply] XML attribute.

Default value: `true`.

[[jmix-ui-component-filter-columns-count]]
== jmix.ui.component.filterColumnsCount

Sets the default number of columns for placing conditions on the filter panel. It can be overridden for a concrete instance of the `Filter` component using the xref:vcl/components/filter.adoc#filter-attribute-columns-count[columnsCount] XML attribute.

Default value: `3`.

[[jmix-ui-component-filter-properties-hierarchy-depth]]
== jmix.ui.component.filterPropertiesHierarchyDepth

Defines the properties hierarchy depth in the xref:vcl/components/filter.adoc#add-condition[Add Condition] editor in filter. For example, if the depth value is 2, then you can select an entity attribute `contractor.city.country`, if the value is 3, then `contractor.city.country.name`, etc.

Default value: `2`.

[[jmix-ui-component-filter-show-configuration-id-field]]
== jmix.ui.component.filterShowConfigurationIdField

Determines whether the *Configuration id* field should be visible in the xref:vcl/components/filter.adoc#run-time-configuration[Configuration editor] screen of the `Filter` component. By default, the *Configuration id* field is not shown, and the `configurationId` is generated depending on the `configurationName`.

Default value: `false`.

[[jmix-ui-component-html-sanitizer-enabled]]
== jmix.ui.component.htmlSanitizerEnabled

Determines whether the `HtmlSanitizer` bean should be used by the UI components implementing the `HasHtmlSanitizer` interface to prevent cross-site scripting (XSS) in HTML content. The sanitization can also be enabled or disabled by individual components using xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] attribute.

Default value: `true`.

[[jmix-ui-component-pagination-items-per-page-options]]
== jmix.ui.component.paginationItemsPerPageOptions

Defines the options for the drop-down list that can be used as a number of items per page for xref:vcl/components/pagination.adoc[Pagination]. To configure a custom list of options for a concrete instance of the `Pagination` component, use the xref:vcl/components/pagination.adoc#items-per-page-options[itemsPerPageOptions] XML attribute.

Default value: `20`, `50`, `100`, `500`, `1000`, `5000`.


[[jmix-ui-component-upload-field-max-upload-size-mb]]
== jmix.ui.component.uploadFieldMaxUploadSizeMb

Maximum file size (in megabytes) that can be uploaded using the xref:vcl/components/file-upload-field.adoc[FileUploadField], xref:vcl/components/file-multi-upload-field.adoc[FileMultiUploadField], xref:vcl/components/file-storage-upload-field.adoc[FileStorageUploadField]  components.

Default value: `20`.

[[jmix.ui.screen.closeShortcut]]
== jmix.ui.screen.closeShortcut

Defines the keyboard shortcut that closes the current xref:backoffice-ui:screens.adoc[screen].

Default value: `ESCAPE`.

[[jmix.ui.screen.useSaveConfirmation]]
== jmix.ui.screen.useSaveConfirmation

Defines the layout of the dialog displayed when a user attempts to close a xref:backoffice-ui:screens.adoc[screen] with unsaved changes in `DataContext`.

Value of `true` corresponds to a layout with three possible actions: "Save changes", "Don’t save", "Don’t close the screen".

The value of `false` corresponds to a form with two options: "Close the screen without saving changes", "Don’t close the screen".

Default value: `true`.

[[jmix.ui.themeConfig]]
== jmix.ui.themeConfig

Defines a `<theme-name>-theme.properties` file or files that store theme variables, such as default popup window dimensions and input field width.

Default value:
[source, code,indent=0]
----
io/jmix/ui/theme/helium-theme.properties \
io/jmix/ui/theme/halo-theme.properties \
io/jmix/ui/theme/hover-theme.properties
----

[[jmix-ui-theme-name]]
== jmix.ui.theme.name

Defines the name of the xref:themes.adoc[theme] used as default. See also <<jmix.ui.themeConfig,jmix.ui.themeConfig>>.

Default value: `helium`.