= Backoffice UI Properties

[[jmix.ui.htmlSanitizerEnabled]]
== jmix.ui.htmlSanitizerEnabled

Determines whether the `HtmlSanitizer` bean should be used by the UI components implementing the `HasHtmlSanitizer` interface to to prevent cross-site scripting (XSS) in HTML content. The sanitization can also be enabled or disabled by individual components using xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] attribute.

Default value: `true`

[[jmix.ui.comboBoxPageLength]]
== jmix.ui.comboBoxPageLength

Defines the default number of options on one page of the drop-down list in the xref:vcl/components/combo-box.adoc[ComboBox] and xref:vcl/components/entity-combo-box.adoc[EntityComboBox] components. It can be overridden for a concrete instance of the component using the xref:vcl/components/combo-box.adoc#paging[pageLength] XML attribute.

Default value: 10.

[[jmix.ui.theme]]
== jmix.ui.theme

Defines the name of the xref:themes.adoc[theme] used as default. See also <<jmix.ui.themeConfig,jmix.ui.themeConfig>>.

Default value: `helium`.

[[jmix.ui.themeConfig]]
== jmix.ui.themeConfig

Defines a `<theme-name>-theme.properties` file or files that store theme variables, such as default popup window dimensions and input field width.

Default value:
[source, code,indent=0]
----
io/jmix/ui/theme/helium-theme.properties \
io/jmix/ui/theme/halo-theme.properties \
io/jmix/ui/theme/hover-theme.properties
----
