= Компоненты данных

Компоненты данных – это невизуальные элементы экрана, которые обеспечивают загрузку данных, привязку их к визуальным компонентам и сохранение измененных экземпляров обратно в хранилище данных. Существуют следующие типы компонентов данных:

* xref:backoffice-ui:data/data-containers.adoc[Контейнеры] обеспечивают тонкий слой между сущностями и визуальными компонентами, связанными с данными (data-aware). Разные типы контейнеров могут хранить один экземпляр или коллекцию экземпляров сущностей.
* xref:backoffice-ui:data/data-loaders.adoc[Загрузчики] загружают данные в контейнеры.
* xref:backoffice-ui:data/data-context.adoc[DataContext] отслеживает изменения сущностей и сохраняет измененные экземпляры по запросу.

Обычно компоненты данных задаются в XML-дескрипторе экрана внутри элемента `<data>`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/data/department-browse-data.xml[tags=data]
----

Компоненты данных можно инжектировать в контроллер экрана так же, как и визуальные компоненты:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/data/DepartmentBrowseData.java[tags=loader;name;before-show]
----

Компоненты данных конкретного экрана регистрируются в объекте `ScreenData`, который связан с контроллером экрана и доступен с помощью метода `getScreenData()` экрана. Этот объект полезен в прикладном коде, когда необходимо загрузить все данные экрана, к примеру:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/data/DepartmentEditData.java[tags=before-show]
----

NOTE: Используйте фасет `DataLoadCoordinator` для декларативного связывания загрузчиков данных с контейнерами данных, визуальными компонентами и событиями экрана. В случае, если необходимо установить некоторые параметры загрузки, можно использовать программную загрузку, как описано в разделе  xref:backoffice-ui:data/data-examples.adoc#using-screen-parameters-in-loaders[Использование компонентов данных].