= Data Components

Data components are non-visual elements of screens that provide loading of data, binding it to data-aware visual components and saving changed data back to the data store. There are the following categories of data components:

* xref:backoffice-ui:data/data-containers.adoc[Containers] provide the thin layer between entities and data-aware visual components. Different types of containers hold either single instances or collections of entities.
* xref:backoffice-ui:data/data-loaders.adoc[Loaders] load data to containers.
* xref:backoffice-ui:data/data-context.adoc[DataContext] tracks changes in entities and saves changed instances upon request.

Usually, data components are defined in the screen XML descriptor in the `<data>` element:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/data/department-browse-data.xml[tags=data]
----

Data components can be injected into the controller in the same way as visual components:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/data/DepartmentBrowseData.java[tags=loader;name;before-show]
----

Data components of a particular screen are registered in the `ScreenData` object which is associated with the screen controller and available through its `getScreenData()` method. This object is useful when you need to load all data for the screen, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/data/DepartmentEditData.java[tags=before-show]
----

NOTE: Use `DataLoadCoordinator` facet for declarative linking of data loaders to data containers, visual components and screen events. In case you need to set some loading parameters, you can use programmatic loading. 