= Пользовательский интерфейс

Пользовательский интерфейс Jmix позволяет разрабатывать богатые веб-интерфейсы используя Java и XML. Он основан на веб-фреймворке https://vaadin.com[Vaadin^].

В Jmix UI компоненты пользовательского интерфейса работают в той же JVM, что и бэкенд, что значительно упрощает работу с данными и вызов бизнес-логики. Кроме того, он не требует знакомства с современным стеком JavaScript/HTML/CSS.

Технология Jmix UI имеет ограниченную масштабируемость: бэкенд-часть пользовательского интерфейса является stateful и потребляет объем ресурсов, пропорциональный количеству одновременных пользовательских сеансов. Поэтому UI подходит для работы при предсказуемом и не очень большом (до десятков тысяч) количестве пользователей, одновременно работающих с системой.

Для web-scale проекта и полной свободы настройки UI рассмотрите возможность создания фронтенд-приложения используя традиционные фронтенд-технологии. Работа с бэкендом Jmix будет осуществляться через xref:rest:index.adoc[REST API].
