= BaseAction

`BaseAction` – это базовый класс реализации действий. От него рекомендуется наследовать собственные нестандартные действия, если возможностей xref:actions/declarative-actions.adoc[декларативного создания действий] не хватает.

При создании конкретного класса действия необходимо определить метод `actionPerform()` и передать в конструктор `BaseAction` идентификатор действия. Можно также переопределить любые методы получения свойств действия: `getCaption()`, `getDescription()`, `getIcon()`, `getShortcut()`, `isEnabled()`, `isVisible()`, `isPrimary()`. Стандартные реализации этих методов возвращают значения, установленные соответствующими setter-методами. Исключение составляет метод `getCaption()`: если название действия явно не установлено методом `setCaption()`, то он обращается в пакет локализованных сообщений с именем, соответствующим пакету класса действия, и возвращает сообщение с ключом, равным идентификатору действия. Если сообщения с таким ключом нет, то возвращается сам ключ, то есть идентификатор действия.

В качестве альтернативы переопределению методов можно использовать fluent API для установки свойств и lambda-выражений для предоставления кода обработки действия: см. методы `withXYZ()`.

BaseAction может изменять свои свойства enabled и visible в соответствии с разрешениями xref:security:index.adoc[пользователя] и текущим контекстом.

`BaseAction` видим (visible), если:

* метод `setVisible(false)` не вызывался;
* для действия не установлено UI разрешение hide.

Действие разрешено (enabled), если:

* метод `setEnabled(false)` не вызывался;
* для действия не установлено UI разрешений hide или read-only;
* метод `isPermitted()` возвращает `true`;
* метод `isApplicable()` возвращает `true`;
* все `EnabledRules` (если таковые есть) возвращают `true`.

Примеры использования:

== Действие Button

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-sayHelloBtn;notifications;on-init-start;base-action-button;on-init-end]
----

В данном случае кнопка `sayHelloBtn` получит в качестве заголовка строку, находящуюся в пакете сообщений с ключом `hello`. Для того, чтобы получить название кнопки каким-либо иным способом, можно переопределить метод `getCaption()` действия.

== Действие ValuePicker

Действие программно создаваемого `ValuePicker`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/valuepicker/ValuePickerScreen.java[tags=inject-notifications;inject-messageBundle;inject-uiComponents;inject-vBox;onInit-start;base-action-value-picker;onInit-end]
----

Здесь анонимный класс-наследник `BaseAction` используется для задания действия кнопки поля выбора. Заголовок кнопки не отображается, вместо него используется значок и описание, всплывающее при наведении курсора мыши.

== Действие Table

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/table/TableScreen.java[tags=inject-customersTable;inject-notifications;onInit-start;add-base-action;onInit-end;base-action-table]
----

Здесь объявлен класс `AboutSingleAction`, экземпляр которого добавляется в список действий таблицы. Действие разрешено когда выбрана одна строка таблицы. Последнее условие реализуется с помощью свойства `target` действия, которое автоматически устанавливается, когда действие добавляется в `ListComponent` (`Table` или `Tree`).

== Использование ItemTrackingAction

Если необходимо действие, которое доступно, когда выделены одна или более строк таблицы, удобно воспользоваться наследником `BaseAction` – классом `ItemTrackingAction`, который добавляет стандартную реализацию метода `isApplicable()`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/table/TableScreen.java[tags=inject-customersTable;inject-notifications;onInit-start;add-ItemTrackingAction;onInit-end]
----