= BaseAction

`BaseAction` is a base class for action implementation. It is recommended to derive custom actions from it when xref:actions/declarative-actions.adoc[declarative action creation] functionality is insufficient.

When creating a custom action class, you should implement the `actionPerform()` method and pass the action identifier to the `BaseAction` constructor. You can override any property getters: `getCaption()`, `getDescription()`, `getIcon()`, `getShortcut()`, `isEnabled()`, `isVisible()`, `isPrimary()`. Standard implementations of these methods return values set by setter methods, except the `getCaption()` method. If the action name is not explicitly set by `setCaption()` method, it retrieves a message using action identifier as key from the localized message pack corresponding to the action class package. If there is no message with such key, then the key itself, that is, the action identifier is returned.

Alternatively, you can use the fluent API for setting properties and providing a lambda expression for handling the action: see `withXYZ()` methods.

`BaseAction` can change its enabled and visible properties depending on user xref:security:index.adoc[permissions] and current context.

`BaseAction` is visible if the following conditions are met:

* `setVisible(false)` method was not called;
* there is no "hide" UI permission for this action.

The action is enabled if the following conditions are met:

* `setEnabled(false)` method was not called;
* there are no "hide" or "read-only" UI permissions for this action;
* `isPermitted()` method returns `true`;
* `isApplicable()` method returns `true`;
* all `EnabledRules` (if any) return `true`.

Usage examples:

== Button action

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=inject-sayHelloBtn;notifications;on-init-start;base-action-button;on-init-end]
----

In this example, the `sayHelloBtn` button caption will be set to the string located in the message pack with the `hello` key. You can override the `getCaption()` action method to initialize the button name differently.

== ValuePicker action

Action of a programmatically created `ValuePicker`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/valuepicker/ValuePickerScreen.java[tags=inject-notifications;inject-messageBundle;inject-uiComponents;inject-vBox;onInit-start;base-action-value-picker;onInit-end]
----

In this example, an anonymous `BaseAction` derived class is used to set the actions of the value picker buttons. The button's caption is not displayed, as an icon with a description, which pops up when hovering mouse cursor, is used instead.

== Table action

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/table/TableScreen.java[tags=inject-customersTable;inject-notifications;onInit-start;add-base-action;onInit-end;base-action-table]
----

In this example, the `AboutSingleAction` class is declared, and its instance is added to the table’s actions list. The action is enabled when a single table row is selected. The latter is possible because BaseAction’s `target` property is automatically assigned to the action when it is added to a `ListComponent` descendant (`Table` or `Tree`).

== Using ItemTrackingAction

If you need an action, which becomes enabled when one or more table rows are selected, use BaseAction’s descendant - `ItemTrackingAction`, which adds default implementation of `isApplicable()` method:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/component/table/TableScreen.java[tags=inject-customersTable;inject-notifications;onInit-start;add-ItemTrackingAction;onInit-end]
----