= 标准操作
:page-aliases: backoffice-ui:actions/standard-actions.adoc

框架提供标准操作用于处理常见任务，例如为表格中选择的实体调用编辑界面。通过在 `type` 属性中指定其类型，就可以在界面 XML 描述中声明标准操作。

每个标准操作都通过一个使用了 `@ActionType("<some_type>")` 注解的类实现。该类定义了操作的默认属性和行为。

可以通过指定基本操作的 XML 属性来覆盖通用的属性：`caption`、`icon`、`shortcut` 等。示例：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=standard-action-create]
----

有两种类型的标准操作：

* <<list-actions,列表组件操作>>。
* <<picker-actions,选取器组件操作>>。

[[list-actions]]
== 列表组件操作

列表组件操作用于处理展示在表格或树中的实体集合。包括 xref:actions/standard-actions/add-action.adoc[AddAction]、xref:actions/standard-actions/bulk-edit-action.adoc[BulkEditAction]、xref:actions/standard-actions/create-action.adoc[CreateAction]、xref:actions/standard-actions/edit-action.adoc[EditAction]、xref:actions/standard-actions/exclude-action.adoc[ExcludeAction]、xref:actions/standard-actions/refresh-action.adoc[RefreshAction]、xref:actions/standard-actions/related-action.adoc[RelatedAction]、xref:actions/standard-actions/remove-action.adoc[RemoveAction]、xref:actions/standard-actions/view-action.adoc[ViewAction]。

当表格、树或者数据网格添加了列表组件操作之后，可以从组件的右键菜单或者预定义的快捷键调用这些操作。通常也会使用添加在按钮面板的一个按钮调用操作。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=group-table-list-actions]
----

[[picker-actions]]
== 选取器组件操作

选取器组件操作用于处理选取器组件的内容。包括 xref:actions/standard-actions/entity-clear-action.adoc[EntityClearAction]、xref:actions/standard-actions/entity-lookup-action.adoc[EntityLookupAction]、xref:actions/standard-actions/entity-open-action.adoc[EntityOpenAction]、xref:actions/standard-actions/entity-open-composition-action.adoc[EntityOpenCompositionAction]、xref:actions/standard-actions/tag-lookup-action.adoc[TagLookupAction]、xref:actions/standard-actions/value-clear-action.adoc[ValueClearAction]、xref:vcl/components/values-picker.adoc#select-action[ValuesSelectAction]。

当组件添加了选取器操作之后，自动使用组件的内嵌按钮展示。

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=entityPicker3actions]
----

== 附加属性

标准操作带有附加参数，可以在 XML 进行设置或者在 Java 中用 setter 方法进行设置。在 XML 中，使用内部的 `<properties>` 元素设置，其中每个 `<property>` 元素对应一个操作类中的 setter 方法：

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=create-action]
----

在 Java 控制器也可以做同样的设置：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=create-action;on-init-start;create-action-set;on-init-end]
----

== 注册处理器

如果一个 setter 接收功能接口参数，可以在界面控制器注册一个处理方法。比如，`CreateAction` 有 `setAfterCommitHandler(Consumer)` 方法，设置一个处理方法，该方法会在创建的实体提交之后调用。那么可以按照下面的方式注册处理器：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=handler]
----

[TIP]
====
可以用 xref:studio:index.adoc[Studio] 生成处理器的实现桩代码。
====

所有的操作都有一个通用的 `enabledRule` 处理器，可以根据不同的情景设置操作的 “启用” 状态。下面的例子中，对某些实体禁用了 `RemoveAction`：

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=table;enabledRule]
----
