= Standard Actions
:page-aliases: backoffice-ui:actions/standard-actions.adoc

The framework provides standard actions to solve common tasks, such as an invocation of an edit screen for an entity selected in a table. A standard action should be declared in the screen XML descriptor by specifying its type in the `type` attribute.

Each standard action is implemented by a class annotated with `@ActionType("<some_type>")`. The class defines the action’s default properties and behavior.

You can specify any basic action XML attributes to override common action properties: `caption`, `icon`, `shortcut`, etc. For example:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=standard-action-create]
----

There are two categories of standard actions:

* <<list-actions,List actions>>.
* <<picker-actions,Picker field actions>>.

[[list-actions]]
== List Actions

List actions work with collections of entities that are displayed in tables or trees. These are xref:actions/standard-actions/add-action.adoc[AddAction], xref:actions/standard-actions/bulk-edit-action.adoc[BulkEditAction], xref:actions/standard-actions/create-action.adoc[CreateAction], xref:actions/standard-actions/edit-action.adoc[EditAction], xref:actions/standard-actions/exclude-action.adoc[ExcludeAction], xref:actions/standard-actions/refresh-action.adoc[RefreshAction], xref:actions/standard-actions/related-action.adoc[RelatedAction], xref:actions/standard-actions/remove-action.adoc[RemoveAction], xref:actions/standard-actions/view-action.adoc[ViewAction].

When a list action is added to a table, tree, or data grid, it can be invoked from the component’s context menu item and by its predefined keyboard shortcut. Usually, the action is also invoked by a button added to the buttons panel.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=group-table-list-actions]
----

[[picker-actions]]
== Picker Actions

Picker actions work with the content of the field. These are xref:actions/standard-actions/entity-clear-action.adoc[EntityClearAction], xref:actions/standard-actions/entity-lookup-action.adoc[EntityLookupAction], xref:actions/standard-actions/entity-open-action.adoc[EntityOpenAction], xref:actions/standard-actions/entity-open-composition-action.adoc[EntityOpenCompositionAction], xref:actions/standard-actions/tag-lookup-action.adoc[TagLookupAction], xref:actions/standard-actions/value-clear-action.adoc[ValueClearAction], xref:vcl/components/values-picker.adoc#select-action[ValuesSelectAction].

When a picker action is added to the component, it is automatically represented by a button inside the field.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=entityPicker3actions]
----

== Additional Properties

Standard actions have additional properties that can be set in XML or using setters in Java. In XML, additional properties are configured using the nested `<properties>` element, where each `<property>` element corresponds to a setter existing in this action class:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=create-action]
----

The same can be done in Java controller:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=create-action;on-init-start;create-action-set;on-init-end]
----

== Installing Handlers

If a setter accepts a functional interface, you can install a handler method in the screen controller. For example, `CreateAction` has `setAfterCommitHandler(Consumer)` method which is used to set a handler to be invoked after the created entity is committed. Then you can provide the handler as follows:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=handler]
----

[TIP]
====
You can generate handlers implementation stubs using xref:studio:index.adoc[Studio].
====

There is a common `enabledRule` handler available to all actions, which allows you to set the action "enabled" state depending on the situation. In the example below, it disables `RemoveAction` for some entities:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=table;enabledRule]
----