= Стандартные действия

Предлагаемые фреймворком стандартные действия, предназначены для решения типовых задач, таких как вызов экрана редактирования для сущности, выбранной в таблице. Стандартные действия объявляются в XML-дескрипторе экрана с указанием их типа в атрибуте `type`.

Каждое стандартное действие реализуется классом, аннотированным `@ActionType("<some_type>")`. Класс задает свойства и поведение действия по умолчанию.

Для переопределения общих свойств действий можно задать XML-атрибуты элемента action, такие как `caption`, `icon`, `shortcut` и др., например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=standard-action-create]
----

Существует два вида стандартных действий:

* <<list-actions,Действия с коллекцией>>.
* <<picker-actions,Действия поля выбора>>.

[[list-actions]]
== Действия с коллекцией

Действия с коллекцией сущностей, отображаемой в таблице или дереве. Это xref:actions/standard-actions/add-action.adoc[AddAction], xref:actions/standard-actions/bulk-edit-action.adoc[BulkEditAction], xref:actions/standard-actions/create-action.adoc[CreateAction], xref:actions/standard-actions/edit-action.adoc[EditAction], xref:actions/standard-actions/exclude-action.adoc[ExcludeAction], xref:actions/standard-actions/refresh-action.adoc[RefreshAction], xref:actions/standard-actions/related-action.adoc[RelatedAction], xref:actions/standard-actions/remove-action.adoc[RemoveAction], xref:actions/standard-actions/view-action.adoc[ViewAction].

Когда действие с коллекцией добавлено в таблицу или дерево, оно может быть вызвано из контекстного меню данного компонента или с помощью предустановленной горячей клавиши. Обычно для вызова действия используется также кнопка, добавленная в панель кнопок.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=group-table-list-actions]
----

[[picker-actions]]
== Действия поля выбора

Действия поля выбора работают с содержимым поля. Это xref:actions/standard-actions/entity-clear-action.adoc[EntityClearAction], xref:actions/standard-actions/entity-lookup-action.adoc[EntityLookupAction], xref:actions/standard-actions/entity-open-action.adoc[EntityOpenAction], xref:actions/standard-actions/entity-open-composition-action.adoc[EntityOpenCompositionAction], xref:actions/standard-actions/tag-lookup-action.adoc[TagLookupAction], xref:actions/standard-actions/value-clear-action.adoc[ValueClearAction], xref:vcl/components/values-picker.adoc#select-action[ValuesSelectAction].

Когда такое действие добавляется в компонент, оно автоматически отображается кнопкой внутри поля.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/component/entitypicker/entityPicker-screen.xml[tags=entityPicker3actions]
----

== Дополнительные параметры

Стандартные действия имеют дополнительные параметры, которые могут быть установлены в XML или используя сеттеры в Java. В XML дополнительные параметры конфигурируются во вложенном элементе `<properties>`, где каждый элемент `<property>` соответствует сеттеру, имеющемуся в классе данного действия:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/actions/action-screen.xml[tags=create-action]
----

То же самое можно сделать в контроллере на Java:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=create-action;on-init-start;create-action-set;on-init-end]
----

== Установка обработчиков

Если сеттер принимает функциональный интерфейс, то в контроллере можно создать соответствующий метод-обработчик. Например, `CreateAction` имеет метод `setAfterCommitHandler(Consumer)`, который используется для установки обработчика, вызываемого после коммита созданной сущности. Тогда обработчик можно задать следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=handler]
----

[TIP]
====
Вы можете сгенерировать заглушку реализации обработчика с помощью xref:studio:index.adoc[Studio].
====

Во всех действиях имеется обработчик `enabledRule`, который позволяет управлять состоянием "enabled" действия в зависимости от некоторых условий. В примере ниже данный обработчик запрещает `RemoveAction` для некоторых сущностей:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/actions/ActionScreen.java[tags=table;enabledRule]
----