= Контейнеры данных

Контейнеры данных образуют тонкий слой между визуальными компонентами и моделью данных приложения. Они могут хранить один экземпляр или коллекцию экземпляров сущностей, предоставлять информацию о мета-классе сущности, ее представлении и выбранном экземпляре коллекции, а также регистрировать слушатели для различных событий экрана.

[plantuml]
....
@startuml

interface InstanceContainer {
}

interface CollectionContainer {
}

interface CollectionPropertyContainer {
}

interface InstancePropertyContainer {
}

interface Nested {
}

interface KeyValueContainer {
}

interface KeyValueCollectionContainer {
}

InstanceContainer ^-- KeyValueContainer
InstanceContainer ^-- CollectionContainer
InstanceContainer ^-- InstancePropertyContainer
KeyValueContainer ^-- KeyValueCollectionContainer
CollectionContainer ^-- KeyValueCollectionContainer
CollectionContainer ^-- CollectionPropertyContainer
Nested ^-- CollectionPropertyContainer
Nested ^-- InstancePropertyContainer

@enduml
....