= Контейнеры KeyValue

Контейнеры `KeyValueContainer` и `KeyValueCollectionContainer` предназначены для работы с сущностями типа xref:data-model:entities.adoc#key-value[KeyValueEntity]. Такая сущность может содержать произвольный набор атрибутов, задаваемый во время работы приложения.

`KeyValueContainer` и `KeyValueCollectionContainer` могут быть заданы декларативно в XML-дескрипторе экрана элементами `keyValueInstance` и `keyValueCollection`.

XML-описание контейнеров KeyValue должно содержать элемент `properties`, который задает атрибуты `KeyValueEntity` (то есть ключи и значения). Порядок вложенных элементов `property` должен соответствовать порядку колонок в результирующем наборе, возвращаемом запросом. Например, в следующем определении атрибут `customer` получит значение из колонки `o.customer`, а атрибут `sum` из колонки `sum(o.amount)`:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/data/order-browse-data.xml[tags=key-value-container]
----

Кроме того, можно настроить контейнеры KeyValue, используя их Java API, который содержит следующие методы:

* `addProperty()` - позволяет определить атрибуты сущности (ключи). Данный метод принимает имя атрибута и его тип в виде xref:data-model:data-types.adoc[Datatype] или Java-класса. В последнем случае класс должен быть либо сущностью, либо классом, поддерживаемым одним из типов данных (datatypes). Фреймворк использует этот метод при декларативном определении свойств контейнера KeyValue в XML, как описано выше.

* `setIdName()` опциональный метод, позволяющий назначить один из атрибутов идентификатором сущности. Это означает, что экземпляры `KeyValueEntity`, содержащиеся в данном контейнере, будут иметь идентификаторы, получаемые из данного атрибута. В противном случае экземпляры `KeyValueEntity` получают случайно сгенерированные UUIDs.

* `getEntityMetaClass()` возвращает динамическую реализацию интерфейса xref:data-model:metadata.adoc[MetaClass], которая представляет текущую схему экземпляров `KeyValueEntity`, заданную вызовами метода `addProperty()`.
