= Контейнеры свойств

Контейнеры `InstancePropertyContainer` и `CollectionPropertyContainer` предназначены для работы с единичными экземплярами и коллекциями экземпляров сущностей, которые являются атрибутами других сущностей.

Контейнеры свойств можно определить в XML-дескрипторе следующим образом:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/ui/ex1/screen/data/department-edit-data.xml[tags=property-container]
----
<1> `InstanceContainer` содержит экземпляр сущности `Department`, имеющей атрибут `employee`.
<2> `CollectionPropertyContainer` содержит коллекцию экземпляров сущности `Employee`, являющейся атрибутом сущности `Department`.

Также контейнер свойств можно создать программно:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/data/DepartmentEditData2.java[tags=property-container]
----

[[methods]]
== Методы

Контейнеры свойств (property containers) реализуют интерфейс `Nested`, в котором определены методы получения родительского контейнера и имя его дочернего атрибута, чтобы привязать к нему контейнер свойства. В примере с сущностями `Department` и `Employee` родительским контейнером будет тот, в котором хранится экземпляр `Department`.

`InstancePropertyContainer` работает напрямую с атрибутом родительской сущности. Это значит, что при вызове метода `setItem()` значение будет установлено для атрибута соответствующей родительской сущности, и будет вызван слушатель ее события `ItemPropertyChangeEvent`.

`CollectionPropertyContainer` содержит копию родительской коллекции. Ниже описаны его методы:

* `getMutableItems()` возвращает изменяемый список сущностей, и изменения списка отражаются на базовом свойстве. То есть, если вы удалите элемент из этого списка, базовый атрибут будет изменен, а для родительского контейнера будет вызван слушатель `ItemPropertyChangeEvent`.
* `getDisconnectedItems()` возвращает изменяемый список сущностей, но изменения списка не отражаются на базовом свойстве. То есть, если вы удалите элемент из этого списка, базовый атрибут останется неизменным.
* `setItems()` устанавливает коллекцию экземпляров сущностей для контейнера и его базового свойства. Слушатель `ItemPropertyChangeEvent` вызывается для родительского контейнера.
* `setDisconnectedItems()` устанавливает коллекцию экземпляров сущностей для контейнера, но базовый исходный атрибут останется неизменным.

Методы `getDisconnectedItems()` и `setDisconnectedItems()` можно использовать для временного изменения отображения коллекции в UI, например, для фильтрации таблицы:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ui/ex1/screen/data/DepartmentEditData.java[tags=filter]
----
