= Переводы фреймворка

Подсистемы фреймворка Jmix имеют в своем составе файлы `messages.properties`, содержащие сообщения на английском языке. Это означает, что даже если вы установите в проекте другой язык и переведете свои файлы сообщений, ваши пользователи все равно будут видеть части UI на английском языке, потому что они реализованы в фреймворке. Это относится к стандартным действиям и компонентам управления данными, таким как фильтры и таблицы, а также всем UI экранам безопасности и других подсистем.

Мы предоставляем переводы сообщений фреймворка на некоторые языки в виде _модулей перевода_. Модуль перевода – это набор файлов сообщений, запакованных в JAR, которые можно добавить в ваш проект как зависимость. Модули перевода можно найти в каталоге дополнений Jmix: откройте окно инструментов *Jmix* -> *Settings* -> *Marketplace* в Studio или перейдите на https://www.jmix.io/marketplace[веб-сайт каталога^] и отфильтруйте его по тегу *Localization*. На данный момент доступны переводы на немецкий, русский, румынский и упрощенный китайский.

Если необходимо перевести сообщения фреймворка на другой язык, можно сделать это прямо в проекте. Ниже приведен рекомендуемый способ:

* Клонируйте репозиторий https://github.com/jmix-framework/jmix[https://github.com/jmix-framework/jmix^] и выберите ветку, соответствующую версии Jmix, используемой в проекте.
* В зависимости от того, какие дополнения используются в вашем проекте, скопируйте все или некоторые файлы `messages.properties` из папки `jmix-translations/content` в те же пути в папке `src/main/resources` вашего проекта.
* Переименуйте файлы `messages.properties` в `messages_<your_language>.properties` и переведите сообщения.

NOTE: Если вы хотите внести свой вклад в перевод фреймворка, присылайте нам пул-реквесты с новыми языками или изменениями в существующих переводах!
