= Framework Translations

The Jmix framework subsystems come with `messages.properties` files containing messages in English. It means that even if you set a different locale in your project and translate your own message files, your users will still see parts of the UI in English because they are implemented in the framework. This includes standard actions and data management components like filter and tables, as well as the entire UI screens of the security and other subsystems.

We provide translations of the framework messages to some languages in the form of _translation modules_. A translation module is a set of message files packed together in a JAR that can be added to your project as a dependency. You can find the translation modules on the Jmix marketplace: open *Jmix* tool window -> *Settings* -> *Marketplace* in Studio or go to the https://www.jmix.io/marketplace[marketplace website^] and filter by the *Localization* tag. At the moment, German and Russian translations are available.

If you need to translate the framework messages to a different language, you can do it right in your project. Below is a recommended way to do it:

* Clone https://github.com/jmix-framework/jmix[https://github.com/jmix-framework/jmix^] repository and checkout a branch corresponding to the Jmix version used in your project.

* Depending on the set of add-ons used in your project, copy all or some of the `messages.properties` files from the `jmix-translations/content` folder to the same paths under your project's `src/main/resources` folder.
* Rename `messages.properties` files to `messages_<your_language>.properties` and translate the messages.

NOTE: If you like to contribute to the framework translations project, feel free to send us pull requests with new languages or changes in existing translations!
