= Пакеты сообщений

Наиболее частой задачей локализации является обеспечение сообщений, соответствующих текущему языку пользователя. Для этого сообщения должны быть извлечены из кода и помещены в специальные файлы свойств, по одному файлу на каждый язык. Коллекция таких файлов называется _пакетом сообщений_.

Помимо сообщений, пакет сообщений также может содержать xref:data-model:data-types.adoc#localized-format-strings[локализованные строки форматов].

Пакет сообщений проекта по умолчанию представляет собой набор файлов `messages_<language>.properties`, расположенных в базовом пакете в папке `src/main/resources`.

CAUTION: Файлы пакетов сообщений должны иметь кодировку UTF-8.

[[setting-locales]]
== Настройка локалей

При создании нового проекта в Studio вы можете настроить список поддерживаемых языков в поле *Locales* мастера проекта. Это поле позволяет выбрать код языка и задать его название.

Studio записывает список кодов языков в свойство приложения `jmix.core.available-locales`, а названия языков - в соответствующие файлы `messages_<language>.properties` с ключом `localeDisplayName.<language>`. Позже вы можете отредактировать эти свойства вручную или использовать вкладку *Locales* окна *Project Properties* в Studio.

Например, если для приложения определено два языка: `en` - `English` и `ru` - `Русский`, в проекте будет следующая структура файлов (при условии, что базовым пакетом является `localization_demo.ex1`):

[source, text]
----
 src/
    main/
        resources/
            localization_demo/
                ex1/
                    messages_en.properties
                    messages_ru.properties
            application.properties
----

И файлы будут иметь следующее содержимое:

.messages_en.properties
[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=localeDisplayName]
----

.messages_ru.properties
[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_ru.properties[tags=localeDisplayName]
----

.application.properties
[source,properties]
----
include::example$/ex1/src/main/resources/application.properties[tags=availableLocales]
----

[[creating-messages]]
== Создание сообщений

[[group-and-key]]
=== Группа и ключ

Обычно приложение содержит один пакет сообщений. Поскольку количество сообщений даже в простом приложении может быть довольно большим, рекомендуется создавать ключи свойств из двух частей: группы и ключа сообщения, разделенных косой чертой (`/`). Это позволяет группировать связанные сообщения и избегать конфликтов имен. В следующем примере `localization_demo.ex1.screen.main` - это группа, а `application.caption` - это ключ сообщения:

[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=structure]
----

Также можно определить сообщение без группы, например:

[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=structure-2]
----

[[localizing-data-model]]
=== Локализация модели данных

Jmix вводит некоторые правила локализации элементов модели данных, таких как имена сущностей и атрибутов, значения перечисления. Это позволяет фреймворку находить локализованные имена при отображении сущностей и перечислений в компонентах UI.

Имя сущности локализуется в формате `<package>/<class>`, имя атрибута - в формате `<package>/<class>.<attribute>`. Например:

[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=entity]
----

Имя перечисления локализуется в формате `<package>/<class>`, значение перечисления - в формате `<package>/<class>.<value>`. Например:

[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=enum]
----

TIP: Локализованные имена элементов модели данных можно легко создавать в визуальных дизайнерах Studio. Нажмите кнопку 🌐 (глобус) рядом с именем элемента и введите локализованные значения для доступных языков в диалоговом окне *Localized Message*.

[[additional-bundles]]
=== Дополнительные пакеты

Для того, чтобы придерживаться разумного размера файлов свойств в масштабном приложении с большим количеством сообщений, можно определить дополнительные пакеты:

. Создайте набор файлов свойств с произвольным именем в любом каталоге раздела `src/main/resources`. В приведенном ниже примере файлы `additional_messages` созданы в том же базовом пакете приложения, что и основной пакет сообщений:
+
[source]
----
 src/
    main/
        resources/
            localization_demo/
                ex1/
                    additional_messages_en.properties
                    additional_messages_ru.properties
                    messages_en.properties
                    messages_ru.properties
----

. Запишите локализованные сообщения в дополнительные файлы так же, как и в основном пакете.

. Добавьте аннотацию `@MessageSourceBasenames` к классу приложения и укажите в ней путь и имя дополнительного пакета:
+
[source,java,indent=0]
----
include::example$/ex1/src/main/java/localization_demo/ex1/LocalizationExampleApplication.java[tags=additional-bundle]
----

CAUTION: Сообщения из всех пакетов приложения загружаются в единый список, поэтому ключи свойств должны быть уникальными среди всех пакетов.

[[using-messages]]
== Использование сообщений

[[using-messages-in-java]]
=== В коде Java

Чтобы получать локализованные сообщения из пакета сообщений, используйте бин `Messages`. Наиболее распространенным вариантом использования является вызов его метода `getMessage()` и предоставление группы сообщений и ключа. Метод вернет сообщение для текущего пользовательского языка или заданного ключа, если сообщение не найдено.

В следующем примере определим сообщение в пакете сообщений и получим его, используя различные методы бина `Messages`:

.messages_en.properties
[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=using-messages]
----

[source,java,indent=0]
----
include::example$/ex1/src/test/java/localization_demo/ex1/MessagesTest.java[tags=using-messages-1]
----

Все три метода возвращают одно и то же значение: `Something has happened`.

<1> Ключ свойства задан целиком.
<2> Группа и ключ сообщения заданы отдельно.
<3> Если первым аргументом является `Class`, метод использует пакет класса как группу.

Существует также перегруженный метод `getMessage()`, принимающий `Enum`. Используйте его для извлечения локализованного значения перечисления, например:

[source,java,indent=0]
----
include::example$/ex1/src/test/java/localization_demo/ex1/MessagesTest.java[tags=using-messages-enum]
----

[[using-messages-in-ui]]
=== В экранах UI

Дескрипторы экрана и файлы конфигурации меню UI распознают префикс `msg://` в сообщениях и загружают их из пакета сообщений.

Рассмотрим различные варианты использования `msg://` с примерами.

. Группа сообщения выводится из пакета экрана.
+
--
Например, если сообщение определено с группой `localization_demo.ex1.screen.user`:

.messages_en.properties
[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=screen]
----

Его можно получить в дескрипторе экрана, расположенном в пакете `localization_demo.ex1.screen.user`, просто указав ключ сообщения без группы:

.localization_demo/ex1/screen/user/user-browse.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/screen/user/user-browse.xml[tags=message-1]
----
--

. Получение сообщения с произвольной группой.
+
--
Сообщение из предыдущего примера можно получить на любом экране, указав группу и ключ после префикса `msg://`, например:

.localization_demo/ex1/screen/main/main-screen.xml
[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/screen/main/main-screen.xml[tags=message]
----
--

. Получение сообщения без группы.
+
--
Чтобы получить сообщение без группы, следует поставить тройную косую черту в префиксе `msg:///`, за которым следует ключ сообщения.

Например, если сообщение определено так:

[source,properties]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/messages_en.properties[tags=structure-2]
----

То его можно получить в любом дескрипторе экрана следующим образом:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/localization_demo/ex1/screen/user/user-browse.xml[tags=message-2]
----
--
