= Свойства REST

Свойства Jmix REST позволяют настраивать различные аспекты поведения конечных точек универсального REST.

[[entities-api-properties]]
== Entities API


[[jmix.rest.default-max-fetch-size]]
=== jmix.rest.default-max-fetch-size

Определяет максимальное количество экземпляров сущностей, возвращаемых API по умолчанию.

Значение по умолчанию: `10000`


[[jmix.rest.entity-max-fetch-size]]
=== jmix.rest.entity-max-fetch-size

Определяет максимальное количество экземпляров сущности, возвращаемых API для конкретной сущности по умолчанию.

В следующем примере настраивается значение `entityMaxFetchSize` для двух сущностей. Для всех остальных сущностей используется значение из <<jmix.rest.default-max-fetch-size>>.

[source,properties]
----
jmix.rest.entity-max-fetch-size.sample_Product = 500
jmix.rest.entity-max-fetch-size.sample_Customer = 1000
----


[[jmix.rest.json-transformation-config]]
=== jmix.rest.json-transformation-config

Определяет файл, содержащий список конфигураций преобразований JSON, которые использует REST API, когда клиенту нужны данные в формате определенной версии модели данных.

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

// TODO: [MD] link to configuration directory description once it is available in the docs

Значение по умолчанию: `none`

[[jmix.rest.max-upload-size]]
=== jmix.rest.max-upload-size

Определяет максимальный размер файла (в байтах), который можно загрузить с помощью REST API.

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

Значение по умолчанию: `20971520` (20 Mb)

[[jmix.rest.optimistic-locking-enabled]]
=== jmix.rest.optimistic-locking-enabled

Включает оптимистическую блокировку сущностей, если атрибут версии указан в JSON.

Значение по умолчанию: `false`

[[jmix.rest.queries-config]]
=== jmix.rest.queries-config

Определяет файл, содержащий список запросов JPQL, доступных как часть xref:rest:entities-api/load-entities.adoc#load-list-jpql[Entities API].

[source,properties]
----
jmix.rest.queries-config = rest/sample/rest-queries.xml
----

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

// TODO: [MD] link to configuration directory description once it is available in the docs

Значение по умолчанию: `none`

[[jmix.rest.services-config]]
=== jmix.rest.services-config

Определяет файл, содержащий список методов сервиса, предоставляемых через xref:rest:business-logic.adoc#services-api[Services API].

[source,properties]
----
jmix.rest.services-config = rest/sample/rest-services.xml
----

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

// TODO: [MD] link to configuration directory description once it is available in the docs

Значение по умолчанию: `none`


[[jmix.rest.response-fetch-plan-enabled]]
=== jmix.rest.response-fetch-plan-enabled

Если установлено значение true, параметр `responseFetchPlan` с именем фетч-плана может передаваться в запросах на создание и обновление. В этом случае созданная/обновленная сущность перезагружается с указанным фетч-планом и возвращается как часть ответа JSON.

Если установлено значение false, ответ содержит JSON с минимальным представлением созданной/обновленной сущности.

Значение по умолчанию: `true`


[[security-properties]]
== Безопасность

См. раздел xref:security:custom-endpoints.adoc#application-properties[Безопасность: Кастомные эндпойнты] для получения информации о свойствах приложения, влияющих на эндпойнты REST.