= REST Properties

Jmix REST properties allow you to configure different aspects of the behavior of the generic REST endpoints.

TIP: https://doc.cuba-platform.com/restapi-7.2/#rest_api_v2_settings

TIP: https://doc.cuba-platform.com/restapi-7.2/#app_properties

[[entities-api-properties]]
== Entities API


[[jmix.rest.default-max-fetch-size]]
=== jmix.rest.default-max-fetch-size

Defines the default maximum amount of entity instances that are returned by the API.

Default value: `10000`


[[jmix.rest.entity-max-fetch-size]]
=== jmix.rest.entity-max-fetch-size

Defines the default maximum amount of entity instances that are returned by the API for a particular entity.

The following example configures the `entityMaxFetchSize` value for two entities. For all other entites the value from <<jmix.rest.default-max-fetch-size, jmix.rest.default-max-fetch-size>> is taken into consideration.

[source,properties]
----
jmix.rest.entity-max-fetch-size.sample_Product = 500
jmix.rest.entity-max-fetch-size.sample_Customer = 1000
----


[[jmix.rest.json-transformation-config]]
=== jmix.rest.json-transformation-config

Property defining a file that contains a list of JSON transformations configurations used by the REST API when the client needs data in the format of some particular data model version.

The file is loaded using the Resources interface, so it can be located in the classpath or the configuration directory.

// TODO: [MD] link to configuration directory description once it is available in the docs

Default value: `none`

[[jmix.rest.max-upload-size]]
=== jmix.rest.max-upload-size

Maximum file size (in bytes) that can be uploaded with the REST API.

The file is loaded using the `Resources` interface, so it can be located in the classpath or the configuration directory.

Default value: `20971520` (20 Mb)

[[jmix.rest.optimistic-locking-enabled]]
=== jmix.rest.optimistic-locking-enabled

Enables optimistic locking of entities with optimistic locking if the version attribute is provided in JSON.

Default value: `false`

[[jmix.rest.queries-config]]
=== jmix.rest.queries-config

Property defining a file that contains a list of JPQL queries available as part of the xref:rest:entities-api/load-entities.adoc#_load_entities_via_jpql[Entities API].

[source,properties]
----
jmix.rest.queries-config = rest/sample/rest-queries.xml
----

The file is loaded using the Resources interface, so it can be located in the classpath or the configuration directory.

// TODO: [MD] link to configuration directory description once it is available in the docs

Default value: `none`

[[jmix.rest.services-config]]
=== jmix.rest.services-config

Property defining a file that contains a list of Service methods that are exposed via the xref:rest:business-logic.adoc#_services_api[Services API].

[source,properties]
----
jmix.rest.services-config = rest/sample/rest-services.xml
----

The file is loaded using the Resources interface, so it can be located in the classpath or the configuration directory.

// TODO: [MD] link to configuration directory description once it is available in the docs

Default value: `none`


[[jmix.rest.response-fetch-plan-enabled]]
=== jmix.rest.response-fetch-plan-enabled

If set to true, the `responseFetchPlan` parameter with the fetch plan name can be passed in the create and update requests. In this case, the created/updated entity is reloaded with the specified fetch plan and returned as part of the response JSON.

If set to false, the response contains JSON with a minimal representation of the created/updated entity.

Default value: `true`


[[security-properties]]
== Security

[[jmix.security.oauth2.client-id]]
=== jmix.security.oauth2.client-id

Defines an identifier of the REST API client. In this case, the client is not a platform user, but an application (some web portal or mobile app) that uses REST API. Client credentials are used for basic authentication when accessing the REST API token endpoint.

Default value: `client`

CAUTION: This value should be changed to some application specific random, long and non-guessable string.


[[jmix.security.oauth2.client-secret]]
=== jmix.security.oauth2.client-secret

Defines the secret for the REST API client. In this case, the client is not a platform user, but an application (some web portal or mobile app) that uses REST API. Client credentials are used for basic authentication when accessing the REST API token endpoint.

The application property value in addition to the actual password value (e.g., `secret`), must contain an identifier of the Password Encoder (e.g., `\{noop\}`). More information about the Password Encoder Mechanism can be found in the {spring-security-api}/org/springframework/security/crypto/password/DelegatingPasswordEncoder.html[Spring Security documentation^].

NOTE: When the Token retrieval request is send for authentication, the Password Encoder identifier must not be part of the request value. Only `secret` is part of the request.

Default value: `\{noop\}secret`

CAUTION: This value should be changed to some application specific random, long and non-guessable string.

[[jmix.rest.anonymous-url-patterns]]
=== jmix.rest.anonymous-url-patterns

Defines a comma-separated list of URL https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[patterns^], which should allow xref:rest:security/authentication.adoc#anonymous-access[anonymous access].

Default value: `none`

[[jmix.rest.authenticated-url-patterns]]
=== jmix.rest.authenticated-url-patterns

Defines a comma-separated list of URL https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[patterns^] of xref:rest:business-logic.adoc#custom-controller[custom controllers] that require the standard OAuth2 authentication.

Default value: `none`



