= REST 配置

Jmix REST 应用程序属性支持配置通用 REST 不同方面的行为。

[[entities-api-properties]]
== 实体 API

[[jmix.rest.default-max-fetch-size]]
=== jmix.rest.default-max-fetch-size

定义 API 返回实体实例数量的默认最大值。

默认值：`10000`

[[jmix.rest.entity-max-fetch-size]]
=== jmix.rest.entity-max-fetch-size

定义 API 返回特定实体实例数量的默认最大值。

下面示例中，为两个实体配置了 `entityMaxFetchSize`。所有其他实体则会使用 <<jmix.rest.default-max-fetch-size, jmix.rest.default-max-fetch-size>> 配置的值。

[source,properties]
----
jmix.rest.entity-max-fetch-size.sample_Product = 500
jmix.rest.entity-max-fetch-size.sample_Customer = 1000
----


[[jmix.rest.json-transformation-config]]
=== jmix.rest.json-transformation-config

定义包含一组 JSON 转换配置的文件，由 REST API 在客户端需要某些特定版本格式的数据时使用。

通过 Resources 接口加载，因此文件可位于 classpath 或者配置文件夹中。

// TODO: [MD] link to configuration directory description once it is available in the docs

默认值：`none`

[[jmix.rest.max-upload-size]]
=== jmix.rest.max-upload-size

定义 REST API 支持上传的文件大小的最大值（单位为字节）。


默认值：`20971520`（20 MB）

[[jmix.rest.optimistic-locking-enabled]]
=== jmix.rest.optimistic-locking-enabled

如果 JSON 中提供了 `version` 属性，则启用实体乐观锁。

默认值：`false`

[[jmix.rest.queries-config]]
=== jmix.rest.queries-config

定义包含 JPQL 查询语句的文件，JQPL 查询语句用于 xref:rest:entities-api/load-entities.adoc#_load_entities_via_jpql[实体 API]。

[source,properties]
----
jmix.rest.queries-config = rest/sample/rest-queries.xml
----

通过 Resources 接口加载，因此文件可位于 classpath 或者配置文件夹中。

// TODO: [MD] link to configuration directory description once it is available in the docs

默认值：`none`

[[jmix.rest.services-config]]
=== jmix.rest.services-config

定义包含一组服务方法的文件，这些服务方法开放为 xref:rest:business-logic.adoc#_services_api[服务 API]。

[source,properties]
----
jmix.rest.services-config = rest/sample/rest-services.xml
----

通过 Resources 接口加载，因此文件可位于 classpath 或者配置文件夹中。

// TODO: [MD] link to configuration directory description once it is available in the docs

默认值：`none`


[[jmix.rest.response-fetch-plan-enabled]]
=== jmix.rest.response-fetch-plan-enabled

如果设置为 `true`，则可以在创建和更新请求中使用 `responseFetchPlan` 参数指定 fetch plan 名称。此时，创建/更新后的实体使用参数指定的 fetch plan 加载后以 JSON 格式返回。

如果设置为 `false`，返回体仅包含创建/更新后实体的最简单内容。

默认值：`true`

[[security-properties]]
== 安全

参阅 xref:security:custom-endpoints.adoc#application-properties[安全：自定义端点] 部分了解如何为 REST 端点配置应用程序属性。
