= CORS

Из соображений безопасности браузеры не разрешают сетевые вызовы JavaScript к ресурсам за пределами текущего источника. Cross-Origin Resource Sharing или CORS снимает это ограничение, поскольку позволяет указать разрешенные междоменные запросы.

По умолчанию все запросы к REST API из разных источников разрешены. Чтобы ограничить список источников, определите свойство приложения xref:ROOT:app-properties.adoc#jmix.cors.allowed-origins[jmix.cors.allowed-origins] и другие xref::app-properties.adoc#cors[свойства CORS].

Настройки CORS автоматически применяются к следующим URL-адресам:

* `/oauth/**`
* Шаблоны URL, определенные в свойстве xref:authorization-server:protecting-resources.adoc#protecting-rest-api-endpoints[jmix.resource-server.authenticated-url-patterns].

Если вы хотите применить настройки CORS к другому URL-адресу, определите следующий бин (это можно сделать в основном классе приложения):

[source,java,indent=0]
----
include::example$/ex1/src/main/java/rest/sample/RestEx1Application.java[tags=custom-cors]
----

Чтобы заменить предоставленную Jmix конфигурацию CORS по умолчанию, зарегистрируйте бин с именем `corsConfigurationSource` в своем проекте. В этом случае упомянутые выше свойства работать не будут.

Дополнительные сведения о CORS см. в {spring-security-doc}/servlet/integrations/cors.html[документации по безопасности Spring^].