= CORS

For security reasons, browsers don't allow JavaScript network calls to resources outside the current origin. Cross-Origin Resource Sharing or CORS solves this restriction, as it lets you specify which cross-domain requests are allowed.

By default, all cross-origin requests to the REST API are allowed. To restrict the origins list you can define the xref:ROOT:app-properties.adoc#jmix.cors.allowed-origins[jmix.cors.allowed-origins] application property and other xref::app-properties.adoc#cors[CORS properties].

CORS settings are automatically applied to the following URLs:

* `/rest/**`
* `/oauth/**`
* URL patterns defined in xref:app-properties.adoc#jmix.rest.authenticated-url-patterns[jmix.rest.authenticated-url-patterns] property.

If you want to apply the CORS settings to another URL path, define the following bean (you can do it in the main application class):

[source,java,indent=0]
----
include::example$/ex1/src/main/java/rest/sample/RestEx1Application.java[tags=custom-cors]
----

In order to replace the default CORS configuration provided by Jmix, register a bean with the `corsConfigurationSource` name in your project. In this case, the properties mentioned above will not work.

Refer to {spring-security-doc}/servlet/integrations/cors.html[Spring Security Documentation^] for more information on CORS.