= Generic Functionality

== Entity Interactions

=== Read Operations

==== Getting Entity Instance List

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_get_entities_list


Let's suppose that the system has a `rstex11_Order` entity and we need to get a list of this entity instances. Besides, we need to get not all the records, but only 5 records, starting with the 10th one. A response must contain not only simple properties of the `rstex11_Order` entity but also an information about the order customer (a reference field named `customer`). Orders must be sorted by date.

A base URL for getting all instances of the `rstex11_Order` entity is as follows:

`\http://localhost:8080/rest/entities/rstex11_Order`

To implement all the conditions described above the following request parameters must be specified:

* *fetchPlan* - a {manual}/fetchPlans.html[fetchPlan], that will be used for loading entities. In our case the `order-with-details` contains a `customer` reference.
* *limit* - a number of instances to be returned.
* *offset* - a position of the first extracted record.
* *sort* - an entity attribute name that will be used for sorting. `+attribute` for ascending order (optional), `-attribute` for descending order.

An OAuth token must be put in the `Authorization` header with the `Bearer` type:

  Authorization: Bearer 29bc6b45-83cd-4050-8c7a-2a8a60adf251

The following *GET* request URL contains the parameters for fetching the correct data:

`http://localhost:8080/rest/entities/rstex11_Order?fetchPlan=order-with-details&limit=50&offset=5&sort=+date`

[source, bash]
----
curl -H "Authorization: Bearer d335902c-9cb4-455e-bf92-24ca1d66d72f" http://localhost:8080/app/rest/v2/entities/rstex11_Order?view=order-with-details&limit=5&offset=10&sort=+date
----

The corresponding JSON response contains the orders with additional attributes sorted by `date`:

[source, json]
----
[
  {
    "_entityName": "rstex11_Order",
    "_instanceName": "rest.sample.entity.Order-21021f78-edac-224b-e6f8-6e71e02a0f0d [detached]",
    "id": "21021f78-edac-224b-e6f8-6e71e02a0f0d",
    "date": "2020-12-13",
    "amount": 49.99,
    "createdDate": "2021-02-06T12:03:38.049",
    "createdBy": "admin",
    "lastModifiedDate": "2021-02-06T12:03:38.049",
    "lines": [
      {
        "_entityName": "rstex11_OrderLine",
        "_instanceName": "rest.sample.entity.OrderLine-64e4fbb0-7fd6-818b-984e-a8769c4fbe88 [detached]",
        "id": "64e4fbb0-7fd6-818b-984e-a8769c4fbe88",
        "product": {
          "_entityName": "rstex11_Product",
          "_instanceName": "Outback Power Remote Power System",
          "id": "7750adbe-6c30-cede-31a6-577a1a96aa83",
          "name": "Outback Power Remote Power System"
        },
        "quantity": 1.0,
        "createdDate": "2021-02-06T12:03:38.049",
        "createdBy": "admin",
        "lastModifiedDate": "2021-02-06T12:03:38.049",
        "version": 1
      }
    ],
    "version": 1,
    "customer": {
      "_entityName": "rstex11_Customer",
      "_instanceName": "Sidney Chandler",
      "id": "0826806e-6074-90fa-f241-564b5c94d018",
      "createdDate": "2021-02-06T12:00:53.72",
      "createdBy": "admin",
      "lastModifiedDate": "2021-02-06T12:00:53.72",
      "name": "Sidney Chandler",
      "version": 1
    }
  },
  {
    "_entityName": "rstex11_Order",
    "_instanceName": "rest.sample.entity.Order-41aae331-b46b-85ee-b0bc-2de8cbf1ab86 [detached]",
    "id": "41aae331-b46b-85ee-b0bc-2de8cbf1ab86",
    "date": "2021-02-02",
    "amount": 283.55,
    "createdDate": "2021-02-06T12:04:37.372",
    "createdBy": "admin",
    "lastModifiedDate": "2021-02-06T12:04:37.372",
    "lines": [
      {
        "_entityName": "rstex11_OrderLine",
        "_instanceName": "rest.sample.entity.OrderLine-d89df652-9d06-8d3e-2f26-5387e96e5b5d [detached]",
        "id": "d89df652-9d06-8d3e-2f26-5387e96e5b5d",
        "product": {
          "_entityName": "rstex11_Product",
          "_instanceName": "Cotek Battery Charger",
          "id": "1ed85c7a-89f1-c339-a738-16307ed6003a",
          "name": "Cotek Battery Charger"
        },
        "quantity": 1.0,
        "createdDate": "2021-02-06T12:04:37.372",
        "createdBy": "admin",
        "lastModifiedDate": "2021-02-06T12:04:37.372",
        "version": 1
      },
      {
        "_entityName": "rstex11_OrderLine",
        "_instanceName": "rest.sample.entity.OrderLine-7ccd45ec-8878-2a4a-2c24-b5ac053b6d4c [detached]",
        "id": "7ccd45ec-8878-2a4a-2c24-b5ac053b6d4c",
        "product": {
          "_entityName": "rstex11_Product",
          "_instanceName": "Solar-One HUP Flooded Battery 48V",
          "id": "1860904a-5444-9c3e-9dc1-1d7a26d9ac19",
          "name": "Solar-One HUP Flooded Battery 48V"
        },
        "quantity": 1.0,
        "createdDate": "2021-02-06T12:04:37.372",
        "createdBy": "admin",
        "lastModifiedDate": "2021-02-06T12:04:37.372",
        "version": 1
      }
    ],
    "version": 1,
    "customer": {
      "_entityName": "rstex11_Customer",
      "_instanceName": "Shelby Robinson",
      "id": "bd1c8e90-3d35-cbe2-9efd-167202c758d2",
      "name": "Shelby Robinson",
      "version": 1
    }
  }
]
----

NOTE: Every entity in the response has a `_entityName` attribute with the name of the entity and an `_instanceName` attribute with the xref:data-model:entities.adoc#instance-name[Instance Name] of the entity.

==== Getting Entity by ID

TIP: new

==== Using Entity Search Filter

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_search_filter

==== Getting Instance via JPQL

===== Predefined JPQL Query Configuration
TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_queries_config

===== Executing JPQL Query (GET)
TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_query_get

===== Executing JPQL Query (POST)
TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_query_post

=== Write Operation

==== New Entity Instance Creation

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_create_entity

==== Existing Entity Instance Update

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_update_entity



== File Interactions

=== Downloading Files

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_file_download

=== Uploading Files

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_file_upload


== Metadata

=== Localized Messages

TIP: https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_localized_messages

=== Permissions

TIP: https://files.cuba-platform.com/swagger/7.1/#/Permissions


=== User Info

TIP: https://files.cuba-platform.com/swagger/7.1/#/UserInfo


=== Model Introspection

TIP: https://files.cuba-platform.com/swagger/7.1/#/Metadata
