= Generic Functionality

The Generic REST API comes with different built-in functionalities to interact with a Jmix application:

* <<Metadata,Metadata>> Endpoints for introspection of various information, like data-model descriptions, information about the current user and their permission or localized messages.


== Metadata

=== Localized Messages

When interacting with a frontend application (like a React UI or a mobile app), it is often needed to display localised messages of the application. As those translated values are already defined in the Jmix `.messages` files, the Messages API provides the ability to exposing those values through the REST API.

There are the following endpoints that you can use to retrieve translated messages:

`/messages/entities`:: Translation for the entity name and attributes of all entities
`/messages/entities/:entityName`:: Translation for the entity name and attributes of the given entity
`/messages/enums`:: Translation for the enum name and values of all enums
`/messages/enums/:enumClassName`:: Translation for the enum name and values of the given enum

In the following example, you can see how to request translated values for the `CustomerType` enum through the API:

[source, http request]
.Messages for `CustomerType` Request
----
GET http://localhost:8080/rest
            /messages
            /enums
            /rest.sample.entity.CustomerType
----

[source,json]
.Response: 200 - OK
----
{
  "rest.sample.entity.CustomerType": "CustomerType",
  "rest.sample.entity.CustomerType.BUSINESS": "Business",
  "rest.sample.entity.CustomerType.PRIVATE": "Private"
}
----

It is also possible to explicitly request translated messages for a given locale by setting the `Accept-Language` header. In the following example, you can see how to request german translations for the `CustomerType` enum:

[source, http request]
.Translated Message for `CustomerType` Request
----
GET http://localhost:8080/rest
            /messages
            /enums
            /rest.sample.entity.CustomerType
Accept-Language: de
----

[source,json]
.Response: 200 - OK
----
{
  "rest.sample.entity.CustomerType": "Kundentyp",
  "rest.sample.entity.CustomerType.BUSINESS": "Geschäftskunde",
  "rest.sample.entity.CustomerType.PRIVATE": "Privatkunde"
}
----


=== Permissions

TIP: https://files.cuba-platform.com/swagger/7.1/#/Permissions


=== User Info

TIP: https://files.cuba-platform.com/swagger/7.1/#/UserInfo


=== Model Introspection

TIP: https://files.cuba-platform.com/swagger/7.1/#/Metadata
