= Универсальный REST

Jmix предоставляет универсальный REST API, который позволяет работать с сущностями модели данных и сервисами бизнес-логики без написания собственных REST-контроллеров на бэкенде. Универсальный REST автоматически предоставляет конечные точки (endpoints) для следующей функциональности:

* CRUD-операции с сущностями.
* Вызов зарегистрированных методов сервисов.
* Выполнение преднастроенных запросов JPQL.
* Загрузка и выгрузка файлов.
* Предоставление информации о модели данных.
* Предоставление информации о текущем пользователе и его правах.

NOTE: Конечные точки универсального REST можно изучить, используя Swagger UI по адресу {rest-api-open-api}{page-component-display-version}[{rest-api-open-api}{page-component-display-version}^]

REST API использует протокол OAuth2 для аутентификации и поддерживает также анонимный доступ. Все конечные точки REST API ограничивают доступ к данным в соответствии с настройками xref:security:index.adoc[подсистемы безопасности].

[[installation]]
== Установка

Универсальный REST API поставляется как опциональное дополнение. Для его автоматической установки через маркетплейс Jmix обратитесь к инструкции в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Чтобы установить дополнение вручную, добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$/rest-ex1/build.gradle[tags=dependencies]
----
