= Generic REST

Jmix provides a generic REST API that allows you to work with data model entities and business services without writing REST controllers on the backend. It automatically exposes endpoints for the following functionality:

* CRUD operations on entities.
* Calling of registered service methods.
* Execution of predefined JPQL queries.
* Uploading and downloading files.
* Returning information about the data model.
* Returning information about the current user and their permissions.

REST API uses the OAuth2 protocol for authentication and supports anonymous access. All REST API endpoints respect data access constraints imposed by xref:security:index.adoc[security].

NOTE: xref:frontend-ui:index.adoc[] works with Jmix backend through the generic REST API.

[[installation]]
== Installation

To include REST API in your application, add the following line to the `dependencies` section of your `build.gradle` file:

[source,java,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----

