= Безопасность

При использовании REST API ваше клиентское приложение должно работать в соответствии с разрешениями и ограничениями конкретного пользователя. Jmix связывает вызовы API с пользователем и применяет к запросам обычные возможности Jmix по xref:security:authorization.adoc[контролю доступа].

REST API поддерживает множество механизмов безопасности, доступных через xref:security:index.adoc[подсистему безопасности] Jmix. Кроме того, он добавляет такие специфичные для API функции, как OAuth2, для защиты взаимодействий через API.

[[predefined-roles]]
== Предопределенные роли

*REST: minimal access* (`rest-minimal`): позволяет пользователям взаимодействовать с приложением через API.

[[cors]]
== CORS

Из соображений безопасности браузеры не разрешают сетевые вызовы JavaScript к ресурсам за пределами текущего источника. Cross-Origin Resource Sharing или CORS снимает это ограничение, поскольку позволяет указать разрешенные междоменные запросы.

По умолчанию все запросы к REST API из разных источников разрешены. Чтобы ограничить список источников, определите свойство приложения xref:ROOT:app-properties.adoc#jmix.cors.allowed-origins[jmix.cors.allowed-origins] и другие xref::app-properties.adoc#cors[свойства CORS].

Настройки CORS автоматически применяются к следующим URL-адресам:

* `/rest/**`
* `/oauth/**`
* Шаблоны URL, определенные в свойстве xref:app-properties.adoc#jmix.rest.authenticated-url-patterns[jmix.rest.authenticated-url-patterns].

Если вы хотите применить настройки CORS к другому URL-адресу, определите следующий бин (это можно сделать в основном классе приложения):

[source,java,indent=0]
----
include::example$/ex1/src/main/java/rest/sample/RestEx1Application.java[tags=custom-cors]
----

Чтобы заменить предоставленную Jmix конфигурацию CORS по умолчанию, зарегистрируйте бин с именем `corsConfigurationSource` в своем проекте. В этом случае упомянутые выше свойства работать не будут.

Дополнительные сведения о CORS см. в {spring-security-doc}/servlet/integrations/cors.html[документации по безопасности Spring^].