= Resources

The `io.jmix.core.Resources` interface is a central infrastructure API for loading resources from different locations.

It is useful when application code or framework configuration needs to load files that can be supplied either from the classpath or from the external configuration directory.

[[resource-locations]]
== Resource Locations

`Resources` searches for a resource according to the following rules:

. If the location is a URL, the resource is loaded from this URL.
. If the location starts with the `classpath:` prefix, the resource is loaded from the classpath.
. If the location is not a URL and does not start with `classpath:`, Jmix first searches for the file in the directory specified by the xref:ROOT:app-properties.adoc#jmix.core.conf-dir[jmix.core.conf-dir] application property, using the provided location as a relative path.
. If the file is not found in the configuration directory, Jmix searches for it in the classpath.

In practice, resources are usually loaded either from the external configuration directory or from the classpath. A file in the configuration directory overrides a classpath resource with the same location.

[[loading-resources]]
== Loading Resources

Inject `Resources`:

[source,java]
----
@Autowired
private Resources resources;
----

Use `getResourceAsStream()` to get an `InputStream` for the resource. The method returns `null` if the resource is not found. Close the stream after use:

[source,java,indent=0]
----
include::example$/features-ex1/src/main/java/com/company/demo/view/document/DocumentDetailView.java[tags=resources-example]
----

Use `getResourceAsString()` to load the resource content as a UTF-8 string. The method returns `null` if the resource is not found:

[source,java]
----
String content = resources.getResourceAsString("com/company/demo/sample.txt");
----

[[getting-spring-resource]]
== Getting Spring Resource

Because `Resources` extends Spring's `ResourceLoader`, you can also use `getResource()` when you need a `org.springframework.core.io.Resource` object:

[source,java]
----
Resource resource = resources.getResource("classpath:com/company/demo/sample.txt");
----