= Storing Files in Database

In this section, we will give an example of uploading and saving images to the application database. In addition, we will describe how images can be displayed in Jmix UI views.

CAUTION: Save only small files in the database: thumbnails, icons, etc., because the whole file is placed in memory when it is uploaded or downloaded.

Firstly, create an attribute of the byte array (`byte[]`) type in your entity, for example:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/entity/Person.java[tags=file]
----

When you run the application, Studio generates a database migration script for creating a corresponding column of the type appropriate for your database. For example, for PostgreSQL it is `bytea`.

For uploading the file from a user interface, use the xref:flow-ui:vc/components/fileUploadField.adoc[] component bound to the entity attribute. If the file is an image, you can use the xref:flow-ui:vc/html-components/image.adoc[] component to display the image in the view. For example:

[source,xml,indent=0]
----
include::example$/files-ex1/src/main/resources/com/company/demo/view/person/person-detail-view.xml[tags=file]
----

<1> `fileUploadField` component allows users to upload a file and store it in an entity attribute.
<2> `image` component displays the content of the entity attribute.

If you want to be able to download the file, add a button and define its click handler as follows:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/person/PersonDetailView.java[tags=file]
----

<1> Use the xref:downloading-files.adoc#downloader[Downloader] bean to download files.
<2> Define the downloaded file name.
<3> If you know the file format, specify it in the last argument of the `download()` method. Depending on the format, the web browser either downloads the file or shows it in a tab.
