= Хранение файлов в базе данных

// todo Explain how to upload/download files in REST when https://github.com/Haulmont/jmix-core/issues/200 is fixed

В этом разделе приводится пример загрузки и сохранения изображений в базу данных приложения, а также описывается, как можно отображать изображения на экранах UI.

CAUTION: Сохраняйте в базу данных только небольшие файлы: миниатюры, значки и т.д., так как при загрузке или скачивании в память помещается весь файл.

Во-первых, создайте атрибут типа байтового массива (`byte[]`) в сущности, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/files/ex1/entity/Person.java[tags=file]
----

При запуске приложения Studio генерирует скрипт миграции базы данных для создания соответствующего столбца подходящего базе типа. Например, для PostgreSQL это `bytea`.

Для загрузки файла из экрана UI используйте компонент xref:ui:vcl/components/file-upload-field.adoc[], привязанный к атрибуту сущности. Если файл является изображением, можно использовать компонент xref:ui:vcl/components/image.adoc[] для его отображения на экране. Например:

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/files/ex1/screen/person/person-edit.xml[tags=file-1;file-2]
----

<1> Компонент `FileUploadField` позволяет пользователям загружать файл и сохранять его в атрибуте сущности.
<2> Компонент `Image` отображает содержимое атрибута сущности.

Для того, чтобы иметь возможность скачивать файл, добавьте кнопку и определите ее обработчик следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/files/ex1/screen/person/PersonEdit.java[tags=file]
----

<1> Используйте бин `Downloader` для скачивания файлов.
<2> Определите имя скачанного файла.
<3> Если вы знаете формат файла, укажите его в последнем аргументе метода `download()`. В зависимости от формата веб-браузер будет либо скачивать файл, либо отображать его во вкладке.
