= Загрузка файлов

В этом разделе объясняется, как загружать файлы с компьютера пользователя с помощью компонентов пользовательского интерфейса. Сведения о том, как загружать файлы через REST API, см. в разделе xref:rest:files-api.adoc[Files API].

[[file-upload-components]]
== Компоненты загрузки файлов

Jmix предлагает набор UI-компонентов для загрузки файлов. Все они содержат кнопку, которая при нажатии открывает диалоговое окно файловой системы для выбора файлов. Вот краткий обзор различий между компонентами. Более подробная информация о каждом компоненте приведена в соответствующих разделах.

* xref:flow-ui:vc/components/fileUploadField.adoc[] позволяет пользователям выбрать один файл и сохранить его в виде массива байтов в атрибут сущности. Пользователи также могут получить доступ к содержимому файла напрямую из значения компонента, не связывая его с сущностью.

* xref:flow-ui:vc/components/fileStorageUploadField.adoc[] позволяет пользователям выбрать один файл и сохранить его в xref:file-storage.adoc[файловом хранилище]. Значение компонента - объект `FileRef`. Пользователи могут связать компонент с атрибутом сущности типа `FileRef`, чтобы автоматически сохранять ссылку на файл в базу данных.

* xref:flow-ui:vc/components/upload.adoc[] позволяет пользователям загружать один или несколько файлов одновременно. Он предоставляет основу для обработки загрузки файлов, но не взаимодействует непосредственно с сущностями или системами хранения.

[[using-temporary-storage]]
== Использование TemporaryStorage

Компонент `fileStorageUploadField` имеет атрибут xref:flow-ui:vc/components/fileStorageUploadField.adoc#fileStoragePutMode[fileStoragePutMode] со значением по умолчанию `IMMEDIATE`. Если установить его в `MANUAL`, компонент загружает файл во временное хранилище в файловой системе приложения и дает вам полный контроль над загруженным файлом. Его можно передать в файловое хранилище как есть, предварительно обработать его, а также сделать все, что вам нужно, вообще не сохраняя его в файловом хранилище.

// todo fileMultiUploadField
// То же самое и с компонентом xref:ui:vcl/components/file-multi-upload-field.adoc[FileMultiUploadField]: он просто загружает файлы во временное хранилище и уведомляет ваш код о завершении загрузки.

Интерфейс `TemporaryStorage` предоставляет API для создания временных файлов, сохранения их в хранилище файлов или их удаления.

Ниже приведен пример использования `fileStorageUploadField` в ручном режиме для переноса загруженного файла из временного в файловое хранилище.

[source,xml,indent=0]
----
include::example$/files-ex1/src/main/resources/com/company/demo/view/files/files-view.xml[tags=put-mode-manual]
----

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/files/FilesView.java[tags=temporary-storage-1;temporary-storage-2]
----
<1> Получение локального файла из временного хранилища, используя идентификатор, предоставляемый объектом события.
<2> Перенос локального файла в файловое хранилище.

Метод `putFileIntoStorage()` также удаляет временный локальный файл.

Если вам нужно только локально обработать файл, не сохраняя его в файловое хранилище, используйте метод `deleteFile()` интерфейса `TemporaryStorage` после работы с файлом, например:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/files/FilesView.java[tags=get-and-delete]
----

Во временном хранилище накапливаются файлы, которые по разным причинам не были удалены. Поэтому он предоставляет JMX-интерфейс для удаления старых неиспользуемых файлов.

// todo flowui JMXConsole
// Его можно найти по имени *jmix.ui:type=TemporaryStorage* на экране *Administration -> JMX Console*.

У MBean есть метод `clearTempDirectory()`, который удаляет все файлы старше 2 дней из временного каталога приложения (`.jmix/temp` по умолчанию). Вы можете вызывать этот метод вручную или периодически использовать задание xref:quartz:index.adoc[Quartz]. Для этого в задании нужно внедрить компонент `TemporaryStorageManagementFacade` и вызвать его метод `clearTempDirectory()`.
