= Загрузка файлов

В этом разделе объясняется, как загружать файлы с компьютера пользователя с помощью компонентов пользовательского интерфейса. Сведения о том, как загружать файлы через REST API, см. в разделе xref:rest:files-api.adoc[Files API].

[[file-upload-components]]
== Компоненты загрузки файлов

Jmix предоставляет набор компонентов UI для загрузки файлов. Все они содержат кнопку, при нажатии которой открывается диалоговое окно файловой системы для выбора файлов. Ниже приводится краткое объяснение различий между компонентами. Полная информация о компонентах представлена в соответствующих разделах.

* xref:ui:vcl/components/file-upload-field.adoc[] позволяет выбрать один файл и сохранить его как массив байтов в атрибуте сущности. Также вы можете получить содержимое файла прямо из значения компонента, не связывая его с сущностью.

* xref:ui:vcl/components/file-storage-upload-field.adoc[] позволяет выбрать один файл и сохранить его в xref:file-storage.adoc[хранилище файлов]. Значением компонента является объект `FileRef`. Вы можете связать этот компонент с атрибутом сущности `FileRef` типа для автоматического сохранения ссылки на файл в базе данных.

* xref:ui:vcl/components/file-multi-upload-field.adoc[] позволяет выбрать сразу несколько файлов и загрузить их во  <<using-temporary-storage,временное хранилище>> на сервере.  Затем вы можете обработать их и/или перенести в постоянное файловое хранилище.

`FileUploadField` и `FileStorageUploadField` могут отображать имя загруженного файла рядом с кнопкой. Имя файла также служит ссылкой для скачивания.

`FileUploadField` и `FileStorageUploadField` могут иметь «зону перетаскивания» и «зону вставки» для загрузки файлов путем перетаскивания или вставки с клавиатуры.

[[using-temporary-storage]]
== Использование TemporaryStorage

Компонент `FileStorageUploadField` имеет атрибут xref:ui:vcl/components/file-storage-upload-field.adoc#file-storage-put-mode[fileStoragePutMode] со значением по умолчанию `IMMEDIATE`. Если установить его в `MANUAL`, компонент загружает файл во временное хранилище в файловой системе приложения и дает вам полный контроль над загруженным файлом. Его можно передать в файловое хранилище как есть, предварительно обработать его, а также сделать все, что вам нужно, вообще не сохраняя его в файловом хранилище.

То же самое и с компонентом xref:ui:vcl/components/file-multi-upload-field.adoc[FileMultiUploadField]: он просто загружает файлы во временное хранилище и уведомляет ваш код о завершении загрузки.

Интерфейс `TemporaryStorage` предоставляет API для создания временных файлов, сохранения их в хранилище файлов или их удаления.

Ниже приведен пример использования `FileStorageUploadField` в ручном режиме для переноса загруженного файла из временного в файловое хранилище.

[source,xml,indent=0]
----
include::example$/ex1/src/main/resources/files/ex1/screen/files/files-screen.xml[tags=put-mode-manual]
----
<1> Установите для компонента `fileStoragePutMode="MANUAL"`.

[source,java,indent=0]
----
include::example$/ex1/src/main/java/files/ex1/screen/files/FilesScreen.java[tags=temporary-storage-1;temporary-storage-2]
----
<1> Получение локального файла из временного хранилища, используя идентификатор, указанный в поле.
<2> Перенос локального файла в файловое хранилище.

Метод `putFileIntoStorage()` также удаляет временный локальный файл.

Если вам нужно только локально обработать файл, не сохраняя его в файловое хранилище, используйте метод `deleteFile()` интерфейса `TemporaryStorage` после работы с файлом, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/files/ex1/screen/files/FilesScreen.java[tags=get-and-delete]
----

Во временном хранилище накапливаются файлы, которые по разным причинам не были удалены. Поэтому он предоставляет JMX-интерфейс для удаления старых неиспользуемых файлов. Его можно найти по имени *jmix.ui:type=TemporaryStorage* на экране *Administration -> JMX Console*. У MBean есть метод `clearTempDirectory()`, который удаляет все файлы старше 2 дней из временного каталога приложения (`.jmix/temp` по умолчанию). Вы можете вызывать этот метод вручную или периодически использовать задание xref:quartz:index.adoc[Quartz]. Для этого в задании нужно внедрить компонент `TemporaryStorageManagementFacade` и вызвать его метод `clearTempDirectory()`.
